### ISSUE TITLE
Connect Event parameters

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#10]
Am I doing this right?:

    var list = widgets.NewQListWidget(nil)
    list.ConnectKeyPressEvent(func(event *gui.QKeyEvent) { keyPressEvent(event) })
...

    func keyPressEvent(event *gui.QKeyEvent) { ... }

**Comment by therecipe** [comment]
Hey

Yes, you are doing it right.
But, it's currently not possible to override virtual functions/events in parent classes.

So you can override the `keyPressEvent` in `QWidget`, but not in `QListWidget`.
I also stated some other limitations here: https://github.com/therecipe/qt/issues/9

```go
package main

import (
	"os"

	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	var widget = widgets.NewQWidget(nil, 0)
	widget.ConnectKeyPressEvent(keyPressEvent)
	widget.Show()

	widgets.QApplication_Exec()
}

func keyPressEvent(event *gui.QKeyEvent) {
	println("keyPressEvent:", event.Text())
}
```

I'm going to look into this now, maybe I will find a simple way to fix this.

**Comment by therecipe** [comment]
Okay, I pushed the changes.

This should work now:

```go
package main

import (
	"os"

	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	var listWidget = widgets.NewQListWidget(nil)
	listWidget.AddItems([]string{"some", "test", "labels"})
	listWidget.ConnectKeyPressEvent(keyPressEvent)
	listWidget.Show()

	widgets.QApplication_Exec()
}

func keyPressEvent(event *gui.QKeyEvent) {
	println("keyPressEvent:", event.Text())
}
```

But there are still some limitations, like not being able to call the default virtual implementation.
Feel free to ask, if you need some other functions added.

**Comment by 5k3105** [comment]
Wow. That was fast. Thank you for your help.
