### ISSUE TITLE
qtsetup seems to expect $GOPATH/bin instead of $GOBIN

### ISSUE THREAD

**Issue by justinfx** [therecipe/qt#100]
When running the intial `qtsetup`, it failed because it assumes that `$GOBIN` == `$GOPATH/bin`, but on my own system I point `$GOBIN` to a common path location. If this is indeed the case, I would think it would be good to first check if `$GOBIN` is set, and if not, fallback on `$GOPATH/bin`

Example failure:

```
> echo $GOPATH/bin
/Users/justin/src/go/bin
> echo $GOBIN
/Users/justin/bin
> $GOBIN/qtsetup     
...
PANI[3237] failed to test widgets/line_edits
error: 
cmd: &{/Users/justin/src/go/bin/qtdeploy [/Users/justin/src/go/bin/qtdeploy test desktop /Users/justin/src/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits ] []  <nil>   [] <nil> <nil> <nil> <nil> <nil> false [0xc425460060 0xc425460078 0xc425460078] [0xc425460060 0xc425460078] [0xc425460070] [0x6efa0] <nil> <nil>}  error="fork/exec /Users/justin/src/go/bin/qtdeploy: no such file or directory"
panic: (*logrus.Entry) (0x1c8d60,0xc424254a50)
```

**Comment by therecipe** [comment]
Hey

Fixed it as you suggested, qtsetup is now aware of GOBIN and will fallback to GOPATH/bin with https://github.com/therecipe/qt/commit/0ffd648614d6f2637d823202496f3956f5fcd9f8

**Comment by justinfx** [comment]
That fixed it! Thanks for the quick turn around
