### ISSUE TITLE
undefined: NewQSystemTrayIconWithCustomSlot

### ISSUE THREAD

**Issue by esrrhs** [therecipe/qt#1001]
Hi,
when I compile this example  [qt/internal/examples/widgets/systray/systray.go] on windows, it has error: undefined: NewQSystemTrayIconWithCustomSlot
Is windows not support?

**Comment by moson-mo** [comment]
How did you build it? Use "qtdeploy build". That will generate the moc files as well which will contain the code for "NewQSystemTrayIconWithCustomSlot"

**Comment by esrrhs** [comment]
ok, I will try it

**Comment by esrrhs** [comment]
@moson-mo it work, thanks
