### ISSUE TITLE
Fast build fails due to permission error

### ISSUE THREAD

**Issue by svartkanin** [therecipe/qt#1004]
I have followed the instructions to install `qt` here https://github.com/therecipe/qt/wiki/Installation-on-Linux (both approaches, the global one and the per project one).

The building process works successfully when running

`qtdeploy -uic=false build`

However, that takes quite long to execute. It will even rebuild the app if there have not been any code changes at all. 
I've tried using the `-fast` flag described in the help to see if that would speed things up, but I received an error 

```
$ qtdeploy -uic=false -fast build
...
error="exit status 1" name="build for linux on linux"
go build runtime/internal/sys: open /usr/lib/go-1.13/pkg/linux_amd64/runtime/internal/sys.a: permission denied
go build math/bits: open /usr/lib/go-1.13/pkg/linux_amd64/math/bits.a: permission denied
go build container/list: open /usr/lib/go-1.13/pkg/linux_amd64/container/list.a: permission denied
go build encoding: open /usr/lib/go-1.13/pkg/linux_amd64/encoding.a: permission denied
go build unicode/utf16: open /usr/lib/go-1.13/pkg/linux_amd64/unicode/utf16.a: permission denied
go build unicode: open /usr/lib/go-1.13/pkg/linux_amd64/unicode.a: permission denied
go build unicode/utf8: open /usr/lib/go-1.13/pkg/linux_amd64/unicode/utf8.a: permission denied
go build runtime/internal/atomic: open /usr/lib/go-1.13/pkg/linux_amd64/runtime/internal/atomic.a: permission denied
go build internal/cpu: open /usr/lib/go-1.13/pkg/linux_amd64/internal/cpu.a: permission denied
go build internal/race: open /usr/lib/go-1.13/pkg/linux_amd64/internal/race.a: permission denied
go build sync/atomic: open /usr/lib/go-1.13/pkg/linux_amd64/sync/atomic.a: permission denied
go build runtime/cgo: open /usr/lib/go-1.13/pkg/linux_amd64/runtime/cgo.a: permission denied
```
Do I need special permissions for the files in `/usr/lib/go-1.13/pkg/linux_amd64/...`?

**Comment by therecipe** [comment]
Hey

Could you maybe try to remove https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/build.go#L78-L80 and then re-build the tools with `go install -tags=no_env github.com/therecipe/qt/cmd/...`?

Also btw, you can also just use the plain `go build` and `go run .` commands to compile your application during the development.
