### ISSUE TITLE
What idea do you use to write golang (therecipe/qt) ?..

### ISSUE THREAD

**Issue by adneg** [therecipe/qt#1006]
What idea do you use to write golang (therecipe/qt) ?..

I am currently using liteide. 
I don't like working with qml in liteide. 

what are you using?

**Comment by amlwwalker** [comment]
vscode with all the plugins....

**Comment by therecipe** [comment]
I'm using Sublime Text with GoSublime and the QML package.
But I would probably use the Qt Creator for bigger Qml projects.

In the future you can probably use the Qt Creator for Go projects as well, but the last time I tried it with Go's language server (https://github.com/golang/tools/tree/master/gopls) things weren't really stable.

**Comment by adneg** [comment]
Thanks. Vscode is not for me. I'm going to try Sublime..
