### ISSUE TITLE
Advice on making a game

### ISSUE THREAD

**Issue by amlwwalker** [therecipe/qt#1009]
I want to make a game, specifically a backgammon game. I.e a player drags pieces around a board and places them in legal positions. The computer then plays it's move against the player.
My thinking is each piece on the board has an ID and each possible position on the board has an ID. When each piece is generated it is given its ID and starting position. When a player moves it, it's position ID is updated.
I know that's extremely vague, but I'm not convinced I know how I would code that - and by that I mean, would you generate the go objects that represent pieces first and then they render on the board or would you generate them in qml and send IDs back to go? I.e does go only have knowledge of IDs?
I haven't seen much in the way of how games are made so I'm quite new to that, this question is really high level I know but I hoped someone could shed some ideas on how to approach something like this.

**Comment by therecipe** [comment]
Hey

It's been a while since I tinkered with gamedev, but what you probably want to use is an
[Entity system](https://en.wikipedia.org/wiki/Entity_component_system). I would probably create something like this:

```go
package main

import (
	"os"
	"time"

	"github.com/google/uuid"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/quick"
	"github.com/therecipe/qt/widgets"
)

func init() {
	Piece_QmlRegisterType2("CustomQmlTypes", 1, 0, "PieceInternal")
	Board_QmlRegisterType2("CustomQmlTypes", 1, 0, "BoardInternal")
}

var pieces = make(map[string]*Piece)

type Piece struct {
	quick.QQuickItem

	_ func() `constructor:"init"`

	_ string `property:"ID"`

	_ func(newX, newY float64) `signal:"moveTo"`
	_ func(newColor string)    `signal:"changeColor"`

	speed float64
}

func (p *Piece) init() {
	p.SetID(uuid.New().String()[:4])
	pieces[p.ID()] = p

	p.speed = 1 + (float64(len(pieces)) / 10)

	go func() {
		t := time.NewTicker(100 * time.Millisecond)
		for range t.C {
			p.MoveTo(p.X()+(1*p.speed), p.Y())

			if p.X()+p.Width() >= board.Width() {
				p.ChangeColor("green")
				t.Stop()
			}
		}
	}()
}

var board *Board

type Board struct {
	quick.QQuickItem
	_ func() `constructor:"init"`
}

func (b *Board) init() {
	board = b
}

func main() {
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)

	widgets.NewQApplication(len(os.Args), os.Args)

	view := quick.NewQQuickView(nil)
	view.SetResizeMode(quick.QQuickView__SizeRootObjectToView)
	view.SetSource(core.NewQUrl3("qrc:/qml/main.qml", 0))
	view.Show()

	widgets.QApplication_Exec()
}
```

`qml/main.qml`
```qml
import QtQuick 2.13
import CustomQmlTypes 1.0

BoardInternal {
	width: 250
	height: 250

	Rectangle {
		anchors.fill: parent

		color: "blue"

		Piece {
			x: 0
			y: 0
		}

		Piece {
			x: 0
			y: 55
		}

		Piece {
			x: 0
			y: 110
		}

		Piece {
			x: 0
			y: 165
		}
	}
}
```

`qml/Piece.qml`
```qml
import QtQuick 2.13
import QtQuick.Controls 2.13
import CustomQmlTypes 1.0

PieceInternal {
	id: piece

	onMoveTo: { x = newX; y = newY; }
	onChangeColor: rect.color = newColor;

	width: 50
	height: 50

	Rectangle {
		id: rect

		anchors.fill: parent
		color: "red"

		Label {
			anchors.centerIn: parent
			text: piece.ID
		}
	}
}
```

But you will probably need to calculate the proper x and y coordinates on the fly, if you want to be able to resize the window. (Or don't work with coordinates at all an instead just re-parent the pieces from one field to another, and simply let the fields auto-scale by using anchors and such)

Also maybe take a look here: https://felgo.com/doc/felgo-entity-concept/
If you don't want to use Felgo, then you can at least get some inspiration for a possible api design.

Also maybe https://github.com/rashwell/neochessqt which is widgets based, but maybe interesting nevertheless.

**Comment by amlwwalker** [comment]
Blimey! That was fast! Thanks, I need to read about entity systems! Sweet - I thought there would be a tried and tested approach. Looking forward to this project. This Qt binding has resulted in me having about 10 projects running simultanesously! I need to focus 😂 
I'll comment for others once I have made some progress, thanks!
