### ISSUE TITLE
QMenu.addAction is missing overloads with single QAction and with QWidgetAction

### ISSUE THREAD

**Issue by tomasger** [therecipe/qt#1014]
Quoting [QMenu](https://doc.qt.io/qt-5/qmenu.html#actions) documentation:

> Widgets can be inserted into menus with the QWidgetAction class. Instances of this class are used to hold widgets, and are inserted into menus with the addAction() overload that takes a QAction.

However, `QMenu.addAction` is missing that kind of an overload. Furthermore, it would be nice if QMenu would have an overload to insert a single `QAction` type, now the only way to insert a QAction to a menu is by making a slice and passing it to `QMenu.addActions()`.

**Comment by therecipe** [comment]
Hey

It's unfortunate, but the function you are looking for is simply overshadowed by QMenu.
But it's available for the QWidget class, where it originates from.
To access it from a QMenu object, you can use something like: `(*QMenu).QWidget.AddAction()`

So something like this should work:
```go
menu := widgets.NewQMenu(nil)
wa := widgets.NewQWidgetAction(nil)
wa.SetDefaultWidget(widgets.NewQPushButton(nil))y
menu.QWidget.AddAction(wa)
```

**Comment by tomasger** [comment]
Thank you for clearing that out, I didn't take notice of QWidget field in QMenu. That solves my issue.
