### ISSUE TITLE
Functions numbering difference in OS

### ISSUE THREAD

**Issue by waqasraz** [therecipe/qt#1015]
I was developing in Linux and everything was working fine but when I setup on windows and try to compile I started getting issues like this

```
client\extras\extras.go:83:76: cannot use "" (type string) as type core.QBitArray_ITF in argument to core.NewQVariant14:
        string does not implement core.QBitArray_ITF (missing QBitArray_PTR method)

.\main.go:39:27: too many arguments in call to gui.NewQPixmap5
        have (string, string, core.Qt__ImageConversionFlag)
        want (gui.QPixmap_ITF)

```

I had to change NewQVariant14 to NewQVariant15 and NewQPixmap5 to NewQPixmap4

**Comment by therecipe** [comment]
Hey

Did you use QT_PKG_CONFIG on linux?
It could be that your were using a different api version on linux than you were using on windows.
To check your api version on linux you can run `$(go env GOPATH)/bin/qtsetup check`, then simply run the equivalent on windows and see if the versions match or differ.

In case they differ, you can use the `QT_API` env var like this `QT_API=5.12.0`, to change the api version before running qtdeploy or qtsetup.

**Comment by waqasraz** [comment]
Yes I've set QT_API on linux and ran the setup, now it's fine. Thank you.
