### ISSUE TITLE
 can not install qt?

### ISSUE THREAD

**Issue by busgo** [therecipe/qt#1029]
```shell

INFO[0119] running: 'qtsetup install darwin' [docker=false] [vagrant=false] 
INFO[0119] installing full qt/core                      
vendor/github.com/therecipe/qt/core/core.go:11:2: no Go files in /Users/apple/Desktop/wp/code/home/bus/vendor/github.com/therecipe/qt

ERRO[0119] failed to install 'core'; aborting setup     
cpe-172-100-11-203:bus apple$ 


```

**Comment by therecipe** [comment]
Hey

Did you vendor "therecipe/qt" with "go dep" or something?
If yes, then I'm sorry, vendoring this package (without using go modules) isn't supported atm.

The only supported way to vendor this package, is to use go modules.
But I will look into this, once I find some time.

**Comment by busgo** [comment]
> Hey
> 
> Did you vendor "therecipe/qt" with "go dep" or something?
> If yes, then I'm sorry, vendoring this package (without using go modules) isn't supported atm.
> 
> The only supported way to vendor this package, is to use go modules.
> But I will look into this, once I find some time.

I use  "go mod "

**Comment by dev-drprasad** [comment]
@busgo I facing same issue. How did you resolve it ?
