### ISSUE TITLE
DataChanged is cause of errors

### ISSUE THREAD

**Issue by MK5555** [therecipe/qt#1030]
The problem is this: there is a table in which data is periodically added, it is necessary to display them as soon as they appear.  But when I used DataChanged the app crashed. 
`
`package main

import (
	"os"
	"strconv"
	"time"

	"github.com/therecipe/qt/core"

	"github.com/therecipe/qt/widgets"
)

func main() {
	//нужно для создания приложения
	qApp := widgets.NewQApplication(len(os.Args), os.Args)
	//создать окно
	window := widgets.NewQMainWindow(nil, 0)
	widget := widgets.NewQWidget(nil, 0)
	window.SetCentralWidget(widget)
	window.SetMinimumSize2(500, 500)
	window.SetWindowTitle("beta version")
	widget.SetLayout(widgets.NewQVBoxLayout())
	button := widgets.NewQPushButton2("start", nil)
	widget.Layout().AddWidget(button)
	table := formTable(widget)

	button.ConnectClicked(func(bool) {

		fillTable(table, qApp)
	})
	//table

	window.Show()
	qApp.Exec()
}

const (
	role1 = int(core.Qt__UserRole) + 1<<iota
	role2
)

func formTable(widget *widgets.QWidget) (table *widgets.QTableWidget) {
	table = widgets.NewQTableWidget(nil)
	table.SetColumnCount(2)
	table.SetRowCount(1)
	fill := widgets.NewQTableWidgetItem2("Столбец 1", 0)
	table.SetItem(0, 0, fill)
	fill = widgets.NewQTableWidgetItem2("Столбец 2", 0)
	table.SetItem(0, 1, fill)
	table.HorizontalHeader().SetSectionResizeMode2(0, widgets.QHeaderView__ResizeToContents)
	table.HorizontalHeader().SetSectionResizeMode2(1, widgets.QHeaderView__ResizeToContents)
	widget.Layout().AddWidget(table)
	return table
}

func fillTable(table *widgets.QTableWidget, qApp *widgets.QApplication) {
	var k int = 1
	for i := 0; i < 6; i++ {
		if k <= table.RowCount() {
			table.SetRowCount(table.RowCount() + 1)
		}
		fill1 := widgets.NewQTableWidgetItem2(strconv.Itoa(i), 0)
		fill2 := widgets.NewQTableWidgetItem2(strconv.Itoa(i*i), 0)
		table.SetItem(k, 0, fill1)
		table.SetItem(k, 1, fill2)
		var topLeft core.QModelIndex_ITF
		var bottomRight core.QModelIndex_ITF
		topLeft.QModelIndex_PTR().Sibling(i, 1)
		bottomRight.QModelIndex_PTR().Sibling(i, 1)

		table.DataChanged(topLeft, bottomRight, []int{role1, role2})
		// qApp.ProcessEvents(core.QEventLoop__AllEvents)
		k++
		time.Sleep(100 * time.Millisecond)
	}
}
`
`

**Comment by akiyosi** [comment]
You shouldn't use the hoge_ITF type to create a variable of a certain type. I think this is an abstract interface type used by qt binding's internal code.
Try the following code:

```
package main

import (
	"os"
	"strconv"
	"time"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

func main() {
	qApp := widgets.NewQApplication(len(os.Args), os.Args)
	window := widgets.NewQMainWindow(nil, 0)
	widget := widgets.NewQWidget(nil, 0)
	window.SetCentralWidget(widget)
	window.SetMinimumSize2(500, 500)
	window.SetWindowTitle("beta version")
	widget.SetLayout(widgets.NewQVBoxLayout())
	button := widgets.NewQPushButton2("start", nil)
	widget.Layout().AddWidget(button)
	table := formTable(widget)

	button.ConnectClicked(func(bool) {

		fillTable(table, qApp)
	})

	window.Show()
	qApp.Exec()
}

const (
	role1 = int(core.Qt__UserRole) + 1<<iota
	role2
)

func formTable(widget *widgets.QWidget) (table *widgets.QTableWidget) {
	table = widgets.NewQTableWidget(nil)
	table.SetColumnCount(2)
	table.SetRowCount(1)
	fill := widgets.NewQTableWidgetItem2("Столбец 1", 0)
	table.SetItem(0, 0, fill)
	fill = widgets.NewQTableWidgetItem2("Столбец 2", 0)
	table.SetItem(0, 1, fill)
	table.HorizontalHeader().SetSectionResizeMode2(0, widgets.QHeaderView__ResizeToContents)
	table.HorizontalHeader().SetSectionResizeMode2(1, widgets.QHeaderView__ResizeToContents)
	widget.Layout().AddWidget(table)
	return table
}

func fillTable(table *widgets.QTableWidget, qApp *widgets.QApplication) {
	var k int = 1
	for i := 0; i < 6; i++ {
		if k <= table.RowCount() {
			table.SetRowCount(table.RowCount() + 1)
		}
		fill1 := widgets.NewQTableWidgetItem2(strconv.Itoa(i), 0)
		fill2 := widgets.NewQTableWidgetItem2(strconv.Itoa(i), 0)
		table.SetItem(k, 0, fill1)
		table.SetItem(k, 1, fill2)
		// var topLeft core.QModelIndex_ITF
		// var bottomRight core.QModelIndex_ITF
		topLeft := core.NewQModelIndex()
		bottomRight := core.NewQModelIndex()

		topLeft.QModelIndex_PTR().Sibling(i, 1)
		bottomRight.QModelIndex_PTR().Sibling(i, 1)

		table.DataChanged(topLeft, bottomRight, []int{role1, role2})
		// qApp.ProcessEvents(core.QEventLoop__AllEvents)
		k++
		time.Sleep(100 * time.Millisecond)
	}
}
```

**Comment by akiyosi** [comment]
@MK5555 
Did you solve it?

**Comment by MK5555** [comment]
This works (Sorry that I did not reply for a while), but I don’t understand why the data in the table is not updated during the cycle, but display only after it completes. Therefore, I am using a not very correct solution with qApp.ProcessEvents(core.QEventLoop__AllEvents).

**Comment by MK5555** [comment]
@akiyosi 
This works (Sorry that I did not reply for a while) , but I don’t understand why the data in the table is not updated during the loop, but display only after it is completed. Therefore, I am using a not very correct solution with qApp.ProcessEvents(core.QEventLoop__AllEvents) that data updata during the loop.
