### ISSUE TITLE
[Question] Fast track version vs Official version install

### ISSUE THREAD

**Issue by gioboske** [therecipe/qt#1032]
Hi all,
could someone explain which are the main differences if installing the "Fast track version" or the "Official version" as reported [here](https://github.com/therecipe/qt/wiki/Installation-on-macOS) for macOS?

In particular: when one of the installation methods is suggested over the other one?

Thank you.

**Comment by therecipe** [comment]
Hey

The "fast track version" was created to make
`go get github.com/therecipe/qt/cmd/... && $(go env GOPATH)/bin/qtsetup`
work out of the box, and is basically the "official version" minus the debug binaries and some of the Qt tools.

I would suggest that unless you need the full Qt debug binaries with debug symbols and/or you want to use the Qml debugger/profiler, that the "fast track" version is good enough for most needs.

**Comment by gioboske** [comment]
Thanks for the clarification!

**Comment by gioboske** [comment]
Closing the issue, since your reply perfectly answers the initial question.
