### ISSUE TITLE
Combining OpenCV and QML Image Question

### ISSUE THREAD

**Issue by TheApeMachine** [therecipe/qt#1042]
Hello,

I am working on an application that uses OpenCV to grab frames from a Raspberry Pi camera, and I would like to display those frames in a QT window.
If I understand things correctly I should be using an Image to display those frames?

I am using QML to define the UI for my application, but I am a little confused on how to interact with the QML elements, specifically how I could overwrite the image data of an Image element.

I am using the Gallery example from the QML folder as a jumping off point, and I am just looking now to overwrite the Image (logo) in that example with my video frames.
Any pointers?

**Comment by amlwwalker** [comment]
I can help a bit here I think.
I am assuming that you are saving images from OpenCV somewhere, and then want to set the path of an image to that path?

Without any code I can't elaborate on it, but I can tell you that from Go, you can set a property on a struct like:

```
type aController struct {
	quick.QQuickItem
	_ string          `property:"filepath"`
...
}
```
then from qml you can just access the property called `filepath`.

In go you can set the filepath as above like

```
aC := NewAController(nil)
aC.SetFilepath("/file/path")
```

you can reset it as many times as you like, and the QML will pick it up. Then in qml

```
Image {
id: filepath
...
}
```

If however its a stream of video, there is probably a better Qt object to display a video stream.

**Comment by TheApeMachine** [comment]
Hi @amlwwalker,

Actually I should have specified that I am not working with saved images, I am streaming from a camera video stream, so I am looking to get those frames displayed as a video stream on the GUI.

**Comment by amlwwalker** [comment]
So thats a slightly different problem then. In this case there are some examples that can lead you to some good clues. Some code snippets (or a repo) would help to be able to give you more support, but in the meantime, I would look at

https://github.com/therecipe/qt/blob/c8497dbdcf68bd7ac2733a2d854ffda7f4fc7696/internal/examples/3rdparty/qzxing/demo/QZXingLive/main.qml#L56
https://doc.qt.io/qt-5/qml-qtmultimedia-video.html
and the search results here https://github.com/therecipe/qt/search?q=QtMultimedia+Video&unscoped_q=QtMultimedia+Video

**Comment by therecipe** [comment]
Hey

I looked into this and created a small example here: https://github.com/therecipe/qt/tree/master/internal/examples/qml/gocv

It works by using a QQuickPaintedItem to display the frames.
To use it you can simply copy the gocv.go file into your project and then use then use it from Qml like it's shown here: https://github.com/therecipe/qt/blob/master/internal/examples/qml/gocv/qml/app.qml

To compile the example just run something like `qtrcc && qtmoc && go run -v .`
(qtdeploy might break the application, because it fails to deploy the OpenCV dependencies)

Also btw, if you don't manipulate the frames with OpenCV then using something like this here, as @amlwwalker suggested, is probably more performant: https://github.com/therecipe/qt/blob/c8497dbdcf68bd7ac2733a2d854ffda7f4fc7696/internal/examples/3rdparty/qzxing/demo/QZXingLive/main.qml#L47-L59

**Comment by amlwwalker** [comment]
There maybe some useful stuff in here aswell https://github.com/chili-epfl/qml-cvcamera

**Comment by amlwwalker** [comment]
I had a play with this. Its' quite cool :)

I tried to modify your example @therecipe to use the facedetection capabilities [outlined here](https://github.com/hybridgroup/gocv/blob/master/cmd/facedetect/main.go)

Here is the code I used to modify gocv.go

```
package main

import (
	"fmt"
	"image"
	"image/color"
	"sync"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/quick"
	"gocv.io/x/gocv"
)

func init() {
	GoCV_QmlRegisterType2("CustomModule", 1, 0, "GoCV")
}

type GoCV struct {
	quick.QQuickPaintedItem

	_ func() `constructor:"init"`

	image *gui.QImage
	data  []byte
	mutex *sync.Mutex
}

func (p *GoCV) init() {
	xmlFile := "./facedetect.xml"
	//setup gocv
	webcam, _ := gocv.OpenVideoCapture(0)
	// prepare image matrix
	img := gocv.NewMat()

	//setup painting
	p.image = gui.NewQImage()
	p.mutex = new(sync.Mutex)
	p.SetRenderTarget(quick.QQuickPaintedItem__FramebufferObject)
	p.ConnectPaint(p.paint)

	// color for the rect when faces detected
	blue := color.RGBA{0, 0, 255, 0}

	// load classifier to recognize faces
	classifier := gocv.NewCascadeClassifier()
	defer classifier.Close()

	if !classifier.Load(xmlFile) {
		fmt.Printf("Error reading cascade file: %v\n", xmlFile)
		return
	}

	go func() {
		for {
			webcam.Read(&img)
			if img.Empty() {
				fmt.Println("empty, continuing")
				continue
			}
			p.mutex.Lock()
			// detect faces
			rects := classifier.DetectMultiScale(img)
			fmt.Printf("found %d faces\n", len(rects))

			// draw a rectangle around each face on the original image,
			// along with text identifing as "Human"
			for _, r := range rects {
				gocv.Rectangle(&img, r, blue, 3)

				size := gocv.GetTextSize("Human", gocv.FontHersheyPlain, 1.2, 2)
				pt := image.Pt(r.Min.X+(r.Min.X/2)-(size.X/2), r.Min.Y-2)
				gocv.PutText(&img, "Human", pt, gocv.FontHersheyPlain, 1.2, blue, 2)
			}

			p.data, _ = gocv.IMEncode(".jpg", img)
			p.mutex.Unlock()
			p.UpdateDefault()
		}
	}()
}

func (p *GoCV) paint(painter *gui.QPainter) {
	p.mutex.Lock()
	p.image.LoadFromData(p.data, len(p.data), "JPG")
	p.mutex.Unlock()

	painter.DrawImage6(core.NewQRect4(0, 0, int(p.Width()), int(p.Height())), p.image)
}

```

However it causes a segmentation fault, although the gocv one works fine. The error is

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x750e9db]

runtime stack:
runtime.throw(0x439cd7b, 0x2a)
	runtime/panic.go:774 +0x72
runtime.sigpanic()
	runtime/signal_unix.go:378 +0x47c

goroutine 52 [syscall]:
runtime.cgocall(0x42c4fe0, 0xc000035e40, 0xc000462300)
	runtime/cgocall.go:128 +0x5b fp=0xc000035e10 sp=0xc000035dd8 pc=0x40146ab
gocv.io/x/gocv._Cfunc_CascadeClassifier_DetectMultiScale(0x0, 0x1de25a50, 0x0, 0x0)
	_cgo_gotypes.go:1071 +0x4d fp=0xc000035e40 sp=0xc000035e10 pc=0x4251c4d
gocv.io/x/gocv.(*CascadeClassifier).DetectMultiScale.func1(0xc000451fe8, 0x1de25a50, 0x0, 0x0)
	gocv.io/x/gocv/objdetect.go:52 +0x9c fp=0xc000035e80 sp=0xc000035e40 pc=0x425bffc
gocv.io/x/gocv.(*CascadeClassifier).DetectMultiScale(0xc000451fe8, 0x1de25a50, 0x0, 0x0, 0x0)
	gocv.io/x/gocv/objdetect.go:52 +0x56 fp=0xc000035f08 sp=0xc000035e80 pc=0x42584a6
main.(*GoCV).init.func1(0xc0000a6090, 0xc000451fd0, 0xc0001bc000, 0xc000451fe8, 0xff0000)
	github.com/therecipe/qt/internal/examples/qml/gocv/gocv.go:63 +0x2c5 fp=0xc000035fb8 sp=0xc000035f08 pc=0x42689f5
runtime.goexit()
	runtime/asm_amd64.s:1357 +0x1 fp=0xc000035fc0 sp=0xc000035fb8 pc=0x40680c1
created by main.(*GoCV).init
	github.com/therecipe/qt/internal/examples/qml/gocv/gocv.go:54 +0x23
```

Specifically the error seems to be to do with `rects := classifier.DetectMultiScale(img)`.

The xml file btw [is found here](https://github.com/hybridgroup/gocv/blob/master/data/haarcascade_frontalface_default.xml)

**Comment by TheApeMachine** [comment]
People, I am so sorry not to notice these responses earlier, work got a bit crazy, but thank you so much for this. This really helps me out of a bind that allows me to move forward today with this project :)

**Comment by TheApeMachine** [comment]
Hey people,

One more thing about this, everything in the GoCV example has been made to work after your help, which I really appreciate.
However, I am trying now to make this into a little component within our architecture, but for some reason it seems like the paint method is never called setting things up in the following way:

`package kiosk

import (
	"sync"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/quick"
)

func init() {
	CameraPreview_QmlRegisterType2("CustomModule", 1, 0, "CameraPreview")
}

type CameraPreview struct {
	quick.QQuickPaintedItem
	_     func() `constructor:"init"`
	image *gui.QImage
	data  []byte
	mutex *sync.Mutex
}

func (cameraPreview *CameraPreview) init() {
	cameraPreview.image = gui.NewQImage()
	cameraPreview.mutex = new(sync.Mutex)
}

func (cameraPreview *CameraPreview) WithChannel(ch chan []byte) *CameraPreview {
	go func() {
		for {
			cameraPreview.mutex.Lock()
			cameraPreview.data = <-ch
			cameraPreview.mutex.Unlock()
			cameraPreview.UpdateDefault()
		}
	}()

	return cameraPreview
}

func (cameraPreview *CameraPreview) paint(painter *gui.QPainter) {
	cameraPreview.mutex.Lock()
	cameraPreview.image.LoadFromData(cameraPreview.data, len(cameraPreview.data), "JPG")
	cameraPreview.mutex.Unlock()

	painter.DrawImage6(
		core.NewQRect4(0, 0, int(cameraPreview.Width()), int(cameraPreview.Height())), cameraPreview.image,
	)
}
`
I have since removed OpenCV from the project, since we were really just using it as a means to access the camera, and now opted for just reading a MJPEG stream from stdin.
