### ISSUE TITLE
Install failed ...

### ISSUE THREAD

**Issue by Matt-Texier** [therecipe/qt#105]
Hi Guys,

I am having issue installing the package in my workspace:

INFO[0000] running setup/prep                           
WARN[0001] (not root) failed to create qtdeploy symlink in your PATH (/usr/local/bin) -> use /home/matthieu/go-work/bin/qtdeploy instead 
WARN[0001] (not root) failed to create qtmoc symlink in your PATH (/usr/local/bin) -> use /home/matthieu/go-work/bin/qtmoc instead 
WARN[0001] (not root) failed to create qtrcc symlink in your PATH (/usr/local/bin) -> use /home/matthieu/go-work/bin/qtrcc instead 
WARN[0001] (not root) failed to create qtminimal symlink in your PATH (/usr/local/bin) -> use /home/matthieu/go-work/bin/qtminimal instead 
INFO[0001] running setup/check desktop                  
INFO[0001] GOOS: linux                                  
INFO[0001] GOARCH: amd64                                
INFO[0001] GOVERSION: go1.7.3                           
INFO[0001] GOROOT: /usr/local/go                        
INFO[0001] GOPATH: /home/matthieu/go-work               
INFO[0001] GOBIN: /home/matthieu/go-work/bin            
INFO[0001] HASH: c61a787766c9bdb6168e5d443977858743d5981e 
INFO[0001] QT_DIR: /home/matthieu/Qt                    
INFO[0001] QT_STUB: false                               
INFO[0001] Distro: ubuntu                               
INFO[0001] QT_PKG_CONFIG:                               
INFO[0001] UsePkgConfig: false                          
INFO[0001] running setup/generate                       
INFO[0006] generating full qt/core                      
INFO[0017] generating full qt/androidextras             
INFO[0017] generating full qt/gui                       
INFO[0025] generating full qt/network                   
...
...
INFO[0184] installing full qt/sensors                   
INFO[0196] installing full qt/positioning               
INFO[0199] installing full qt/widgets                   
ERRO[0876] failed to install.widgets
error: # github.com/therecipe/qt/widgets
/tmp/go-build800272350/github.com/therecipe/qt/widgets/_obj/_cgo_main.c: In function ‘crosscall2’:
/tmp/go-build800272350/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:2:23: warning: unused parameter ‘fn’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                       ^
/tmp/go-build800272350/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:2:61: warning: unused parameter ‘a’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                             ^
/tmp/go-build800272350/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:2:68: warning: unused parameter ‘c’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }

Is it me ... or something is wrong in he last commit ?

Thanks Matt.

**Comment by Matt-Texier** [comment]
[dump.txt](https://github.com/therecipe/qt/files/590513/dump.txt)

The whole trace if it could help ...

Thanks Matt.

**Comment by therecipe** [comment]
Hey

It seems like you are running out of memory during the installation of the widgets module:
`fatal error: runtime: out of memory` taken from the dump
(the rest are just warnings, which I will cleanup some day)

You need 8gb to install that module ...
So you probably have to export `QT_STUB=true` and re-run the setup.
And then use `qtminimal` and `go build/run -tags=minimal ...` manually or `qtdeploy` as usual.

**Comment by Matt-Texier** [comment]
Oups sorry, I'll increase memory of my VM and give it another try ...

**Comment by Matt-Texier** [comment]
Works great with 8GB of RAM, sorry I should I figure that myself.

Thanks Matt.

**Comment by therecipe** [comment]
No problem ;)
