### ISSUE TITLE
Cross-compile for Windows in Docker container

### ISSUE THREAD

**Issue by cfanatic** [therecipe/qt#1052]
Hi,

I would like to understand how to cross-compile my application for Windows inside a Docker container. I am running macOS myself. I saw that there are some Windows related Docker images on https://hub.docker.com/r/therecipe/qt/tags, but I am not sure which one to select.

Also, it would be helpful if you could provide the instructions which are necessary to cross-compile my applications **inside** the Docker container. Maybe something similar to:

`qtdeploy build windows <applications>`

Thanks for your support!

**Comment by cfanatic** [comment]
The following README might help you to understand what I am doing:

https://github.com/cfanatic/go-expensegui

**Comment by therecipe** [comment]
Hey

The easiest way to cross-compile your application inside a docker container is to use the `-docker` flag when using qtdeploy.

To do so, you can simply run something like this:
```bash
go get -v -d github.com/cfanatic/go-expensegui
cd $(go env GOPATH)/src/github.com/cfanatic/go-expensegui
qtdeploy -docker build windows_64_static
```

This will compile your application into a single 64bit binary, which has no external depedencies.
If you want to compile a linux application, then just use the `linux_static` image to create an application which can work accross different distros.

The image you currently use for linux deployments (`linux_debian_9`) works too, but it links against the Qt libraries provided by `apt` and therefore will probably not work on different distros than Debian/Ubuntu.


Also btw, if you want to build upon the docker images instead then you can use something like this as well:
```Dockerfile
FROM therecipe/qt:windows_64_static

WORKDIR /home/user/work/src/github.com/cfanatic/
RUN go get -v -d github.com/cfanatic/go-expensegui

RUN qtdeploy build windows github.com/cfanatic/go-expensegui
```

**Comment by cfanatic** [comment]
Thanks! It is working great now.

I have finalized the README for https://github.com/cfanatic/go-expensegui. Added some screenshots, instructions, etc.

Feel free to reference that program in your documentation. If I recall correctly, you have a page where you list programs of other developers which use your Qt bindings.

Cheers, and thanks again for your help.
