### ISSUE TITLE
Failed to run command

### ISSUE THREAD

**Issue by miRemid** [therecipe/qt#1059]
Os: Ubuntu19.10
Qt: Qt5.12.6
Run: $GOPATH/bin/qtdeploy 
Error:
ERRO[0000] failed to run command                         _func=RunCmd cmd="go list -mod=vendor -find -e -f {{.Dir}} github.com/therecipe/env_linux_amd64_513" dir=/dev env="ALACRITTY_LOG=/tmp/Alacritty-491.log CLUTTER_IM_MODULE=ibus COLORTERM=truecolor DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus DEFAULTS_PATH=/usr/share/gconf/pop.default.path DESKTOP_SESSION=pop DISPLAY=:1 GDMSESSION=pop GIO_LAUNCHED_DESKTOP_FILE_PID=491 GNOME_DESKTOP_SESSION_ID=this-is-deprecated GNOME_SHELL_SESSION_MODE=pop GO111MODULE=on GOPATH=/home/kamir/go GOPROXY=https://goproxy.io GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1 GTK_IM_MODULE=ibus GTK_MODULES=gail:atk-bridge:appmenu-gtk-module HOME=/home/kamir IM_CONFIG_CHECK_ENV=1 IM_CONFIG_PHASE=1 INVOCATION_ID=d82e19c823424e9f930f98f53cf365d5 JOURNAL_STREAM=9:937893 LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ADDRESS=en_US.UTF-8 LC_IDENTIFICATION=en_US.UTF-8 LC_MEASUREMENT=en_US.UTF-8 LC_MONETARY=en_US.UTF-8 LC_NAME=en_US.UTF-8 LC_NUMERIC=en_US.UTF-8 LC_PAPER=en_US.UTF-8 LC_TELEPHONE=en_US.UTF-8 LC_TIME=en_US.UTF-8 LOGNAME=kamir MANAGERPID=1580 MANDATORY_PATH=/usr/share/gconf/pop.mandatory.path PAPERSIZE=letter PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/home/kamir/node/bin:/home/kamir/.bin PWD=/home/kamir/go/bin QT4_IM_MODULE=ibus QT_IM_MODULE=ibus SESSION_MANAGER=local/pop-os:@/tmp/.ICE-unix/7557,unix/pop-os:/tmp/.ICE-unix/7557 SHELL=/bin/zsh SHLVL=1 SSH_AGENT_PID=1703 SSH_AUTH_SOCK=/run/user/1000/keyring/ssh TERM=xterm-256color USER=kamir USERNAME=kamir WINDOWID=67108868 WINDOWPATH=2 XAUTHORITY=/run/user/1000/gdm/Xauthority XDG_CONFIG_DIRS=/etc/xdg/xdg-pop:/etc/xdg XDG_CURRENT_DESKTOP=pop:GNOME XDG_DATA_DIRS=/usr/share/pop:/usr/local/share/:/usr/share/ XDG_MENU_PREFIX=gnome- XDG_RUNTIME_DIR=/run/user/1000 XDG_SESSION_CLASS=user XDG_SESSION_DESKTOP=pop XDG_SESSION_TYPE=x11 XMODIFIERS=@im=ibus _=/home/kamir/go/bin/./qtdeploy OLDPWD=/home/kamir ZSH=/home/kamir/.oh-my-zsh PAGER=less LESS=-R LSCOLORS=Gxfxcxdxbxegedabagacad LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36: CGO_ENABLED=0" error="exit status 1" name="get env dir"
go: cannot find main module; see 'go help modules'

**Comment by aab009725** [comment]
你怎么解决的

**Comment by NJUSTgzy** [comment]
能分享一下你的解决方案吗？
