### ISSUE TITLE
qtsetup installing full qt/core error

### ISSUE THREAD

**Issue by miRemid** [therecipe/qt#1063]
Qt5.13.0, Ubuntu19.10
when running qtsetup, get a fatal error:

INFO[0134] generating full qt/printsupport
INFO[0136] generating full qt/designer
INFO[0140] generating full qt/scxml
INFO[0141] generating full qt/gamepad
INFO[0142] generating full qt/purchasing
INFO[0142] generating full qt/datavisualization    [GPLv3]
INFO[0148] generating full qt/charts               [GPLv3]
INFO[0157] generating full qt/virtualkeyboard      [GPLv3]
INFO[0158] generating full qt/speech
INFO[0158] generating full qt/quickcontrols2
INFO[0159] generating full qt/sailfish
INFO[0159] generating full qt/webview
INFO[0159] generating full qt/remoteobjects
INFO[0161] running: 'qtsetup install linux' [docker=false] [vagrant=false]
INFO[0161] installing full qt/core
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:159:10: fatal error: QScriptExtensionPlugin: No such file or directory
  159 | #include <QScriptExtensionPlugin>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

ERRO[0257] failed to install 'core'; aborting setup

**Comment by akiyosi** [comment]
Hi

The following issues may help you.
https://github.com/therecipe/qt/issues/939

**Comment by miRemid** [comment]
thank you :D
