### ISSUE TITLE
Some methods are missing from core.QItemSelectionModel

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#107]
These methods, that all return QModelIndexList, are missing.
http://doc.qt.io/qt-5/qitemselectionmodel.html#selectedColumns
http://doc.qt.io/qt-5/qitemselectionmodel.html#selectedIndexes
http://doc.qt.io/qt-5/qitemselectionmodel.html#selectedRows

I noticed this when I went to use the selectedRows method.

**Comment by therecipe** [comment]
Yes, all the [container classes](http://doc.qt.io/qt-5/containers.html#the-container-classes) are currently missing.

I just happened to start working on this on Sunday and got it partially working.
Maybe I will push the changes later today, once it works with `qtminimal`.

**Comment by pekim** [comment]
As it happens I've now worked around this, with a completely different approach to what I was doing. However I know that shortly I'll be working on a bit of functionality that will need this support.

I'm so impressed with this library, your continuing addition to it, quick fixing of problems, and quick answering of problems. Thank you.

**Comment by therecipe** [comment]
Thank you for the kind words, I really appreciate it :)

I added a few new functions with the last two commits.

But only plain normal functions that return some sort of QList<T> or similar.
No functions that take QList<T> as input or signals, slots or virtual functions.
I will add them as well, but it may take some time.

**Comment by pekim** [comment]
QSelectionModel.SelectedRows was the particular function that I wanted to use. It seems to work well, so I'll close.
