### ISSUE TITLE
How to debug a crash? No Console

### ISSUE THREAD

**Issue by zanitee** [therecipe/qt#1075]
There is a crash, likely to do with something simple. However I'm wondering what is the correct way to run and debug a application using this package. I'm testing my application with: "qtdeploy -uic=false test desktop"

when the crash occurs the window just closes and the process exits, there is no console attached either (im on windows) how would I get the info as you would normally get from the console?

**Comment by akiyosi** [comment]
Hi,

You can get the console log with using env `QT_DEBUG_CONSOLE=true` like the following: 

```
QT_DEBUG_CONSOLE=true qtdeploy build desktop
```

It is also helpful to use the following tools: https://github.com/go-delve/delve

**Comment by zanitee** [comment]
Perfect. Thank you!
