### ISSUE TITLE
qtdeploy generate too much targets

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#108]
Running `qtdeploy desktop linux` generate too much files for unrelated targets. Maybe that why it's so slow.

![screenshot from 2016-11-15 20-44-33](https://cloud.githubusercontent.com/assets/474302/20308171/44cb4920-ab75-11e6-998b-9ced0abd541b.png)

**Comment by therecipe** [comment]
I wrote a bit about this here: https://github.com/therecipe/qt/issues/70#issuecomment-258463811

Most time is spend with `qtmoc` and `qtminimal`, which I haven't had time to cleanup and optimize yet.
And also much time is spend with `go build/run`, probably compiling the C/C++ code with gcc/clang.

I can probably reduce the time spend with qtmoc/qtminimal by 50%, which will make qtdeploy maybe 5 sec faster, but on some platforms like android (which uses gradle) you won't notice the difference.

For developing, it's probably better to use `qtmoc`, `qtminimal`, `qtrcc` manually with
`go build/run -tags=minimal ...` and only use `qtdeploy` for deploying.

**Comment by bclermont** [comment]
> For developing, it's probably better to use qtmoc, qtminimal, qtrcc manually with
> go build/run -tags=minimal ... and only use qtdeploy for deploying.

ah thanks, I'll try that!

maybe that should be in `README.md` somewhere? this way you might save some time to reply all my issues :P

**Comment by therecipe** [comment]
I will add it :)

**Comment by RadhiFadlillah** [comment]
Closed since it's old and has been fixed.
