### ISSUE TITLE
How to color cell in tablewidget?

### ISSUE THREAD

**Issue by MK5555** [therecipe/qt#1084]
In c++ it looks like `ui->tableWidget->item(i,j)->setBackground(Qt::red);.
But in golang I'm don't understand how to set color for `new2 = widgets.NewQTableWidgetItem2(pass, 0).SetBackground()`. How i can set color ?

**Comment by zanitee** [comment]
You would need to create a QColor, pass it to QBrush and pass that to SetBackground. I would advise you simply use a stylesheet its much easyier:

ui.tableWidget.SetStyleSheet("QTableView::item{ background-color: #FFFFFF; }")

**Comment by MK5555** [comment]
I solved my problem this way
`
	new2 := widgets.NewQTableWidgetItem2(path, 0)
	table.SetItem(k-1, 0, new2)
	new2.SetBackground(gui.NewQBrush3(gui.NewQColor3(64, 32, 64, 255), 1))`
