### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by svartkanin** [therecipe/qt#1095]
Looking at the changes that were last committed I was wondering if this project is still actively maintained?

**Comment by therecipe** [comment]
Hey

Yes it still is, I was just busy with some other stuff the last few month.
I will try to finish the update of the binding to Qt 5.14 in the next week and then start to work on the fixes needed for 5.15 as well.
After that I might start to work through the backlog of issues.
Sorry for the radio silence.

**Comment by svartkanin** [comment]
Awesome, great to hear!
