### ISSUE TITLE
sorry to trouble you

### ISSUE THREAD

**Issue by crazykun** [therecipe/qt#11]
I'm sorry to trouble you.  I watch your course study. But when I had a problem, I couldn't solve it.
d:\gopath\src\github.com\therecipe\qt\core\core.cpp:4:30: fatal error: QAbstractAnimation: No such file or directory

compilation terminated

**Comment by therecipe** [comment]
Hey

Did you install Qt in `C:\Qt\Qt5.5.1\`?

If you did install Qt in the correct location, you should be able to find the `QAbstractAnimation` file in the following directory: `C:\Qt\Qt5.5.1\5.5\mingw492_32\include\QtCore\QAbstractAnimation`

Then you can simply run the `setup.bat` again.
