### ISSUE TITLE
Q: Is this project still alive?

### ISSUE THREAD

**Issue by nekrondev** [therecipe/qt#1102]
I'm in progress of evaluating different Go-based GUIs. A major point for me is the future-proofness of the bindings. So is this project still alive as I can see latest commits from the end of January, no closed issues or other project activity since then.

 Maybe @therecipe can give us a vital sign (and hopefully he/she is doing fine in this troublesome times)?

**Comment by GreyXor** [comment]
https://github.com/therecipe/qt/issues/1095#issuecomment-612488206

**Comment by nekrondev** [comment]
Thanks I didn't saw that comment. Good to know the @therecipe is alive and kicking  👍
