### ISSUE TITLE
Support For Using Custom(User made) Plugins.

### ISSUE THREAD

**Issue by antony-jr** [therecipe/qt#1120]
In the current version of the binding, I was able to load my plugin successfully but I could not access my methods or signals. Anyway to do this now?? Since QMetaObject seems to be incomplete, So I cannot use it to call my methods too.

*I'm just opening this issue for you to consider this feature, I'm in no hurry*.

Here is what I'm talking about.
```
import (
   "fmt"
   "flags"
   "github.com/therecipe/qt/core"
   "github.com/therecipe/qt/widgets"
);

func main(){
        PLUGIN_PATH := "/libMyPlugin.so";
        flag.Parse()
        args := flag.Args()
        app := widgets.NewQApplication(len(args), args);
        pluginLoader := core.NewQPluginLoader(nil);
        pluginLoader.SetFileName(PLUGIN_PATH);
        status := pluginLoader.Load();
        fmt.Println("Loaded:: ", status);

        MyPlugin := pluginLoader.Instance();
        fmt.Println("Address:: ", MyPlugin);
        
        // Let's call a method from the interface of 
        // the plugin.
       // MyPlugin.setFile("Something.data");
       // But the above will fail.
}
```

**Comment by amlwwalker** [comment]
Did you see this? https://github.com/therecipe/qt/issues/759#issuecomment-453235535

**Comment by antony-jr** [comment]
@amlwwalker Are you suggesting that I use golang's ```plugin``` package by wrapping the qt plugin itself in the golang's plugin? I don't know but PySide and PyQt5 have a good solution on this take.

To put it simply, I want to do what python binding can do, something like this,
```
from PySide.QtCore import QPluginLoader

loader = QPluginLoader('path/to/plugin.so')
loader.load()
qobject = loader.instance()
qobject.MyMethodFromPluginInterface()
```

**Comment by amlwwalker** [comment]
Yeah basically I am, the reason I am, is because I brought this topic up a while ago and @therecipe suggested this was the way to go. I guess it depends what you are after, I'm not sure what the capability of the Qt plugins vs the Go plugins are, but the Go approach did it for what I needed. [Here is a link to the conversation I had](https://github.com/therecipe/qt/issues/1007#issuecomment-553343876)
