### ISSUE TITLE
QtQuick Control 1.4 not supported

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#113]
I have a QML that uses `MenuBar` from QtQuick 1.4. When I compiled and run it, I always get error

```
qrc:///qml/main.qml:3:1: module "QtQuick.Controls" is not installed
```

But when I remove import for QtQuick 1.4, that error gone. does qt binding only support QtQuick 2 ?

**Comment by therecipe** [comment]
Hey

Yes, I think the lowest supported QtQuick version is 2.0 (since Qt 5.x)

But I could get the MenuBar working with the following imports:
```qml
import QtQuick 2.0
import QtQuick.Controls 1.4
```

**Comment by arknable** [comment]
I see, I can confirm that. thanks.

**Comment by arknable** [comment]
@therecipe Sorry, I think I was mistakenly see terminal output when I test this. on my machine, above two import is not working
```
module "QtQuick.Controls" version 1.4 is not installed
```

but I won't open this issue again because v1.4 is old component indeed, I always using v2.0 so it's ok.

**Comment by arknable** [comment]
Hey, I'm reopening this issue because I can't find `FileDialog` replacement in QtQuick 2. Your example is working but when I use more complex component structure, QtQuick 1.x is not recognized. I still finding out a simple example to reproduce this to show you, but using simple example it seems always working.

**Comment by arknable** [comment]
I think I might have a reproducible example [here](https://github.com/arknable/therecipe-issue-113). If you compile that, it should output error like this:
```
QQmlApplicationEngine failed to load component
qrc:///qml/dialog.qml:3 module "QtQuick.Controls" version 1.4 is not installed
```

To solve the error, you can do one of two options,
1. Remove `AlertDialog.qml`
2. Add new import in `AlertDialog.qml`
```
import QtQuick 2.0
import QtQuick.Controls 2.0
import QtQuick.Controls 1.4     // new import
import QtQuick.Controls.Material 2.0
```

`AlertDialog` is not used in `main.qml` and not using any `QtQuick 1.4` specific control. In Qt Creator, this code works. So probably problem in application engine ?

**Comment by bclermont** [comment]
```
$ git diff
diff --git a/qml/dialog.qml b/qml/dialog.qml
index ef6df89..3a9be95 100755
--- a/qml/dialog.qml
+++ b/qml/dialog.qml
@@ -1,6 +1,5 @@
 import QtQuick 2.7
 import QtQuick.Controls 2.0
-import QtQuick.Controls 1.4
 import QtQuick.Dialogs 1.2
 import QtQuick.Window 2.2

$ qtdeploy build 
$ deploy/linux_minimal/therecipe-issue-113
XmbTextListToTextProperty result code -2
```

works for me and a windows open

@arknable I think you should rebuild your binding and clean your `pkg`. something might be wrong in your setup?

**Comment by bclermont** [comment]
I tried on both Linux and OSX and the problem can only be reproduced on OSX.
It's working fine on Linux

**Comment by arknable** [comment]
@bclermont Thanks to confirm because rebuilding qt binding still output the same result.

**Comment by therecipe** [comment]
Hey

The problem seems to be the missing `libqtquickcontrolsplugin.dylib` plugin (+ a few qml files) on macOS after the use of `macdeployqt`.
It works on Linux, because there the plugins are always copied regardless if needed or not.
And it also seems to work on android with `androiddeployqt`.

If you use `go build` with `qtmoc` and `qtrcc` instead of `qtdeploy` it should work on macOS as well.

Maybe it's a bug in `macdeployqt`?

**Comment by arknable** [comment]
@therecipe I see. so I should do following steps ?
1. run `qtmoc` in project folder
2. run `qtrcc` in project folder
3. run `go build` in project folder

is that correct ? I can skip `macdeployqt`.

**Comment by therecipe** [comment]
Yes, for developing you could simply run 
```
qtmoc && qtrcc && go build -o test && ./test
```
in the project folder

**Comment by arknable** [comment]
thanks a lot, I can confirm that the app compiled and running now. so I assume the problem is `macdeployqt`.

**Comment by bclermont** [comment]
@arknable 

the thing is that you have a workaround, `macdeployqt` is still broken :)

can you reopen this issue?
