### ISSUE TITLE
Is this project dead

### ISSUE THREAD

**Issue by StarAurryon** [therecipe/qt#1152]
Hello everyone,

I don't see many issues or pull requests that have answers.

Is this project dead.
I have two patches waiting, that I would like to be merged as there are severe bugs.

In the meantime I have created my fork with the patches [https://github.com/StarAurryon/qt](https://github.com/StarAurryon/qt)

Aurryon

**Comment by therecipe** [comment]
Hey

It's not dead, but development has slowed down this year.
I will spend this week to work on some stuff that is long overdue though, such as the changes necessary to make 5.14, 5.15 and the 6.0 alpha work.
And also fix some issues that should speed-up compile times on windows, as well as fix some other windows specific issues.

**Comment by muesli** [comment]
Can't wait for 5.15 support! It's really hindering my development currently, as I have to keep a special VM with Qt <=5.14 for it 🙈

**Comment by photondreams** [comment]
5.15 support would be great!

**Comment by ahmedkhalf** [comment]
Is this project dead.

**Comment by 1-bytes** [comment]
It's been a year and you need to update it.
QT version 6.1 need to be supported.

@therecipe

**Comment by 1-bytes** [comment]
> Is this project dead.

It looks like the project is dead.. :(
I am considering whether to learn Go Qt.
