### ISSUE TITLE
QML issues on Android

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#116]
https://github.com/bclermont/therecipe-qt-issue-116

is a very simple app that show an input field and a text area.

on desktop, if I run that, fill some text in both widgets and click button, I see in console:

```
$ deploy/linux_minimal/bug
XmbTextListToTextProperty result code -2
qml: text area:y
qml: input:x
```

while on android the same thing don't works. If I fill text in input field... and click the value of `textArea1.text` is empty string.
If I fill strings in both fields I can't never get both values. either input is empty or text area.

**Comment by therecipe** [comment]
Hey

It works for me on android, when I close that keyboard popup first.
The reason therefore is, that the `text` property is only set after the keyboard popup is gone.

But you could use `input1.displayText` to get the current visible text for the `TextInput` element.
http://doc.qt.io/qt-5/qml-qtquick-textinput.html#displayText-prop

I will see if there is something similar for the `TextArea`.

**Comment by bclermont** [comment]
Thank you for this. It's working fine now!
