### ISSUE TITLE
Deploy and Brand Android application

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#120]
`qtdeploy build android` create an app called `go` with name `org.qtproject.example.go`. Android robot logo and version 1.0.
How to change those and set the icon?
Possibly keep that along with Go code.

**Comment by therecipe** [comment]
You can simply put a custom `AndroidManifest.xml` and `build.gradle` inside the `android` subfolder.

```
project_name
├── android
│   ├── AndroidManifest.xml
│   ├── alias.txt
│   ├── build.gradle
│   ├── gradle
│   │   └── wrapper
│   │       └── gradle-wrapper.properties
│   ├── icon.png
│   ├── password.txt
│   ├── project_name.keystore
│   └── res
│       ├── drawable-hdpi
│       │   └── icon.png
│       ├── drawable-ldpi
│       │   └── icon.png
│       └── drawable-mdpi
│           └── icon.png
├── deploy
│   └── android_minimal
│       └── build
├── project.go
└── qml
    └── project.qml
```

The content of the `android` folder will be copied into `deploy/android_minimal/build` before using gradle to bundle the binary inside a `*.apk`.

You can use the `AndroidManifest.xml` found inside `deploy/android_minimal/build` as a template to build upon. (Set package identifier, icon, permissions, ...)

For example:
`android:icon="@drawable/icon"` can be used inside the `AndroidManifest.xml` to use the icon.png

**Comment by bclermont** [comment]
I started to take your issue replies and create permanent recycle doc for all users in #124

**Comment by therecipe** [comment]
That's a good Idea :)
