### ISSUE TITLE
QtWebKit

### ISSUE THREAD

**Issue by gen2brain** [therecipe/qt#121]
QtWebKit is back:

https://github.com/annulen/webkit
https://github.com/annulen/webkit/wiki/Comparison-with-QtWebKit-5.6
http://qtwebkit.blogspot.rs/2016/08/qtwebkit-im-back.html

Don't know if it will be included in official, I hope it will.
WebKit will then work in Windows with mingw, and don't know what is the status for Android, but probably there too, as I understand currently WebEngine needs visual studio and you can not use it in Android?

I already use new QtWebkit in my project https://github.com/gen2brain/url2img , with this patch https://gist.githubusercontent.com/gen2brain/b680573e55c9a21b9299db21041d2465/raw/5bc6489cb114275a79c02802b74766fde1925c8d/qtwebkit.patch .
With patch qtminimal needs a lot of time, maybe it is not complete, but it works at the end. It should work also with old QtWebKit, docs .index is old, the new one has some additions but they were of no use to me.

I tried first to use WebEngine but it failed to load images on many pages, I could not hide scrollbars etc. QtWebKit is more integrated with Qt, uses standard Qt components and memory usage is much smaller.
Also, it can be compiled statically (new, the old needed hack/patch), WebEngine can only work as shared lib.

If you want to try new QtWebKit i recommend you checkout https://github.com/annulen/qtwebkit-snapshots , much smaller repo.

**Comment by therecipe** [comment]
Hey

Thank you, those are great news :)
Especially @5k3105 might be happy to hear that: https://github.com/therecipe/qt/issues/53

I just checked the 5.8 RC, because I hoped for pre-build libs.
But sadly it doesn't seem to be officialy included yet. (Maybe in 5.9 ?)

Nevertheless, I was able to simply build it on macOS with qmake and make.
So I will make some changes to optionally support this and also update the docs.

Did you have to install many additional deps (like when building webengine from source) on Linux?

Btw, nice project :)
I'm planning to create a list of notable projects that use the binding someday and will keep it in mind.

**Comment by 5k3105** [comment]
Yes - great news. Very excited to see this  may be implemented soon :) Thanks for the heads up!

**Comment by gen2brain** [comment]
@therecipe Thanks. There are more dependencies now, https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Linux but I needed only libhyphen, I had everything else already. And I used cmake for build, not qmake:
```cmake -DPORT=Qt -DCMAKE_BUILD_TYPE=Release -DSHARED_CORE=OFF -DGENERATE_DOCUMENTATION=OFF -DENABLE_PRINT_SUPPORT=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_DEVICE_ORIENTATION=OFF -DENABLE_TOUCH_EVENTS=OFF -DENABLE_SPELLCHECK=OFF -DENABLE_WEB_AUDIO=OFF -DENABLE_VIDEO=OFF -DQT_STATIC_BUILD=ON ../../..```

For video, it can be compiled with qtmultimedia OR gstreamer, I disabled that for now because I didn't need it.

**Comment by therecipe** [comment]
Okay, thank you :)
I will probably link directly to the wiki.
(I was just surprised that it worked without installing any deps on macOS, because I had many problems when I tried to build the webengine on Linux (for the raspberry pi) some time ago.)

**Comment by therecipe** [comment]
@gen2brain 

Hey

I added the support for the webkit, as it seems like there will be pre-built versions available now:
https://github.com/therecipe/qt/commit/6d11509f782efa2ee6dc56a0a6f2153198c5ac43

Here are some instructions:
https://github.com/therecipe/qt#additional-modules

I tested it with url2img, and it works on macOS and Linux.
On windows it compiles fine, but I always get a completely white image.

But there was also the need to make some minor changes in your code:
```diff
diff --git a/url2img/loader.go b/url2img/loader.go
index 7328091..ce0267a 100644
--- a/url2img/loader.go
+++ b/url2img/loader.go
@@ -16,8 +16,8 @@ import (
 type Object struct {
 	core.QObject
 
-	_ func(data string)     `signal:load`
-	_ func(id, data string) `signal:loadFinished`
+	_ func(data string)     `signal:"load"`
+	_ func(id, data string) `signal:"loadFinished"`
 }
 
 // Image loader

```

And it currently only works if you make use of qtminimal, otherwise you will only get a completely black image. But I will look into that.

**Comment by gen2brain** [comment]
That is great, thanks!

I didn't know binaries are now available, nice. I will try to rebuild my url2img binaries these days. I also wanted to try to build with offscreen qpa plugin, to remove X server requirement, not sure still if is possible.

**Comment by 5k3105** [comment]
Hello :D

Have tested in win7 (go1.7.5) and it works great!

```go
package main

import (
	"os"

        "github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
	"github.com/therecipe/qt/webkit"
)


var (
	ap *Application

)

type Application struct {
	*widgets.QApplication
	Window    *widgets.QMainWindow
	Statusbar *widgets.QStatusBar
}

func main() {
	ap = &Application{}
	ap.QApplication = widgets.NewQApplication(len(os.Args), os.Args)

	ap.Window = widgets.NewQMainWindow(nil, 0)
	ap.Window.SetWindowTitle("webkit")

	wv := webkit.NewQWebView(ap.Window)
	
	url := `http://localhost:6060/pkg/github.com/therecipe/qt/webkit/`
	qurl := core.NewQUrl3(url, core.QUrl__TolerantMode)
	
	wv.Load(qurl)

	ap.Window.SetCentralWidget(wv)

	widgets.QApplication_SetStyle2("fusion")
	ap.Window.ShowMaximized()
	widgets.QApplication_Exec()
}
```

Clicked around. Even pressing backspace took me to the previous page (something chrome removed and everyone loves :P).

Thank you! :1st_place_medal: :1st_place_medal: 

Something I noticed though. You now have ```qtdeploy - fast``` and for some reason it's having trouble with detecting imports.. and regualr qtdeploy is now at 5min (used to be 1min on my machine). I will create an issue.

Really happy about this webkit!!!! Thank you!!!

**Comment by therecipe** [comment]
@gen2brain 

>remove X server requirement

I have no experience with these, but could you maybe make use of the "minimal" plugin?

@5k3105 

Ah great that it works for you :)
I wasn't able to really test it on windows (beside compiling)

**Comment by gen2brain** [comment]
@therecipe 
I found this custom qpa plugin from phantomjs https://github.com/ariya/phantomjs/tree/master/src/qt-qpa-platform-plugin, they don't need X server. If my experiments with offscreen and minimal are not ok, I guess I can just build that plugin in binary.

**Comment by therecipe** [comment]
@gen2brain 

I have used phantomjs once, a few years ago :D didn't know it was powered by Qt.

> I guess I can just build that plugin in binary.

Yes, I think that would work :)
And it is maybe also necessary to use a custom plugin, based on what I read in the `[Linux] Use our platform plugin instead of offscreen` commit msg.

**Comment by gen2brain** [comment]
I released a new binary of url2img. It seems there are some issues in latest release (tp5) with JPG and WEBP, I can get only PNG to work, so I have a workaround that uses image/jpeg etc. to encode images.

Also, it works now with offscreen platform plugin so X server is not required. It does render web pages flawlessly! The ones I tried at least.

**Comment by therecipe** [comment]
Nice, thank for letting me know :)
And it's awesome that you got it working with the offscreen plugin :)
