### ISSUE TITLE
Registered context property via QML engine not recognized by QML

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#122]
Hi, 

I'm encountering an issue where it seems that if I set a context property to QML engine, it will not be recognized by loaded QML. Currently it works using `QQuickView`, but I think QML engine is the best way to load QML file.

Thanks.

**Comment by therecipe** [comment]
Hey

Did you register the class with `*.QRegisterMetaType()` first?

This works for me:
```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/qml"
)

type NativeResult struct {
	core.QObject

	_ func() *NativeResult `slot:"returnNativeResult"`
}

func main() {
	gui.NewQGuiApplication(len(os.Args), os.Args)

	var testObj = NewNativeResult(nil)
	testObj.ConnectReturnNativeResult(func() *NativeResult {
		println("hello")
		return testObj
	})
	testObj.QRegisterMetaType()

	var engine = qml.NewQQmlApplicationEngine(nil)
	engine.RootContext().SetContextProperty("testObj", testObj)
	engine.Load(core.NewQUrl3("qrc:///qml/main.qml", 0))

	gui.QGuiApplication_Exec()
}
```

```qml
import QtQuick 2.7
import QtQuick.Controls 2.0
import QtQuick.Window 2.2

Window {
  visible: true
  Button {
    anchors.centerIn: parent
    text: "click"
    onClicked: console.log(testObj.returnNativeResult().returnNativeResult())
  }
}
```

**Comment by arknable** [comment]
ah ok thanks, I'm trying this. I'm rebuilding the binding again because `QRegisterMetaType()` is not recognized last time I tried.

**Comment by arknable** [comment]
nice, `QRegisterMetaType()` seems working for context property so I can use QMLEngine. but I still can't get it working as function return type. Since I can use QML engine, I will close this issue.
