### ISSUE TITLE
How to run examples?

### ISSUE THREAD

**Issue by ghost** [therecipe/qt#1240]
I executed ```go get -d -v github.com/therecipe/examples/...``` from the instructions in the Wiki (https://github.com/therecipe/qt/wiki/Getting-Started)
but got error:
```
go get: github.com/therecipe/examples@none updating to
        github.com/therecipe/examples@v0.0.0-20200701200025-1b5d8d146c95: parsing go.mod: go.mod:3: require github.com/therecipe/qt: version "master" invalid: must be of the form v1.2.3
go.mod:5: require github.com/therecipe/qt/internal/binding/files/docs/5.13.0: version "master" invalid: must be of the form v1.2.3
```
How can I fix this?

go version go1.16.5 linux/amd64

**Comment by lemon37564** [comment]
So I downloaded the examples from https://github.com/therecipe/examples directly.
But cannot compile with lots of error messages.
This seems to be duplicate of #1187
So I'm gonna to close this issue

**Comment by evgeniygazetdinov** [comment]
I support the question

**Comment by evgeniygazetdinov** [comment]
find solve?

**Comment by evgeniygazetdinov** [comment]
finded solving?

**Comment by razsteinmetz** [comment]
Any news on solution?

**Comment by oslyak** [comment]
git clone https://github.com/therecipe/examples
cd examples/

go run basic/widgets/main.go 

This is the way to run that example.

But, so many other examples have errors like:
i.ConnectDestroyTreeItem undefined (type *TreeItem has no field or method ConnectDestroyTreeItem)

It is so sad. (

It could be a greater project.
So many stars and bugs at the first line...
