### ISSUE TITLE
QtWidgets: splitter and MoveSplitter()

### ISSUE THREAD

**Issue by pztrn** [therecipe/qt#127]
Hey there and thanks for making these bindings :)

OS: OSX 10.11.6
Go: go version devel +75055de Tue Nov 22 04:28:59 2016 +0000 darwin/amd64 

I have a problem while trying to resize a splitter. E.g.:

```go
    saved_pane_pos, ok := ctx.Cfg.Cfg["/mainwindow/pane_negative_position"]
    if ok {
        pane_negative_pos, _ := strconv.Atoi(saved_pane_pos)
        new_splitter_pos := m.window_width - pane_negative_pos
        fmt.Println(new_splitter_pos)
        m.splitter.MoveSplitter(new_splitter_pos, 1)
    } else {
        g := m.window.Geometry()
        w := g.Width()
        m.splitter.MoveSplitter(w - 150, 1)
    }
```

Not working, and first widget (on left side of splitter) takes whole window width.

Tried to use index 0 for splitter, but do nothing. Instead I've connected with `splitter.ConnectSplitterMoved()` and saw that index was 1.

What I'm doing wrong here? Or there is a bug in bindings?

**Comment by therecipe** [comment]
Hey
Thank you :)

I did test the following example on macOS 10.12.1 with go1.7.1 darwin/amd64 and it works there.

```go
package main

import (
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	var window = widgets.NewQMainWindow(nil, 0)
	var vbox = widgets.NewQVBoxLayout2(nil)

	var splitter = widgets.NewQSplitter(nil)
	splitter.ConnectSplitterMoved(func(pos int, index int) {
		println("pos:", pos, "index:", index)
	})
	splitter.AddWidget(widgets.NewQTextEdit(nil))
	splitter.AddWidget(widgets.NewQTextEdit(nil))
	vbox.AddWidget(splitter, 0, 0)

	var button = widgets.NewQPushButton2("0%", nil)
	button.ConnectClicked(func(checked bool) { splitter.MoveSplitter(0, 1) })
	vbox.AddWidget(button, 0, 0)

	button = widgets.NewQPushButton2("25%", nil)
	button.ConnectClicked(func(checked bool) { splitter.MoveSplitter(splitter.Width()/4, 1) })
	vbox.AddWidget(button, 0, 0)

	button = widgets.NewQPushButton2("50%", nil)
	button.ConnectClicked(func(checked bool) { splitter.MoveSplitter(splitter.Width()/2, 1) })
	vbox.AddWidget(button, 0, 0)

	button = widgets.NewQPushButton2("75%", nil)
	button.ConnectClicked(func(checked bool) { splitter.MoveSplitter(splitter.Width()/4*3, 1) })
	vbox.AddWidget(button, 0, 0)

	button = widgets.NewQPushButton2("100%", nil)
	button.ConnectClicked(func(checked bool) { splitter.MoveSplitter(splitter.Width(), 1) })
	vbox.AddWidget(button, 0, 0)

	window.Layout().DestroyQObject()
	window.SetLayout(vbox)
	window.Show()

	widgets.QApplication_Exec()
}
```

If I would have to guess, then I would say that maybe some widget in your splitter don't wants to be resized. Did you set a SizePolicy or a fixedSize or something like that?

Or maybe the `new_splitter_pos` is calculated wrong? Maybe you could make use of [QSplitter::closestLegalPosition(int pos, int index)](http://doc.qt.io/qt-5/qsplitter.html#closestLegalPosition) to figure out what goes wrong?

**Comment by pztrn** [comment]
My splitter's positiong calculates like: window_weight - splitter_position for saving, and `window_weight - saved_negative_position` (was calculated on saving as `window_weight - splitter_position`). Calculated position is definetely within `0 .. window_weight` range.

But I found (possibly) my error - I should do "window.Show()" before moving splitter :) Sorry for bothering, my bad.

**Comment by therecipe** [comment]
No problem :)
