### ISSUE TITLE
QAbstractTextDocumentLayout Draw is not available

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#128]
This pure virtual function is not available.
http://doc.qt.io/qt-5.7/qabstracttextdocumentlayout.html#draw

A grossly oversimplified version of what I'm doing.
```go
	document := gui.NewQTextDocument(nil)
        ...
	document.DocumentLayout().Draw(painter, context)
```

**Comment by therecipe** [comment]
#129 is probably the cause, once that class is known the `Draw` function should become available automatically.
I will look into this.

**Comment by pekim** [comment]
Sorry, I forgot to close this. It's working fine now.
