### ISSUE TITLE
No means of creating a QAbstractTextDocumentLayout::PaintContext class instance

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#129]
http://doc.qt.io/qt-5.7/qabstracttextdocumentlayout-paintcontext.html

I need to be able to create a `PaintContext` for passing to `QAbstractTextDocumentLayout.Draw`.
(See https://github.com/therecipe/qt/issues/128)

**Comment by therecipe** [comment]
Hey

The class should be supported now with https://github.com/therecipe/qt/commit/aae3031704c4d2422a8841026c4815698335f8f1

But this property is not supported yet http://doc.qt.io/qt-5.7/qabstracttextdocumentlayout-paintcontext.html#selections-var
Did you plan to make use of it?

**Comment by pekim** [comment]
I don't currently have any plans to make use of context's selections. My initial interest is in setting a colour for a palette role in the context's palette.

**Comment by therecipe** [comment]
Okay, that's good.
Because it would take some time to get it working currently.

**Comment by pekim** [comment]
Sorry, I forgot to close this. It's working fine now.

**Comment by therecipe** [comment]
No problem :)
