### ISSUE TITLE
Construct QVariant from object pointer

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#130]
Hi,

Is there any way in qt binding to create `QVariant` from object pointer ? I didn't see constructor of `core.NewQVariantX` that accept pointer.

thanks.

**Comment by therecipe** [comment]
Hey

Maybe this function works http://doc.qt.io/qt-5/qvariant.html#QVariant-2.

`core.NewQVariant3(typeId, copy)` with `core.QMetaType__QObjectStar` or `core.QMetaType__VoidStar` for typeId and `(*core.QObject).Pointer()` for copy.
But I haven't tested it.

The other functions that QVariant provides to wrap custom types depend on templates, such as http://doc.qt.io/qt-5/qvariant.html#fromValue, http://doc.qt.io/qt-5/qvariant.html#qvariant_cast, http://doc.qt.io/qt-5/qvariant.html#setValue or http://doc.qt.io/qt-5/qvariant.html#value.
And are therefore not generally available.

Depending on what you need, I could either add helper functions like
`func (*).ToVariant() *core.QVariant` or `func *_FromVariant(*core.QVariant) *` to the moc classes.

Or for standard classes, I could add functions to the QVariant class like I did here: https://github.com/therecipe/qt/issues/101

**Comment by arknable** [comment]
ah yes, I must have missed that `core.NewQVariant3`. I'll try that.

**Comment by arknable** [comment]
I tried `core.NewQVariant3` but my sample app crashed. but, I have the same problem when doing the same thing using c++. so I guess I'll create success sample first in c++ then tried to retest this again in go.

**Comment by therecipe** [comment]
> to create QVariant from object pointer

Do you mean  a `*core.QObject` or a `(*core.QObject).Pointer()` aka `unsafe.Pointer` raw C void* pointer.

For `*core.QObject` I could add two new functions:

```go
(*core.QObject).ToVariant() *core.QVariant
(*core.QVariant).ToObject() *core.QObject
```

But I don't know if it's (allowed/possible/valid) to wrap a *core.QObject inside a QVariant.
What do you think?

Also, is there a special need to wrap it inside a QVariant? Instead of just passing the object as a `*core.QObject`?

**Comment by arknable** [comment]
I have a result object that holds result data which can be native type such as int, string, etc or just an object. This result will be a common return value passed from go to QML. I tried once to wrap QObject using `QVariant::fromValue` and pass it when calling QML function from C++ and it works. But `QVariant::fromValue` didn't worked when applied in function's return value. So probably the rule is different, I'll do one more experiment to make sure.

**Comment by therecipe** [comment]
Okay, please let me know if there is someway I could help.

**Comment by arknable** [comment]
it seems that QML doesn't support `QObject` pointer wrapped in `QVariant`. what working is if I map `QObject` pointer to `variant` in QML. Qt doc also doesn't mention about this and just mention that `QObject` pointer is supported, so probably other kind of pointer doesn't supported.

**Comment by therecipe** [comment]
Hey,

I think I got it working with https://github.com/therecipe/qt/commit/ec70fa5bcd6844c068e3d1fb10f26d2a8aacad53
The two new functions are `(*core.QObject) ToVariant` and `(*core.QVariant) ToObject`

I looked into the docs again and you were right, QObject* should be supported.

This example shows, that it's now possible to wrap a qVariantResult inside a QVariant and use it from QML.

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/quick"
)

// qVariantResult represents a result that carries a variant data
type qVariantResult struct {
	core.QObject
	// Data with type variant
	data core.QVariant

	// Slot to retrieve data
	_ func() core.QVariant `slot:"data"`
}

// CreateVariantResult returns new variant data result
func CreateVariantResult(data *core.QVariant) *core.QObject {
	var result = NewQVariantResult(nil)
	result.QRegisterMetaType()
	//result.qResult.initialize()
	result.data = *data
	result.ConnectData(func() *core.QVariant { return &result.data })
	return result.QObject_PTR()
}

func main() {

	gui.NewQGuiApplication(len(os.Args), os.Args)

	var view = quick.NewQQuickView(nil)

	//just to show that QVariant really wraps the QObject* and doesn't copy it
	var variantView = view.ToVariant()
	view.SetObjectName("testObjectName")
	println(view.Pointer(), view.ObjectName(), "==", variantView.ToObject().Pointer(), variantView.ToObject().ObjectName())
	//

	view.RootContext().SetContextProperty2("context", CreateVariantResult(CreateVariantResult(core.NewQVariant14("hello")).ToVariant()).ToVariant())

	view.SetSource(core.NewQUrl3("qrc:///qml/main.qml", 0))
	view.SetResizeMode(quick.QQuickView__SizeRootObjectToView)
	view.Show()

	gui.QGuiApplication_Exec()
}
```

```qml
import QtQuick 2.5
import QtQuick.Controls 1.4

Rectangle {
  Text {
    anchors.centerIn: parent
    text: "click me!"
  }

  MouseArea {
      id: mouseArea
      anchors.fill: parent
      onClicked:
      {
        var temp = context.data();
        console.log(temp);
        console.log(temp.data());
      }
  }
}
```
