### ISSUE TITLE
How can I print log to console in windows?

### ISSUE THREAD

**Issue by fcying** [therecipe/qt#139]
I try use `log` `fmt` in `go run ...`, it doesn't work.

**Comment by therecipe** [comment]
Hey

Yes, unfortunately the console output is suppressed on windows.
You could however redirect the Go console output into a file or create a log window ...

Also the [msys2](https://msys2.github.io) mingw32/64 shells seem to print the complete console output (Qt + Go) as on Linux or macOS.

**Comment by fcying** [comment]
Thanks, I use `log.SetOutput(logFile)` now, it can save log into logFile.
