### ISSUE TITLE
need some gitignores

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#141]
i just did a fresh 

go get -v github.com/therecipe/qt/cmd/...
$GOPATH/bin/qtsetup

i noticed that the qtsetup script put about 20  files in the bluetooth and core  folders that are NOT git ignored.  Maybe we need a .gitignore for this in master ?

**Comment by joeblew99** [comment]
my bad :) turns out my fork was a little messed up.

i deleted everything on disk and then:
go get -v github.com/therecipe/qt/cmd/...
$GOPATH/bin/qtsetup

then its only 3 dbus files showing up for git commit.

So nothing to worry about..

**Comment by therecipe** [comment]
Okay, no problem :)
