### ISSUE TITLE
how to  pull latest

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#144]
go get -u -v github.com/therecipe/qt/cmd/...

does not get latest, once i have already done this in the past.

so if i just do a git pull, do i have to rerun setup ?
--

also a git ignore is needed for these 3 ?

	dbus/dbus.cpp
	dbus/dbus.go
	dbus/dbus.h

**Comment by therecipe** [comment]
You could try `go get -a -u -v github.com/therecipe/qt/cmd/...`
It seems like qtsetup and the rest is not rebuild if you only use `-u -v`

Or try to use git pull with `go install ./...` in `qt/cmd`, if you remove the old `qt*` binaries in `GOPATH/bin` or `GOBIN` first.

And yes, re-runing the setup is necessary  to re-gen the binding for your system. (You can use ctrl+c after the installation phase, to stop the building of the examples)

> also a git ignore is needed for these 3 ?

No, that shouldn't be necessary. But the build is somehow inconsistent for me as well. (3 functions in the "widgets" package)

I suspect in your case the reason for this is, that you are using the HomeBrew version.
And the repo files were generated with the official Qt installer. So there can be minor differences.

But if you are not using the HomeBrew version, could you post the diff?

**Comment by joeblew99** [comment]
i think that we need vendoring as Jordan suggested

````
x-MacBook-Pro:~ apple$ pwd
/Users/apple
x-MacBook-Pro:~ apple$ go get -a -u -v github.com/therecipe/qt/cmd/...
github.com/therecipe/qt (download)
github.com/Sirupsen/logrus (download)
Fetching https://golang.org/x/crypto/ssh?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh?go-get=1
get "golang.org/x/crypto/ssh": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
Fetching https://golang.org/x/crypto/curve25519?go-get=1
Parsing meta tags from https://golang.org/x/crypto/curve25519?go-get=1 (status code 200)
get "golang.org/x/crypto/curve25519": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/curve25519?go-get=1
get "golang.org/x/crypto/curve25519": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/ed25519?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ed25519?go-get=1 (status code 200)
get "golang.org/x/crypto/ed25519": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ed25519?go-get=1
get "golang.org/x/crypto/ed25519": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/ed25519/internal/edwards25519?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ed25519/internal/edwards25519?go-get=1 (status code 200)
get "golang.org/x/crypto/ed25519/internal/edwards25519": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ed25519/internal/edwards25519?go-get=1
get "golang.org/x/crypto/ed25519/internal/edwards25519": verifying non-authoritative meta tag
runtime/internal/sys
go install runtime/internal/sys: open /usr/local/go/pkg/darwin_amd64/runtime/internal/sys.a: permission denied

````

**Comment by joeblew99** [comment]
shall i close this ?

**Comment by therecipe** [comment]
Yeah, I'm currently using these free CI services ...
But I'm currently not able to test everything I want.

Like full builds for each platform with each target, sailfish + raspberry stuff, the docker images, backward/forward compatibility tests with different Qt versions, full functionality test of the deployed applications and probably more stuff that I can't think of right now.

Is it complicated to set this vmware ESXI stuff up? I just used the vmware player und such years (10 or so) ago ...

**Comment by joeblew99** [comment]
Here are my notes on the matter:
https://github.com/gu-io/gu-x/tree/master/tool/vmware

i am working on this problem as i learn more.

is it complicated ? not really.
https://www.macstadium.com/
- they have dedicated desktop images as ISO's readdy to go.
- this is who the golang team also use.

https://github.com/golang/build/search?utf8=%E2%9C%93&q=vmware
- here you can see the references.
- if we did this properly we would use the same code as them for this automation, but thats for later i feel.

**Comment by therecipe** [comment]
Oh, that's a lot of stuff to think about :)

I like your idea to unify everything, but that's probably out of scope for me right now :D

The roadmap currently is, to clean/refactor the current code without introducing to much new stuff (that can possible break). And doing so with backward/forward compatibility in mind.

After this I will start thinking about CI again, until then I will keep your notes in mind.

**Comment by joeblew99** [comment]
Yes fully understand.

Just so there is no confusion - dont think i am suggesting it all be done
now. Its just my notes on a big picture idea.
You can get a managed vmware ESXI server with Window, OSX and Ubuntu
desktops setup in 10 minutes over a MacShack. They do that, and you can RDP
into the Desktops as you please. Its about 30 a month i think.

i am planning to do this in the next fews days and will give you access to
have a play if it helps.

**Comment by therecipe** [comment]
Thanks for the offer :)
There is really one thing I would like to test.

If it's possible to get VirtualBox running on an already virtualized machine (I assume the machines are virtualized)
So that CI is possible for the Sailfish target (and maybe android-emulator someday)

I know it's possible, but I was not able to do that with travis and co.
Probably because of the virtualisation method they use OpenVZ, KVM or something similar I believe (but I'm not sure).

**Comment by joeblew99** [comment]
Yes your are correct - Pretty sure with ESXI, yes you can then run VirtBox
inside a guest.
On OSX; you can of course run Windows 10 and Ubuntu inside Virtbox too. I
guess thats your game plan.


i contacted travis today about getting an ESXI server. Will hear back from
them later today i hope. Will let you know.

**Comment by therecipe** [comment]
Nice, thank you :)
Please let me know if you hear back from them.
