### ISSUE TITLE
qtdeploy broken for IOS - Apple did a  OSX update  today

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#145]
The problem is that qtdeploy for ios is broken.

Today Apple did a OSX update that required a reboot. 
This could have broken the qtdeploy script?

## How to reproduce

i am using the example at:
internal/examples/qml/application

from that folder:
````
# build
qtdeploy build ios
````

terminal output is:
````
ERRO[0005] failed to find iPhoneOS sdk in /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs 
````

I checked that folder:

````
x-MacBook-Pro:application apple$ ls -al /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs 
total 8
drwxrwxr-x  4 root  wheel  136 Dec 13 09:28 .
drwxr-xr-x  5 root  wheel  170 Dec  7 00:36 ..
drwxrwxr-x  7 root  wheel  238 Dec  1 22:27 iPhoneOS.sdk
lrwxr-xr-x  1 root  wheel   12 Dec 13 09:20 iPhoneOS10.2.sdk -> iPhoneOS.sdk

````

**Comment by joeblew99** [comment]
i just ran a basic test xcode project, and it runs fine from inside xcode.
Its using: Iphone 6 - IOS 10.2

Today Apple did a OSX update that required a reboot. 
This could have broken the qtdeploy script?


I also did a git pull on the latest, and ran qtsetup.
It seems to also not find the IOS SDK !!

````

x-MacBook-Pro:md-archi-qt apple$ qtsetup
INFO[0000] running setup/prep                           
INFO[0001] running setup/check desktop                  
INFO[0001] GOOS: darwin                                 
INFO[0001] GOARCH: amd64                                
INFO[0001] GOVERSION: go1.7.1                           
INFO[0001] GOROOT: /usr/local/go                        
INFO[0001] GOPATH: /Users/apple/workspace/go            
INFO[0001] GOBIN: /Users/apple/workspace/go/bin         
INFO[0001] HASH: 98fe845133a6a1b5ab313f8b17d45192684e7e31 
INFO[0001] QT_DIR: /usr/local/opt/qt5                   
INFO[0001] QT_STUB: false                               
INFO[0001] QT_HOMEBREW:                                 
INFO[0001] IsHomeBrewQtDir: true                        
INFO[0001] UseHomebrew: true                            
INFO[0001] QT_DARWIN_DIR: /usr/local/opt/qt5            
INFO[0001] XCODE_DIR: /Applications/Xcode.app           
INFO[0001] MACOS_SDK_DIR: MacOSX10.12.sdk               
ERRO[0001] failed to find iPhoneOS sdk in /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs 
INFO[0001] IPHONEOS_SDK_DIR:                            
ERRO[0001] failed to find iPhoneSimulator sdk in /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs 
INFO[0001] IPHONESIMULATOR_SDK_DIR:                     
INFO[0001] running setup/generate  

````

Mhhh...

**Comment by therecipe** [comment]
I had the same problem, after updating Xcode yesterday.
So this commit https://github.com/therecipe/qt/commit/279ae4e3bc1c14297ea01b1aa0ce3dd78160dbdb#diff-6e57344e2624c1a36c8b3a0d9c0ac99e should have fixed this already.

I guess, that even if you `pulled/go get` the latest repo version that somehow the `qt*` tools haven't been rebuild. (And therefore this still fails)

And I just noticed that the "HASH" in the output is not a usable replacement for a version number.
Because an old "qtsetup", would still show the newest hash (like in your case).
So I added a simple hardcoded version number to qtsetup.

You should be able to check the version number and if the `IPHONEOS_SDK_DIR` can be found.
With `qtsetup check desktop` or  `qtsetup check ios`

**Comment by joeblew99** [comment]
it finds the IPhone SDK now.

But ios setup fails for me.

from the root qt folder....

````
# get latest of therecipe/qt
git pull
go get -u -v github.com/therecipe/qt/cmd/...
qtsetup check desktop
qtsetup check ios

````



````

x-MacBook-Pro:qt apple$ qtsetup check desktop
INFO[0000] running setup/check desktop                  
INFO[0000] VERSION: 0.0.1                               
INFO[0000] GOOS: darwin                                 
INFO[0000] GOARCH: amd64                                
INFO[0000] GOVERSION: go1.7.1                           
INFO[0000] GOROOT: /usr/local/go                        
INFO[0000] GOPATH: /Users/apple/workspace/go            
INFO[0000] GOBIN: /Users/apple/workspace/go/bin         
INFO[0000] HASH: e6da611e3d4403e73a2f5b94d606ad62751ea3cf 
INFO[0000] QT_DIR: /usr/local/opt/qt5                   
INFO[0000] QT_STUB: false                               
INFO[0000] QT_HOMEBREW:                                 
INFO[0000] IsHomeBrewQtDir: true                        
INFO[0000] UseHomebrew: true                            
INFO[0000] QT_DARWIN_DIR: /usr/local/opt/qt5            
INFO[0000] XCODE_DIR: /Applications/Xcode.app           
INFO[0000] MACOS_SDK_DIR: MacOSX10.12.sdk               
INFO[0000] IPHONEOS_SDK_DIR: iPhoneOS10.2.sdk           
INFO[0000] IPHONESIMULATOR_SDK_DIR: iPhoneSimulator10.2.sdk 
x-MacBook-Pro:qt apple$ qtsetup check ios
INFO[0000] running setup/check ios                      
INFO[0000] VERSION: 0.0.1                               
INFO[0000] GOOS: darwin                                 
INFO[0000] GOARCH: amd64                                
INFO[0000] GOVERSION: go1.7.1                           
INFO[0000] GOROOT: /usr/local/go                        
INFO[0000] GOPATH: /Users/apple/workspace/go            
INFO[0000] GOBIN: /Users/apple/workspace/go/bin         
INFO[0000] HASH: e6da611e3d4403e73a2f5b94d606ad62751ea3cf 
INFO[0000] QT_DIR: /usr/local/opt/qt5                   
INFO[0000] QT_STUB: false                               
INFO[0000] QT_HOMEBREW:                                 
INFO[0000] IsHomeBrewQtDir: true                        
INFO[0000] UseHomebrew: true                            
INFO[0000] QT_DARWIN_DIR: /usr/local/opt/qt5            
INFO[0000] XCODE_DIR: /Applications/Xcode.app           
INFO[0000] MACOS_SDK_DIR: MacOSX10.12.sdk               
INFO[0000] IPHONEOS_SDK_DIR: iPhoneOS10.2.sdk           
INFO[0000] IPHONESIMULATOR_SDK_DIR: iPhoneSimulator10.2.sdk 
x-MacBook-Pro:qt apple$ 


````

Ok so basic stuff works, now lets try ios

x-MacBook-Pro:qt apple$ $GOPATH/bin/qtsetup ios
INFO[0000] running setup/prep                           
INFO[0006] running setup/check ios                      
INFO[0006] VERSION: 0.0.1                               
INFO[0006] GOOS: darwin                                 
INFO[0006] GOARCH: amd64                                
INFO[0006] GOVERSION: go1.7.1                           
INFO[0006] GOROOT: /usr/local/go                        
INFO[0006] GOPATH: /Users/apple/workspace/go            
INFO[0006] GOBIN: /Users/apple/workspace/go/bin         
INFO[0007] HASH: e6da611e3d4403e73a2f5b94d606ad62751ea3cf 
INFO[0007] QT_DIR: /usr/local/opt/qt5                   
INFO[0007] QT_STUB: false                               
INFO[0007] QT_HOMEBREW:                                 
INFO[0007] IsHomeBrewQtDir: true                        
INFO[0007] UseHomebrew: true                            
INFO[0007] QT_DARWIN_DIR: /usr/local/opt/qt5            
INFO[0007] XCODE_DIR: /Applications/Xcode.app           
INFO[0007] MACOS_SDK_DIR: MacOSX10.12.sdk               
INFO[0007] IPHONEOS_SDK_DIR: iPhoneOS10.2.sdk           
INFO[0007] IPHONESIMULATOR_SDK_DIR: iPhoneSimulator10.2.sdk 
INFO[0007] running setup/generate                       
INFO[0007] running setup/install ios                    
INFO[0032] running setup/test ios (~10min)              
INFO[0032] testing widgets/line_edits                   
PANI[0041] failed to run command                         cmd="/Users/apple/workspace/go/bin/qtdeploy test ios /Users/apple/workspace/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits " error="exit status 2" func=RunCmd name="test widgets/line_edits" output="time=\"2016-12-15T09:24:40+01:00\" level=panic msg=\"failed to run command\" cmd=\"go build -v -ldflags=\\\"-w\\\" -o /Users/apple/workspace/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/deploy/ios_minimal/libgo.a -tags=\\\"minimal\\\"\\\"ios\\\" -installsuffix=ios -buildmode c-archive\" error=\"exit status 2\" func=RunCmd name=\"build for ios on darwin\" output=\"github.com/therecipe/qt/internal/android/cgo\\ngithub.com/therecipe/qt\\ngithub.com/therecipe/qt/core\\n# github.com/therecipe/qt/core\\n/tmp/go-build669936328/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]\\n/tmp/go-build669936328/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]\\n/tmp/go-build669936328/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]\\n/tmp/go-build669936328/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n/tmp/go-build669936328/github.com/therecipe/qt/core/_obj/_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n/tmp/go-build669936328/github.com/therecipe/qt/core/_obj/_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]\\n/tmp/go-build669936328/github.com/therecipe/qt/core/_obj/_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]\\n/tmp/go-build669936328/github.com/therecipe/qt/core/_obj/_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]\\n/tmp/go-build669936328/github.com/therecipe/qt/core/_obj/_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]\\n# github.com/therecipe/qt/core\\n../../../../core/core-minimal.cpp:9:10: fatal error: 'QAbstractAnimation' file not found\\n\" \npanic: (*logrus.Entry) (0x2167e0,0xc4200e8410)\n\ngoroutine 1 [running]:\npanic(0x2167e0, 0xc4200e8410)\n\t/usr/local/go/src/runtime/panic.go:500 +0x1a1\ngithub.com/Sirupsen/logrus.Entry.log(0xc42000c7d0, 0xc4200d0810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420054d00, ...)\n\t/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x423\ngithub.com/Sirupsen/logrus.(*Entry).Panic(0xc4200e83c0, 0xc420112de8, 0x1, 0x1)\n\t/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x124\ngithub.com/therecipe/qt/internal/utils.RunCmd(0xc4200e2160, 0xc4200da460, 0x17, 0x2, 0x2)\n\t/Users/apple/workspace/go/src/github.com/therecipe/qt/internal/utils/utils.go:81 +0x56e\nmain.build()\n\t/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtdeploy/qtdeploy.go:470 +0x833\nmain.main()\n\t/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtdeploy/qtdeploy.go:45 +0x144\n"
panic: (*logrus.Entry) (0x1ca500,0xc420017c70)

goroutine 1 [running]:
panic(0x1ca500, 0xc420017c70)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/Sirupsen/logrus.Entry.log(0xc420016280, 0xc42022c510, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420037300, ...)
	/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x423
github.com/Sirupsen/logrus.(*Entry).Panic(0xc420017c20, 0xc420037470, 0x1, 0x1)
	/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x124
github.com/therecipe/qt/internal/utils.RunCmd(0xc4200de2c0, 0xc4200d4880, 0x17, 0x1, 0x1)
	/Users/apple/workspace/go/src/github.com/therecipe/qt/internal/utils/utils.go:81 +0x56e
main.test(0x7fff5fbff7de, 0x3)
	/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtsetup/test.go:46 +0x12ae
main.main()
	/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtsetup/qtsetup.go:82 +0x3f8
x-MacBook-Pro:qt apple$

**Comment by joeblew99** [comment]
i upgraded go to 1.7.4.
i did a "qtsetup desktop" and it works
then i did a "qtsetup ios" and it fails

````
PANI[0005] failed to run command                         cmd="go install -tags=\"ios\" -installsuffix=ios std" error="exit status 1" func=RunCmd name=install.std output="go install runtime/internal/sys: mkdir /usr/local/go/pkg/darwin_arm64_ios_shared: permission denied\n"

````

wondering if my go setup is wrong

````
x-MacBook-Pro:pkg apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build426804729=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

````

**Comment by joeblew99** [comment]
So this is a permissions problem.
Same issue with android too.
and i see in the main readme, that it asks developers to chmod on the PKG dir.

I think this might help ?
https://github.com/golang/go/issues/14213

We should be using the proper golang way and using "go build" it seems.

comment ??

**Comment by joeblew99** [comment]
also i want to raise this:
https://github.com/karalabe/xgo

this is used by the Ethereum project to allow them to cross build for Android and IOS and desktops.

**Comment by joeblew99** [comment]
i fixed the qtsetup ios permissions issue by changing to using "go build", instead of "go install".
This was suggested here: golang/go#14213

line 102 of github.com/therecipe/qt/cmd/qtsetup:
````
func installPkgCmd(buildTarget, tagFlags, pkg string, env map[string]string) *exec.Cmd {
	var cmd = exec.Command("go", "build") // was install, but that causes permission issue on $GOROOT/pkg

````


still hit the next issue though still :)

````

x-MacBook-Pro:qtsetup apple$ qtsetup ios
INFO[0000] running setup/prep                           
INFO[0028] running setup/check ios                      
INFO[0028] VERSION: 0.0.1                               
INFO[0028] GOOS: darwin                                 
INFO[0028] GOARCH: amd64                                
INFO[0028] GOVERSION: go1.7.4                           
INFO[0028] GOROOT: /usr/local/go                        
INFO[0028] GOPATH: /Users/apple/workspace/go            
INFO[0028] GOBIN: /Users/apple/workspace/go/bin         
INFO[0028] HASH: e6da611e3d4403e73a2f5b94d606ad62751ea3cf 
INFO[0028] QT_DIR: /usr/local/opt/qt5                   
INFO[0028] QT_STUB: false                               
INFO[0028] QT_HOMEBREW:                                 
INFO[0028] IsHomeBrewQtDir: true                        
INFO[0028] UseHomebrew: true                            
INFO[0028] QT_DARWIN_DIR: /usr/local/opt/qt5            
INFO[0028] XCODE_DIR: /Applications/Xcode.app           
INFO[0028] MACOS_SDK_DIR: MacOSX10.12.sdk               
INFO[0028] IPHONEOS_SDK_DIR: iPhoneOS10.2.sdk           
INFO[0028] IPHONESIMULATOR_SDK_DIR: iPhoneSimulator10.2.sdk 
INFO[0028] running setup/generate                       
INFO[0028] running setup/install ios                    
INFO[0068] running setup/test ios (~10min)              
INFO[0068] testing widgets/line_edits                   
PANI[0085] failed to run command                         cmd="/Users/apple/workspace/go/bin/qtdeploy test ios /Users/apple/workspace/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits " error="exit status 2" func=RunCmd name="test widgets/line_edits" output="time=\"2016-12-15T11:18:16+01:00\" level=panic msg=\"failed to run command\" cmd=\"go build -v -ldflags=\\\"-w\\\" -o /Users/apple/workspace/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/deploy/ios_minimal/libgo.a -tags=\\\"minimal\\\"\\\"ios\\\" -installsuffix=ios -buildmode c-archive\" error=\"exit status 2\" func=RunCmd name=\"build for ios on darwin\" output=\"runtime/internal/sys\\nruntime/internal/atomic\\nruntime\\nerrors\\ninternal/race\\nsync/atomic\\nmath\\nunicode/utf8\\ngithub.com/therecipe/qt/internal/android/cgo\\nunicode\\nsync\\nruntime/cgo\\nio\\nsyscall\\nstrconv\\nstrings\\nreflect\\ntime\\nos\\nfmt\\nlog\\ngithub.com/therecipe/qt\\ngithub.com/therecipe/qt/core\\n# github.com/therecipe/qt/core\\n/tmp/go-build280081786/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]\\n/tmp/go-build280081786/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]\\n/tmp/go-build280081786/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]\\n/tmp/go-build280081786/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n/tmp/go-build280081786/github.com/therecipe/qt/core/_obj/_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n/tmp/go-build280081786/github.com/therecipe/qt/core/_obj/_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]\\n/tmp/go-build280081786/github.com/therecipe/qt/core/_obj/_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]\\n/tmp/go-build280081786/github.com/therecipe/qt/core/_obj/_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]\\n/tmp/go-build280081786/github.com/therecipe/qt/core/_obj/_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]\\n# github.com/therecipe/qt/core\\n../../../../core/core-minimal.cpp:9:10: fatal error: 'QAbstractAnimation' file not found\\n\" \npanic: (*logrus.Entry) (0x216800,0xc4200e8370)\n\ngoroutine 1 [running]:\npanic(0x216800, 0xc4200e8370)\n\t/usr/local/go/src/runtime/panic.go:500 +0x1a1\ngithub.com/Sirupsen/logrus.Entry.log(0xc42000c7d0, 0xc4200d0420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420054d00, ...)\n\t/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x423\ngithub.com/Sirupsen/logrus.(*Entry).Panic(0xc4200e8320, 0xc42010ade8, 0x1, 0x1)\n\t/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x124\ngithub.com/therecipe/qt/internal/utils.RunCmd(0xc42008ab00, 0xc420013520, 0x17, 0x2, 0x2)\n\t/Users/apple/workspace/go/src/github.com/therecipe/qt/internal/utils/utils.go:81 +0x56e\nmain.build()\n\t/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtdeploy/qtdeploy.go:470 +0x833\nmain.main()\n\t/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtdeploy/qtdeploy.go:45 +0x144\n"
panic: (*logrus.Entry) (0x1ca500,0xc42023c1e0)

goroutine 1 [running]:
panic(0x1ca500, 0xc42023c1e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/Sirupsen/logrus.Entry.log(0xc4200980a0, 0xc4200f2c60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420037300, ...)
	/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x423
github.com/Sirupsen/logrus.(*Entry).Panic(0xc42023c190, 0xc420037470, 0x1, 0x1)
	/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x124
github.com/therecipe/qt/internal/utils.RunCmd(0xc420097080, 0xc420224420, 0x17, 0x1, 0x1)
	/Users/apple/workspace/go/src/github.com/therecipe/qt/internal/utils/utils.go:81 +0x56e
main.test(0x7fff5fbff7d8, 0x3)
	/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtsetup/test.go:46 +0x12ae
main.main()
	/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtsetup/qtsetup.go:82 +0x3f8

````

Not sure what else to do right now.. :)

**Comment by therecipe** [comment]
> BTW, after a git pull, i guess i must run "qtsetup desktop" EVERYTIME ?

You can use `qtsetup prep && qtsetup check && qtsetup generate && qtsetup install` to skip the test phase and basically only generate + install the binding.

Also depending on what you need (if you only use qtdeploy and not `go build` directly)
you can use the STUB mode to speedup the installation. (Or if you are okay with using `qtminimal && go build -tags=minimal ...`)


> So this is a permissions problem.
Same issue with android too.

Ah, yes there where already a few issues about this.
(I think `go install` speeds up the deployment a little, but `go build` is more convenient)


> also i want to raise this:
https://github.com/karalabe/xgo

I will look into this, but I don't know if this really makes things simpler because there are non standard targets like Sailfish/RaspberryPi and probably more in the future. And there is also the need to use the gcc cross compilers.

This seems to be the cause of your last error:  `fatal error: 'QAbstractAnimation' file not`
But I don't know why this comes up, I will change `go install` to `go build` and try to reproduce your error on my system.

**Comment by therecipe** [comment]
I removed the `go install std` step with https://github.com/therecipe/qt/commit/8dbcd7aecc4bfffa250649fb81384692cac02305

**Comment by therecipe** [comment]
Oh, I know what went wrong ...

You are using the HomeBrew version of Qt `INFO[0028] UseHomebrew: true`
The HomeBrew version is lacking the necessary files to deploy to iOS and Android.

You will need to use the official Qt version with android and iOS support.
https://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-mac-x64-android-ios-5.7.0.dmg
Then it should work. (Don't forget to unset the defined environmental variables when re-runing qtsetup)

I will add a few additionally checks to let qtsetup catch such things earlier.

**Comment by therecipe** [comment]
qtsetup + qtdeploy should recognize this and some similar problems now.
https://github.com/therecipe/qt/commit/28b6970117d4025e0d11d2e3b7cbce67f2e07eb9

**Comment by gedw99** [comment]
Thanks for all this.
Now I can try this and then keep trying my demos on desktops and mobiles.

So for mobiles you can't use homebrew. Relieved this is the answer.
Please update the readme, so others don't get caught and raise this issue again.
Also maybe then it makes sense to not allow the homebrew option. Just download it for them as part of setup. Really brute for e but will remove lots of confusion and issues.

I have a suggestion about mobile.
Gomobile and xamarin for Mac both download all android SDK and other bits and place them in their own explicit folders. Then there is no guessing on the dependency stuff. It's one time hit. You might want to do the same as part of the setup phase.

Both of the above can be done as part of qtsetup, but you could also have a "qtinit". Just like "omobile init".

All of this is really designed to lower the permutations of different ways to do things.

**Comment by therecipe** [comment]
No problem :) You are welcome.

I will update the readme asap.

I'm also all for lowering permutations and minimalism in general.
But the HomeBrew option on mac, like the PkgConfig option on linux allows the creation of really lightweight deployments that don't have to ship any dependencies, as they are expected to be already separately installed. And this is a really nice feature to have. If this wouldn't have been the case, I would probably have gone rid of them (HomeBrew, PkgConfig) already :)

And `qtinit` sounds like a good idea, I will keep that in mind.
This could also contain a function to update to a newer version of the binding more easily with
`qtinit update` or something.

**Comment by joeblew99** [comment]
Ah thats was my other question actually.
If i make a nice app with QT and want to package and deploy it for users, do the users have to install QT via homebrew ? Pretty important thing for real world development.
Please let me know..

Ok glad qtinit idea works for you. The init function should check if an update is needed and just do it, whilst telling the developer. This again ensures less issues raised and enforcing best practice. But maybe we can try either way and see what works based on issues raised.

**Comment by therecipe** [comment]
> If i make a nice app with QT and want to package and deploy it for users, do the users have to install QT via homebrew ?

If you use HomeBrew during deployment (`QT_HOMEBREW=true` or QT_DIR set to a HomeBrew Qt version), then the users have to install Qt via HomeBrew as well. And there should be a small `*.app` in `deploy/darwin_minimal`.

This is useful if you develop applications with HomeBrew users in mind. (If you want for example to create your own HomeBrew package, that pulls the Qt or other dependencies by itself.)

If you use the "official" Qt package instead, then the `*.app` should contain everything that is needed to run on any mac (even without Qt).

Yes, "force" updating can be nice as well. But it's also dangerous so I'm not sure about that.
But making it "safe" with asking a simple `Y/N` question before updating should work though.

**Comment by joeblew99** [comment]
ok thanks for the explanation - it really clears it up.
