### ISSUE TITLE
qtsetup is very slow on windows

### ISSUE THREAD

**Issue by overlordtm** [therecipe/qt#152]
While running qtsetup on linux takes maybe half an hour, on my Windows 7 64bit it is running since yesterday and still stuck at `installing full qt/widgets`.

Any idea what can I check why it is so slow. I have noticed that `widgets.go` is quite huge file, and I have bad experiences with compiling huge go files on windows. Right now memory usage for compiler is 3,5GB, while using almost 0% CPU.

Can you share specs of your windows build rig? I am building in Windows 7 64 bit VM (virtualbox). 2 CPU cores, 4GB ram. Qt 5.7 (downloaded form link provided in README). Go 1.7.3 amd64 from official site, MYSY2 system, but I am using MinGW compiler provided by Qt.

**Comment by overlordtm** [comment]
Seems like setting VM RAM to 8GB helps a lot :) Now it sucessfully installed everything in about 45 minutes, running tests now.

**Comment by therecipe** [comment]
Yes, you will require at least 8gb otherwise the installation is very slow ...
Also alternatively there is the STUB mode for systems with less ram.
https://github.com/therecipe/qt#full-or-stub-installation
