### ISSUE TITLE
Support for QtChart 

### ISSUE THREAD

**Issue by zfsamzfsam** [therecipe/qt#153]

**Comment by therecipe** [comment]
Hey

I will look into it.

**Comment by therecipe** [comment]
The QtCharts module is supported now with: https://github.com/therecipe/qt/commit/203995b2f4166e6adca46b5e3bae3cbd04de88bc

You may need to re-install both Qt (to check the box during the installation to install the chart module)
and this binding (you may need to clean your GOPATH/bin or GOBIN from all old qt* tools prior to
`go install github.com/therecipe/qt/cmd/...`)

I haven't tested the modules yet, but they should work.
