### ISSUE TITLE
Changing Layout of dock widget

### ISSUE THREAD

**Issue by Matt-Texier** [therecipe/qt#154]
Hi,

I am having problems trying to change default layout of a dock widget.

I tried to destroy existing layout like this: 

`ribManipDock.Layout().DestroyQObject()`
`var ribManipDockLayout = widgets.NewQHBoxLayout()`
`ribManipDock.SetLayout(ribManipDockLayout)`

It gets compiled ok but end up with a segmentation fault ...

I tried to get existing layout and try to work with it ... no joy as well while adding widget to it.

I tried to add a layout without touching anything in the dock ... doesn't work as well. Program complains during execution about adding a layout on top of an existing one ...  

Could you please guide me on how to solve this ?

(in CPP version dock doesn't come with any layout by default, you just need to add it to the dock ...).

Thanks Matt.

**Comment by therecipe** [comment]
Hey

I usually just use `setWidget` http://doc.qt.io/qt-5/qdockwidget.html#setWidget and if necessary create a wrapper widget with an layout.

Like this:

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	var window = widgets.NewQMainWindow(nil, 0)

	var dockwidget = widgets.NewQDockWidget("Hello", window, 0)

	var wrapper = widgets.NewQWidget(dockwidget, 0)
	var wrapperLayout = widgets.NewQVBoxLayout()
	wrapper.SetLayout(wrapperLayout)

	wrapperLayout.AddWidget(widgets.NewQPushButton2("left", wrapper), 0, core.Qt__AlignLeft)
	wrapperLayout.AddWidget(widgets.NewQPushButton2("center", wrapper), 0, core.Qt__AlignCenter)
	wrapperLayout.AddWidget(widgets.NewQPushButton2("right", wrapper), 0, core.Qt__AlignRight)

	dockwidget.SetWidget(wrapper)

	window.SetCentralWidget(dockwidget)
	window.Show()

	widgets.QApplication_Exec()
}
```

I don't know if you can directly set a layout for the dockwidget, I would have to port it over to c++ to test this.

**Comment by Matt-Texier** [comment]
Hey,

Thanks for your prompt reply :-) !

It is somehow getting better ... The dock appears on my UI however, when I try to detach it from the window and move it somewhere else ... core dump ...
Not sure it could help but that's what I get (the IO wait part is probably not related to UI but more to my gRPC socket being interrupted): No sure it helps.

Thanks Matt.

matthieu@matt-dev-box:~/go-work/src/github.com/Matt-Texier/local-mitigation-agent/UI$ ./deploy/linux_minimal/UI.sh 
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f3e072633f3]

runtime stack:
runtime.throw(0xb203c6, 0x2a)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x98e8b0, 0xc420175e50, 0x0)
	/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420175e20 sp=0xc420175de0
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0x0)
	??:0 +0x49 fp=0xc420175e50 sp=0xc420175e20
github.com/therecipe/qt/widgets.QApplication_Exec(0xc42012f1b0)
	/home/matthieu/go-work/src/github.com/therecipe/qt/widgets/widgets-minimal.go:1270 +0x22 fp=0xc420175e68 sp=0xc420175e50
main.main()
	/home/matthieu/go-work/src/github.com/Matt-Texier/local-mitigation-agent/UI/gobgpClientMain.go:111 +0x54c fp=0xc420175f38 sp=0xc420175e68
runtime.main()
	/usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420175f90 sp=0xc420175f38
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420175f98 sp=0xc420175f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 7 [syscall]:
os/signal.signal_recv(0xc42002bfa8)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 36 [IO wait]:
net.runtime_pollWait(0x7f3e08018f40, 0x72, 0x3)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420202140, 0x72, 0xc420226b08, 0xc42000c1e0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420202140, 0x1081120, 0xc42000c1e0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4202020e0, 0xc420204000, 0x8000, 0x8000, 0x0, 0x1081120, 0xc42000c1e0)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420132200, 0xc420204000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc420168420)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc420168420, 0xc4201f80f8, 0x9, 0x9, 0x9, 0x18, 0x28)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x107dae0, 0xc420168420, 0xc4201f80f8, 0x9, 0x9, 0x9, 0x44de78, 0x30, 0xc420226d18)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x107dae0, 0xc420168420, 0xc4201f80f8, 0x9, 0x9, 0xf0ad37fff0b2b401, 0xf000000000000000, 0x2)
	/usr/local/go/src/io/io.go:325 +0x58
golang.org/x/net/http2.readFrameHeader(0xc4201f80f8, 0x9, 0x9, 0x107dae0, 0xc420168420, 0x0, 0xc400000000, 0x0, 0x0)
	/home/matthieu/go-work/src/golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc4201f80c0, 0x10825e0, 0xc42016c660, 0x0, 0x0)
	/home/matthieu/go-work/src/golang.org/x/net/http2/frame.go:464 +0xa4
google.golang.org/grpc/transport.(*framer).readFrame(0xc42016b500, 0xc42016c660, 0xc42016c660, 0x0, 0x0)
	/home/matthieu/go-work/src/google.golang.org/grpc/transport/http_util.go:508 +0x2f
google.golang.org/grpc/transport.(*http2Client).reader(0xc420214000)
	/home/matthieu/go-work/src/google.golang.org/grpc/transport/http2_client.go:975 +0xbc
created by google.golang.org/grpc/transport.newHTTP2Client
	/home/matthieu/go-work/src/google.golang.org/grpc/transport/http2_client.go:210 +0x9ca

goroutine 37 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc420214000)
	/home/matthieu/go-work/src/google.golang.org/grpc/transport/http2_client.go:1053 +0x5b5
created by google.golang.org/grpc/transport.newHTTP2Client
	/home/matthieu/go-work/src/google.golang.org/grpc/transport/http2_client.go:240 +0xf97

goroutine 38 [select]:
google.golang.org/grpc.(*addrConn).transportMonitor(0xc4201e8000)
	/home/matthieu/go-work/src/google.golang.org/grpc/clientconn.go:753 +0x63e
created by google.golang.org/grpc.(*ClientConn).resetAddrConn
	/home/matthieu/go-work/src/google.golang.org/grpc/clientconn.go:496 +0x6de
matthieu@matt-dev-box:~/go-work/src/github.com/Matt-Texier/local-mitigation-agent/UI$

**Comment by therecipe** [comment]
No problem :)

Ah, IIRC you need to add the dockwidget with `*.AddDockWidget` like it's shown here: https://github.com/5k3105/AM/blob/master/main.go#L64-L65

I replaced `SetCentralWidget` with `AddDockWidget` in the example above and it works now.

**Comment by Matt-Texier** [comment]
Thanks, found another issue in my code (sharing if it could help others) ... and if I may, I would suggest to update the following example:

[https://github.com/therecipe/qt/blob/master/internal/examples/widgets/line_edits/line_edits.go](url)

I cannot explain why, but those lines of code do have serious side effect ... and avoid to have dock attached to the main window:

`var window = widgets.NewQMainWindow(nil, 0)`
`window.Layout().DestroyQObject()`
`window.SetLayout(layout)`

I changed for the SetCentralWidget approach as in your code and all is working fine now ...

Thanks for your help,
Matt.

**Comment by therecipe** [comment]
Oh, I should have re-read http://doc-snapshots.qt.io/qt5-5.8/qmainwindow.html#details

Seems like QMainWindow expects a centralWidget and even explains that the default (unique) QMainWindow layout is needed to get QDockWidget, QToolBars and such working ...

This explains probably a few of the issues I had some time ago, that I couldn't track down.

I will update all examples.

Thank you for reporting :)

**Comment by therecipe** [comment]
Updated the examples with https://github.com/therecipe/qt/commit/8318f0c212c2d34a84e0bdaf6ece20dbc33670a1

**Comment by 5k3105** [comment]
```go
window.AddDockWidget(core.Qt__LeftDockWidgetArea, Panel)```
