### ISSUE TITLE
Support for URL Interception

### ISSUE THREAD

**Issue by JonathanLogan** [therecipe/qt#155]
Currently it seems to be impossible to instantiate a QWebEngineUrlRequestInterceptor which allows for the implementation of interceptRequest.
A change would be appreciated (feature-bounty might be available....)

**Comment by therecipe** [comment]
Hey

The class should be supported now with https://github.com/therecipe/qt/commit/986dd10067c4a5065300126d7536e65b0b6b2ec8

> A change would be appreciated (feature-bounty might be available....)
Thank you I appreciate it, but it wasn't too much of a hassle to get it working :)

**Comment by JonathanLogan** [comment]
Big "thank you" for that fast fix. For this interested, here's code how to use it:
`
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/webengine"
	"github.com/therecipe/qt/widgets"
)

func main() {
	app := widgets.NewQApplication(len(os.Args), os.Args)
	_ = app
	view := webengine.NewQWebEngineView(nil)
	profile := webengine.NewQWebEngineProfile(view)
	interceptor := webengine.NewQWebEngineUrlRequestInterceptor(view)
	interceptor.ConnectInterceptRequest(func(info *webengine.QWebEngineUrlRequestInfo) {
		fmt.Printf("Host: %s\n", info.RequestUrl().Host(core.QUrl__FullyDecoded))
	})
	profile.SetRequestInterceptor(interceptor)
	page := webengine.NewQWebEnginePage2(profile, view)
	view.SetPage(page)
	view.SetUrl(core.QUrl_FromUserInput("http://github.com/therecipe/qt/"))
	view.Show()
	widgets.QApplication_Exec()
}
`
