### ISSUE TITLE
QWindow.FromWinId ?

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#16]
Will 'FromWinId' be supported? (http://doc.qt.io/qt-5/qwindow.html#fromWinId)
```go
	var hw win.HWND
	...
	hw = win.FindWindow(nil, syscall.StringToUTF16Ptr(windowName))

	widgets.NewQApplication(len(os.Args), os.Args)

	var window = widgets.NewQMainWindow(nil, 0)

	w := gui.NewQWindow(nil)
	w.FromWinId(hw)
	x := widgets.CreateWindowContainer(w, nil, 0)

	window.SetCentralWidget(x)
	window.ShowMaximized()
	widgets.QApplication_Exec()
```

**Comment by therecipe** [comment]
Hey

I will look into this.

**Comment by therecipe** [comment]
I added the support for WinIds.

This example should work now:

```go
package main

import (
	"fmt"
	"os"
	"syscall"

	"github.com/lxn/win"

	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {

	widgets.NewQApplication(len(os.Args), os.Args)

	var (
		testWindowName = "TestWindow"
		testWindow     = widgets.NewQMainWindow(nil, 0)
		testButton     = widgets.NewQPushButton2(testWindowName, nil)
		testLayout     = widgets.NewQVBoxLayout()
	)
	testWindow.SetWindowTitle(testWindowName)
	testLayout.AddWidget(testButton, 0, 0)
	testWindow.Layout().DestroyQObject()
	testWindow.SetLayout(testLayout)
	testWindow.Show()

	var (
		hw = win.FindWindow(nil, syscall.StringToUTF16Ptr(testWindowName))

		mainWindow = widgets.NewQMainWindow(nil, 0)

		//testWindowFromId = gui.QWindow_FromWinId(testWindow.WinId())
		testWindowFromId = gui.QWindow_FromWinId(uintptr(hw))

		testWindowContainer = widgets.QWidget_CreateWindowContainer(testWindowFromId, nil, 0)
	)

	mainWindow.SetWindowTitle(fmt.Sprintf("TestWindowIds: %v %v", testWindow.WinId(), uintptr(hw)))

	mainWindow.SetCentralWidget(testWindowContainer)
	mainWindow.Show()

	widgets.QApplication_Exec()
}
```

**Comment by 5k3105** [comment]
C:\Users\5k3105\goworksp\src\github.com\therecipe\qt (master)
	λ setup.bat

	go run ./internal/setup/check.go

	if 0 NEQ 0 exit /b 0

	go run C:\Users\5k3105\goworksp;C:\Users\5k3105\goworksp\bin;C:\Users\5k3105\goworksp\local/src/github.com/therecipe/qt/internal/setup/generate.go
	GetFileAttributesEx C:\Users\5k3105\goworksp;C:\Users\5k3105\goworksp\bin;C:\Users\5k3105\goworksp\local/src/github.com/therecipe/qt/internal/setup/generate.go: The filename, directory name, or volume label syntax is incorrect.

	if 1 NEQ 0 exit /b 1

**Comment by therecipe** [comment]
You set the GOPATH to: `C:\Users\5k3105\goworksp;C:\Users\5k3105\goworksp\bin;C:\Users\5k3105\goworksp\local`

So, you need to simplify the GOPATH or replace `%GOPATH%/src/github.com/therecipe/qt` in the [generate.go](https://github.com/therecipe/qt/blob/master/setup.bat) file with `.` to use a relative path.

**Comment by 5k3105** [comment]
Works great! Thank you!
And compile times are Amazing!!

**Comment by therecipe** [comment]
You are welcome :)
