### ISSUE TITLE
responsive layouts

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#161]
On all the variety of mobiles out there, you need a strategy to manage how the screen layout changes based on the Screen aspect ratio & the Pixel density.

http://doc.qt.io/qt-5/scalability.html, so maybe I will create a small example.

I am looking for examples too :)

**Comment by joeblew99** [comment]
i think that this QML sample is a perfect example for responsive design.
https://github.com/ekke/drawer_nav_x

It uses loaders to allow different screens to be loaded when needed, which is nails the worst case scenario when you just must have a different screen layout for different devices.

What you we think about making the slight changes in the cpp so it works with golang ?

**Comment by therecipe** [comment]
Hey

> On all the variety of mobiles out there, you need a strategy to manage how the screen layout changes based on the Screen aspect ratio & the Pixel density.

Yes, there really should be an example for this.

> What you we think about making the slight changes in the cpp so it works with golang ?

I will look into it and report back.

**Comment by therecipe** [comment]
I ported the example with https://github.com/therecipe/qt/commit/dde655ca0e85d4c0802e7320d6413bf7555c61ca

You can find it here: https://github.com/therecipe/qt/tree/master/internal/examples/qml/drawer_nav_x

It was pretty simple, I just needed to make some minor changes in the qml files to find the images under the new path (`qrc:/qml/images/...` instead of `qrc:/images/...`)

**Comment by joeblew99** [comment]
thats super. Really encouraging too how easy it was to port. 

i will try this out.

**Comment by therecipe** [comment]
I updated the example with https://github.com/therecipe/qt/commit/e201af8a0fed43d8a1edddc912ebe777eb7bc052 after I solved this issue https://github.com/therecipe/qt/issues/162

This change makes it simpler to convert old QML projects from C++ to Go, because the qml files can stay untouched now.

**Comment by joeblew99** [comment]
ok will close this and try it out.

When we get the LiriOS sample going (now that the QML code does not need so much hand conversion) it will be nice to see how well it handle Responsive layouts between Desktop and Mobile.
