### ISSUE TITLE
Setting IntelliJ IDEA to run qtrcc as external tool before running project results in panic

### ISSUE THREAD

**Issue by akamensky** [therecipe/qt#164]
I have Qt 5.7.1 installed. Thus installation directory is (as default on Mac OS) `/Users/username/Qt5.7.1`

I have built the tools with appropriate `QT_DIR` env var set to the installation directory (it simply would not build if I pointed to the wrong directory or didn't set it at all).

I setup IntelliJ IDEA to run `qtrcc` as follows: Edit configurations -> (Choose configuration) -> Before launch -> "+" -> Run external tool -> "Name: qtrcc; Program: $ProjectFileDir$/bin/qtrcc; Working directory: $ProjectFileDir$/src/main/"

Running project in this configuration results in:

```
/Users/username/IdeaProjects/project/bin/qtrcc
time="2016-12-30T14:12:10+08:00" level=panic msg="failed to run command" cmd="/Users/username/Qt5.7.0/5.7/clang_64/bin/rcc -project -o /Users/username/IdeaProjects/project/src/main/rrc.qrc" error="fork/exec /Users/username/Qt5.7.0/5.7/clang_64/bin/rcc: no such file or directory" func=RunCmd name="execute rcc.1 on darwin" output= 
panic: (*logrus.Entry) (0xe10e0,0xc420016aa0)

goroutine 1 [running]:
panic(0xe10e0, 0xc420016aa0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/Sirupsen/logrus.Entry.log(0xc420016190, 0xc4200108a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420035a00, ...)
	/Users/username/IdeaProjects/project/src/github.com/Sirupsen/logrus/entry.go:124 +0x423
github.com/Sirupsen/logrus.(*Entry).Panic(0xc420016a50, 0xc4200c5af8, 0x1, 0x1)
	/Users/username/IdeaProjects/project/src/github.com/Sirupsen/logrus/entry.go:169 +0x124
github.com/therecipe/qt/internal/utils.RunCmd(0xc420082580, 0xc4200124c0, 0x17, 0x1, 0x1)
	/Users/username/IdeaProjects/project/src/github.com/therecipe/qt/internal/utils/utils.go:81 +0x56e
main.main()
	/Users/username/IdeaProjects/project/src/github.com/therecipe/qt/cmd/qtrcc/qtrcc.go:71 +0x5b6

Process finished with exit code 2
```

Obviously the issue is that even though the tool were built with QT_DIR set to appropriate location, they won't work without setting QT_DIR env var.

In IntelliJ IDEA there is no way to set env var separately for external tool. So I hope there would be some other way, as having program to execute from IDE with all resources loaded would be very nice and useful for proper debugging.

Possible solution is to have $(GOPATH)/.qtrc file that would contain needed settings (e.g. QT_DIR location). **please note** I would hope it to be $(GOPATH)/.qtrc and not the location given to qtrcc as project path (which currently is a module in the project, so I have to always do ./bin/qtrcc ./src/module_name/ and I always have to put the resources in the module directory as they won't be picked up from other locations...)

**Comment by therecipe** [comment]
> In IntelliJ IDEA there is no way to set env var separately for external tool. So I hope there would be some other way, as having program to execute from IDE with all resources loaded would be very nice and useful for proper debugging.

Yes, that would be useful indeed.
Strange that IntelliJ IDEA doesn't provide a way to set env variables.

> Possible solution is to have $(GOPATH)/.qtrc file that would contain needed settings (e.g. QT_DIR location).

Yes, that could be a work-around. But I'm not sure if it's good to introduce config files at all.
I hoped to get it working with environmental variables only.

Could you maybe instead wrap `qtrcc` for your needs inside a script like this?
```
set QT_DIR=path/to/qt
path/to/qtrcc path/to/project
```
 
Btw, does 5.7.1 work properly for you?
I tested it and had some problems while deploying some qml/quick examples.

**Comment by akamensky** [comment]
5.7.1 works fine for me. No problem at all. I use it because they have fixed quite a few bugs there. 

As for wrapper script - that could work but then I again need to include this wrapper script with my project sources which is not that different from .qtrc IMO

**Comment by therecipe** [comment]
What about if I add a flag to `qtrcc`, so that the QT_DIR can be defined with something like
`qtrcc -qt_dir=...` as well?

**Comment by akamensky** [comment]
I think that will work fine

**Comment by therecipe** [comment]
Okay, added the flag with https://github.com/therecipe/qt/commit/8e6d46d68e6b1733ae88ba6cd9a4e96c39704205

So you should be able to define an alternative QT_DIR with `qtrcc -qt_dir=...`

**Comment by akamensky** [comment]
Confirmed, it works as expected with this argument and can run it from IDEA without any problem.

Can close this one I guess.

New issue was introduced tho see #172

**Comment by akamensky** [comment]
Closing.
