### ISSUE TITLE
Add `Stringer` Generator to Enums (for debugging)

### ISSUE THREAD

**Issue by KellyLSB** [therecipe/qt#168]
You already know how to do this, probably but for those who don't: https://blog.golang.org/generate

Consider https://github.com/therecipe/qt/blob/0329327628516a871009849ee9aa2003990ac75c/quick/quick.go#L8825 as:
```
//go:generate stringer -type=QQuickView__Status
//QQuickView::Status
type QQuickView__Status int64

const (
	QQuickView__Null    = QQuickView__Status(0)
	QQuickView__Ready   = QQuickView__Status(1)
	QQuickView__Loading = QQuickView__Status(2)
	QQuickView__Error   = QQuickView__Status(3)
)
```

The running `go generate` will create `qquickview__status_stringer.go` (or similar; add `_stringer.go` to `.gitignore`) with the contents:
```
package quick

import "fmt"

const _QQuickView__Status_name = "QQuickView__NullQQuickView__ReadyQQuickView__LoadingQQuickView__Error"

var _QQuickView__Status_index = [...]uint8{0, 16, 33, 50}

func (i QQuickView__Status) String() string {
    if i < 0 || i+1 >= QQuickView__Status(len(_QQuickView__Status_index)) {
        return fmt.Sprintf("QQuickView__Status(%d)", i)
    }
    return _QQuickView__Status_name[_QQuickView__Status_index[i]:_QQuickView__Status_index[i+1]]
}
```

**Comment by therecipe** [comment]
Hey 

Thanks for the pull request :)
It's indeed useful for debuging, I totaly forgot that the stringer existed.

I also tested to let `qtsetup` invoke `go generate` during the "setup", but then the whole process took another 4-5 min longer. So I discarded that.
