### ISSUE TITLE
can it work for android sdk 5.1?

### ISSUE THREAD

**Issue by JoeyYYF** [therecipe/qt#177]
We intend to use this develop android app,our android version is 5.1.So can it works?or it can only work for the android 7?

**Comment by therecipe** [comment]
Hey

Yes, it should work with android 4.1 (api level 16) and higher.
https://developer.android.com/guide/topics/manifest/uses-sdk-element.html#ApiLevels

**Comment by JoeyYYF** [comment]
Thanks!Another,can it use qt Creator for visual programming such as UI layout or it just all in code?

**Comment by therecipe** [comment]
Yes, you can use the ui designer to load *.ui files with the `uitools` package.
An example can be found [here](https://github.com/therecipe/qt/tree/master/internal/examples/uitools/calculator)

And the Qml/Quick Designer outputs *.qml files which can be directly used as usual.

But you can as well just write everything in code.

**Comment by JoeyYYF** [comment]
Great！Thanks
