### ISSUE TITLE
godoc can't handle widgets docs

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#178]
```HTTP response was too large: 33554637. The limit is: 33554432.```

I was hoping it was chrome, but firefox won't show it either (on my machine Win7).

I think this may fall under "not qt binding's problem". I'm perfectly ok just using ctl-f on the source file :)

**Comment by therecipe** [comment]
Hey

Yes, the web version of godoc has problems with the "widgets" package.

You could however setup a local server yourself with `godoc -http :8080` and then access it under `http://localhost:8080/pkg/github.com/therecipe/qt/widgets/`

Or directly use godoc from the command line with something like
`godoc github.com/therecipe/qt/widgets QPushButton`

**Comment by 5k3105** [comment]
Sorry. Thanks. For some reason my setup was not right and wouldn't index. I reinstalled the bindings and godoc works fine now.
