### ISSUE TITLE
qtsetup: cmd option to limit cpu usage

### ISSUE THREAD

**Issue by fabstu** [therecipe/qt#179]
Can I somehow limit memory use? Durcing qtsetup 8 cpu's are in full use most of time, 13 GB of memory is used and cache can be found on ssd swap with20GB and rising. And iotop got heavy activity.

All in all my computer is unresponsive during that time and I did not try to let it run through yet.

Anyway I don't think qtsetup is supposed to stop me using my computer during setting things up?

**Comment by fabstu** [comment]
Nevermind, interestingly it ran through with neither stopping somewhere nor use of any swap. Thanks anyway!

**Comment by therecipe** [comment]
Hey

I can maybe add a flag to `qtsetup` to limit the amount of cpus used, but I probably can't limit the memory usage. The reason therefore is, that simply installing the packages with `go install ...` is very resource intensive, because of the amount of cgo code that is used.

**Comment by fabstu** [comment]
That would probably work nicely, can you do that?

**Comment by therecipe** [comment]
Yes, I'm working on it. Will push the changes later today.

**Comment by fabstu** [comment]
Thank you!

**Comment by therecipe** [comment]
You are welcome :)
With https://github.com/therecipe/qt/commit/fdef10e5ac52b888704ee5c92d2f4adc720a2a95 it  should be possible to define the number of cpu's used during the setup with the `-p` flag.
Like this: `qtsetup -p 1`

**Comment by fabstu** [comment]
Very nice!
