### ISSUE TITLE
Setting IntelliJ IDEA to run qtmoc as external tool before running project is not working

### ISSUE THREAD

**Issue by akamensky** [therecipe/qt#180]
Same as issue #164

The problem is that `qtmoc` produces machine dependent files, so resulting files should not be added to the repository.

It is not possible to set env vars for external tools in IDEA, but qtmoc uses env vars `QT_DIR` and `QT_VERSION` to determine location of Qt installation and of headers inside that directory.

In my case version is 5.7.1 which is different from default 5.7.0, I suggest either adding CLI arguments (as was done for issue #164) to the tool, or add more general `.qt_profile` config file (and use it as alternative to env vars)

**Comment by therecipe** [comment]
Hey

With https://github.com/therecipe/qt/commit/8a83cb4e3e44dd412f5e6ebaca289404e329c2a2 all tools got support for the `qt_version` and `qt_dir` flag.
Also the right version should be detected now automatically for a "normal" or HomeBrew Qt installation, if a valid QT_DIR is set (either as env or via flag)

And flags have the highest priority now, so they will always override env variables.

**Comment by akamensky** [comment]
Yes, works on 8a83cb4. Closing this issue then.
