### ISSUE TITLE
CheckState: Checked and Unchecked constants

### ISSUE THREAD

**Issue by fabstu** [therecipe/qt#188]
I'm using tables and its nice so far. One thing I noticed is, that if you use the CheckStateRole, there's no constants for Checked and Unchecked.

Maybe I haven't found them, anyway they would be just conenience, since they are easy to look up.

Cheers!

Docs:
CheckDataRole is value 10 here and is already present in your code: http://doc.qt.io/qt-5.7/qt.html#ItemDataRole-enum

Values for the constants which I could not find: http://doc.qt.io/qt-5.7/qt.html#CheckState-enum

**Comment by therecipe** [comment]
Hey

Those should be available as:

```go
core.Qt__Checked
core.Qt__Unchecked
core.Qt__PartiallyChecked
```

**Comment by fabstu** [comment]
Ah I'm usually searching in local godoc and here repo too, but it seems I only searched godoc with Checkable, but subsequent Checked/Unchecked just in github repo. Thanks!
