### ISSUE TITLE
A build fails on Windows 10

### ISSUE THREAD

**Issue by AnyCPU** [therecipe/qt#194]
Windows 10 64 bit.
I did all commands in the msys2 console and then I got

$GOPATH/bin/qtsetup
time="2017-01-14T20:46:10+02:00" level=info msg="running setup/prep"
time="2017-01-14T20:46:10+02:00" level=info msg="running setup/check desktop"
time="2017-01-14T20:46:10+02:00" level=info msg="VERSION: 0.0.4"
time="2017-01-14T20:46:10+02:00" level=info msg="GOOS: windows"
time="2017-01-14T20:46:10+02:00" level=info msg="GOARCH: amd64"
time="2017-01-14T20:46:10+02:00" level=info msg="GOVERSION: go1.7.4"
time="2017-01-14T20:46:10+02:00" level=info msg="GOROOT: C:/Go"
time="2017-01-14T20:46:10+02:00" level=info msg="GOPATH: C:/gqt"
time="2017-01-14T20:46:10+02:00" level=info msg="GOBIN: C:\\gqt\\bin"
time="2017-01-14T20:46:10+02:00" level=info msg="HASH: 6f05f39db9444871e7cb8fa05592836e77a78fbc"
time="2017-01-14T20:46:10+02:00" level=info msg="QT_VERSION: 5.7.0"
time="2017-01-14T20:46:10+02:00" level=info msg="QT_VERSION_MAJOR: 5.7"
time="2017-01-14T20:46:10+02:00" level=info msg="QT_DIR: C:\\Qt\\Qt5.7.0"
time="2017-01-14T20:46:10+02:00" level=info msg="QT_STUB: true"
time="2017-01-14T20:46:10+02:00" level=info msg="MSYSTEM: MSYS"
time="2017-01-14T20:46:10+02:00" level=info msg="QT_MSYS2: true"
time="2017-01-14T20:46:10+02:00" level=info msg="QT_MSYS2_DIR: "
time="2017-01-14T20:46:10+02:00" level=info msg="IsMsys2QtDir: false"
time="2017-01-14T20:46:10+02:00" level=info msg="UseMsys2: true"
time="2017-01-14T20:46:10+02:00" level=info msg="running setup/generate"
time="2017-01-14T20:46:14+02:00" level=error msg="failed to load C:\\msys64\\mingw32\\include\\QtGui\\5.7.0\\QtGui\\qpa\\qplatformgraphicsbuffer.h" error="open C:\\msys64\\mingw32\\include\\QtGui\\5.7.0\\QtGui\\qpa\\qplatformgraphicsbuffer.h: The system cannot find the path specified."
time="2017-01-14T20:46:14+02:00" level=error msg="failed to load C:\\msys64\\mingw32\\include\\QtGui\\5.7.0\\QtGui\\qpa\\qplatformsystemtrayicon.h" error="open C:\\msys64\\mingw32\\include\\QtGui\\5.7.0\\QtGui\\qpa\\qplatformsystemtrayicon.h: The system cannot find the path specified."
time="2017-01-14T20:46:18+02:00" level=error msg="failed to load C:\\msys64\\mingw32\\include\\QtUiTools\\quiloader.h" error="open C:\\msys64\\mingw32\\include\\QtUiTools\\quiloader.h: The system cannot find the path specified."
time="2017-01-14T20:46:19+02:00" level=info msg="generating stub qt/core"
time="2017-01-14T20:46:38+02:00" level=info msg="generating stub qt/androidextras"
time="2017-01-14T20:46:38+02:00" level=info msg="generating stub qt/gui"

...

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libuser32.a when searching for -luser32
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -luser32
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libkernel32.a when searching for -lkernel32
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib\libkernel32.a when searching for -lkernel32
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libkernel32.a when searching for -lkernel32
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lkernel32
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libmingwthrd.a when searching for -lmingwthrd
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib\libmingwthrd.a when searching for -lmingwthrd
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libmingwthrd.a when searching for -lmingwthrd
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwthrd
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libmingw32.a when searching for -lmingw32
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib\libmingw32.a when searching for -lmingw32
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libmingw32.a when searching for -lmingw32
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingw32
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/libgcc.a when searching for -lgcc
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0\libgcc.a when searching for -lgcc
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/libgcc.a when searching for -lgcc
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/libgcc_eh.a when searching for -lgcc_eh
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0\libgcc_eh.a when searching for -lgcc_eh
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/libgcc_eh.a when searching for -lgcc_eh
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc_eh
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libmoldname.a when searching for -lmoldname
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib\libmoldname.a when searching for -lmoldname
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libmoldname.a when searching for -lmoldname
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmoldname
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libmingwex.a when searching for -lmingwex
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib\libmingwex.a when searching for -lmingwex
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libmingwex.a when searching for -lmingwex
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwex
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for -lmsvcrt
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib\libmsvcrt.a when searching for -lmsvcrt
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for -lmsvcrt
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt
collect2.exe: error: ld returned 1 exit status

Is there a native way for Windows to make a build?

**Comment by therecipe** [comment]
Hey

Did you installed the 32-bit package? `pacman -S mingw-w64-i686-...` or the 64-bit?
If you installed the 32-bit package, then you need to use the mingw32 shell otherwise you need to use the ming64 shell.

Here is a related issue https://github.com/therecipe/qt/issues/166#issuecomment-270017504 maybe some info there might help you as well.

>Is there a native way for Windows to make a build?

You could use the "official" Qt pre-build package, which doesn't depend on msys2.
Or did you meant something else?

**Comment by AnyCPU** [comment]
@therecipe I have installed the 64 bit package. But I made a mistake because of the msys2 launches a 32 bit shell on a 64 bit os.
I started building again and I still get strange warnings. 
At the moment I'm getting application windows. So, as I understand it is ok and I get exactly what is written in go's code.

**Comment by therecipe** [comment]
>I started building again and I still get strange warnings.

There can be warnings, but as long as the setup continues and the examples show up in the end, everything is good.

**Comment by AnyCPU** [comment]
@therecipe 
> You could use the "official" Qt pre-build package, which doesn't depend on msys2.
Yes, I did. 
For example, I have: a installed ms' build tools, a downloaded qt's binaries, all paths in the PATH env var.
And all what I need is `go get ...` command.

But I think that the go compiler doesn't support an output of the ms build tools.

**Comment by AnyCPU** [comment]
@therecipe Tests have been done. I think, all is ok.

**Comment by therecipe** [comment]
Okay, yes if the test are successful.
Then the rest should work as well.
