### ISSUE TITLE
Having problems running <filename>.sh file on rpi2

### ISSUE THREAD

**Issue by gabeart10** [therecipe/qt#196]
I could not run the test.sh because I get a `* failed to add service - already in use?` I am trying to solve this right now, but if anyone has idea they would be appreciated.

**Comment by gabeart10** [comment]
Ok, the `dtoverlay=vc4-kms-v3d,cma-256` line in the config.txt was braking it I commented it out and it started working. I would look into this.

**Comment by therecipe** [comment]
Hey

Ah, yes I should probably update the readme.
I didn't explicitly stated to use the *.sh like I did in the linux instructions.

And I will change the instruction about the `dtoverlay`, currently the warning is written after the command to change the `config.txt`. So I will put the warning in front and make it clear that this is an experimental setting.

But does it work so far?
I only directly tested it on a rpi1 and rpi3, so it would be nice to get a confirmation that it's properly working on a rpi2 as well.

**Comment by gabeart10** [comment]
Yes, it is working fine

**Comment by therecipe** [comment]
Nice, thank you :)
