### ISSUE TITLE
How to pass LDFLAGS  into cmd when using qtdeploy?

### ISSUE THREAD

**Issue by quantonganh** [therecipe/qt#198]
Hi @therecipe,

What is different between using `go build`  and `qtdeploy`?

How can I pass `LDFLAGS`  into cmd when using `qtdeploy`?

something like this when using `go build`:

```
go build -v -ldflags=...
```

**Comment by therecipe** [comment]
@quantonganh 

>What is different between using go build and qtdeploy?

qtdeploy  calls `qtrcc`, `qtmoc`, `qtminimal` then `go build -tags=minimal ...` (with the right env variables + path to cross compilers if necessary) and it does additional steps to bundle the libs with the binary to make it a stand alone application in the end. 

>How can I pass LDFLAGS into cmd when using qtdeploy?
something like this when using go build:
go build -v -ldflags=...

The `-ldflags` is currently not supported, as well as the other `go build` flags.
But you could put them into a comment above `import "C"` in your code.
(Maybe look at the cgo* files)

So something like this should work:
```go
package main

// #cgo LDFLAGS: -L/go/src/foo/libs -lfoo
import "C"
```

Here are some more infos: https://golang.org/cmd/cgo/

**Comment by therecipe** [comment]
`qtdeploy -ldflags="..." build desktop` should work now with https://github.com/therecipe/qt/commit/e3e91ae71b2e4ccb60e36d5d87c936f6ac5c899d
