### ISSUE TITLE
Would it possible to support return value for slot?

### ISSUE THREAD

**Issue by longlongh4** [therecipe/qt#20]
How to get return value from slot ?
for example:

    type SignalHandler struct {
	core.QObject
	_ func(a int, b int) int           `slot:sum`   
    }

How to get result of the sum function?

**Comment by therecipe** [comment]
I pushed the changes https://github.com/therecipe/qt/commit/100b0677bdd545c75f0a7ad1cfb4266010b9134b
It should work now :)

**Comment by longlongh4** [comment]
Works perfectly !!!
