### ISSUE TITLE
Redux pattern for at with golang

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#200]
An open ended questions here in terms of design.

What is the best way to maintain state between you qml views and your golang database or code ?

I am playing with some ideas....

A boltdb database that emits events when data changes. Each qml view subscribes to these events.

Instead of a database, use a redux store technique.

Sorry about opening up an issue which is really more of a design thing, but I started to write a boltdb database to do this and am hoping I can get some feedback about the approaches others have taken.

I would like to finish the component and submit a example to the repo eventually for others too.

**Comment by therecipe** [comment]
Hey

I'm not really familiar with boltdb or redux (https://github.com/reactjs/redux ?).

But 
>A boltdb database that emits events when data changes. Each qml view subscribes to these events.

sounds good to me, but I'm no expert.

Also here are some great slides, about best practice with qml http://www.slideshare.net/ICSinc/best-practices-in-qt-quick-qml-part-1, some of them go more into detail about state and mvc.
They might be interesting.

>I would like to finish the component and submit a example to the repo eventually for others too.

Sounds great :) let me know when you have something.

**Comment by joeblew99** [comment]
thanks for the links to the slides. i will digest and come back :)

Some points:
Boltdb runs on mobiles and desktops with no issues. So its an ideal KV store with QT i feel, but others may not of course. 
BoltDB has some very nice overlay to make querying easy as pie. This is an ORM over boltdb.
https://github.com/asdine/storm
You can storm data as JSON or protocol buffers. Nice.


Leaving this open for others to find for now for discussion wtc...

**Comment by joeblew99** [comment]
@therecipe  really good slides !!!

Whats the best example, do you think, showing off the use of QT binding techniques in the current internal examples ?  I

**Comment by joeblew99** [comment]
https://github.com/therecipe/qt/blob/master/internal/examples/sql/querymodel/main.go

This looks like a good base to start from.
But it does not show how to do data binding both ways.

Also it's using a generic table view.
Would be cool to see it working with a proper qml widget. 

The classic need us what is often called the Master / Detail pattern.
Master is the table view.
Detail is the new page where you see a form that represents a row from the Master Table View. You edit some data, fire validation checking, and save the data to the DB.

Then I can get boltdb and goleveldb working with the same example.

He project is over at github/gu-io.
We are getting QT working with lots of standard golang libraries

**Comment by therecipe** [comment]
>BoltDB has some very nice overlay to make querying easy as pie. This is an ORM over boltdb.
https://github.com/asdine/storm
You can store data as JSON or protocol buffers. Nice.

Yeah, that would probably work great.

>Whats the best example, do you think, showing off the use of QT binding techniques in the current internal examples ?

Here is an example, but the model + view is both in qml and there is only a signal emitted to go, when the data changes.
https://github.com/therecipe/qt/tree/master/internal/examples/quick/tableview

I should probably create an example where the model is in go, so something like this:
https://github.com/therecipe/qt/issues/140#issuecomment-274301807
So that it can be easily extended to use boltdb/storm.
But I will probably have to solve the generic list / container problem first, so that [this](http://doc.qt.io/qt-5/qabstractitemmodel.html#dataChanged) function is available.

>He project is over at github/gu-io.
We are getting QT working with lots of standard golang libraries

Looks interesting :)
Is that the project where you want to use `fluid`?

**Comment by therecipe** [comment]
@joeblew99 

generic lists / containers are now supported with: 
https://github.com/therecipe/qt/commit/3456e5280a438b31c6c4529ef86e465ba190ef7d

>This looks like a good base to start from.
But it does not show how to do data binding both ways.
Also it's using a generic table view.
Would be cool to see it working with a proper qml widget.

this example here is just one way from go -> qml
https://github.com/therecipe/qt/tree/master/internal/examples/quick/listview

but I will create another one with an editable table, that shows it works from qml -> go

**Comment by joeblew99** [comment]
Thanks this is awesome to get going ...

**Comment by joeblew99** [comment]
Will close now as this helped me alot
