### ISSUE TITLE
Support for qmlRegisterSingletonType

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#202]
Hi,

It would be nice if we can register singleton type from go. As you mentioned on our chat before, adding second override would be very helpful i.e. this one : http://doc.qt.io/qt-5/qqmlengine.html#qmlRegisterSingletonType-2.

Thanks.

**Comment by arknable** [comment]
I added a c++ sample here: https://github.com/arknable/therecipe-issue.

**Comment by therecipe** [comment]
>I added a c++ sample here: https://github.com/arknable/therecipe-issue.

Great, thank you :)

**Comment by therecipe** [comment]
@arknable 

Should work now with https://github.com/therecipe/qt/commit/45ca69a6d71a1226e2d851740c483f3582e3d94b

The function is now a member of `QQmlEngine` and can be used like this

```
app.QmlRegisterSingletonType(core.NewQUrl3("qrc:///qml/core/UITheme.qml", 0), "Core", 1, 0, "UITheme")
```
in your example.

I removed everything c++ related (*.cpp, *.pro) to test it.

```
.
├── application.go
└── qml
    ├── core
    │   ├── UISettings.qml
    │   └── UITheme.qml
    ├── imports
    │   └── Core
    │       └── qmldir
    └── main.qml
```

and got: `qml: #90c3d4` (like in the original c++ version)

**Comment by arknable** [comment]
I tested this and it works, thanks 👍

**Comment by therecipe** [comment]
You are welcome :)
