### ISSUE TITLE
ubantu qtsetup error

### ISSUE THREAD

**Issue by jmesyan** [therecipe/qt#203]
I have installed the qt 5.7,but setup error

ERRO[0004] failed to load /work/qt/Docs/Qt-5.7/qtdatavisualization/qtdatavisualization.index  error="open /work/qt/Docs/Qt-5.7/qtdatavisualization/qtdatavisualization.index: no such file or directory"
ERRO[0004] failed to load /work/qt/Docs/Qt-5.7/qtcharts/qtcharts.index  error="open /work/qt/Docs/Qt-5.7/qtcharts/qtcharts.index: no such file or directory"

**Comment by therecipe** [comment]
Hey

These two errors are just warnings, if the examples showed up in the end and you can deploy applications with `qtdeploy`, then everything is okay.

**Comment by jmesyan** [comment]
thank you, Do you know how to solve the warning problems

**Comment by therecipe** [comment]
yes, I will hide these warnings soon.

in the meantime you could install the two missing modules to get rid of the warnings. (but that requires the re-installation of Qt)
