### ISSUE TITLE
OSX installation issue

### ISSUE THREAD

**Issue by odunboye** [therecipe/qt#204]
When trying to install on OSX  El-capitan, i get the error below

cd .; git clone https://github.com/therecipe/qt /Users/*****/codes/go/src/github.com/therecipe/qt
Cloning into '/Users/*******/codes/go/src/github.com/therecipe/qt'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
package github.com/therecipe/qt/cmd/...: exit status 128

any way out?

**Comment by therecipe** [comment]
Hey

Could be a github issues, did you tried it again some time later?

**Comment by odunboye** [comment]
Thanks for quick response,
I ended up downloading as zip and extracted it manually.
