### ISSUE TITLE
core.Qt__Key not working

### ISSUE THREAD

**Issue by gabeart10** [therecipe/qt#207]
So I have been using core.Qt__Key and for some reason this does not work:
`rect.ConnectKeyPressEvent(func(keypress *gui.QKeyEvent) {
                 if keypress.Key() == core.Qt__Key_Left {
                         rect.SetPos2(rect.X()-10, rect.Y()) 
                 } 
})
`
The error is `./main.go:21: invalid operation: keypress.Key() == core.Qt__Key_Left (mismatched types int and core.Qt__Key)`

Using the raw key code does work though.

**Comment by therecipe** [comment]
Hey

Yeah, you may need to wrap it like this:
`keypress.Key() == int(core.Qt__Key_Left)`
or like this
`core.Qt__Key(keypress.Key()) == core.Qt__Key_Left`

**Comment by gabeart10** [comment]
Ah my bad, thanks! :)
