### ISSUE TITLE
QList translation from c++

### ISSUE THREAD

**Issue by gabeart10** [therecipe/qt#209]
So, I look through a few examples and I can't find how to translate this `QList<QGraphicsItem *> colliding_item = scene.CollidingItem()` to Golang

Thanks,
gabeart10

**Comment by therecipe** [comment]
Hey

Yes, generic lists / containers are currently not (fully) supported.

But, I worked on this for the last few days and I'm almost done now :)
I will do some more testing today, and then probably push the changes in the next 24 hours.

And I just checked the function and `CollidingItem` will return a `[]*widgets.QGraphicsItem`

**Comment by gabeart10** [comment]
Ah thanks

**Comment by therecipe** [comment]
@gabeart10 

`CollidingItem` should be available now with: https://github.com/therecipe/qt/commit/3456e5280a438b31c6c4529ef86e465ba190ef7d
