### ISSUE TITLE
install failed on windows 10, golang 1.7.5

### ISSUE THREAD

**Issue by ismlsmile** [therecipe/qt#210]
The error info:

time="2017-01-29T10:41:15+08:00" level=info msg="installing full qt/scripttools"
time="2017-01-29T10:41:21+08:00" level=error msg="failed to run command" cmd="go install -p 8 -v github.com/therecipe/qt/scripttools" error="exit status 2" func=RunCmdOptional name=install.scripttools
Exception 0xc0000005 0x0 0x27ef890 0x7ffa26bcf5b9
PC=0x7ffa26bcf5b9

syscall.Syscall(0x7ffa24dda430, 0x3, 0x2, 0x1, 0x6, 0x0, 0x0, 0x0)
        c:/go/src/runtime/syscall_windows.go:163 +0x6b
syscall.socket(0x100000002, 0x6, 0x676e696e6e755200, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:1382 +0x73
syscall.Socket(0x2, 0x1, 0x6, 0x0, 0x0, 0x0)
        c:/go/src/syscall/syscall_windows.go:709 +0x58
net.probeIPv4Stack(0xc042008a01)
        c:/go/src/net/ipsock_posix.go:23 +0x4e
net.init.2()
        c:/go/src/net/net.go:100 +0x2e
net.init()
        c:/go/src/net/unixsock_posix.go:205 +0x983
crypto/x509.init()
        c:/go/src/crypto/x509/x509.go:2081 +0xaa
crypto/tls.init()
        c:/go/src/crypto/tls/tls.go:298 +0x73
main.init()
        c:/go/src/cmd/go/zosarch.go:43 +0xb4
rax     0x27ef870
rbx     0xf23d78
rcx     0xf23d80
rdi     0x6c
rsi     0x2e3000
rbp     0xc0420b7c00
rsp     0x8fc90
r8      0x27ef870
r9      0x27ef870
r10     0x0
r11     0x8f520
r12     0x2
r13     0xffffffffffffffff
r14     0xf23d80
r15     0x2700
rip     0x7ffa26bcf5b9
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by ismlsmile** [comment]
I check the detailed error:
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

It seems that I install a 64bit golang but the Qt is 32bit. I will try the 32bit golang installation

**Comment by ismlsmile** [comment]
I test the 32bit golang, the above error is ok, but I meet a new error:

# github.com/therecipe/qt/widgets
runtime: out of memory: cannot allocate 1900544-byte block (1339621376 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x92d213, 0xd)
        c:/go/src/runtime/panic.go:566 +0x7f
runtime.largeAlloc(0x1c5d52, 0x449100, 0x11476000)
        c:/go/src/runtime/malloc.go:776 +0xb7
runtime.mallocgc.func1()
        c:/go/src/runtime/malloc.go:669 +0x31
runtime.systemstack(0x11471400)
        c:/go/src/runtime/asm_386.s:323 +0x5e
runtime.mstart()
        c:/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()


My PC has 32GB memory and 25G+ free, It is strange that meets "out of memory".

**Comment by ismlsmile** [comment]
I think maybe it is because the "qtsetup.exe" is 32bit, so it can not use allocate 2G+ memory. How to get over it ?

**Comment by therecipe** [comment]
Hey

>I think maybe it is because the "qtsetup.exe" is 32bit, so it can not use allocate 2G+ memory. How to get over it ?

Yes that's right, but it's the Go "compile.exe" that hits the memory limit and crashes.
So you will need to use the 64bit version of Go for this to work.

(It will automatically cross compile your applications to 32bit on windows, to make it work with the 32bit Qt libs)

I will setup a fresh windows box and look into it.

**Comment by therecipe** [comment]
Okay, tested it on windows 7 64bit with Go 1.7.5 64bit and the "official" pre-build Qt 5.7.0.
And it worked, datavisualization and charts threw errors though, but that is normal if you don't opt-in to them while installing Qt.

Could you maybe run `qtsetup install` again?
And/Or maybe post the output of `qtsetup check`?
Did you use msys2 or something? Or just the plain normal Qt setup?

**Comment by ismlsmile** [comment]
I use the "official" pre-build Qt 5.7.0 and mingw built-in the qt installer. I think the problem maybe I use 64bit golang but the mingw built-in qt is 32bit?

1. qtsetup check
time="2017-01-30T10:51:15+08:00" level=info msg="running setup/check desktop"
time="2017-01-30T10:51:15+08:00" level=info msg="VERSION: 0.0.4"
time="2017-01-30T10:51:15+08:00" level=info msg="GOOS: windows"
time="2017-01-30T10:51:15+08:00" level=info msg="GOARCH: amd64"
time="2017-01-30T10:51:15+08:00" level=info msg="GOVERSION: go1.7.5"
time="2017-01-30T10:51:15+08:00" level=info msg="GOROOT: E:\\Go\\"
time="2017-01-30T10:51:15+08:00" level=info msg="GOPATH: E:\\GoPath"
time="2017-01-30T10:51:15+08:00" level=info msg="GOBIN: E:\\GoPath\\bin"
time="2017-01-30T10:51:19+08:00" level=info msg="HASH: ea1ff647b6e9b0bb757e1c0163e7036f4f325d3f"
time="2017-01-30T10:51:19+08:00" level=info msg="QT_VERSION: 5.7.0"
time="2017-01-30T10:51:19+08:00" level=info msg="QT_VERSION_MAJOR: 5.7"
time="2017-01-30T10:51:19+08:00" level=info msg="QT_DIR: E:\\Qt\\5.7.0"
time="2017-01-30T10:51:19+08:00" level=info msg="QT_STUB: false"
time="2017-01-30T10:51:19+08:00" level=info msg="MSYSTEM: "
time="2017-01-30T10:51:19+08:00" level=info msg="QT_MSYS2: "
time="2017-01-30T10:51:19+08:00" level=info msg="QT_MSYS2_DIR: "
time="2017-01-30T10:51:19+08:00" level=info msg="IsMsys2QtDir: false"
time="2017-01-30T10:51:19+08:00" level=info msg="UseMsys2: false"


2、qtsetup install
time="2017-01-30T10:52:05+08:00" level=info msg="running setup/install desktop"
time="2017-01-30T10:52:05+08:00" level=info msg="starting to install modules (~15min)"
time="2017-01-30T10:52:05+08:00" level=info msg="installing full qt/core"
time="2017-01-30T10:52:10+08:00" level=error msg="failed to run command" cmd="go install -p 8 -v github.com/therecipe/qt/core" error="exit status 2" func=RunCmdOptional name=install.core
Exception 0xc0000005 0x0 0x27ff890 0x7ff80475f5b9
PC=0x7ff80475f5b9

syscall.Syscall(0x7ff801ffa430, 0x3, 0x2, 0x1, 0x6, 0x0, 0x0, 0x0)
        c:/go/src/runtime/syscall_windows.go:163 +0x6b
syscall.socket(0x100000002, 0x6, 0x676e696e6e755200, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:1382 +0x73
syscall.Socket(0x2, 0x1, 0x6, 0x0, 0x0, 0x0)
        c:/go/src/syscall/syscall_windows.go:709 +0x58
net.probeIPv4Stack(0xc04203c901)
        c:/go/src/net/ipsock_posix.go:23 +0x4e
net.init.2()
        c:/go/src/net/net.go:100 +0x2e
net.init()
        c:/go/src/net/unixsock_posix.go:205 +0x983
crypto/x509.init()
        c:/go/src/crypto/x509/x509.go:2081 +0xaa
crypto/tls.init()
        c:/go/src/crypto/tls/tls.go:298 +0x73
main.init()
        c:/go/src/cmd/go/zosarch.go:43 +0xb4
rax     0x27ff870
rbx     0xe9ca8
rcx     0xe9cb0
rdi     0x65
rsi     0x2f1000
rbp     0xc0420d1c00
rsp     0x8fc90
r8      0x27ff870
r9      0x27ff870
r10     0x0
r11     0x8f520
r12     0x2
r13     0xffffffffffffffff
r14     0xe9cb0
r15     0x2700
rip     0x7ff80475f5b9
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

time="2017-01-30T10:52:10+08:00" level=info msg="installing full qt/androidextras"

3. go install -p 8 -v github.com/therecipe/qt/core
github.com/therecipe/qt/internal/android/cgo
github.com/therecipe/qt
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

**Comment by therecipe** [comment]
>I think the problem maybe I use 64bit golang but the mingw built-in qt is 32bit?

It would be a problem, but the setup and qtdeploy take extra steps to set the env variable `GOARCH=386` prior to compiling. This makes it possible to use the 64bit Go version to compile 32bit  applications (and it also makes it work with the 32bit Qt libs)

You can try it yourself by setting:
`CGO_ENABLED=1` and `GOARCH=386` before running `go install -p 8 -v github.com/therecipe/qt/core`


I googled `syscall_windows.go:163` and found this and similar issues: https://github.com/docker/docker/issues/27423
It seems to be a win 10 Go problem.

Maybe you need to simply update Go to 1.8rc3 or downgrade to 1.6.x, or if you have bad luck you need to update/downgrade your windows installation.

**Comment by ismlsmile** [comment]
I tried 1.8rc3, it failed too. But I tested on Win 7, it is ok. Maybe it is golang bug in Win 10

**Comment by darrenstahlmsft** [comment]
FYI a solution was found to docker/docker#27423. See https://github.com/docker/docker/issues/27423#issuecomment-278196016 and following comments.

In short, [Layered Service Providers](https://en.wikipedia.org/wiki/Layered_Service_Provider) intercept socket traffic, and if not implemented correctly, can cause certain socket API calls to fail. You likely have some third party LSP installed that is crashing. Follow the instructions [here](https://support.microsoft.com/en-us/help/2568167/setfilecompletionnotificationmodes-api-causes-an-i-o-completion-port-not-to-work-correctly-if-a-non-ifs-lsp-is-installed) under More Information for a workaround.

For the developers, see https://github.com/docker/docker/issues/27423#issuecomment-278204990 for an idea on how to fix this.
