### ISSUE TITLE
How to add android permission?

### ISSUE THREAD

**Issue by nnvn** [therecipe/qt#211]
Hi, I tried the jni demo app. It is working. Now, how do I add permissions to AndroidManifest?

**Comment by therecipe** [comment]
Hey

You just need to put a `AndroidManifest.xml` inside the `android` sub-folder.
https://github.com/therecipe/qt/blob/master/internal/docs/android.md

Simply copy the manifest from `deploy/android_minimal/build` and expend it with the new permissions.

**Comment by nnvn** [comment]
Thanks.
