### ISSUE TITLE
BGP flowspec tool using your binding

### ISSUE THREAD

**Issue by Matt-Texier** [therecipe/qt#213]
https://github.com/Matt-Texier/local-mitigation-agent

No issue here ... as discussed, I just make public a repo that propose a UI (using your code) to push routing updates to a BGP open source stack ( could be used for DDoS mitigation) .

If you believe it could be used as an example ... feel free to refers to it.
(I did nothing very original from a UI point of view !)

Thanks Matt.

**Comment by Matt-Texier** [comment]
My pleasure ! 

It was very useful to have a native go UI library. I had options to use C gRPC API from GoBGP and use C/C++ Qt or do the whole stuff in Go. GoBGP comes with gRPC API client written in Go, as such, it was easier for me to do the whole stuff in Go.

It was globally nice and easy to use your bindings. Couple of things that would be great: see if this is doable to interface with Qt creator tool (Could save time to create widgets), highlight the value that Golang could bring ... For now, I have identified the ability to pass additional parameters to functions when connecting buttons and others widgets using anonymous functions but I believe that a Golang expert could find more value.

What is not yet clear to me is how to make a simple package of what I have done ... This is something I need to understand and work on now !

**Comment by Matt-Texier** [comment]
Forgot to mention but at some point, I would be interested in having support of Qt charts but as far as I can see you are working on it right ?

Thanks Matt.

**Comment by therecipe** [comment]
Thank you for taking the time to give some feedback, I appreciate it :)

>Couple of things that would be great: see if this is doable to interface with Qt creator tool (Could save time to create widgets), highlight the value that Golang could bring ...

You mean like a plugin/extension for the Qt Creator, to interfere with Go?
Or being able to load/use the stuff that you can create with the drag and drop gui designer? (this is already possible and shown in the [uitools/calculator](https://github.com/therecipe/qt/tree/master/internal/examples/uitools/calculator) example)

>For now, I have identified the ability to pass additional parameters to functions when connecting buttons and others widgets using anonymous functions but I believe that a Golang expert could find more value.

Yes, that really useful indeed. Maybe if you want to dive in deeper, you could also create your own properties, signals and slots for you qtmoc "subclasses" that are derived from QObject.
(the [quick/listview](https://github.com/therecipe/qt/tree/master/internal/examples/quick/listview) shows what is possible currently with qtmoc, even though it's a qml example)

>What is not yet clear to me is how to make a simple package of what I have done ... This is something I need to understand and work on now !

You mean like how to create a .msi on windows, .dmg/.pkg on macOS or .deb/.rpm on linux?
I know there is this http://doc.qt.io/qtinstallerframework/index.html from Qt itself to create a setup installer, but I haven't used that myself yet.  (Also there is some info here: https://wiki.qt.io/Building_Qt_Installers, but that's probably aged.)

>Forgot to mention but at some point, I would be interested in having support of Qt charts but as far as I can see you are working on it right ?

It should already work, you just need to opt-in the charts module during the Qt setup.
(Could be that you need to install Qt again for that, as I'm not sure if you can use the Qt maintain tool to install additional modules)

**Comment by Matt-Texier** [comment]
Hi,

Gui designer: I was thinking about the drag and drop stuff ... I didn't realise that it was possible to parse a QML file and generate .go file. Could you let me know how to do this ?

Package: yes, I would like to build a linux package. Looking at the .sh script autogenerated by qtdeploy, I was wondering which files/lib I should install on a fresh installed linux server ...

Thanks for your help and availability,
Matt.

**Comment by therecipe** [comment]
For the gui designer, there are actually two different ones.
There is one for the desktop widgets and one for qml widgets.

The one for the desktop widgets produces *.ui files, which can be loaded with the uitools package. 
After loading the *.ui file, you just need to find your child widgets with the help of the object name like it's shown in the example and then use them as usual.
http://doc.qt.io/qt-5/qtdesigner-manual.html

And there is also the possibility to create *.cpp files from these *.ui files with the help of the `uic`.
I did plan to port the `uic` to Go at some point, to let it create *.go files, but I haven't had time for that yet.


The other qml designer, produces qml files which can be used just like hand written qml files.
http://doc.qt.io/qtcreator/creator-using-qt-quick-designer.html

For the packaging, you usually just need to deploy the folders along with the *.sh and the binary.
There is also the possibility to get rid of the *.sh file, by setting the library paths in you code, but I haven't tried that myself yet.
