### ISSUE TITLE
Weird text

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#216]
![screen shot 2017-02-04 at 10 01 03 pm](https://cloud.githubusercontent.com/assets/13412168/22619340/7fdcaac8-eb25-11e6-9558-d09927c6cc30.png)

Hi,

I have an issue where a title with size 20 will changed to symbols when opening a component using `StackView` and loaded using `Loader`.  I composed the simplest example on this repo: https://github.com/arknable/therecipe-issue.

Actually, if I eliminate `Loader` and use `StackView` directly and change the text via `onCurrentItemChanged`, it will still result in the same symptom.

However, the symptom disappear when,
1. `FileDialog` eliminated from `Page1`
2. I don't set title after page loaded
3. Put `SearchInput` in `main.qml`
4. Load `Page1` as initial page, but it will occur on page change, i.e. open `Page2` and then open `Page1`
5. Decrease font size to less than 20. in the real app only size 20 raise the issue.
6. Set text to be non-bold, i.e. remove `bold: true`

Putting another text outside `ToolBar` result in the same symptom so probably not an issue related to toolbar.

Thanks

**Comment by therecipe** [comment]
Hey

This seems to be related or maybe it's even the same bug:
https://forum.qt.io/topic/71732/text-font-weight-appears-to-be-broken-on-ios-10

The simplest solutions is to use another (similar looking) font.

I got it working by using:
```go
gui.QGuiApplication_SetFont(gui.NewQFont2("Helvetica Neue", -1, -1, false))
```
or changing the font family in qml:
```qml
family: "Helvetica Neue"
```

**Comment by arknable** [comment]
Hi,

I just tried to built my sample branch using Qt Creator and the symptom appears, so I think that's Qt's issue but I'm not sure if font weight issue above related but at least the issue is in the same topic i.e. font. so I will close this. thanks for the link.

thanks.
