### ISSUE TITLE
Using a webview on desktop and mobile

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#217]
Is it possible to control a web view on mobile and desktop ?

I would like to be able to inject HTML into the Dom directly from golang templates.

Here is an example using webviews without Qt, so you get the idea.

https://github.com/murlokswarm/app

**Comment by therecipe** [comment]
Hey

This is an basic example that manipulates the DOM with js:
```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/webengine"
	"github.com/therecipe/qt/widgets"
)

const htmlData = `<!DOCTYPE html>
<html>
<body>

<div id="div1">
<p id="p1">This is a paragraph.</p>
<p id="p2">This is another paragraph.</p>
</div>

</body>
</html>`

const jsData = `var para = document.createElement("p");
var node = document.createTextNode("This is new.");
para.appendChild(node);

var element = document.getElementById("div1");
element.appendChild(para);`

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	var window = widgets.NewQMainWindow(nil, 0)

	var centralWidget = widgets.NewQWidget(nil, 0)
	centralWidget.SetLayout(widgets.NewQVBoxLayout())

	var view = webengine.NewQWebEngineView(nil)
	view.SetHtml(htmlData, core.NewQUrl())
	centralWidget.Layout().AddWidget(view)

	var button = widgets.NewQPushButton2("click me", nil)
	button.ConnectClicked(func(checked bool) {
		view.Page().RunJavaScript4(jsData)
	})
	centralWidget.Layout().AddWidget(button)

	window.SetCentralWidget(centralWidget)
	window.Show()

	widgets.QApplication_Exec()
}
```
and there is also a qml api http://doc.qt.io/qt-5/qml-qtwebview-webview.html

But it works only on the desktop: http://doc.qt.io/qt-5/qtwebengine-overview.html#platform-notes

If you want to directly manipulate the DOM, then you probably need to use: http://doc.qt.io/qt-5/qtwebchannel-module.html

Also there is another WebEngine called WebKit, here: https://github.com/therecipe/qt/issues/121
which gives you better (iirc direct) access to the DOM and more options in general.
But you need to compile it yourself, as there don't seem to be pre-built libs.
(I hope it will be an official module with pre-built libs in Qt 5.9 again)
I planned to support the WebKit as an add-on, but I haven't really worked on that yet.

**Comment by therecipe** [comment]
Seems like the qml WebView http://doc.qt.io/qt-5/qtwebview-index.html, works cross platform on android and iOS as well.

**Comment by joeblew99** [comment]
thanks. this is great.

I found a nice example here too:
https://github.com/lirios/browser/blob/develop/src/main/main.cpp

what i would like to do is allow people to build with HTML and run anywhere inside a webview, but also bring up QT native controls like dialogs for calanders, etc.
This woudl be really amazing because Murlok has allot of work cut out to get everything working cross platform, but QT webview solves it in one hit.
But mayn devs still like HTML and thats great too.

Wondering what you think. I would like to have a go at making an example for this repo so others can try it too.

**Comment by therecipe** [comment]
>Wondering what you think. I would like to have a go at making an example for this repo so others can try it too.

Sounds, good :)
You probably would use the qml WebView? To create the driver?
Because I just remembered that the WebEngine is currently not supported on windows.
See here: https://github.com/therecipe/qt/issues/53

But the qml WebView should work (I haven't tested it though)

**Comment by joeblew99** [comment]
thanks for the tips.

Yes i will use the QML webview to make the driver.  But we wont link to murlok yet. Mostly just want to get it working easily so you can built the GUI with QT or wth Golang Templates driving the GUI.

I dont get the real difference between the Qt WebView and the Qt WebEngine.
They are both based on Chrome ?

I guess the problem you mentioned with building the web engine for Windows is because it has allot of extra stuff like GUI things ?

i found this too. Shows how easy it is to use different engines.
https://github.com/lirios/browser/wiki/Development-Setup

**Comment by therecipe** [comment]
>I dont get the real difference between the Qt WebView and the Qt WebEngine.

Found this in the docs:

>WebView is a component for displaying web content which is implemented using native APIs on the platforms where this is available, thus it does not necessarily require including a full web browser stack as part of the application.

So you can use it without the need to deploy the chrome engine (like electron does iirc), it will probably use IE on windows and Safari on macOS/iOS, on Linux/android probably what is currently available (chrome is preferred there I guess).

But the api is therefore pretty limited: http://doc.qt.io/qt-5/qml-qtwebview-webview.html

And it seems like this function is currently missing: http://doc.qt.io/qt-5/qtwebview.html#initialize for it to work. But I will look into it.


>I guess the problem you mentioned with building the web engine for Windows is because it has allot of extra stuff like GUI things ?

Actually, it's because chrome on windows uses/needs the visual studio compiler, and these weren't compatible with Go the last time I checked.

**Comment by therecipe** [comment]
I added a new example [qml/webview](https://github.com/therecipe/qt/tree/master/internal/examples/qml/webview) with https://github.com/therecipe/qt/commit/177d16c013e7b331274952903173aa4309a8bb81

I tested it only on macOS, android and iOS. But linux and windows work probably as well.

**Comment by joeblew99** [comment]
Thanks.

Will give it a whirl this week.

**Comment by influx6** [comment]
The code above blows up with the following error on linux:

```shell
Could not initialize GLX
SIGABRT: abort
PC=0x7f75aee237ef m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4bdcb0, 0xc420051eb0, 0x4af89c)
	/home/influx6/Labs/local/src/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420051e70 sp=0xc420051e30
github.com/therecipe/qt/widgets._Cfunc_QApplication_NewQApplication(0x7fff00000001, 0x225a970, 0x0)
	github.com/therecipe/qt/widgets/_obj/_cgo_gotypes.go:362 +0x4e fp=0xc420051eb0 sp=0xc420051e70
github.com/therecipe/qt/widgets.NewQApplication(0x1, 0xc420010200, 0x1, 0x1, 0x0)
	/home/influx6/Labs/repos/go/src/github.com/therecipe/qt/widgets/widgets-minimal.go:664 +0xcb fp=0xc420051f28 sp=0xc420051eb0
main.main()
	/home/influx6/Labs/repos/go/src/github.com/gu-io/qt/qt.go:31 +0x55 fp=0xc420051f88 sp=0xc420051f28
runtime.main()
	/home/influx6/Labs/local/src/go/src/runtime/proc.go:185 +0x20a fp=0xc420051fe0 sp=0xc420051f88
runtime.goexit()
	/home/influx6/Labs/local/src/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420051fe8 sp=0xc420051fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/influx6/Labs/local/src/go/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x2353f80
rcx    0x7f75aee237ef
rdx    0x0
rdi    0x2
rsi    0x7fff401f1320
rbp    0x7fff401f16e0
rsp    0x7fff401f1398
r8     0x0
r9     0x7fff401f1320
r10    0x8
r11    0x246
r12    0x2353fb0
r13    0x2271e30
r14    0x0
r15    0x2271e30
rip    0x7f75aee237ef
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by therecipe** [comment]
I test the WebView on windows, and it seems like it won't work there as well.
So it has the same limitations as the QWebEngine (it seems to make use of it underneath, somehow)

The only remaining change for windows, seems to be the WebKit.

**Comment by influx6** [comment]
Ah I see. Would be nice to find a cross platform way of getting a webview
to work through qt.

Best Regards,
Alex.

Chief Information Officer (CIO)
Dream Bench Technologies
www.dreambench.io (alex.ewetumo@dreambench.com)
