### ISSUE TITLE
Some Qt application can't run on Windows

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#222]
build https://github.com/therecipe/qt#example

```
~/src/qtExample qtdeploy build windows . docker
```

and move `deploy/windows_minimal` to a Windows host. in my case I use https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

and run `qtExample.exe` and that works:

![screenshot from 2017-02-07 14-38-55](https://cloud.githubusercontent.com/assets/474302/22680604/daa8d2ea-ed43-11e6-9c24-37b8f1d79ab3.png)

but if I do the same exact thing with https://github.com/therecipe/qt/tree/master/internal/examples/qml/application it don't works.

Even if I manually work around #221 by copy 3 `.dll`. The `.exe` just start and immediately stop.
It stop before `main()` is executed.

To figure where it crashed, I added the following code:

```
diff --git a/internal/examples/qml/application/application.go b/internal/examples/qml/application/application.go
index 152ac48..f12648d 100755
--- a/internal/examples/qml/application/application.go
+++ b/internal/examples/qml/application/application.go
@@ -2,6 +2,7 @@ package main
 
 import (
        "os"
+       "fmt"
 
        "github.com/therecipe/qt/core"
        "github.com/therecipe/qt/gui"
@@ -9,11 +10,18 @@ import (
 )
 
 func main() {
-
+       fmt.Println("gui.NewQGuiApplication()")
        gui.NewQGuiApplication(len(os.Args), os.Args)
 
+       fmt.Println("qml.NewQQmlApplicationEngine")
        var app = qml.NewQQmlApplicationEngine(nil)
-       app.Load(core.NewQUrl3("qrc:///qml/application.qml", 0))
 
+       fmt.Println("core.NewQUrl3")
+       url := core.NewQUrl3("qrc:///qml/application.qml", 0)
+
+       fmt.Println("app.Load")
+       app.Load(url)
+
+       fmt.Println("gui.QGuiApplication_Exec")
        gui.QGuiApplication_Exec()
 }
```

when I try to run the `.exe` from `cmd.exe` I get nothing in the console. none of the `fmt.Println` output.

![screenshot from 2017-02-07 14-56-40](https://cloud.githubusercontent.com/assets/474302/22680952/c77de186-ed45-11e6-9628-5b3fbb963883.png)

I tried 32 and 64 bits build. 

Same `.exe` ran from `wine` (32 bits) on Linux and `wine64`

It look like it's related to #221

**Comment by therecipe** [comment]
It seems like you need to enable the 3d acceleration of your vm to get qml/quick applications working.
As they are making use of OpenGL (with 5.8 it should work even without 3d acceleration, but I haven't tested that)

Also on windows you need to use the http://msys2.github.io/ mingw shell (just the shell, you don't need to use msys2 for compiling) to get an output from your applications.

**Comment by bclermont** [comment]
> It seems like you need to enable the 3d acceleration of your vm to get qml/quick applications working.

somewhat.

I installed various Windows version, mix of 32 and 64 bits from XP to 10. 32 or 64 bits, it don't make any difference.

I rebuild binary of `internal/qml/application` using latest Docker image.

Results are:

# Windows XP & Windows 7

Segfault if 3D acceleration is off. Works if using https://github.com/therecipe/qt/issues/119#issuecomment-279236878

if VM 3D acceleration is on, no need to set environment variable

# Windows 8.1 & Windows 10

VM 3D acceleration still segfault.

Works if using https://github.com/therecipe/qt/issues/119#issuecomment-279236878

> Also on windows you need to use the http://msys2.github.io/ mingw shell (just the shell, you don't need to use msys2 for compiling) to get an output from your applications.

Why we can't get the segfault string using `cmd.exe` ?

> As they are making use of OpenGL (with 5.8 it should work even without 3d acceleration, but I haven't tested that)

I couldn't test 5.8 as the docker image is still using 5.7.0.

**Comment by therecipe** [comment]
>Why we can't get the segfault string using cmd.exe ?

On windows, the output to cmd is suppressed if you use `go build -ldflags="-H=windowsgui"` or if you link against the Gui lib from Qt. The mingw shells from msys2 seem to work though (they probably don't recognize the "-H=windowsgui" flag, because it's only a windows thing)

You could probably receive the output as well, if you would start your application from small wrapper application with exec.Cmd and make use of Output() or CombinedOutput().

**Comment by bclermont** [comment]
>You could probably receive the output as well, if you would start your application from small wrapper application with exec.Cmd and make use of Output() or CombinedOutput(). (But I haven't tested that)

you mean there is no concept of standard error on windows or what?

I still don't understand why the segfault string disapears

**Comment by therecipe** [comment]
>you mean there is no concept of standard error on windows or what?
I still don't understand why the segfault string disapears

no, only if the application is compiled with `-H=windowsgui` (or if you link it against the Qt Gui lib, iirc), then the output in general is suppressed (in/out/err).

found the explanation and a possible solution here:
http://stackoverflow.com/questions/23743217/printing-output-to-a-command-window-when-golang-application-is-compiled-with-ld

**Comment by stillwarter** [comment]
I wonder if the application can run without Qt*.dll

**Comment by therecipe** [comment]
@stillwarter 
>I wonder if the application can run without Qt*.dll

Not all Qt*.dlls are necessary to run it, but most are.

**Comment by bclermont** [comment]
ok thanks @therecipe we know the problem and have workaround for it

**Comment by bclermont** [comment]
unclosing the issue as the workaround isn't a fix. and it's on https://github.com/mxe/mxe/issues/1685 the real fix will be
