### ISSUE TITLE
A build of Go Qt 5.8 fails on Windows 10 and MSYS2 

### ISSUE THREAD

**Issue by AnyCPU** [therecipe/qt#224]
I have tried to install the msys2 into custom directory and a build is failing now.
Every time I get the message "C:\\msys64\\mingw64\\bin\\rcc - file does not exist". No wonder because there is wrong directory.

**Comment by therecipe** [comment]
Hey

You can set a custom dir with: `QT_MSYS2_DIR`

**Comment by AnyCPU** [comment]
@therecipe got it.

**Comment by AnyCPU** [comment]
@therecipe 
I think it may be closed.
