### ISSUE TITLE
Error: Can't compile on windows

### ISSUE THREAD

**Issue by longlongh4** [therecipe/qt#23]
Win7 32bit will crash when compiling. Here is the log info:

C:\develop\src\github.com\therecipe\qt>go run C:\develop/src/github.com/therecip
e/qt/internal/setup/install.go
________________________Install-desktop________________________
core                           47s
androidextras                  0
gui                            47s
network                        15s
sql                            8s
xml                            8s
dbus                           6s
nfc                            4s
script                         5s
sensors                        10s
positioning                    5s
widgets

install.Widgets
output:# github.com/therecipe/qt/widgets
C:\Windows\go-build958700558\github.com\therecipe\qt\widgets\_obj\_cgo_main.c: I
n function 'crosscall2':
C:\Windows\go-build958700558\github.com\therecipe\qt\widgets\_obj\_cgo_main.c:2:
23: warning: unused parameter 'fn' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int), void *a, int c) { }
                       ^
C:\Windows\go-build958700558\github.com\therecipe\qt\widgets\_obj\_cgo_main.c:2:
46: warning: unused parameter 'a' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int), void *a, int c) { }
                                              ^
C:\Windows\go-build958700558\github.com\therecipe\qt\widgets\_obj\_cgo_main.c:2:
53: warning: unused parameter 'c' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int), void *a, int c) { }
                                                     ^
C:\Windows\go-build958700558\github.com\therecipe\qt\widgets\_obj\_cgo_main.c: I
n function '_cgo_allocate':
C:\Windows\go-build958700558\github.com\therecipe\qt\widgets\_obj\_cgo_main.c:5:
26: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                          ^
C:\Windows\go-build958700558\github.com\therecipe\qt\widgets\_obj\_cgo_main.c:5:
33: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                                 ^
C:\Windows\go-build958700558\github.com\therecipe\qt\widgets\_obj\_cgo_main.c: I
n function '_cgo_panic':
C:\Windows\go-build958700558\github.com\therecipe\qt\widgets\_obj\_cgo_main.c:6:
23: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                       ^
C:\Windows\go-build958700558\github.com\therecipe\qt\widgets\_obj\_cgo_main.c:6:
30: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                              ^
# github.com/therecipe/qt/widgets
widgets\widgets.go: In function '_cgo_60ca106ee6b5_Cfunc_QApplication_QApplicati
on_AboutQt':
widgets\widgets.go:8110:49: warning: unused variable 'a' [-Wunused-variable]
 }
                                                 ^
widgets\widgets.go: In function '_cgo_60ca106ee6b5_Cfunc_QApplication_QApplicati
on_Beep':
widgets\widgets.go:8165:49: warning: unused variable 'a' [-Wunused-variable]
  }
                                                 ^
widgets\widgets.go: In function '_cgo_60ca106ee6b5_Cfunc_QApplication_QApplicati
on_CloseAllWindows':
widgets\widgets.go:8174:49: warning: unused variable 'a' [-Wunused-variable]
 }
                                                 ^
widgets\widgets.go: In function '_cgo_60ca106ee6b5_Cfunc_QScrollerProperties_QSc
rollerProperties_UnsetDefaultScrollerProperties':
widgets\widgets.go:74370:49: warning: unused variable 'a' [-Wunused-variable]
  }
                                                 ^
widgets\widgets.go: In function '_cgo_60ca106ee6b5_Cfunc_QToolTip_QToolTip_HideT
ext':
widgets\widgets.go:101481:49: warning: unused variable 'a' [-Wunused-variable]
  }
                                                 ^
widgets\widgets.go: In function '_cgo_60ca106ee6b5_Cfunc_QWhatsThis_QWhatsThis_E
nterWhatsThisMode':
widgets\widgets.go:108496:49: warning: unused variable 'a' [-Wunused-variable]
  defer qt.Recovering("callback QPlainTextEdit::scrollContentsBy")
                                                 ^
widgets\widgets.go: In function '_cgo_60ca106ee6b5_Cfunc_QWhatsThis_QWhatsThis_H
ideText':
widgets\widgets.go:108505:49: warning: unused variable 'a' [-Wunused-variable]
 func (ptr *QPlainTextEdit) ScrollContentsBy(dx int, dy int) {
                                                 ^
widgets\widgets.go: In function '_cgo_60ca106ee6b5_Cfunc_QWhatsThis_QWhatsThis_L
eaveWhatsThisMode':
widgets\widgets.go:108526:49: warning: unused variable 'a' [-Wunused-variable]
  }
                                                 ^
# github.com/therecipe/qt/widgets
widgets\widgets.cpp:12702:44: warning: unused parameter 'ok' [-Wunused-parameter
]
 void* QFontDialog_QFontDialog_GetFont2(int ok, void* parent){
                                            ^
widgets\widgets.cpp:12706:43: warning: unused parameter 'ok' [-Wunused-parameter
]
 void* QFontDialog_QFontDialog_GetFont(int ok, void* initial, void* parent, char
* title, int options){
                                           ^
widgets\widgets.cpp:19515:121: warning: unused parameter 'ok' [-Wunused-paramete
r]
 int QInputDialog_QInputDialog_GetInt(void* parent, char* title, char* label, in
t value, int min, int max, int step, int ok, int flags){

                                         ^
widgets\widgets.cpp:19519:125: warning: unused parameter 'ok' [-Wunused-paramete
r]
 char* QInputDialog_QInputDialog_GetItem(void* parent, char* title, char* label,
 char* items, int current, int editable, int ok, int flags, int inputMethodHints
){

                                             ^
widgets\widgets.cpp:19523:106: warning: unused parameter 'ok' [-Wunused-paramete
r]
 char* QInputDialog_QInputDialog_GetMultiLineText(void* parent, char* title, cha
r* label, char* text, int ok, int flags, int inputMethodHints){

                          ^
widgets\widgets.cpp:19527:107: warning: unused parameter 'ok' [-Wunused-paramete
r]
 char* QInputDialog_QInputDialog_GetText(void* parent, char* title, char* label,
 int mode, char* text, int ok, int flags, int inputMethodHints){

                           ^
# github.com/therecipe/qt/widgets
fatal error: out of memory

runtime stack:
runtime.throw(0x7b4a40, 0xd)
        c:/go/src/runtime/panic.go:530 +0x7f
runtime.(*mcache).refill(0x110250, 0xf, 0x72e906c0)
        c:/go/src/runtime/mcache.go:121 +0xce
runtime.mallocgc.func2()
        c:/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x10f8c000)
        c:/go/src/runtime/asm_386.s:313 +0x5e
runtime.mstart()
        c:/go/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
        c:/go/src/runtime/asm_386.s:267 fp=0x506b57a4 sp=0x506b57a0
runtime.mallocgc(0xe0, 0x787e80, 0x1, 0x72b0fea0)
        c:/go/src/runtime/malloc.go:643 +0x6ca fp=0x506b5810 sp=0x506b57a4
runtime.newobject(0x787e80, 0x72b0fea0)
        c:/go/src/runtime/malloc.go:781 +0x41 fp=0x506b5824 sp=0x506b5810
cmd/compile/internal/gc.regopt.func1(0x0, 0x0)
        c:/go/src/cmd/compile/internal/gc/reg.go:1064 +0x2b fp=0x506b5830 sp=0x5
06b5824
cmd/compile/internal/gc.Flowstart(0x72ae16c0, 0x8107f0, 0x10)
        c:/go/src/cmd/compile/internal/gc/popt.go:288 +0x704 fp=0x506b58c0 sp=0x
506b5830
cmd/compile/internal/gc.regopt(0x72ae16c0)
        c:/go/src/cmd/compile/internal/gc/reg.go:1064 +0x49f fp=0x506b5bb4 sp=0x
506b58c0
cmd/compile/internal/gc.compile(0x1a009500)
        c:/go/src/cmd/compile/internal/gc/pgen.go:521 +0xc94 fp=0x506b5cf0 sp=0x
506b5bb4
cmd/compile/internal/gc.funccompile(0x1a009500)
        c:/go/src/cmd/compile/internal/gc/dcl.go:1450 +0x198 fp=0x506b5d2c sp=0x
506b5cf0
cmd/compile/internal/gc.Main()
        c:/go/src/cmd/compile/internal/gc/lex.go:472 +0x1c00 fp=0x506b5ec0 sp=0x
506b5d2c
cmd/compile/internal/x86.Main()
        c:/go/src/cmd/compile/internal/x86/galign.go:108 +0x53e fp=0x506b5f2c sp
=0x506b5ec0
main.main()
        c:/go/src/cmd/compile/main.go:30 +0x117 fp=0x506b5f98 sp=0x506b5f2c
runtime.main()
        c:/go/src/runtime/proc.go:188 +0x234 fp=0x506b5fc0 sp=0x506b5f98
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1585 +0x1 fp=0x506b5fc4 sp=0x506b5fc0

error:exit status 2

exit status 1

C:\develop\src\github.com\therecipe\qt>if 1 NEQ 0 exit /b 1

**Comment by longlongh4** [comment]
I have tried 3 times, all failed

**Comment by therecipe** [comment]
Yes, it's not working on Win 32-bit systems. (The `widgets` package is to big)
You will need to use a Win 64-bit system and at least 2GB RAM.

The compiled application will nevertheless work on Win 32-bit.

**Comment by therecipe** [comment]
@longlongh4 
Made some changes, your can now define `QT_STUB=true` before running the setup file, this should work on machines with at least 1gb ram.
https://github.com/therecipe/qt#installation
