### ISSUE TITLE
qtsetup don't fail on error

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#233]
In #232 you can a single step failed with `qtsetup`. 
Everything else built correctly.

When one of those step fail, should `qtsetup` just stop?

because from a user point of view. If I wasn't careful enough, I could had missed this and assumed everything is supposed to works.

**Comment by bclermont** [comment]
Maybe what you can do is pile up all `[]error` and at the end report failures with a warning?

**Comment by bclermont** [comment]
Like:

```
The following packages had failed to install:
- github.com/therecipe/qt/designer
```

**Comment by therecipe** [comment]
That sounds good, I will add it.
