### ISSUE TITLE
qtsetup error display in console

### ISSUE THREAD

**Issue by Gyga8K** [therecipe/qt#235]
Cosole: Gitbash
OS: Windows 10 Pro

[31mERRO[0m[0005] failed to load C:\msys64\mingw64\include\QtGui\5.8.0\QtGui\qpa\qplatformgraphicsbuffer.h  [31merror[0m="open C:\msys64\mingw64\include\QtGui\5.8.0\QtGui\qpa\qplatformgraphicsbuffer.h: El sistema no puede encontrar la ruta especificada."
[31mERRO[0m[0005] failed to load C:\msys64\mingw64\include\QtGui\5.8.0\QtGui\qpa\qplatformsystemtrayicon.h  [31merror[0m="open C:\msys64\mingw64\include\QtGui\5.8.0\QtGui\qpa\qplatformsystemtrayicon.h: El sistema no puede encontrar la ruta especificada."
[31mERRO[0m[0011] failed to load C:\msys64\mingw64\include\QtUiTools\quiloader.h  [31merror[0m="open C:\msys64\mingw64\include\QtUiTools\quiloader.h: El sistema no puede encontrar la ruta especificada."

**Comment by therecipe** [comment]
Hey

Do you get these errors after using `qtdeploy` or while running `qtsetup`?

**Comment by Gyga8K** [comment]
running qtsetup

**Comment by therecipe** [comment]
Did the examples showed up in the end? Or did it break prior the "testing" phase?

**Comment by therecipe** [comment]
Okay, should be fixed now with:
https://github.com/therecipe/qt/commit/58c2df8b9560a59c314ee5e585c7b13dc2112ad6
