### ISSUE TITLE
Self contained docker image

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#237]
Is it possible to have a different docker architecture.

Instead of users get source of `github.com/therecipe/qt`, install `github.com/therecipe/qt/cmd/...` And use `qtsetup` to call `docker`. 
S
hould it be more simple for you as a maintainer and developer/user to just have a docker base image that bring all depencies:

- golang
- qt sdk
- `github.com/therecipe/qt`
- binaries of `github.com/therecipe/qt/cmd/...`

And other images that depends on that base that add

- android
- Windows 32
- Windows 64

To perform a build `docker run` must be executed

**Comment by quantonganh** [comment]
> And use qtsetup to call docker.

`qtsetup` not call `docker`.
It install `qt*` on the host.

> to just have a docker base image that bring all depencies: golang, `qt` sdk, `github.com/therecipe/qt`, binaries of `github.com/therecipe/qt/cmd/...`

He already did that all:

```
root@ 28001c56beae:/# which go
/usr/local/go/bin/go
```

```
root@28001c56beae:/# tree -L 1 /opt/Qt5.8.0/
/opt/Qt5.8.0/
|-- 5.8
|-- Docs
|-- Examples
|-- InstallationLog.txt
|-- Licenses
|-- MaintenanceTool
|-- MaintenanceTool.dat
|-- MaintenanceTool.ini
|-- Tools
|-- components.xml
|-- dist
`-- network.xml
```

```
root@28001c56beae:/# tree -L 3 /home/user/work/src/

/home/user/work/src/
|-- github.com
|   |-- Sirupsen
|   |   `-- logrus
|   `-- therecipe
|       `-- qt
`-- golang.org
    `-- x
        `-- crypto
```

```
root@28001c56beae:/# ls -l /usr/local/bin/qt*
lrwxrwxrwx 1 root root 28 Feb 16 17:11 /usr/local/bin/qtdeploy -> /home/user/work/bin/qtdeploy
lrwxrwxrwx 1 root root 29 Feb 16 17:11 /usr/local/bin/qtminimal -> /home/user/work/bin/qtminimal
lrwxrwxrwx 1 root root 25 Feb 16 17:11 /usr/local/bin/qtmoc -> /home/user/work/bin/qtmoc
lrwxrwxrwx 1 root root 25 Feb 16 17:11 /usr/local/bin/qtrcc -> /home/user/work/bin/qtrcc
```

> To perform a build `docker run` must be executed


```
time="2017-03-01T02:57:14Z" level=debug msg=Execute cmd="docker run --rm -v /path/to/gopath0:/media/sf_GOPATH0 -v /path/to/gopath1:/media/sf_GOPATH1 -v /path/to/gopath2:/media/sf_GOPATH2 -v /path/to/gopath3:/media/sf_GOPATH3 -e GOPATH=/media/sf_GOPATH0:/media/sf_GOPATH1:/media/sf_GOPATH2:/media/sf_GOPATH3 -i therecipe/qt:base_windows qtdeploy -debug -ldflags=... build windows /media/sf_GOPATH3/path/to/the/app
```

IIUC, your question related to the first step he wrote in the README file:

> Install the desktop version for Windows, macOS or Linux

Why we have to do that? Can we just pass the command directly to the `docker run`?

**Comment by quantonganh** [comment]
> then compiles your project on the host

"on the host"? or inside the docker container?

**Comment by therecipe** [comment]
Sorry, I meant compiles inside the container, but thereby uses the project from your host.

**Comment by bclermont** [comment]
@quantonganh I think this is fixed, right?

**Comment by quantonganh** [comment]
> @quantonganh I think this is fixed, right?

Yes.
