### ISSUE TITLE
Custom path to MXE

### ISSUE THREAD

**Issue by Kutabe** [therecipe/qt#239]
It'd be nice to have a variable for MXE path for non-debian distributions just like QT_DIR variable for QT.

**Comment by therecipe** [comment]
Hey

Yes, that should be easily possible.
And I already made some initial changes to support that, while working on something related.
There will be a new env variable, probably called `QT_MXE_DIR` to define the location.
I will push the changes later today.

Do you plan to use it on some other linux distro? Or on macOS?

**Comment by Kutabe** [comment]
I had to build MXE manually and link it to /usr/lib/mxe to make it work and then I thought it'd be a good idea to make environmental variable just like QT_DIR but for MXE. Also, QT_MXE_DIR sounds good. Thanks for reply.

**Comment by therecipe** [comment]
You should be able to use `QT_MXE_DIR` now with https://github.com/therecipe/qt/commit/70f198d247298eff4e3d57c87bbe0d19f3f3b9f1 (the default value is: `/usr/lib/mxe`)

I also added the initial support for static linking, if you want to test it you just need to set `QT_MXE_STATIC=true` and `QT_QMAKE_CGO=true`
and of course you would need to build the static mxe version yourself, but I assume you already know that ;)

>I use another Linux distribution but it should work for BSD as well, I suppose.

It should work now as well, but I haven't tested it yet.

**Comment by Kutabe** [comment]
Tested on my system, static linking works fine too, but:
`QT_MXE_DIR`, `QT_MXE_STATIC` and `QT_QMAKE_CGO` should be present in `INFO` section, just like `QT_DIR` and `QT_MXE_ARCH`. Anyway it's not critical, issue closed, I'm happy, thanks.

**Comment by therecipe** [comment]
Great :)

Yeah, these will be added when things are more stable.
