### ISSUE TITLE
more than one slots just only call one goroutine

### ISSUE THREAD

**Issue by liugangnhm** [therecipe/qt#240]
code like this

```go
//create a button and connect the clicked signal
	var button = widgets.NewQPushButton2("Click me!", nil)
	button.ConnectClicked(func(flag bool) { log.Println("clickme1") })
	button.ConnectClicked(func(flag bool) { log.Println("clickme2") })
```

output is 
```
clickme2
clickme2
```

i just try pushbutton, maybe other widgets have the same issue.

**Comment by therecipe** [comment]
Hey

I made some changes with: https://github.com/therecipe/qt/commit/70f198d247298eff4e3d57c87bbe0d19f3f3b9f1 and it should work now
(even for slots and virtual functions, and not only for signals)

the functions will be called in the same order as the connect* functions were called in the first place.

thanks for the idea :)

**Comment by Kutabe** [comment]
Wait. Why don't you just use one `button.ConnectClicked()` function call for both `clickme1` and `clickme2`?

**Comment by therecipe** [comment]
>If several slots are connected to one signal, the slots will be executed one after the other, in the order they have been connected, when the signal is emitted.

http://doc.qt.io/qt-5/signalsandslots.html#signals

it's possible in c++, so he probably expected that it's also working in go

**Comment by liugangnhm** [comment]
@therecipe cool, i will have a try tonight.

**Comment by liugangnhm** [comment]
yes, it works now, just like qt in c++

> If several slots are connected to one signal, the slots will be executed one after the other, in the order they have been connected, when the signal is emitted.

see here http://doc.qt.io/qt-5.8/signalsandslots.html#signals
