### ISSUE TITLE
#include "moc_moc.h" makes tests fail

### ISSUE THREAD

**Issue by MatejLach** [therecipe/qt#243]
System: Linux (Arch Linux x64)

Installed Qt 5.8 with all of its components from the official repositories, however because `moc_moc.h` isn't part of the standard Qt distribution, it makes tests fail. What's its purpose over `moc.h`?

**Comment by therecipe** [comment]
Hey

`moc_moc.h` is created by `moc` from the `moc.cpp` to make your custom signals/slots/properties work. And `moc.h` is just there to make the functions in `moc.cpp` available to Go (in `moc.go`).

You will need `moc.h`, `moc.cpp`, `moc.go` and `moc_moc.h` in the end.
But you should get all of them by running `qtmoc` inside the folder where you "moc structs" are located.

**Comment by MatejLach** [comment]
@therecipe Sure, that makes sense. 

I just followed the install instructions for Linux and ended up here, perhaps it'll be good to add that `qtmoc` 
needs to be run as part of the install process, since the examples that require it are being compiled as part of running `qtsetup`. 

Thanks for your quick response and sorry for the fuss, awesome project.

**Comment by therecipe** [comment]
>`qtmoc` needs to be run as part of the install process, since the examples that require it are being compiled as part of running qtsetup.

Actually, if you run `qtdeploy` (like it's done during the setup), then these `moc*` files will be removed if the compilation was successful. (to prevent littering your project folder(s))

>EDIT: Just noticed that it relies on root privileges to create symlinks, I wonder if that is strictly needed.

I will look into that, as I'm currently refactoring the setup anyway.
Maybe I will let it check all the folders in your PATH, to find one with the right permission.
Or maybe append GOBIN to your PATH.
But both options are not really appealing to me.

>Thanks for your quick response and sorry for the fuss, awesome project.

No problem, you are welcome :)
