### ISSUE TITLE
 docker pull therecipe/qt Error not found

### ISSUE THREAD

**Issue by guanghui1987** [therecipe/qt#244]
root@vultr:~# docker pull therecipe/qt
Using default tag: latest
Error response from daemon: manifest for therecipe/qt:latest not found

Hi, can you tell me that's why?
thanks!!!

**Comment by guanghui1987** [comment]
docker pull therecipe/qt:base for linux development
docker pull therecipe/qt:base_android for android development (+ linux development)
docker pull therecipe/qt:base_windows for windows development (+ linux development)

**Comment by therecipe** [comment]
Hey

yeah, I didn't used the `latest` tag.
for future reference, you can find the tag list here:
https://hub.docker.com/r/therecipe/qt/tags/
