### ISSUE TITLE
tutorial video

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#247]
https://www.youtube.com/watch?v=WIRRoPxIerc

this helped me allot because its a high level one, not about programming but about architectural choices and recommendations.

i did not know qt webview used the OS native web browser for example.
Makes sense now :)

Might be useful to others. Or maybe put a link in the readme for newbies.

**Comment by Kutabe** [comment]
Oh, I think It would be nice to have SLACK channel or something like IRC channel for conversations about Golang QT and instant feedback science it gaining popularity and stability. I beleve soon we will see first stable release and get rid of this frightful **WIP** prefix.

**Comment by jordanorelli** [comment]
oh we have a slack channel. the invite is here:

https://invite.slack.golangbridge.org/

there's a #qt-binding channel in here.

**Comment by Kutabe** [comment]
Oh, thanks! Didn't notice.

**Comment by therecipe** [comment]
>Might be useful to others. Or maybe put a link in the readme for newbies.

Thanks, it's really a nice overview :)
I will add it to the readme.

**Comment by joeblew99** [comment]
Ok i will close this...
