### ISSUE TITLE
Moc and multiple packages

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#251]
I have a large code base, and I wanted to keep into separated packages the `moc`'ed `struct`.

If I `qtmoc` https://github.com/bclermont/mocbug I get:

```
moc.cpp:41: Parse error at "void"
```

Is it possible to have C++ include the `.h` generated elsewhere?

**Comment by therecipe** [comment]
Hey

Yes, moc structs from other packages can't be used as a property or in a signal/slot function currently.
And they also can't be extended.
I pushed these things back, when I worked on it the last time.
But I will look into it again.

**Comment by therecipe** [comment]
the example should work now with: https://github.com/therecipe/qt/commit/2536e26395fc07a1da9eab0d126f98ef3349bf06

and it's now also possible to subclass a moc struct from a different packages
(but there is the limitation, that you can't downcast these classes)

**Comment by bclermont** [comment]
@therecipe thank you!!!

"downcast"?

**Comment by therecipe** [comment]
ah, sorry I meant upcasting.

This is when you cast from a (sub-class to a super-class / child to a parent class / derived class to a base class)
The "casting" can be done with the `*_PTR()` functions or if you use one of the `*_ITF` interfaces


here is an example:

`mocbug/lib`
```go
package lib

import "github.com/therecipe/qt/core"

type MyType struct {
	core.QObject

	_ func(s string) `slot:"someSlot"`

	_ func(s string) `slot:"someSignal"`
}
```

`mocbug`
```go
package main

import "github.com/bclermont/mocbug/lib"

type OtherType struct {
	lib.MyType

	_ bool   `property:"newProperty"`
	_ func() `slot:"newSlot"`
	_ func() `signal:"newSignal"`
}

type SomeOtherType struct {
	OtherType
}

func main() {

	t1 := NewOtherType(nil)
	t1.ConnectSomeSlot(func(s string) { println(s) })
	t1.SomeSlot("hello1")

	//shouldn't work, because you upcast into a type from another package
	t1.MyType_PTR().SomeSlot("hello1")
	upcastAndCallSomeSlot(t1)
	//

	t2 := NewSomeOtherType(nil)
	t2.ConnectSomeSlot(func(s string) { println(s) })
	t2.SomeSlot("hello2")

	//should work, because you upcast into a type from the same package
	t2.SomeOtherType_PTR().SomeSlot("hello2")

	//shouldn't work, because you upcast into a type from another package
	upcastAndCallSomeSlot(t2)
	//

}

func upcastAndCallSomeSlot(m lib.MyType_ITF) {
	m.MyType_PTR().SomeSlot("hello3")
}
```

okay, that's strange
it works now, but it shouldn't ...

at least it didn't worked when I tested it: https://github.com/therecipe/qt/blob/master/internal/cmd/moc/test/qtmoc_test.go#L1637-L1641
I guess, I will need to do some more testing

**Comment by bclermont** [comment]
is this bug still valid?

**Comment by therecipe** [comment]
>is this bug still valid?

https://github.com/bclermont/mocbug, should be fixed at least.

I haven't had time to look into the upcasting issue again, but that's a really specific issue.
So I will wait until it comes up again.
