### ISSUE TITLE
`qtmoc` failed on Protobuf import

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#255]
Hi,

I tried latest code and use `qtmoc` on code that uses Protobuf's import, specifically on `ptypes`. `qtmoc` seems cannot handle that anymore (it used to worked).

I made an example for you on https://github.com/arknable/therecipe-issue.

Thanks.

**Comment by arknable** [comment]
By the way, this is the log when running `qtmoc -debug`'

[log.txt](https://github.com/therecipe/qt/files/864150/log.txt)

**Comment by therecipe** [comment]
Hey

It should be fixed now with: https://github.com/therecipe/qt/commit/6bcfb21c9ac72a0a7efae2f8ea24f193d603f5ff

qtmoc stuck in a infinit recursion caused by the protobuf package

**Comment by arknable** [comment]
Hey, I tried and it works. thanks 👍

**Comment by arknable** [comment]
Hi,

I reopen this issue because it seems that the problem reappears. Please see example on https://github.com/arknable/therecipe-issue. If you remove protobuf and logrus import, `qtmoc` creates `moc*` files, but if we used those imports there are no `moc*` files created. Attached is log output of the failed `qtmoc` using `-debug` switch.
[log.txt](https://github.com/therecipe/qt/files/876357/log.txt)


Thanks.

**Comment by therecipe** [comment]
Sorry, should be fixed with: https://github.com/therecipe/qt/commit/6943fe08ad1a7fe5fdc2d0ef5defc7de4cf7997f

**Comment by arknable** [comment]
tested, confirm that it fixed.
