### ISSUE TITLE
Windwos version problem

### ISSUE THREAD

**Issue by usayao** [therecipe/qt#256]
I would like to ask is only support windowsx86？There is how to configure the windowsx64！

**Comment by therecipe** [comment]
Hey

Yes, the pre-built version is currently only available for 32 bit versions of windows.
But you should be able to install and run it on 64 bit version as well.

Or do you mean the deployment for 64 bit windows version?
That is currently only doable (on windows) if you compile Qt on your own for 64 bit first.

But you could install this binding on linux and cross compile to 64 bit windows: https://github.com/therecipe/qt#instructions

or maybe take a look at the docker images, they support 64 bit windows deployments as well.
