### ISSUE TITLE
Support for qmlRegisterType

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#258]
Hey, 

Do you have plan to support `qmlRegisterType` ? or you already have it ? cause I can't find it.

Thanks.

**Comment by therecipe** [comment]
Hey

I added 2 from 3 qmlRegisterType functions with: https://github.com/therecipe/qt/commit/19b9f87854765d5f0baa5840397428e8bae4bc57

http://doc.qt.io/qt-5/qqmlengine.html#qmlRegisterType
is available for moc classes like this: `NameOfMocClass_QmlRegisterType()`

and you can find http://doc.qt.io/qt-5/qqmlengine.html#qmlRegisterType-2
as `qml.QQmlEngine_QmlRegisterType(url, uri, versionMajor, versionMinor, qmlName)`
and `(*qml.QmlEngine).QmlRegisterType(url, uri, versionMajor, versionMinor, qmlName)`

the one that is still missing is:
`int qmlRegisterType(const char *uri, int versionMajor, int versionMinor, const char *qmlName)`
but it's on my todo list

**Comment by therecipe** [comment]
@arknable 

I had to make some changes to solve this issue https://github.com/therecipe/qt/issues/260 that may affect you

You now need to import `github.com/therecipe/qt/qml` in the "moc package" to make the `NameOfMocClass_QmlRegisterType()` function usable.
(it will be there regardless, but it will only work if you import the "qml", "quick" or "quickcontrols2" package)

The `qml.QQmlEngine_QmlRegisterType(url, uri, versionMajor, versionMinor, qmlName)` is not affected by this.

**Comment by arknable** [comment]
Hi,

Is there a way to use `QQmlEngine_QmlRegisterType` with generic to register go component. Afaik we can register c++ component using `qmlRegisterType<Class>("com.something", 1, 0)`. I tried `Class_QmlRegisterType` function but I can't use registered class in QML. for example if I have class `Message` like this

```
type Message struct {
     core.QObject
}
```

then somewhere in `main` I do
```
Message_QmlRegisterType()
```

I can't add `Message` to qml tree like this:
```
ApplicationWindow {
      Message {}
}
```

I assume that's because the doc said `This template function registers the C++ type in the QML system. Instances of this type cannot be created from the QML system.` so the only way is to use engine's register function that uses generic to register c++ class.

Thanks

**Comment by arknable** [comment]
Hey, 

I put an example of c++ version on https://github.com/arknable/therecipe-issue-support.  that sample described the scenario I'm trying to accomplish.

Thanks.

**Comment by therecipe** [comment]
Added the missing function with: https://github.com/therecipe/qt/commit/9b7d566d6de88ff822434cc38c92ade917ffcffa

So this should work now:

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/qml"
)

type Message struct {
	core.QObject
	_ string `property:"content"`
}

func main() {
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)

	gui.NewQGuiApplication(len(os.Args), os.Args)

	Message_QmlRegisterType2("Dummy", 1, 0, "Message")

	engine := qml.NewQQmlApplicationEngine(nil)

	var messages []*core.QVariant
	m1 := NewMessage(nil)
	m1.SetContent("Message 1")
	messages = append(messages, m1.ToVariant())
	m2 := NewMessage(nil)
	m2.SetContent("Message 2")
	messages = append(messages, m2.ToVariant())
	engine.RootContext().SetContextProperty2("messages", core.NewQVariant24(messages))

	engine.Load(core.NewQUrl3("qrc:/main.qml", 0))

	gui.QGuiApplication_Exec()
}
```

**Comment by arknable** [comment]
Hi, I tried that and it works, thanks a lot 👍

**Comment by djahma** [comment]
Hello, 
where is the documentation for this moc thingy? New to this and now that I need to export Go types, all I could find is this: [https://github.com/therecipe/qt/wiki/Available-Tools#qtmoc](https://github.com/therecipe/qt/wiki/Available-Tools#qtmoc)
For example, you say:

> http://doc.qt.io/qt-5/qqmlengine.html#qmlRegisterType
is available for moc classes like this: NameOfMocClass_QmlRegisterType()

But now it must be called `NameOfMocClass_QmlRegisterType2("Namespace", 1, 0, "Type")`
This '2' is impossible to guess, or am I looking in the wrong places? Anyway, any usage documentation would be much appreciated:)

**Comment by therecipe** [comment]
@djahma
Sorry there is no compressive documentation of qtmoc atm, but it's in the works

For now you will need to dig through the examples to see how this more advanced stuff works: https://github.com/therecipe/examples/tree/master/advanced/qml_quick/gotemplate
