### ISSUE TITLE
QGraphicsSceneMouseEvent

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#26]
```go
	func mousePressEvent(e *widgets.QGraphicsSceneMouseEvent) {
		var color = gui.NewQColor2(160, 160, 160, 255) // r,g,b,a
		var pen = gui.NewQPen3(color)
		pen.SetWidth(1)
		var brush = gui.NewQBrush()

		scene.AddRect2(float64(e.ScreenPos().X()), float64(e.ScreenPos().Y()), 5, 10, pen, brush)

	}
```

AddRect only accepts a float64. Your version of QGraphicsSceneMouseEvent uses only ScreenPos which returns a QPoint, not QPointF.

Running this, the rectangles appear 100 pixels from where the mouse cursor actually is in the scene.

Maybe I have done something wrong?

**Comment by therecipe** [comment]
These work for me now.

```go
func mousePressEvent(e *widgets.QGraphicsSceneMouseEvent) {
	var color = gui.NewQColor2(160, 160, 160, 255) // r,g,b,a
	var pen = gui.NewQPen3(color)
	pen.SetWidth(1)
	var brush = gui.NewQBrush()

	scene.AddRect2(e.ScenePos().X(), e.ScenePos().Y(), 5, 10, pen, brush)
}
```


Or if you override the ConnectMousePressEvent on the `QGraphicsView`
```go
func mousePressEvent(e *gui.QMouseEvent) {
	var color = gui.NewQColor2(160, 160, 160, 255) // r,g,b,a
	var pen = gui.NewQPen3(color)
	pen.SetWidth(1)
	var brush = gui.NewQBrush()

	var pointOnScene = view.MapToScene5(int(e.Pos().X()), int(e.Pos().Y()))
	scene.AddRect2(pointOnScene.X(), pointOnScene.Y(), 5, 10, pen, brush)
}
```

**Comment by 5k3105** [comment]
First example you gave:

```
	build
	output:# local/qt_test
	.\test1.go:178: cannot use e.ScreenPos().X() (type int) as type float64 in argument to scene.AddRect2
	.\test1.go:178: cannot use e.ScreenPos().Y() (type int) as type float64 in argument to scene.AddRect2

	error:exit status 2
```

Second example, it draws the box but now instead of a few hundred pixels to bottom right, it is a few hundred pixels top left from where the mouse is.

**Comment by therecipe** [comment]
Hey

Sorry, you have to sync with the repo first.

Also the first example is slightly edited and now uses `e.ScenePos().X()` instead of `e.ScreenPos().X()`
And the second example needs to be used in `view.ConnectMousePressEvent` (QGraphicsView)

Hope it works now ;)

**Comment by 5k3105** [comment]
I see now. Even when I stare at something several times I miss it. Sorry. It's working now. Thanks!
