### ISSUE TITLE
local imports on AM?

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#262]
Firstly, am raising the issue here ecaue there is no issue list on AM project

i was just playing around with the AM project, but could not get it to compile.
I flipped all the local imports to proper github/therecipe/AM... and the last error is this:

x-MacBook-Pro:AM apple$ go build
# github.com/therecipe/AM/controlbox
controlbox/controlbox.go:136: cannot use "png" (type string) as type core.QByteArray_ITF in argument to gui.NewQImageReader3:
	string does not implement core.QByteArray_ITF (missing QByteArray_PTR method)
x-MacBook-Pro:AM apple$ 

AM looks really useful for a whole host of things. Even visualising the QML relationships on things.

**Comment by therecipe** [comment]
Hey

Yeah, that's just a fork I used once.
You probably should look into this one instead: https://github.com/5k3105/Pipeline-Editor
That's the more polished version of the AM editor.

(But it somehow crashes at runtime for me currently, so I will have to look into it)

>controlbox/controlbox.go:136: cannot use "png" (type string) as type core.QByteArray_ITF in argument to gui.NewQImageReader3:
string does not implement core.QByteArray_ITF (missing QByteArray_PTR method)

Here is one of the related issues: https://github.com/therecipe/qt/issues/126

**Comment by joeblew99** [comment]
yeah its crashing for me too.

I will also try to get it going on the the latest code.

will leave open here for now...
