### ISSUE TITLE
Idea / proposal : domain name path

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#264]
https://gopherpit.com/?utm_source=golangweekly&utm_medium=email

It will make it easy to map a import path to a git tag.
Probably makes sense for the examples to use it.

**Comment by therecipe** [comment]
Ah thanks, that looks interesting and could also be used for branding someday.
I will check if I can make the examples go gettable.

**Comment by joeblew99** [comment]
ok cool. Will leave open for now i guess..
