### ISSUE TITLE
QGrapicsItems Interactions

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#27]
Hi,

I am wanting to hook into events for rectangle, ellipse and text but it looks like these are not completely implemented yet:

QGraphicsEllipseItem
QGraphicsLineItem
QGraphicsPathItem
QGraphicsPixmapItem
QGraphicsPolygonItem
QGraphicsRectItem
QGraphicsSimpleTextItem
QGraphicsTextItem

Thanks

**Comment by therecipe** [comment]
Which functions do you need exactly?

**Comment by 5k3105** [comment]
Hi!,

From your post in (https://github.com/therecipe/qt/issues/12) : 

> if you would want to be able to override virtual functions in QGraphicsLineItem, you would need to create a new QGraphicsLineItem with widgets.NewQGraphicsLineItem and then add it to the scene with scene.AddItem.

I'm trying to use the mouse hover:

hoverEnterEvent(QGraphicsSceneHoverEvent *)
hoverLeaveEvent(QGraphicsSceneHoverEvent *)
hoverMoveEvent(QGraphicsSceneHoverEvent *)

It's possible I'm not going about it right. So for each line or rectangle or circle I plot on the scene I want it to trigger it's hover events so I know which item it's over.

I tried this last week and it's didn't seem to work (I used AddRect, setAcceptHoverEvents and ConnectHoverEnterEvent I believe) then I remembered your post about that.

Thanks

**Comment by therecipe** [comment]
Hey

Yes, you need to create the items directly with `NewQ*` instead of `add*`.
(Because you want to override virtual functions and not signals)

You might want to also call the default virtual implementation (which always ends with `*Default`)


This works for me:
```go
	var text = widgets.NewQGraphicsSimpleTextItem2("Hello 世界", nil)
	text.SetFont(gui.NewQFont2("Meiryo", 20, 2, false))
	text.SetAcceptHoverEvents(true)

	text.ConnectHoverEnterEvent(func(e *widgets.QGraphicsSceneHoverEvent) {
		text.SetText("entered")
		text.HoverEnterEventDefault(e)
	})

	text.ConnectHoverMoveEvent(func(e *widgets.QGraphicsSceneHoverEvent) {
		text.SetText(fmt.Sprintf("moved %v %v", e.ScenePos().X(), e.ScenePos().Y()))
		text.HoverMoveEventDefault(e)
	})

	text.ConnectHoverLeaveEvent(func(e *widgets.QGraphicsSceneHoverEvent) {
		text.SetText("leaved")
		text.HoverLeaveEventDefault(e)
	})

	scene.AddItem(text)
```

**Comment by 5k3105** [comment]
I wonder what I was looking at. They are all implemented :/

Sorry! Thanks!

**Comment by 5k3105** [comment]
With ```text.SetPos2(50, 50)``` this modification gives "moved 0 0" :

```go
	text.ConnectHoverMoveEvent(func(e *widgets.QGraphicsSceneHoverEvent) {
		var x, y = e.Pos().X(), e.Pos().Y()
		var i = scene.ItemAt3(x, y, nil)
		x, y = i.X(), i.Y()
		text.SetText(fmt.Sprintf("moved %v %v", x, y))
		text.HoverMoveEventDefault(e)
	})
```

Same with this:

```go
	text.ConnectHoverMoveEvent(func(e *widgets.QGraphicsSceneHoverEvent) {
		var x, y = e.Pos().X(), e.Pos().Y()
		var i = scene.ItemAt3(x, y, nil)
		var p = core.NewQPointF()
		p = i.ScenePos()
		x, y = p.X(), p.Y()
		text.SetText(fmt.Sprintf("moved %v %v", x, y))
		text.HoverMoveEventDefault(e)
	})
```

I would have thought x,y would be the coords of where the item is in the scene - 50 50.

My application draws rectangles on a grid. I am trying to retrieve the xy of the hovered item. Instead it always returns 0,0.

**Comment by 5k3105** [comment]
It's strange that didn't work - but I found a better solution by subclassing QGaphicsItem. Thanks.

**Comment by therecipe** [comment]
Hey

This gives me `moved 50 50`

```go
	text.SetPos2(50, 50)

	text.ConnectHoverMoveEvent(func(e *widgets.QGraphicsSceneHoverEvent) {
		var x, y = e.ScenePos().X(), e.ScenePos().Y()
		var i = scene.ItemAt3(x, y, nil)
		x, y = i.X(), i.Y()

		text.SetText(fmt.Sprintf("moved %v %v", x, y))
		text.HoverMoveEventDefault(e)
	})

	text.ConnectHoverMoveEvent(func(e *widgets.QGraphicsSceneHoverEvent) {
		var x, y = e.ScenePos().X(), e.ScenePos().Y()
		var i = scene.ItemAt3(x, y, nil)
		var p = i.ScenePos()
		x, y = p.X(), p.Y()

		text.SetText(fmt.Sprintf("moved %v %v", x, y))
		text.HoverMoveEventDefault(e)
	})
```

I just needed to replace `e.Pos()` with `e.ScenePos()`.


There are 3 different current positions you can get from the event `e.Pos(), e.ScenePos() and e.ScreenPos()` and you probably want to use `e.ScenePos()` most of the time.

Maybe take a look here: http://doc.qt.io/qt-5/qgraphicsscenehoverevent.html#pos
