### ISSUE TITLE
binarycreator

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#271]
I was playing around with packaging today.

https://andrewdolby.com/articles/2016/continuous-deployment-for-qt-applications/

Is there any possibility to make an example to show how to do this for Windows and osx ?

Thank you.

**Comment by therecipe** [comment]
>Is there any possibility to make an example to show how to do this for Windows and osx ?

There are a few ways to get CD working.
And I'm currently in the process of re-writing the readme and will write a bit about the topic there as well.

But you basically got a few options for CD:
* You could look into the ci folder [here](https://github.com/therecipe/qt/tree/master/internal/ci) and the *.yml files in the root folder of the repo, to get some inspiration how to get it working like shown in the article.
* You could skip the installation of the "non-go" dependencies and pull the docker images instead and then use `qtdeploy -docker ...`
* You could just pull the docker images and then automate your deployments in a disposal container.
* Or you could build upon the docker images with `FROM therecipe/qt:TAG` and then create your own docker images.

**Comment by joeblew99** [comment]
Ok that sounds like i should wait for the new readme and see what is in it.

Thanks and will close this.
