### ISSUE TITLE
Flux pattern implementation

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#272]
Flux allows loose coupling between components and a unidirectional flow of data.

There is a very popular Qt lib for this:
https://github.com/benlau/quickflux

This would make a huge difference to building large maintainable applications.

There is an excellent documentation link if you have not used flux before too

**Comment by joeblew99** [comment]
There are some Google examples in the repo but i think its useful to see it being used by the main Ubuntu distros email and cal app here:

https://code.dekkoproject.org/dekko-dev/dekko/blob/master/Dekko/Mail/app/Dekko.qml

**Comment by therecipe** [comment]
Hey

That looks interesting :)

It's probably possible that you can already use it with only a few changes, because you will only need access to the QML api.

I will try to get it working in an example.

**Comment by joeblew99** [comment]
Yeah i noticed it's heavy on qml and not c++.
Thanks it will be a huge help.

I should add that he has a test runner too.

https://github.com/benlau/testable/
I am in two minds about this as i am still getting into testing.
The Qt approach is very golangy.
Devs need to test at different leveld
1. Golang only
2. Qml which will call golang.

So i am thinking that using some leading golang testing toolkit that has a "plugin" to also call the Qt tests might be useful.
Still not sure yet though.

Anyway. If you can get flux working it's pretty huge. It solves some hairy issues

**Comment by joeblew99** [comment]
The flux repo is using qml unit tests.

https://github.com/benlau/quickflux/tree/master/tests/quickfluxunittests

But he has written a Testrunner that is in another of his git repositories. Easy to find.
I looks like a compelling approach.

Just wanted to point this out since the Testrunner is the initiatory

**Comment by joeblew99** [comment]
Here is the testrunner he has written to drive the flux code.

https://github.com/benlau/testable

**Comment by therecipe** [comment]
added a new example (the "todo" example from the quickflux repo) with: https://github.com/therecipe/qt/commit/2a0989d91f9d7c038d0205384ffaa17ddb1d1f31

You probably need to edit the "cgo_stub.go" file in ("qml/todo/quickflux") to point to your "qmake" binary. After that, you need to also run "go generate" once, either in "qml/todo" or in "qml/todo/quickflux". Then you can use "qtdeploy" as usual.

About the testing, I will take a look.
But from a quick glance it seems like there is the need to access the C++ api.

>https://github.com/benlau/quickflux/tree/master/tests/quickfluxunittests

Is probably easier to get working.

**Comment by gedw99** [comment]
thanks you.
Ok yep i see the path in the cgo_stug.go.

Will give it a whirl and let you knwo how i go
