### ISSUE TITLE
undefined: QAndroidJniEnvironment error during qtsetup

### ISSUE THREAD

**Issue by kybin** [therecipe/qt#277]
Hello, I encountered this error during qtsetup.

```
androidextras/androidextras.go:9:10: undefined: QAndroidJniEnvironment

...

failed to install the following 1 package(s):
androidextras
```

It suggests me to `qtsetup install linux`. So I followed, but the same error occurred.

**Comment by therecipe** [comment]
Hey

Did you install a Qt version with android support?
 
Maybe try to remove the `qt/androidextras` folder and run the setup again.

**Comment by kybin** [comment]
Hi, it revives when I run `qtsetup`.

**Comment by therecipe** [comment]
What Qt version do you use?

If you use the plain normal "official" pre-built version, then are you sure you installed a version that has android support?
And that you didn't opt out the android support during the installation?

Could you take a look if you got the `android_armv7` in `path/to/Qt/5.8/`?
And maybe post a longer log with the `androidextras/androidextras.go:9:10: undefined: QAndroidJniEnvironment` error?

**Comment by kybin** [comment]
It was because I setup wrong QT_DIR.

My setup was

```
export QT_DIR=$HOME/Qt/5.8
export QT_QMAKE_DIR=$QT_DIR/gcc_64/bin
```

Proper setup is

```
export QT_DIR=$HOME/Qt
export QT_QMAKE_DIR=$QT_DIR/5.8/gcc_64/bin
```

Now my `qtsetup` works like a charm. Sorry for the noise.

Cheers!

**Comment by therecipe** [comment]
:) no problem
