### ISSUE TITLE
qt/webview: no buildable Go source files in

### ISSUE THREAD

**Issue by avdva** [therecipe/qt#279]
Hi, I'm building static windows binary under linux from docker and getting the following error:
```
qtdeploy -docker build windows
time="2017-04-10T10:43:13Z" level=debug msg=Execute cmd="go build -p 4 -v -ldflags="-s" "-w" "-H=windowsgui" -o /media/sf_GOPATH0/src/cesanta.com/mos/deploy/windows/mos.exe -tags="windows" "minimal" -pkgdir /home/user/work/pkg/windows_windows_386" env="CGO_ENABLED=1 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin GOPATH=/home/user/work:/media/sf_GOPATH0 GOOS=windows GOROOT=/usr/local/go CC=/usr/lib/mxe/usr/bin/i686-w64-mingw32.static-gcc CXX=/usr/lib/mxe/usr/bin/i686-w64-mingw32.static-g++ GOARCH=386" func=RunCmd name="build for windows on linux" 
time="2017-04-10T10:43:13Z" level=error msg="failed to run command" cmd="go build -p 4 -v -ldflags="-s" "-w" "-H=windowsgui" -o /media/sf_GOPATH0/src/cesanta.com/mos/deploy/windows/mos.exe -tags="windows" "minimal" -pkgdir /home/user/work/pkg/windows_windows_386" env="CGO_ENABLED=1 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin GOPATH=/home/user/work:/media/sf_GOPATH0 GOOS=windows GOROOT=/usr/local/go CC=/usr/lib/mxe/usr/bin/i686-w64-mingw32.static-gcc CXX=/usr/lib/mxe/usr/bin/i686-w64-mingw32.static-g++ GOARCH=386" error="exit status 1" func=RunCmd name="build for windows on linux" 
ui_qt.go:11:2: no buildable Go source files in /home/user/work/src/github.com/therecipe/qt/webview
```
The same happens, if I pass `-fast` flag.
How can it be fixed?

**Comment by therecipe** [comment]
Hey

Yes, unfortunately the webengine/webview packages are not working for windows currently.
The problem is that these packages can't be compiled with the mingw version of gcc (or the cross compiler).
They are currently only supported by the msvc, and that one wasn't supported by Go the last time I checked. (It might be supported with Go 1.9)

So for windows the only real option currently is the [webkit](https://github.com/annulen/webkit).
But that one isn't supported out of the box currently.
Here is the related issue: https://github.com/therecipe/qt/issues/121

**Comment by avdva** [comment]
Thanks a lot for your explanation.

**Comment by therecipe** [comment]
No problem :)

I looked into the WebKit issue again and added the support with: https://github.com/therecipe/qt/commit/6d11509f782efa2ee6dc56a0a6f2153198c5ac43

I'm not sure if it's useful for your use case, but you can find the instruction how to get it working here: https://github.com/therecipe/qt#additional-modules

**Comment by averrin** [comment]
Aaand again i wrote code which works fine on linux and not fails to compile on windows (first time it was plugins). So sad=( I hate windows=(

**Comment by dosaki** [comment]
I get a similar problem with JetBrains's Gogland, but it builds ok on the command line.
