### ISSUE TITLE
Undefined alias when using two sub package

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#283]
Hi,

I encountered following error when running `go test`,
```
# github.com/arknable/therecipe-issue-support/connection
./moc.go:58: undefined: custom_duration in custom_duration.MyDuration
./moc.go:60: undefined: custom_duration in custom_duration.NewMyDurationFromPointer
./moc.go:69: undefined: custom_duration in custom_duration.MyDuration_ITF
./moc.go:71: undefined: custom_duration in custom_duration.PointerFromMyDuration
./moc.go:78: undefined: custom_duration in custom_duration.MyDuration
./moc.go:83: undefined: custom_duration in custom_duration.MyDuration
./moc.go:91: undefined: custom_duration in custom_duration.MyDuration
./moc.go:92: undefined: custom_duration in custom_duration.MyDuration
./moc.go:108: undefined: custom_duration in custom_duration.MyDuration_ITF
./moc.go:110: undefined: custom_duration
./moc.go:110: too many errors
FAIL    github.com/arknable/therecipe-issue-support/connection [build failed]
```

I checked `moc.go` and there was no import with `custom_duration` as alias and it should be there. I have a simple example for you to try on `https://github.com/arknable/therecipe-issue-support`. To try it, just run `qtmoc` in all package and run test in `connection` package. If we remove line 5 and 12 (`user` package) of `connection.go`, then the issue doesn't occurs.

Do you have any idea what might cause this ?

Thanks.

**Comment by therecipe** [comment]
Hey

Should be fixed now with: https://github.com/therecipe/qt/commit/2162f6ccc4ada1aee096975c291340c5bfade59b

It was a caching issue.

**Comment by arknable** [comment]
tested, it fixed, thanks.
