### ISSUE TITLE
run qtsetup error when using webkit on osx 

### ISSUE THREAD

**Issue by yandd** [therecipe/qt#287]
INFO[0159] generating full qt/webkit
ERRO[0161] failed to run command                         cmd="/usr/local/opt/qt5/bin/qmake /Users/yandongdong/works/go/src/github.com/therecipe/qt/webkit.pro -spec macx-clang CONFIG+=x86_64" env= error="exit status 3" func=RunCmdOptional name="run qmake for darwin on darwin"
Info: creating stash file /Users/yandongdong/works/go/src/github.com/therecipe/qt/webkit/.qmake.stash
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets

ERRO[0161] failed to load /Users/yandongdong/works/go/src/github.com/therecipe/qt/webkit/Makefile  error="open /Users/yandongdong/works/go/src/github.com/therecipe/qt/webkit/Makefile: no such file or directory"

**Comment by therecipe** [comment]
Hey

Did you extra the pre-built modules in `QT_DIR/5.8/{mingw53_32|clang_64|gcc_64}`?

**Comment by yandd** [comment]
I already extracted `qtwebkit-tp5-qt58-darwin-x64.tar.xz` to `/usr/local/opt/qt5/clang_64`, `/usr/local/opt/qt5/gcc_64`, `/usr/local/opt/qt5/5.8/clang_64` and `/usr/local/opt/qt5/5.8/gcc_64`

**Comment by therecipe** [comment]
ah, sorry the instruction was meant for the "official" installation

If you use HomeBrew, then you probably need to extract it in `/usr/local/Cellar/qt5/5.8.0_1` or `/usr/local/opt/qt5`
