### ISSUE TITLE
qtdeploy create files/directories as root

### ISSUE THREAD

**Issue by toxinu** [therecipe/qt#290]
Every time I run another `qtdeploy` I have this error:

```golang
PANI[0000] failed to remove deploy folder                error="remove deploy/linux/test-app.sh: permission denied"
panic: (*logrus.Entry) (0x721ba0,0xc420234550)

goroutine 1 [running]:
github.com/Sirupsen/logrus.Entry.log(0xc420078140, 0xc42021ab70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40e100, ...)
	[...]/src/github.com/Sirupsen/logrus/entry.go:124 +0x340
github.com/Sirupsen/logrus.(*Entry).Panic(0xc420234500, 0xc420055d80, 0x1, 0x1)
	[...]/src/github.com/Sirupsen/logrus/entry.go:169 +0x11b
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x7ffc5746079f, 0x5, 0x7ffc574607a5, 0x5, 0xc420020044, 0x2e, 0x1, 0x0, 0x0, 0x7fb316dca400)
	[...]/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:26 +0xc74
main.main()
	[...]/src/github.com/therecipe/qt/cmd/qtdeploy/main.go:102 +0x34a
Makefile:6: recipe for target 'build-linux' failed
make: *** [build-linux] Error 2
```

Why `qtdeploy` create files and directories as root user?

**Comment by therecipe** [comment]
Hey

Sorry, it should be fixed already since yesterday with: https://github.com/therecipe/qt/commit/567a43070480ca267f7feebda314c6064d7cfd89

>Why qtdeploy create files and directories as root user?

I honestly forgot why `qtdeploy`  and `qtsetup` did that in the first place.

**Comment by toxinu** [comment]
Thanks for your quick answer!
Strange that I tried `qt` just 3-4 hours ago.
I'll update it and give you feedback about it soon.

**Comment by therecipe** [comment]
>In addition, permission denied error is because files are created as root and not because of too restrictive chmod.

ah, sorry then I got it wrong,  thought it was a chmod issue.

But `qtdeploy` shouldn't create files or folders as root at all.

These are the functions that are used to create folder and/or files: https://github.com/therecipe/qt/blob/master/internal/utils/utils.go#L23-L65

**Comment by therecipe** [comment]
@sandangel  Thank you :)

**Comment by sandangel** [comment]
it seem that you 're using a Makefile to auto build steps with docker.
if so you should modify the Makefile instead of modiffy utils.go
For example:
```Makefile
docker:
    @docker run -v $PWD:/projects buildImage:linux make all

all: build perm

build:
    @build command

perm:
    @chown -R $(shell stat -c '%u:%g' .) .
```

**Comment by therecipe** [comment]
@sandangel 
Thanks, it should be fixed with: https://github.com/therecipe/qt/commit/08810ca7099aa976b31f3c84d56bf7a1f3465007

It's fixed now by passing the current uid+gid to docker. That way there is no need to  chown the files afterwards.
