### ISSUE TITLE
Qt question: setproperty on qtreewidgetitem

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#294]
I've read that another way to set styles on a widget is to use qobject.setproperty (http://doc.qt.io/qt-5/qobject.html#setProperty) which sets the state which can be accessed within a qstylesheet. I am unable to get to that method from qtreewidgetitem though.

Is this not available for this type of widget (as I have also found out about focus methods)?

Thanks.

**Comment by therecipe** [comment]
Hey

>Is this not available for this type of widget (as I have also found out about focus methods)?

Yes, I think it's not available because [QTreeWidgetItem](http://doc.qt.io/qt-5/qtreewidgetitem.html) is not derived from QObject.

**Comment by 5k3105** [comment]
Thanks.
