### ISSUE TITLE
Can't build demos for iOS 10

### ISSUE THREAD

**Issue by MikeHawkesCapventis** [therecipe/qt#297]
I'm getting errors when using qtdeploy on OSX that say I'm using features that require IOS 8 or greater. I can see compile/link flags that suggest iphoneos of 7.0, but can't find a way to change it. Any help appreciated.

c_main_wrapper_arm64.cpp:2:14: warning: unused parameter 'argc' [-Wunused-parameter]
int main(int argc, char *argv[]) { go_main_wrapper(); }
             ^
c_main_wrapper_arm64.cpp:2:26: warning: unused parameter 'argv' [-Wunused-parameter]
int main(int argc, char *argv[]) { go_main_wrapper(); }
                         ^
2 warnings generated.
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/XCTest.framework/XCTest) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by therecipe** [comment]
Hey

Sorry, should be fixed for now with: https://github.com/therecipe/qt/commit/118c850fc3e17743687b9404abe053e3ac844b43

**Comment by MikeHawkesCapventis** [comment]
Thanks lots - a bit closer - but some working, some not. The webengine demo example dies with:

```
# qtdeploy build ios
ERRO[0038] failed to run command                         cmd="go build -p 12 -v -ldflags="-w" -o /Users/mikehawkes/Work/Capventis/Source/src/github.com/therecipe/qt/internal/examples/widgets/webengine/deploy/ios/libgo.a -tags="ios" "minimal" -pkgdir /Users/mikehawkes/Work/Capventis/Source/pkg/ios_darwin_arm64 -buildmode c-archive" env="GOOS=darwin CGO_CPPFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk -miphoneos-version-min=7.0 -arch arm64 CGO_LDFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk -miphoneos-version-min=7.0 -arch arm64 CGO_ENABLED=1 PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/go/bin:/Users/mikehawkes/Work/Capventis/Source/bin GOPATH=/Users/mikehawkes/Work/Capventis/Source GOROOT=/usr/local/go GOARCH=arm64" error="exit status 2" func=RunCmd name="build for ios on darwin"
runtime/internal/sys
runtime/internal/atomic
runtime
sync/atomic
errors
internal/race
math
unicode/utf8
unicode
runtime/cgo
sync
io
syscall
strings
strconv
reflect
time
os
github.com/therecipe/qt/webengine
fmt
# github.com/therecipe/qt/webengine
../../../../webengine/webengine-minimal.cpp:9:10: fatal error: 'QStringList' file not found

```

Along with a lot if warnings about united parameters ... 

`# github.com/therecipe/qt/core
../../../../core/core-minimal.cpp:124:40: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:318:54: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:333:50: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:355:40: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:422:46: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:452:55: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:467:48: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:522:56: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:542:49: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:562:48: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:582:61: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:597:60: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:612:59: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:627:58: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:807:47: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:822:40: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:870:42: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:885:52: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:900:45: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:915:45: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:930:44: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:945:40: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1195:41: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1210:40: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1225:41: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1668:54: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1683:55: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1698:55: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1713:52: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1728:53: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1773:43: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1788:46: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:1803:54: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:2068:47: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:2088:47: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:2103:47: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:2123:39: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:2143:39: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:2158:38: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:2178:53: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:2193:53: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:2208:49: warning: unused parameter 'ptr' [-Wunused-parameter]
../../../../core/core-minimal.cpp:2223:48: warning: unused parameter 'ptr' [-Wunused-parameter]
# github.com/therecipe/qt/core
/tmp/go-build571861996/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]
/tmp/go-build571861996/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]
/tmp/go-build571861996/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]
/tmp/go-build571861996/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]
/tmp/go-build571861996/github.com/therecipe/qt/core/_obj/_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]
/tmp/go-build571861996/github.com/therecipe/qt/core/_obj/_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]
/tmp/go-build571861996/github.com/therecipe/qt/core/_obj/_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]
/tmp/go-build571861996/github.com/therecipe/qt/core/_obj/_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]
/tmp/go-build571861996/github.com/therecipe/qt/core/_obj/_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]
`

**Comment by therecipe** [comment]
Ah, yes the webengine is only available on Linux and macOS http://doc.qt.io/qt-5/qtwebengine-overview.html#platform-notes. (Windows is not supported because of the reasons stated here: https://github.com/therecipe/qt/issues/279)

But the webview is available on Linux, macOS, Android and iOS: https://github.com/therecipe/qt/tree/master/internal/examples/qml/webview

And only the webkit is available on Windows, macOS and Linux.

**Comment by MikeHawkesCapventis** [comment]
Thank you!
