### ISSUE TITLE
Deprecated headers in designer.cpp

### ISSUE THREAD

**Issue by MikeHawkesCapventis** [therecipe/qt#298]
I'm getting a build error on OSX - is there an easy fix for this please?

go install -p 12 -v github.com/therecipe/qt/designer
github.com/therecipe/qt/designer
# github.com/therecipe/qt/designer
In file included from ../src/github.com/therecipe/qt/designer/designer.cpp:25:
../../../../capventis.com/QT5_8/5.8/clang_64/lib/QtDesigner.framework/Headers/QDesignerCustomWidgetCollectionInterface:4:4: warning: Header <QtDesigner/QDesignerCustomWidgetCollectionInterface> is deprecated. Please include <QtUiPlugin/QDesignerCustomWidgetCollectionInterface> instead. [-W#warnings]
../../../../capventis.com/QT5_8/5.8/clang_64/lib/QtDesigner.framework/Headers/QDesignerCustomWidgetCollectionInterface:8:10: fatal error: 'QtUiPlugin/QDesignerCustomWidgetCollectionInterface' file not found

**Comment by therecipe** [comment]
Hey

Ah, yes this one is long overdue, I will look into it.

**Comment by joeblew99** [comment]
Would be cool if this worked.
Am thinking some tooling integration can then be worked up, almost like a quasi idea.
I currently do this with pure golang projects with a file watcher and go generate with a web GUI, it makes keeping track of everything easier. It could be loaded into a webview in a Qt application.
We could then extend it to do moc and other codegen things and give the user / develop good feedback.
Just an idea I have had for a while.

I can work up a basic demo if you want and upload it into a repo
