### ISSUE TITLE
Resulting .app does just launch half way on other Macs

### ISSUE THREAD

**Issue by philiplb** [therecipe/qt#299]
Hi,

I run qtdeploy build and copy the resulting (around 50mb big) .app file onto another Mac. But when I double click on it, no window opens. But the application itself seems to be running, an icon appears in the dock and I can tab to it and cmd+q it.
When I launch it in the terminal via "open ....app", nothing appears on stdout.
Nothing appears in the macOS console.
Any clue how to debug this?

**Comment by joeblew99** [comment]
it may depend on how you linked to qt ?
did you use the brew install QT OR the full QT install ?

**Comment by philiplb** [comment]
The full QT install. May it help if I list the .app contents here?

**Comment by therecipe** [comment]
Hey

>When I launch it in the terminal via "open ....app", nothing appears on stdout.

You probably just need to run `./deploy/darwin/project_name.app/Contents/MacOS/project_name` instead, to get the stdout.

>May it help if I list the .app contents here?

Yes, and maybe also which (qt) packages you used.

**Comment by philiplb** [comment]
Hi,
thank you for the response.
Absolutly weird: If I zip the program, transfer it to the other machine, unzip it, then it works just fine.
When I directly scp everything, macOS shows a broken default icon and it doesn't work (all files were transfered successfully).
Anyway, this is no therecipe/qt issue. :) Great library btw, thank you! This will be my goto choice for cross platform UI development.

**Comment by therecipe** [comment]
Thanks for the kind words :)

>Absolutly weird: If I zip the program, transfer it to the other machine, unzip it, then it works just fine.
When I directly scp everything, macOS shows a broken default icon and it doesn't work (all files were transfered successfully).

Maybe scp broke the symlinks somehow, you probably need to use `rsync` instead if you want to preserve them.

**Comment by philiplb** [comment]
I really think Golang plus qt makes a great couple for the quick GUI from time to time. :) C++ has a bigger project setup plus an hell of a setup for cross platform, JavaFX comes with the big JVM and the commercial part where Oracle started to sue in strange ways, Lazarus would be nice but has its hickups.
I close this as the issue is resolved for me. :)
