### ISSUE TITLE
suggest: create one new project: qtbase,just support  binding for qtbase

### ISSUE THREAD

**Issue by sunwangme** [therecipe/qt#30]
we just build desktop classic app ,just need qtbase/qtwidget.
almost people just need one useful uilib,but none,so build gui with c++.

**Comment by sunwangme** [comment]
as i know, nobody use qml to build app. it is a bad solution.

**Comment by sunwangme** [comment]
gopher dont like complex, just one bare qtwidget binding, is ok.

**Comment by therecipe** [comment]
Hey

I'm not sure what exactly you want to suggest.
Do you mean I should merge the modules (qtcore/qtgui/qtwidget) into on big module (qtbase)?

I tried to mimic the way you usually use qt, therefore I kept them in separate modules.

**Comment by sunwangme** [comment]
just qtcore qtgui qtwidget，no others
