### ISSUE TITLE
why can't i install on windows?please help,thx!

### ISSUE THREAD

**Issue by baofengqqwwff** [therecipe/qt#302]
"C:\Program Files (x86)\JetBrains\Gogland 171.3780.106\bin\runnerw.exe" E:/Go\bin\go.exe run E:/GoProject/src/github.com/therecipe/qt/cmd/qtsetup/main.go
time="2017-04-28T09:34:06+08:00" level=info msg="running: 'qtsetup prep'" 
time="2017-04-28T09:34:07+08:00" level=info msg="running: 'qtsetup check windows' [docker=false]" 
time="2017-04-28T09:34:07+08:00" level=info msg="GOOS:                        'windows'" 
time="2017-04-28T09:34:07+08:00" level=info msg="GOARCH:                      'amd64'" 
time="2017-04-28T09:34:07+08:00" level=info msg="GOVERSION:                   'go1.8.1'" 
time="2017-04-28T09:34:07+08:00" level=info msg="GOROOT:                   *  'E:/Go'" 
time="2017-04-28T09:34:07+08:00" level=info msg="GOPATH:                   *  'E:/GoProject'" 
time="2017-04-28T09:34:07+08:00" level=info msg="GOBIN:                       'E:\GoProject\bin'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_HASH:                     '118c850fc3e17743687b9404abe053e3ac844b43'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_VERSION:                  '5.8.0'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_VERSION_MAJOR:            '5.8'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_DIR:                   *  'E:\QT'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_STUB:                     'true'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_DEBUG:                    'false'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_QMAKE_DIR:                ''" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_WEBKIT:                   'false'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_MSYS2:                 *  'true'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_MSYS2_DIR:             *  'E:\msys64\mingw64'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_MSYS2_ARCH:            *  'amd64'" 
time="2017-04-28T09:34:07+08:00" level=info msg="QT_MSYS2_STATIC:          *  'false'" 
time="2017-04-28T09:34:07+08:00" level=info msg="running: 'qtsetup generate windows' [docker=false]" 
time="2017-04-28T09:34:14+08:00" level=info msg="generating stub qt/core" 
time="2017-04-28T09:34:16+08:00" level=info msg="generating stub qt/androidextras" 
time="2017-04-28T09:34:17+08:00" level=info msg="generating stub qt/gui" 
time="2017-04-28T09:34:19+08:00" level=info msg="generating stub qt/network" 
time="2017-04-28T09:34:20+08:00" level=info msg="generating stub qt/xml" 
time="2017-04-28T09:34:20+08:00" level=info msg="generating stub qt/dbus" 
time="2017-04-28T09:34:21+08:00" level=info msg="generating stub qt/nfc" 
time="2017-04-28T09:34:21+08:00" level=info msg="generating stub qt/script" 
time="2017-04-28T09:34:21+08:00" level=info msg="generating stub qt/sensors" 
time="2017-04-28T09:34:21+08:00" level=info msg="generating stub qt/positioning" 
time="2017-04-28T09:34:22+08:00" level=info msg="generating stub qt/widgets" 
time="2017-04-28T09:34:29+08:00" level=info msg="generating stub qt/sql" 
time="2017-04-28T09:34:30+08:00" level=info msg="generating stub qt/qml" 
time="2017-04-28T09:34:30+08:00" level=info msg="generating stub qt/websockets" 
time="2017-04-28T09:34:30+08:00" level=info msg="generating stub qt/xmlpatterns" 
time="2017-04-28T09:34:30+08:00" level=info msg="generating stub qt/bluetooth" 
time="2017-04-28T09:34:30+08:00" level=info msg="generating stub qt/webchannel" 
time="2017-04-28T09:34:31+08:00" level=info msg="generating stub qt/svg" 
time="2017-04-28T09:34:31+08:00" level=info msg="generating stub qt/multimedia" 
time="2017-04-28T09:34:33+08:00" level=info msg="generating stub qt/quick" 
time="2017-04-28T09:34:33+08:00" level=info msg="generating stub qt/help" 
time="2017-04-28T09:34:34+08:00" level=info msg="generating stub qt/location" 
time="2017-04-28T09:34:34+08:00" level=info msg="generating stub qt/scripttools" 
time="2017-04-28T09:34:34+08:00" level=info msg="generating stub qt/uitools" 
time="2017-04-28T09:34:34+08:00" level=info msg="generating stub qt/winextras" 
time="2017-04-28T09:34:34+08:00" level=info msg="generating stub qt/testlib" 
time="2017-04-28T09:34:34+08:00" level=info msg="generating stub qt/serialport" 
time="2017-04-28T09:34:34+08:00" level=info msg="generating stub qt/serialbus" 
time="2017-04-28T09:34:35+08:00" level=info msg="generating stub qt/printsupport" 
time="2017-04-28T09:34:35+08:00" level=info msg="generating stub qt/designer" 
time="2017-04-28T09:34:36+08:00" level=info msg="generating stub qt/scxml" 
time="2017-04-28T09:34:36+08:00" level=info msg="generating stub qt/gamepad" 
time="2017-04-28T09:34:36+08:00" level=info msg="generating stub qt/purchasing" 
time="2017-04-28T09:34:36+08:00" level=info msg="generating stub qt/datavisualization" 
time="2017-04-28T09:34:36+08:00" level=info msg="generating stub qt/charts" 
time="2017-04-28T09:34:37+08:00" level=info msg="generating stub qt/speech" 
time="2017-04-28T09:34:37+08:00" level=info msg="generating stub qt/quickcontrols2" 
time="2017-04-28T09:34:37+08:00" level=info msg="generating stub qt/sailfish" 
time="2017-04-28T09:34:37+08:00" level=info msg="running: 'qtsetup install windows' [docker=false]" 
time="2017-04-28T09:34:37+08:00" level=info msg="installing stub qt/core" 
time="2017-04-28T09:34:40+08:00" level=info msg="installing stub qt/androidextras" 
time="2017-04-28T09:34:40+08:00" level=info msg="installing stub qt/gui" 
time="2017-04-28T09:34:43+08:00" level=info msg="installing stub qt/network" 
time="2017-04-28T09:34:45+08:00" level=info msg="installing stub qt/xml" 
time="2017-04-28T09:34:46+08:00" level=info msg="installing stub qt/dbus" 
time="2017-04-28T09:34:46+08:00" level=info msg="installing stub qt/nfc" 
time="2017-04-28T09:34:47+08:00" level=info msg="installing stub qt/script" 
time="2017-04-28T09:34:48+08:00" level=info msg="installing stub qt/sensors" 
time="2017-04-28T09:34:49+08:00" level=info msg="installing stub qt/positioning" 
time="2017-04-28T09:34:50+08:00" level=info msg="installing stub qt/widgets" 
time="2017-04-28T09:35:03+08:00" level=info msg="installing stub qt/sql" 
time="2017-04-28T09:35:04+08:00" level=info msg="installing stub qt/qml" 
time="2017-04-28T09:35:05+08:00" level=info msg="installing stub qt/websockets" 
time="2017-04-28T09:35:05+08:00" level=info msg="installing stub qt/xmlpatterns" 
time="2017-04-28T09:35:06+08:00" level=info msg="installing stub qt/bluetooth" 
time="2017-04-28T09:35:06+08:00" level=info msg="installing stub qt/webchannel" 
time="2017-04-28T09:35:07+08:00" level=info msg="installing stub qt/svg" 
time="2017-04-28T09:35:07+08:00" level=info msg="installing stub qt/multimedia" 
time="2017-04-28T09:35:10+08:00" level=info msg="installing stub qt/quick" 
time="2017-04-28T09:35:12+08:00" level=info msg="installing stub qt/help" 
time="2017-04-28T09:35:14+08:00" level=info msg="installing stub qt/location" 
time="2017-04-28T09:35:14+08:00" level=info msg="installing stub qt/scripttools" 
time="2017-04-28T09:35:15+08:00" level=info msg="installing stub qt/uitools" 
time="2017-04-28T09:35:15+08:00" level=info msg="installing stub qt/winextras" 
time="2017-04-28T09:35:16+08:00" level=info msg="installing stub qt/testlib" 
time="2017-04-28T09:35:17+08:00" level=info msg="installing stub qt/serialport" 
time="2017-04-28T09:35:17+08:00" level=info msg="installing stub qt/serialbus" 
time="2017-04-28T09:35:18+08:00" level=info msg="installing stub qt/printsupport" 
time="2017-04-28T09:35:19+08:00" level=info msg="installing stub qt/designer" 
time="2017-04-28T09:35:20+08:00" level=info msg="installing stub qt/scxml" 
time="2017-04-28T09:35:21+08:00" level=info msg="installing stub qt/gamepad" 
time="2017-04-28T09:35:21+08:00" level=info msg="installing stub qt/purchasing" 
time="2017-04-28T09:35:22+08:00" level=info msg="installing stub qt/datavisualization" 
time="2017-04-28T09:35:22+08:00" level=info msg="installing stub qt/charts" 
time="2017-04-28T09:35:24+08:00" level=info msg="installing stub qt/speech" 
time="2017-04-28T09:35:24+08:00" level=info msg="installing stub qt/quickcontrols2" 
time="2017-04-28T09:35:25+08:00" level=info msg="installing stub qt/sailfish" 
time="2017-04-28T09:35:25+08:00" level=info msg="running: 'qtsetup test windows' [docker=false]" 
time="2017-04-28T09:35:25+08:00" level=info msg="testing widgets\line_edits" 
time="2017-04-28T09:35:57+08:00" level=error msg="failed to run command" cmd="E:\msys64\mingw64\bin\windeployqt E:\GoProject\src\github.com\therecipe\qt\internal\examples\widgets\line_edits\deploy\windows\line_edits.exe -qmldir=E:\GoProject\src\github.com\therecipe\qt\internal\examples\widgets\line_edits -force" env= error="exit status 1" func=RunCmd name="depoy windows on windows" 
E:\GoProject\src\github.com\therecipe\qt\internal\examples\widgets\line_edits\deploy\windows\line_edits.exe 64 bit, release executable
Direct dependencies: Qt5Core Qt5Gui Qt5Widgets
All dependencies   : Qt5Core Qt5Gui Qt5Widgets
To be deployed     : Qt5Core Qt5Gui Qt5Widgets
Unable to find the platform plugin.

exit status 1

Process finished with exit code 1

**Comment by therecipe** [comment]
Hey

Sorry, don't know how this issue slipped though.
I will look into it.
