### ISSUE TITLE
qtsetup test android: Gradle version 2.2 is required. Current version is 2.14.1

### ISSUE THREAD

**Issue by 3togo** [therecipe/qt#303]
Below are the errors。
I guess there might be some wrong with the project settings. But where is it ?

Joe
______________________________________________________
Updating Android package files with project settings.
  -- res/values/libs.xml
  -- AndroidManifest.xml 
Pregenerating entry list for assets file engine.
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/home/marvel/.go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/deploy/android/build/build.gradle'.
Included projects: [root project 'build']
Evaluating root project 'build' using build file '/home/marvel/.go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/deploy/android/build/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/marvel/.go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/deploy/android/build/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating root project 'build'.
> Failed to apply plugin [id 'com.android.application']
   > Gradle version 2.2 is required. Current version is 2.14.1. If using the gradle wrapper, try editing the distributionUrl in /home/marvel/.go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/deploy/android/build/gradle/wrapper/gradle-wrapper.properties to gradle-2.2-all.zip

**Comment by therecipe** [comment]
Hey

I think you need to create the `gradle-wrapper.properties` file in `your_project_root/android/gradle/wrapper`:

```
.
├── android
│   └── gradle
│       └── wrapper
│           └── gradle-wrapper.properties
├── main.go
└── qml
    └── main.qml
```

The `gradle-wrapper.properties` file should contain something like this:

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
```

or this (with the `gradle-2.2-all.zip`):

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.2-all.zip
```

**Comment by 3togo** [comment]
many thanks
I fixed the problem by editing "$ANDROID_SDK_DIR/tools/templates/gradle/wrapper/gradle/wrapper/gradle-wrapper.properties"
>cat $ANDROID_SDK_DIR/tools/templates/gradle/wrapper/gradle/wrapper/gradle-wrapper.properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.2-all.zip

**Comment by therecipe** [comment]
ah, yes overriding the default template should do the trick as well :)

**Comment by 3togo** [comment]
I got a new problems

FAILURE: Build failed with an exception.
I guess I need to change 25.0.2 to 25.0.3
But where?

Joe

____________________________________________________

* What went wrong:
A problem occurred configuring root project 'build'.
> failed to find Build Tools revision 25.0.2

**Comment by therecipe** [comment]
>But where?

It's here: https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/assets.go#L77

Didn't know that 25.0.3 was already available, I will fix that.

**Comment by 3togo** [comment]
I can't find this file in $GOPATH. So what should I do then?

**Comment by therecipe** [comment]
Did you looked in `$GOPATH/src/github.com/therecipe/qt/internal/cmd/deploy` ?

**Comment by 3togo** [comment]
problems fixed.
One last minor question.  How can I skip the "install debug app" step?

____________________________________________________________________________
DEBU[0031] Execute                                       cmd="/home/marvel/Android/Sdk/platform-tools/adb install -r /home/marvel/.go/src/github.com/therecipe/qt/internal/examples/qml/application/deploy/android/build-debug.apk" env= func=RunCmdOptionael name="install debug app"

**Comment by therecipe** [comment]
>problems fixed.

Great :)

>One last minor question. How can I skip the "install debug app" step?

You can use `qtdeploy build android ...` instead of `qtdeploy test android ...`

**Comment by 3togo** [comment]
Many thanks
Have a nice day.
