### ISSUE TITLE
QTableWidget Repaint

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#308]
Hi,

I update items in table and they are not repainted. If I move the window off the screen and bring it back or scroll down or highlight the item, it is repainted. Calling repaint directly does not do anything.

**Comment by 5k3105** [comment]
stv.Viewport().Repaint()

fixes it.

from: http://stackoverflow.com/questions/2274512/update-or-repaint-fails-to-trigger-paintevent

**Comment by therecipe** [comment]
Hey

Thanks for reporting :)
