### ISSUE TITLE
QPaintDevice::metrics: Device has no metric information

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#309]
```go
func main() {
	app := widgets.NewQApplication(len(os.Args), os.Args)

	window := widgets.NewQMainWindow(nil, 0)
	window.Show()

	// renderer := svg.NewQSvgRenderer2("<absolute-path-to-an-svg-file>", nil)
	image := gui.NewQImage3(256, 256, gui.QImage__Format_ARGB32)
	image.Fill(0x00A08080)
	painter := gui.NewQPainter()
	painter.Begin(image)
	// renderer.Render(painter)
	// painter.End()

	widgets.QApplication_Exec()
}
```

> QPaintDevice::metrics: Device has no metric information
> Unrecognised metric 2!

The resulting image is not usable. It has no width or height.

And I encounter the same sort of metrics messages when attempting to create an image from raw data, with some thing like this. 
```
	image := gui.NewQImage()
	image.LoadFromData(string(body), len(body), "")
```

**Comment by therecipe** [comment]
Hey

I will look into it.

But for now you can get it working if you make use of qtminimal like this:
`qtminimal && go build -tags=minimal ...`

Or you could use `qtdeploy -fast ...`

**Comment by pekim** [comment]
I've been using `qtdeploy -fast build desktop`, and I've just tried `qtminimal && go build -tags=minimal`. Unfortunately neither approach helps.

**Comment by therecipe** [comment]
Sorry, I meant `qtdeploy ...` without the `fast` flag.

This works for me currently:

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	image := gui.NewQImage3(256, 256, gui.QImage__Format_ARGB32)
	image.Fill3(core.Qt__blue)
	painter := gui.NewQPainter()
	painter.Begin(image)
	painter.SetPen2(gui.NewQColor2(core.Qt__darkBlue))
	painter.DrawLine3(0, image.Height()/2, image.Width(), image.Height()/2)
	painter.End()

	label := widgets.NewQLabel(nil, 0)
	label.SetPixmap(gui.QPixmap_FromImage(image, 0))
	label.Show()

	widgets.QApplication_Exec()
}
```

with `qtminimal && go build -tags=minimal -o=test && ./test` or `qtdeploy`

on macOS with Qt 5.8 ("official" version) + Go 1.8.1

**Comment by pekim** [comment]
`qtdeploy -fast build desktop && deploy/linux/mixlac-qt-go-2`
exhibits the problem

`qtminimal && go build -tags=minimal -o=test && ./test`
is fine
I'm not sure what I was doing wrong when I tried that earlier. Sorry for the confusion.
I can work with this for now, but it's slower than `qtdeploy -fast`.

**Comment by pekim** [comment]
Strangely the `QPaintDevice::metrics: Device has no metric information` and `Unrecognised metric 1!` messages do not _seem_ have any impact on functionality. At least I don't think that they do. I will continue to watch out for any effects.

They did confuse me though.

**Comment by therecipe** [comment]
Ah, great to hear that the workaround works for you :)

>messages do not seem have any impact on functionality.

Yeah, I think there is a great chance that most functions work as usual.

Nevertheless I will try to fix it tomorrow.

**Comment by therecipe** [comment]
Should be fixed now with: https://github.com/therecipe/qt/commit/d9ade1b5beee37c2907c6fc62e68952144e2f0e1

**Comment by pekim** [comment]
Yes, that's better. Thank you.
