### ISSUE TITLE
Docker: Logrus precompiled binary in build

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#311]
In docker `/home/user/work/pkg/linux_amd64/github.com/Sirupsen/logrus.a` is there. which might not be the same version as the user of docker image might want.

is logrus used only in `github.com/therecipe/qt/internal`?

if yes, both internal and logrus should be removed from the binary there.

**Comment by therecipe** [comment]
Hey

>is logrus used only in github.com/therecipe/qt/internal?

yes, only the tooling makes use of logrus.
the binding code has no external (go) dependencies.

>if yes, both internal and logrus should be removed from the binary there.

yeah, you are right.
the deps should be removed now (from the final image(s)) with: https://github.com/therecipe/qt/commit/bad753a26690dd8e1ed9e4f1f434eb9bf3d210a1
