### ISSUE TITLE
Any support for tray applications yet?

### ISSUE THREAD

**Issue by rucuriousyet** [therecipe/qt#315]

**Comment by therecipe** [comment]
Hey

Yes, you can find a small example here: https://github.com/therecipe/qt/tree/master/internal/examples/widgets/systray

**Comment by sisyphsu** [comment]
@therecipe The example can't run, lots of compile error.

**Comment by therecipe** [comment]
@sisyphsu Did you run the setup first?

**Comment by sisyphsu** [comment]
@therecipe I resolved it yet, use `qtmoc` command, thanks~

**Comment by RadhiFadlillah** [comment]
Closed since it's old and has been solved.
