### ISSUE TITLE
qtdeploy fails with "failed to remove deploy folder". Regression bug ?

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#316]
````
x-MacBook-Pro:webview apple$ qtdeploy build desktop
PANI[0000] failed to remove deploy folder                error="remove /Users/apple/workspace/go/src/github.com/therecipe/qt/internal/examples/qml/webview/deploy/darwin: directory not empty"
panic: (*logrus.Entry) (0x13265a0,0xc42001ab90)

````

On OSX
Did not get this bug before, so seems to be a regression.

**Comment by therecipe** [comment]
Mh, could it be that you still had the `webview.app` running in the background?
I will look into it, but I suspect that it was just back luck, because there was some application or file still open in `./deploy/darwin`

**Comment by inondle** [comment]
This happens to me as well on windows 10. I'm trying to build a Qt quick app, after running `qtdeploy test desktop` it spawns a new process but the process doesn't show anything on the screen. To work around this I just killed the new process.

**Comment by therecipe** [comment]
@inondle 
Yeah, it can happen under some circumstances that the applications keeps running in the background without any visible window. But this should only happen if there was an error in you QML code or maybe you forgot to make the windows visible.

You could try to check for errors, before the main even loop takes over with `*_Exec()`.
To do this for the QQuickWindow for example, you can simply use the `Errors()` function.

**Comment by joeblew99** [comment]
Oh I get now window often when I screw up my qml or qml binding.
Can you write a basic example here or put it in one of the internal examples ?
I was planning to address this and logging and crashed in general.
So if I can see the scaffolding in an example I can extend it and wire it up to one of the hosted logging and crashed reporters. I use stackdriver for all these sort of ops things.
Pretty useful too because it will summarise that devices have what issues so I can get to the bottom of unusual bugs

**Comment by therecipe** [comment]
I added an example for the QQuickView here: https://github.com/therecipe/qt/tree/master/internal/examples/quick/errors

Looked in QQmlApplicationEngine as well, but that requieres http://doc.qt.io/qt-5/qtglobal.html#qInstallMessageHandler which is currently not supported.
But I will look into that as well.

**Comment by joeblew99** [comment]
I tried the example but did not really help me.
Maybe i am invoking it incorrectly Or maybe its just not possible in all practicality.


```

# Gives no feedback
#qtdeploy build

# Gives no feedback
qtdeploy -fast build

# Gives no feedback
#qtrcc && qtmoc && qtminimal && go build

# Gives feedback telling me what line has an error, but not what the error is.
#qmlscene main.qml

```

**Comment by therecipe** [comment]
Ah, sorry I probably didn't understood you correctly :D

The example I wrote just exits upon an error: https://github.com/therecipe/qt/blob/master/internal/examples/quick/errors/main.go#L32-L37
But you could get additional infos about the error there as well first, and log them if you like.

The qt* tools only give feedback, if there something went wrong during the build/deploy process.
But they don't check if your qml files have errors. You could use qmllint for that as well.

**Comment by joeblew99** [comment]
closing .. Was my fault with a locked process :)
