### ISSUE TITLE
Project ERROR: Could not resolve SDK Path for 'macosx'

### ISSUE THREAD

**Issue by medvednikov** [therecipe/qt#327]
Hi,

I'm trying to install it on macOS. I've tried with both brew qt5 and qt's official installer.

```
ERRO[0010] failed to run command cmd="/Users/alex/Qt5.8.0/5.8/clang_64/bin/qmake Users/alex/src/github.com/therecipe/qt/core.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=release" env= error="exit status 3" func=RunCmdOptional name="run qmake for darwin on darwin"

Project ERROR: Could not resolve SDK Path for 'macosx'
```

```
go version go1.8.1 darwin/amd64
```

I've followed all the instructions.

This may also be useful:

```
INFO[0000] running: 'qtsetup prep'
INFO[0000] successfully created qtrcc symlink in your PATH (/usr/local/bin/qtrcc)
INFO[0000] successfully created qtmoc symlink in your PATH (/usr/local/bin/qtmoc)
INFO[0000] successfully created qtminimal symlink in your PATH (/usr/local/bin/qtminimal)
INFO[0000] successfully created qtdeploy symlink in your PATH (/usr/local/bin/qtdeploy)
INFO[0000] running: 'qtsetup check darwin' [docker=false]
INFO[0000] GOOS:                        'darwin'
INFO[0000] GOARCH:                      'amd64'
INFO[0000] GOVERSION:                   'go1.8.1'
INFO[0000] GOROOT:                   *  '/Users/alex/go/'
INFO[0000] GOPATH:                   *  '/Users/alex/'
INFO[0000] GOBIN:                       '/Users/alex/bin'
INFO[0000] QT_HASH:                     'bb6259c35dc7eb6907d01510eea6cfca5b1af3d2'
INFO[0000] QT_VERSION:                  '5.8.0'
INFO[0000] QT_VERSION_MAJOR:            '5.8'
INFO[0000] QT_DIR:                      '/Users/alex/Qt5.8.0'
INFO[0000] QT_STUB:                     'false'
INFO[0000] QT_DEBUG:                    'false'
INFO[0000] QT_QMAKE_DIR:                ''
INFO[0000] QT_WEBKIT:                   'false'
INFO[0000] QT_HOMEBREW:                 'false'
INFO[0000] XCODE_DIR:                   '/Applications/Xcode.app'
INFO[0000] running: 'qtsetup generate darwin' [docker=false]
```

Thanks

**Comment by therecipe** [comment]
Hey

Thanks for the infos :)

You are probably on an older macOS version or? With some older Xcode version? 7.x or something?

I found a few post that are probably related to your issue:

http://community.mrtrix.org/t/setup-error/673/2
(This one suggests that you probably need to start Xcode once)

https://bugreports.qt.io/browse/QTCREATORBUG-17494

https://stackoverflow.com/questions/44015079/project-error-could-not-resolve-sdk-path-for-macosx
https://stackoverflow.com/questions/26320677/error-could-not-resolve-sdk-path-for-macosx10-8
https://stackoverflow.com/questions/32642109/could-not-resolve-sdk-path-for-macosx10-10

**Comment by medvednikov** [comment]
Sorry, forgot to mention. 10.12 Sierra, Xcode 8.

I'll try that, thanks.

**Comment by therecipe** [comment]
Mh, then it should work.
Maybe you really only need to start Xcode once to install the command line tools.

Or maybe try to run: `xcode-select --install` that will tell you if you need to install the tools, or if they are already installed.

**Comment by medvednikov** [comment]
Ok, that was an easy fix

https://stackoverflow.com/questions/41513456/qt-5-7-xcode-8-1-os-x-el-captain-could-not-resolve-sdk-path-for-macosx

Xcode's -> Preferences -> Locations -> Command Line Tools -> select SDK

Thanks :)

**Comment by therecipe** [comment]
Great, thanks for letting me know :)
