### ISSUE TITLE
g++: error: unrecognized command line option ‘-marm’

### ISSUE THREAD

**Issue by minhajakhterkhan199** [therecipe/qt#328]
When cross compiling project, I am getting below error. Please advise to solve the issue
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
g++: error: unrecognized command line option ‘-marm’
-----------------------------------------------------------------

Please find below my go environment variables setup
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/minhaj/GoLang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOARM=""
CC="arm-linux-gnueabi-gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build277718108=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2" 

----------------------------------------------------
With amd64 everything is working good.....

**Comment by nanu-c** [comment]
You have to set the CXX="arm-linux-gnueabi-cpp-7" to the right compiler

**Comment by therecipe** [comment]
Closing as it's a dup of https://github.com/therecipe/qt/issues/329
