### ISSUE TITLE
Chrome OS testing

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#330]
Google announced a chrome OS emulator last week. 
So it will make it much easier to test QT android apps on chrome OS :)

You have to sign up for now:

https://www.google.de/amp/s/9to5google.com/2017/05/19/google-chromebook-emulator/amp/

**Comment by therecipe** [comment]
Hey

That's great, thanks for letting me know :)
I will try to get into the beta, to test it.

**Comment by joeblew99** [comment]
will close for now then...
