### ISSUE TITLE
Unable to setup using qtsetup

### ISSUE THREAD

**Issue by dinesh-chander** [therecipe/qt#331]
When I ran qtsetup, i got
```
failed to run command :  cmd="go install -p 4 -v github.com/therecipe/qt/webkit" env= error="exit status 2" func=RunCmdOptionalError name="install webkit"

error: use of undeclared identifier 'callbackQWebPluginFactory_Plugins'; did you mean 'callbackQWebPluginFactory_RefreshPlugins'?
```

I'm using 
```
macosx@10.12.5 (sierra)
qt@5.8.0_2 using homebrew with --with-qtwebkit option
Xcode@8.3.2
```

**Comment by dinesh-chander** [comment]
When I tried official Qt version it worked. There might be something missing in the homebrew Qt installation.

**Comment by therecipe** [comment]
Hey

I tried to reproduce your issue and yes it seems like there are some things missing in the homebrew version. But I did built Qt today with `--with-qtwebkit` and it worked.

**Comment by dinesh-chander** [comment]
Did you use homebrew when you built Qt with `--with-qtwebkit`?

**Comment by therecipe** [comment]
Yeah, I just ran `brew install qt --with-qtwebkit` iirc, and it worked.

Also I broke it yesterday, but it's fixed again with: https://github.com/therecipe/qt/commit/bdd7427f145a21e7b52ed688d8d02b52586235a4

Here are the hashes for the generated files (in: `github.com/therecipe/qt/webkit`)
```
SHA(webkit.cpp)= ddcb002d84c55f5203e4f3c44d1bf7d56df5ad51
SHA(webkit.go)= 44df2b4152889e4c3bf19c25e081292b18bdf46d
SHA(webkit.h)= b38ce9cef09b73e2a111596fe9f0b28b7e5e3dca
```

I'm on the same macOS and Xcode version as you and used only these env variables:
```
QT_WEBKIT=true
QT_HOMEBREW=true
```

Could you maybe try to update the binding and then re-run the setup?
Running `./qtsetup upgrade && ./qtsetup` should be enough

And maybe if you don't mind upload the diff somewhere, so I can take a look?
