### ISSUE TITLE
How to use Qt5 modules like QtAV

### ISSUE THREAD

**Issue by RadhiFadlillah** [therecipe/qt#332]
As title says, is it possible to use QtAV modules with this package ?

**Comment by therecipe** [comment]
Hey

Maybe, I will look into it.

**Comment by therecipe** [comment]
I tried to get QtAV installed on macOS, but didn't really succeeded to build the examples afterwards.
Will try it on linux again when I got more time.

However, it should be possible to use at least the QML api like you would do normally.
