### ISSUE TITLE
Embedding core.QAbstractListModel results in build failure

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#334]
It appears that including this
```go
import "github.com/therecipe/qt/core"

type ConversationsModel struct {
	core.QAbstractListModel
}
```
results in a build error like this
```
In file included from /home/mike/Qt/5.8/gcc_64/include/QtQml/qqml.h:43:0,
                 from /home/mike/Qt/5.8/gcc_64/include/QtQuick/qquickitem.h:44,
                 from /home/mike/Qt/5.8/gcc_64/include/QtQuick/QQuickItem:1,
                 from ui/moc.cpp:66:
/home/mike/Qt/5.8/gcc_64/include/QtQml/qqmlprivate.h: In instantiation of ‘void QQmlPrivate::createInto(void*) [with T = Application]’:
/home/mike/Qt/5.8/gcc_64/include/QtQml/qqml.h:270:5:   required from ‘int qmlRegisterType(const char*, int, int, const char*) [with T = Application]’
ui/moc.cpp:2445:128:   required from here
/home/mike/Qt/5.8/gcc_64/include/QtQml/qqmlprivate.h:108:37: error: use of deleted function ‘QQmlPrivate::QQmlElement<Application>::QQmlElement()’
     void createInto(void *memory) { new (memory) QQmlElement<T>; }
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mike/Qt/5.8/gcc_64/include/QtQml/qqmlprivate.h:99:11: note: ‘QQmlPrivate::QQmlElement<Application>::QQmlElement()’ is implicitly deleted because the default definition would be ill-formed:
     class QQmlElement : public T
           ^~~~~~~~~~~
/home/mike/Qt/5.8/gcc_64/include/QtQml/qqmlprivate.h:99:11: error: no matching function for call to ‘Application::Application()’
ui/moc.cpp:531:2: note: candidate: Application::Application(int&, char**)
  Application(int &argc, char **argv) : QApplication(argc, argv) {};
  ^~~~~~~~~~~
ui/moc.cpp:531:2: note:   candidate expects 2 arguments, 0 provided
```

**Comment by pekim** [comment]
Of course soon after I created this issue, I realise that QAbstractListModel appears to be QML related. I shall go and read about Qt model classes again.

**Comment by pekim** [comment]
It seems that `NewQStandardItemModel` can do everything that I need.

(Why is it that it doesn't matter how much reading one does before asking a question, the answer often seems to come to light soon after? I guess that raising an issue is a form of rubber ducking.)

**Comment by therecipe** [comment]
>Why is it that it doesn't matter how much reading one does before asking a question, the answer often seems to come to light soon after? I guess that raising an issue is a form of rubber ducking.

Yeah, I think it works pretty similar :)
Maybe even better, because you also need to write everything down.

Btw, I wrote a few examples lately that might be interesting as they show the basic usage of list, table and tree views + widgets.

You can find them here:
https://github.com/therecipe/qt/blob/master/internal/examples/common/widgets/itemViews.go
https://github.com/therecipe/qt/blob/master/internal/examples/common/widgets/itemWidgets.go

**Comment by pekim** [comment]
Thanks for the examples. They are helpful.

However I'm now back to wanting to extend (embed) `QAbstractListModel`, and I have the original problem. Is it not possible?

I can manage without doing it that way, and using simple composition. But it feels slightly messy somehow. It's not how I'm now used to extending other QObject derived classes.

**Comment by pekim** [comment]
And I hit the same problem as soon as I try to subclass `QSortFilterProxyModel`.

```go
type ConversationsModelProxy struct {
	core.QSortFilterProxyModel
	_ func() `constructor:"init"`
}

func (cm *ConversationsModelProxy) init() {
	...
}
```

results in
```
In file included from /home/mike/Qt/5.8/gcc_64/include/QtQml/qqml.h:43:0,
                 from /home/mike/Qt/5.8/gcc_64/include/QtQuick/qquickitem.h:44,
                 from /home/mike/Qt/5.8/gcc_64/include/QtQuick/QQuickItem:1,
                 from ui/moc.cpp:66:
/home/mike/Qt/5.8/gcc_64/include/QtQml/qqmlprivate.h: In instantiation of ‘void QQmlPrivate::createInto(void*) [with T = Application]’:
/home/mike/Qt/5.8/gcc_64/include/QtQml/qqml.h:270:5:   required from ‘int qmlRegisterType(const char*, int, int, const char*) [with T = Application]’
ui/moc.cpp:4079:128:   required from here
/home/mike/Qt/5.8/gcc_64/include/QtQml/qqmlprivate.h:108:37: error: use of deleted function ‘QQmlPrivate::QQmlElement<Application>::QQmlElement()’
     void createInto(void *memory) { new (memory) QQmlElement<T>; }
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mike/Qt/5.8/gcc_64/include/QtQml/qqmlprivate.h:99:11: note: ‘QQmlPrivate::QQmlElement<Application>::QQmlElement()’ is implicitly deleted because the default definition would be ill-formed:
     class QQmlElement : public T
           ^~~~~~~~~~~
/home/mike/Qt/5.8/gcc_64/include/QtQml/qqmlprivate.h:99:11: error: no matching function for call to ‘Application::Application()’
ui/moc.cpp:96:2: note: candidate: Application::Application(int&, char**)
  Application(int &argc, char **argv) : QApplication(argc, argv) {};
  ^~~~~~~~~~~
ui/moc.cpp:96:2: note:   candidate expects 2 arguments, 0 provided
```

**Comment by pekim** [comment]
I'm being dense. I don't _have_ to subclass `QSortFilterProxyModel`. I can simply create an instance and `ConnectSort` and whatever else I need. So I can workaround this too.

However I would still like to subclass these model classes if I can.

**Comment by therecipe** [comment]
Yeah, it should usually be possible to subclass them.

Can you compile this simple example successfully?
```go

package main

import (
	"github.com/therecipe/qt/core"
)

type ConversationsModelProxy struct {
	core.QSortFilterProxyModel
	_ func() `constructor:"init"`
}

func (cm *ConversationsModelProxy) init() {

}

func main() {

}
```
with `qtmoc && go build`

And do you by any chance already subclass `QApplication`, `QGuiApplication` or `QCoreApplication` somewhere in your code? I got a similar error to the one you posted above on macOS, when trying to subclass `QApplication` and `QSortFilterProxyModel`.

**Comment by pekim** [comment]
Yes, your example builds fine.

Yes, I am sublassing QApplication in my application.

This exhibits the problem.
```
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

type Application struct {
	widgets.QApplication
	_ func() `constructor:"init"`
}

func (a *Application) init() {
}

type ConversationsModelProxy struct {
	core.QSortFilterProxyModel
	_ func() `constructor:"init"`
}

func (cm *ConversationsModelProxy) init() {

}

func main() {
	NewApplication(len(os.Args), os.Args)
}
```

**Comment by therecipe** [comment]
Yeah, it should be fixed now with: https://github.com/therecipe/qt/commit/92b770863df951b15635463ad64734fec6987318

The problem was that for every subclassed class, there are also some `qmlRegisterType` helper functions created. And these functions are usually hidden behind a `#ifdef` so that they only get usable if you also import the qml module.

But subclassing `core.QSortFilterProxyModel` or some other model pulls in the qml module and therefore makes the hidden `qmlRegisterType` function visible to the compiler. Which then resulted in the error you posted above, because it's apparently not possible to "qmlRegister" `QCoreApplication` derived classes such as `QApplication`.

It's solved now by omitting the creation of these `qmlRegisterType` functions for `QCoreApplication` derived classes.

**Comment by pekim** [comment]
Yes, that's fixed it. Thank you.
