### ISSUE TITLE
Missing setTabsClosable method in QTabWidget

### ISSUE THREAD

**Issue by RadhiFadlillah** [therecipe/qt#335]
I want to make closable tab and according to [Qt5 documentation](http://doc.qt.io/qt-5/qtabwidget.html#tabsClosable-prop), I can do it using `setTabsClosable`. Unfortunately, it seems this method is not available in this package.

**Comment by therecipe** [comment]
Hey

Yeah, indeed the method is missing.
I will look into it.

**Comment by therecipe** [comment]
These functions should be available now with: https://github.com/therecipe/qt/commit/92b770863df951b15635463ad64734fec6987318

**Comment by RadhiFadlillah** [comment]
Yeah, it works now. Thanks
