### ISSUE TITLE
could not run bundled examples

### ISSUE THREAD

**Issue by Harish1n1ly** [therecipe/qt#339]
Operating System: Windows 10 / 64 bit
Installed therecipe/qt package using regular method explained here: https://github.com/therecipe/qt#tools

> $ go.exe version
go version go1.8.3 windows/amd64

> $ qtdeploy test desktop C:\Go\packages\src\github.com\therecipe\qt\internal\examples\widgets\table\table.go
ERRO[0000] failed to run command                         cmd="go list -e -f '{{ join .TestImports "|" }}':'{{ join .Imports "|" }}' -tags=""" env="CGO_ENABLED=1 PATH=C:\Windows;C:\Windows\System32;C:\Go\bin;C:\Go\packages\bin;C:\Qt\Qt5.8.0\Tools\mingw530_32\bin GOPATH=C:\Go\packages TMP=C:\Users\Administrator\AppData\Local\Temp TEMP=C:\Users\Administrator\AppData\Local\Temp GOARCH=386 GOROOT=C:\Go\ GOOS=windows" error="fork/exec C:\Go\bin\go.exe: The directory name is invalid." func=RunCmd name="go list deps"

Am I doing something wrong?

**Comment by therecipe** [comment]
Hey

Could you try running
```
qtdeploy test desktop C:\Go\packages\src\github.com\therecipe\qt\internal\examples\widgets\table
```
instead ?

The last argument should be the relative or absolute path to your project dir.

**Comment by Harish1n1ly** [comment]
The command fails with following error:

> \# github.com/therecipe/qt/internal/examples/widgets/table
.\table.go:99: undefined: NewDelegate

Am I missing something?

**Comment by therecipe** [comment]
Did qtdeploy create the `moc*` or `rcc*` in the project dir?

You probably will also need to go get `github.com/emirpasic/gods/lists/arraylist` first, before running qtdeploy. If you haven't already.

**Comment by Harish1n1ly** [comment]
3 `rcc*` files got created under `table` directory

```
rcc.cpp
rcc.qrc
rcc_cgo_windows_windows_386.go
```

There were other warning messages when running `qtdeploy test build` : [full_output](https://github.com/therecipe/qt/files/1050499/output.txt)

`github.com/emirpasic/gods/lists/arraylist` package is already present

**Comment by therecipe** [comment]
Okay, could you then try to run `qtmoc -debug` inside the dir to see if the `moc*` files are beeing created?

**Comment by Harish1n1ly** [comment]
Ran the command but no `moc*` files created : 
[full_output.txt](https://github.com/therecipe/qt/files/1050534/output.txt)

**Comment by therecipe** [comment]
Did you modify the Delegate struct?

```go
type Delegate struct {
	widgets.QStyledItemDelegate
}
```

**Comment by Harish1n1ly** [comment]
I did not change the code. I just tried to run few examples after installing `therecipe/qt` package. I am getting similar error for `textedit` example also
```
# github.com/therecipe/qt/internal/examples/widgets/textedit
.\textedit.go:55: undefined: NewTextEdit
```
Thanks

**Comment by therecipe** [comment]
Yeah, that's probably the same issue, as `NewTextEdit` should have been created by qtmoc as well.
The other examples that don't depend on qtmoc should work though, maybe try the `widgets/line_edits` example.

I'm currently setting up a fresh win 10 vm and will try to reproduce it.

**Comment by therecipe** [comment]
Okay, I just tested it on Win 10 x64 (Version: 1703) with Go 1.8.3 + Qt 5.8.0 and it worked.

Do you use the latest version of the binding?
And could you maybe run qtmoc in `github.com/therecipe/qt/internal/cmd/moc/test`?

**Comment by Harish1n1ly** [comment]
Output of `qtmoc -debug desktop github.com/therecipe/qt/internal/cmd/moc/test` : [output.txt](https://github.com/therecipe/qt/files/1053673/output.txt)

Yes. `widgets/line_edits` and `widgets/video_player` works. But other examples `widgets/treeview` and `widgets/webengine` fails with error : `no buildable Go source files`

I removed the entire Qt and Go installation and reinstalled them. Still no luck.

**Comment by Harish1n1ly** [comment]
@therecipe Is there anything else I can do to debug the problem?

**Comment by therecipe** [comment]
Sorry, I was a bit busy.

I just looked into the function that is probably failing and I think that the issue could be that your GOPATH is located in your GOROOT: https://github.com/therecipe/qt/blob/master/internal/cmd/moc/moc.go#L245-L247

```
GOPATH=C:\Go\packages GOROOT=C:\Go\
```

So you will probably need to move your GOPATH out of your GOROOT for this to work.

Or maybe try to change it to
```go
	if strings.HasPrefix(path, filepath.Join(runtime.GOROOT(), "src")) {
		return nil, "", nil
	}
```

and let me know if this fixes it for you.

**Comment by Harish1n1ly** [comment]
It is working after moving GOPATH and running qtsetup again. Thanks. Keep up the good work.

**Comment by therecipe** [comment]
Awesome :)
