### ISSUE TITLE
Key press event not triggered 

### ISSUE THREAD

**Issue by dzhou121** [therecipe/qt#345]
Hi, I need help on the key press events, it doesn't do anything for me for the following code:

```
package main

import (
	"fmt"

	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func keyPress(event *gui.QKeyEvent) {
	fmt.Println(event)
}

func main() {
	widgets.NewQApplication(0, nil)
	window := widgets.NewQMainWindow(nil, 0)
	window.SetWindowTitle("Hello World Example")
	widget := widgets.NewQWidget(nil, 0)
	widget.ConnectKeyPressEvent(keyPress)
	window.SetCentralWidget(widget)
	window.Show()
	widgets.QApplication_Exec()
}
```

**Comment by therecipe** [comment]
Hey

You need to set a focus policy first, otherwise the widget won't process keyboard or mouse events: http://doc.qt.io/qt-5/qwidget.html#focusPolicy-prop

Something like this should work: `widget.SetFocusPolicy(core.Qt__StrongFocus)`

**Comment by dzhou121** [comment]
It works. Thanks for your help.
