### ISSUE TITLE
Porting c++ code to golang QT

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#347]
I am trying to port this:
https://github.com/shi-yan/Pillow

It uses QT.
What i am confused about is the reference to openGL.
https://github.com/shi-yan/Pillow/blob/master/View/SplitedView.h
Can you make direct calls to openGL in QT ?

**Comment by therecipe** [comment]
Hey

Yes, I think you can make OpenGL calls: https://stackoverflow.com/questions/15671816/opengl-vs-qopengl-qtopengl-in-qt-5-differences-and-limitations

But from a quick glance it seems like the project you are porting just embeds a normal OpenGL view/canvas inside the QWindow and uses the regular c OpenGL api for the calls.

So you probably need to either write the OpenGL code in c as well or maybe make use of a go binding: https://github.com/go-gl

Another option would be to use QML + https://doc.qt.io/qt-5/qt3d-index.html, but I don't know if it's feasible for what you are planning to do.

Also btw, I think I needed to blacklist a few OpenGL related function but if you need some of them then just let me know and I will look into it.

**Comment by joeblew99** [comment]
Thank for the review.
Ah that makes sense , but was not sure.

Yes I also looked at the go-gl option.
There are golang 3d libs / examples for OpenGL and Vulkan now that run on desktop and mobile.
For osx and iOS you must buy a Vulkan to metal license for 159 USD per user. Yikes !

But Qt will be supporting Vulkan too. I think they of course are wrapping Vulkan / Metal API differences for you.

So with QT I can program to the QT API and it will run it as OpenGL or Vulkan depending on what's on the end user machine. I read it's not compile time dependent even, but not 100% sure yet.

So logically path is to stick with QT I feel when you weigh it all up.
Will mean more work but seems right path.

Will try to get as far as I can

**Comment by therecipe** [comment]
>So logically path is to stick with QT I feel when you weigh it all up.
Will mean more work but seems right path.

Yeah, you are right sticking to Qt is probably the best option.
I also recall reading that they got some nice 3D stuff from Nvidia lately.
So there is probably more stuff to see from that in 5.10 or so.
