### ISSUE TITLE
undefined: ssh.InsecureIgnoreHostKey

### ISSUE THREAD

**Issue by ChrisFernandez** [therecipe/qt#349]
Hello im following the dockersetup in your readme. but getting this error on the clone step

```
go get -v github.com/therecipe/qt/cmd/...
github.com/therecipe/qt/internal/cmd/deploy
# github.com/therecipe/qt/internal/cmd/deploy
src/github.com/therecipe/qt/internal/cmd/deploy/assets.go:687: undefined: ssh.InsecureIgnoreHostKey
```

**Comment by therecipe** [comment]
Hey

You probably just need to update `golang.org/x/crypto/ssh` first.

**Comment by ChrisFernandez** [comment]
@therecipe Hello I tried to "go get" and later did:
```
go test golang.org/x/crypto/ssh
ok      golang.org/x/crypto/ssh 0.381s
```
still not luck :/

**Comment by therecipe** [comment]
Could you try to run: `go get -u -v golang.org/x/crypto/...` ?
This should update the `crypto` package and all the sub packages.

**Comment by ChrisFernandez** [comment]
@therecipe ok I think work
```
go get -v github.com/therecipe/qt/cmd/...
github.com/therecipe/qt/internal/cmd/deploy
github.com/therecipe/qt/cmd/qtdeploy
github.com/therecipe/qt/internal/cmd/setup
github.com/therecipe/qt/cmd/qtsetup
```

Thanks!

**Comment by ignusius** [comment]
@therecipe I've updated crypto, but this error show too. :(

> go get -v github.com/therecipe/qt/cmd/...
> github.com/therecipe/qt (download)
> github.com/therecipe/qt/internal/utils
> github.com/therecipe/qt/internal/binding/parser
> github.com/therecipe/qt/internal/cmd
> github.com/therecipe/qt/internal/binding/converter
> github.com/therecipe/qt/internal/binding/templater
> github.com/therecipe/qt/internal/cmd/minimal
> github.com/therecipe/qt/internal/cmd/moc
> github.com/therecipe/qt/internal/cmd/rcc
> github.com/therecipe/qt/cmd/qtrcc
> github.com/therecipe/qt/cmd/qtminimal
> github.com/therecipe/qt/internal/cmd/deploy
> github.com/therecipe/qt/cmd/qtmoc
> # github.com/therecipe/qt/internal/cmd/deploy
> go/src/github.com/therecipe/qt/internal/cmd/deploy/assets.go:689: undefined: ssh.InsecureIgnoreHostKey
>

**Comment by therecipe** [comment]
@ignusius maybe try to run:
```
go clean -i golang.org/x/crypto/...  && go get -u -v golang.org/x/crypto/... && go get -u -v github.com/therecipe/qt/cmd/...
```
