### ISSUE TITLE
QtWebkit (Win7, Go1.7.5): The application was unable to start correctly (0x000007b)

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#350]
I have not tested webkit in about a month. Not sure when this stopped working.

**Comment by therecipe** [comment]
Hey

I will look into it.

**Comment by therecipe** [comment]
I fixed a minor bug in: https://github.com/therecipe/qt/commit/9127474fe466369177aeef9e78ca8c547411eedc that was probably related to this.

This example:
```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/webkit"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	view := webkit.NewQWebView(nil)
	view.Load(core.NewQUrl3("http://www.google.com/", 0))
	view.Show()

	widgets.QApplication_Exec()
}
```

Should work again with Qt 5.8 and `qtwebkit-tp5-qt58-mingw530-x86.zip`

**Comment by 5k3105** [comment]
Thanks I'll try it out!

**Comment by 5k3105** [comment]
Worked great! Thanks!
