### ISSUE TITLE
MXE can't be installed on Ubuntu

### ISSUE THREAD

**Issue by medvednikov** [therecipe/qt#353]
Hi,

I'm trying to cross compile my app to Windows on Ubuntu.

I followed these instructions: https://github.com/therecipe/qt#linux

I'm getting the following error when trying to install MXE:

```
The repository 'https://pkg.mxe.cc/repos/apt/debian jessie Release' does not have a Release file.
Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
See apt-secure(8) manpage for repository creation and user configuration details.
Failed to fetch https://pkg.mxe.cc/repos/apt/debian/dists/jessie/main/binary-amd64/Packages  SSL: certificate subject name (thechess.ru) does not match target host name 'pkg.mxe.cc'
```

Thanks

**Comment by therecipe** [comment]
Hey

Could be that the jessie packages (and the docs) are deprecated now.
Maybe try to follow the official MXE docs instead: http://pkg.mxe.cc/

I will look into it and update the docs if necessary.

**Comment by hello-code** [comment]
Change **https** to **http** solved my issue.
`deb http://pkg.mxe.cc/repos/apt/debian jessie main`
