### ISSUE TITLE
build examples failed on mac

### ISSUE THREAD

**Issue by shalaby** [therecipe/qt#356]
ERRO[0100] failed to run command                         cmd="go build -p 8 -v -ldflags="-w" "-r=/Users/medo/Qt5.8.0/5.8/clang_64/lib" -o /Users/medo/gocode/src/github.com/shalaby/election-server/deploy/darwin/election-server.app/Contents/MacOS/election-server -tags="minimal"" env= error="exit status 2" func=RunCmd name="build for darwin on darwin"

**Comment by therecipe** [comment]
Hey

Could you maybe provide a longer log?

**Comment by shalaby** [comment]
@therecipe Appreciate ur amazing work and quick response, please keep going :)
regarding the issue it was something I missed, so sorry to bother u.
