### ISSUE TITLE
Need help with Cookies

### ISSUE THREAD

**Issue by pvitaliy84** [therecipe/qt#359]
Hello. Sorry for my  bad English. I don't understand how get all cookies from QML WebEngineView...

**Comment by therecipe** [comment]
Hey

I added a new example here: https://github.com/therecipe/qt/tree/master/internal/examples/quick/cookies

You need to send the profile used by the webengine back to Go and then connect the "cookieAdded" signal. After that you will get notified every time there is a new cookie added, or an old one updated.

Just click on the button in the example and then scroll the site up and down.

```
|
|  QML
|  http://doc.qt.io/qt-5/qml-qtwebengine-webengineview.html
|
|  http://doc.qt.io/qt-5/qml-qtwebengine-webengineprofile.html
|  ----------------------------------------------------------------
|                       |sendProfile(*Profile)|
|  ----------------------------------------------------------------
|  Go 
|  https://doc.qt.io/qt-5/qquickwebengineprofile.html
|
|  https://doc.qt.io/qt-5/qwebenginecookiestore.html
V
```
