### ISSUE TITLE
Is QOpenGLWidget supported? 

### ISSUE THREAD

**Issue by dzhou121** [therecipe/qt#362]
Hi, I can see NewQOpenGLWidgetFromPointer, but is QOpenGLWidget supported?

**Comment by therecipe** [comment]
Hey

Unfortunately no, not yet.
But I will look into it.

**Comment by dzhou121** [comment]
Thanks

**Comment by therecipe** [comment]
QOpenGLWidget is supported since a while https://github.com/therecipe/qt/tree/master/internal/examples/opengl
so I will close this now
