### ISSUE TITLE
Info.plist for macOS deployments

### ISSUE THREAD

**Issue by dzhou121** [therecipe/qt#363]
Hi,

Is there any reason 

```
<key>CFBundleName</key>
<string>%[1]v</string>
```
was removed in 735736102d91565712c2866ec89009a09d8f3945

The "Hide" menu doesn't include the app name.

**Comment by therecipe** [comment]
Hey

No there was no special reason, I just updated the plist to the standard template from Qt 5.9.
It's re-added now with: https://github.com/therecipe/qt/commit/2e6a226ed9ba29b4562330ac4f648d4b67f12e26

**Comment by dzhou121** [comment]
Thanks
