### ISSUE TITLE
Segfault occasionally when doing QWidget Move2

### ISSUE THREAD

**Issue by dzhou121** [therecipe/qt#364]
Part of the segfault below. I've set ```GOTRACEBACK=crash```and the core dump is generated but it's just empty. Happens on both macOS and Linux. How can I debug it? Thanks. 

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f44d02090cc pc=0x7f4804aad99b]

runtime stack:
runtime.throw(0xa00cd6, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 4 [syscall, locked to thread]:
runtime.cgocall(0x8b61d0, 0xc42005b878, 0xa00371)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc42005b838 sp=0xc42005b7f8
github.com/therecipe/qt/widgets._Cfunc_QWidget_Move2(0x28d6010, 0x2f00000000)
	github.com/therecipe/qt/widgets/_obj/_cgo_gotypes.go:11598 +0x45 fp=0xc42005b878 sp=0xc42005b838
github.com/therecipe/qt/widgets.(*QWidget).Move2.func1(0x28d6010, 0x2f00000000)
	/home/user/work/src/github.com/therecipe/qt/widgets/widgets-minimal.go:11623 +0x70 fp=0xc42005b8b0 sp=0xc42005b878
github.com/therecipe/qt/widgets.(*QWidget).Move2(0xc4201505a0, 0x0, 0x2f)
	/home/user/work/src/github.com/therecipe/qt/widgets/widgets-minimal.go:11623 +0x56 fp=0xc42005b8d0 sp=0xc42005b8b0
github.com/dzhou121/gonvim.(*PopupMenu).scroll(0xc42006ad00, 0xffffffffffffffff)
	/media/sf_GOPATH0/src/github.com/dzhou121/gonvim/popupmenu.go:192 +0x163 fp=0xc42005b930 sp=0xc42005b8d0
```

**Comment by dzhou121** [comment]
Also I occasionally got this error:

```
gonvim(24680,0x7ffff2f343c0) malloc: *** error for object 0x2a26ef10: double free
*** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fffea148d42 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4ffb5f0, 0xc4204edd60, 0x0)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/cgocall.go:131 +0xe2 fp=0xc4204edd30 sp=0xc4204edcf0
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0x0)
        github.com/therecipe/qt/widgets/_obj/_cgo_gotypes.go:8869 +0x49 fp=0xc4204edd60 sp=0xc4204edd30
github.com/therecipe/qt/widgets.QApplication_Exec(0xc420011d70)
        /Users/Lulu/go/src/github.com/therecipe/qt/widgets/widgets.go:9314 +0x22 fp=0xc4204edd78 sp=0xc4204edd60
github.com/dzhou121/gonvim.InitEditorNew()
        /Users/Lulu/go/src/github.com/dzhou121/gonvim/editor.go:352 +0xdc2 fp=0xc4204edf68 sp=0xc4204edd78
main.main()
        /Users/Lulu/go/src/github.com/dzhou121/gonvim/cmd/gonvim/gonvim.go:15 +0x3a fp=0xc4204edf88 sp=0xc4204edf68
runtime.main()
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:185 +0x20a fp=0xc4204edfe0 sp=0xc4204edf88
runtime.goexit()
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4204edfe8 sp=0xc4204edfe0
```

**Comment by therecipe** [comment]
Hey

You could try to set `QT_DEBUG=true` and then re-run qtminimal and/or qtmoc.
Like this `QT_DEBUG=true && qtmoc && qtminimal && go build -tags=minimal`.

Setting QT_DEBUG will print out the current class and function name to the console before calling the actual c function.
```
22:33:20 	QApplication                                 NewQApplication(argc int, argv []string) *QApplication
22:33:20 	QObject                                      ConnectDestroyed(f func (obj *QObject) ) 
22:33:20 	QPushButton                                  NewQPushButton2(text string, parent QWidget_ITF) *QPushButton
22:33:20 	QObject                                      ConnectDestroyed(f func (obj *QObject) ) 
22:33:20 	QWidget                                      Show() 
22:33:20 	QWidget                                      X() int
22:33:20 	QWidget                                      Y() int
22:33:20 	QWidget                                      Move2(x int, y int) 
```

Or maybe take a look at https://github.com/derekparker/delve.

But most of the time the issue is something like calling a function that is not a slot or signal from another go routine/thread to make visual changes. Passing `nil` to a function that expects a real object. Or not fully implementing all the pure virtual function in abstract classes (QAbstractItemModel for example).

I would try to point you in concrete direction if I could, but those strack traces are not really informative. (but they rarely are)

>Also I occasionally got this error:
gonvim(24680,0x7ffff2f343c0) malloc: *** error for object 0x2a26ef10: double free

Do you manually free objects with `Destroy*` or `DeleteLater` ?

**Comment by dzhou121** [comment]
I do directly make visual changes from other go routine. I'll fix that. Thanks. 

> Do you manually free objects with Destroy* or DeleteLater ?

Yes, I manually destory* QBrush, QFontMetricsF, QPainter, QRectF, QPointF. Is that not needed?

**Comment by therecipe** [comment]
It depends, most of the times you don't have to, as most non QObject derived objects are gc.
But it might be necessary in some cases, like if you create many new objects in a "render" function. (Maybe caching those reusable tmp objects, would also be an option there)

Usually you can free everything that you created through `New*` and even calling the `Destroy*` function multiple times should be save.
A different case are objects received through functions like http://doc.qt.io/qt-5/qpainter.html#brush and http://doc.qt.io/qt-5/qpen.html#brush. The first one can't be freed but the second one can.

You can check for this by looking into the source to see if there is an finalizer set. Or by checking the official Qt docs, to see if the functions returns a real value or just a pointer or reference.

```go
func (ptr *QPainter) Brush() *QBrush {
	if ptr.Pointer() != nil {
		return NewQBrushFromPointer(C.QPainter_Brush(ptr.Pointer()))
	}
	return nil
}

func (ptr *QPen) Brush() *QBrush {
	if ptr.Pointer() != nil {
		var tmpValue = NewQBrushFromPointer(C.QPen_Brush(ptr.Pointer()))
		runtime.SetFinalizer(tmpValue, (*QBrush).DestroyQBrush)
		return tmpValue
	}
	return nil
}
```

And you also should never free objects that you received as input parameters when you override/connect a function, as they are most of the time freed internally.

**Comment by dzhou121** [comment]
After changing to use signal and slot for making visual changes, the crash is fixed. Thanks.
