### ISSUE TITLE
Compilation of qt/core as dependency fails

### ISSUE THREAD

**Issue by wbthomason** [therecipe/qt#366]
I'm building `qt/core` as a dependency of dzhou121/gonvim; as such, compiling `qt/core` does not follow the directions given in the README. Compilation fails with `QAbstractAnimation: No such file or directory`. Searching in the other issues indicated that running `qtsetup` might fix this, but that would seem to require installation of `qt/core` separately from `gonvim`. Is this the correct fix? If not, is there anything that I should be trying to make this compile as a dependency (I apologize if this is a stupid question; I'm a Golang naif).

I'm on Arch Linux, with go version 1.8.3.

**Comment by therecipe** [comment]
Hey

:) No, that's not a stupid question.
And yeah, you need to take some extra steps to setup this dependency.
The reason therefor is that this binding depends on cgo, and so qtsetup needs to generate some missing infos first to make it work.

You probably can get it working by running something like this:
```
go get -d -v github.com/dzhou121/gonvim
go get -v github.com/therecipe/qt/cmd/...
pacman -S qt5 qt5-doc
export QT_VERSION=5.9.0
export QT_PKG_CONFIG=true
$GOPATH/bin/qtsetup
$GOPATH/bin/qtdeploy test desktop $GOPATH/src/github.com/dzhou121/gonvim/cmd/gonvim
```

But I haven't tested it on arch in a while, and it also seems like they are already on 5.9.
I'm sure it should work, but there might show up a lot of warnings/errors.

**Comment by wbthomason** [comment]
Hi

Thanks for the response! I finally had a chance to try out the
instructions. Unfortunately, `qtsetup` reports a large number of errors
about a missing "purchasing" module. `qtdeploy` similarly reports errors
and fails to compile gonvim.

I'm going to ask in the `gonvim` repo to see if any steps need to be added
to the build instructions. The errors in the `qtdeploy` step seem to be
unrelated to this library, so if you don't think that the missing
purchasing module errors are important (i.e. they can be ignored), I'll go
ahead and close this issue.

Thanks again!

**Comment by therecipe** [comment]
No problem :)
And yes, the warnings/errors about the purchase module are expected (when QT_PKG_CONFIG is used) and are nothing to worry about.

**Comment by wbthomason** [comment]
Ok, closing as not an issue with this repo. Thanks again!
