### ISSUE TITLE
`Is` prefix resulted in error build

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#374]
Hi, 

I tried your fix for `Is` prefix issue for bool property. I got following message when building the code,

```
MacBook-Pro:therecipe-issue arknable$ qtrcc && go build -o app
# github.com/arknable/therecipe-issue
./moc.cpp:80:40: error: no member named 'isDefaultDefault' in 'Controller'; did you mean 'isIsDefaultDefault'?
./moc.cpp:62:7: note: 'isIsDefaultDefault' declared here
In file included from ./moc.cpp:310:
./moc_moc.h:97:53: error: no member named 'isIsDefault' in 'Controller'; did you mean 'isDefault'?
./moc.cpp:47:7: note: 'isDefault' declared here
```
I put a simple example here: https://github.com/arknable/therecipe-issue/blob/master/application.go#L13

thanks.

**Comment by therecipe** [comment]
Sorry, should be fixed with: https://github.com/therecipe/qt/commit/947ae3fdd8c925a08180dca6d9022a08153f8d03

**Comment by arknable** [comment]
hey, it works ... thanks 👍
