### ISSUE TITLE
builds using vagrant instead of docker ?

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#378]
suggestion... Here my pitch :)

1. Its a full OS, and so much less weird issues.
2. You need a desktop anyway to test your build outputs on and play with them.
- you need 2 in reality. One for builds, and one clean machine for testing (with no QT installed etc)
3. Vagrant with vagrant manager is so so easy to run. I am on OSX.
- see my complete setup at the bottom.
4. You can run OSX under vagrant fully !
5. The boxes (as they are called) are easy to use.
6. Its very easy to share files from the host to the virtualised OS
7. You can use packer to make IOS's that virtual box can boot if you want. Free for open soruce projects
8. There are some golang based help projects out there. Have no needed them yet.
9. You can also use them to provision docker !
- https://www.vagrantup.com/docs/providers/

Bad things:
1. disk space
 - It takes more disk then docker.
 - on my oSX host: windows take s15 gb, OSX takes about 17 gb.  Have not checked the docker images currently used for disk space, but i imagine its smaller..

2. ci 
- There are AWS and GCE providers.Also Vagrant cloud

Here is my setup script for everything

````
# windows testing using VirtualBox
brew doctor
brew update
sudo xcodebuild -license

# ensure any existing virtbox PIDS are killed first !
brew cask install virtualbox virtualbox-extension-pack vagrant vagrant-manager

## Bring up Windows
# win10: https://atlas.hashicorp.com/boxes/search?utf8=%E2%9C%93&sort=&provider=&q=windows
vagrant init Microsoft/EdgeOnWindows10; vagrant up --provider virtualbox

# win7: https://atlas.hashicorp.com/milbuild/boxes/Windows7
vagrant init milbuild/Windows7; vagrant up --provider virtualbox

# OSX
# https://github.com/AndrewDryga/vagrant-box-osx
# this is not hosted on vagrant cloud, but others are, and its legal these days
vagrant init http://files.dryga.com/boxes/osx-sierra-0.3.1.box
````

AddenduM.
There is also a way to VNC into Docker running desktops !! Forogt about that one :)
I tried it and it does work. So another option where you need to build & play with the compiled app

**Comment by therecipe** [comment]
Hey

Thank you, thats a great suggestion :)

I think that it could also be used to create a more extensive CI plan.
I'm not really happy with the current situation, because I can just test a small subset of what I would like to.
So this comes really handy. (I recall that I looked into vagrant before, but it somehow slipped my mind)

And yeah, something like `qtdeploy -vagrant build ...` should be easily possible after the initial hurdle is taken to setup this for CI.

I will try to get something working in the next few days.

Btw https://app.vagrantup.com/milbuild/boxes/Windows7 gives me a 404 atm, but that's probably due the fastly outage.

**Comment by joeblew99** [comment]
I am still in 2minds of this idea....
Docker can be a pain but it's automatic updating is sweet.
Virtual box is easy to use, but it's update story is insanity square :)
For osx, windows, Ubuntu I loose 60 gb of ssd disk and 4 GB of ram. So 50% of the Devs will not be able to use this, me included.

So don't throw away the docker approach.

**Comment by therecipe** [comment]
Yeah, I'm not planning to get rid of docker.
I will instead use vagrant to fill the missing spots in the CI and then also add a flag to the tools, so that you can use it for "cross-compiling" like you can do with the docker flag.

**Comment by therecipe** [comment]
@joeblew99 
I have added the initial support for vagrant with: https://github.com/therecipe/qt/commit/0f99eb634c8837bffcd4fd524ec8169692042d41

I haven't written the docs yet, but for example you just need to run `vagrant up linux` in `https://github.com/therecipe/qt/tree/master/internal/vagrant/linux` and then after the machine is provisioned you can use `qtdeploy -vagrant build linux/linux ...` like usual.

Or for iOS run `vagrant up ios` in `https://github.com/therecipe/qt/tree/master/internal/vagrant/darwin` and then use
`qtdeploy -vagrant build darwin/ios ...`
