### ISSUE TITLE
Is uic supported by this binding?

### ISSUE THREAD

**Issue by stephenlyu** [therecipe/qt#381]
I write a goqtuic tool for this qt binding. Please check https://github.com/stephenlyu/goqtuic. Any questions, please make an issue.

**Comment by therecipe** [comment]
Hey

That really awesome :)
I had a port of the uic, on my todo list but never found the time unfortunately.

After a quick look into the sample, it seems to work great so far :)
And you even got the signal/slot connections working.

The only thing that I found a bit tedious was that I had to write something like this:
```go
	w := widgets.NewQWidget(nil, 0)
	ui := new(UITestForm)
	ui.SetupUI(w)
	w.Show()
```

Instead of something like this:
```go
	w := NewUITestForm()
	w.Show()
```

But that's only a minor thing.

I will look into it more deeply tomorrow to give you some more feedback.

**Comment by stephenlyu** [comment]
Thanks for your feedback.

Before I wrote test code like this.
`	w := widgets.NewQWidget(nil, 0)
	ui := new(UITestForm)
	ui.SetupUI(w)
	w.Show()`

In order to support signal/slot connection better, I use subclassing mode. Because we could override slot function of "w" widget.

**Comment by stephenlyu** [comment]
I will update the test code generation logic. 

If no signal/slot connections in the ui file, I will generate code like this:
```
	w := widgets.NewQWidget(nil, 0)
	ui := new(UITestForm)
	ui.SetupUI(w)
	w.Show()
```
else, generate code like this:
```
	w := NewUITestForm()
	w.Show()
```

Actually, subclassing mode need use moc, it is a bit tedious.

**Comment by kitech** [comment]
so good point. hope to use it.

**Comment by jxltom** [comment]
Nice work! With it, I don't need to write UI code by hand but using QT-designer to design UI and using uic tools to generate UI code automatically. Save a lot of time.

Is there any plan to integrate it to therecipe's qt project? Like python's QT binding PyQt, it provide uic, rcc tools together. It will be great to install go's qt binding in one click, but with all tools such as uic, rcc integrated.

**Comment by jxltom** [comment]
@stephenlyu Maybe your initial designer was right? 

Using following code, user can SetupUI for any widget, such as QWindow, QDialog or just QWidget.

```go
w := widgets.NewQWidget(nil, 0)
	ui := new(UITestForm)
	ui.SetupUI(w)
	w.Show()
```

But after you change to ```w := NewUITestForm()```, user can not set base class and it will always be QWidget. Sometimes, user need use some property of other widget, such as QDialog.

Here is [usage](http://pyqt.sourceforge.net/Docs/PyQt5/designer.html#using-the-generated-code) of pyuic in Python's qt binding, which is already a mature qt binding, as a reference.

**Comment by therecipe** [comment]
I will close this now, since I recently added support for the uic with https://github.com/therecipe/qt/commit/01e05b1d5c9df871fabae4842127189431e526ac

**Comment by ManPython** [comment]
@therecipe but how we can use the .ui files exactly?

There is the 
`github.com\therecipe\qt\internal\examples\uitools\calculator` 
but not so clear how is generated the 
`github.com\therecipe\qt\internal\examples\uitools\calculator\ui\calculatorform.go` 

BTW do you know the https://github.com/kitech/qt.go ?
