### ISSUE TITLE
Qml SpinBox: Cannot assign to non-existent property "onEditingFinished"

### ISSUE THREAD

**Issue by averrin** [therecipe/qt#383]
Seems like SpinBox component has no `onEditingFinished` signal and `maximumValue` property.
But if i use it only with `value` it can be shown. But without signals i cannot interact with it=(

**Comment by therecipe** [comment]
Hey

Those should be available.
But the functions you are looking for are called: `ConnectEditingFinished` and `Maximum`

Does this work for you?
```go
package main

import (
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	window := widgets.NewQMainWindow(nil, 0)

	spinbox := widgets.NewQSpinBox(nil)
	spinbox.ConnectEditingFinished(func() {
		println("editing finished", spinbox.Value())
	})

	spinbox.SetMinimum(0)
	spinbox.SetMaximum(1000)

	window.SetCentralWidget(spinbox)
	window.Show()

	widgets.QApplication_Exec()
}
```

**Comment by averrin** [comment]
I am about QML SpinBox and if i write something like
```
SpinBox {
  onEditingFinished: {
    someFunc();
  }
}```
Ill get error.

**Comment by therecipe** [comment]
Ah, sorry.

Then you are probably just imported the new controls with "import QtQuick.Controls 2.1", but you are still looking at the old controls docs.

http://doc.qt.io/qt-5/qml-qtquick-controls-spinbox.html
https://doc.qt.io/qt-5/qml-qtquick-controls2-spinbox.html

Here, this example shows that the old SpinBox has the onEditingFinished signal + the maximumValue property. While the new one has the onValueChanged signal + "from" and "to" instead of min/maxValue.

```qml
import QtQuick 2.7
import QtQuick.Layouts 1.3

import QtQuick.Controls 1.4 as Old
import QtQuick.Controls 2.1 as New

Rectangle {
  Old.SpinBox {
    id: oldSpinBox

    anchors {
      top: parent.top
      left: parent.left
      right: parent.right
    }

    minimumValue: 10
    maximumValue: 20

    onEditingFinished: {
      console.log("Old SpinBox Finished" + value)
    }

    onValueChanged: {
      console.log("Old SpinBox Changed " + value)
    }
  }

  New.SpinBox {

    anchors {
      top: oldSpinBox.bottom
      left: parent.left
      right: parent.right
    }

    from: 10
    to: 20

    onValueChanged: {
      console.log("New SpinBox Changed" + value)
    }
  }
}
```

**Comment by averrin** [comment]
Nice catch, thanks!
