### ISSUE TITLE
Why QLineEdit Font SetPointSize only effects placeholder?

### ISSUE THREAD

**Issue by hanbang-wang** [therecipe/qt#384]
For example I had a `QLineEdit` created by `widgets.NewQLineEdit(nil)`, then I `.SetPlaceholderText("Num here")` and `.SetText("1000")`. After that, I used `.Font().SetPointSize(20)` to set the font's point size, but the result was really confusing. The text `1000` has its original size, but when I deleted the text and left it blank, the placeholder text `Num here` was using the correct size.

**Comment by therecipe** [comment]
Hey

I think that this is made on purpose.

>In particular, certain styles like GTK style, Mac style, Windows XP, and Vista style, apply special modifications to the widget font to match the platform's native look and feel. Because of this, assigning properties to a widget's font is not guaranteed to change the appearance of the widget. Instead, you may choose to apply a styleSheet.

from: http://doc.qt.io/qt-5/qwidget.html#font-prop

And using a stylesheet seem to work:
```go
package main

import (
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	le := widgets.NewQLineEdit(nil)
	le.SetPlaceholderText("Num here")
	le.SetText("1000")
	//le.Font().SetPointSize(20)
	le.SetStyleSheet("font: 20px")
	le.Show()

	widgets.QApplication_Exec()
}
```

**Comment by hanbang-wang** [comment]
That helps a lot, thanks!

_Sent from my Samsung SM-G9500 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
