### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#391]
Would like to donate to help keep this going . Have you got a patron account ?

**Comment by therecipe** [comment]
Hey

Thanks for the offer :)
But no, I got no patreon or anything similar.
I looked into these services and figured that unless you have a really really big following, the outcome is most of the times rather moderate. And so I let it be.

Another reason therefor was also, that there are plans to secure the further development of this project with the help of dual license bussiness model. And so I wouldn't feel comfortable to also accept donations (by individuals).


But again thanks for the offer, I really appreciate it, even though I can't accept it :)

**Comment by averrin** [comment]
Maybe you just add paypal button? I like go and qt, but some issues make me sad=(
