### ISSUE TITLE
Cannot resize tableview embedded within TabWidget

### ISSUE THREAD

**Issue by omac777** [therecipe/qt#395]
I'm trying to get the tableview to resize itself to its parent container, a TabPage within a Tab widget.  My attempt has a callback for the resize event that tells the the main window about the new frame size, but I haven't found the appropriate functions to drill down and set the tab, tableview, and column sizes respectively. In fact I received an error 
when I tried to iterate through all the QWidget window handles owned by QApplication from within the resize event.
i.e. QQuickWidget cannot be used as a native child widget. Consider setting Qt::AA_DontCreateNativeWidgetSiblings

Has anyone dealt with anything similar with the golang bindings?

I was actually considering to use a set of qmlbridge values for the resizewindowidth and resizewindowheight, then entirely handle it from the qml side, but I was hoping to do the entire opposite which is to entirely handle it from the golang qt bindings side.

Thank you in advance.

```
window := initSomeMainWindow()
centralWidget := widgets.NewQWidget(window, 0)
windowLayout := widgets.NewQVBoxLayout()

centralWidget.SetLayout(windowLayout)
window.SetCentralWidget(centralWidget)

var viewFirstPage = quick.NewQQuickWidget(nil)
viewFirstPage.RootContext().SetContextProperty("QmlBridge", qmlBridge)
viewFirstPage.SetSource(core.NewQUrl3("qrc:///qml/scenes-tableview.qml", 0))
viewFirstPage.SetResizeMode(quick.QQuickWidget__SizeViewToRootObject)
//viewFirstPage.SetResizeMode(quick.QQuickWidget__SizeRootObjectToView)
	
layoutFirstTabPage.AddWidget(viewFirstPage, 0, core.Qt__AlignCenter)
myFirstTabPage.SetLayout(layoutFirstTabPage)
myTabWidget.AddTab(myFirstTabPage, "Scene selection")

windowLayout.AddWidget(myTabWidget, 0, 0)

window.ConnectResizeEvent(window.resizeEvent)

window.Show()

widgets.QApplication_Exec()





func (tmw *SomeMainWindow) resizeEvent(ev *gui.QResizeEvent) {
	fmt.Printf("SomeMainWindow resizeEvent()...\n")
	fmt.Printf("ev.Size():<<%v>>\n", ev.Size())

	qsizeResizeEvent := ev.Size()
	fmt.Printf("qsizeResizeEvent.Rheight():<<%v>>\n", qsizeResizeEvent.Rheight())
	fmt.Printf("qsizeResizeEvent.Rwidth():<<%v>>\n", qsizeResizeEvent.Rwidth())
	

	//QApplication_AllWidgets() []*QWidget

	//theAppWidgets := widgets.QApplication_AllWidgets()
	//fmt.Printf("theAppWidgets:<<%q>>\n", theAppWidgets)

	// for index, theWidget := range theAppWidgets {
	// 	fmt.Printf("index <<%d>>\n", index)
	// 	fmt.Printf("value <<%v>>\n", theWidget)

	// 	theWindowId := theWidget.WinId()
	// 	fmt.Printf("WinId():<<%v>>\n", theWindowId)

	// 	//theName := theWidget.ObjectName()
	// 	//fmt.Printf("objectname: <<%s>>\n", theName)
	// }
	
	
	//create a qmlbridge property for tableview qrect or qsize
	//then set all the tableview's column widths from within qml itself and not from golang
	//???possibly set the qmlbridge's tableview qrect/qsize based on the resize event's new qsize HERE.	

        //how to translate the following code pattern in golang therecipe/qt bindings?
        //if I could find the correct windowid for the tableview I could possibly cast the pointer
        //into a golang qt tableview object and then call the appropriate functions.
	//MOVE THE FOLLOWING CODE PATTERN INTO THE TABLEVIEW QML FILE
	//table_view->setColumnWidth(0, this->width()/3);
	//table_view->setColumnWidth(1, this->width()/3);
	//table_view->setColumnWidth(2, this->width()/3);	
}
```

**Comment by therecipe** [comment]
Hey

You probably just made a small mistake by using `core.Qt__AlignCenter` when calling: `layoutFirstTabPage.AddWidget(viewFirstPage, 0, core.Qt__AlignCenter)` 
This will change the SizePolicy of the viewFirstPage or layoutFirstTabPage.AddWidget (or something else) and therefore the viewFirstPage will stop expanding. (I hope that's one of the things you wanted to achieve)

The other thing is, that even though you can directly manipulate QML from Go/C++, it's not really recommended. If you still have to, then you should create a property in the QmlBridge and use it as a proxy between Go and the QML TableColumn width. (Or use signals/slots, but properties are most of the time more convenient)

Here is a working version:
```go
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/quick"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	window := widgets.NewQMainWindow(nil, 0)
	centralWidget := widgets.NewQWidget(window, 0)
	windowLayout := widgets.NewQVBoxLayout()

	centralWidget.SetLayout(windowLayout)
	window.SetCentralWidget(centralWidget)

	viewFirstPage := quick.NewQQuickWidget(nil)
	//viewFirstPage.RootContext().SetContextProperty("QmlBridge", qmlBridge)
	viewFirstPage.SetSource(core.NewQUrl3("./qml/scenes-tableview.qml", 0))
	//viewFirstPage.SetResizeMode(quick.QQuickWidget__SizeViewToRootObject)
	viewFirstPage.SetResizeMode(quick.QQuickWidget__SizeRootObjectToView) //<- we want the root object (QML TableView) to resize to the size of the qquickwidget

	myTabWidget := widgets.NewQTabWidget(nil)
	window.SetCentralWidget(myTabWidget)

	layoutFirstTabPage := widgets.NewQVBoxLayout()
	layoutFirstTabPage.AddWidget(viewFirstPage, 0, 0) //<- core.Qt__AlignCenter does probably change the sizepolicy of viewFirstPage or something, therefore the widget won't expand

	myFirstTabPage := widgets.NewQWidget(nil, 0)
	myFirstTabPage.SetLayout(layoutFirstTabPage)
	myTabWidget.AddTab(myFirstTabPage, "Scene selection")

	window.ConnectResizeEvent(func(ev *gui.QResizeEvent) { resizeEvent(viewFirstPage, ev) })

	window.Show()

	widgets.QApplication_Exec()

}

func resizeEvent(view *quick.QQuickWidget, ev *gui.QResizeEvent) {
	fmt.Printf("SomeMainWindow resizeEvent()...\n")
	fmt.Printf("ev.Size():<<%v>>\n", ev.Size())

	qsizeResizeEvent := ev.Size()
	fmt.Printf("qsizeResizeEvent.Rheight():<<%v>>\n", qsizeResizeEvent.Rheight())
	fmt.Printf("qsizeResizeEvent.Rwidth():<<%v>>\n", qsizeResizeEvent.Rwidth())

	fmt.Println("view.RootObject:", view.RootObject().ObjectName())

	/* casting to TableView + SetColumnWidth won't work
	table_view := widgets.NewQTableViewFromPointer(view.RootObject().Pointer())
	table_view.SetColumnWidth(0, view.Width()/3)
	table_view.SetColumnWidth(1, view.Width()/3)
	table_view.SetColumnWidth(2, view.Width()/3)
	*/

	//This works, but it is not recommented to directly manipulate QML from Go
	//comment these out and take a look into the QML file instead
	//you will also feel that the QML version feels less sluggish
	quick.NewQQuickItemFromPointer(view.RootObject().FindChild("column1", core.Qt__FindChildrenRecursively).Pointer()).SetProperty("width", core.NewQVariant7(view.Width()/3))
	quick.NewQQuickItemFromPointer(view.RootObject().FindChild("column2", core.Qt__FindChildrenRecursively).Pointer()).SetProperty("width", core.NewQVariant7(view.Width()/3))
	quick.NewQQuickItemFromPointer(view.RootObject().FindChild("column3", core.Qt__FindChildrenRecursively).Pointer()).SetProperty("width", core.NewQVariant7(view.Width()/3))
}
```

```qml
import QtQuick 2.7
import QtQuick.Controls 1.4

TableView {
  id: root
  objectName: "MyQmlTableView"
	model: ListModel {
    ListElement {
      name: "Apple"
      cost: 2.45
      color: "red"
    }

    ListElement {
      name: "Orange"
      cost: 3.25
      color: "orange"
    }

    ListElement {
      name: "Banana"
      cost: 1.95
      color: "yellow"
    }
  }

  TableViewColumn {
    objectName: "column1"
    role: "name"
    title: role
    //width: root.width / 3 //<- parent is null, therefore you need to use the root id instead
    //width: qmlBridge.someCustomProperty1 //<- alternatively if you want to use properties
  }

  TableViewColumn {
    objectName: "column2"
    role: "cost"
    title: role
    //width: root.width / 3 //<- parent is null, therefore you need to use the root id instead
    //width: qmlBridge.someCustomProperty2 //<- alternatively if you want to use properties
  }

  TableViewColumn {
    objectName: "column3"
    role: "color"
    title: role
    //width: root.width / 3 //<- parent is null, therefore you need to use the root id instead
    //width: qmlBridge.someCustomProperty3 //<- alternatively if you want to use properties
  }
}
```

**Comment by omac777** [comment]
Your answer is so thorough.  I truly appreciate all your efforts.  I
wish therecipe/qt the greatest of popularity and success.  It deserves
greater attention from the golang community as it crystallizes its
position as the #1 choice for building gui's with golang on all
operating systems alike.

Thank you.

**Comment by omac777** [comment]
worked like a charm on Arch Linux with Qt5.8.0 downloaded from trolltech.  I can't manage to compile with archlinux qt packages unfortunately since the dirs are the same.

I tried the same sample you gave me in windows msys2 updated last week.  when I build I get the following errors, but it still outputs a working binary that behaves seemingly correctly.

2017-07-12_09:21:56_EDT : ~/go-rsztblvw

qtdeploy build desktop .
time="2017-07-12T09:22:51-04:00" level=error msg="failed to run command" cmd="cp C:\\dev\\msys64\\mingw64\\bin\\libicudt57.dll C:\\dev\\msys64\\home\\davidm\\go-rsztblvw\\deploy\\windows_minimal" error="exit status 1" func=RunCmdOptional name="copy libicudt57 for desktop on windows" output="cp: cannot stat 'C:\\dev\\msys64\\mingw64\\bin\\libicudt57.dll': No such file or directory\n"
time="2017-07-12T09:22:52-04:00" level=error msg="failed to run command" cmd="cp C:\\dev\\msys64\\mingw64\\bin\\libicuin57.dll C:\\dev\\msys64\\home\\davidm\\go-rsztblvw\\deploy\\windows_minimal" error="exit status 1" func=RunCmdOptional name="copy libicuin57 for desktop on windows" output="cp: cannot stat 'C:\\dev\\msys64\\mingw64\\bin\\libicuin57.dll': No such file or directory\n"
time="2017-07-12T09:22:52-04:00" level=error msg="failed to run command" cmd="cp C:\\dev\\msys64\\mingw64\\bin\\libicuuc57.dll C:\\dev\\msys64\\home\\davidm\\go-rsztblvw\\deploy\\windows_minimal" error="exit status 1" func=RunCmdOptional name="copy libicuuc57 for desktop on windows" output="cp: cannot stat 'C:\\dev\\msys64\\mingw64\\bin\\libicuuc57.dll': No such file or directory\n"

**Comment by therecipe** [comment]
Thank you :)

On Arch you should be able to get it working by simply exporting `QT_PKG_CONFIG=true` and then re-running the setup. (There should be no further config required)
Also make sure to make the QT_PKG_CONFIG export persistent, otherwise you will need to re-set it before running qtdeploy.

For the msys2 issue, you probably need to either update the binding or the packages, or maybe even both.
