### ISSUE TITLE
Crossplatform app with webkit

### ISSUE THREAD

**Issue by averrin** [therecipe/qt#400]
After long hard way (https://github.com/therecipe/qt/issues/380) i wrote webkit code for windows, but on linux where webengine code works, `undefined: webkit.NewQWebView`.
I installed `qt-opensource-linux-x64-5.9.1.run` and `qtwebkit-5.212.0_alpha2-qt59-linux-x64.tar.xz`, reinstall bindings, but no luck. On windows i use qtsetup with QT_VERSION=5.8 when using sources from 5.9 but i cant do it on linux (both vars used in path).
So, my customer platform is windows, but i think qwebkit is very valuable part of qt and it is problem when we have no enough docs for using it.

**Comment by therecipe** [comment]
Hey

I haven't tested 5.9 + "qtwebkit-5.212.0_alpha2" on linux yet.
But it should already work with the official pre-built version of 5.8 and https://github.com/annulen/webkit/releases/download/qtwebkit-tp5/qtwebkit-tp5-qt58-linux-x64.tar.xz
