### ISSUE TITLE
If I have some Go package, Then my program has a console window

### ISSUE THREAD

**Issue by pipilu321** [therecipe/qt#412]
like title!

**Comment by therecipe** [comment]
Hey

Yeah, I experienced a similar issue recently on windows, when importing certain 3rd party packages.
But I haven't looked into it yet.

What settings did you used to compile your program?
MSYS2? The official pre-built Qt version? Did you cross compil from Linux with MXE?
Is your application 32 or 64 bit? Do you import a lot of 3rd party packages?

**Comment by pipilu321** [comment]
Thanks for your reply.
I use Qt 5.8.0 and MinGW on Windows10 64 bit, my application build for 32bit. I import a my own package.
Let's look a example: https://github.com/pipilu321/qt-issue

**Comment by pipilu321** [comment]
I installed QT by this https://github.com/therecipe/qt/blob/master/README.md
---
Desktop
  Windows(Official (with Android support))
---

**Comment by therecipe** [comment]
Thanks, I will look into this.

**Comment by therecipe** [comment]
Will close this, since it seems to be fixed by now (https://github.com/therecipe/qt/commit/0e3cd9505298e99148fa12b6ffd207364155a9d7)
