### ISSUE TITLE
Some question about tools

### ISSUE THREAD

**Issue by RadhiFadlillah** [therecipe/qt#418]
Hey @therecipe, I've using this binding for several weeks, yet I still have some questions about the tools.

1. **What is the purpose of `-qt_dir` and `-qt_version` flags on `qtsetup` and `qtdeploy` ?**
   
   In [#392](https://github.com/therecipe/qt/issues/392#issuecomment-314626295) I've tried installing Qt 5.9.0 by setting `-qt_dir` and `-qt_version` flags like this :

   ```
   qtsetup -qt_dir "$HOME/Qt5.9.0" -qt_version "5.9.0"
   ```

   However this command doesn't work, and installation only works after making environment variables `QT_DIR` and `QT_VERSION` permanent in `~/.profile`. So, why do `-qt_dir` and `-qt_version` flags exist and when should we use it ?

2. **Can I use regular installation and docker installation at same time ?**

   I've installed this binding on Manjaro Linux using [regular installation](https://github.com/therecipe/qt#regular-setup) method with Qt 5.9.0. After that, I create an app that use new Qt 5.9 API [`QSplitter.replaceWidget`](https://doc.qt.io/qt-5/qsplitter.html#replaceWidget). Now I want to cross compile it from Linux to Windows. For simplicity, I decided to use docker images. So, according to [readme](https://github.com/therecipe/qt#minimal-setup) I have to run setup again : 
   
   ```
   qtsetup -docker
   ```
   
   After finished, I tried to deploy it to Windows using :

   ```
   qtdeploy -docker build windows
   ```

   However, since docker image is using Qt 5.8.0, the API that I want to use is not available. Now I try to deploy my app to Linux, using `qtdeploy` that I've installed using regular installation with Qt 5.9.0 :
   
   ```
   qtdeploy build linux
   ```
   
   Unfortunately, it still said that `replaceWidget` is undefined. So, does the second `qtsetup` (which using Qt 5.8.0 on docker image) will overwrite API that generated by first `qtsetup` (which using Qt 5.9.0) ?

3. **Are there any differences between static app that deployed for 64-bit (`QT_MXE_ARCH=amd64`) and for 32-bit (`QT_MXE_ARCH=386`) ?**

   In my Linux system, I've set `QT_MXE_STATIC=true` and downloaded docker image for both `windows_64_static` and `windows_32_static` :

   ```bash
   [radhi@Lenovo-G50 ~]$ docker image ls
   REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
   therecipe/qt        windows_64_static   3447495a49b6        3 days ago          5.63GB
   therecipe/qt        windows_32_static   71a3a091b13f        3 days ago          5.46GB
   therecipe/qt        windows_32_shared   2346cf8dc099        3 days ago          4.92GB
   therecipe/qt        linux               d76fb56178a9        3 days ago          3.58GB
   ```

   After that, I tried to deploy my app to Windows 64-bit and 32-bit. Everytime I want to switch the architecture, I set environment variables `QT_MXE_ARCH` permanently in `~/.profile`, reboot my system, then run `qtdeploy -docker build windows`. 
   
   The weird thing is, output of `qtdeploy` for 64-bit and 32-bit has same size :

   ```bash
   [radhi@Lenovo-G50 ~]$ ls -l | grep my-app
   -rwxr-xr-x   1 radhi radhi 28210688 Agu  5 16:17 my-app-386.exe
   -rwxr-xr-x   1 radhi radhi 28210688 Agu  5 16:32 my-app-x64.exe
   ```

   And both have same file type :

   ```bash
   [radhi@radhi-Lenovo-G50 ~]$ file my-app*
   my-app-386.exe: PE32 executable (GUI) Intel 80386 (stripped to external PDB), for MS Windows
   my-app-x64.exe: PE32 executable (GUI) Intel 80386 (stripped to external PDB), for MS Windows
   ```

   Even in Windows task manager, `my-app-x64.exe` is reported as 32-bit app :

   ![capture](https://user-images.githubusercontent.com/6129042/28995919-03ed78ae-7a20-11e7-964a-6656ba31b70b.PNG)

   Fortunately, both executable work normally no matter what is the system architecture. So this question is just to satisfy my curiosity.

4. Following above question, **if I want to change `QT_MXE_ARCH` and `QT_MXE_STATIC`, do I have to set it permanently in `~/.profile` ?**

5. **Why is output directory of `qtdeploy -docker` is owned by root ?**

   So, for minimal installation I installed Docker using these commands :

   ```bash
   sudo pacman -S docker
   sudo usermod -a -G docker $USER
   sudo systemctl enable docker
   sudo systemctl start docker
   ```

   Now, whenever I deploy uisng `-docker` flag, output directory will be owned by `root`. So, if I run this command :

   ```
   qtdeploy -docker build windows
   ```

   the `windows` directory will be owned by root :

   ```bash
   [radhi@Lenovo-G50 deploy]$ ls -l
   total 8
   drwxr-xr-x 6 radhi radhi 4096 Agu  5 11:14 linux
   drwxr-xr-x 2 root  root  4096 Agu  5 16:32 windows
   ```

Well that's all for now, thanks for your answer.

**Comment by therecipe** [comment]
>What is the purpose of -qt_dir and -qt_version flags on qtsetup and qtdeploy ?

This is only a convenient way to quickly test another Qt version without the need to override your current env variables.
If you have two different Qt versions installed for example, then you can quickly test a deployment/build against the other version with `qtdeploy -qt_dir=... -qt_version=... build desktop ...`.

>Unfortunately, it still said that replaceWidget is undefined. So, does the second qtsetup (which using Qt 5.8.0 on docker image) will overwrite API that generated by first qtsetup (which using Qt 5.9.0) ?

Yes it will be overridden, and you also don't need to run the docker setup to deploy with docker.
Just run the regular setup and then use `qtdeploy -docker ...`

The docker setup is mainly for people who don't want to install Qt on the host at all and only ever use the `qtdeploy -docker ...` deployments.

 >Are there any differences between static app that deployed for 64-bit (QT_MXE_ARCH=amd64) and for 32-bit (QT_MXE_ARCH=386) ?

Yes, setting QT_MXE_ARCH=amd64 should give you 64 bit applications in the end.
You also don't need to set the env variables inside the .profile for this to work, you just need to export them with `export QT_MXE_ARCH=amd64 && export QT_MXE_STATIC=true` for example.

Its seems like you only got two 32 bit applications somehow.

Maybe try to run `qtdeploy -docker build windows_64_static` and `qtdeploy -docker build windows_32_static` instead, I haven't documented that yet, but you should be able to use the docker image names now as well to switch between 32/64 and static/shared.


>Following above question, if I want to change QT_MXE_ARCH and QT_MXE_STATIC, do I have to set it permanently in ~/.profile ?

Nope, you just need to export them before running `qtdeploy -docker ...` somehow.

 >Why is output directory of qtdeploy -docker is owned by root ?

Yeah, that's dockers fault.
Docker needs to be run as root and adding yourself to the `docker` group with usermod is the same as adding yourself into the root group iirc. But this should have been fixed some time ago: https://github.com/therecipe/qt/issues/290 (I will look into it again.)

>Well that's all for now, thanks for your answer.

You are welcome :)

**Comment by RadhiFadlillah** [comment]
Hey @therecipe 

> This is only a convenient way to quickly test another Qt version without the need to override your current env variables.

So, basically those flags is only used if I don't want to set the environment variables. Instead, I have to run `qtsetup` and `qtdeploy` with same value in `-qt_dir` and `-qt_version` flags. For example, if I want to deploy using Qt 5.9.0 without setting permanent environment variables, I have to run :

```
qtsetup -qt_dir=$HOME/Qt5.9.0 -qt_version=5.9.0
qtdeploy -qt_dir=$HOME/Qt5.9.0 -qt_version=5.9.0 build desktop
```

> ... you also don't need to run the docker setup to deploy with docker.

> The docker setup is mainly for people who don't want to install Qt on the host at all and only ever use the qtdeploy -docker ... deployments.

So, if I'm using the minimal installation, there are no need to run `qtsetup -docker` at all. Instead I can just go running `qtdeploy -docker`. And here I am keep on switching between normal `qtsetup` and `qtsetup -docker` :triumph: :triumph:.

> you should be able to use the docker image names now as well to switch between 32/64 and static/shared.

Yeah it works. Now when I'm running `file` command, it reported that my app is `PE32+ executable (GUI) x86-64 for MS Windows`. And, there are also no need to set `QT_MXE_ARCH` and `QT_MXE_STATIC` :triumph:.

It seems the readme really need to be updated ASAP. 

Unfortunately, I still have some work until Wednesday. However, if you don't mind waiting until then, once I'm done with my work I will continue working on wiki and once it's ready I will send PR for readme.

**Comment by therecipe** [comment]
Sorry, I'm bit bussy atm and will try to slowly work through the backlog in the next few days.

>to deploy using Qt 5.9.0 without setting permanent environment variables, I have to run

You don't need to re-run the setup with -qt_version and -qt_dir if you just want to quickly test the deployment against 5.9 or some other version and you already have 5.8 or some other Qt version installed. This is because qtdeploy will use qtminimal to create a subset of the needed binding code on the fly, and this new code will not interfer with your "full" qt installation (even if another Qt version was used). The files that are created by qtdeploy or qtminimal are prefixed with "minimal-" and can be found in the core, gui, widgets, ... folders.

> And here I am keep on switching between normal qtsetup and qtsetup -docker

Yep, sorry for the confusion :D
You can use "qtdeploy -docker ..." without running any setup at all.

Also, btw thanks for helping out with the issues :)
