### ISSUE TITLE
core.QItemSelectionModel.SetCurrentIndex() invokes bad c++ method

### ISSUE THREAD

**Issue by DaleFarnsworth** [therecipe/qt#419]
Calling core.QItemSelectionModel.SetCurrentIndex(index, flag) results in the following error message:

QMetaObject::invokeMethod: No such method QItemSelectionModel::setCurrentIndex(QModelIndex,QItemSelectionModel::SelectionFlag)
Candidates are:
    setCurrentIndex(QModelIndex,QItemSelectionModel::SelectionFlags)

Thanks.

**Comment by therecipe** [comment]
Hey

I will look into it.

**Comment by therecipe** [comment]
Should be fixed now with: https://github.com/therecipe/qt/commit/7840b778c38f5872ad67f1f0451ea252812536ee

**Comment by DaleFarnsworth** [comment]
Thanks! I should have closed this long ago.
