### ISSUE TITLE
qtsetup fails to run on Gentoo/Funtoo systems

### ISSUE THREAD

**Issue by quiznilo1** [therecipe/qt#420]
Can't get this to install on Funtoo x86_64 system:

QT_DIR=/usr/lib64/qt5 QT_VERSION=5.7 qtsetup 
...
ERRO[0021] failed to run command                         cmd="/usr/lib64/qt5/5.7/gcc_64/bin/rcc -project -o /home/xxxx/go/src/github.com/therecipe/qt/internal/examples/qml/application/rcc.qrc" env= error="fork/exec /usr/lib64/qt5/5.7/gcc_64/bin/rcc: no such file or directory" func=RunCmd name="execute rcc *.qrc on linux for linux"

while I have no /usr/lib64/qt5/5.7/gcc_64/bin/rcc, I do have a /usr/lib64/qt5/bin/rcc

Note: I have those env vars already in ~/.zshrc

**Comment by therecipe** [comment]
Hey

It seems like you are trying to use the Qt libs provided by your systems package manager or?
If yes, then maybe unset QT_DIR and QT_VERSION and instead just set QT_PKG_CONFIG=true.
Then just re-run the setup.
