### ISSUE TITLE
Autocomplete do not work

### ISSUE THREAD

**Issue by neoxharsh** [therecipe/qt#421]
Autocomplete seems to be non working in any IDE, i have tried LiteIDE and GoGlang. It was working perviously. On GoGlang it shows that their are no buildable go source.

**Comment by bigemon** [comment]
https://github.com/rogpeppe/godef/pull/44/files
Try this

**Comment by 5k3105** [comment]
When I was having trouble with IntelliJ, I was able to fix it by upping the memory settings:
See "Code Editor Settings (for code completion)" on main page.

**Comment by neoxharsh** [comment]
It seems that only qt widgets is not auto completing, all others seems to work

**Comment by 5k3105** [comment]
because widgets is larger than the others. Increase memory size if possible.

**Comment by r03** [comment]
It does work in vim with vim-go. (also widgets)
I guess some IDE's have problems with large files/packages?

**Comment by therecipe** [comment]
@r03 
Yepp, depending on your editor/IDE you might need to increase the memory size or edit the default timeout for go-code: https://github.com/therecipe/qt/wiki/FAQ#how-to-make-ides-code-completion-works-

For some editors such as Atom, Sublime or LiteIDE it works out of the box though.

**Comment by neoxharsh** [comment]
I have tried LiteIDE and it is not working

**Comment by therecipe** [comment]
@neoxharsh 
Not at all? Or only the widgets/gui packages?
Could be that you also need to set GOARCH=386, if you are on windows.

Alternatively you probably could also run the the setup with `QT_STUB=true` once, and then install the stub packages with something like `go install github.com/therecipe/qt/...` to get code completion working for windows with GOARCH=amd64.
