### ISSUE TITLE
Example Web Browser

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#422]
https://github.com/5k3105/Coral

I will be using this as a base for my project but if you'd like to include it as an example you are welcome to copy it as it is now.

**Comment by therecipe** [comment]
Awesome, thank you :)
I will copy it and create a new example tomorrow.

**Comment by 5k3105** [comment]
ok. closing this then.

**Comment by therecipe** [comment]
Thanks again, I added it here: https://github.com/therecipe/qt/tree/master/internal/examples/webkit/coral

**Comment by 5k3105** [comment]
Thanks :+1:  Better to name it examples/webkit/browser because this is only the start of that coral project.
