### ISSUE TITLE
example showing signing apps

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#427]
any chance you can show how to sign an app for google and apple stores ?

For android i do this in general:
https://docs.google.com/presentation/d/1PvlfcO5OU0Zlv3eISdIgUsRLpXsVaMvxX0C0c7iCvHg/edit#slide=id.g1530211a36_0_279

For IOS / OSX; i have not worked it out yet.

**Comment by therecipe** [comment]
Yeah, the info for android is a bit hidden under: https://github.com/therecipe/qt#branding-3

>If you want to have your *.apk signed automatically, then you need to create an alias.txt, password.txt and an project_name.keystore inside the android folder.

```
project_name
├── android
│   ├── AndroidManifest.xml
│   ├── alias.txt
│   ├── build.gradle
│   ├── gradle
│   │   └── wrapper
│   │       └── gradle-wrapper.properties
│   ├── icon.png
│   ├── password.txt
│   ├── project_name.keystore
│   └── res
│       ├── drawable-hdpi
│       │   └── icon.png
│       ├── drawable-ldpi
│       │   └── icon.png
│       └── drawable-mdpi
│           └── icon.png
├── deploy
│   └── android
│       └── build
├── project.go
└── qml
    └── project.qml
```

For macOS or iOS, you will need to use Xcode.
There you can chose a provisioning team/provile and then it will be automatically signed when you click the build button.
It's probably also possible to sign it from command line, but I haven't looked into that yet.

**Comment by joeblew99** [comment]
thanks. makes sense. Wil try this way..
