### ISSUE TITLE
Multiple gcc/mingw installations

### ISSUE THREAD

**Issue by qZanity** [therecipe/qt#433]
Hello.

I currently have an existing mingw/gcc installed on my system, and the /bin directorys in my PATH env variables.

To use this qt package we require to add another mingw/gcc /bin to the system PATH. (from the qt/tools directory)

How do i get qtdeploy and other tools to use the correct gcc.exe? as it's using the one that appears first in my PATH variable. It works if i remove the other PATH but then my editor (Atom) wont succesfully build go programs.

**Comment by 5k3105** [comment]
I use https://www.rapidee.com/en/download when I need to re-order env-vars between programs. It is kind of a pain switching between compilers though.
