### ISSUE TITLE
Question : " Go get therecipe/qt "

### ISSUE THREAD

**Issue by hubyhuby** [therecipe/qt#437]
Hi Thereceipe,

It could be a nice feature to be able to do a "go get" like with most golang project / library.
I am not an expert and don t know anything about Docker. Maybe my question is out of focus...

What I love with go it is its simplicity, at the core of it. Things like "go get" is super powerful & Works out of the box. Asking people to install and learn Docker (even if it is simple), is raising the bar to get in your project. 

Sorry for creating directly a bug, I don t think there is a forum for it.

**Comment by 5k3105** [comment]
You don't have to use the docker version. Download the qt distro then go get this lib.

**Comment by therecipe** [comment]
@hubyhuby 
No problem, this is a good place to ask questions as well :)

Yeah, beeing able to simply go get this package would be nice, but that's a bit difficult to realize due the dependecy on cgo. However, maybe there will be support for godep in the future to make things a bit simpler to setup.

**Comment by hubyhuby** [comment]
Hi,
The new readme commited recently is much much better . 
It now gives clear indications on how to start with the library.
It brings you first to the "minimal installation", which is what  people like me wish, in order  to give it a try.
https://github.com/therecipe/qt/wiki/Installation

Thanks a lot

**Comment by hubyhuby** [comment]
Guess I am getting closer ....
I managed to launch the docker image , with the following command (wich could be added to the install doc): 

**sudo docker run -it therecipe/qt:linux bash**

The deploy command the "easy way" doesn t look so good :

root@decd5dc673fc:~/work/src/ex01# qtdeploy -docker test desktop
ERRO[0000] failed to run command                         cmd="docker run --rm -e IDUG=0:0 -v /home/user/work:/media/sf_GOPATH0 -e GOPATH=/home/user/work:/media/sf_GOPATH0 -i therecipe/qt:linux qtdeploy -debug -ldflags= -tags= build linux /media/sf_GOPATH0/src/ex01" env= error="exec: \"docker\": executable file not found in $PATH" func=RunCmd name="deploy binary for linux on linux with docker"

The other way looks better :+1: qtdeploy test desktop
It makes a bunch of files...Not sure what it is used for X)
I get folders  like this :+1: 
root@decd5dc673fc:~/work/src/qtexample# ls
deploy	linux  main.go	qml  rcc.cpp  rcc.qrc  rcc_cgo_linux_linux_amd64.go
root@decd5dc673fc:~/work/src/qtexample# 

Which is nice... but nothing that I can actually run. (I ve tried some go run her and there...but nothing)

I think I am too dumb of a programmer to run this for now. Will try when there is something more straightforward... Go QT for dummies anyone ?

**Comment by 5k3105** [comment]
why use docker? why not just install to linux or windows directly?

**Comment by hubyhuby** [comment]
Dear @5k3105 ,
Thank you so much for following.
I am trying to try your QT library :) Therefore I am mostly looking for the easiest path to build my "hello QT / Go" program. Following your readme Install it says "Minimal Installation" which I translate into "easy kinda".

https://github.com/therecipe/qt/wiki/Installation
The very first step described is the Docker stuf.
There is no install path **explained**  without docker.

If there is an easy way, please please let me know. Point me to a "hello world qt". 

Thanks a lot
Yann

PS: if you go to get started it says you also have to do the "installation" page...
https://github.com/therecipe/qt/wiki/Getting-Started

**Comment by RadhiFadlillah** [comment]
@5k3105 there are some reasons we prefer using docker instead regular installation, for example :

- For some people, it might be easier to get started using docker image.
- Using docker make cross compiling to other platform really easy. For example, if you are using regular installation, to deploy from [Linux to Windows](https://github.com/therecipe/qt/wiki/Deploying-Linux-to-Windows-32-bit-Static) you need to install `mxe` first. In other hand, by using docker image you can simply run `qtdeploy -docker build windows_32_static`.

@hubyhuby I think you are missing some steps for installing this binding :

1. First of all, install docker to your system. If you are using Ubuntu, you can follow step 1-2 in this tutorial from [DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04). You might need to restart after installation finished.

2. Download docker image for your deployment target :

   ```
   docker pull therecipe/qt:linux
   ```

3. Install this binding by running :

   ```
   go get -u -v github.com/therecipe/qt/cmd/...
   ```

4. This step is optional, but if you want, you can run `qtsetup` in your terminal. This will compile and run some examples.

5. Now you can get started following the [wiki](https://github.com/therecipe/qt/wiki/Getting-Started).

**Comment by hubyhuby** [comment]
Dea @RadhiFadlillah ,
Thanks
I suppose you are missing a step?? 2.1 : "sudo docker run -it therecipe/qt:linux bash"
That s what I do to get a bash with this docker image... Also I know about nothing in Docker...
I did the go get with thr "..."  , also there is already the qt package in src... in this docker image
root@1d530d12593e:~/work/src/github.com/therecipe/qt# ls

Finally I try qtsetup which gives me pages of Errors :

INFO[0000] running: 'qtsetup prep'                      
INFO[0000] successfully created qtrcc symlink in your PATH (/usr/local/bin/qtrcc) 
INFO[0000] successfully created qtmoc symlink in your PATH (/usr/local/bin/qtmoc) 
INFO[0000] successfully created qtminimal symlink in your PATH (/usr/local/bin/qtminimal) 
INFO[0000] successfully created qtdeploy symlink in your PATH (/usr/local/bin/qtdeploy) 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.8.3'       
INFO[0000] GOROOT:                      '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/home/user/work' 
INFO[0000] GOBIN:                       '/home/user/work/bin' 
INFO[0000] QT_HASH:                     'a7d7d6588cc6988a4f93bda1c34a8f4f55cfd864' 
INFO[0000] QT_VERSION:                  '5.9.1'         
INFO[0000] QT_VERSION_MAJOR:            '5.9.1'         
INFO[0000] QT_DIR:                   *  '/opt/Qt5.8.0'  
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'ubuntu'        
INFO[0000] QT_PKG_CONFIG:               'false'         
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
ERRO[0000] failed to load /opt/Qt5.8.0/Docs/Qt-5.9.1/qtremoteobjects/qtremoteobjects.index  error="open /opt/Qt5.8.0/Docs/Qt-5.9.1/qtremoteobjects/qtremoteobjects.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=RemoteObjects
ERRO[0000] failed to load /opt/Qt5.8.0/Docs/Qt-5.9.1/qtcore/qtcore.index  error="open /opt/Qt5.8.0/Docs/Qt-5.9.1/qtcore/qtcore.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Core
ERRO[0000] failed to load /opt/Qt5.8.0/Docs/Qt-5.9.1/qtandroidextras/qtandroidextras.index  error="open /opt/Qt5.8.0/Docs/Qt-5.9.1/qtandroidextras/qtandroidextras.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=AndroidExtras
ERRO[0000] failed to load /opt/Qt5.8.0/Docs/Qt-5.9.1/qtlocation/qtlocation.index  error="open /opt/Qt5.8.0/Docs/Qt-5.9.1/qtlocation/qtlocation.index: no such file or direc

**Comment by RadhiFadlillah** [comment]
> I suppose we are missing a step? 2.1 : "sudo docker run -it therecipe/qt:linux bash"
That s what I do to get a bash with this docker image...

No @hubyhuby, I think that is where you are wrong. You must use the bash from your own system, not the bash from docker image. BTW, what is your operating system ?

**Comment by hubyhuby** [comment]
Dear @RadhiFadlillah ,
I did try it too...when I am in my own bash on Ubuntu MATE 17.04  after doing your go get, I run 

/projects/src/qtexample$ qtdeploy -docker test desktop
qtdeploy: command not found

OR
GE72-2QF:~/Documents/projects/src/qtexample$ qtdeploy
qtdeploy: command not found

OR
~/Documents/projects/src/qtexample$ qtsetup
qtsetup: command not found

At least when I am in the docker bash I get some life :) (living errors :) )

Thanks a lot

**Comment by RadhiFadlillah** [comment]
@hubyhuby those `command not found` might be caused by the `$GOROOT/bin` is not included in your `$PATH`.

I see that you installed `go` in `~/Documents/projects`. Have you set the `$GOROOT` and `$PATH` environment variables by following tutorial from [Golang.org](https://golang.org/doc/install#tarball) ?

Can you show me the result of these commands :

- `echo $GOROOT`
- `echo $PATH`
- `cat $HOME/.profile`

**Comment by hubyhuby** [comment]
@RadhiFadlillah 
Note that, All my other go projects compiles correctly (using go get) such a couchbase, UUID and others. 
The go get you gave me works correctly.

echo $GOROOT
/usr/lib/go-1.7
 
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin

cat $HOME/.profile
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

export GOPATH=/home/("ME")/Documents/projects
export GOROOT=/usr/lib/go-1.7

---------
echo $GOPATH
/home/(ME)/Documents/projects

**Comment by RadhiFadlillah** [comment]
Open your `$HOME/.profile` using `nano`, `gedit` or other text editor, then add following lines to the end of file :

```
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
```

Restart your system, then run `qtsetup` again. It should (hopefully) works.

**Comment by hubyhuby** [comment]
Hooray @RadhiFadlillah !
I have some life in my bash now , after modifying the profile .
The basic sample doesn t compile. Guess I am now entering the docker world ;)

qtdeploy -docker test desktop
ERRO[0000] failed to run command                         cmd="docker run --rm -e IDUG=1000:1000 -v /home/yann/Documents/projects:/media/sf_GOPATH0 -e GOPATH=/home/user/work:/media/sf_GOPATH0 -i therecipe/qt:linux qtdeploy -debug -ldflags= -tags= build linux /media/sf_GOPATH0/src/qtexample" env= error="exit status 125" func=RunCmd name="deploy binary for linux on linux with docker"
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.

This on my machine works :  sudo docker run hello-world
This doesnt : 
qtexample$ sudo qtdeploy -docker test desktop
sudo: qtdeploy: command not found

**Comment by hubyhuby** [comment]
HoorayX2  @RadhiFadlillah,
Got the "hello world" to work! So cool. Thanks for your help.
There was one thing disturbing me when you run " qtdeploy -docker test desktop"
You can type in the command line while it is compiling the thing....which made me thing it was bugging !!!
Could we put a little message "Deploying your project, please wait ..."

PS: I finally did a last thing, before it work...but am not 100% it help to make it work . But I post it here in case it could help someone :+1: 

sudo gpasswd -a $USER docker
newgrp docker
docker run hello-world
(this should run the docker hello world without SU privileges)

**Comment by hubyhuby** [comment]
I can confirme each time I reboot the deploy command doesn t work and I have to do :+1: 
sudo gpasswd -a $USER docker
newgrp docker
And then : qtdeploy -docker test desktop

I understand this must be an issue related to docker / install, but it may help other testing this lib ;)

**Comment by RadhiFadlillah** [comment]
@hubyhuby glad that it works for you.

To run `docker` without `sudo` privileges, you have to run following [commands](https://docs.docker.com/engine/installation/linux/linux-postinstall/#manage-docker-as-a-non-root-user) :

```
sudo groupadd docker
sudo usermod -aG docker $USER
```

After that, log out from your system, then log in again. Now you should be able to run `docker` without `sudo`.

> I can confirme each time I start a terminal, the deploy command doesn t work and I have to do :
> ...
> If I don t do so I get :
> ```
> qtdeploy -docker test desktop
> ERRO[0000] failed to run command cmd="docker run --rm -e IDUG=1000:1000 -v /home/yann/Documents/projects:/media/sf_GOPATH0 -e GOPATH=/home/user/work:/media/sf_GOPATH0 -i therecipe/qt:linux qtdeploy -debug -ldflags= -tags= build linux /media/sf_GOPATH0/src/golang.org/x/mobile/example/basic" env= error="exit status 125" func=RunCmd name="deploy binary for linux on linux with docker"
> docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
> See 'docker run --help'.
> ```

That error is happened because Docker hasn't been enabled on your system, which make it doesn't start on boot. To enable it, run following [commands](https://docs.docker.com/engine/installation/linux/linux-postinstall/#configure-docker-to-start-on-boot) :

```
sudo systemctl enable docker
sudo systemctl start docker
```

Now, you can check whether Docker is running or not by running :

```
systemctl status docker
```

If Docker has started succesfully, it will show something like this :

```docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-09-04 09:40:31 WIB; 2s ago
     Docs: https://docs.docker.com
 Main PID: 1840 (dockerd)
    Tasks: 20 (limit: 4915)
   Memory: 19.6M
      CPU: 321ms
   CGroup: /system.slice/docker.service
           ├─1840 /usr/bin/dockerd -H fd://
           └─1848 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-
```

**Comment by hubyhuby** [comment]
Dear @RadhiFadlillah ,
Everything is working perfectly now on my system, THANKS :)
Bottom line maybe, a "tips about docker " page would be usefull for people starting (also I understand this is not a place to learn docker). The two following tips you gave me , got it to work on my machine:
"
To enable it, run following commands :
sudo systemctl enable docker
sudo systemctl start docker
Now, you can check whether Docker is running or not by running :
systemctl status docker
"
+
"
Open your $HOME/.profile using nano, gedit or other text editor, then add following lines to the end of file :
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
Restart your system, then run qtsetup again. It should (hopefully) works.
"
