### ISSUE TITLE
link failed when import sqlite3

### ISSUE THREAD

**Issue by freboat** [therecipe/qt#438]
in any widget example,  import sqlite3, g++ link failed:
such as  therecipe/qt/internal/examples/widgets/video_player

```
package main
import (
	"fmt"
	"os"
	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/multimedia"
	"github.com/therecipe/qt/widgets"
        "database/sql"
	_ "github.com/mattn/go-sqlite3"          ////here import 
)

var (
	videoPlayer     *widgets.QWidget
	mediaPlayer     *multimedia.QMediaPlayer
	playButton      *widgets.QPushButton
	positionsSlider *widgets.QSlider
	errorLabel      *widgets.QLabel
        db *sql.DB                           ///add here let sqlite3 load
)
```

when deploy, it failed and  complain:
_/media/sf_GOPATH0/src/github.com/therecipe/qt/internal/examples/widgets/video_player
# _/media/sf_GOPATH0/src/github.com/therecipe/qt/internal/examples/widgets/video_player
/usr/local/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/bin/ld: /tmp/go-link-537664626/000003.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

------
my env:   ubuntu 64 16.04    minimal docker deploy style
it complile all widget examples smooth without sqlite3

**Comment by 5k3105** [comment]
did you try not using an underscore in front of the import?

**Comment by RadhiFadlillah** [comment]
@freboat in my Manjaro Linux it works without problem :

![sqlite3](https://user-images.githubusercontent.com/6129042/29993322-540f3d3a-8fde-11e7-8ea0-b1c54a58242a.gif)

**Comment by therecipe** [comment]
@freboat 
Just tested it on macOS and Manjaro with and without docker as well.
Maybe pull the latest linux image and then try again?

And/or maybe try to run "go clean -i github.com/mattn/go-sqlite3" first, it could be that the cached version of go-sqlite3 on your host system causes this.

**Comment by freboat** [comment]
thanks to @all 
the command "go clean -i github.com/mattn/go-sqlite3"  works
now my prj compiles success
