### ISSUE TITLE
Projects with a Makefile

### ISSUE THREAD

**Issue by muesli** [therecipe/qt#440]
I'm trying to use these bindings in a project which uses a `Makefile` as a wrapper for calling `go build` - out of convenience and to better deal with git submodules. Calling `qtdeploy build desktop` from the Makefile works and builds just fine, but afterwards my Makefile gets deleted. I guess it's used and overwritten in the process of deploying.

Could you generate and run those files in a separate build directory or try to pick an alternative Makefile names for qtdeploy, so these bindings don't tamper with regular project data?

Keep up the great work!

**Comment by therecipe** [comment]
Oops, should be fixed now with: https://github.com/therecipe/qt/commit/ddaa55df8d2bd7690f8eec56763d7a6b9222bf43

The problem was related to the internal use of qmake by qtrcc, qtmoc and qtdeploy.

**Comment by muesli** [comment]
Updating & testing right now...
