### ISSUE TITLE
how can display Chinese 

### ISSUE THREAD

**Issue by freboat** [therecipe/qt#452]
```
textBrowser := widgets.NewQTextBrowser(nil)
textBrowser.SetWindowTitle("Text Browser")

textBrowser.SetText("This Is A Text Browser 测试中文")     //how to set the right lang codec
fmt.Println("This Is A Text Browser 测试中文")
```
it cannot display Chinese in the textbrowser,  but golang println to  stdout ok

**Comment by hello-code** [comment]
```
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {
	app := widgets.NewQApplication(len(os.Args), os.Args)

	// main window
	window := widgets.NewQMainWindow(nil, 0)
	window.SetWindowTitle("Hello QT")
	window.SetMinimumSize2(200, 200)

	// layout
	layout := widgets.NewQVBoxLayout()

	//main widgets
	mainWidget := widgets.NewQWidget(nil, 0)
	mainWidget.SetLayout(layout)

	textBrowser := widgets.NewQTextBrowser(nil)
	textBrowser.SetWindowTitle("text browser...")
	textBrowser.SetText("Hello 世界")
	layout.AddWidget(textBrowser, 0, 0)
	fmt.Println("This is a test 世界.")

	window.SetCentralWidget(mainWidget)

	// show
	window.Show()
	app.Exec()
}

```

![screenshot_2017-09-14_14-20-43](https://user-images.githubusercontent.com/7741586/30414869-316adf36-9958-11e7-93b6-69bd219c95cd.png)


![screenshot_2017-09-14_14-23-00](https://user-images.githubusercontent.com/7741586/30414922-4a828afa-9958-11e7-8504-c422f0e453c4.png)

**Comment by freboat** [comment]
can  you  tell me  the lang  codec of your source code file,

my souce code file  uses utf-8, and  textBrowser can not display Chinese

**Comment by hello-code** [comment]
```
$ file main.go
main.go: C source, UTF-8 Unicode text
```

**Comment by therecipe** [comment]
@freboat 
Just tested hello-code's code on macOS and Arch Linux and it seems to work.

**Comment by freboat** [comment]
@therecipe 
i  run  the  therecipe'Qt  DOCKER  on ubuntu 1604
it must be  5.9.0.

the system's default lang codec  is  en-utf8,  so is the  src' file.

**Comment by therecipe** [comment]
Mh, I successfully tested it on a completly clean ubuntu 16.04 `4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` box.

I used the latest docker linux image to build the example from above: `c1d35e8eac85`

Can you maybe provide some error log, or some more infos (a screenshot or something) that shows the issue?

**Comment by freboat** [comment]
@therecipe , my docker  version show that:
brook@ubuntu16:~$ docker history 847
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
8473b4090aa0        6 weeks ago         /bin/sh -c $GOPATH/bin/qtsetup install linux    475.4 MB            
<missing>           6 weeks ago         /bin/sh -c $GOPATH/bin/qtsetup generate linux   37.52 MB            
<missing>           6 weeks ago         /bin/sh -c $GOPATH/bin/qtsetup check linux      0 B                 
<missing>           6 weeks ago         /bin/sh -c $GOPATH/bin/qtsetup prep linux       107 B               
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV QT_DIR=/opt/Qt5.8.0      0 B                 
<missing>           6 weeks ago         /bin/sh -c curl -sL --retry 10 --retry-delay    1.373 GB            
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV QT_QPA_PLATFORM=minima   0 B                 
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV QT=qt-opensource-linux   0 B                 
<missing>           6 weeks ago         /bin/sh -c rm -r /home/user/work/pkg/linux_am   0 B                 
<missing>           6 weeks ago         /bin/sh -c rm -r /home/user/work/src/github.c   0 B                 
<missing>           6 weeks ago         /bin/sh -c go get -v github.com/therecipe/qt/   623.7 MB            
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV GOPATH=/home/user/work   0 B                 
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PATH=/usr/local/sbin:/   0 B                 
<missing>           6 weeks ago         /bin/sh -c curl -sL --retry 10 --retry-delay    268.9 MB            
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV GO=go1.8.3.linux-amd64   0 B                 
<missing>           6 weeks ago         /bin/sh -c rm -f /usr/bin/g++; sudo ln -s /us   14 B                
<missing>           6 weeks ago         /bin/sh -c rm -f /usr/bin/gcc; sudo ln -s /us   14 B                
<missing>           6 weeks ago         /bin/sh -c add-apt-repository -y ppa:ubuntu-t   123.1 MB            
<missing>           6 weeks ago         /bin/sh -c apt-get -qq update && apt-get -y -   81.29 MB            
<missing>           6 weeks ago         /bin/sh -c apt-get -qq update && apt-get -y -   225.2 MB            
<missing>           6 weeks ago         /bin/sh -c apt-get -qq update && apt-get -y -   179.3 MB            
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV QT_DOCKER=true           0 B                 
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV HOME=/home/user          0 B                 
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV USER=user                0 B                 
<missing>           6 weeks ago         /bin/sh -c #(nop)  LABEL maintainer=therecipe   0 B                 
<missing>           9 weeks ago         /bin/sh -c #(nop)  CMD ["/bin/bash"]            0 B                 
<missing>           9 weeks ago         /bin/sh -c mkdir -p /run/systemd && echo 'doc   7 B                 
<missing>           9 weeks ago         /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.895 kB            
<missing>           9 weeks ago         /bin/sh -c rm -rf /var/lib/apt/lists/*          0 B                 
<missing>           9 weeks ago         /bin/sh -c set -xe   && echo '#!/bin/sh' > /u   194.6 kB            
<missing>           9 weeks ago         /bin/sh -c #(nop) ADD file:345f29394c5b185989   187.8 MB

**Comment by freboat** [comment]
@therecipe 

is there a way  to get into the compiling container  to debug,

maybe when the docker start,  mount the local src file dir without right lang codec ?

**Comment by freboat** [comment]
![screenshot_2017-09-24_10-52-03](https://user-images.githubusercontent.com/21974735/30779035-c7227c46-a0d3-11e7-8d51-af63b3effba1.png)

**Comment by freboat** [comment]
i update go to 1.9.0, and pull docker img:   c1d35e8eac85

and compile,  they doesn't work with Chinese  neither.   :(

**Comment by rashwell** [comment]
I know this might be out in left field, but it appears to me that the fonts are different @freboat your default font that your textbrowser is using might not have the chinese chars.  If that turns out to be the case you can set the font for the document.  You can also if you have either embedded a font with QFontDatabase class stuff or if you know your system has a font installed already that will support this, you can SetFontFamily, SetCurrentFont, SetCurrentFontDefault on the textbrowser.

**Comment by freboat** [comment]
@rashwell 
thks for your hint,   i  apt-get install the WQY Cjk  fonts and set it default

now it works

thanks to @all
