### ISSUE TITLE
Using system QT

### ISSUE THREAD

**Issue by Kutabe** [therecipe/qt#453]
Is there any way to make qtsetup work with system installed QT?
What I mean is, I use Arch Linux and I'm trying to make a PKGBUILD for qt: qt bindings for go (Golang).
So qtsetup acts like ./configure and make, but it wants an odd file structure. It wants Docs to be installed in $QT_DIR/Docs/QT-$QT_VERSION/ when it's located in /usr/share/doc/qt/ and it wants qmake to be located in $QT_DIR/QT-$QT_VERSION/gcc_64/bin/qmake when I have it in my /usr/bin/. Is there a simple, elegant way to make use of system installed QT without some bizarre methods that came to my mind like symlinking all these files into a friendly file structure? I know QT Creator can do this: it detects all my QT versions, no matter how the file structure is organized. It can detect my system QT installation and my android-qt5 installation located in /opt/android-qt5/${android_arch} and the QT versions that were installed using QT Installer. Why can't qtsetup be this way?

**Comment by willeponken** [comment]
Hello,

Have you read: https://github.com/therecipe/qt/wiki/Installation-on-Linux#package-manager?
By using the `QT_PKG_CONFIG=true` environment variable `qtsetup` should use your systems version of Qt.
