### ISSUE TITLE
gui and widget packages are invisible

### ISSUE THREAD

**Issue by wuzzapcom** [therecipe/qt#454]
I am unable to create new window via function gui.NewQGuiApplication() or widgets.NewQApplication(), because packages gui and widgets are invisible. Goglang says, that ".../github.com/therecipe/qt/gui has no buildable Go source files"
I use go 1.9, macOS.

**Comment by therecipe** [comment]
Hey

You probably need to increase the memsize of the Java VM to get those working: https://github.com/therecipe/qt/wiki/FAQ#how-to-make-ides-code-completion-works-
