### ISSUE TITLE
Bluetooth Issue

### ISSUE THREAD

**Issue by minhajakhterkhan199** [therecipe/qt#459]
Trying to work with Bluetooth but bluetooth.QBluetoothLocalDevice{} IsValid() always return false. 
Host Machine Ubuntu: 16.04 and Bluetooth is working well on Host Machine. 
Please advise 
```
	bthLocalDevice := bluetooth.QBluetoothLocalDevice{}
	if bthLocalDevice.IsValid() {
		log.Println("Bluetooth Device is Valid")
	}else {
		log.Println("Bluetooth Device is Invalid")
	}
```

**Comment by therecipe** [comment]
Hey

You will need to use `bluetooth.NewQBluetoothLocalDevice` or `bluetooth.NewQBluetoothLocalDevice2` instead of `bluetooth.QBluetoothLocalDevice{}`.

**Comment by minhajakhterkhan199** [comment]
kindly give me reference / tutorial or example... In addition, please share GO-QT documentation link as well

**Comment by therecipe** [comment]
Here, you can find all necessary infos in the c++ docs:
http://doc.qt.io/qt-5/qbluetoothlocaldevice.html#QBluetoothLocalDevice

There are no ported Go bluethooth examples yet, but you could try to port one of these: 
http://doc.qt.io/qt-5/bluetooth-examples.html

**Comment by minhajakhterkhan199** [comment]
I am unable to discover any Bluetooth devices... Please advise what is wrong in below code
```
bthLocalDevice := bluetooth.NewQBluetoothLocalDevice(nil)

	//log.Println(bthLocalDevice.Name()+ " "+ adapterAddress.ToString())
	//
	if bthLocalDevice.IsValid() {
		log.Println("Name: "+bthLocalDevice.Name()+ "address" +bthLocalDevice.Address().ToString() )
		
		bthLocalDevice.PowerOn()
		disvoveryAgent := bluetooth.NewQBluetoothDeviceDiscoveryAgent(nil)
		disvoveryAgent.SetInquiryType(bluetooth.QBluetoothDeviceDiscoveryAgent__GeneralUnlimitedInquiry)
		disvoveryAgent.Start()
		time.Sleep(1000)

		disvoveryAgent.DeviceDiscovered(bluetooth.NewQBluetoothDeviceInfo())
		qBluetoothDeviceInfoList := disvoveryAgent.DiscoveredDevices()

		for _,qBluetoothDeviceInfo:=range qBluetoothDeviceInfoList{
			log.Println(qBluetoothDeviceInfo.Name() + " : "+qBluetoothDeviceInfo.Address().ToString())
		}


		disvoveryAgent.Stop()


	}else {
		log.Println("Bluetooth Device is Invalid")
	}
```

**Comment by therecipe** [comment]
Mh, I'm not sure.
I will try to port the bluetooth scanner example tomorrow.

**Comment by minhajakhterkhan199** [comment]
Waiting for your response

**Comment by minhajakhterkhan199** [comment]
@therecipe Waiting for your response regarding scanner example..

**Comment by minhajakhterkhan199** [comment]
@therecipe Still waiting for your response... Kindly give some time to fix this issue...

**Comment by minhajakhterkhan199** [comment]
Is this project dead? @therecipe

**Comment by therecipe** [comment]
I ported a few examples, you can find them [here](https://github.com/therecipe/qt/tree/master/internal/examples/bluetooth) now.

**Comment by josephcenk** [comment]
@therecipe Kindly accelerate,
