### ISSUE TITLE
What would be the right way to build an application using ubuntu 16.04 default qt5?

### ISSUE THREAD

**Issue by zerkms** [therecipe/qt#468]
I've taken an example application from the https://github.com/therecipe/qt/wiki/Getting-Started

And when I try to build it specifying the path to Qt5 headers explicitly it still cannot find it:

```
$ CGO_CFLAGS=-I/usr/include/x86_64-linux-gnu/qt5/QtCore go build main.go
# github.com/therecipe/qt/core
core.cpp:9:30: fatal error: QAbstractAnimation: No such file or directory
compilation terminated.
```

But the header file is there

```
$ ls -la /usr/include/x86_64-linux-gnu/qt5/QtCore/QAbstractAnimation
-rw-r--r-- 1 root root 32 Oct 13  2015 /usr/include/x86_64-linux-gnu/qt5/QtCore/QAbstractAnimation
```

How would I build it?

**Comment by zerkms** [comment]
I see, I should have run `qtdeploy test desktop`

**Comment by zerkms** [comment]
Well, I'm still stuck: is it even possible to use this binding and default ubuntu xenial qt5 (not install the qt5 additionally or via docker)?

**Comment by zerkms** [comment]
The closest I could reach is
```
CPATH="/usr/include/x86_64-linux-gnu/qt5/QtCore:/usr/include/x86_64-linux-gnu/qt5:/usr/include/x86_64-linux-gnu/qt5/QtMultimedia:/usr/include/x86_64-linux-gnu/qt5/QtGui:/usr/include/x86_64-linux-gnu/qt5/QtDBus" go build main.go
```

but then it fails on `QDeadlineTimer` which was added in qt 5.9 and the default ubuntu xenial is 5.5.1

**Comment by therecipe** [comment]
@zerkms Sorry, the minimal supported Qt version is 5.6 at the moment.
