### ISSUE TITLE
qprocess example?

### ISSUE THREAD

**Issue by ReK2Fernandez** [therecipe/qt#474]
@therecipe I am trying to get the output of a system command on linux, on the C++ QT doc it shows how to do this with qprocess, but I can't find any example with GO+QT... is this implemented? if so can I have a small example? if not, how I can go about getting the raw GO way to open a system app let's say "ls" and redirect the output to a NewQTextEdit() ?

Thanks.

**Comment by ChrisFernandez** [comment]
knock knock... just need a yes or no is not supported, im stuck in the middle of a proyect waiting to see what way I go. thanks.

**Comment by rashwell** [comment]
Ok, here I found a c++ version of a small example of what you are asking.  [QProcess Example](https://gist.github.com/ynonp/8148340)  

> However, looking into the source of the bindings it appears that the bindings for the QProcess stuff are not yet in a supported, or completed state.  It is possible to create a QProcess object with something like this in go:

```go
qio := core.NewQIODevice()	
qprocess := core.NewQProcessFromPointer(qio.Pointer())
```

But I expect when / if QProcess is fully supported that there will instead exist a core.NewQProcess() which isn't there yet, so you end up missing methods like in the example were you would do qprocess.Start("").  And [here](https://github.com/therecipe/qt/blob/master/internal/binding/parser/class.go#L256) it looks like @therecipe has QProcess and QProcessEnvironment marked as unsuported.

**Comment by CaninoDev** [comment]
Is QProcess now supported? I couldn't find a NewQProcess method in the source code.

**Comment by therecipe** [comment]
Sorry, I was quite busy in late 2017 and seem to have never come back to the issues raised in that period.
But I added support for `QProcess` and `QProcessEnvironment` with  https://github.com/therecipe/qt/commit/73192f6811d0cea6b42a4be130e1a6ac07e7a8b8 now.

Now something like this should work:

```go
package main

import (
	"encoding/hex"
	"github.com/therecipe/qt/core"
)

func main() {

	gzip := core.NewQProcess(nil)
	gzip.Start("gzip", []string{"-c"}, core.QIODevice__ReadWrite)
	if !gzip.WaitForStarted(30000) {
		return
	}

	gzip.Write2("Qt rocks!")
	gzip.CloseWriteChannel()

	if !gzip.WaitForFinished(30000) {
		return
	}

	result := gzip.ReadAll()
	println(hex.EncodeToString([]byte(result.ConstData())))

	//

	gunzip := core.NewQProcess(nil)
	gunzip.Start("gunzip", []string{"-c"}, core.QIODevice__ReadWrite)
	if !gunzip.WaitForStarted(30000) {
		return
	}

	gunzip.Write3(result)
	gunzip.CloseWriteChannel()

	if !gunzip.WaitForFinished(30000) {
		return
	}

	result = gunzip.ReadAll()
	println(result.ConstData())
}
```

**Comment by CaninoDev** [comment]
Does core.NewQProcess  exist any more? I can't find it in the source code. (Perhaps I am running off of an old version?)

**Comment by therecipe** [comment]
@CaninoDev It should be there (it's not available for iOS though)

```go
% go doc github.com/therecipe/qt/core QProcess

type QProcess struct {
	QIODevice
}

func NewQProcess(parent QObject_ITF) *QProcess
func NewQProcessFromPointer(ptr unsafe.Pointer) (n *QProcess)
func (ptr *QProcess) Arguments() []string
func (ptr *QProcess) CloseReadChannel(channel QProcess__ProcessChannel)
func (ptr *QProcess) CloseWriteChannel()
func (ptr *QProcess) ConnectDestroyQProcess(f func())
func (ptr *QProcess) ConnectErrorOccurred(f func(error QProcess__ProcessError))
...
```

Which Qt version do you use?
