### ISSUE TITLE
http://doc.qt.io/qt-5/qvalidator.html

### ISSUE THREAD

**Issue by ReK2Fernandez** [therecipe/qt#477]
Is Qvalidator ported?

**Comment by rashwell** [comment]
@ChrisFernandez I use validators, and the [Line Edits Example](https://github.com/therecipe/qt/blob/master/internal/examples/widgets/line_edits/line_edits.go) in this repo, shows a small example of appling different validators to fields, etc. So I think short answer to your question, yes it is included in the bindings.

**Comment by ChrisFernandez** [comment]
thanks! I will take a look in the mean time I have used govalidator it was for URL/IP entry
