### ISSUE TITLE
Can I create a fully static binary?

### ISSUE THREAD

**Issue by rucuriousyet** [therecipe/qt#486]
I'm wondering if there's any way to compile my application to include the required Qt libraries in the binary (primarily for linux but would be good to know about the other OSs as well) allowing for deployments of only a single binary with no deps? When trying to run a compiled binary on another linux system I get errors for missing shared libraries, this is the problem I am trying to avoid.

**Comment by thesyncim** [comment]
yes,
https://github.com/therecipe/qt/wiki/Deploying-Linux-to-Windows-64-bit-Static

**Comment by rucuriousyet** [comment]
Actually.. I'm interested in creating a static binary for Linux from Linux.
I found the page for the windows stuff.

-sent from my OnePlus X

**Comment by GeertJohan** [comment]
Have you tried this already?
http://blog.wrouesnel.com/articles/Totally%20static%20Go%20builds/

**Comment by rucuriousyet** [comment]
I haven't yet, looks promising though

-sent from my OnePlus X

**Comment by rucuriousyet** [comment]
I wonder how well this would work for cross compiling qt....

-sent from my OnePlus X

**Comment by 5k3105** [comment]
I've used the instructions here for static builds on windows successfully:
https://github.com/therecipe/qt/wiki/Installation-on-Windows

**Comment by therecipe** [comment]
@rucuriousyet
You will need to create a static version of Qt first: http://doc.qt.io/qt-5/linux-deployment.html#building-qt-statically
Then you need to change the QT_DIR env variable to point to your static build and re-run the setup.
