### ISSUE TITLE
Examples hidpi scaling not working on windows

### ISSUE THREAD

**Issue by tarb** [therecipe/qt#489]
A lot of the examples ([including  the qml getting started snippet](https://github.com/therecipe/qt/wiki/Getting-Started#user-content-qml)) dont have correct hidpi scaling on windows (and maybe linux). 

~~~~go
// the qml example from getting started

func main() {
        // Create application
        app := gui.NewQGuiApplication(len(os.Args), os.Args)
    
        // Enable high DPI scaling
        app.SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
        ...
~~~~

It looks as if `app.SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)` does nothing as I was free to comment it out without any change to output. [From some googling](https://stackoverflow.com/a/36057995) it appears this attribute has to be set before the apps creation to have any effect and the below change seems to fix it for me.

~~~~go
func main() {
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
	// Create application
        gui.NewQGuiApplication(len(os.Args), os.Args)

	// Enable high DPI scaling
	// app.SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
        ...
~~~~

As I'm about 2 hours into qt, someone way more experienced may want to investigate further.

**Comment by therecipe** [comment]
@tarb Yes, you are right the attribute needs to be set before creating the application.
I fixed the example with https://github.com/therecipe/qt/commit/d0f4fa9f44a99390acaa7b7b9d32c7f65a95952b and will also fix the wiki.
Thanks for the heads up.
