### ISSUE TITLE
please help to make working qml application

### ISSUE THREAD

**Issue by xenamorph** [therecipe/qt#49]
I copy qml example from https://github.com/therecipe/qt/tree/master/internal/examples/qml/application
to d:\gosrc\src\qtQml  (gopath d:\gosrc\src\)

d:\gosrc\src\qtQml>dir

 Том в устройстве D имеет метку Black
 Серийный номер тома: EE89-CC7D

 Содержимое папки d:\gosrc\src\qtQml

11.08.2016  16:20    <DIR>          .
11.08.2016  16:20    <DIR>          ..
11.08.2016  15:23               343 application.go
11.08.2016  15:24    <DIR>          qml
               1 файлов            343 байт
               4 папок  609 981 190 144 байт свободно

run d:\gosrc\src>qtdeploy build desktop qtQml

d:\gosrc\src\qtQml\deploy\windows>dir

 Том в устройстве D имеет метку Black
 Серийный номер тома: EE89-CC7D

 Содержимое папки d:\gosrc\src\qtQml\deploy\windows

11.08.2016  16:20    <DIR>          .
11.08.2016  16:20    <DIR>          ..
11.08.2016  16:20    <DIR>          bearer
01.07.2016  06:23         3 695 104 D3Dcompiler_47.dll
11.08.2016  16:20    <DIR>          iconengines
11.08.2016  16:20    <DIR>          imageformats
10.06.2016  10:16            22 016 libEGL.dll
29.12.2015  01:25           120 334 libgcc_s_dw2-1.dll
10.06.2016  10:16         2 801 664 libGLESV2.dll
29.12.2015  01:25         1 540 622 libstdc++-6.dll
29.12.2015  01:25            79 360 libwinpthread-1.dll
23.09.2014  13:36        15 220 736 opengl32sw.dll
11.08.2016  16:20    <DIR>          platforms
11.08.2016  16:20    <DIR>          private
11.08.2016  16:20    <DIR>          qmltooling
11.08.2016  16:20         5 384 704 Qt5Core.dll
10.06.2016  10:23         5 283 840 Qt5Gui.dll
10.06.2016  10:17         1 610 240 Qt5Network.dll
11.06.2016  15:22         3 924 480 Qt5Qml.dll
11.06.2016  15:35         3 771 904 Qt5Quick.dll
10.06.2016  20:51           348 160 Qt5Svg.dll
10.06.2016  10:29         6 358 528 Qt5Widgets.dll
11.08.2016  16:20    <DIR>          QtGraphicalEffects
11.08.2016  16:20    <DIR>          QtQml
11.08.2016  16:20        19 206 656 qtQml.exe
11.08.2016  16:20    <DIR>          QtQuick
11.08.2016  16:20    <DIR>          QtQuick.2
11.08.2016  16:20    <DIR>          translations
              15 файлов     69 368 348 байт
              13 папок  609 981 190 144 байт свободно

try to run qtQml.exe and get a blank screen, no error messages

**Comment by therecipe** [comment]
Hey

What Go version do you use?
Do you have another mingw / visual studio installation on you system?
Did the examples work for you during the installation? (setup.bat)
Do the widget examples work for you?

**Comment by xenamorph** [comment]
all examples work fine
minigw 64 and 32 installed, system path only to C:\Qt\Qt5.7.0\Tools\mingw530_32\bin
visual studio 2015
go version go1.6.2 windows/amd64

**Comment by therecipe** [comment]
Oh, I totally forgot that the `qml/application` example doesn't work on windows somehow (it works everywhere else through).

You're better of if you try the `quick/calc` example (or the other quick examples).

If you want to use the `QQmlApplicationEngine` (like in the `qml/application` example instead of the `QQuickView`, you need to wrap the top Rectangle in the `calc.qml` inside a `ApplicationWindow`

```qml 
import QtQuick.Controls 1.2

ApplicationWindow
{
    visible: true

    Rectangle
    {
        id: window
        ...
    }
}
```

**Comment by xenamorph** [comment]
thank you very much for your work
