### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by nilsocket** [therecipe/qt#491]
I have installed this and I got so many errors while installing, I have qt 5.9.2.
It seems this is specifically made for 5.8, It's working now but I got some errors.
qtsetup takes lot of time to run, why can't that make use of other cores.

**Comment by bclermont** [comment]
5.9.1 works for me

and sure, qtsetup takes a lot of time, it need to generate tons of C++ files and generate golang code. and build them.

blame your local C++ toolchains for that

**Comment by therecipe** [comment]
@nilsocket No it's not dead, I was just quite busy with some other stuff. And yeah the setup takes some time, but I will try to work around this with prebuilt libraries in the future.
