### ISSUE TITLE
qtseup issue Qt 5.6.1 golang 1.9.1 Centos 6

### ISSUE THREAD

**Issue by tedx** [therecipe/qt#494]
I've installed:
qt5-qtbase-devel-5.6.1-3.el6.x86_64
qt5-qtbase-5.6.1-3.el6.x86_64
qt5-qtbase-gui-5.6.1-3.el6.x86_64
qt5-qtbase-common-5.6.1-3.el6.noarch
qt5-rpm-macros-5.6.1-3.el6.noarch
 
ran:
go get -u -v github.com/therecipe/qt/cmd/...

exported:
QT_PKG_CONFIG=true

to my environment and then ran:
gocode/bin/qtsetup

which fails see below. Where does core.pro come from? Is is supposed to be generated? 

time="2017-11-22T16:05:13-06:00" level=info msg="running: 'qtsetup prep'"
time="2017-11-22T16:05:13-06:00" level=warning msg="failed to create qtrcc symlink in your PATH (/usr/lib/golang/bin/qtrcc); please use /home/tedx/gocode/bin/qtrcc instead"
time="2017-11-22T16:05:13-06:00" level=warning msg="failed to create qtmoc symlink in your PATH (/usr/lib/golang/bin/qtmoc); please use /home/tedx/gocode/bin/qtmoc instead"
time="2017-11-22T16:05:13-06:00" level=warning msg="failed to create qtminimal symlink in your PATH (/usr/lib/golang/bin/qtminimal); please use /home/tedx/gocode/bin/qtminimal instead"
time="2017-11-22T16:05:13-06:00" level=warning msg="failed to create qtdeploy symlink in your PATH (/usr/lib/golang/bin/qtdeploy); please use /home/tedx/gocode/bin/qtdeploy instead"
time="2017-11-22T16:05:13-06:00" level=info msg="running: 'qtsetup check linux' [docker=false] [vagrant=false]"
time="2017-11-22T16:05:13-06:00" level=info msg="GOOS:                        'linux'"
time="2017-11-22T16:05:13-06:00" level=info msg="GOARCH:                      'amd64'"
time="2017-11-22T16:05:13-06:00" level=info msg="GOVERSION:                   'go1.9.1'"
time="2017-11-22T16:05:13-06:00" level=info msg="GOROOT:                      '/usr/lib/golang'"
time="2017-11-22T16:05:13-06:00" level=info msg="GOPATH:                   *  '/home/tedx/gocode'"
time="2017-11-22T16:05:13-06:00" level=info msg="GOBIN:                       '/home/tedx/gocode/bin'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_HASH:                     '599f8bc2c975802ea592c43d110209f0a267b188'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_VERSION:                  '5.6.1'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_VERSION_MAJOR:            '5.6'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_DIR:                      '/home/tedx/Qt5.6.1'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_STUB:                     'false'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_DEBUG:                    'false'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_QMAKE_DIR:                ''"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_WEBKIT:                   'false'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_DISTRO:                   'fedora'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_PKG_CONFIG:            *  'true'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_DOC_DIR:                  '/usr/share/doc/qt5'"
time="2017-11-22T16:05:13-06:00" level=info msg="QT_MISC_DIR:                 '/usr/lib64/qt5'"
time="2017-11-22T16:05:13-06:00" level=info msg="running: 'qtsetup generate linux' [docker=false] [vagrant=false]"
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=WebView
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=DBus
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Quick
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Multimedia
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Network
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Help
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Gui
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Bluetooth
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Qml
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Sql
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=XmlPatterns
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Location
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=WebChannel
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Xml
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Core
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Sensors
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Positioning
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Svg
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=ScriptTools
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=WebSockets
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=AndroidExtras
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Widgets
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Nfc
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Script
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=UiTools
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=SerialPort
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Designer
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Scxml
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=SerialBus
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=PrintSupport
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=QuickControls2
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=WebEngine
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=Gamepad
time="2017-11-22T16:05:13-06:00" level=warning msg=parser.LoadModule error=EOF module=TestLib
time="2017-11-22T16:05:13-06:00" level=info msg="generating full qt/core"
time="2017-11-22T16:05:13-06:00" level=error msg="failed to run command" cmd="/usr/lib64/qt5/bin/qmake -o Mfile /home/tedx/gocode/src/github.com/therecipe/qt/core.pro -spec linux-g++ CONFIG+=release" env= error="exit status 3" func=RunCmdOptional name="run qmake for linux on linux"
Project ERROR: Unknown module(s) in QT: svg

time="2017-11-22T16:05:13-06:00" level=error msg="failed to load /home/tedx/gocode/src/github.com/therecipe/qt/core/Mfile" error="open /home/tedx/gocode/src/github.com/therecipe/qt/core/Mfile: no such file or directory"

**Comment by justinclift** [comment]
It seems to be complaining that the Qt installation doesn't include the SVG module.

Maybe if you try with the Qt installer version (eg from qt.io), instead of the CentOS 6 provided libraries?  In theory :wink:, that should include all of the required bits. :smile:

**Comment by therecipe** [comment]
@tedx Can this be closed? You probably just needed to install the svg lib.
