### ISSUE TITLE
Legal way to create closed source app?

### ISSUE THREAD

**Issue by jamalsa** [therecipe/qt#495]
Currently this binding doesnt have commercial license so [it is impossible to create closed source app](https://github.com/therecipe/qt/wiki/FAQ#can-i-make-a-proprietary-app-with-this-binding-). For temporary solution I wonder if we can use binary only package to create closed source app legally.

Say we have an application. This application splitted into two packages, core and gui. Only the gui part use this qt package. If we provide source for gui but only binary package for core, will it comply LGPL restrictions?

Please share your thought about this

**Comment by cyphar** [comment]
Consult with a lawyer, don't ask random strangers on the internet for legal advice.

**Comment by therecipe** [comment]
@jamalsa Yes, afaik this should work.

**Comment by jamalsa** [comment]
Thanks @therecipe, will try this. I hope you can release commercial license as soon as possible because I would love to support this great library :)
