### ISSUE TITLE
webview demo do not work

### ISSUE THREAD

**Issue by yyyyykkkk** [therecipe/qt#498]
'/github.com/therecipe/qt/internal/examples/webchannel/webview ' this demo can not do work !
shared.NewWebSocketClientWrapper(nil) has no method!!
please ,provide a working example.

**Comment by bclermont** [comment]
it works for me.

you provided no informations to troubleshoot the problem:

- no QT version
- no operating system it's running on
- no go version

nothing

**Comment by xjz9600** [comment]
![image](https://user-images.githubusercontent.com/25845262/33211180-4cb615de-d158-11e7-9640-f7ff1895f63f.png)
I have same problem

**Comment by yyyyykkkk** [comment]
go version go1.8.3 darwin/amd64

qt version 5.9.2

**Comment by xjz9600** [comment]
![image](https://user-images.githubusercontent.com/25845262/33212161-c7374658-d15c-11e7-810c-82aa1d4ada37.png)

**Comment by xjz9600** [comment]
![image](https://user-images.githubusercontent.com/25845262/33212234-0a68fe08-d15d-11e7-967f-08d8a1edcca9.png)

**Comment by xjz9600** [comment]
but i get an error 
![image](https://user-images.githubusercontent.com/25845262/33212266-3131dece-d15d-11e7-8bce-5fb05c104c39.png)

**Comment by bclermont** [comment]
look like you didn't ran `qtsetup` first

**Comment by therecipe** [comment]
@yyyyykkkk @xjz9600 Did you ran "qsetup" first? Can this be closed?
