### ISSUE TITLE
missing libpcre2-16-0.dll

### ISSUE THREAD

**Issue by Requaos** [therecipe/qt#499]
`qtdeploy build windows` does not copy in a required library... I was testing my .msi installation file and the `libpcre2-16-0.dll` library was missing from the deployment folder

**workaround:** copy the library in from `msys/mingw64/bin` before running the .msi packager

**Comment by therecipe** [comment]
Hey

This should have been fixed with: https://github.com/therecipe/qt/commit/ecde93482da5275d432beef50d96b866c081ba8b#diff-16e44658fb89a392fbb49ad74fdc4570R227
