### ISSUE TITLE
Fatal error: QTextDocument: No such file or directory

### ISSUE THREAD

**Issue by blowin** [therecipe/qt#505]
`package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/qml"
	"github.com/therecipe/qt/quickcontrols2"
)

func main() {
	// Create application
	app := gui.NewQGuiApplication(len(os.Args), os.Args)

	// Enable high DPI scaling
	app.SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)

	// Use the material style for qml
	quickcontrols2.QQuickStyle_SetStyle("material")

	// Create a QML application engine
	engine := qml.NewQQmlApplicationEngine(nil)

	// Load the main qml file
	engine.Load(core.NewQUrl3("qrc:/qml/main.qml", 0))

	// Execute app
	gui.QGuiApplication_Exec()
}`

installed version of qt 5.8
i make qtsetup

the contents of the qt5.8 folder and the environment variables:
![variable](https://user-images.githubusercontent.com/22686801/33591029-11cb6b88-d994-11e7-9d44-4e7d9cf59c61.jpg)
![default](https://user-images.githubusercontent.com/22686801/33591031-11f2ec76-d994-11e7-924a-fd8a90a28efa.jpg)

**Comment by gauravagnihotri** [comment]
See https://github.com/therecipe/qt/issues/492
I think your QT_DIR should be 'E:\program\Qt'

**Comment by therecipe** [comment]
Hey

Yeah, https://github.com/therecipe/qt/issues/505#issuecomment-355216048 should fix this.
