### ISSUE TITLE
On darwin Qml Map & geoservices plugins are not deployed correctly

### ISSUE THREAD

**Issue by akhenakh** [therecipe/qt#506]
When building an app which includes `QtLocation` the `xx.app/Contents/Plugins/geoservices` is not copied nor dylib relinked with the appropriate path.

**Comment by therecipe** [comment]
Hey

Could this be related to [this](https://bugreports.qt.io/browse/QTBUG-50805) issue?
Otherwise, do you import the "github.com/therecipe/qt/location" package in your code?
And do you make use of the location package through Go or through QML?

**Comment by akhenakh** [comment]
It looks like the same issue yep.

I'm using it via QML only.

**Comment by akhenakh** [comment]
Tested, it's fixed now !
