### ISSUE TITLE
Can not work with gocode

### ISSUE THREAD

**Issue by fcying** [therecipe/qt#51]
```go
var window = widgets.NewQMainWindow(nil, 0)
window.
```
When I  type '.', it will be block a long time, without any prompt

my platform:
win10x64
qt-opensource-windows-x86-mingw530-5.7.0.exe
golang 1.7.1 amd64

**Comment by therecipe** [comment]
Hey

Did you ran the setup.bat?
Which editor do you use (atom, liteide, vs)?
Do the other packages such as core or gui work?

**Comment by 5k3105** [comment]
Hi,

I have the same issues but this is something I attributed to gocode not being able to parse such a huge library.

**Comment by fcying** [comment]
@therecipe  yes, i run the setup.bat
I use Vim 8.
I try test other gui:  goqt, sciter, can work with gocode

**Comment by therecipe** [comment]
@fcying 
Is your gocode package/binary up to date?
Did the setup.bat finish successfully (did the examples show up)?
I'm using atom + gocode on a mac and it works there.

So maybe there is a problem how gocode is integrated into vim?
How much ram do your machine have?

@5k3105 
Do you use vim as well?

**Comment by fcying** [comment]
@therecipe  
I updated my gocode.
The examples can be show up.

I try test Atom+autocomplete-plus, Although a little slow, but it can be used.

In vim, get gocode must use "go get -u -ldflags -H=windowsgui github.com/nsf/gocode"
atom, use  "go get -u github.com/nsf/gocode"

May be "-ldflags -H=windowsgui" let gocode not  deal with a huge library.

my platform:
I5 + 8G , win10x64

**Comment by therecipe** [comment]
This "-ldflags -H=windowsgui" should just hide the cmd window and have no effect on gocode itself.

There is probably a bug in the vim plugin you use and there is nothing I can do on my side to fix this.
So if you want to get this sorted, you probably need to contact the author of the plugin.

**Comment by fcying** [comment]
@therecipe  ok , I will report this bug, thanks~

**Comment by fcying** [comment]
Find the problem.
neocomplete time out.
add the following setting will work ok.
`let g:neocomplete#skip_auto_completion_time = "1.0"`

**Comment by therecipe** [comment]
Thank you :)
This will be useful for future reference.
