### ISSUE TITLE
Slow compiling

### ISSUE THREAD

**Issue by DeadNumbers** [therecipe/qt#516]
I'm try deploy with docker, compiling simple program takes almost a minute
```
real	0m50,984s
user	0m0,099s
sys	0m0,085s
```
is there a way to speed it up?

**Comment by 5k3105** [comment]
other than using ```qtdeploy -fast``` after the first run, no.

**Comment by therecipe** [comment]
Hey

No, docker deployments will always be slower than regular builds.
However, the "-fast" flag could help in some cases.
