### ISSUE TITLE
ld (linker) error with qt/uitools on Qt 5.9.3

### ISSUE THREAD

**Issue by justinclift** [therecipe/qt#520]
When running qtsetup on a CentOS 7 x64 workstation, this ld error is being displayed for the qt/uitools module:

```
...
INFO[0640] installing full qt/help                      
INFO[0657] installing full qt/location                  
INFO[0664] installing full qt/scripttools               
INFO[0667] installing full qt/uitools                   
ERRO[0670] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/uitools" env= error="exit status 2" func=RunCmdOptionalError name="install uitools"
github.com/therecipe/qt/uitools
# github.com/therecipe/qt/uitools
_cgo_main.c: In function ‘crosscall2’:
_cgo_main.c:2:23: warning: unused parameter ‘fn’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                       ^
_cgo_main.c:2:61: warning: unused parameter ‘a’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                             ^
_cgo_main.c:2:68: warning: unused parameter ‘c’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                    ^
_cgo_main.c:2:85: warning: unused parameter ‘ctxt’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                                     ^
_cgo_main.c: In function ‘_cgo_release_context’:
_cgo_main.c:4:41: warning: unused parameter ‘ctxt’ [-Wunused-parameter]
 void _cgo_release_context(__SIZE_TYPE__ ctxt) { }
                                         ^
_cgo_main.c: In function ‘_cgo_allocate’:
_cgo_main.c:6:26: warning: unused parameter ‘a’ [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                          ^
_cgo_main.c:6:33: warning: unused parameter ‘c’ [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                                 ^
_cgo_main.c: In function ‘_cgo_panic’:
_cgo_main.c:7:23: warning: unused parameter ‘a’ [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                       ^
_cgo_main.c:7:30: warning: unused parameter ‘c’ [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                              ^
# github.com/therecipe/qt/uitools
/usr/bin/ld: /home/jc/Qt/5.9.3/gcc_64/lib/libQt5UiTools.a(quiloader.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

Also note, this is with Qt 5.9.3 and Go 1.9.2:

```
$ go version
go version go1.9.2 linux/amd64
```

Does anyone know if that linker error at the end is likely to be a problem in general usage?  I'm just starting to explore `thereceipe/qt`, so not sure if `qt/uitools` is important. :smile:

**Comment by justinclift** [comment]
The answer to my above query appears to be "Yes".  Projects needing to use `github.com/therecipe/qt/uitools` won't be able to compile.

This one for example: https://github.com/therecipe/qt/tree/master/internal/examples/uitools/calculator

Haven't yet found out if anything else is affected, or if it can be worked around, as I'm still exploring. :smile:

**Comment by justinclift** [comment]
As a data point, I tried this again today on a brand new [CentOS 7 x64](http://mirrors.coreix.net/centos/7/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso) VM (with updates applied), + Go 1.9.2 and + Qt 5.9.3.

The exact same problem happens, so this  appears to be a real bug/issue rather than something weird with my general development desktop.

**Comment by justinclift** [comment]
As another data point, just went through the whole setup process on Win 7 x64 (Go 1.9.2, Qt 5.9.3 from official installer), and this uitools failure doesn't happen.  Not sure if it's "Linux specific" or something CentOS specific yet.

**Comment by justinclift** [comment]
Trying on CentOS 7 again, this time with different Qt versions:

| Qt version | Result |
| --- | --- |
| 5.8.0 | No compile error |
| 5.9.0 | Compiling now... |
| 5.9.1 | Not yet tested |
| 5.9.2 | Not yet tested |
| 5.9.3 | uitools compile error |

**Comment by drrob1** [comment]
I would like to add that I also have seen this bug, on an Ubuntu 16.04 host using the docker image called minimal install.  And the qt-hello.go won't compile for me.  
How do I downgrade my Qt from 5.9.3 to 5.9.2?

**Comment by justinclift** [comment]
> How do I downgrade my Qt from 5.9.3 to 5.9.2?

It depends on how you installed Qt.

For me, I installed it using the official Qt installer from qt.io.  When that runs, it gives you a selection of versions you can download + installs them (by default) in a "Qt" folder inside your home directory.

So, I just deleted the "Qt" folder in my home directory and ran through the installer again. :smile:

**Comment by drrob1** [comment]
Your experience is on CentOS.  I'm on Ubuntu 16.04.  Qt 5.9.0 thru 5.9.4 did not work for me.  However, 5.10.0 works to completion.  It's interesting that the installer defaults to 5.9.4.
Thanks again for your help.

**Comment by bigbyman** [comment]
Had the same error, but on Windows 10. Tried with qt 5.10.0, 5.9.3 and 5.9.2, none was working. Today I came back to this, realised that my version of golang arch is x86_64, installed mingw-w64, pointed my path to it, and reinstalled qt ..well, now it works like a charm, installation passes without any errors. Hope this helps.

**Comment by justinclift** [comment]
Cool.  I'll try 5.10.0 again here, and see if it's working now.  @therecipe added further 5.10.0 support a few days ago (in a76e7081468b0d9d554349b66b4971929f036ce7), which might mean that part works now. :smile:

**Comment by justinclift** [comment]
Yep, the `qt/uitools` error is gone now when building with Qt 5.10.0.

Used Go 1.10beta2 (linux/amd64) this time around too, which may have made a difference as well.  Not sure.  Anyway, it's working now, which is good enough.

Thanks for the pointer to try Qt 5.10.0 again @drrob1 and @bigbyman. :smile:
