### ISSUE TITLE
How to call go function from qml?

### ISSUE THREAD

**Issue by gauravagnihotri** [therecipe/qt#523]
I think this question begs documentation on how to effectively use qml as a UI tool when writing code in go.
I got functions definined in go which will perform an action on a string. 
I'm trying to use qml to get user input in a text field. I got a button definined in qml which I would like to use to call a function in my main.go file acting on the string entered in the text field.

For eg
```

//main.go
func scrape_vin(input string) {
    //perform some action to the input string
    //print something
    }

func main() {
...
    // Create a QML application engine
    engine := qml.NewQQmlApplicationEngine(nil)
    // Load the main qml file
    engine.Load(core.NewQUrl3("qrc:/qml/main.qml", 0))
    // Execute app
    gui.QGuiApplication_Exec()
}

```
```
//main.qml
...
    TextField {
      id: vin_num
      anchors.horizontalCenter: parent.horizontalCenter
      placeholderText: "Enter VIN Number here"
    }
...
    Button {
      anchors.horizontalCenter: parent.horizontalCenter
      text: "Decode"
      onClicked: scrape_vin(vin_num.text)
    }
  }

```

This doesn't work. I suspect my qml file doesn't know what scrape_vin does. Because it's not defined anywhere in my qml file. 

I couldn't find any documentation about this.
I would appreciate if someone could explain how to interface qml with go.

edit: updated the question with formatting

**Comment by bclermont** [comment]
you should learn markdown...

here is an example of how to call golang from qml

https://github.com/therecipe/qt/blob/master/internal/examples/quick/bridge/bridge.go#L100

**Comment by gauravagnihotri** [comment]
Thanks! this is amazing! 

p.s. sorry for being sloppy with formatting
