### ISSUE TITLE
Qtsetup failed wrong constructor of QRandomGenerator

### ISSUE THREAD

**Issue by cuthix** [therecipe/qt#524]
I run qtsetup with these settings:

```
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.9.2'       
INFO[0000] GOROOT:                   *  '/xxx/build/go-1.9.2/go' 
INFO[0000] GOPATH:                   *  '/xxx/gopath' 
INFO[0000] GOBIN:                       '/xxx/gopath/bin' 
INFO[0000] QT_HASH:                     '2d071cd40c60f9a09ad5c5267e7ace25e38983d4' 
INFO[0000] QT_VERSION:               *  '5.10.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.10.0'        
INFO[0000] QT_DIR:                   *  '/xxx/build/qt/qt-5.10.0' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'arch'          
INFO[0000] QT_PKG_CONFIG:               'false'         
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
```
ended up with error for `installing qt/core` : 
```
# github.com/therecipe/qt/core
/tmp/go-build827332482/github.com/therecipe/qt/core/_obj/core.cpp.o: In function `QRandomGenerator_NewQRandomGenerator4':
src/github.com/therecipe/qt/core/core.cpp:15494: undefined reference to `QRandomGenerator::QRandomGenerator(QRandomGenerator::System)'
collect2: error: ld returned 1 exit status
```
while code generation finished without any error

**Comment by velascopja** [comment]
I'm getting the same error when installing full qt/core, full qt/androidextras, etc. Here are my settings:

`INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                                     'linux'         
INFO[0000] GOARCH:                                'amd64'         
INFO[0000] GOVERSION:                           'go1.9.2'       
INFO[0000] GOROOT:                                 '/xxx/go' 
INFO[0000] GOPATH:                                * '/xxx/go_work' 
INFO[0000] GOBIN:                                     '/xxx/go_work/bin' 
INFO[0000] QT_HASH:                                '2d071cd40c60f9a09ad5c5267e7ace25e38983d4' 
INFO[0000] QT_VERSION:                        * '5.10.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.10.0'        
INFO[0000] QT_DIR:                                  * '/home/velascopja/Qt' 
INFO[0000] QT_STUB:                                 'false'         
INFO[0000] QT_DEBUG:                              'false'         
INFO[0000] QT_QMAKE_DIR:                      ''              
INFO[0000] QT_WEBKIT:                              'false'         
INFO[0000] QT_DISTRO:                              'ubuntu'        
INFO[0000] QT_PKG_CONFIG:                    'false'         
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
`
And here the full error for qt/core:

`ERRO[0514] failed to run command                         cmd="go install -p 2 -v github.com/therecipe/qt/core" env= error="exit status 2" func=RunCmdOptionalError name="install core"
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
cgo-gcc-prolog: In function ‘_cgo_1dbb1a4f9053_Cfunc_QThread_QThread_YieldCurrentThread’:
cgo-gcc-prolog:52477:49: warning: unused variable ‘a’ [-Wunused-variable]
# github.com/therecipe/qt/core
core.cpp: In function ‘char QAbstractEventDispatcher_RegisterEventNotifier(void*, void*)’:
core.cpp:662:59: warning: unused parameter ‘ptr’ [-Wunused-parameter]
 char QAbstractEventDispatcher_RegisterEventNotifier(void* ptr, void* notifier)
                                                           ^~~
core.cpp:662:70: warning: unused parameter ‘notifier’ [-Wunused-parameter]
 char QAbstractEventDispatcher_RegisterEventNotifier(void* ptr, void* notifier)
                                                                      ^~~~~~~~
core.cpp: In function ‘void QAbstractEventDispatcher_UnregisterEventNotifier(void*, void*)’:
core.cpp:746:61: warning: unused parameter ‘ptr’ [-Wunused-parameter]
 void QAbstractEventDispatcher_UnregisterEventNotifier(void* ptr, void* notifier)
                                                             ^~~
core.cpp:746:72: warning: unused parameter ‘notifier’ [-Wunused-parameter]
 void QAbstractEventDispatcher_UnregisterEventNotifier(void* ptr, void* notifier)
                                                                        ^~~~~~~~
core.cpp: In function ‘void* QAbstractTableModel_DataDefault(void*, void*, int)’:
core.cpp:3081:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
core.cpp: In function ‘int QAbstractTableModel_ColumnCountDefault(void*, void*)’:
core.cpp:3093:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
core.cpp: In function ‘int QAbstractTableModel_RowCountDefault(void*, void*)’:
core.cpp:3105:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
core.cpp: In function ‘void* QAbstractListModel_DataDefault(void*, void*, int)’:
core.cpp:2464:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
core.cpp: In function ‘int QAbstractListModel_RowCountDefault(void*, void*)’:
core.cpp:2492:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
core.cpp: In function ‘void* QAbstractProxyModel_IndexDefault(void*, int, int, void*)’:
core.cpp:2784:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
core.cpp: In function ‘void* QAbstractProxyModel_ParentDefault(void*, void*)’:
core.cpp:2800:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
core.cpp: In function ‘int QAbstractProxyModel_ColumnCountDefault(void*, void*)’:
core.cpp:2816:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
core.cpp: In function ‘int QAbstractProxyModel_RowCountDefault(void*, void*)’:
core.cpp:2832:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
core.cpp: In function ‘int QAnimationGroup_DurationDefault(void*)’:
core.cpp:3444:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
# github.com/therecipe/qt/core
_cgo_main.c: In function ‘crosscall2’:
_cgo_main.c:2:23: warning: unused parameter ‘fn’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                       ^~
_cgo_main.c:2:61: warning: unused parameter ‘a’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                             ^
_cgo_main.c:2:68: warning: unused parameter ‘c’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                    ^
_cgo_main.c:2:85: warning: unused parameter ‘ctxt’ [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                                     ^~~~
_cgo_main.c: In function ‘_cgo_release_context’:
_cgo_main.c:4:41: warning: unused parameter ‘ctxt’ [-Wunused-parameter]
 void _cgo_release_context(__SIZE_TYPE__ ctxt) { }
                                         ^~~~
_cgo_main.c: In function ‘_cgo_allocate’:
_cgo_main.c:6:26: warning: unused parameter ‘a’ [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                          ^
_cgo_main.c:6:33: warning: unused parameter ‘c’ [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                                 ^
_cgo_main.c: In function ‘_cgo_panic’:
_cgo_main.c:7:23: warning: unused parameter ‘a’ [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                       ^
_cgo_main.c:7:30: warning: unused parameter ‘c’ [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                              ^
# github.com/therecipe/qt/core
/tmp/go-build930652959/github.com/therecipe/qt/core/_obj/core.cpp.o: In function `QRandomGenerator_NewQRandomGenerator4':
Documents/go_work/src/github.com/therecipe/qt/core/core.cpp:15494: undefined reference to `QRandomGenerator::QRandomGenerator(QRandomGenerator::System)'
collect2: error: ld returned 1 exit status
`

**Comment by RadhiFadlillah** [comment]
@cuthix AFAIK Qt 5.10.0 still not supported by this binding, but @therecipe already [started](https://github.com/therecipe/qt/issues/508#issuecomment-352613973) working on it.

**Comment by therecipe** [comment]
This should have been fixed with: https://github.com/therecipe/qt/commit/a76e7081468b0d9d554349b66b4971929f036ce7
