### ISSUE TITLE
QObject::~QObject: Timers cannot be stopped from another thread with

### ISSUE THREAD

**Issue by avrahamlev** [therecipe/qt#525]
_**I have the flowing test code:**_

//===================CODE==========================
#include <stdio.h>
#include  <QThread>
#include <QApplication>
#include <QMainWindow>
#include <QPushButton>
#include <unistd.h>
#include <thread>

using namespace std;
class mywindow : public QMainWindow
{
protected:
    **QPushButton** but;
public:
    mywindow();
    ~mywindow();
};
mywindow::mywindow():but(" test button",this)
{
    printf(" mywindow constructor: thread =%8lx\n",(long  unsigned  int)QThread::currentThread()  );
    but.move(10,10);
    but.resize(140,40);
    but.show();
}
mywindow::~mywindow()
{
    printf(" mywindow distructor: thread =%8lx\n",(long  unsigned  int)QThread::currentThread()  );
}

QApplication *pGuiAppl=NULL;
void guithread()
{
    printf("guithread start thread=%8lx\n",(long  unsigned  int)QThread::currentThread()  );
    int n=0; 
    QApplication a(n, NULL);
    pGuiAppl = &a;
    mywindow w;
    w.resize(500,400);
    w.move(450,250);
    w.show();
    a.setActiveWindow(&w); 
    int r= a.exec();  
    printf("guithread end thread=%8lx\n",(long  unsigned  int)QThread::currentThread()  ); 
}

int main(int argc, char** argv) 
{
    thread * pstdthread = new thread(guithread);
    printf("main appl start thread=%8lx\n",(long  unsigned  int)QThread::currentThread()  );    
    getchar(); // wait user press any key
    pGuiAppl->exit(0);
    usleep(500*1000); // wait till thread finish
    printf("main appl end   thread=%8lx\n",(long  unsigned  int)QThread::currentThread()  );
    return 0;
}
//========================================================
The output is:
//--------------------OUTPUT -----------------------------
_main appl start thread=55bef87584c0
guithread start thread=7f47e8000b90
WARNING: QApplication was not created in the main() thread.
 mywindow constructor: thread =7f47e8000b90

guithread end thread=7f47e8000b90
 mywindow distructor: thread =7f47e8000b90
main appl end   thread=55bef87584c0
**QObject::~QObject: Timers cannot be stopped from another thread**_
//---------------------------------------------------

Way I get this message : QObject::~QObject: Timers cannot be stopped from another thread

If I remove the QPushButton from the window then This message not reported.

**Comment by therecipe** [comment]
Hey

This is just a binding for Qt, not the repo of Qt itself.
You are probably better off asking your question [here](https://forum.qt.io).

(But to answer your question nevertheless, I probably guess that your are running this on macOS and afaik there you will always need to run gui stuff in the main thread. So this code might work on linux and windows, but will probably not on macOS.)

**Comment by avrahamlev** [comment]
Thanks.
I work on Linux , and the GUI is not run on the main thread because it is dynamic library (*.so).
Except this message code is  run ok.

Avraham

**Comment by therecipe** [comment]
Ah okay, if it's working nevertheless then it's probably just a warning.
Will close this now :)
