### ISSUE TITLE
LE advertising and scanning support on iOS and Bluez/linux

### ISSUE THREAD

**Issue by sarangborude** [therecipe/qt#529]
Hello, 
I read in the documentation that Bluetooth low energy scanning and advertising is not supported. When will this be implemented. I have urgent needs for projects I am working on. 

Thanks,
Sarang

**Comment by renannprado** [comment]
I don't mean to be rude here.
That being said, I see two options:
1. Implement yourself
2. Contact @therecipe and hire him as a consultant to help you out

You can also go to [`#qt-binding`](https://gophers.slack.com/messages/qt-binding/details) slack channel and try to find someone who could help you.

**Comment by therecipe** [comment]
Hey

Are you referring to this: https://doc.qt.io/qt-5.10/qtbluetooth-index.html ?

This project is just a binding to Qt and doesn't actually implement these features itself.
You will probably be better off asking someone [here](https://forum.qt.io).
