### ISSUE TITLE
Add function for casting QBrush to QVariant

### ISSUE THREAD

**Issue by NightWolf007** [therecipe/qt#530]
Hi,
I can't find function for casting QBrush to QVariant. This can be useful for custom model implementation with ForegroundRole and BackgroundRole.
I think this issue is related with #101

**Comment by RadhiFadlillah** [comment]
Hi @NightWolf007, you can do it by using `core.NewQVariant3` like this :

```go
color := gui.NewQColor3(205, 220, 57, 64)
brush := gui.NewQBrush3(color, core.Qt__SolidPattern)
variant := core.NewQVariant3(int(core.QVariant__Brush), brush.Pointer())
```

**Comment by NightWolf007** [comment]
It works, thanks. But, I think, it will be more comfortable to use `brush.ToVariant()`, like for QColor or QFont. I've proposed it PR.
