### ISSUE TITLE
AppVeyor  failures

### ISSUE THREAD

**Issue by justinclift** [therecipe/qt#533]
Seems like the CI process is broken at the moment on AppVeyor.

The error from the AppVeyor logs reads:

```
Warning: No QtAccount credentials found. Please login via the maintenance tool of
the SDK.
```

Anyone know what needs to be done to fix this, or should AppVeyor be removed from the CI process (for now)?

**Comment by therecipe** [comment]
Hey

Yeah, I replaced AppVeyor, Travis and co with [vagrant](https://github.com/therecipe/qt/tree/master/internal/vagrant) since some time.
