### ISSUE TITLE
qtsetup panics

### ISSUE THREAD

**Issue by slytomcat** [therecipe/qt#536]
I'm trying minimal setup with qt (5.1.1) from distro repository for Xubuntu 16.04

`$ qtsetup 
INFO[0000] running: 'qtsetup prep'                      
INFO[0000] successfully created qtrcc symlink in your PATH (/home/stc/DEV/GO/usr_local/go/bin/qtrcc) 
INFO[0000] successfully created qtmoc symlink in your PATH (/home/stc/DEV/GO/usr_local/go/bin/qtmoc) 
INFO[0000] successfully created qtminimal symlink in your PATH (/home/stc/DEV/GO/usr_local/go/bin/qtminimal) 
INFO[0000] successfully created qtdeploy symlink in your PATH (/home/stc/DEV/GO/usr_local/go/bin/qtdeploy) 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.9.2'       
INFO[0000] GOROOT:                   *  '/home/stc/DEV/GO/usr_local/go' 
INFO[0000] GOPATH:                   *  '/home/stc/DEV/GO' 
INFO[0000] GOBIN:                       '/home/stc/DEV/GO/bin' 
INFO[0000] QT_HASH:                     'a76e7081468b0d9d554349b66b4971929f036ce7' 
INFO[0000] QT_VERSION:               *  '5.1.1'         
INFO[0000] QT_VERSION_MAJOR:            '5.1'           
INFO[0000] QT_DIR:                   *  '/usr/lib/x86_64-linux-gnu/qt5' 
INFO[0000] QT_STUB:                  *  'true'          
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:             *  '/usr/lib/x86_64-linux-gnu/qt5/bin' 
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'ubuntu'        
INFO[0000] QT_PKG_CONFIG:            *  'true'          
INFO[0000] QT_DOC_DIR:                  '/usr/share/qt5/doc' 
INFO[0000] QT_MISC_DIR:                 '/usr/lib/x86_64-linux-gnu/qt5' 
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
WARN[0000] parser.LoadModule                             error=EOF module=Gui
WARN[0000] parser.LoadModule                             error=EOF module=Core
WARN[0000] parser.LoadModule                             error=EOF module=AndroidExtras
WARN[0000] parser.LoadModule                             error=EOF module=Quick
WARN[0000] parser.LoadModule                             error=EOF module=Widgets
WARN[0000] parser.LoadModule                             error=EOF module=Sql
WARN[0000] parser.LoadModule                             error=EOF module=Bluetooth
WARN[0000] parser.LoadModule                             error=EOF module=WebSockets
WARN[0000] parser.LoadModule                             error=EOF module=XmlPatterns
WARN[0000] parser.LoadModule                             error=EOF module=Network
WARN[0000] parser.LoadModule                             error=EOF module=SerialBus
WARN[0000] parser.LoadModule                             error=EOF module=Help
WARN[0000] parser.LoadModule                             error=EOF module=Location
WARN[0000] parser.LoadModule                             error=EOF module=Xml
WARN[0000] parser.LoadModule                             error=EOF module=Qml
WARN[0000] parser.LoadModule                             error=EOF module=DBus
WARN[0000] parser.LoadModule                             error=EOF module=WebChannel
WARN[0000] parser.LoadModule                             error=EOF module=Nfc
WARN[0000] parser.LoadModule                             error=EOF module=Svg
WARN[0000] parser.LoadModule                             error=EOF module=Script
WARN[0000] parser.LoadModule                             error=EOF module=Multimedia
WARN[0000] parser.LoadModule                             error=EOF module=Sensors
WARN[0000] parser.LoadModule                             error=EOF module=Designer
WARN[0000] parser.LoadModule                             error=EOF module=Positioning
WARN[0000] parser.LoadModule                             error=EOF module=ScriptTools
WARN[0000] parser.LoadModule                             error=EOF module=UiTools
WARN[0000] parser.LoadModule                             error=EOF module=Gamepad
WARN[0000] parser.LoadModule                             error=EOF module=PrintSupport
WARN[0000] parser.LoadModule                             error=EOF module=Scxml
WARN[0000] parser.LoadModule                             error=EOF module=TestLib
WARN[0000] parser.LoadModule                             error=EOF module=WebEngine
WARN[0000] parser.LoadModule                             error=EOF module=SerialPort
WARN[0000] parser.LoadModule                             error=EOF module=WebView
WARN[0000] parser.LoadModule                             error=EOF module=QuickControls2
INFO[0000] generating stub qt/core                      
INFO[0000] generating stub qt/androidextras             
INFO[0000] generating stub qt/gui                       
INFO[0000] generating stub qt/network                   
INFO[0000] generating stub qt/xml                       
INFO[0000] generating stub qt/dbus                      
INFO[0000] generating stub qt/nfc                       
INFO[0000] generating stub qt/script                    
INFO[0000] generating stub qt/sensors                   
INFO[0000] generating stub qt/positioning               
INFO[0000] generating stub qt/widgets                   
INFO[0000] generating stub qt/sql                       
INFO[0000] generating stub qt/qml                       
INFO[0000] generating stub qt/websockets                
INFO[0000] generating stub qt/xmlpatterns               
INFO[0000] generating stub qt/bluetooth                 
INFO[0000] generating stub qt/webchannel                
INFO[0000] generating stub qt/svg                       
INFO[0000] generating stub qt/multimedia                
INFO[0000] generating stub qt/quick                     
INFO[0000] generating stub qt/help                      
INFO[0000] generating stub qt/location                  
INFO[0000] generating stub qt/scripttools               
INFO[0000] generating stub qt/uitools                   
INFO[0000] generating stub qt/webengine                 
INFO[0000] generating stub qt/testlib                   
INFO[0000] generating stub qt/serialport                
INFO[0000] generating stub qt/serialbus                 
INFO[0000] generating stub qt/printsupport              
INFO[0000] generating stub qt/designer                  
INFO[0000] generating stub qt/scxml                     
INFO[0000] generating stub qt/gamepad                   
INFO[0000] generating stub qt/datavisualization         
INFO[0000] generating stub qt/charts                    
INFO[0000] generating stub qt/quickcontrols2            
INFO[0000] generating stub qt/sailfish                  
INFO[0000] generating stub qt/webview                   
INFO[0000] running: 'qtsetup install linux' [docker=false] [vagrant=false] 
INFO[0000] installing stub qt/core                      
INFO[0000] installing stub qt/androidextras             
ERRO[0000] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/androidextras" env= error="exit status 2" func=RunCmdOptionalError name="install androidextras"
github.com/therecipe/qt/androidextras
# github.com/therecipe/qt/androidextras
../src/github.com/therecipe/qt/androidextras/androidextras.go:11:10: undefined: QAndroidJniEnvironment

INFO[0000] installing stub qt/gui                       
INFO[0000] installing stub qt/network                   
INFO[0000] installing stub qt/xml                       
INFO[0000] installing stub qt/dbus                      
INFO[0000] installing stub qt/nfc                       
INFO[0000] installing stub qt/script                    
INFO[0000] installing stub qt/sensors                   
INFO[0000] installing stub qt/positioning               
INFO[0000] installing stub qt/widgets                   
INFO[0000] installing stub qt/sql                       
INFO[0000] installing stub qt/qml                       
INFO[0000] installing stub qt/websockets                
INFO[0000] installing stub qt/xmlpatterns               
INFO[0000] installing stub qt/bluetooth                 
INFO[0000] installing stub qt/webchannel                
INFO[0000] installing stub qt/svg                       
INFO[0000] installing stub qt/multimedia                
INFO[0000] installing stub qt/quick                     
INFO[0001] installing stub qt/help                      
INFO[0001] installing stub qt/location                  
INFO[0001] installing stub qt/scripttools               
INFO[0001] installing stub qt/uitools                   
INFO[0001] installing stub qt/webengine                 
INFO[0001] installing stub qt/testlib                   
INFO[0001] installing stub qt/serialport                
INFO[0001] installing stub qt/serialbus                 
INFO[0001] installing stub qt/printsupport              
INFO[0001] installing stub qt/designer                  
INFO[0001] installing stub qt/scxml                     
INFO[0001] installing stub qt/gamepad                   
INFO[0001] installing stub qt/datavisualization         
INFO[0001] installing stub qt/charts                    
INFO[0001] installing stub qt/quickcontrols2            
INFO[0001] installing stub qt/sailfish                  
INFO[0001] installing stub qt/webview                   
WARN[0001] failed to install:                           
WARN[0001] androidextras                                
INFO[0001] running: 'qtsetup test linux' [docker=false] [vagrant=false] 
INFO[0001] testing qml/application                      
WARN[0002] parser.LoadModule                             error=EOF module=WebView
WARN[0002] parser.LoadModule                             error=EOF module=AndroidExtras
WARN[0002] parser.LoadModule                             error=EOF module=Core
WARN[0002] parser.LoadModule                             error=EOF module=Gui
WARN[0002] parser.LoadModule                             error=EOF module=Quick
WARN[0002] parser.LoadModule                             error=EOF module=Help
WARN[0002] parser.LoadModule                             error=EOF module=Network
WARN[0002] parser.LoadModule                             error=EOF module=Location
WARN[0002] parser.LoadModule                             error=EOF module=Xml
WARN[0002] parser.LoadModule                             error=EOF module=ScriptTools
WARN[0002] parser.LoadModule                             error=EOF module=DBus
WARN[0002] parser.LoadModule                             error=EOF module=UiTools
WARN[0002] parser.LoadModule                             error=EOF module=WebEngine
WARN[0002] parser.LoadModule                             error=EOF module=Nfc
WARN[0002] parser.LoadModule                             error=EOF module=TestLib
WARN[0002] parser.LoadModule                             error=EOF module=Script
WARN[0002] parser.LoadModule                             error=EOF module=SerialPort
WARN[0002] parser.LoadModule                             error=EOF module=Sensors
WARN[0002] parser.LoadModule                             error=EOF module=SerialBus
WARN[0002] parser.LoadModule                             error=EOF module=Positioning
WARN[0002] parser.LoadModule                             error=EOF module=PrintSupport
WARN[0002] parser.LoadModule                             error=EOF module=Widgets
WARN[0002] parser.LoadModule                             error=EOF module=Designer
WARN[0002] parser.LoadModule                             error=EOF module=Scxml
WARN[0002] parser.LoadModule                             error=EOF module=Sql
WARN[0002] parser.LoadModule                             error=EOF module=Gamepad
WARN[0002] parser.LoadModule                             error=EOF module=Qml
WARN[0002] parser.LoadModule                             error=EOF module=WebSockets
WARN[0002] parser.LoadModule                             error=EOF module=QuickControls2
WARN[0002] parser.LoadModule                             error=EOF module=XmlPatterns
WARN[0002] parser.LoadModule                             error=EOF module=WebChannel
WARN[0002] parser.LoadModule                             error=EOF module=Svg
WARN[0002] parser.LoadModule                             error=EOF module=Bluetooth
WARN[0002] parser.LoadModule                             error=EOF module=Multimedia
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x6e78fd]

goroutine 1 [running]:
github.com/therecipe/qt/internal/cmd/minimal.Minimal(0xc42025c820, 0x4e, 0x8002b6, 0x5, 0x0, 0x0)
	/home/stc/DEV/GO/src/github.com/therecipe/qt/internal/cmd/minimal/minimal.go:150 +0xb0d
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x7ffe2a, 0x4, 0x8002b6, 0x5, 0xc42025c820, 0x4e, 0x46eb00, 0x0, 0x0, 0x0, ...)
	/home/stc/DEV/GO/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:54 +0xd42
github.com/therecipe/qt/internal/cmd/setup.Test(0x8002b6, 0x5, 0x7f0000, 0x0, 0x0)
	/home/stc/DEV/GO/src/github.com/therecipe/qt/internal/cmd/setup/test.go:148 +0x72e
main.main()
	/home/stc/DEV/GO/src/github.com/therecipe/qt/cmd/qtsetup/main.go:90 +0x2d3`

**Comment by therecipe** [comment]
Hey

Yeah this is because Qt 5.1.1 is currently unsupported.
