### ISSUE TITLE
Exposing a non QObject struct in a QObject struct to QML

### ISSUE THREAD

**Issue by velascopja** [therecipe/qt#537]
Sorry if this is a stupid question, but I'm a newbie both with Qt and Go.
Suppose I have a package foo with a struct like this:
```go
type Foo struct {
    Member1 string
    Member2 string
}
```
I'd like to have access to my members from a .qml file, so I create another struct like this:
```go
type QFoo struct {
    core.QObject
    Foo foo.Foo
}
```
and try to access Member1 from main.qml with something like:
```qml
Label {
        id: label1
        anchors.margins: 5
        anchors.fill: parent
        wrapMode: Text.WordWrap
        text: QFoo.Foo.Member1
}
```
Of course after setting the context before loading main.qml:
```go
var test = NewQFoo(nil)
test.Foo.Member1 = "blablabla"
...
engine.RootContext().SetContextProperty("QFoo", test)
```
I get this error:
```
qrc:/qml/main.qml:xxx: TypeError: Cannot read property 'Member1' of undefined
``` 
Can someone, please, tell me what I'm doing wrong?

I guess I lack a lot of knowledge so I'll appreciate so much your help.

Also sorry for my English, I hope I made myself clear enough when exposing the issue.

Thanks in advance!

**Comment by therecipe** [comment]
Hey

Foo and QFoo will both need to "subclass" core.QObject and explicitly delare "foo", "member1" and "member2" as properties for this to work.
And you will need to access the properties by using lowercase names such as "QFoo.foo.member1".

This should work:
main.go
```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/quick"
	"github.com/therecipe/qt/widgets"
)

type QFoo struct {
	core.QObject

	_ Foo `property:"foo"`
}

type Foo struct {
	core.QObject

	_ string `property:"member1"`
	_ string `property:"member2"`
}

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	qv := quick.NewQQuickView(nil)
	qv.SetResizeMode(quick.QQuickView__SizeViewToRootObject)

	test := NewQFoo(nil)
	test.SetFoo(NewFoo(nil))
	test.Foo().SetMember1("blablabla")

	qv.Engine().RootContext().SetContextProperty("QFoo", test)
	qv.SetSource(core.QUrl_FromLocalFile("main.qml"))

	qv.Show()

	widgets.QApplication_Exec()
}
```

main.qml
```qml
import QtQuick 2.5
import QtQuick.Controls 2.3

Label {
	anchors.margins: 5
	text: QFoo.foo.member1
	width: 100
	height: 100
}
```
