### ISSUE TITLE
core.QLocale_System().Name() is always 'en_US' ?

### ISSUE THREAD

**Issue by ghost** [therecipe/qt#539]
Running win7 x64 PRC, but core.QLocale_System().Name() is 'en_US', Expecting 'zh_CN'.

Maybe automatically load locale qm ? Need to load locale qm manually.

```
	translator := core.NewQTranslator(nil)
	translator.Load("qt_zh_CN", ":/res/i18n/", "", "") // core.QLocale_System().Name() -> en_US
	app.InstallTranslator(translator)
```

**Comment by therecipe** [comment]
Hey

`core.QLocale_System().Name()` seems to work for me on macOS 10.13.3 with Qt 5.10.1.
