### ISSUE TITLE
Are there any company or individual that use this binding for large project ?

### ISSUE THREAD

**Issue by nntaoli** [therecipe/qt#542]

**Comment by Huholoman** [comment]
Jeg forstår ikke i det hele tatt.

**Comment by RadhiFadlillah** [comment]
I've personally use this binding for Point of Sale system in my own company, and it works nicely. For large open source project, you can check [gonvim](https://github.com/dzhou121/gonvim).

As far as I know, this binding is stable and still actively developed. So, as long as your works doesn't have any problem with [LGPL license](https://github.com/therecipe/qt/wiki/FAQ#what-is-the-implication-from-using-lgpl-library-in-my-go-app-) that used by this binding, I think it's a good idea to use it.

**Comment by di3663** [comment]
内存泄漏，慎用，qt已经足够简单了。

**Comment by nntaoli** [comment]
@di3663  嗯，我只会Go语言，c++不是很懂，我是看中qt的跨平台和组建丰富，想用qt做界面，go做业务逻辑，这样方便我维护整个项目。想了解下这个绑定是否稳定，所以提了这个issue。

**Comment by nntaoli** [comment]
@RadhiFadlillah 
Can do business software based on this project, with dynamic link qt?
