### ISSUE TITLE
win10 install qt5.8 error msg="failed to run command" cmd="copyCmd 

### ISSUE THREAD

**Issue by wuyushuai** [therecipe/qt#543]
`$ ./qtsetup.exe
time="2018-02-04T11:45:18+08:00" level=info msg="running: 'qtsetup prep'"
time="2018-02-04T11:45:19+08:00" level=info msg="running: 'qtsetup check windows' [docker=false] [vagrant=false]"
time="2018-02-04T11:45:19+08:00" level=info msg="GOOS:                        'windows'"
time="2018-02-04T11:45:19+08:00" level=info msg="GOARCH:                      'amd64'"
time="2018-02-04T11:45:19+08:00" level=info msg="GOVERSION:                   'go1.9.2'"
time="2018-02-04T11:45:19+08:00" level=info msg="GOROOT:                   *  'C:\\Go\\'"
time="2018-02-04T11:45:19+08:00" level=info msg="GOPATH:                   *  'C:\\Users\\Public\\Code\\Go'"
time="2018-02-04T11:45:19+08:00" level=info msg="GOBIN:                       'C:\\Users\\Public\\Code\\Go\\bin'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_HASH:                     'a76e7081468b0d9d554349b66b4971929f036ce7'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_VERSION:               *  '5.8.0'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_VERSION_MAJOR:            '5.8'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_DIR:                   *  'C:\\Qt\\Qt5.8.0'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_STUB:                  *  'true'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_DEBUG:                 *  'false'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_QMAKE_DIR:                ''"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_WEBKIT:                   'false'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_MSYS2:                    'true'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_MSYS2_DIR:                'C:\\msys64\\mingw64'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_MSYS2_ARCH:               'amd64'"
time="2018-02-04T11:45:19+08:00" level=info msg="QT_MSYS2_STATIC:             'false'"
time="2018-02-04T11:45:19+08:00" level=info msg="running: 'qtsetup generate windows' [docker=false] [vagrant=false]"
time="2018-02-04T11:45:31+08:00" level=info msg="generating stub qt/core"
time="2018-02-04T11:45:33+08:00" level=info msg="generating stub qt/androidextras"
time="2018-02-04T11:45:33+08:00" level=info msg="generating stub qt/gui"
time="2018-02-04T11:45:40+08:00" level=info msg="generating stub qt/network"
time="2018-02-04T11:45:41+08:00" level=info msg="generating stub qt/xml"
time="2018-02-04T11:45:41+08:00" level=info msg="generating stub qt/dbus"
time="2018-02-04T11:45:41+08:00" level=info msg="generating stub qt/nfc"
time="2018-02-04T11:45:41+08:00" level=info msg="generating stub qt/script"
time="2018-02-04T11:45:41+08:00" level=info msg="generating stub qt/sensors"
time="2018-02-04T11:45:42+08:00" level=info msg="generating stub qt/positioning"
time="2018-02-04T11:45:42+08:00" level=info msg="generating stub qt/widgets"
time="2018-02-04T11:45:47+08:00" level=info msg="generating stub qt/sql"
time="2018-02-04T11:45:47+08:00" level=info msg="generating stub qt/qml"
time="2018-02-04T11:45:47+08:00" level=info msg="generating stub qt/websockets"
time="2018-02-04T11:45:47+08:00" level=info msg="generating stub qt/xmlpatterns"
time="2018-02-04T11:45:47+08:00" level=info msg="generating stub qt/bluetooth"
time="2018-02-04T11:45:48+08:00" level=info msg="generating stub qt/webchannel"
time="2018-02-04T11:45:48+08:00" level=info msg="generating stub qt/svg"
time="2018-02-04T11:45:48+08:00" level=info msg="generating stub qt/multimedia"
time="2018-02-04T11:45:49+08:00" level=info msg="generating stub qt/quick"
time="2018-02-04T11:45:49+08:00" level=info msg="generating stub qt/help"
time="2018-02-04T11:45:50+08:00" level=info msg="generating stub qt/location"
time="2018-02-04T11:45:50+08:00" level=info msg="generating stub qt/scripttools"
time="2018-02-04T11:45:50+08:00" level=info msg="generating stub qt/uitools"
time="2018-02-04T11:45:50+08:00" level=info msg="generating stub qt/winextras"
time="2018-02-04T11:45:50+08:00" level=info msg="generating stub qt/testlib"
time="2018-02-04T11:45:50+08:00" level=info msg="generating stub qt/serialport"
time="2018-02-04T11:45:50+08:00" level=info msg="generating stub qt/serialbus"
time="2018-02-04T11:45:50+08:00" level=info msg="generating stub qt/printsupport"
time="2018-02-04T11:45:51+08:00" level=info msg="generating stub qt/designer"
time="2018-02-04T11:45:51+08:00" level=info msg="generating stub qt/scxml"
time="2018-02-04T11:45:51+08:00" level=info msg="generating stub qt/gamepad"
time="2018-02-04T11:45:51+08:00" level=info msg="generating stub qt/datavisualization"
time="2018-02-04T11:45:52+08:00" level=info msg="generating stub qt/charts"
time="2018-02-04T11:45:52+08:00" level=info msg="generating stub qt/speech"
time="2018-02-04T11:45:52+08:00" level=info msg="generating stub qt/quickcontrols2"
time="2018-02-04T11:45:52+08:00" level=info msg="generating stub qt/sailfish"
time="2018-02-04T11:45:52+08:00" level=info msg="running: 'qtsetup install windows' [docker=false] [vagrant=false]"
time="2018-02-04T11:45:52+08:00" level=info msg="installing stub qt/core"
time="2018-02-04T11:45:55+08:00" level=info msg="installing stub qt/androidextras"
time="2018-02-04T11:45:55+08:00" level=info msg="installing stub qt/gui"
time="2018-02-04T11:45:59+08:00" level=info msg="installing stub qt/network"
time="2018-02-04T11:46:00+08:00" level=info msg="installing stub qt/xml"
time="2018-02-04T11:46:01+08:00" level=info msg="installing stub qt/dbus"
time="2018-02-04T11:46:02+08:00" level=info msg="installing stub qt/nfc"
time="2018-02-04T11:46:02+08:00" level=info msg="installing stub qt/script"
time="2018-02-04T11:46:03+08:00" level=info msg="installing stub qt/sensors"
time="2018-02-04T11:46:05+08:00" level=info msg="installing stub qt/positioning"
time="2018-02-04T11:46:05+08:00" level=info msg="installing stub qt/widgets"
time="2018-02-04T11:46:16+08:00" level=info msg="installing stub qt/sql"
time="2018-02-04T11:46:17+08:00" level=info msg="installing stub qt/qml"
time="2018-02-04T11:46:17+08:00" level=info msg="installing stub qt/websockets"
time="2018-02-04T11:46:18+08:00" level=info msg="installing stub qt/xmlpatterns"
time="2018-02-04T11:46:19+08:00" level=info msg="installing stub qt/bluetooth"
time="2018-02-04T11:46:19+08:00" level=info msg="installing stub qt/webchannel"
time="2018-02-04T11:46:20+08:00" level=info msg="installing stub qt/svg"
time="2018-02-04T11:46:21+08:00" level=info msg="installing stub qt/multimedia"
time="2018-02-04T11:46:23+08:00" level=info msg="installing stub qt/quick"
time="2018-02-04T11:46:25+08:00" level=info msg="installing stub qt/help"
time="2018-02-04T11:46:26+08:00" level=info msg="installing stub qt/location"
time="2018-02-04T11:46:27+08:00" level=info msg="installing stub qt/scripttools"
time="2018-02-04T11:46:28+08:00" level=info msg="installing stub qt/uitools"
time="2018-02-04T11:46:29+08:00" level=info msg="installing stub qt/winextras"
time="2018-02-04T11:46:29+08:00" level=info msg="installing stub qt/testlib"
time="2018-02-04T11:46:30+08:00" level=info msg="installing stub qt/serialport"
time="2018-02-04T11:46:31+08:00" level=info msg="installing stub qt/serialbus"
time="2018-02-04T11:46:31+08:00" level=info msg="installing stub qt/printsupport"
time="2018-02-04T11:46:33+08:00" level=info msg="installing stub qt/designer"
time="2018-02-04T11:46:34+08:00" level=info msg="installing stub qt/scxml"
time="2018-02-04T11:46:35+08:00" level=info msg="installing stub qt/gamepad"
time="2018-02-04T11:46:35+08:00" level=info msg="installing stub qt/datavisualization"
time="2018-02-04T11:46:36+08:00" level=info msg="installing stub qt/charts"
time="2018-02-04T11:46:38+08:00" level=info msg="installing stub qt/speech"
time="2018-02-04T11:46:38+08:00" level=info msg="installing stub qt/quickcontrols2"
time="2018-02-04T11:46:39+08:00" level=info msg="installing stub qt/sailfish"
time="2018-02-04T11:46:40+08:00" level=info msg="running: 'qtsetup test windows' [docker=false] [vagrant=false]"
time="2018-02-04T11:46:40+08:00" level=info msg="testing widgets\\line_edits"
time="2018-02-04T11:47:49+08:00" level=error msg="failed to run command" cmd="copyCmd C:\\msys64\\mingw64\\bin\\Qt5OpenGL.dll C:\\Users\\Public\                                                           \Code\\Go\\src\\github.com\\therecipe\\qt\\internal\\examples\\widgets\\line_edits\\deploy\\windows" env= error="exec: \"copyCmd\": executable f                                                           ile not found in %PATH%" func=RunCmd name="copy Qt5OpenGL for windows on windows"
`

![tim 20180204123521](https://user-images.githubusercontent.com/36121631/35774370-191e032a-09a8-11e8-821b-c682c38b375c.png)

**Comment by zuiwuchang** [comment]
this is a bug at [internal/cmd/deploy/bundle.go line 275](https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/bundle.go)
code should 
```go
utils.RunCmd(exec.Command(copyCmd, filepath.Join(libraryPath, fmt.Sprintf("%v.dll", lib)), depPath), fmt.Sprintf("copy %v for %v on %v", lib, target, runtime.GOOS))
```
but now is this
```go
utils.RunCmd(exec.Command("copyCmd", filepath.Join(libraryPath, fmt.Sprintf("%v.dll", lib)), depPath), fmt.Sprintf("copy %v for %v on %v", lib, target, runtime.GOOS))
```
should **copyCmd** not **"copyCmd"**

fix it you can do this at msys2
cp /usr/bin/cp.exe /user/bin/copyCmd.exe
qtsetup

**Comment by wuyushuai** [comment]
tkank you for your help   @zuiwuchang      
![tim 20180204173924](https://user-images.githubusercontent.com/36121631/35776302-e43796ee-09d4-11e8-99c3-a637edc13669.png)

**Comment by therecipe** [comment]
@zuiwuchang Thank you, this will be fixed with the next commit.

**Comment by therecipe** [comment]
Should be fixed with: https://github.com/therecipe/qt/commit/49ef0b2a81b60e1dea801bdbe6673ee3e4fef43d
