### ISSUE TITLE
golang 1.10rc1 qt 5.10 ios error - 

### ISSUE THREAD

**Issue by vahid-sohrabloo** [therecipe/qt#544]
I run gallery example with golang 1.10rc1 and QT 5.10 on ios simulator
After build and run gave me this error
```
qrc:/gallery.qml:-1 no such file or directory
```

**Comment by therecipe** [comment]
Hey

Yeah, there seems to be some problem with go don't compiling external *.cpp files or something.
I will look into this.

**Comment by therecipe** [comment]
Just tested it, the examples that won't work with Go 1.10 work with Go 1.9.5.
I will need to check if this is my fault, or if I have to raise an issue.

**Comment by therecipe** [comment]
@vahid-sohrabloo Sorry, took a little longer but this should be fixed now with: https://github.com/therecipe/qt/commit/856baca876f2362b409bfd531e738f651453f0fd

**Comment by vahid-sohrabloo** [comment]
Hi @therecipe , Thank you. it fixed
