### ISSUE TITLE
Can't build on archlinux with go1.10

### ISSUE THREAD

**Issue by erfanio** [therecipe/qt#558]
I just updated go on archlinux, and keep getting this when trying to build

Building with `qtdeploy`
```
ERRO[0000] failed to run command                         cmd="go build -p 8 -v -ldflags=\"-s\" \"-w\" -o /home/erfan/go/src/github.com/erfanio/1pass/deploy/linux/1pass -i -tags=\"\"" env= error="exit status 2" func=RunCmd name="build for linux on linux"
invalid value "\"-s\" \"-w\"" for flag -ldflags: missing =<value> in <pattern>=<value>
usage: build [-o output] [-i] [build flags] [packages]
```

**Comment by mjevans** [comment]
I get a similar error, it's complaining about missing go in /usr/local/go/bin/go

ERRO[0003] failed to run command                         cmd="docker run --rm -e IDUG=1000:1000 -v /home/aeon/go:/media/sf_GOPATH0 -e GOPATH=/home/user/work:/media/sf_GOPATH0 -i therecipe/qt:linux qtdeploy -debug -ldflags= -tags= build linux /media/sf_GOPATH0/src/test/qt_line_edits.go" env= error="exit status 1" func=RunCmd name="deploy binary for linux on linux with docker"
time="2018-03-04T02:27:51Z" level=debug msg="running Deploy" docker=false fast=false ldFlags= mode=build path=/media/sf_GOPATH0/src/test/qt_line_edits.go target=linux
time="2018-03-04T02:27:51Z" level=debug msg="start Rcc" path=/media/sf_GOPATH0/src/test/qt_line_edits.go target=linux
time="2018-03-04T02:27:51Z" level=debug msg="get imports" level=0 path=/media/sf_GOPATH0/src/test/qt_line_edits.go
time="2018-03-04T02:27:51Z" level=debug msg=Execute cmd="go list std" env= func=RunCmd name="go list std"
time="2018-03-04T02:27:52Z" level=debug msg=Execute cmd="go list -e -f '{{ join .TestImports \"|\" }}':'{{ join .Deps \"|\" }}' -tags=\"\"" env= func=RunCmd name="go list deps"
time="2018-03-04T02:27:52Z" level=error msg="failed to run command" cmd="go list -e -f '{{ join .TestImports \"|\" }}':'{{ join .Deps \"|\" }}' -tags=\"\"" env= error="fork/exec /usr/local/go/bin/go: not a directory" func=RunCmd name="go list deps"

**Comment by mjevans** [comment]
It's rather odd that this works...

cd ~/go/src/Whatever
qtdeploy -docker test desktop

Which eventually lead me to doing this:

cd ~/go/src/Whatever
rm -r deploy linux ; GODIR=~/go ~/go/bin/qtdeploy -docker build linux ./

See if adding GODIR makes it work for you; go will default to ~/go if you don't have it setup, but the docker container doesn't work around the fact that it's ~/ and your ~/ are different.

**Comment by erfanio** [comment]
@mjevans I think you might have a different problem with the docker image.
The docker images are pinned to go1.9.2 and the flags problem is only on >= go1.9.3

Also for the future, if you put your output in a [code block](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) it makes it way easier to read

**Comment by erfanio** [comment]
@therecipe Awesome 💯
