### ISSUE TITLE
Weird directory requirement for Qt

### ISSUE THREAD

**Issue by mixedCase** [therecipe/qt#56]
Any particular reason why the bindings cannot be used if Qt isn't located in /usr/share/Qt5.7.0 ?

What exactly does the library need that cannot be probed for?

**Comment by therecipe** [comment]
Hey

There is no particular reason for the Qt location requirement in /usr/local. I simply forgot to change it to the default Qt install directory when I updated the binding from 5.6 to 5.7.
I will change it to the default Qt install directory (I believe it's $HOME/Qt5.8.0), when I update the binding to 5.8.

In the meantime I planned to add the ability to provide an environmental variable for a custom Qt location. (Probably with the next commit)

If you don't want to wait for this, you could simply create a symlink to /usr/local/Qt5.7.0

**Comment by mixedCase** [comment]
Is there any chance we could use the non-Android version that is usually shipped in Linux distros?

I'm not interested in Android development with Qt, at least for the moment.

**Comment by therecipe** [comment]
Sure, it should work with the non-Android version too.
I just linked to the android version, because it's only 50mb bigger and nice to have if needed someday.

**Comment by therecipe** [comment]
With https://github.com/therecipe/qt/commit/4c104f8cca5cad6ec4f5fd62524856b7ef0ce737, you can now define a custom Qt location by setting the `QT_INSTALL_DIR` env variable before running the setup.

**Comment by mixedCase** [comment]
Nice job!, closing
