### ISSUE TITLE
invalid flag in CFLAGS: -fno-keep-inline-dllexport

### ISSUE THREAD

**Issue by Xeizzen** [therecipe/qt#561]
Getting this error:
`go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -fno-keep-inline-dllexport`
By trying to test one of the examples with qml using `qtdeploy test desktop`.
I'm using golang 1.10 x86 and Qt 5.10.1 with mingw5.3 x32 provided by Qt itself.

Is there a way to fix this?

**Comment by Keyn1** [comment]
I have this mistake too.

run the command: qtsetup.exe
at first, everything goes well
generate is ok
but then there is such a mistake
/////////////////////////////////////////
.... 
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -fno-keep-inline-dllexport
/////////////////////////////////////////

"qtdeploy test desktop" also this error

environment variable
LIBRARY_PATH = C:\Qt\Qt5.9.1\5.9.1\mingw53_32\lib
CPATH = C:\Qt\Qt5.9.1\5.9.1\mingw53_32\include
QT_DIR = C:\Qt\Qt5.9.1
QT_VERSION = 5.9.1
Path = C:\mingw-w64\x86_64-7.2.0-win32-seh-rt_v5-rev1\mingw64\bin;C:\Go\bin;C:\Gosrc\bin
GOARCH = amd64
GOBIN = c:\gosrc\bin
GOPATH = c:\Gosrc
GOROOT = C:\Go\

**Comment by ernstvanzyl** [comment]
See #549. Issue is related to using Go version > 1.9.3.
