### ISSUE TITLE
Trying to understand the licensing in simple terms.

### ISSUE THREAD

**Issue by brettskiii** [therecipe/qt#562]
Can I write a closed source commercial game and sell it without allowing the user access to the code?

From what I read this doesn't seem possible (at least yet), so I'm wondering if I have to give up on my dream of using these awesome bindings.

**Comment by pztrn** [comment]
Yes, you should give up.

LGPL in short: you can use LGPL libraries and/or software under LGPL in commercial product only if LGPL libraries and/or software aren't statically linked (e.g. anyone is able to recompile your app or use your object code with another version of Qt and/or this binding).

**Comment by brettskiii** [comment]
It's all good, just disappointing. Thank you for the response.

**Comment by therecipe** [comment]
@brettskiii You could run "go build -work" and then only distribute the "_pkg_.a" files + the "importcfg.link" file + the info which Go + Qt version you used.
This should be enough to comply with LGPL.

Here is an related issue: https://github.com/therecipe/qt/issues/495
