### ISSUE TITLE
memory leak in Go with Qt

### ISSUE THREAD

**Issue by ubuntulove74** [therecipe/qt#564]
I noticed that all go with qt programs have memory leak problems,But Increase memory in qml applications is very slowly; However, the problems are serious.
Can these problems be solved?

**Comment by therecipe** [comment]
Hey

I fixed some leaks with: https://github.com/therecipe/qt/commit/299f21022aa217faace4fae811ddd2ede4e35c9d
Please let me know if this solves your problem.
If it doesn't solve your issue, then please try to provide an example so that I can try to recreate the issue.
