### ISSUE TITLE
Binary size

### ISSUE THREAD

**Issue by mixedCase** [therecipe/qt#57]
Apparently the example binary ends up being 99MB over here (linux/amd64). Is it by design to build this much statically or just a temporary measure?

I must say that I did compile using `go build` instead of `qtdeploy` as indicated in the guide, since I apparently don't have that binary, might that have anything to do with it?

Btw I didn't say it in my last issue but impressive work you have here. Well done.

**Comment by therecipe** [comment]
Hey

Thank you :)

Yes, binary size is an issue with the normal / plain `go build`, even through Go 1.7 reduced the average binary size around 40%. So I made a workaround by allowing qtdeploy to dynamical generate a small version of the binding on the fly. (I will sooner or later separate the function into a stand alone binary called: qtminimal)

If you want to use qtdeploy you might need to run this `sudo chown -R $USER /usr/local/go/` to allow the creation of qtdeploy and qtmoc in `/usr/local/go/bin/`.

And then this `go run $GOPATH/src/github.com/therecipe/qt/internal/setup/test.go` to build qtdeploy + qtmoc and also all the examples.

After this, you should be able to use qtdeploy like this:
`qtdeploy build desktop YourExampleProject`, which will build a big binary (100mb) in "YourExampleProject/deploy/linux/" and also a small binary (2mb) in "YourExampleProject/deploy/linux_minimal"

You can also just execute qtdeploy like this: `qtdeploy build desktop YourExampleProject minimal` to only build the small (minimal) version.

**Comment by mixedCase** [comment]
Any chance that qtdeploy (from what I'm looking it's a Go program) could be simply be `go install`ed in the test script so that it ends up in `$GOPATH/bin` instead?

Right now I created the /usr/local/go directory and chowned it but even that gives me a permission denied error for qtdeploy when running the test script, so I can't test that either.

In any case, this may be a good thing to mention in the installation instructions.

**Comment by therecipe** [comment]
The qtdeploy + qtmoc binaries just need to end up somewhere in you $PATH.

I assumed that most people got their $GOROOT set to `/usr/local/go` and their $PATH somehow contains `$GOROOT/bin`.

 And that most don't have their $GOPATH/bin in their $PATH.

**Comment by mixedCase** [comment]
I don't have `$GOROOT` set in my shell, but `go env GOROOT` returns the right location (`/usr/lib/go` used by Arch Linux).

In any case, I believe `$GOPATH` is the right place for Go applications/libraries to be installed to with the go tools, while `$GOROOT` is for the Go toolset. What's more, `$(go env GOROOT)/bin` is symlinked to `/usr/bin` in my system (by the `go` distro package).

**Comment by therecipe** [comment]
Yes, you are right.
I should probably change the test.go, so that qtdeploy and qtmoc get installed into $GOPATH/bin (with `go install ...`) and then symlink them to `/usr/local/bin`

**Comment by mixedCase** [comment]
Did just that in #58 minus symlinking, as I believe having it on $PATH is kind of a personal choice. Of course, it's your call.

**Comment by therecipe** [comment]
Okay, thank you.
I will probably merge it in the next 24h, but I will have to test it first. (It's late here, so I will look into this tomorrow)
Because I'm not sure, if not having them in the $PATH may break some things (probably when qtmoc is called from qtdeploy).

**Comment by therecipe** [comment]
Merged you pull request and also made some small changes with https://github.com/therecipe/qt/commit/4c104f8cca5cad6ec4f5fd62524856b7ef0ce737.
So that qtdeploy + qtmoc get symlinked into /usr/local/bin (%GOROOT%/bin on windows).
And it's not mandatory anymore to be in the $PATH for qtdeploy + qtmoc to work correctly.

**Comment by mixedCase** [comment]
I'm closing this and opening a new issue more focused on improving dynamic linking against system libs instead of a vendored, blessed version.
