### ISSUE TITLE
Use older version of Qt in Docker

### ISSUE THREAD

**Issue by FireFaced** [therecipe/qt#574]
Is there a way to make the Docker deployments use an older version of Qt for compatibility with systems that are not bleeding-edge?

**Comment by therecipe** [comment]
Hey

Yes, but you would need to create your own docker images by editing: https://github.com/therecipe/qt/blob/master/internal/docker/linux/Dockerfile
to export `QT_VERSION=5.x.x`

and https://github.com/therecipe/qt/blob/master/internal/ci/iscript.qs#L54:L68
to change the installer script to install some older version of Qt

then you would also have to manually use docker with `docker run ...` for the actual deployment

**Comment by FireFaced** [comment]
Knowing how all that works, I'd be happy to help make separate docker images for Dockerhub based on older versions, and implement `-qt_version` support for `-docker`

**Comment by therecipe** [comment]
:) Any help is gladly appreciated, feel free to work on this and I will merge the PR right away if it looks good.

**Comment by FireFaced** [comment]
Will do!
