### ISSUE TITLE
 invalid flag in #cgo CFLAGS: -fno-keep-inline-dllexport

### ISSUE THREAD

**Issue by llgoer** [therecipe/qt#575]
build on windows 10 ues msys2,show error like :
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -fno-keep-inline-dllexport

**Comment by therecipe** [comment]
Hey

If you manually build with "go build" (and Go 1.9.4+) you will need to set:
```
CGO_CXXFLAGS_ALLOW=".*" 
CGO_LDFLAGS_ALLOW=".*" 
CGO_CFLAGS_ALLOW=".*" 
```
Take a look here: https://github.com/therecipe/qt/issues/549
