### ISSUE TITLE
Any chance of an example of accessing struct parameters from qml?

### ISSUE THREAD

**Issue by amlwwalker** [therecipe/qt#583]
If I have:

```
type Config stuct {
	Name string
}
type QmlBridge struct {
    core.QObject
    Config Config
    _ func(p string)        `signal:"updateLoader"`
    _ func(data string) string `slot:"sendToGo"`
}
```

and I pass an instance of QmlBridge like:

```
view.RootContext().SetContextProperty("QmlBridge", qmlBridge)
```

What do I need to change to be able to access the elements in Config?
I was thinking perhaps I could do:

```
type QmlBridge struct {
    core.QObject
   Config
    _ func(p string)        `signal:"updateLoader"`
    _ func(data string) string `slot:"sendToGo"`
}
```
and access them straight off the bridge, but alas, to no avail...

Thanks

**Comment by therecipe** [comment]
Hey

You can't directly access go structs, but you can define properties and then use them from go and qml.

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/quick"
	"github.com/therecipe/qt/widgets"
)

type Config struct {
	core.QObject

	_ string `property:"name"`
}

type QmlBridge struct {
	core.QObject

	_ Config `property:"config"`
}

func main() {
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
	widgets.NewQApplication(len(os.Args), os.Args)

	conf := NewConfig(nil)
	conf.SetName("someName")
	conf.ConnectNameChanged(func(n string) {
		println("new name:", n)
	})

	qmlBridge := NewQmlBridge(nil)
	qmlBridge.SetConfig(conf)

	view := quick.NewQQuickView(nil)
	view.RootContext().SetContextProperty("qmlBridge", qmlBridge)
	view.SetSource(core.NewQUrl3("qrc:///qml/main.qml", 0))
	view.Show()

	widgets.QApplication_Exec()
}
```

```qml
import QtQuick 2.0
import QtQuick.Controls 2.0

Rectangle {
    width: 320
    height: 480

    Text {
      anchors.fill: parent
      text: qmlBridge.config.name
    }

    MouseArea {
      anchors.fill: parent
      onClicked: qmlBridge.config.name = "someOtherName"
    }
}
```

**Comment by amlwwalker** [comment]
Is it valid to name these properties in the struct so they can be accessed by both Go and QML, maybe a stupid question, however I tried it and I got an error: Config has both a member and a function of the same name (or words to that effect), by doing:

```
type Config struct {
	core.QObject
	Name string `property:"name"`
}
type QmlBridge struct {
	core.QObject

	Conf Config `property:"config"`
}
```

then in Go trying to do `QmlBridge.Conf.Name = "hello world`.
But perhaps I error'd elsewhere (I didn't work to long on it, just a test).

That's very cool then if both Qml and Go can read/write to the same property directly, although I suppose you still need a signal/slot to let the other know it has changed? Would make updates between the two so nice to use.

**Comment by therecipe** [comment]
No, sadly it's currently not possible to give them the same name.
This is because the name is reserved for the "getter" function.

You can access the property from Go like this:

```go
	someConfig := NewConfig(nil)
	someConfig.ConnectNameChanged(func(name string) { //connecting the changed signal
		println("name changed to:", name)
	})
	someConfig.SetName("someName") //using the setter
	println(someConfig.Name())     //using the getter
```

And in QML you can use the "Connection" object, take a look here: https://github.com/therecipe/qt/tree/master/internal/examples/qml/prop2

Also you will also always need to use lowercase names for properties in qml, so instead of:
`QmlBridge.Conf.Name = "hello world"` you will need to use `QmlBridge.conf.name = "hello world` iirc.
