### ISSUE TITLE
Getting this package to work on Windows 10

### ISSUE THREAD

**Issue by creedr** [therecipe/qt#586]
I spent quite some time today trying to get `therecipe/qt` to work on Windows 10. There were a few other issues that helped me along, namely #187, #581, and #483, but I would like to share my solution in hopes that others might not waste as much time as I did on it.

First of all, this will be a continuation of my comment on #581. So I tried running the [Widget example here](https://github.com/therecipe/qt/wiki/Getting-Started#starting-application) which failed because my install was using the 32 bit MinGW that came with the Qt installer, and Go was wanting to compile a 64 bit app. Well I looked around for the best and quickest way to get a 64 bit MinGW and decided to go with the MSYS2 version of Qt. I used `pacman -S mingw-w64-x86_64-qt-creator mingw-w64-x86_64-qt5` as noted on the [Installation Wiki](https://github.com/therecipe/qt/wiki/Installation-on-Windows).

After that, I had to set a few environment variables that I didn't see mentioned anywhere else. Perhaps we can have the Wiki updated with this info, but here is what I had to set...
`QT_MSYS2_DIR=path\to\my\MSYS2` and `QT_MSYS2_ARCH=amd64`

Now here I ran into a couple of issues.  One was that the `func QT_MSYS2_DIR()` in `qt/internal/utils/windows.go` was returning a path hardcoded to the `C:\` drive, but my MSYS2 install was on `E:\`. I have addressed this in PR #585.  The other issue was that I wanted to use the 64 bit MinGW, but for some reason the `QT_MSYS2_ARCH` was defaulting to `386` which is for the 32 bit version, thus I simply reset the evironment variable to `amd64`.  **EDIT: Actually I said that last sentence wrong. My `QT_MSYS2_ARCH` was actually not set at all, thus the `suffix` in `func QT_MSYS2_DIR()` was defaulting to `386`. My `runtime.GOARCH` is `amd64`, so perhaps we can implement this case as a condition in `func QT_MSYS2_DIR()` to handle the scenario correctly.?
Regarding issue #187 with @therecipe's comment:**

> I'm not sure if mingw-w64 works with the Qt libs, because those were compiled with mingw32.

> On windows you need to set GOARCH=386 and CGO_ENABLED=1 first to let the go compiler work along with the "default" mingw32 gcc.

**mine seems to work fine with `mingw-w64`. In fact my install of MSYS2 has two subdirectories, `mingw32` and `mingw64`, in which the `mingw64` directory is the only one with anything in it. With that, running `qtdeploy` wouldn't work with `GOARCH=386`, and I had to resort to setting `QT_MSYS_ARCH=amd64` and leave it with the default `runtime.GOARCH = amd64`.**

Everything seems to be working nicely since I went with this solution.

**Comment by therecipe** [comment]
Hey

Thank you for the write-up and also for the PR.

Yeah, you are right the docs don't seem to mention the msys2 env variables such as `QT_MSYS2`, `QT_MSYS2_DIR`, `QT_MSYS2_ARCH` and `QT_MSYS2_STATIC`.
The info was probably lost in the transition from the readme to the wiki, and I somehow missed that.
(Not that it makes a difference now, but it was present at some point https://github.com/therecipe/qt/blob/9720239949e766fb495002290a55a301a2e4f9e9/README.md#target-specific-infos-and-settings ...)

>My runtime.GOARCH is amd64, so perhaps we can implement this case as a condition in func QT_MSYS2_DIR() to handle the scenario correctly.?

Yes, the current behavior:
```
runtime.GOOS == 386 -> QT_MSYS2_DIR == C:\msys32\mingw32
runtime.GOOS == amd64 -> QT_MSYS2_DIR == C:\msys64\mingw32
```
is confusing.

I will apply this patch:
```diff
diff --git a/internal/utils/windows.go b/internal/utils/windows.go
index 76367880..b486b1b8 100644
--- a/internal/utils/windows.go
+++ b/internal/utils/windows.go
@@ -13,7 +13,7 @@ func QT_MSYS2() bool {
 
 func QT_MSYS2_DIR() string {
 	if dir, ok := os.LookupEnv("QT_MSYS2_DIR"); ok {
-		if QT_MSYS2_ARCH() == "amd64" {
+		if runtime.GOARCH == "amd64" || QT_MSYS2_ARCH() == "amd64" {
 			return filepath.Join(dir, "mingw64")
 		}
 		return filepath.Join(dir, "mingw32")
@@ -23,7 +23,7 @@ func QT_MSYS2_DIR() string {
 		prefix = "msys64"
 	}
 	suffix := "mingw32"
-	if QT_MSYS2_ARCH() == "amd64" {
+	if runtime.GOARCH == "amd64" || QT_MSYS2_ARCH() == "amd64" {
 		suffix = "mingw64"
 	}
 	return fmt.Sprintf("C:\\%v\\%v", prefix, suffix)
```

after I merged your PR to solve this.

And I will also continue to update the wiki.
