### ISSUE TITLE
The example app from "Getting started" section is 200M ?

### ISSUE THREAD

**Issue by matthieubellon** [therecipe/qt#588]
Hello,

Absolute newbie in the Qt world here. I followed the step by step guide and compiled the 'getting started' example app from MacOs to MacOS. I ended up with a 199M executable, is this expected ?
Shouldn't it be leaner ?
go version go1.9.4 darwin/amd64
and brew install Qt5
Thanks

**Comment by therecipe** [comment]
Hey

Which example did you compile? The widget or the qml one?
Also how did you compile it? `go build ...` or `qtdeploy build ...`

I just tested it, and the biggest I could get them was:

```
 92M	widgets
```

with plain `go build` with all debug infos and not stripped

with `qtdeploy`:
```
 22M	./widgets.app
 22M	./widgets.app/Contents
2,0M	./widgets.app/Contents/MacOS
3,5M	./widgets.app/Contents/PlugIns
4,0K	./widgets.app/Contents/Resources
 17M	./widgets.app/Contents/Frameworks
```
2mb in MacOS for the main executable

and

```
 68M	qml
```

with plain `go build` with all debug infos and not stripped

with `qtdeploy`:
```
 40M	.
 40M	./qml.app
 40M	./qml.app/Contents
1,3M	./qml.app/Contents/MacOS
6,4M	./qml.app/Contents/PlugIns
5,0M	./qml.app/Contents/Resources
 27M	./qml.app/Contents/Frameworks
```
1,3mb in MacOS for the main executable

**Comment by matthieubellon** [comment]
I went for the widget example with `qtdeploy build desktop`
I'll test with go build and see

I am really

**Comment by matthieubellon** [comment]
Thanks for your feedback

I went for the widget example with `qtdeploy build desktop`
I'll test with go build and see if I can match your results.

I am really new to the GUI world so I was expecting something really different than Electron for example which is a 100M at minimum for a "hello world". But I need to learn more here (for example I don't know yet how to strip debug infos)

You say the executable is 2M in your first set but you have to deliver the 22M "widget.app" container to your users right ?

**Comment by therecipe** [comment]
No problem.

Yeah, the 2mb is just the main executable but you will need to deliver the 22mb "*.app" folder/container for it to run on your users machine. (It's like 10mb zipped)
It will grow in size once you add more stuff, but the grow rate should be very moderate.
(There is one "qtmoc" issue that affects the size, but that's one of the things I will work on in the next weeks, and it's also not that drastic)

And if size is a greater concern, than there is always the possibility to compile a custom static version of Qt and use that instead.

Btw, to omit debug infos, and the symbol table you can simply run something like `go build -ldflags="-s -w"`, or maybe `go build -ldflags=all="-s -w"` (don't know if Go 1.9.4 requires that yet).
And then on macOS also `strip path/to/your/binary`

**Comment by matthieubellon** [comment]
Great, thanks for your time, feedback and tips, I'll dive deeper and continue my tests.
