### ISSUE TITLE
build error in last version: ld.exe: cannot find -lQt5Core(win10x64)

### ISSUE THREAD

**Issue by fcying** [therecipe/qt#59]
build ok in 54246e181ea03baae8e8bcaec106b57d6d518501

build error in last version

```shell
go run D:\workspace\go/src/github.com/therecipe/qt/internal/setup/test.go
------------------------test----------------------------
widgets\line_edits

test.widgets\line_edits
output:

build_1
output:# github.com/therecipe/qt/internal/examples/widgets/line_edits
C:/qt/Qt5.7.0/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lQt5Core
collect2.exe: error: ld returned 1 exit status

error:exit status 2
```

**Comment by therecipe** [comment]
Hey

Sorry, I hadn't test the last few commits on windows yet.
But it's fixed now https://github.com/therecipe/qt/commit/b253a6c012ade8eb20e90366342e1e2e36787f62

If you don't want to rebuild everything, you can just download and replace the deploy.go file (qt/internal/deploy/deploy.go) https://github.com/therecipe/qt/blob/master/internal/deploy/deploy.go

Then just run `go run %GOPATH%\src\github.com\therecipe\qt\internal\setup\test.go`, that will rebuild qtdeploy + qtmoc and also test the examples.

**Comment by fcying** [comment]
Now it's working well~
