### ISSUE TITLE
Dynamically adding widgets

### ISSUE THREAD

**Issue by krak3n** [therecipe/qt#590]
Hi

First of all thank you very much for this library :smile: I'm new to QT and UI programming in general, I'm more of a backend / server guy.

I'm having trouble creating dynamic widgets programmatically, my use case is a simple app that subscribes to an external pub/sub system and will play media such as videos and images. My first attempt was to get a simple full screen app running that plays video which I've got working below:

``` go
	widgets.NewQApplication(len(os.Args), os.Args)

	layout := widgets.NewQVBoxLayout()
	layout.SetContentsMargins(0, 0, 0, 0)

	widget := widgets.NewQWidget(nil, 0)
	widget.SetLayout(layout)

	window := widgets.NewQMainWindow(nil, 0)
	window.SetWindowState(core.Qt__WindowFullScreen) // Run in full screen
	window.SetCentralWidget(widget)

	vw := multimedia.NewQVideoWidget(widget)
	layout.AddWidget(vw, 0, 0)

	player := multimedia.NewQMediaPlayer(nil, multimedia.QMediaPlayer__VideoSurface)
	player.SetVideoOutput(vw)
	player.SetMedia(multimedia.NewQMediaContent2(core.QUrl_FromLocalFile(VIDEO_PATH)), nil)
	player.Play()

	window.Show()

	gui.QGuiApplication_Exec()
```

This works :+1: so now I'm trying to move to the next stage where the application is created and then some time later an event comes in to play a video, to simulate this I wrapped the video widget into a go routine and delayed by 5 seconds, this works on Linux but not Windows (which is my target platform).

``` go
	widgets.NewQApplication(len(os.Args), os.Args)

	layout := widgets.NewQVBoxLayout()
	layout.SetContentsMargins(0, 0, 0, 0)

	widget := widgets.NewQWidget(nil, 0)
	widget.SetLayout(layout)

	window := widgets.NewQMainWindow(nil, 0)
	window.SetWindowState(core.Qt__WindowFullScreen) // Run in full screen
	window.SetCentralWidget(widget)

	vw := multimedia.NewQVideoWidget(widget)
	layout.AddWidget(vw, 0, 0)

	player := multimedia.NewQMediaPlayer(nil, multimedia.QMediaPlayer__VideoSurface)
	player.SetVideoOutput(vw)

	go func() {
		time.Sleep(time.Second * 5)
		player.SetMedia(multimedia.NewQMediaContent2(core.QUrl_FromLocalFile(VIDEO_PATH)), nil)
		player.Play()
	}()

	window.Show()

	gui.QGuiApplication_Exec()
```

Is this the right way to go about doing something like this? Or am I totally baring up the wrong tree :dog2:  :deciduous_tree: 

Thank you,

Chris

**Comment by therecipe** [comment]
Hey

Yes, your code should usually work, since [setMedia](http://doc.qt.io/qt-5/qmediaplayer.html#setMedia) and [play](http://doc.qt.io/qt-5/qmediaplayer.html#play) are both labeled as slots so they should work across thread (and from a different go routine).

The general rule is, that you should only call functions that result in a visual change from the main thread. So every time you call a (non-slot/signal) function from another thread or go routine, you need to use a signal or slot to wrap the function call yourself.

You can do this with the help of [qtmoc](https://github.com/therecipe/qt/wiki/Available-Tools#qtmoc).
By creating a "subclass" and adding a custom signal (or slot).
Then you just need to wire up the signal to the functions you want to call and call the slot from within your go routine.

(I will update the docs in this and the following week, since there is a lot of outdated info floating around)

So something like this should work on windows as well:

```go
package main

import (
	"os"
	"time"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/multimedia"
	"github.com/therecipe/qt/widgets"
)

type CustomMediaPlayer struct {
	multimedia.QMediaPlayer

	_ func(VIDEO_PATH string) `signal:"PlayFile"`
}

func main() {

	widgets.NewQApplication(len(os.Args), os.Args)

	layout := widgets.NewQVBoxLayout()
	layout.SetContentsMargins(0, 0, 0, 0)

	widget := widgets.NewQWidget(nil, 0)
	widget.SetLayout(layout)

	window := widgets.NewQMainWindow(nil, 0)
	window.SetWindowState(core.Qt__WindowFullScreen) // Run in full screen
	window.SetCentralWidget(widget)

	vw := multimedia.NewQVideoWidget(widget)
	layout.AddWidget(vw, 0, 0)

	player := NewCustomMediaPlayer(nil, multimedia.QMediaPlayer__VideoSurface)
	player.SetVideoOutput(vw)
	player.ConnectPlayFile(func(VIDEO_PATH string) {
		player.SetMedia(multimedia.NewQMediaContent2(core.QUrl_FromLocalFile(VIDEO_PATH)), nil)
		player.Play()
	})

	go func() {
		time.Sleep(time.Second * 5)
		player.PlayFile(VIDEO_PATH)
	}()

	window.Show()

	widgets.QApplication_Exec()
}
```

But, since you example should work as well. I will need to look into this.
Which deployment method did you use for windows? The official version on a windows machine yourself of some of the docker images?

**Comment by krak3n** [comment]
Ah ok thank you for the reply, I'll try that :)

I have a Windows 7 laptop I'm using a test rig since windows 7 is also the target production system. I am building on a Linux (arch) system using the docker images:

```
qtdeploy -docker build windows_64_static ./cmd/myapp
```

**Comment by krak3n** [comment]
I'm also going to need to display static images as well, so I am wondering if a graphics scene maybe more appropriate.

For further context it's the system that powers this: https://www.youtube.com/watch?v=0SGk1cDSfZw

It runs on a powerful PC running Windows 7 with the most insane graphics card I've ever seen, we aren't responsible for the hardware so I'm stuck with Windows 7. It's currently implemented using web technology bundled in an Electron app and leaks memory like a sieve, we've tried to patch it but I don't think web tech is appropriate for the use case, which is why I'm looking into Qt with Go since I can just plumb go straight into our event system which is also written in go.

**Comment by krak3n** [comment]
Your solution above worked perfectly, thank you :+1: :smile:

**Comment by therecipe** [comment]
>Your solution above worked perfectly, thank you 👍 😄

Great :)

>For further context it's the system that powers this: https://www.youtube.com/watch?v=0SGk1cDSfZw

That's really awesome, it's always nice to see where this stuff gets used and knowing that it's used to power such an installation is really cool, thanks for letting me know :)

>I'm also going to need to display static images as well, so I am wondering if a graphics scene maybe more appropriate.

So I guess, you want to display some static image(s) before the show gets started?
Then yes, it's probably best to use a [graphicsview](http://doc.qt.io/qt-5/qgraphicsview.html) with a [graphicsscene](http://doc.qt.io/qt-5/qgraphicsscene.html) and then if you want to switch between the scene and the player you can use a [stackedlayout](http://doc.qt.io/qt-5/qstackedlayout.html) or some [stackedwidget](http://doc.qt.io/qt-5/qstackedwidget.html).

**Comment by krak3n** [comment]
Great, thanks for your help, I'll close the issue 💯
