### ISSUE TITLE
Unknown registered type

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#591]
Hi,

I have problem that doesn't occurred before. Somehow all my registered custom  qt types is not recognized on QML-side. it's fine on go-side though.

I put a simple example that I think represents the simplest code to reproduce the same problem. Please pull following repos to do that:
1. https://github.com/arknable/therecipe-issue
2. https://github.com/arknable/therecipe-issue-support

Please try to run `therecipe-issue` repo and you will see output as follows

```
arknables-MacBook-Pro:therecipe-issue arknable$ ./app
qml: user: Wolverine
qrc:///qml/main.qml:19: Error: Unknown method return type: QUser*
```

this used to works, but it seems QML doesn't recognized the real class of `User` component.

could you please help me check if that's related to binding issue ?

thanks for the help :).

**Comment by arknable** [comment]
sorry I forgot to mention, I'm using osx, Qt 5.9.1, and go 1.9.5.

**Comment by therecipe** [comment]
Hey, long time no see :)

Sorry, I need to write more test to catch this stuff sooner in the future.
But it should be fixed now with: https://github.com/therecipe/qt/commit/f1d82edc122bc2fae734ef735cccc74ff6cbed6e

**Comment by arknable** [comment]
hehe, nice to talk to you again. anyway I tried you fixed and it works. thanks.
