### ISSUE TITLE
String array recognized as QJSValue

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#594]
Hi,

I think there is a problem with `qtrcc`. My assignment value, which is array of string in QML, assigned to property typed array of `QVariant` now recognized as `QJSValue`.

```
qrc:///qml/main.qml:15:20: Unable to assign QJSValue to QVector<QVariant>
```

[This line](https://github.com/arknable/therecipe-issue/blob/master/qml/main.qml#L15) assigns array of string to `dataRoles` which has type [array of QVariant](https://github.com/arknable/therecipe-issue-support/blob/master/staff/user.go#L9). This used to work but now I got error I mentioned above.

Could you please check if there is a possible issue on `qtrcc` ?

Thanks

**Comment by therecipe** [comment]
Hey

Sorry, hoped that QVector and QList were simply interchangeable. But it seems like QLists provide a better integration with QML. (QVariantList like in this case, is one example)

I reverted the change, and your example should work now again with:  https://github.com/therecipe/qt/commit/78582b215527c5cced034c689938081edc1dce27

**Comment by arknable** [comment]
oh so that caused by the data type, I thought something else. ok thanks, I'll try this again.

**Comment by arknable** [comment]
it works ! thanks a lot. 👍
