### ISSUE TITLE
qt_stub with msys2 unable to change

### ISSUE THREAD

**Issue by a97077088** [therecipe/qt#598]
when setting  qt_stub in msys2 
you code:
///////////////////////////////////////
internal/utils/env.go
func QT_STUB() bool {
--
75 | return (os.Getenv("QT_STUB") == "true" \|\| QT_MSYS2()) && !QT_FAT()
//////////////////////
anytime check  true?

reason in qt_msys2 anytime is true

picture in after

////////////////////////////////////////////////////picture
$ qtsetup
time="2018-04-17T13:00:33+08:00" level=info msg="running: 'qtsetup prep'"
time="2018-04-17T13:00:33+08:00" level=info msg="running: 'qtsetup check windows' [docker=false] [vagrant=false]"
time="2018-04-17T13:00:33+08:00" level=info msg="GOOS:                        'windows'"
time="2018-04-17T13:00:33+08:00" level=info msg="GOARCH:                   *  'amd64'"
time="2018-04-17T13:00:33+08:00" level=info msg="GOVERSION:                   'go1.10.1'"
time="2018-04-17T13:00:33+08:00" level=info msg="GOROOT:                   *  'C:/msys64/mingw64/lib/go'"
time="2018-04-17T13:00:33+08:00" level=info msg="GOPATH:                   *  'C:/msys64/home/fbi/go'"
time="2018-04-17T13:00:33+08:00" level=info msg="GOBIN:                    *  'C:\\msys64\\mingw64\\lib\\go\\bin'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_HASH:                     '856baca876f2362b409bfd531e738f651453f0fd'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_VERSION:               *  '5.10.1'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_VERSION_MAJOR:            '5.10.1'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_DIR:                   *  'C:\\msys64\\mingw64'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_STUB:                  *  'true'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_DEBUG:                 *  'false'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_QMAKE_DIR:             *  'C:\\msys64\\mingw64\\bin'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_WEBKIT:                   'false'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_MSYS2:                 *  'true'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_MSYS2_DIR:                'C:\\msys64\\mingw64'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_MSYS2_ARCH:            *  'amd64'"
time="2018-04-17T13:00:33+08:00" level=info msg="QT_MSYS2_STATIC:             'false'"
time="2018-04-17T13:00:33+08:00" level=info msg="running: 'qtsetup generate windows' [docker=false] [vagrant=false]"

**Comment by therecipe** [comment]
Hey

I changed that with: https://github.com/therecipe/qt/commit/49a0021f932c3446cda48796e4871093d8189a66

(There will be some issue when installing the "designer" module, but I will look into that later)

**Comment by a97077088** [comment]
Thank you and hope you have a better tomorrow
