### ISSUE TITLE
Can you change the output directory in Windows?

### ISSUE THREAD

**Issue by fcying** [therecipe/qt#61]
default location is `C:\WINDOWS`, it need permissions: `output:mkdir C:\WINDOWS\go-build240713163: Access is denied.`

You can use this `%temp%`  instead of it.

**Comment by therecipe** [comment]
Hey

Fixed it with https://github.com/therecipe/qt/commit/944221dbc1d520c75ccbb8723339b72e0e8a5f0f
This also removes the need to run the `setup.bat` and `qtdeploy` with admin rights (which bothered me all the time)

Thanks for reporting :)

**Comment by fcying** [comment]
It's work, thanks~~
