### ISSUE TITLE
qtdeploy creates mounted folders as root (minor bug)

### ISSUE THREAD

**Issue by arsham** [therecipe/qt#613]
Hi,
`qtdeploy -docker` with following images creates the mount points in the deploy folder as root, which requires `root` access to clean up:
```
windows_64_static
windows_32_static
```
However, the following images are fine:
```
linux
windows_64_shared
windows_32_shared
```

Thanks.

**Comment by therecipe** [comment]
Hey

This should have been fixed with: https://github.com/therecipe/qt/commit/491342284b02f5b27d5a19d030e5e446727b464d#diff-16e44658fb89a392fbb49ad74fdc4570R177
