### ISSUE TITLE
How do I use CustomEvents for layouts without a struct?

### ISSUE THREAD

**Issue by MTRNord** [therecipe/qt#619]

**Comment by therecipe** [comment]
Hey

Sorry, I'm not quite sure what you mean.
Could you give me a little bit more detail?

**Comment by MTRNord** [comment]
Hi I think I resolved this myself and forgot to close it. What I wanted to ask was I think how I can use the CustomEvents function in the binding instead of having to make a hole new QObject struct and in there define slots/signals (I hope I dont mix namings. I am not a C coder so I dont know which term is correct to use when reffering to events in QT)
