### ISSUE TITLE
Could you move the temp file to deploy folder?

### ISSUE THREAD

**Issue by fcying** [therecipe/qt#62]
when i build a qtquick application, it will auto generate some files:
some qrc file , there will be autodelete after build.
a lot of moc file, stay in the src folder, they make src folder unclean.

**Comment by renannprado** [comment]
can't you `.gitignore` them?

**Comment by therecipe** [comment]
Hey

The moc* files are now removed when they are not needed anymore https://github.com/therecipe/qt/commit/96f237ab0ac318df2979cd48370d891c6488be6b
If you want to use them (for a manual build with `go build`), you can still invoke "qtmoc" to generate them

btw: you may need to export/set the env variable `QT_DIR` for the Qt install location before running the setup

**Comment by fcying** [comment]
@renannprado  yes , i use `.gitignore` file now,  I just not like unlcean workspace,

**Comment by fcying** [comment]
@therecipe 
I always thought that only used `qtdeploy`...

I try to use go build, it make some error.

```shell
$ qtmoc.exe
$ go build
main.go:6:2: no buildable Go source files in D:\workspace\go\src\github.com\therecipe\qt\core
main.go:7:2: no buildable Go source files in D:\workspace\go\src\github.com\therecipe\qt\gui
main.go:8:2: no buildable Go source files in D:\workspace\go\src\github.com\therecipe\qt\quick
```

**Comment by therecipe** [comment]
You need to set `GOARCH=386` and `CGO_ENABLED=1` before you run `go build` (CGO_ENABLED is somehow not enabled by default on windows)

and you also need to run `windeployqt.exe` (C:\Qt\Qt5.7.0\5.7\mingw53_32\bin\windeployqt.exe),
because windows won't find the libs otherwise

**Comment by fcying** [comment]
I set `CGO_ENABLED=1` , it can be build.
I see the `go env`, when i set `set GOARCH=386`, the `CGO_ENABLED` will change to `0`.

I test `bridge2` by `go build`, it can create exe file, but run it only display a blank window.
use `qtdeploy` work ok.

**Comment by therecipe** [comment]
Yes, `go env` it behaving strange only my side also.
Just make sure you run `set GOARCH=386` and `set CGO_ENABLED=1` before every `go build`

And the quick and qml examples require additional files (the qrc* files), which can be only created with qtdeploy at the moment.

**Comment by fcying** [comment]
ok,i know~

Thanks for the help~~
