### ISSUE TITLE
How to use setContextProperty?

### ISSUE THREAD

**Issue by ilya-fedin** [therecipe/qt#621]
Hello! I need to use the Go function in QML, but I can't figure out how to do this. The example from https://github.com/therecipe/examples/blob/master/advanced/qml_quick/ctxproperty/main.go doesn't work.
I tried to change NewCtxObject(nil) to new(CtxObject) and comment the line t.SetSomeString - then the example compiles without errors, but when I click the button, it still gives an error:
`TypeError: Cannot call method 'clicked' of null`

**Comment by therecipe** [comment]
Hey

You will need to use `New*` functions instead of the standard Go `new(*)` function for this to work.
And you will also need to run `qtmoc` once before using `go build ...`. (Or `qtdeploy`)

**Comment by ilya-fedin** [comment]
Yes, I already understood that :)
Thank you!
