### ISSUE TITLE
QT detecting Linux on MacOS

### ISSUE THREAD

**Issue by joshuafbadams** [therecipe/qt#627]
![screen shot 2018-05-23 at 9 42 11 am](https://user-images.githubusercontent.com/7192015/40435848-d9ab3c96-5e6e-11e8-9d14-3a544a10a813.png)

I've installed the docker linux version, and decided against it. Removed docker and all remaining files, all qt files, and repos. Rebooted, fresh qt install, no docker. Trying to detect the Linux distro?

**Comment by therecipe** [comment]
Maybe try to run: `env | grep QT` to see which env variables you have exported.
I'm pretty sure you have set `QT_PKG_CONFIG=true`

**Comment by joshuafbadams** [comment]
You are correct. Thanks!
