### ISSUE TITLE
Designing GUI, QT Quick Controls 2 and QT Designer

### ISSUE THREAD

**Issue by qZanity** [therecipe/qt#631]
Hi, Thanks for providing a great binding for Qt.

I've developed with Qt C++ in the past, Before i start digging into stuff with golang, Is it possible to use QT Designer to create UI's and use them with golang and this package?

Furthermore, Can we also use CSS to style the UIs that is being used in golang?

Finally are there are examples for skinning UIs with the QT Quick Controls 2 Imagine style, As mentioned here: http://blog.qt.io/blog/2017/11/23/qt-quick-controls-2-imagine-style/

Thanks.

**Comment by therecipe** [comment]
Hey

Yes, you can use the *.qml files created by the designer the same way as you would do with C++.
And yes, you can also style the native widgets with Qt's css syntax.

But no sorry, there are no examples for the imagine style yet.
However, I'm pretty sure that it's working.

Here are some examples that might help you, if you are new to Go: https://github.com/therecipe/examples/tree/master/basic/qml
https://github.com/therecipe/qt/tree/master/internal/examples/qml/material
