### ISSUE TITLE
undefined: unsupported_goEnum

### ISSUE THREAD

**Issue by AnyCPU** [therecipe/qt#634]
OS: Linux/Ubuntu 16.04, KDE Neon 64 bit
GO: 1.10.2
Qt: 5.11.0

I got this error:

> ERRO[2020] failed to run command                         cmd="go build -p 1 -v -ldflags=all=\"-s\" \"-w\" -o /home/dev/go/src/github.com/therecipe/qt/internal/examples/qml/application/deploy/linux/application -tags=\"minimal\"" dir=/home/dev/go/src/github.com/therecipe/qt/internal/examples/qml/application env="GOPATH=/home/dev/go GOROOT=/usr/local/go CGO_CFLAGS_ALLOW=.* CGO_CXXFLAGS_ALLOW=.* CGO_LDFLAGS_ALLOW=.* GOOS=linux PATH=/home/dev/bin:/home/dev/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dev/go/bin:/usr/local/go/bin GOARCH=amd64 CGO_ENABLED=1" error="exit status 2" func=RunCmd name="build for linux on linux"
github.com/therecipe/qt
github.com/therecipe/qt/core
># github.com/therecipe/qt/core
>../../../../core/core-minimal.go:4341: undefined: unsupported_goEnum

I think the code gen has troubles working on this Qt's enum - http://doc.qt.io/qt-5/qt.html#InputMethodQuery-enum

Also I got this error - https://github.com/therecipe/qt/issues/628 , it can be easily fixed by uncommenting a one line in the source code.

@therecipe I have read your plans about the mid june's update, so I'm waiting for it too :) Thanks for your job!

**Comment by therecipe** [comment]
Sorry, took a little longer but 5.11.x should work now with https://github.com/therecipe/qt/commit/5355937d17e9eee62460706cb9a033180014400e

**Comment by AnyCPU** [comment]
@therecipe thank you very much
