### ISSUE TITLE
android: stderr - undefined reference

### ISSUE THREAD

**Issue by AnyCPU** [therecipe/qt#636]
OS: Linux/Ubuntu 16.04
Go: 1.10.2
Qt: 5.10.1

I got:

>ERRO[0009] failed to load /home/dev/go/src/github.com/therecipe/qt/scripttools/Mfile  error="open /home/dev/go/src/github.com/therecipe/qt/scripttools/Mfile: no such file or directory"
ERRO[0013] failed to run command                         cmd="go build -p 4 -v -ldflags=all=\"-s\" \"-w\" -o /home/dev/go/src/github.com/therecipe/qt/internal/examples/qml/application/deploy/android/libgo_base.so -tags=\"android\" \"minimal\" -pkgdir /home/dev/go/pkg/android_android_arm -buildmode c-shared" dir=/home/dev/go/src/github.com/therecipe/qt/internal/examples/qml/application env="GOARCH=arm CC=/home/dev/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc CXX=/home/dev/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ CGO_LDFLAGS=--sysroot=/home/dev/android-ndk-r17/platforms/android-16/arch-arm -llog CGO_CFLAGS_ALLOW=.* GOOS=android CGO_ENABLED=1 CGO_CPPFLAGS=-isystem /home/dev/android-ndk-r17/platforms/android-16/arch-arm/usr/include CGO_CXXFLAGS_ALLOW=.* GOARM=7 CGO_LDFLAGS_ALLOW=.* PATH=/home/dev/bin:/home/dev/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/dev/go/bin GOPATH=/home/dev/go GOROOT=/usr/local/go" error="exit status 2" func=RunCmd name="build for android on linux"
errors
internal/race
runtime/internal/sys
unicode
unicode/utf8
sync/atomic
runtime/internal/atomic
math
internal/testlog
runtime
runtime/cgo
strconv
># runtime/cgo
>gcc_android.c:30: error: undefined reference to 'stderr'
gcc_libinit.c:30: error: undefined reference to 'stderr'
gcc_linux_arm.c:25: error: undefined reference to 'sigfillset'
gcc_util.c:19: error: undefined reference to 'stderr'
collect2: error: ld returned 1 exit status
sync
io
reflect
syscall
bytes
strings
bufio
time
internal/poll
os
fmt
log

Could we do something with that?

**Comment by AnyCPU** [comment]
I have installed the API 16 and API 27. All seems ok, but there is strange trouble in settings or directory structure. That is why I have to copy some header files to the API 16&27 directories manually to make things work. After that Qt itself and Android builds work and run well.

**Comment by therecipe** [comment]
Will close this now, since the update to Qt 5.12 (https://github.com/therecipe/qt/commit/5746a84fb25d76c6b43b253a73f3aaa2344b03cb) made newer versions (the one containing a clang compiler) work with this binding.
