### ISSUE TITLE
How can I make compile faster ?

### ISSUE THREAD

**Issue by dongnengyu** [therecipe/qt#639]
Hi, thanks for your wonderful work, l love it very much!

But it took me a lot of time to compile a hello world, so is there any possible to make the compilation faster?

**Comment by arsham** [comment]
Have a look at [this](https://github.com/therecipe/qt/wiki/Faster-builds-(Linux)) wiki page.

**Comment by dongnengyu** [comment]
@arsham thanks, i used the ccache, but it seems like does not help a lot.

**Comment by dongnengyu** [comment]
@arsham I will have a try in tomorrow morning, thanks again.
