### ISSUE TITLE
missing CGO_LDFLAGS_ALLOW

### ISSUE THREAD

**Issue by morriswinkler** [therecipe/qt#644]
Installation fails on Linux 
```
INFO[0571] installing full qt/sensors                   
ERRO[0635] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/sensors" env="CGO_LDFLAGS_ALLOW=.* CGO_ENABLED=1 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/bin:/home/morris/go/bin GOPATH=/home/morris/go GOROOT=/usr/lib/go-1.10 CGO_CXXFLAGS_ALLOW=.* GOOS=linux GOARCH=amd64 CGO_CFLAGS_ALLOW=.*" error="exit status 2" func=RunCmdOptionalError name="install sensors"
github.com/therecipe/qt
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
/usr/bin/x86_64-linux-gnu-ld: cannot find -lpulse-mainloop-glib
/usr/bin/x86_64-linux-gnu-ld: cannot find -lpulse
/usr/bin/x86_64-linux-gnu-ld: cannot find -lglib-2.0
/usr/bin/x86_64-linux-gnu-ld: cannot find -lGL
```
Works with 
```
CGO_LDFLAGS_ALLOW=".*" qtsetup 
```

**Comment by akhenakh** [comment]
documented here https://github.com/therecipe/qt/wiki/Installation#go--110-specific-environmental-variables

**Comment by morriswinkler** [comment]
Sorry I haven't got the time to read the code, but I have read the code when I opened the bug, and correct me but somehow the other two env flags where set within the qtsetup executable. If i am wrong please go ahead and close the bug, otherwise, why isn't this flag set within the executable.

**Comment by therecipe** [comment]
@morriswinkler
Yeah the 3 `*_ALLOW` env flags are automatically used during the setup.
 
But the initial issue looks more like your system is/was missing some libs. (pulse, glib2.0)

You would have just needed to install them with something like this on ubuntu/debian:
```
sudo apt-get -y install build-essential libglu1-mesa-dev libpulse-dev libglib2.0-dev
```

**Comment by morriswinkler** [comment]
Strange looks like I posted the wrong error, strange. 
I guess I should have spent more time on nailing this one down. 

Let's close the issue, if I ran into it again I will investigate it further.

Thanks for that great library.
