### ISSUE TITLE
QQmlListProperty inside a context variable

### ISSUE THREAD

**Issue by jaylevin** [therecipe/qt#648]
Hello, I am having a simple issue trying to send a `[]MyType` from Go to QML.
This is my setup:

```
 type Key struct {
 	Email string
 	Name  string
 }
 
 type KeyList struct {
 	core.QObject
 	_ []Key `property: "keys"`
 	_ func() `constructor:"init"`
 }

 func (t *KeyList) init() {
 	log.Println("Something happened!")
 }

 func main() {

     // window/qml engine initialization omitted

     keyList := NewKeyList(nil)
     keyList.SetProperty("keys", ........)? // not sure if this is how we d
 }

```
My question is: 

After I have exported the `[]Key` field as a QML property, I want to be able to add a `Key` to the `keyList` variable defined in the main function. How do I do this? Is it even possible? All the examples show the case where you want the user to add things to the ListView from the UI.

Also, is there any way to call a QObject's function defined in QML from Go?

Thank you very much.

**Comment by therecipe** [comment]
Hey

>After I have exported the []Key field as a QML property, I want to be able to add a Key to the keyList variable defined in the main function. How do I do this? Is it even possible?

Yes, something like this should work: `keyList.SetKeys([]Key{{"someEmail", "someName"}})`

>Also, is there any way to call a QObject's function defined in QML from Go?

Yes, you will need to add a new signal to your keyList for example: 
```
_ func(something string) `signal:"someSignal"`
```
and then connect it on the QML side with something like this:

```qml
	Connections {
		target: ctxObject //<- name of the context property object you passed to QML
		onSomeSignal: {
			console.log(something)
		}
	}
```
then you can call it from Go by using the generated "SomeSignal" function.

---

Also because you wrote about passing Go structs to QML, I edited the "ctxproperty" example to show you how to do it.

First thing is you will need to Qtfy your Key struct by subclassing QObject and then exporting your properties with the property struct tag.
Then because the QQmlListProperty support isn't fully working yet you will need to change your keys property from:
```
_ []Key `property: "keys"`
```
to:
```
_ []*core.QObject `property:"keys"`
```
And lastly, when you want to change the List from within QML you will need to copy it first and then reassign the modified list afterwards. 
```
			var listCopy = ctxObject.keys
			listCopy.push(Qt.createQmlObject('import CustomTypes 1.0; Key {name: "newName"; email: "newEmail"}', ctxObject))
			ctxObject.keys = listCopy
```

Here is a fully working example:
```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/quick"
	"github.com/therecipe/qt/widgets"
)

func init() {
	Key_QmlRegisterType2("CustomTypes", 1, 0, "Key")
}

type Key struct {
	core.QObject

	_ string `property:"name"`
	_ string `property:"email"`
}

type CtxObject struct {
	core.QObject

	_ func() `constructor:"init"`

	_ string `property:"someString"`

	_ []*core.QObject `property:"keys"`
}

func (t *CtxObject) init() {
	t.SetSomeString("click me!\nand look into the console")

	newKey := NewKey(nil)
	newKey.SetEmail("someEmail")
	newKey.SetName("someName")
	t.SetKeys([]*core.QObject{newKey.QObject_PTR()})

	t.ConnectKeysChanged(func(keys []*core.QObject) {
		for i, keyObject := range keys {
			key := NewKeyFromPointer(keyObject.Pointer())
			println("key", i, key.Name(), key.Email())
		}
	})
}

func main() {
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)

	app := widgets.NewQApplication(len(os.Args), os.Args)

	view := quick.NewQQuickView(nil)
	view.SetTitle("ctxproperty Example")
	view.SetResizeMode(quick.QQuickView__SizeRootObjectToView)
	view.RootContext().SetContextProperty("ctxObject", NewCtxObject(nil))
	view.SetSource(core.NewQUrl3("qrc:/qml/main.qml", 0))
	view.Show()

	app.Exec()
}
```
```qml
import QtQuick 2.10
import QtQuick.Controls 2.3

Item {
	width: 250
	height: 200

	Button {
		anchors.fill: parent
		text: ctxObject.someString
		onClicked: {
			console.log(ctxObject.keys[0].name, ctxObject.keys[0].email)

			var listCopy = ctxObject.keys
			listCopy.push(Qt.createQmlObject('import CustomTypes 1.0; Key {name: "newName"; email: "newEmail"}', ctxObject))
			ctxObject.keys = listCopy

			console.log(ctxObject.keys)
		}
	}
}
```
