### ISSUE TITLE
qtsetup failed partially on mac os

### ISSUE THREAD

**Issue by W-B-S** [therecipe/qt#649]
ERRO[1170] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/remoteobjects" env="CGO_CXXFLAGS_ALLOW=.* CGO_LDFLAGS_ALLOW=.* GOOS=darwin GOARCH=amd64 PATH=/usr/local/opt/qt/bin:/usr/local/opt/openssl/bin:/Users/wsli/.opam/system/bin:/usr/local/opt/openssl/bin:/Users/wsli/.cargo/bin:/usr/local/Cellar/ant/1.9.6/bin:/Users/wsli/tools/adt-bundle-mac-x86_64-20140702/sdk/tools:/Users/wsli/tools/adt-bundle-mac-x86_64-20140702/sdk/platform-tools:/Users/wsli/tools/adt-bundle-mac-x86_64-20140702/sdk:/Users/wsli/tools/adt-bundle-mac-x86_64-20140702/sdk/ndk-bundle:/Users/wsli/Desktop/masschat/cocos2d-x-sourcecode/templates:/Users/wsli/Desktop/masschat:/Users/wsli/Desktop/masschat/cocos2d-x-sourcecode/tools/cocos2d-console/bin:/Users/wsli/tools/adt-bundle-mac-x86_64-20140702/sdk/platform-tools:/usr/local/opt/maven/bin:/usr/local/opt/qt/bin:/usr/local/opt/openssl/bin:/Users/wsli/.opam/system/bin:/usr/local/opt/openssl/bin:/Users/wsli/.cargo/bin:/usr/local/Cellar/ant/1.9.6/bin:/Users/wsli/tools/adt-bundle-mac-x86_64-20140702/sdk/tools:/Users/wsli/tools/adt-bundle-mac-x86_64-20140702/sdk/platform-tools:/Users/wsli/tools/adt-bundle-mac-x86_64-20140702/sdk:/Users/wsli/tools/adt-bundle-mac-x86_64-20140702/sdk/ndk-bundle:/Users/wsli/Desktop/masschat/cocos2d-x-sourcecode/templates:/Users/wsli/Desktop/masschat:/Users/wsli/Desktop/masschat/cocos2d-x-sourcecode/tools/cocos2d-console/bin:/Users/wsli/tools/adt-bundle-mac-x86_64-20140702/sdk/platform-tools:/usr/local/opt/maven/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS::/usr/local/go/bin:/Users/wsli/go/bin::/usr/local/opt/go/libexec/bin:/Users/wsli/go/bin GOPATH=/Users/wsli/go GOROOT=/usr/local/Cellar/go/1.10.3/libexec CGO_CFLAGS_ALLOW=.* CGO_ENABLED=1" error="exit status 2" func=RunCmdOptionalError name="install remoteobjects"
github.com/therecipe/qt
github.com/therecipe/qt/remoteobjects
# github.com/therecipe/qt/remoteobjects
remoteobjects.cpp:40:10: fatal error: 'QRemoteObjectPersistedStore' file not found

**Comment by therecipe** [comment]
Hey

Which Qt version did you test the binding with?

**Comment by therecipe** [comment]
I will close this now, please reopen if this is still relevant
