### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by jaylevin** [therecipe/qt#651]
Hi! After carefully examining the provided examples, I have noticed that the only [example](https://github.com/therecipe/examples/tree/master/advanced/qml_quick/listview) for QQuick ListView shows how to dynamically add/edit/delete list items by calling the model's respective add/edit/delete slots defined in Go from QML. 

This is awesome, however I'm looking for a quick example on best practices to dynamically create/edit items inside of a ListModel from within Go. Again, the current listview examples only invoke the add, edit, etc slots from within QML. 

Where I'm lost:

1. I could instantiate the subclassed CustomListModel inside of Golang and make it a property of a context property, then I would have access to it from within Go, to be able to invoke any slots

2. But I could also instantiate the CustomListModel inside QML (Like the current example does) and then somehow emit some connected signals from Go to QML, for instance:

In QML:
```
Connections {
	target: QmlBridge

	onAddItem: {
		listView.customListModel.add(item)
	}
}
```

In Go:
```
type QmlBridge struct {
	core.QObject
 
	_ func()                           `constructor:"init"`

	_ func(item *models.ListItem) bool `signal:"addItem,auto"`
}

main {
	.....
	qmlBridge := NewQmlBridge(nil)

	//setting context property omitted
        
       .... some time later in another goroutine ....
	for _, item := range items {
		qmlBridge.addItem(item)
	}
}
```

Any advice on which direction I should go would be much appreciated,
Thanks

**Comment by therecipe** [comment]
Hey

What about saving the reference/pointer to the CustomListModel when the constructor gets called within Go after the the CustomListModel was instantiate inside QML?
Then you can simply use it to call the add, edit and remove function from within Go.
Instead of going through`Go -> QML -> Go` for each call and also using an extra helper struct.

```patch
diff --git a/advanced/qml_quick/listview/main.go b/advanced/qml_quick/listview/main.go
index e3f3345..8eba508 100644
--- a/advanced/qml_quick/listview/main.go
+++ b/advanced/qml_quick/listview/main.go
@@ -29,6 +29,9 @@ type CustomListModel struct {
 }
 
 func (m *CustomListModel) init() {
+
+	//simply save "m" somewhere to access it later from Go
+
 	m.modelData = []ListItem{{"john", "doe"}, {"john", "bob"}}
 
 	m.ConnectRowCount(m.rowCount)
```
