### ISSUE TITLE
module "QtQuick.VirtualKeyboard" is not installed rpi3

### ISSUE THREAD

**Issue by akhenakh** [therecipe/qt#654]
Importing VirtualKeyboard generates a runtime error when compiled with docker rpi3, but works when compiled for amd64 linux

`import QtQuick.VirtualKeyboard 2.3`

it seems `qml/QtQuick/VirtualKeyboard/Styles/libqtvirtualkeyboardstylesplugin.so` is missing in the deployment

**Comment by therecipe** [comment]
Hey

The raspberry images should contain and deploy the virtual keyboard plugin now with: https://github.com/therecipe/qt/commit/c963a694b534bfcbfa5bc783f0528e0e46321c26#diff-0fb60d87bb752dd233ffd5a15afe2eaaR12

**Comment by akhenakh** [comment]
solved thank you
