### ISSUE TITLE
Goland issue with QT Bindings

### ISSUE THREAD

**Issue by JasonWeise** [therecipe/qt#659]
Hi Team

Is there a method to getting JetBrains Goland to work with these QT bindings.

I have duplicated the internal/examples/draw_nav_x package and opened in Goland and am getting unresolved reference errors on the following lines in main.go:
16: gui.NewQGuiApplication(len(os.Args), os.Args)
38: gui.QGuiApplication_Exec()

I have even tried creating a clean package to import a QML file using the examples as a guide and get the exact same lines as unresolved references.

Is there any way to resolve this with Goland or is likely just not compatible with these bindings?

Note: All my other Go projects work fine with Goland but I could be missing a vital step.

Thanks in advance.

**Comment by JasonWeise** [comment]
For anyone having an issue with Goland and these QT bindings showing "unresolved reference errors" I have found a solution to the issue.

Goland caps the size of a source file it will index for CodeInsights (by default I think it is 2500kb)
With this default size github.com/therecipe/qt/gui/gui.go won't be indexed as it is over 5MB in size.

To resolve this just increase the allowable file size that can be indexed by changing and IDE configuration option.

This file on MacOS can be found at:
`Applications/GoLand.app/Contents/bin/idea.properties`

Then edit the following line to be a larger size (I made mine 99999) and restart IDE:
`idea.max.intellisense.filesize=2500`

Hope this helps someone else with the same issue

**Comment by mwegner** [comment]
Thanks for the pointer!  I was hitting the same issue.

For anyone who comes next, a more durable way to define custom properties is via a preferences file.  The easiest way to edit/make one is via any of the JetBrains IDEs.  Just do Help -> Edit Custom Properties (on any platform).

**Comment by therecipe** [comment]
Will close this now, for future reference more infos can be found here: https://github.com/therecipe/qt/wiki/FAQ#how-to-make-ides-code-completion-works-

**Comment by MostHated** [comment]
:+1: :+1: :+1:  Thanks a ton for that link. I was having similar issues with several projects I downloaded to try out
