### ISSUE TITLE
QTableWidget Warn

### ISSUE THREAD

**Issue by nntaoli** [therecipe/qt#665]
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)

**Comment by therecipe** [comment]
Hey

QVector should be registered by default.
Can you maybe provide some small code snippet so I can reproduce the issue?

**Comment by nntaoli** [comment]
compile no warn but runtime warn 
```
listView = widgets.NewQTableWidget2(22, 4, nil)
listView.SetHorizontalHeaderLabels([]string{"a", "b", "c", "d"})
listView.SetEditTriggers(widgets.QAbstractItemView__NoEditTriggers)
item := widgets.NewQTableWidgetItem2("12.02", 0)
listView.SetItem(i, 0, rateItem)
```

**Comment by nntaoli** [comment]
After testing and observation, it is impossible to determine where the problem occurred

**Comment by m3nu** [comment]
Getting the same error when working with a `QTableWidget`. No clear what line triggers it. There is one error message for each column. No matter how much data/rows are in the table.
