### ISSUE TITLE
error while using minimal compiling

### ISSUE THREAD

**Issue by renannprado** [therecipe/qt#67]
I was trying to compile using the `minimal` option in `qtdeploy`, but got the below error.

![image](https://cloud.githubusercontent.com/assets/2359543/19407638/8206d652-927e-11e6-9094-ef57aab62f20.png)

The code I tried to compile is the same as the one in the readme.

```go
package main

import (
    "os"

    "github.com/therecipe/qt/core"
    "github.com/therecipe/qt/widgets"
)

func main() {
    widgets.NewQApplication(len(os.Args), os.Args)

    //create a button and connect the clicked signal
    var button = widgets.NewQPushButton2("Click me!", nil)
    button.ConnectClicked(func(flag bool) {
        widgets.QMessageBox_Information(nil, "OK", "You clicked me!", widgets.QMessageBox__Ok, widgets.QMessageBox__Ok)
    })

    //create a layout and add the button
    var layout = widgets.NewQVBoxLayout()
    layout.AddWidget(button, 0, core.Qt__AlignCenter)

    //create a window, add the layout and show the window
    var window = widgets.NewQMainWindow(nil, 0)
    window.SetWindowTitle("Hello World Example")
    window.SetMinimumSize2(200, 200)
    window.Layout().DestroyQObject()
    window.SetLayout(layout)
    window.Show()

    widgets.QApplication_Exec()
}
```

If I do not put the `minimal` it or use `go build`, it compiles just fine.

Tested in Ubuntu 14

**Comment by fcying** [comment]
try to use `qtdeploy build desktop . minimal`

**Comment by therecipe** [comment]
Hey

fcying's comment should work. If you omit the "." qtdeploy will look in "./minimal" and complains because it can't find any files.
Also the minimal flag is deprecated and will be removed, because all builds are minimal now by default.
The folders in your "deploy" folder should all have the "_minimal" suffix.

@fcying Thanks.

**Comment by renannprado** [comment]
@therecipe @fcying my bad, I didn't pay attention to the parameter before `minimal`... thanks! Yes the folder did have the `minimal` in its name.

@therecipe shouldn't we have a channel for this library in `gophers` slack?
