### ISSUE TITLE
MacOS core.Qt__WindowMinimized Don‘t work ？

### ISSUE THREAD

**Issue by nntaoli** [therecipe/qt#670]
mainWindow.SetWindowState(core.Qt__WindowMinimized) on macos don't work ? Cannot minimize window ？Do you have a solution? thanks

**Comment by therecipe** [comment]
Hey

Can you maybe provide an example so I can reproduce the issue?
Because it usually should work:
```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	window := widgets.NewQMainWindow(nil, 0)

	button := widgets.NewQPushButton2("click me", nil)
	button.ConnectClicked(func(bool) {
		window.SetWindowState(core.Qt__WindowMinimized)
	})

	window.SetCentralWidget(button)
	window.Show()

	widgets.QApplication_Exec()
}
```

Also maybe try to call `SetWindowState` from within the main (gui) thread, for example from within a slot or signal.

**Comment by nntaoli** [comment]
`
 package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	window := widgets.NewQMainWindow(nil, core.Qt__FramelessWindowHint)

	button := widgets.NewQPushButton2("click me", nil)
	button.ConnectClicked(func(bool) {
		window.SetWindowState(core.Qt__WindowMinimized)
	})

	window.SetCentralWidget(button)
	window.Show()

	widgets.QApplication_Exec()
}
`

SetWindowFlag core.Qt__FramelessWindowHint don't work

**Comment by therecipe** [comment]
Looked into this again and it seems like it's already reported here: https://bugreports.qt.io/browse/QTBUG-65637

So there is nothing I can do atm, but you can work around this by downloading the macOS 10.12 sdk.

Just download "MacOSX10.12.sdk.tar.xz" from here: https://github.com/phracker/MacOSX-SDKs/releases/tag/10.13 and unpack it in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/` then rename the newer 10.13 sdk to something else and re-run qtsetup.

**Comment by nntaoli** [comment]
thank you

**Comment by therecipe** [comment]
I looked into this again, and it's still broken with Qt 5.13
But there was a work around posted in the meantime, which seems to work.

Just create a new package with these files:

`window_darwin.go`
```go
// +build darwin

package window

//void allowMinimize(void*);
import "C"
import "unsafe"

func AllowMinimize(winId uintptr) {
	C.allowMinimize(unsafe.Pointer(winId))
}
```

`window_darwin.m`
```obj-c

#import <AppKit/AppKit.h>

void allowMinimize(void* w)
{
	[[(NSView*)(w) window] setStyleMask:NSWindowStyleMaskMiniaturizable];
}
```

`window.go`
```go
// +build !darwin

package window

func AllowMinimize(uintptr) {}
```

And the following example should work:

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"

	"path/to/window" //<-- fix the import first
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	w := widgets.NewQPushButton2("click me", nil)

	w.SetWindowFlags(core.Qt__FramelessWindowHint)
	window.AllowMinimize(w.WinId())

	w.ConnectClicked(func(bool) {
		w.ShowMinimized()
		//or w.SetWindowState(core.Qt__WindowMinimized)
	})

	w.Show()

	widgets.QApplication_Exec()
}
```
