### ISSUE TITLE
qtdeploy -docker build android connect: permission denied

### ISSUE THREAD

**Issue by xyboy0909** [therecipe/qt#673]
ERRO[0000] failed to run command                         cmd="docker run --rm -e IDUG=1000:1000 -v /home/huoshu/golib:/media/sf_GOPATH0 -v /home/huoshu/goproject:/media/sf_GOPATH1 -e GOPATH=/home/user/work:/media/sf_GOPATH0:/media/sf_GOPATH1 -i therecipe/qt:android qtdeploy -debug -ldflags= -tags= build android /media/sf_GOPATH0/src/huoshu.xin/examples-go-qt/deploy/android" dir= env= error="exit status 126" func=RunCmd name="deploy binary for android on linux with docker"
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.30/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

How to solve it when use docker image?

**Comment by therecipe** [comment]
Will close this now, for future reference https://github.com/therecipe/qt/wiki/Deploying-Linux-to-Android#docker-deployment
