### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets

### ISSUE THREAD

**Issue by idoor88** [therecipe/qt#678]
I followed this link: https://github.com/therecipe/qt/wiki/Getting-Started and did the basic examples as the following, but I got Project ERROR: Unknown module(s) in QT: webkit webkitwidgets, and the hello widgets dialog window did show up, so please help me resolve the error, thanks. IDoor

go get -d -v github.com/therecipe/examples/...
cd $GOPATH/src/github.com/therecipe/examples

qtdeploy test desktop ./basic/widgets
ERRO[0011] failed to run command                         cmd="/usr/local/opt/qt5/bin/qmake -o Mfile ../webkit.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=release" dir=/Users/d2233/workspace/go/src/github.com/therecipe/qt/webkit env= error="exit status 3" func=RunCmdOptional name="run qmake for darwin on darwin"
Info: creating stash file /Users/d2233/workspace/go/src/github.com/therecipe/qt/webkit/.qmake.stash
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets

ERRO[0011] failed to load /Users/d2233/workspace/go/src/github.com/therecipe/qt/webkit/Mfile  error="open /Users/d2233/workspace/go/src/github.com/therecipe/qt/webkit/Mfile: no such file or directory"

**Comment by therecipe** [comment]
Hey

Did you download and extract the webkit module from https://github.com/annulen/webkit?

**Comment by idoor88** [comment]
Yes, I downloaded it by following this instruction:
optional install the experimental webkit module: https://github.com/annulen/webkit/releases/download/qtwebkit-5.212.0-alpha2/qtwebkit-5.212.0_alpha2-qt59-darwin-x64.tar.xz, extract it's content inside $HOME\Qt\5.11.1\clang_64 (or similar) and export QT_WEBKIT=true

But after I turned it off by setting QT_WEBKIT=false, it works ok now.

Thanks
David
