### ISSUE TITLE
go test -v ./test/widgets generated a lot of errors

### ISSUE THREAD

**Issue by idoor88** [therecipe/qt#679]
I following the instructions here:
https://github.com/therecipe/qt/wiki/Getting-Started
But it generated a lot of errors on my Mac book:

go test -v ./test/widgets
# github.com/therecipe/qt/core
core.cpp:246:19: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:247:47: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:863:19: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:864:47: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:2409:19: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:2410:47: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:2641:19: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:2642:48: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:3061:19: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:3062:48: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:3402:19: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:3403:44: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:3722:19: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:3723:73: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:3763:19: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:3764:36: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:5027:19: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:5028:71: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
core.cpp:7123:19: error: unknown type name 'QAbstract3DGraph'; did you mean 'QtDataVisualization::QAbstract3DGraph'?
/usr/local/Cellar/qt/5.11.1/lib/QtDataVisualization.framework/Headers/qabstract3dgraph.h:47:35: note: 'QtDataVisualization::QAbstract3DGraph' declared here
fatal error: too many errors emitted, stopping now [-ferror-limit=]
FAIL	github.com/therecipe/examples/test/widgets [build failed]

**Comment by therecipe** [comment]
Hey

Could you please post the output from `$GOPATH/bin/qtsetup check`?

**Comment by idoor88** [comment]
I have moved to use a new Macbook computer and re-installed everything, also turned off QT_WEBKIT, these errors are not happening anymore.
