### ISSUE TITLE
qtdeploy cant find QT_DIR on Linux

### ISSUE THREAD

**Issue by prvst** [therecipe/qt#68]
Hi,

First of all, thanks for this project !

I just followed the Linux installation guide, and during QT installation I defined a different QT_DIR path, then I exported the path as a new env var. The installation scripts worked well, but when trying to run qtdeploy, I have the following error:

`qrc.qrc`
`output:`
`error:fork/exec /home/user/Qt5.7.0/5.7/gcc_64/bin/rcc: no such file or directory`

It seems to me that qtdeploy is not aware of the correct installation path, its still looking into the default place.

**Comment by therecipe** [comment]
Hey

You probably only need to export the QT_DIR in your ~/.profile or ~/.bash_profile, because qtdeploy and qtmoc have to be aware of QT_DIR as well.

**Comment by prvst** [comment]
adding the path to .bashrc seems to work. I followed the example on the bottom of the readme file, I created a qtExample folder and added the code example, but now when I run qtdeploy I have this:

`build_1`

`output:../../therecipe/qt/core/core-minimal.go:10:1: found packages main (qrc.go) and qt (qt.go) in /home/user/go/src/github.com/therecipe/qt`

`/home/user/go/src/github.com/therecipe/qt/core/core-minimal.go:10:1: import "github.com/therecipe/qt" is a program, not an importable package`

`/home/user/go/src/github.com/therecipe/qt/gui/gui-minimal.go:11:1: import "github.com/therecipe/qt" is a program, not an importable package`

`/home/user/go/src/github.com/therecipe/qt/widgets/widgets-minimal.go:12:1: import "github.com/therecipe/qt" is a program, not an importable package`

`error:exit status 1`

**Comment by therecipe** [comment]
Seems like you ran qtdeploy in in the qt root dir.
Just remove the qrc.* files and if present the moc.* files.
The only go file in the root dir should be qt.go

**Comment by prvst** [comment]
I'm actually running the qtdeploy from the go/bin folder, is that OK ?

**Comment by therecipe** [comment]
Yes, you can run it like this:

`cd path/to/your/project && $GOPATH/bin/qtdeploy build desktop`
or 
`$GOPATH/bin/qtdeploy build desktop path/to/your/project`

There will be a folder created called deploy and also several files prefixed with `qrc` and `moc`, but those will be removed after qtdeploy is done.

**Comment by prvst** [comment]
but that's the problem, I'm running from bin folder, as you detailed above, and I'm getting that error message

**Comment by therecipe** [comment]
Were there qrc* files in $GOPATH/src/github.com/therecipe/qt?
Did you remove them and the moc* files (if there were some)?

Do you get the same error if you run the command below?
`$GOPATH/bin/qtdeploy test desktop $GOPATH/src/github.com/therecipe/qt/internal/examples/widgets/line_edits`

**Comment by prvst** [comment]
> Were there qrc* files in $GOPATH/src/github.com/therecipe/qt?

I only have folders, some go files, yaml files, a bat file and a sh file in Inside the `$GOPATH/src/github.com/therecipe/qt`. I don't see any moc* or qrc* there.

> Did you remove them and the moc* files (if there were some)?

Didn't had to because there are none.

> Do you get the same error if you run the command below?

yes, i have the same error when running the example I copied from the README file and from the `widgets/line_edits` folder

**Comment by therecipe** [comment]
Okay, there should be only one go file `qt.go` and the setup files + the yaml files + readme, could you remove the rest and try again?
Are these files prefixed with cgo_* or similar? 

If nothing works, you could simply clone the repo again and re-run the setup.

**Comment by prvst** [comment]
I just removed every reference from _therecipe_ from GOPATH and tried again, now its working. Thanks for the support.

**Comment by therecipe** [comment]
It's solved, so I'm closing this.
