### ISSUE TITLE
windows installation

### ISSUE THREAD

**Issue by xaria-coin** [therecipe/qt#684]
having issues with the windows installation guide, got linux working fine but windows is causing a headache!

the final section in the windows installation instructions is to run 
$GOPATH/bin/qtsetup
which looks like a linux command, not windows

but i just get the error - qtsetup is not recognized as an internal or external command etc etc etc

probably a simple fix but im relatively new to this so any help would be appreciated, thanks

**Comment by akiyosi** [comment]
Have tried `%GOPATH%\bin\qtsetup.exe` ?

**Comment by xaria-coin** [comment]
Didn't seem to work either

**Comment by xaria-coin** [comment]
I've tried a few times but in that directory there is no qtsetup, but there was on Linux?
I know I've gone wrong somewhere but I've gone through everything twice now and can't see what I've missed

**Comment by akiyosi** [comment]
what Qt version are you using?  (official or MSYS2)
if you using MSYS2 version, `$GOPATH/bin/qtsetup` in the installation document is correct.

And also check that another command written in golang is created in `%GOPATH%\bin` (or `$GOPATH/bin` in MSYS2 MinGW shell)

**Comment by xaria-coin** [comment]
the install instructions for windows seem to be missing a step or two, ive managed to get qtsetup to run but it fails still
msys2 installs mingw64 with empty directories which cause a fail as gcc compiler is missing, installed mingw64 through their separate installer which allows qtsetup to run but i then get failure - static assertion failure

**Comment by therecipe** [comment]
@xaria-coin 
The basic installation should be pretty similar to the one on Linux or macOS.

First you will need to install Qt: 
https://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe

then you will need to add the directory containing **g++** to your **PATH** (`C:\Qt\Tools\mingw530_32\bin` or some similar path depending on your Qt installation)
sorry, this was somehow missing in the instructions

then you will need to install Go: https://golang.org/doc/install?download=go1.10.3.windows-amd64.msi
(and maybe **git** if you haven't already)

then simply run `go get -v github.com/therecipe/qt/cmd/...` to get `qtsetup, qtdeploy, ...`

and lastly run: `%GOPATH%\bin\qtsetup.exe` (you can get your **GOPATH** with `go env GOPATH` or `go env`)

**Comment by therecipe** [comment]
Mh, you are using the official version of Qt now or?
If yes, then maybe try to unset `QT_MSYS2` and `QT_MSYS2_DIR` and also remove `C:\msys64\mingw64\bin` from your PATH.

Then it should work, I hope.

**Comment by xaria-coin** [comment]
It was all me being a pleb, where I'd not been paying attention I tried both the normal qt version and the msys2 version so there were conflicts
Thanks for all your help guys ;)

**Comment by therecipe** [comment]
you are welcome :)
