### ISSUE TITLE
Example MDI (multi document interface)

### ISSUE THREAD

**Issue by Keyn1** [therecipe/qt#686]
Please give an example of a MDI application. At least tell me where to start?

**Comment by therecipe** [comment]
Hey

This should work:

```go
package main

import (
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	window := widgets.NewQMainWindow(nil, 0)

	mdiArea := widgets.NewQMdiArea(nil)

	subWindow := widgets.NewQMdiSubWindow(nil, 0)
	sWCentralWidget := widgets.NewQWidget(nil, 0)
	sWCentralWidgetLayout := widgets.NewQVBoxLayout2(sWCentralWidget)

	sWCentralWidgetLayout.AddWidget(widgets.NewQLabel2("Label", nil, 0), 0, 0)
	sWCentralWidgetLayout.AddWidget(widgets.NewQPushButton2("PushButton", nil), 0, 0)

	subWindow.SetWidget(sWCentralWidget)
	mdiArea.AddSubWindow(subWindow, 0)

	window.SetCentralWidget(mdiArea)

	window.Show()

	widgets.QApplication_Exec()
}
```

Also maybe take a look here: http://doc.qt.io/qt-5/qmdiarea.html#details

**Comment by Keyn1** [comment]
Thank you, it's working.
Some errors occurred during compilation. Then the main window started.


PS C:\Goproject\src\StartQt\start4> qtdeploy test desktop
ERRO[0007] failed to load C:\Qt\Docs\Qt-5.11.1\qtremoteobjects\qtremoteobjects.index  error="open C:\\Qt\\Docs\\Qt-5.11.1\\qtremoteobjects\\qtremoteobjects.index: The system cannot find the path specified."
WARN[0007] parser.LoadModule                             error=EOF module=RemoteObjects
ERRO[0007] failed to load C:\Qt\Docs\Qt-5.11.1\qtdatavisualization\qtdatavisualization.index  error="open C:\\Qt\\Docs\\Qt-5.11.1\\qtdatavisualization\\qtdatavisualization.index: The system cannot find the path specified."
ERRO[0007] failed to load C:\Qt\Docs\Qt-5.11.1\qtcharts\qtcharts.index  error="open C:\\Qt\\Docs\\Qt-5.11.1\\qtcharts\\qtcharts.index: The system cannot find the path specified."
ERRO[0008] failed to load C:\Qt\Docs\Qt-5.11.1\qtpurchasing\qtpurchasing.index  error="open C:\\Qt\\Docs\\Qt-5.11.1\\qtpurchasing\\qtpurchasing.index: The system cannot find the path specified."
WARN[0008] parser.LoadModule                             error=EOF module=Purchasing
ERRO[0020] failed to run command                         cmd="C:\\Qt\\5.11.1\\mingw53_32\\bin\\qmake -o Mfile ..\\remoteobjects.pro -spec win32-g++ CONFIG+=windows CONFIG+=release" dir="C:\\Users\\Keyn\\go\\src\\github.com\\therecipe\\qt\\remoteobjects" env= error="exit status 3" func=RunCmdOptional name="run qmake for windows on windows"
Info: creating stash file C:\Users\Keyn\go\src\github.com\therecipe\qt\remoteobjects\.qmake.stash
Project ERROR: Unknown module(s) in QT: remoteobjects

ERRO[0020] failed to load C:\Users\Keyn\go\src\github.com\therecipe\qt\remoteobjects\Mfile.Release  error="open C:\\Users\\Keyn\\go\\src\\github.com\\therecipe\\qt\\remoteobjects\\Mfile.Release: The system cannot find the file specified."
ERRO[0021] failed to run command                         cmd="C:\\Qt\\5.11.1\\mingw53_32\\bin\\qmake -o Mfile ..\\datavisualization.pro -spec win32-g++ CONFIG+=windows CONFIG+=release" dir="C:\\Users\\Keyn\\go\\src\\github.com\\therecipe\\qt\\datavisualization" env= error="exit status 3" func=RunCmdOptional name="run qmake for windows on windows"
Info: creating stash file C:\Users\Keyn\go\src\github.com\therecipe\qt\datavisualization\.qmake.stash
Project ERROR: Unknown module(s) in QT: datavisualization

ERRO[0021] failed to load C:\Users\Keyn\go\src\github.com\therecipe\qt\datavisualization\Mfile.Release  error="open C:\\Users\\Keyn\\go\\src\\github.com\\therecipe\\qt\\datavisualization\\Mfile.Release: The system cannot find the file specified."
ERRO[0021] failed to run command                         cmd="C:\\Qt\\5.11.1\\mingw53_32\\bin\\qmake -o Mfile ..\\charts.pro -spec win32-g++ CONFIG+=windows CONFIG+=release" dir="C:\\Users\\Keyn\\go\\src\\github.com\\therecipe\\qt\\charts" env= error="exit status 3" func=RunCmdOptional name="run qmake for windows on windows"
Info: creating stash file C:\Users\Keyn\go\src\github.com\therecipe\qt\charts\.qmake.stash
Project ERROR: Unknown module(s) in QT: charts

ERRO[0021] failed to run command                         cmd="C:\\Qt\\5.11.1\\mingw53_32\\bin\\qmake -o Mfile ..\\purchasing.pro -spec win32-g++ CONFIG+=windows CONFIG+=release" dir="C:\\Users\\Keyn\\go\\src\\github.com\\therecipe\\qt\\purchasing" env= error="exit status 3" func=RunCmdOptional name="run qmake for windows on windows"
Info: creating stash file C:\Users\Keyn\go\src\github.com\therecipe\qt\purchasing\.qmake.stash
Project ERROR: Unknown module(s) in QT: purchasing

ERRO[0021] failed to load C:\Users\Keyn\go\src\github.com\therecipe\qt\purchasing\Mfile.Release  error="open C:\\Users\\Keyn\\go\\src\\github.com\\therecipe\\qt\\purchasing\\Mfile.Release: The system cannot find the file specified."
ERRO[0021] failed to load C:\Users\Keyn\go\src\github.com\therecipe\qt\charts\Mfile.Release  error="open C:\\Users\\Keyn\\go\\src\\github.com\\therecipe\\qt\\charts\\Mfile.Release: The system cannot find the file specified."
PS C:\Goproject\src\StartQt\start4>

**Comment by therecipe** [comment]
Yeah, these are just warning and you can ignore them if you don't depend on one of these modules.
This happens if you opt-out modules during the installation, or if the module is not supported by the target. It's a bit annoying, but I will look into a way to suppress these in the future.
