### ISSUE TITLE
Android Docker image - libssl libcrypto

### ISSUE THREAD

**Issue by bbascbr** [therecipe/qt#691]
When running:
`qtdeploy -docker build android`
We get error:
`External library /home/user/openssl-1.0.2o-arm/libcrypto.so does not exist!`

The issue is in the command in the Dockerfile:
`RUN mkdir -p $HOME/openssl-1.0.2o-arm && mv $HOME/openssl-1.0.2o/*.so $HOME/openssl-1.0.2o-arm`

it moves only the *.so files while the libcrypto.so and libssl.so are links to libcrypto.so.1.0.0 and libssl.so.1.0.0 respectively.
It should either move v *.so.* or copy *.so.* to *.so

```
lrwxrwxrwx  1 root root      18 Aug 20 08:52 libcrypto.so -> libcrypto.so.1.0.0
-rwxr-xr-x  1 root root 1918176 Aug 20 08:52 libcrypto.so.1.0.0
-rw-r--r--  1 root root  512214 Aug 20 08:52 libssl.a
-rw-r--r--  1 root root     294 Aug 20 08:52 libssl.pc
lrwxrwxrwx  1 root root      15 Aug 20 08:52 libssl.so -> libssl.so.1.0.0
-rwxr-xr-x  1 root root  405476 Aug 20 08:52 libssl.so.1.0.0

```
The Docker image was "https://hub.docker.com/r/therecipe/qt/builds/b4yyfcfjwwzre9wsvjegf3y/"

Also 
`RUN cd $HOME` 
is required prior to:
`RUN rm -rf $HOME/openssl-1.0.2o && tar -xzf openssl-1.0.2o.tar.gz -C $HOME`

**Comment by F0rth** [comment]
https://github.com/therecipe/qt/commit/d0f30a6e4c39e0989b1b00169b66abbca442becf

**Comment by therecipe** [comment]
Hey

Sorry, this should have been fixed yesterday with https://github.com/therecipe/qt/commit/d0f30a6e4c39e0989b1b00169b66abbca442becf for https://github.com/therecipe/qt/issues/689
but it seems like I hit a rate limit while building images so all the builds were canceled

I manually triggered the builds again, and the image should be ready once
https://hub.docker.com/r/therecipe/qt/builds/btsgdnrwdm7hebvnbnrazkh/
https://hub.docker.com/r/therecipe/qt/builds/bkbqctdroxwe8dus69or3kj/
are done (approx. 2 hours)

**Comment by bbascbr** [comment]
Great!
Just tested it out. Works OK. :+1:
Thanks. 
Keep up the good work.
