### ISSUE TITLE
[Linux, go1.11, qt5.11.1] go build github.com/therecipe/qt/core: invalid flag in #cgo LDFLAGS: -Wl,-O1

### ISSUE THREAD

**Issue by Barpfotenbaer** [therecipe/qt#695]
Working on Linux x64 with go1.11 and qt5.11.1 this error is thrown during build process:

go build github.com/therecipe/qt/core: invalid flag in #cgo LDFLAGS: -Wl,-O1

With go1.10.3 and go1.10.4 anything runs very well. (I have done the complete installation process each time before.)

**Comment by therecipe** [comment]
Hey

Yeah, I haven't had the time to test it with Go1.11 yet.
But I will look into this.

**Comment by Barpfotenbaer** [comment]
Thanks for your efforts! I recognized some strange behavior of LiteIDE afterwards. You are totally right! "go build /my/path" works like a charm! However using the "go build"-option in LiteIDE, I still got this error: go build github.com/therecipe/qt/core: invalid flag in #cgo LDFLAGS: -Wl,-O1
That's funny, because my configuration in LiteIDE does not have (and does not show) any build-args at all! But now, it's a matter for the somebody-else's-problem-field :-)

Many thanks for your help and your great(!!!) work, making QT suitable for go!!!

**Comment by therecipe** [comment]
Will close this now, since it should be solved by now https://github.com/therecipe/qt/issues/549#issuecomment-451219065
