### ISSUE TITLE
Will the interface methods be renamed future

### ISSUE THREAD

**Issue by xland** [therecipe/qt#7]
There are many interface methods named xxxxx2(...),xxxx3(...)

Will these interface methods be renamed future?

**Comment by therecipe** [comment]
Are you referring to methods like these ?
https://github.com/therecipe/qt/blob/master/core/qvariant.go#L44

Unfortunately go doesn't support name overloading, so this is necessary.

We could bundle all these overloaded methods with the help of a plain 'interface{}' or '...interface{}', but that would probably lead to more confusion than do good.

**Comment by therecipe** [comment]
I think, this can be closed.
