### ISSUE TITLE
Failed to run command with No devices are booted for ios-simulator

### ISSUE THREAD

**Issue by idoor88** [therecipe/qt#700]
When I run qtdeploy test ios-simulator, I thought it will run my app into a simulator, but the simulator was started, my app was not deployed in the simulator, and I got the following error on command line, it said no devices are booted, do I need a real iPhone connected to my Mac for this to work?
Thanks
IDoor

qtdeploy test ios-simulator ./basic/wascenter
ERRO[0048] failed to run command                         cmd="xcrun simctl uninstall booted /Users/kev/workspace/go/src/github.com/therecipe/examples/basic/wascenter/deploy/ios-simulator/main.app" dir= env= error="exit status 163" func=RunCmdOptional name="uninstall old app"
No devices are booted.

**Comment by therecipe** [comment]
Hey

No, there is no need for an real iPhone for this to work.
Maybe try to run `qtdeploy test ios-simulator` a second time, sometimes the simulator is acting strange especially when you start it the first time.

Also did you run `qtsetup full ios-simulator` prior testing your app?
If yes, did the examples show up in the simulator during the end of the setup?

**Comment by therecipe** [comment]
Will close this now, please reopen if this is still relevant
