### ISSUE TITLE
struct named "Test" that embeds core.QObject causes endless compiling

### ISSUE THREAD

**Issue by skaldesh** [therecipe/qt#701]
In my project, I simply declared this struct:
```
type Test struct {
    core.QObject

    _ func() `slot:"test"`
}

func (t *Test) test() {
    println("test")
}
```

I did not register this component with QML, I simply tried to compile it like that, but the compilation with qtdeploy never finished. I suspect the "special" name "Test" causes this kind of behaviour.

If not fixable, mention it in the FAQ or give some warning in the readme ...

When I renamed the struct to something different, the compilation went fine! I did not try to embed any other types, nor did I test whether names like "TestStruct" or similar cause this problem as well

**Comment by therecipe** [comment]
Hey

I will look into this.

**Comment by therecipe** [comment]
I will close this now, since I remember fixing it some time ago and the struct above seems to work.
