### ISSUE TITLE
posted package parser/viewer

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#704]
Makes it simpler to look up usage and avoid godoc:
https://github.com/5k3105/package_view

Improvements would be to add fuzzy search and open browser for docs.

**Comment by therecipe** [comment]
Nice idea :)

But there seems to be an issue on macOS, haven't tested it on Linux or Windows yet.

<img width="648" alt="screen" src="https://user-images.githubusercontent.com/9833226/46576090-b312eb00-c9c2-11e8-8955-a9578bb0f067.png">
