### ISSUE TITLE
QAbstractTextDocumentLayout.Draw and QColor.Rgb()

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#705]
Hi,

http://doc.qt.io/qt-5/qabstracttextdocumentlayout.html#draw

I do not see this method implemented.

Also, QColor does not have Rgb() method implemented.

Thanks!

**Comment by 5k3105** [comment]
Fyi,

I am attempting to convert over this widget:
https://github.com/maxrd2/subtitlecomposer/blob/master/src/widgets/textoverlaywidget.cpp

I am more than halfway done, but you will notice the last two functions -- setMonoMask and setOutline are quite complex.

Which made me think -- is there a way to run qtsetup on one widget like this, or a group of custom widgets which are already in C++?

**Comment by therecipe** [comment]
Hey

https://github.com/therecipe/qt/commit/b5c3f659cc70a3397852df18f104c77c6874cc71 should add the missing QRgb functions

>Which made me think -- is there a way to run qtsetup on one widget like this, or a group of custom widgets which are already in C++?

Yeah, it should theoretically be possible to change the generator to bind custom widgets (or modules). 
But you would need to write `*.qdocconf` files by hand and use [qdoc](http://doc.qt.io/qt-5/qdoc-index.html) to get an *.index file which then can be feed to the generator to produce the glue code.

I will think about it, maybe there is some easy way to get something working real quick.

**Comment by therecipe** [comment]
Yes, but it seems like it went missing with the update to 5.11.1 https://github.com/therecipe/qt/commit/5355937d17e9eee62460706cb9a033180014400e
However, it's back now https://github.com/therecipe/qt/commit/9221349d0b0667f8301e583e787b6df7a2d51772

**Comment by 5k3105** [comment]
haha. awesome! thanks!
