### ISSUE TITLE
Qtsetup changed library source code when building the binding

### ISSUE THREAD

**Issue by jamalsa** [therecipe/qt#708]
When running qtsetup to install this binding, the source of this binding changed.

### Step To Reproduce
- Install Qt using http://download.qt.io/official_releases/qt/5.11/5.11.2/qt-opensource-linux-x64-5.11.2.run
- Install this binding using command: go get -u github.com/therecipe/qt/cmd/...
- Setup binding using: $GOPATH/bin/qtsetup
- Check source code at $GOPATH/src/github.com/therecipe/qt using `git diff`

### Expected behavior
Binding installed and binding source is not changed

### Current behavior
Binding installation error and binding source is changed. The cause of error is addition of `#include <QtAbstract3DGraph>` and its related code to core/core.cpp.

- The diff: https://gist.github.com/jamalsa/79599c5cf1f21ec8d531b90769bb6c41
- The error: https://gist.github.com/jamalsa/2daf4be15a84103b9a6b194d1c4fc501

### Environment
- OS: Archlinux x86_64
- Qt Version: 5.11
- Go version: 1.11
- Docker: no

**Comment by therecipe** [comment]
Hey

I think https://github.com/therecipe/qt/commit/8da358a56a4ae7d15b0ae3d37532fdca2733fd4b should fix this, but I haven't reproduced the issue to test it

**Comment by jamalsa** [comment]
The strange thing is this problem didn't appear when I used Qt from system packages. Only using downloaded Qt from their site
