### ISSUE TITLE
Prebuilt Packages

### ISSUE THREAD

**Issue by kryptodev** [therecipe/qt#71]
Hi,

This is mainly a request. Is there any chance of someone packaging a pre-built set of files? I have 6 GB of RAM on my laptop so building from source is just not working out for me even though I definitely want to  use this library to make Windows x86 programs. Golang + Qt GUI makes me pretty happy.

Thank you,
I hope someone will consider my request.

**Comment by therecipe** [comment]
Hey

I'm already working on a docker image that lets you (cross) compile to Linux and Windows.

In the meanwhile you could comment out or remove the install step from the setup.bat: `go run %GOPATH%/src/github.com/therecipe/qt/internal/setup/install.go %*` and simply re-run the setup.

This will let you use qtdeploy to build applications without having to install the `widgets` package, but you won't be able to use gocode auto-complete.

**Comment by therecipe** [comment]
I just made some changes with https://github.com/therecipe/qt/commit/d51ced2197a90db687db3a09e367cebde9ade4e4

You can now define `QT_STUB=true` before running the setup file.
This will create stub source code files that can't be used by `go run/build`, but you will get go-code auto-completion and still will be able to deploy everything with `qtdeploy`.
This should work on machines with atleast 1gb ram.

**Comment by therecipe** [comment]
It's solved, so I'm closing this.
