### ISSUE TITLE
How to create a QQuickImageProvider?

### ISSUE THREAD

**Issue by skaldesh** [therecipe/qt#711]
Hey!
I was trying to implement [this example](http://doc.qt.io/qt-5/qquickimageprovider.html) with the ImageProvider type.  
My struct looks like this:
```
type ImageProvider struct {
	quick.QQuickImageProvider
}
```
When I run qtdeploy, I thought I would get a constructor generated (NewImageProvider), exactly like when I am embedding core.QObject, but that was not the case.  

How should I go about this?

**Comment by skys215** [comment]
Try running `qtmoc` first?

**Comment by skaldesh** [comment]
I think `qtdeploy` runs `qtmoc` as well. If you delete the moc files and run deploy, they are created again.  
I tried anyways to run `qtmoc` (btw, both deploy and moc with the `-docker` flag), but it did not work.

**Comment by therecipe** [comment]
Hey

Yeah, qtmoc won't work on QQuickImageProvider because it's not derived from QObject.

But you could work around this with something like:
```go
type ImageProvider struct {
	core.QObject
	*quick.QQuickImageProvider

	_ func() `constructor:"init"`
}

func (ip *ImageProvider) init() {
	ip.QQuickImageProvider = quick.NewQQuickImageProvider()
}
```

You can also find a working example here: https://github.com/therecipe/qt/issues/582#issuecomment-378296813

**Comment by skaldesh** [comment]
@therecipe Thanks for your comment, I did exactly the workaround you suggested :)
