### ISSUE TITLE
uint64 behaves strangely when converted to core.QVariant

### ISSUE THREAD

**Issue by skaldesh** [therecipe/qt#712]
Hey!  
I wanted to convert an `uint64` to a `*core.QVariant` that gets passed to QML. I used the function `core.NewQVariant10(number)` to convert the number and then I wanted to display the value in a listview. However, the number came out slightly INCREASED (yes, I am serious).  

My number is `388519949297975297`. But the number that gets displayed, is `388519949297975300` (Notice the difference in the last three digits only)

CODE:
```
type TagEventOverviewModel struct {
	core.QAbstractListModel
	_ func() `constructor:"init"`
	tags []*db.TagEvent
}

func (t *TagEventOverviewModel) init() {
	t.ConnectData(t.data)
	t.ConnectRowCount(t.rowCount)
}

func (t *TagEventOverviewModel) rowCount(*core.QModelIndex) int {
	return len(t.tags)
}

func (t *TagEventOverviewModel) data(index *core.QModelIndex, role int) *core.QVariant {
	if role != int(core.Qt__DisplayRole) {
		return core.NewQVariant()
	}

	tag := t.tags[index.Row()]
	return core.NewQVariant25(map[string]*core.QVariant{
		"number":        core.NewQVariant10(tag.ID),
	})
}
```

QML:
```
ListView {
        id: list
        anchors {
            top: filterBar.bottom
            left: parent.left
            right: parent.right
            bottom: parent.bottom
        }
        clip: true
        model: bridge.tagEventModel

        delegate: Item {
            width: list.width
            height: 100

            Text {
                text: display.number
                color: Material.foreground
                font.pixelSize: 16
            }
        }
```

**Comment by skaldesh** [comment]
A temporary solution is to convert the uint64 first with `strconv.FormatUint()` and then use `core.NewQVariant14(formatNumber)`. The number is then correctly displayed

**Comment by therecipe** [comment]
Hey

Yeah, iirc I looked into some similar issue a while ago.

The problem back then was that QML can't handle 64 bit integers.

Maybe take a look here: http://doc.qt.io/qt-5/qtqml-typesystem-basictypes.html
and here: http://doc.qt.io/qt-5/qml-int.html

**Comment by skaldesh** [comment]
Yes, I also found out during debugging that QML can not handle uint64.  

Maybe we can add a section to the README or the Wiki "Common/Known Problems" and mention such stuff there? I can start such a section with this problem

**Comment by skaldesh** [comment]
But I could understand, if you said that your qt bridge is just that, a bridge, and does not try to be a second qt developer documentation. So I would be fine with closing the issue as well

**Comment by therecipe** [comment]
>Maybe we can add a section to the README or the Wiki "Common/Known Problems" and mention such stuff there? I can start such a section with this problem

Feel free to create a new Wiki page, I think it's a great idea.
Similar stuff is currently listed here: https://github.com/therecipe/qt/wiki/FAQ#operational-1
But it's probably better to move these stuff to the new page as well and then keep the FAQ for general things.

I also just started overhauling the docs and haven't worked on the FAQ yet, so the timing is great :)

**Comment by skaldesh** [comment]
Alright, I will create one :)

**Comment by skaldesh** [comment]
Done, I created this new [page](https://github.com/therecipe/qt/wiki/Common-Issues) and I adjusted the Home Wiki page to link it (I hope its ok)

**Comment by therecipe** [comment]
It's perfect, thank you :)
