### ISSUE TITLE
unrecognized import path "math/bits" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by zooteld** [therecipe/qt#714]
when i do the go git command it ends with what looks like a "math/bits" issue...

Using windows 10, QT 5.7, and go 1.7.1
![snip1](https://user-images.githubusercontent.com/22121839/46588590-93cc9a00-ca64-11e8-80e4-62e1234cd42a.PNG)

C:\Go>go get -v github.com/therecipe/qt/cmd/...
github.com/therecipe/qt (download)
github.com/sirupsen/logrus (download)
github.com/konsorten/go-windows-terminal-sequences (download)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/crypto/ssh?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh?go-get=1
get "golang.org/x/crypto/ssh": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
package github.com/therecipe/qt/cmd/qtdeploy
        imports math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)

**Comment by zooteld** [comment]
I upgraded golang to 1.11 and now its good

**Comment by therecipe** [comment]
Okay, seems like "math/bits" was added in 1.9: https://golang.org/doc/go1.9#math-bits
I will close this now.
