### ISSUE TITLE
QVariant conversion methods different from Qt spec.

### ISSUE THREAD

**Issue by skaldesh** [therecipe/qt#716]
Hey!
When I wanted to convert a `*core.QVariant` to an integer using the `ToInt(ok bool)` method, I noticed that the official Qt method is `int QVariant::toInt(bool *ok = nullptr) const`.  
Furthermore the [doc](http://doc.qt.io/qt-5/qvariant.html#toInt) says:  
> If ok is non-null: *ok is set to true if the value could be converted to an int; otherwise *ok is set to false.

Isn't there a discrepancy between this binding and the official method? I can not pass a boolean pointer to `ToInt(ok bool)`, therefore I will not be notified, whether my conversion succeeded or not.

**Comment by therecipe** [comment]
Hey

Yeah, you are right it should be a `*bool`.
I will look into this.

**Comment by therecipe** [comment]
Sorry it took so long, but this commit https://github.com/therecipe/qt/commit/c2524f50a59a69c9042b583bb6386400325c853e should make all *bool functions usable.

Also one of the next things I will work on is the []byte support.

**Comment by therecipe** [comment]
Will close this now, since the initial issue seems to be resolved.
