### ISSUE TITLE
how to connect qml and golang? 

### ISSUE THREAD

**Issue by lalawila** [therecipe/qt#719]
I have write this, but not work.
go code
...
	var engine = qml.NewQQmlApplicationEngine(nil)
	engine.Load(core.NewQUrl3("qrc:/powershare.qml", 0))
	a := engine.RootObjects()
	bt := a[0].FindChild("login", core.Qt__FindChildrenRecursively)
	debugLog.Println(bt.Property("text").ToString())
	qt.ConnectSignal(bt.Pointer(), "qmlSignal", func() {
		debugLog.Println("get it")
	})
	gui.QGuiApplication_Exec()
...

qml code
...
            Button {
                id: login
                text: "login"
                objectName: "login"
                width: container.width
                highlighted: true
                signal qmlSignal()
                onClicked: login.qmlSignal()
            }
...

I can get this button object and print text,  but I can't connect signal.
Is any wrong?
Or any better way to connect golang and qml?
thx very much!

**Comment by therecipe** [comment]
Hey

The `QObject::connect` functions and the `QMetaObject::invokeMethod` functions are not available yet.

You can however call from and to qml by using a helper object or by registering a new qml type.

Maybe check these examples: https://github.com/therecipe/examples/tree/master/advanced/qml_quick/bridge
https://github.com/therecipe/examples/tree/master/advanced/qml_quick/ctxproperty

And maybe this example as well, as it shows you how to use qml [Connections](http://doc.qt.io/qt-5/qml-qtqml-connections.html): https://github.com/therecipe/qt/tree/master/internal/examples/quick/bridge2

(It's also possible to directly call qml methods by using a [workaround](https://github.com/therecipe/examples/blob/master/test/qml_quick/qml_quick_test.go#L34), but it's rather ugly and you should only use it for testing)

**Comment by lalawila** [comment]
> Hey
> 
> The `QObject::connect` functions and the `QMetaObject::invokeMethod` functions are not available yet.
> 
> You can however call from and to qml by using a helper object or by registering a new qml type.
> 
> Maybe check these examples: https://github.com/therecipe/examples/tree/master/advanced/qml_quick/bridge
> https://github.com/therecipe/examples/tree/master/advanced/qml_quick/ctxproperty
> 
> And maybe this example as well, as it shows you how to use qml [Connections](http://doc.qt.io/qt-5/qml-qtqml-connections.html): https://github.com/therecipe/qt/tree/master/internal/examples/quick/bridge2
> 
> (It's also possible to directly call qml methods by using a [workaround](https://github.com/therecipe/examples/blob/master/test/qml_quick/qml_quick_test.go#L34), but it's rather ugly and you should only use it for testing)

Got it,  Thx :D
