### ISSUE TITLE
Support for Go modules

### ISSUE THREAD

**Issue by Baldomo** [therecipe/qt#726]
It's now been several months since the official `go mod` tool was released. It is (so far) impossible, however, to use this package inside of a moduled project without resorting to GOPATH hacks or installing packages in GOPATH, then disabling the modules system and running `qtdeploy`. A solution to he whole ordeal could be generating qt inside the `$GOPATH/pkg/mod` and providing/generating a `go.mod` file. This way, a [replace directive](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive) can be used to load the module from local storage.

PS I'm on Windows and Go 1.11

**Comment by therecipe** [comment]
Will close this, since the status is tracked here https://github.com/therecipe/qt/issues/755#issuecomment-455248057 now
