### ISSUE TITLE
found packages xx_test (moc*.go) and xx (*.go)

### ISSUE THREAD

**Issue by quantonganh** [therecipe/qt#727]
- go 1.11.1
- Qt 5.11.1

Steps to reproduce:
- qtmoc.exe
- qtdeploy.exe build desktop

The error:

>controller\account.go:15:2: found packages lib_test (moc.go) and lib (qt.go) in ...
>controller\account.go:15:2: found packages lib (moc.go) and lib_test (moc_cgo_windows_windows_386.go) in

Looks like the package name is not consistent, sometimes it's `lib`, sometimes `lib_test` (in `moc.go`).

Maybe related: https://github.com/golang/go/issues/24895

**Comment by therecipe** [comment]
Hey

Could you test this with the latest version of the binding?
I made some changes last week, which should have fixed this https://github.com/therecipe/qt/commit/3de3e2be88af3cdfa0d49ca4238d2cd4bc713665#diff-121e6d279568d7577d14f069b9ee8890R147
