### ISSUE TITLE
Is that intentional?

### ISSUE THREAD

**Issue by aghasoroush** [therecipe/qt#731]
Guys, I have a question. Have you intentionally made the installation process that hard? I can't believe I couldn't install your package in osx nor windows after 15 years programming.  
If making the installation process hard is a good practice, let me know. I will do it in my next project :)

**Comment by willeponken** [comment]
I'm not any maintainer of this project, but I do not share your view. I would argue this project is _easier_ to install, than, say... Qt. Are you using the Docker method?

Maybe you need some more experience? I have less experience and managed to install it just fine.

**Comment by willeponken** [comment]
Do you have any concrete ideas on how to improve the installation instead of mocking the project?

**Comment by aghasoroush** [comment]
@willeponken I installed it but after spending almost 2 or 3 hours.
I'm working on it to make the installation process easier. 
Cheers

**Comment by therecipe** [comment]
@aghasoroush
I'm somewhat working towards something like `go get github.com/therecipe/qt/cmd/... && $GOPATH/bin/qtsetup init` to make the installation process as simple as possible in the future, but it would take some time to get this properly working on all systems (and all possible configurations)

However, if you have homebrew installed then you could run something like this atm:

```
xcode-select --install; brew install qt && go get github.com/therecipe/qt/cmd/... && echo "export QT_HOMEBREW=true" >> $HOME/.bash_profile && source $HOME/.bash_profile && $(go env GOPATH)/bin/qtsetup
```
(maybe I should add this to the wiki ...)


Also as @willeponken said, it would be great if you could provide infos about how to make the installations instructions more clear or better yet send a pr.

**Comment by aghasoroush** [comment]
@therecipe The problem on windows was due to wrong mingw installation. Both mingw should be installed in `qt` and `tools` sections.

**Comment by therecipe** [comment]
@aghasoroush Sorry, do you mean the issue was due a wrong (different) version of mingw in your PATH? If yes, then yeah this happens pretty often.

**Comment by skaldesh** [comment]
@aghasoroush can the issue be closed?

**Comment by aghasoroush** [comment]
Yes, Thank you.

**Comment by skaldesh** [comment]
@aghasoroush  @therecipe please close it then :)

**Comment by therecipe** [comment]
I made some changes with https://github.com/therecipe/qt/commit/a790897844e01485aa1af200c93d41a4f3e68db7
to make it way easier to get started on linux and macOS.
And windows support for this will follow soon.

On linux and macOS you only need to run 
```
go get -v github.com/therecipe/qt/cmd/... && $(go env GOPATH)/bin/qtsetup
```
from now on. (if you already have Go, Git and an C/C++ compiler installed)

I will make this the preferred way to work with this binding, and people that need more Qt tools (Qt Creator, Qt Designer, QML Profiler, ...) can simply keep using the "full" Qt installation if they like.

These changes will make it way easier for people to get started and it's also a great option for people that just want to compile some project they found that was build with this binding and those people might not know Go or Qt and maybe they don't even want to.

These people can now simply run
```
go get -v gitHub.com/therecipe/qt/cmd/... && $(go env GOPATH)/bin/qtdeploy test desktop github.com/therecipe/examples/basic/widgets
```
and hopefully get an working application out of it
