### ISSUE TITLE
How to pass ldflags that containing spaces to qtdeploy?

### ISSUE THREAD

**Issue by quantonganh** [therecipe/qt#736]
With `go build`, we can do something like this:

```
go build -ldflags '-X "main.foo=bar baz"'
```

but we cannot do the same when using `qtdeploy`:

```
qtdeploy -fast -ldflags '-X "main.foo=bar baz"'
```

The problem is:
- https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/build.go#L26
- https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/build.go#L65

so, that custom flags will be:

```
-ldflags=\"-X\" \"\"main.foo=bar\" \"baz\"\"
```

and we got an error:

>/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64/link: -X flag requires argument of the form importpath.name=value

**Comment by quantonganh** [comment]
@therecipe Instead of escaping every double quote, why not use wrap `ldflags` with single quote and leave everything inside as it is?

**Comment by therecipe** [comment]
@quantonganh Should be fixed now with https://github.com/therecipe/qt/commit/de3f785199230583dcfd11bd96e8e91f0899dc01

The problem were the escaped spaces inside the double quotes.

`exec.Command` needs to have regular spaces escaped like this `-X" "main...` for example.
But not in already escaped places like `"main.foo=bar baz"`, so I had to work around this.
https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/build_escape.go
https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/build_test.go
