### ISSUE TITLE
Segmentation Fault when inserting row

### ISSUE THREAD

**Issue by skaldesh** [therecipe/qt#737]
Hey!  
I have the issue that I am trying to insert a row into my abstract list model, which causes my application to crash with a segfault. The insert is done on a separate goroutine.  
```
func (t *TagEventOverviewModel) loadEvent(event *db.TagEvent) {
        t.BeginInsertRows(core.NewQModelIndex(), 0, 0) // SEGFAULT
	// Efficiently insert the element at the front of the slice.
	t.tags = append(t.tags, nil)
	copy(t.tags[1:], t.tags[0:])
	t.tags[0] = event
	t.EndInsertRows()
}
```

The stacktrace is not very helpful, it just says that some cgo call segfaulted.

**Comment by skaldesh** [comment]
Btw, when I replace `BeginInsertRows()` and `EndInsertRows()` with `BeginResetModel()` and `EndResetModel()`, everything works fine

**Comment by therecipe** [comment]
Hey

>The insert is done on a separate goroutine.

You probably just need to make the `loadEvent` function a slot or signal with qtmoc for this to work, since these functions need to be run on the main thread.

But you could also create some helper "class" to run functions on the main thread instead.

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
)

type mainThreadHelper struct {
	core.QObject

	_ func(f func()) `signal:"runOnMain,auto`
}

func (*mainThreadHelper) runOnMain(f func()) { f() }

var MainThreadRunner = NewMainThreadHelper(nil)

func main() {
	core.NewQCoreApplication(len(os.Args), os.Args)

	println("main thread:", core.QThread_CurrentThread().Pointer())

	go func() { println("some other thread:", core.QThread_CurrentThread().Pointer()) }()

	go MainThreadRunner.RunOnMain(func() { println("again on main thread:", core.QThread_CurrentThread().Pointer()) })

	core.QCoreApplication_Exec()
}
```

**Comment by skaldesh** [comment]
Thank you so much for this code snippet! That is so useful, you should include it somewhere in the docs! :)
