### ISSUE TITLE
Update docker linux image

### ISSUE THREAD

**Issue by skaldesh** [therecipe/qt#740]
Hey @therecipe 
I have seen that you included the new FromData3 function to create a QImage directly from a byte slice! However, the latest docker image does not yet include it. Can you upload a new linux image?
Thank you!

**Comment by therecipe** [comment]
Sorry it took so long, I initially planned to rework the whole string handling in one go, but figured that it would probably be better to incrementally work on it instead.

I pushed the changes necessary to create an QImage directly from an []byte with https://github.com/therecipe/qt/commit/b09bb04a610c6f5fdae8986b44612ed156f4884d#diff-81820573596259c0998d398bc9add967

The functions are `QImage_FromData`, `(*QImage) FromData` and `(*QImage) LoadFromData`
Also if you want to create an QByteArray from []byte you can use `QByteArray_FromRawData` now.

I will also make some functions return []byte in the future, such as `(*QByteArray) Data` and `(*QByteArray) ConstData`

**Comment by skaldesh** [comment]
Thanks!
