### ISSUE TITLE
qtdeploy -qt_dir D:\program\Qt -qt_version 5.11.2 build desktop . error on windows

### ISSUE THREAD

**Issue by dapengjun** [therecipe/qt#742]
My project use go modules.  I get error when I execute "qtdeploy -qt_dir D:\program\Qt -qt_version 5.11.2 build desktop . "

**Comment by dapengjun** [comment]
![qq 20181205103916](https://user-images.githubusercontent.com/9162928/49486597-0b0e8680-f87a-11e8-9aea-88bcd67ec553.png)

**Comment by therecipe** [comment]
This seems to be related to https://github.com/golang/go/pull/28908

The workaround for now is to apply [this](https://github.com/golang/go/commit/c45bd44319810381958984233d6b791727120cee.patch) patch and to recompile your go tool chain.

The long term solution is to wait for the PR to be merged, or for me to work around this limitation by segregating the `*.index` files into several sub repos.

**Comment by therecipe** [comment]
Should be fixed now with  https://github.com/therecipe/qt/commit/86108509bd0c0510a71baea8f6694be341288d88

**Comment by therecipe** [comment]
Will close this, since the status is tracked here https://github.com/therecipe/qt/issues/755#issuecomment-455248057 now
