### ISSUE TITLE
Is it possible to use Sparkle to enable auto update?

### ISSUE THREAD

**Issue by quantonganh** [therecipe/qt#743]
We are adding a new feature for auto update, and found this: https://sparkle-project.org

Looks like Sparkle is being used by multiple apps on my machine:

```
/Applications/VLC.app/Contents/Frameworks/Sparkle.framework
/Applications/TeamViewer.app/Contents/Frameworks/Sparkle.framework
/Applications/Docker.app/Contents/Frameworks/Sparkle.framework
...
```

I found some tutorials showing how to use it in Qt:
- https://github.com/sparkle-project/Sparkle/issues/1137#issuecomment-336667547
- http://www.discoversdk.com/knowledge-base/using-sparkle-in-qt

but it's for C++/Objective C code.

Is it possible to use with Golang?

**Comment by therecipe** [comment]
Hey

Yeah, Sparkle is basically the "default" updater for apps on macOS.
And yes, its possible to use it with Go.

I created a new example that shows you how to use it: https://github.com/therecipe/qt/tree/master/internal/examples/3rdparty/sparkle

Just run the init.sh to download the Sparkle SDK into the darwin dir, and then qtdeploy.
The Sparkle SDK, will automatically be bundled with your application and you will only need to add something like this

```plist
	<key>SUFeedURL</key>
	<string>https://example.com/appcast.xml</string>
	<key>SUPublicEDKey</key>
	<string>someBase64Key</string>
```

to your Info.plist to make it work. (like I did [here](https://github.com/therecipe/qt/blob/master/internal/examples/3rdparty/sparkle/darwin/Contents/Info.plist#L31:L34))

And of course generate the key, sign the new releases and all the other stuff ...

**Comment by quantonganh** [comment]
@therecipe How can I move that button to the Application menu?

![screenshot_2018-12-07_09_06_35](https://user-images.githubusercontent.com/1568504/49624234-412b4200-fa03-11e8-8b4d-ab098514739c.jpg)

**Comment by arknable** [comment]
I think we can use `QMainWindow` and add action to the menu bar. but the problem is main window is returned by `objectCreated` signal and `QApplication::mainWindow` as `QObject` and `QWidget` ... while we can't convert them to `QMainWindow` in go.

@therecipe can you confirm ? do I have the correct understanding ?

**Comment by arknable** [comment]
I tried to add the action via `QWidget` but the menu didn't added, I think it was added to context menu instead of menubar.

**Comment by therecipe** [comment]
@quantonganh @arknable 

If the application is an `QApplication` (required for quick.QQuickView or the widgets module in general), then you can use something like this on macOS (and probably Linux) to create a global MenuBar.

```go
action := widgets.NewQMenuBar(nil).AddMenu2("").AddAction("check for updates")
action.SetMenuRole(widgets.QAction__ApplicationSpecificRole)
action.ConnectTriggered(func(bool) { println("triggered: check for updates") })
```

more infos [here](http://doc.qt.io/qt-5/qmenubar.html#qmenubar-as-a-global-menu-bar)

If you however just use an QGuiApplication (with QQmlApplicationEngine or something), then you will need to either replace the QGuiApplication with QApplication first, or create the MenuBar from within Qml and then callback into Go to invoke the checkUpdates function.
Infos about MenuBar in [QuickControls1](https://doc.qt.io/qt-5/qml-qtquick-controls-applicationwindow.html#menuBar-prop) and [QuickControls2](https://doc.qt.io/qt-5/qml-qtquick-controls2-applicationwindow.html#menuBar-prop)

@arknable 
Yeah, I also tried to cast the `ApplicationWindow` from the `objectCreated` signal into an QMainWindow but the underlying types are probably to different, so it didn't work for me as well.

**Comment by arknable** [comment]
@therecipe so for now the only way to do that is via cgo, perhaps ... right ?

**Comment by therecipe** [comment]
no, you can upcast with `(*widgets.QWidget).QObject` or `(*widgets.QWidget).QObject_PTR()` or downcast with something like `widgets.NewQWidgetsFromPointer(someObject.Pointer())` for example

**Comment by arknable** [comment]
@therecipe ah I thought that kind of functions is using pointer from internal cgo process hehe ... nice tips.

**Comment by Raj-7799** [comment]
@therecipe I downloaded the same example and ran `init.sh` and `qtdeploy` but it seems whenever I try to run the app. It gives the following output. 
`dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/raj/Desktop/projects/qt_sample_app/deploy/darwin/qt_sample_app.app/Contents/MacOS/./qt_sample_app
  Reason: image not found
[1]    186 abort      ./qt_sample_app`

The Sparkle.framework folder is present under `/Contents/Frameworks`. Not sure what could be the issue. Can you please advise?
