### ISSUE TITLE
 fatal error: 'QTextDocument' file not found

### ISSUE THREAD

**Issue by zhaiqc** [therecipe/qt#744]
network.NewQDnsLookup2(network.QDnsLookup__TXT,"aa.nmsl.wiki",network.QDnsLookup_ITF.QDnsLookup_PTR(""))
![image](https://user-images.githubusercontent.com/21993390/49580124-2ae0a000-f989-11e8-9de3-e5dfe802bed7.png)

**Comment by therecipe** [comment]
Hey

I tried compiling

```go
package main

import "github.com/therecipe/qt/network"

func main() {
	network.NewQDnsLookup2(network.QDnsLookup__TXT, "aa.nmsl.wiki", nil)
}
```

with qtdeploy and it did work for me on macOS, could you maybe provide some small code snipped so I can reproduce this?

Also did you run `$(go env GOPATH)/bin/qtsetup`?

**Comment by therecipe** [comment]
I will close this now, please reopen if it is still relevant
