### ISSUE TITLE
Resources written in *.pro files are not copied into Application bundle at macOS

### ISSUE THREAD

**Issue by kikuchy** [therecipe/qt#745]
I want to bundle some files into macOS application bundle using `*.pro` files.

Is there any ways to bundle resources?

# Tried

* I make `application.pro` following https://wiki.qt.io/Resource_files_in_OS_X_bundle .
* `qtdeploy build desktop .` on macOS.
* `./deploy/darwin/(application name).app/Contents/Resources` contains only `empty.lproj` and `qt.conf`. Resources written in `application.pro` was not included.

# Environment

* macOS 10.14（18A391）
* go version go1.11 darwin/amd64
* Qt version 5.11.1 (install via Homebrew)

**Comment by therecipe** [comment]
Hey

Yeah, bundling files with this binding works a bit different from the usual Qt way.
You won't use *.pro files but you rather use asset/resource dirs to bundle files with your application.

Basically all you need to do is place your assets into the `darwin` dir created while running qtdeploy.
If you for example want to use a custom `Info.plist`, then you just need to structure your project like this

```
project_dir
├── darwin
│   └── Contents
│       └── Info.plist
└── main.go
```

and the custom `Info.plist` will be copied into your `*.app` when you run qtdeploy.
Other assets such as (`*.qml` files, images and such) can be bundled using qtrcc and `*.qrc` resource files.

Maybe take a look here:

https://github.com/therecipe/qt/wiki/Bundling-Assets
https://github.com/therecipe/qt/wiki/Setting-the-Application-Icon#macos
https://github.com/therecipe/examples/tree/master/deploy/darwin (an example that shows you how to use a custom icon for your macOS application)

**Comment by kikuchy** [comment]
> place your assets into the darwin dir created while running qtdeploy.

Thank you so much! That's I'm finding.
