### ISSUE TITLE
Compilation randomly fails on Windows 10

### ISSUE THREAD

**Issue by spieglt** [therecipe/qt#751]
I'm using Windows 10 and QT 5.11.1. Both in my app and the examples, compilation just randomly fails. About half the time, the `internal\examples\common\widgets_demo ` example builds perfectly. The other half of the time, this happens:

> PS C:\Users\Admin\go\src\github.com\therecipe\qt\internal\examples\common\widgets_demo> qtdeploy.exe test desktop
> ERRO[0005] failed to run command                         _func=RunCmd cmd="go build -p 4 -v -ldflags=all=\"-s\" \"-w\" \"-H=windowsgui\" -o C:\\Users\\Admin\\go\\src\\github.com\\therecipe\\qt\\internal\\examples\\common\\widgets_demo\\deploy\\windows\\widgets_demo.exe -tags=\"minimal\"" dir="C:\\Users\\Admin\\go\\src\\github.com\\therecipe\\qt\\internal\\examples\\common\\widgets_demo" env=[REDACTED BUT ENV VARS ARE SET PROPERLY FOR QT] ALLUSERSPROFILE=C:\\ProgramData ProgramFiles=C:\\Program Files ConEmuPID=4236 ConEmuWorkDrive=C: OneDrive=C:\\Users\\Admin\\OneDrive PROCESSOR_REVISION=5e03 ANSICON_DEF=7 CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files ConEmuBaseDir=C:\\Program Files\\ConEmu\\ConEmu ConEmuBackHWND=0x000301FA PROCESSOR_LEVEL=6 ProgramW6432=C:\\Program Files SystemRoot=C:\\WINDOWS CGO_ENABLED=1 GOROOT=C:\\Go\\ ComSpec=C:\\WINDOWS\\system32\\cmd.exe ConEmuArgs2= PROCESSOR_ARCHITECTURE=AMD64 ProgramData=C:\\ProgramData ConEmuANSI=ON ConEmuAnsiLog= ConEmuArgs= ConEmuPalette=<ConEmu> USERPROFILE=C:\\Users\\Admin VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\ TEMP=C:\\Users\\Admin\\AppData\\Local\\Temp CGO_CXXFLAGS_ALLOW=\".*\" ConEmuDrive=C:" error="exit status 2" name="build for windows on windows"
> \# github.com/therecipe/qt/internal/examples/common/widgets_demo
> C:\Go\pkg\tool\windows_amd64\link.exe: running g++ failed: exit status 1
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000002.o:rcc.cpp:(.eh_frame+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o: In function `QAbstractItemModel_Index':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\core/core-minimal.cpp:114: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o: In function `QAbstractItemModel_Parent':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\core/core-minimal.cpp:119: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o: In function `QAbstractItemModel_Data':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\core/core-minimal.cpp:124: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o: In function `QAbstractItemModel___layoutChanged_parents_atList':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\core/core-minimal.cpp:245: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o: In function `QAbstractListModel_Index':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\core/core-minimal.cpp:515: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o:C:\Users\Admin\Go\src\github.com\therecipe\qt\core/core-minimal.cpp:523: more undefined references to `_Unwind_Resume' follow
> 
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o:core-minimal.cpp:(.eh_frame$_ZN20MyQAbstractItemModelD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o:core-minimal.cpp:(.eh_frame$_ZN20MyQAbstractItemModelD0Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o:core-minimal.cpp:(.eh_frame$_ZN21MyQAbstractTableModelD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o:core-minimal.cpp:(.eh_frame$_ZN21MyQAbstractTableModelD0Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o:core-minimal.cpp:(.eh_frame$_ZN20MyQAbstractListModelD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000006.o:core-minimal.cpp:(.eh_frame$_ZN20MyQAbstractListModelD0Ev+0x13): more undefined references to `__gxx_personality_v0' follow
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o: In function `QAbstractButton_SetText':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\widgets/widgets-minimal.cpp:208: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o: In function `QAbstractButton_Icon':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\widgets/widgets-minimal.cpp:229: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o: In function `QAbstractButton_Text':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\widgets/widgets-minimal.cpp:235: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\Go\src\github.com\therecipe\qt\widgets/widgets-minimal.cpp:234: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o: In function `QAbstractGraphicsShapeItem_NewQAbstractGraphicsShapeItem':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\widgets/widgets-minimal.cpp:251: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o:C:\Users\Admin\Go\src\github.com\therecipe\qt\widgets/widgets-minimal.cpp:270: more undefined references to `_Unwind_Resume' follow
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o:widgets-minimal.cpp:(.eh_frame$_ZN17MyQAbstractButtonD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o:widgets-minimal.cpp:(.eh_frame$_ZN17MyQAbstractButtonD0Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o:widgets-minimal.cpp:(.eh_frame$_ZN13MyQToolButtonD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o:widgets-minimal.cpp:(.eh_frame$_ZN13MyQToolButtonD0Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o:widgets-minimal.cpp:(.eh_frame$_ZN14MyQRadioButtonD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000010.o:widgets-minimal.cpp:(.eh_frame$_ZN14MyQRadioButtonD0Ev+0x13): more undefined references to `__gxx_personality_v0' follow
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o: In function `QBitmap_NewQBitmap':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\gui/gui-minimal.cpp:86: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o: In function `QBitmap_NewQBitmap6':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\gui/gui-minimal.cpp:91: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o: In function `QBitmap_NewQBitmap2':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\gui/gui-minimal.cpp:96: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o: In function `QBitmap_NewQBitmap4':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\gui/gui-minimal.cpp:101: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o: In function `QBitmap_NewQBitmap5':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\gui/gui-minimal.cpp:106: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o:C:\Users\Admin\Go\src\github.com\therecipe\qt\gui/gui-minimal.cpp:111: more undefined references to `_Unwind_Resume' follow
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o:gui-minimal.cpp:(.eh_frame$_ZN9MyQBitmapD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o:gui-minimal.cpp:(.eh_frame$_ZN9MyQBitmapD0Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o:gui-minimal.cpp:(.eh_frame$_ZN17MyQGuiApplicationD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o:gui-minimal.cpp:(.eh_frame$_ZN17MyQGuiApplicationD0Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o:gui-minimal.cpp:(.eh_frame$_ZN13MyQIconEngineD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000014.o:gui-minimal.cpp:(.eh_frame$_ZN13MyQIconEngineD0Ev+0x13): more undefined references to `__gxx_personality_v0' follow
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o: In function `Z17qRegisterMetaTypeIP12MyQQuickItemEiPKcPT_N9QtPrivate21MetaTypeDefinedHelperIS4_Xaasr12QMetaTypeId2IS4_E7DefinedntsrS9_9IsBuiltInEE11DefinedTypeE':
> C:/Qt/5.11.1/mingw53_32/include/QtCore/qmetatype.h:1747: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o: In function `QQuickItem_NewQQuickItem':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\quick/quick-minimal.cpp:45: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o: In function `QQuickItem_QQuickItem_Tr':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\quick/quick-minimal.cpp:50: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\Go\src\github.com\therecipe\qt\quick/quick-minimal.cpp:50: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o: In function `Z17qRegisterMetaTypeIP14MyQQuickWidgetEiPKcPT_N9QtPrivate21MetaTypeDefinedHelperIS4_Xaasr12QMetaTypeId2IS4_E7DefinedntsrS9_9IsBuiltInEE11DefinedTypeE':
> C:/Qt/5.11.1/mingw53_32/include/QtCore/qmetatype.h:1747: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o:C:\Users\Admin\Go\src\github.com\therecipe\qt\quick/quick-minimal.cpp:258: more undefined references to `_Unwind_Resume' follow
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o:quick-minimal.cpp:(.eh_frame$_ZN12MyQQuickItemD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o:quick-minimal.cpp:(.eh_frame$_ZN12MyQQuickItemD0Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o:quick-minimal.cpp:(.eh_frame$_ZN14MyQQuickWidgetD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o:quick-minimal.cpp:(.eh_frame$_ZN14MyQQuickWidgetD0Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o:quick-minimal.cpp:(.eh_frame$_ZN14MyQQuickWindowD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000018.o:quick-minimal.cpp:(.eh_frame$_ZN14MyQQuickWindowD0Ev+0x13): more undefined references to `__gxx_personality_v0' follow
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000029.o: In function `Z17qRegisterMetaTypeIP11MyQJSEngineEiPKcPT_N9QtPrivate21MetaTypeDefinedHelperIS4_Xaasr12QMetaTypeId2IS4_E7DefinedntsrS9_9IsBuiltInEE11DefinedTypeE':
> C:/Qt/5.11.1/mingw53_32/include/QtCore/qmetatype.h:1747: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000029.o: In function `QJSEngine_NewQJSEngine':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\qml/qml-minimal.cpp:38: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000029.o: In function `QJSEngine_NewQJSEngine2':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\qml/qml-minimal.cpp:56: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000029.o: In function `QJSEngine_QJSEngine_Tr':
> C:\Users\Admin\Go\src\github.com\therecipe\qt\qml/qml-minimal.cpp:62: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\Go\src\github.com\therecipe\qt\qml/qml-minimal.cpp:62: undefined reference to `_Unwind_Resume'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000029.o:C:/Qt/5.11.1/mingw53_32/include/QtCore/qmetatype.h:1747: more undefined references to `_Unwind_Resume' follow
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000029.o:qml-minimal.cpp:(.eh_frame$_ZN11MyQJSEngineD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000029.o:qml-minimal.cpp:(.eh_frame$_ZN11MyQJSEngineD0Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000029.o:qml-minimal.cpp:(.eh_frame$_ZN12MyQQmlEngineD1Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000029.o:qml-minimal.cpp:(.eh_frame$_ZN12MyQQmlEngineD0Ev+0x13): undefined reference to `__gxx_personality_v0'
> C:\Users\Admin\AppData\Local\Temp\go-link-021289935\000029.o:qml-minimal.cpp:(.eh_frame+0xa7): undefined reference to `__gxx_personality_v0'
> collect2.exe: error: ld returned 1 exit status
> 
> 
> PS C:\Users\Admin\go\src\github.com\therecipe\qt\internal\examples\common\widgets_demo>

Not sure what would cause this issue and not finding much helpful in that output. I'm running the exact command every time, closing the app if it built successfully. Sometimes it fails multiple times in a row, sometimes not. Please advise. Thank you!

**Comment by spieglt** [comment]
Update: on a Linux Mint 18 partition of the same machine, using Qt 5.12.0, the same example builds perfectly every time. Should I switch to 5.12.0 on Windows?

**Comment by therecipe** [comment]
Hey

These `__gxx_personality_v0` and `_Unwind_Resume` undefined reference errors are probably caused by another gcc or msvc installation somewhere in your PATH. You might need to remove those from the path to make it work.

Updating to 5.12 will probably make no difference, but I'm not sure, so it might be worth a try.

**Comment by spieglt** [comment]
Should I only have either gcc or msvc installed? I did have VS2015 and VS2017, so uninstalling 2015. And I have an old TDM-GCC installation, but if I change its path, then qtsetup can't seem to find g++. Where should g++ be coming from?

**Comment by therecipe** [comment]
>Should I only have either gcc or msvc installed?

You can probably keep msvc installed, as long as Qt's mingw gcc version is referenced first before msvc or some other gcc version (such as TDM's) installation in your path.

>Where should g++ be coming from?

Qt's mingw gcc version can be found somewhere like `C:\Qt\Tools\mingw530_32\bin` on windows.

You could also use the mingw shell that got installed with Qt.
Maybe check the start menu and search for "Qt" or "mingw", if you use that one instead then you don't have to lookup the gcc path yourself and you also don't need to permanently change your path.

**Comment by spieglt** [comment]
Thanks, that was it.
