### ISSUE TITLE
why my qtsetup.exe need "env_windows_amd64_512"

### ISSUE THREAD

**Issue by ercJuL** [therecipe/qt#753]
I run qtsetup.exe but it's failed. it's need "env_windows_amd64_512" but it's not in github

`time="2018-12-21T08:34:28+08:00" level=error msg="failed to run command" _func=RunCmd cmd="go list -f {{.Dir}} github.com/therecipe/env_windows_amd64_512" dir= env= error="exit status 1" name="get env dir"
can't load package: package github.com/therecipe/env_windows_amd64_512: cannot find package "github.com/therecipe/env_windows_amd64_512" in any of:
        D:\Program\Go\src\github.com\therecipe\env_windows_amd64_512 (from $GOROOT)
        D:\GoPATH\src\github.com\therecipe\env_windows_amd64_512 (from $GOPATH)`

**Comment by therecipe** [comment]
Hey

Sorry, I'm currently working on this I will sort this out in 10 min.

**Comment by therecipe** [comment]
Should be fixed now with https://github.com/therecipe/qt/commit/3d04e41a82127efdaf8198f60646f5c7f590c0e5

I'm currently working on a more comfortable way to setup the binding, and I haven't added the setup for windows yet. Once the support is there I will create a new repo called `env_windows_amd64_512` that will contain all the necessary binaries to get this binding working on windows without the need to manually download and install Qt.

**Comment by ercJuL** [comment]
thanks,
