### ISSUE TITLE
Question about static compilation

### ISSUE THREAD

**Issue by spieglt** [therecipe/qt#754]
I'm working on transitioning my app from wxGo (a wxWidgets wrapper that is no longer maintained) to this. I support Mac, Windows, and Linux. For Mac, I don't need to compile statically as it would be wrapped in an `.app` bundle anyway. But I would very much like to get static compilation working on Linux and Windows and can't seem to do so after a couple days of trying. When I compile Qt statically from source on Linux, errors are thrown when I try to run `qtsetup`. So I saw that in other issues you recommend building the static lib from the version of Qt that is output by the official installer. But even when I `$path_to_qt/configure -static` and `make` on Linux, and then build the `therecipe/qt` examples, they still show as requiring Qt libraries when I run `ldd` against them. Are there any other steps particular to this repo that you'd have to perform after building Qt statically? Or am I still doing something else wrong? Thank you, and thanks for your help with the duplicate compiler issue a few days ago.

**Comment by spieglt** [comment]
Wow, great. Can you make static builds with this setup also?

**Comment by spieglt** [comment]
Got this when trying to install a fresh copy of the repo:
```PS C:\Users\Admin> go get github.com/therecipe/qt/cmd/...
# github.com/therecipe/qt/internal/cmd
Go\src\github.com\therecipe\qt\internal\cmd\cmd.go:23:12: utils.Log.SetFormatter undefined (type *logrus.Logger has no field or method SetFormatter)```

**Comment by therecipe** [comment]
>Wow, great. Can you make static builds with this setup also?

Sadly no, the Qt version that is downloaded when running "go get" is only a shared version.
I might provide static versions as well in the future.

>Got this when trying to install a fresh copy of the repo:

Maybe try running `go get -u -v github.com/therecipe/qt/cmd/...`, it seems like you have some old logrus version installed and using `-u` should update it.
