### ISSUE TITLE
$GOPATH/bin/qtsetup failed

### ISSUE THREAD

**Issue by orange-jacky** [therecipe/qt#773]
macbookpro:Downloads fredlee$ go version
go version go1.12beta2 darwin/amd64

macbookpro:Downloads fredlee$ $GOPATH/bin/qtsetup
INFO[0000] running: 'qtsetup prep'                      
INFO[0000] successfully created qtrcc symlink in your PATH (/usr/local/bin/qtrcc) 
INFO[0000] successfully created qtmoc symlink in your PATH (/usr/local/bin/qtmoc) 
INFO[0000] successfully created qtminimal symlink in your PATH (/usr/local/bin/qtminimal) 
INFO[0000] successfully created qtdeploy symlink in your PATH (/usr/local/bin/qtdeploy) 
INFO[0000] running: 'qtsetup check darwin' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'darwin'        
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.12beta2'   
INFO[0000] GOROOT:                      '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/Users/fredlee/Documents/develop/go/workspace' 
INFO[0000] GOBIN:                    *  '/Users/fredlee/Documents/develop/go/workspace/bin' 
INFO[0000] QT_HASH:                     'e73768bc9bcc6b8cdf6d648be24d3b564ea63cc4' 
INFO[0000] QT_API:                      ''              
INFO[0000] QT_VERSION:                  '5.12.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.12.0'        
INFO[0000] QT_DIR:                      '/Users/fredlee/Qt' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_HOMEBREW:              *  'true'          
INFO[0000] QT_MACPORTS:                 'false'         
INFO[0000] QT_NIX:                      'false'         
INFO[0000] XCODE_DIR:                   '/Applications/Xcode.app' 
INFO[0000] running: 'qtsetup generate darwin' [docker=false] [vagrant=false] 
INFO[0010] generating full qt/core                      
INFO[0032] generating full qt/androidextras             
INFO[0032] generating full qt/gui                       
INFO[0058] generating full qt/network                   
INFO[0066] generating full qt/xml                       
INFO[0068] generating full qt/dbus                      
INFO[0071] generating full qt/nfc                       
INFO[0073] generating full qt/script                    
INFO[0074] generating full qt/sensors                   
INFO[0081] generating full qt/positioning               
INFO[0087] generating full qt/widgets                   
INFO[0147] generating full qt/sql                       
INFO[0151] generating full qt/macextras                 
INFO[0152] generating full qt/qml                       
INFO[0156] generating full qt/websockets                
INFO[0157] generating full qt/xmlpatterns               
INFO[0159] generating full qt/bluetooth                 
INFO[0164] generating full qt/webchannel                
INFO[0165] generating full qt/svg                       
INFO[0167] generating full qt/multimedia                
INFO[0184] generating full qt/quick                     
INFO[0190] generating full qt/help                      
INFO[0196] generating full qt/location                  
INFO[0198] generating full qt/scripttools               
INFO[0199] generating full qt/uitools                   
INFO[0200] generating full qt/webengine                 
INFO[0204] generating full qt/testlib                   
INFO[0205] generating full qt/serialport                
INFO[0206] generating full qt/serialbus                 
INFO[0209] generating full qt/printsupport              
INFO[0214] generating full qt/designer                  
INFO[0224] generating full qt/scxml                     
INFO[0227] generating full qt/gamepad                   
INFO[0229] generating full qt/purchasing                
INFO[0240] generating full qt/datavisualization    [GPLv3] 
INFO[0248] generating full qt/charts               [GPLv3] 
INFO[0264] generating full qt/speech                    
INFO[0265] generating full qt/quickcontrols2            
INFO[0265] generating full qt/sailfish                  
INFO[0265] generating full qt/webview                   
INFO[0266] generating full qt/remoteobjects             
INFO[0268] running: 'qtsetup install darwin' [docker=false] [vagrant=false] 
INFO[0268] installing full qt/core                      
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0284] installing full qt/androidextras             
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0300] installing full qt/gui                       
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0315] installing full qt/network                   
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0330] installing full qt/xml                       
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0346] installing full qt/dbus                      
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0362] installing full qt/nfc                       
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0379] installing full qt/script                    
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0396] installing full qt/sensors                   
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0411] installing full qt/positioning               
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0426] installing full qt/widgets                   
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0443] installing full qt/sql                       
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0458] installing full qt/macextras                 
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0475] installing full qt/qml                       
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0494] installing full qt/websockets                
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0510] installing full qt/xmlpatterns               
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0526] installing full qt/bluetooth                 
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0546] installing full qt/webchannel                
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0564] installing full qt/svg                       
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0581] installing full qt/multimedia                
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0598] installing full qt/quick                     
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0614] installing full qt/help                      
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0630] installing full qt/location                  
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0647] installing full qt/scripttools               
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0663] installing full qt/uitools                   
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0679] installing full qt/webengine                 
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0694] installing full qt/testlib                   
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0710] installing full qt/serialport                
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0726] installing full qt/serialbus                 
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0741] installing full qt/printsupport              
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0755] installing full qt/designer                  
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0769] installing full qt/scxml                     
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0783] installing full qt/gamepad                   
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0798] installing full qt/purchasing                
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0812] installing full qt/datavisualization    [GPLv3] 
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0826] installing full qt/charts               [GPLv3] 
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0842] installing full qt/speech                    
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0858] installing full qt/quickcontrols2            
github.com/therecipe/qt/quickcontrols2
# github.com/therecipe/qt/quickcontrols2
quickcontrols2.cpp:9:10: fatal error: 'QByteArray' file not found

INFO[0859] installing full qt/sailfish                  
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

INFO[0875] installing full qt/webview                   
github.com/therecipe/qt/webview
# github.com/therecipe/qt/webview
webview.cpp:9:10: fatal error: 'QtWebView' file not found

INFO[0876] installing full qt/remoteobjects             
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found

WARN[0891] failed to install:                           
WARN[0891] core                                         
WARN[0891] androidextras                                
WARN[0891] gui                                          
WARN[0891] network                                      
WARN[0891] xml                                          
WARN[0891] dbus                                         
WARN[0891] nfc                                          
WARN[0891] script                                       
WARN[0891] sensors                                      
WARN[0891] positioning                                  
WARN[0891] widgets                                      
WARN[0891] sql                                          
WARN[0891] macextras                                    
WARN[0891] qml                                          
WARN[0891] websockets                                   
WARN[0891] xmlpatterns                                  
WARN[0891] bluetooth                                    
WARN[0891] webchannel                                   
WARN[0891] svg                                          
WARN[0891] multimedia                                   
WARN[0891] quick                                        
WARN[0891] help                                         
WARN[0891] location                                     
WARN[0891] scripttools                                  
WARN[0891] uitools                                      
WARN[0891] webengine                                    
WARN[0891] testlib                                      
WARN[0891] serialport                                   
WARN[0891] serialbus                                    
WARN[0891] printsupport                                 
WARN[0891] designer                                     
WARN[0891] scxml                                        
WARN[0891] gamepad                                      
WARN[0891] purchasing                                   
WARN[0891] datavisualization                            
WARN[0891] charts                                       
WARN[0891] speech                                       
WARN[0891] quickcontrols2                               
WARN[0891] sailfish                                     
WARN[0891] webview                                      
WARN[0891] remoteobjects                                
INFO[0891] running: 'qtsetup test darwin' [docker=false] [vagrant=false] 
INFO[0891] testing qml/application                      
ERRO[0908] failed to run command                         _func=RunCmd cmd="go build -p 4 -v -ldflags=all=\"-w\" -o /Users/fredlee/Documents/develop/go/workspace/src/github.com/therecipe/qt/internal/examples/qml/application/deploy/darwin/application.app/Contents/MacOS/application -tags=\"minimal\"" dir=/Users/fredlee/Documents/develop/go/workspace/src/github.com/therecipe/qt/internal/examples/qml/application env="TERM=xterm-256color GO111MODULES=on LIBRARY_PATH=:/usr/local/lib:/usr/local/lib TERM_SESSION_ID=69529253-A1DD-4692-8C10-E848CAC3F6DE LDFLAGS=-L/usr/local/opt/qt/lib TERM_PROGRAM=Apple_Terminal GO111MODULE=auto ADBPATH=/Users/fredlee/Library/Android/sdk/platform-tools PERL_MM_OPT=INSTALL_BASE=/Users/fredlee/perl5 GOARCH=amd64 USER=fredlee GOPATH=/Users/fredlee/Documents/develop/go/workspace CPPFLAGS=-I/usr/local/opt/qt/include TERM_PROGRAM_VERSION=421.1 PKG_ROOT=/usr/local/lib/pkgconfig QT_HOMEBREW=true CGO_CXXFLAGS_ALLOW=.* CGO_ENABLED=1 PATH=/usr/local/opt/coreutils/libexec/gnubin:/Users/fredlee/Documents/develop/go/workspace/bin:/Applications/mongodb/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/opt/coreutils/libexec/gnubin:/Users/fredlee/Library/Android/sdk/platform-tools:/Users/fredlee/Documents/develop/go/workspace/bin:/Applications/mongodb/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/opt/qt/bin:/usr/local/opt/coreutils/libexec/gnubin:/Users/fredlee/Library/Android/sdk/platform-tools:/Users/fredlee/Documents/develop/go/workspace/bin:/Applications/mongodb/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS DISPLAY=/private/tmp/com.apple.launchd.JmcKDlj5yN/org.macosforge.xquartz:0 _=/Users/fredlee/Documents/develop/go/workspace/bin/qtsetup PWD=/Users/fredlee/Downloads Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.UzHgj4ERgt/Render PERL_MB_OPT=--install_base \"/Users/fredlee/perl5\" OLDPWD=/Users/fredlee/Documents/develop/go/workspace/src/example/thridparty/goquery SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.MM95z4ouBB/Listeners CGO_CFLAGS_ALLOW=.* LANG=zh_CN.UTF-8 DYLD_LIBRARY_PATH=:/usr/local/lib:/usr/local/lib CGO_LDFLAGS_ALLOW=.* GOROOT=/usr/local/go SSLKEYLOGFILE=/Users/fredlee/sslkeylog.log LOGNAME=fredlee XPC_FLAGS=0x0 HOME=/Users/fredlee PKG_CONFIG_PATH=/usr/local/opt/qt/lib/pkgconfig XPC_SERVICE_NAME=0 SHLVL=1 TMPDIR=/var/folders/34/z2z_vp1573g5014m8k7wys100000gn/T/ GOBIN=/Users/fredlee/Documents/develop/go/workspace/bin SECURITYSESSIONID=186a7 GOOS=darwin SHELL=/bin/bash" error="exit status 2" name="build for darwin on darwin"
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core-minimal.cpp:9:10: fatal error: 'QByteArray' file not found

macbookpro:Downloads fredlee$

**Comment by therecipe** [comment]
Hey

Please try running `qtsetup -debug generate` and lookout for errors and/or warnings.
I just tested it, and it did work for me.

Also please show me the content of the `cgo*` file found inside `gihub.com/therecipe/qt/core`

**Comment by orange-jacky** [comment]
running  "qtsetup -debug generate" , please view the flowing file
[qtsetup.log](https://github.com/therecipe/qt/files/2785322/qtsetup.log)

cgo* file content 

> 192:core fredlee$ pwd
/Users/fredlee/Documents/develop/go/workspace/src/github.com/therecipe/qt/core
192:core fredlee$ ll
total 3.1M
-rw-r--r-- 1 fredlee staff  204  1 23 09:40 cgo_darwin_darwin_amd64.go
-rw-r--r-- 1 fredlee staff 1.2M  1 23 09:40 core.cpp
-rw-r--r-- 1 fredlee staff 1.8M  1 23 09:40 core.go
-rw-r--r-- 1 fredlee staff 236K  1 23 09:40 core.h
192:core fredlee$ cat cgo_darwin_darwin_amd64.go 
// +build !ios,!minimal

package core

/*
#cgo CFLAGS: -Wno-unused-parameter -Wno-unused-variable -Wno-return-type
#cgo CXXFLAGS: -Wno-unused-parameter -Wno-unused-variable -Wno-return-type
*/
import "C"
192:core fredlee$

**Comment by orange-jacky** [comment]
thanks, it works for me
