### ISSUE TITLE
docker images deploy with no error but programs not work,

### ISSUE THREAD

**Issue by adneg** [therecipe/qt#779]

**Comment by adneg** [comment]
if i comment/remove this line: 
`//quickcontrols2.QQuickStyle_SetStyle("Material")`
work fine on  windows. 

but on my lilnux old stable debian: 8.11

`
kamil@hpelit[~/go/src/projekty/bestqtwidget/deploy/linux]>> ./bestqtwidget 
./bestqtwidget: relocation error: /home/kamil/go/src/projekty/bestqtwidget/deploy/linux/plugins/platforms/../../lib/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization, version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference

`
maybe I should go to debian 9 but I have a lot of work and now I have a problem.

Some releases would be useful. I should not update docker image

**Comment by adneg** [comment]
I will try build dockfile: 
https://github.com/therecipe/qt/blob/master/internal/docker/linux/Dockerfile



if it does not help me. should I change the versions of qt to older in github.com/therecipe/qt/internal/ci/iscript.qs?

**Comment by adneg** [comment]
Ok a manage with
`kamil@hpelit[~/go/src/projekty/bestqtwidget/deploy/linux]>> ./bestqtwidget ./bestqtwidget: relocation error: /home/kamil/go/src/projekty/bestqtwidget/deploy/linux/plugins/platforms/../../lib/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization, version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time referenc
`
I wget this pull:
qt-3de5d5738194399110f44739e209aa41eaef9a1d.zip
unzip and install qt 5.10.0.

and qtsetup

but still is problem witch
`
quickcontrols2.QQuickStyle_SetStyle("Material"
`

**Comment by therecipe** [comment]
Hey

about the `version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference`, that's probably similar to what happened here: https://bugreports.qt.io/browse/QTBUG-69100
So, 5.10 should still work but it seems like you figured that out already.

Btw, there are docker images for Qt 5.9 and 5.6 called `therecipe/qt:linux_59` and `therecipe/qt:linux_56`, also if you don't need to have it run across different distros, then you could as well use `therecipe/qt:linux_ubuntu_16_04`, `therecipe/qt:linux_ubuntu_18_04` or `therecipe/qt:linux_arch`.
I will see if I can get a trusty version working, which should maybe be compatible with jessie but I haven't tested that...

>but still is problem witch
quickcontrols2.QQuickStyle_SetStyle("Material")

What problems do you encounter ?
Maybe export `QT_DEBUG_CONSOLE=true` or build with something like
`QT_DEBUG_CONSOLE=true qtdeploy -docker ...` to get some console output.
Also did you test the windows application on a VirtualBox VM by any change?
There is a known issue that causes QML applications to not properly work on VirtualBox VMs atm.

**Comment by adneg** [comment]
Thank you for the contact..  
1) 
`
quickcontrols2.QQuickStyle_SetStyle("Material")
`
First step i compiled Application  in the dock therecipe/qt:windows_32_static. New dock image from docker hub.
-Next I move to windows 10 pro 64 bit. 
- execute program and, I see program in task manager but  Aplication Windows is hiden.  

later I will check more styles.

2)
I used this pull  and work on debian 8:
[](https://codeload.github.com/therecipe/qt/zip/3de5d5738194399110f44739e209aa41eaef9a1d)
In docker file: 
[](https://github.com/therecipe/qt/blob/3de5d5738194399110f44739e209aa41eaef9a1d/internal/docker/linux/Dockerfile)

is `
FROM ubuntu:14.04
`

I was sure I would not have problems with qtsetup on my machine:
`
   Ubuntu      |       Debian  
18.04  bionic     buster  / sid   - 10
17.10  artful     stretch / sid   - 9
17.04  zesty      stretch / sid
16.10  yakkety    stretch / sid
16.04  xenial     stretch / sid
15.10  wily       jessie  / sid   - 8
15.04  vivid      jessie  / sid
14.10  utopic     jessie  / sid
14.04  trusty     jessie  / sid
13.10  saucy      wheezy  / sid   - 7
`
but program build in therecipe/qt:linux_ubuntu_16_04 or 18_04  for docker hub not work i debian8.

but I dealt with the problem and there is no need to write more about this.

**Comment by adneg** [comment]
Ok i tested on windows 10 pro 64 bit: QQuickStyle_SetStyle : default  fusion  imagine  material  universal
On windows 10 only default work.
I check on windows serwer 2016 and on fusion  imagine  material  universal i get:
![error](https://user-images.githubusercontent.com/29213941/52245649-da32e800-28e2-11e9-9a33-a65016cab176.png)

**Comment by adneg** [comment]
Ok qml dosen`t work on RDP. QML need opengl1+. And this problem must have been with my application.
