### ISSUE TITLE
RAM Usage

### ISSUE THREAD

**Issue by ohenepee** [therecipe/qt#78]
I haven't started using this great project after I saw the 8GB RAM requirement.. I want to clarify; is this for all platforms or Linux and Mac alone (I'm saying this because  right below that statement is something about `.profile` and `.bash_profile`) so I'm kinda guessing a Windows machine wouldn't need that. In case the requirement is for all platforms is there something being done about reducing the requirement? Cos 8GB is definitely gonna be a huge stumbling block for some of us.

**Comment by therecipe** [comment]
Hey

Unfortunately the 8gb ram requirement is currently for all systems.
The second statement about env variables also applies to Windows users and I probably should edit and/or separate the statements.

But there is hope, I'm currently working on a docker image which will come along with another feature that should reduce the needed amount of ram during the installation. I will therefore generate stub source code that can be  used by `go install` on machines with fewer ram. And if needed provide binary-only packages for machines with even fewer ram.
The installation step in the setup is currently only needed for gocode auto-completion. If you don't need auto-completion you can simply remove or uncomment one line in your setup file https://github.com/therecipe/qt/issues/71#issuecomment-255122240 and run the setup. After the setup completes you can simply use qtdeploy to compile your applications.

**Comment by ohenepee** [comment]
Awww... sweet! So without the auto-completion... no 8GB requirement right?

+1 for the binary-only packages also

**Comment by therecipe** [comment]
Yes, you only need 8gb ram if you want to use auto-completion or the raw `go run/build` command.

**Comment by therecipe** [comment]
Made some changes, your can now define `QT_STUB=true` before running the setup file, this should work on machines with at least 1gb ram.
https://github.com/therecipe/qt#installation
