### ISSUE TITLE
cmd exec question

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#780]
Hi,

I have a textedit widget and type something like: ```ls -lah``` and it lists output in another textedit.

This works correctly when I run qtdeploy and the app auto runs.

When I launch it by clicking on it from deploy folder though I get no output.

I have something like this:
```go
	command := "ls -lah"
	path := `C:\msys64\usr\bin\`
	scommand := strings.Split(path+command, " ")
	cmd := exec.Command(scommand[0], scommand[1:]...)
	cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow: true}	
```

**Comment by therecipe** [comment]
Ah, shit this issue slipped through, sorry.
Hope you were able to resolved it, if not then please reopen.

Usually there should be no difference between using qtdeploy to start your application and starting your application by double clickling it.

The only difference could be the modefied PATH env here:
https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/bundle.go#L309:L313
(which adds `C:\msys64\mingw64\bin` to your path)

Maybe this changed PATH is later inherited while starting the application and therefore acts differently.
