### ISSUE TITLE
Error when run qtsetup on windows 10

### ISSUE THREAD

**Issue by billikill** [therecipe/qt#783]
I get the following error:
https://pastebin.com/uW7J2hhz

Any ideas how to fix this?

**Comment by therecipe** [comment]
Hey

Seems like qtsetup wasn't able to locate your Qt installation.

Which method did you use to install the binding? (Fast track, official or msys2?)

If you did use the official version, then try to create an `QT_DIR` env variable that points to the root dir of your Qt installation before re-running the setup.
