### ISSUE TITLE
Vagrant box not found

### ISSUE THREAD

**Issue by eabz** [therecipe/qt#785]
Hello @therecipe 
Seems that the Vagrant image you use for macOS no longer exists (https://app.vagrantup.com/emil-appunite/boxes/macos10.13-xcode9.1)
I think they changed their username: https://app.vagrantup.com/vagrant-appunite/boxes/macos10.13-xcode9.1

**Comment by therecipe** [comment]
Thank you, I will change it.

**Comment by therecipe** [comment]
Changed it with https://github.com/therecipe/qt/commit/c97efc221f7beff41941803519dccffc8e8deb54#diff-2cd4aea697abc0b5fea6a72b08fee5ec
