### ISSUE TITLE
onActiveChanged is not available on custom type

### ISSUE THREAD

**Issue by tapir** [therecipe/qt#786]
I have a custom type that inherits `QQuickWindow`
```go
type customWindow struct {
	quick.QQuickWindow
	isVisible bool
	_         func()      `constructor:"init"`
	_         func() bool `slot:"toggle,auto"`
}
```

on my qml file I try to do this
```qml
CustomWindow {
    id: window
    flags: Qt.ToolTip | Qt.WA_TranslucentBackground | Qt.FramelessWindowHint
    color: "#00000000"
    visible: false

    onActiveChanged: {
        if (!active) {
            window.toggle()
        }
    }
    ...
}
```
and I get `qrc:/qml/window.qml:13 "CustomWindow.onActiveChanged" is not available in CustomQmlTypes 1.0.`

Shouldn't it be inherited?

**Comment by therecipe** [comment]
Hey

Yeah, it should be inherited and I'm not sure why it's not working.
But there are a few ways to work around this.

The easiest way would be to just use something like this:
```qml
    Connections {
        target: window
        onActiveChanged: {
            console.log("active:", window.active)
            if (!window.active) {
                window.toggle()
            }
        }
    }
```

and another one would be to re-create the `active` property:

```go
type customWindow struct {
	quick.QQuickWindow
	isVisible bool
	_         func()      `constructor:"init"`
	_         func() bool `slot:"toggle,auto"`
	_         bool        `property:"active"`
}

func (c *customWindow) init() {
	c.ConnectIsActive(c.QWindow.IsActive)
	c.QWindow.ConnectActiveChanged(func() { c.ActiveChanged(c.IsActive()) })
}
```
which is probably what happens [here](https://github.com/qt/qtdeclarative/blob/5.12/src/quick/items/qquickwindowmodule.cpp) and [here](https://github.com/qt/qtdeclarative/blob/5.12/src/quick/items/qquickwindowattached.cpp) to make `onActiveChanged` work for the `Window` QML class.

**Comment by tapir** [comment]
I've solved it by putting all the logic to go side. thanks
