### ISSUE TITLE
Request: Example about how to use ImageProvider

### ISSUE THREAD

**Issue by tapir** [therecipe/qt#790]
This one is a little bit tricky due to lack of function override in Go. So I don't know how it's handled by the library.

I see that `QQmlApplicationEngine` implements `addImageProvider` method and there is a `QQmlImageProviderBase` class but how do I create my own struct that implements `QQmlImageProviderBase_ITF`? Which methods does it expect to be implemented and what are the exact names? (As in QT docs, it says `requestPixmap` but that would be not valid in Go as the 'r' means the method is not exported, is it `RequestPixmap` or something else?)

Thanks

**Comment by therecipe** [comment]
Hey

IIRC you can't directly use `QQmlImageProviderBase` atm, but you can use `QQuickImageProvider` instead. Maybe take a look at this example https://github.com/therecipe/qt/issues/582#issuecomment-378296813
(on a side note, it could be that the `LoadFromData` accepts []byte by now, so maybe remove the `string(someImage())` conversion to make it work)

>This one is a little bit tricky due to lack of function override in Go. So I don't know how it's handled by the library.

Function overriding is realized by using `Connect*` functions such as:
```go
(*QQuickImageProvider).ConnectRequestImage(func(id string, size *core.QSize, requestedSize *core.QSize) *gui.QImage { ... })
```

You should be able to simply use `Connect*` functions to override all signal/slot and virtual functions.

So you could call `ConnectSomeFunction(func(){...})` to override the `SomeFunction` function and then call `SomeFunction()` to call your implementation. If the function was implemented already, then you could also call the function with an `*Default` suffix, such as `SomeFunctionDefault()` to call the functions base class implementation.

btw, if you want to subclass `QQmlImageProviderBase` (to extend it with your own signals/slots/properties or something), then you can find an example here https://github.com/therecipe/qt/issues/711#issuecomment-427596919, but that's entirely optional and "subclassing" is not necessary to get it working

**Comment by tapir** [comment]
QQuickImageProvider was actually what I was looking for thanks
