### ISSUE TITLE
The application was unable to start correctly (0x000007b)

### ISSUE THREAD

**Issue by billikill** [therecipe/qt#792]
Hello. I get an error when running app.

package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/qml"
)

func app() {
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)

	gui.NewQGuiApplication(len(os.Args), os.Args)

	var app = qml.NewQQmlApplicationEngine(nil)
	app.Load(core.NewQUrl3("qrc:/qml/test.qml", 0))

	gui.QGuiApplication_Exec()
}

**Comment by akiyosi** [comment]
Hi,

What is the content of `/qml/test.qml`?

**Comment by billikill** [comment]
Hi, 

test.qml

`
import QtQuick 2.12
import QtQuick.Controls 2.12

ApplicationWindow {
    title: "My Application"
    width: 640
    height: 480
    visible: true

    Button {
        text: "Push Me"
        anchors.verticalCenterOffset: -17
        anchors.horizontalCenterOffset: -19
        focusPolicy: Qt.NoFocus
        anchors.centerIn: parent
    }
}
`

**Comment by akiyosi** [comment]
Is this all of your code?
Running your code gets the following.

```
runtime.main_main·f: function main is undeclared in the main package
```

I changed `app()` to `main()` and executed, there is no error, but nothing is displayed.
I think that the code that you do not provide is the cause of the error you encountered.

**Comment by billikill** [comment]
yes, this is all code

**Comment by akiyosi** [comment]
Sorry, the problem that nothing is displayed is due to my environment.
Also, your code works fine in my linux environment.

**Comment by billikill** [comment]
I try to run in windows

**Comment by akiyosi** [comment]
You should check the following.

https://forum.qt.io/topic/46676/solved-the-application-was-unable-to-start-correctly-0xc000007b
https://forum.qt.io/topic/76773/qt-application-gives-0xc000007b-error

**Comment by billikill** [comment]
> You should check the following.
> 
> https://forum.qt.io/topic/46676/solved-the-application-was-unable-to-start-correctly-0xc000007b
> https://forum.qt.io/topic/76773/qt-application-gives-0xc000007b-error

Thanks.
