### ISSUE TITLE
Correct way to deploy image files

### ISSUE THREAD

**Issue by tapir** [therecipe/qt#793]
In my app I have 2 image folders. One is under qml/ and the other one is in the root.
Image files under qml are used by the QML files and qtdeploy successfully copies them to the correct place thus when I run my app they are drawn correctly however the image files in the root are used by go app itself and I don't see them in the .app file -which is expected I guess-. What would be the correct way of doing this? Should I just copy them over to Resource folder and change paths for the mac build?
Thanks

**Comment by therecipe** [comment]
Hey

You can let qtdeploy copy them automatically into your `*.app` if you place them inside the `darwin` subfolder. More info about assets can be found [here](https://github.com/therecipe/qt/wiki/Bundling-Assets) and you can also find a working example (which uses this mechanism to set the application icon) [here](https://github.com/therecipe/examples/tree/master/deploy/darwin)

So something like this should work. (But you are also free to chose any other folder structure inside the `darwin` dir)

```
root_dir
├── darwin
│   └── Contents
│       └── Resources
│           └── someImage.png
├── main.go
└── qml
    ├── main.qml
    └── someQmlImage.png
```

At runtime you could then get the Resource folder with something like `filepath.Join(core.QCoreApplication_ApplicationDirPath(), "..", "Resources")`

**Comment by tapir** [comment]
Thanks
