### ISSUE TITLE
Doesn't react to the  cursor (bug introduced on 5.11)

### ISSUE THREAD

**Issue by Dellu** [therecipe/qt#795]
We have a problem in Texstudio where using keyboard navigation gives wrong results (doesn't react) in the Mac OS. 
The problem is  described here: https://github.com/texstudio-org/texstudio/issues/523

The developers there identified the bug to have been introduced on version 5.11. 

can you guys investigate the issue?

**Comment by akiyosi** [comment]
Are you using this library with your project?

**Comment by therecipe** [comment]
Hey @Dellu 

This repo here is just a Go binding for Qt and it seems like TeXstudio is using Qt directly.
So please open a bug report here instead: https://bugreports.qt.io/browse/QTBUG
The people over there can probably help you better.

I will close this now.
