### ISSUE TITLE
Fail to install MXE's version of Qt on Ubuntu

### ISSUE THREAD

**Issue by zmajew** [therecipe/qt#799]
Hello,
When I run: 
$sudo apt-get -y -qq install mxe-x86-64-w64-mingw32.shared-qt3d mxe-x86-64-w64-mingw32.shared-qtactiveqt ...
it returns:
E: Unable to locate package mxe-x86-64-w64-mingw32.shared-qt3d
E: Couldn't find any package by glob 'mxe-x86-64-w64-mingw32.shared-qt3d'
E: Couldn't find any package by regex 'mxe-x86-64-w64-mingw32.shared-qt3d'
E: Unable to locate package mxe-x86-64-w64-mingw32.shared-qtactiveqt
E: Couldn't find any package by glob 'mxe-x86-64-w64-mingw32.shared-qtactiveqt'
E: Couldn't find any package by regex 'mxe-x86-64-w64-mingw32.shared-qtactiveqt'
E: Unable to locate package mxe-x86-64-w64-mingw32.shared-qtbase
E: Couldn't find any package by glob 'mxe-x86-64-w64-mingw32.shared-qtbase'
...

Than after I run:
$qtsetup full windows
it returns
ERRO[0017] failed to run command                         _func=RunCmd cmd="/usr/lib/mxe/usr/i686-w64-mingw32.shared/qt5/bin/rcc -project -o /home/zeljko/Go/src/github.com/therecipe/qt/internal/examples/qml/application/rcc.qrc" dir=/home/zeljko/Go/src/github.com/therecipe/qt/internal/examples/qml/application/qml env= error="fork/exec /usr/lib/mxe/usr/i686-w64-mingw32.shared/qt5/bin/rcc: no such file or directory" name="execute rcc *.qrc on linux for windows"

How to solve this to deploy on linux for windows?

**Comment by therecipe** [comment]
Hey

It seems like the mxe package servers were down the last few weeks.

I just updated the documentation with the new instructions today.

Maybe try it again, to see how it goes.
https://github.com/therecipe/qt/wiki/Deploying-Linux-to-Windows-64-bit-Shared#mxe-deployment-under-debianubuntu-pre-built

**Comment by therecipe** [comment]
Will close this now, because it should work with the current instructions.
