### ISSUE TITLE
Question: handling nativeEvent

### ISSUE THREAD

**Issue by akiyosi** [therecipe/qt#800]
Hi🙂

I'm creating a frameless window and trying to implement an aero snap feature now.
I installed `nativeEvent` as follows, but on both Windows and MacOS, the application crashes immediately after starting.

How to handle the `nativeEvent` with `therecipe/qt` bindings?

```
package main

import (
	frameless "github.com/akiyosi/goqtframelesswindow"
	"github.com/therecipe/qt/widgets"
)

type framelessTest struct {
	fw *frameless.QFramelessWindow

	app *widgets.QApplication
	win *widgets.QMainWindow
}

func main() {
	a := &framelessTest{}
	a.app = widgets.NewQApplication(0, nil)

	a.fw = frameless.NewQFramelessWindow()
	a.win = a.fw.Window

	// some processes...

	a.fw.SetNativeEvent(a.app)

	a.win.Show()
	a.fw.Widget.SetFocus2()
	a.app.Exec()
}
```

```
package qframelesswindow

import (
	"unsafe"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"

	"github.com/lxn/win"
)

func (f *QFramelessWindow) SetNativeEvent(app *widgets.QApplication) {
	filterObj := core.NewQAbstractNativeEventFilter()
	filterObj.ConnectNativeEventFilter(func(eventType *core.QByteArray, message unsafe.Pointer, result int) bool {
		msg := (*win.MSG)(message)
		switch msg.Message {
		case win.WM_KEYDOWN:
			return false
		default:
			return true
		}
		return filterObj.NativeEventFilter(eventType, message, result)
	})
	app.InstallNativeEventFilter(filterObj)
}
```

All sources are [goqtframelesswindow](https://github.com/akiyosi/goqtframelesswindow).

**Comment by therecipe** [comment]
Hey

These changes should make the nativeEventFilter functions work now https://github.com/therecipe/qt/commit/c97efc221f7beff41941803519dccffc8e8deb54

But I only tested it with some minor change on macOS
```diff
diff --git a/qframelesswindow_darwin.go b/qframelesswindow_darwin.go
index a14533b..20d5587 100644
--- a/qframelesswindow_darwin.go
+++ b/qframelesswindow_darwin.go
@@ -13,7 +13,7 @@ func (f *QFramelessWindow) SetNativeEvent(app *widgets.QApplication) {
        filterObj.ConnectNativeEventFilter(func(eventType *core.QByteArray, message unsafe.Pointer, result int) bool {
                fmt.Println("debug:", eventType)
 
-               return filterObj.NativeEventFilter(eventType, message, result)
+               return false
        })
        app.InstallNativeEventFilter(filterObj)
 }
```

I hope this works on windows as well, if not then please let me know and I will look into it again.

**Comment by akiyosi** [comment]
It was able to work the `nativeEventFilter` function in Windows and MacOS either environment.
Thank you :smiley:

**Comment by therecipe** [comment]
@akiyosi Just a little heads up, I made some changes lately to let `nativeEventFilter` and `nativeEvent` use `*int`.

**Comment by akiyosi** [comment]
OK,
Is there any problem solving behind this fix?

**Comment by therecipe** [comment]
It could be, that it was necessary to get [nativeEvent](https://doc.qt.io/qt-5/qwidget.html#nativeEvent) properly working on windows.
From the docs:
>The result parameter has meaning only on Windows.

**Comment by akiyosi** [comment]
Thank you for quick reply.

BTW, I have a question.
I want to handle `WM_CREATE` message in `ConnectNativeEvent()` of `QMainWindow` which create `NewQMainWindow()`, but can't.
I think `WM_CREATE` message sent when `NewQMainWindow()` called, so it can not catch in `ConnectNativeEvent()`
Is my recognition correct? Also, is there a way to handle `WM_CREATE`?

**Comment by akiyosi** [comment]
I explain the background of the above question.

I'm trying to add shadows to frameless window with `ConnectNativeEvent` of `QMainWindow`.
I confirmed the strange behavior that the window has a shadow when processing `WinId()` but it has no shadow when commented out it.
I thought that something was affecting the window creation process in the `WinId()`.
Also, I thought that it would be best to change the style in the handling of the `WM_CREATE` message.

``` go
package qframelesswindow

import (
	"unsafe"

	"github.com/therecipe/qt/core"
	win "github.com/akiyosi/w32"
)

func (f *QFramelessWindow) SetNativeEvent() {
	f.winid = f.Window.WinId()   // the window has no shadow when commented out this line.
	f.Window.ConnectNativeEvent(func(eventType *core.QByteArray, message unsafe.Pointer, result *int) bool {
		msg := (*win.MSG)(message)
		hwnd := msg.Hwnd
		lparam := msg.LParam

		switch msg.Message {
		case win.WM_NCCALCSIZE:
			if msg.WParam == 1 {
				win.SetWindowLong(hwnd, win.DWL_MSGRESULT, 0)
				return true
			}
			return false

		case win.WM_GETMINMAXINFO:
			mm := (*win.MINMAXINFO)((unsafe.Pointer)(lparam))
			mm.PtMinTrackSize.X = int32(f.minimumWidth)
			mm.PtMinTrackSize.Y = int32(f.minimumHeight)
                
			return true
	
		case win.WM_NCACTIVATE:
			f.putShadow(hwnd)

		}
		return false
	})
}

func (f *QFramelessWindow) putShadow(hwnd win.HWND) {
	if f.borderless {
		return
	}
	// style
	style := win.GetWindowLong(hwnd, win.GWL_STYLE)
	style = style | win.WS_THICKFRAME
	styleptr := uintptr(unsafe.Pointer(&style))
	win.SetWindowLongPtr(hwnd, win.GWL_STYLE, styleptr)

	// shadow
	shadow := &win.MARGINS{1, 1, 1, 1}
	win.DwmExtendFrameIntoClientArea(hwnd, shadow)

	var uflag uint
	uflag = win.SWP_NOZORDER | win.SWP_NOOWNERZORDER | win.SWP_NOMOVE | win.SWP_NOSIZE | win.SWP_FRAMECHANGED
	var nullptr win.HWND
	win.SetWindowPos(hwnd, nullptr, 0, 0, 0, 0, uflag)

	win.ShowWindow(hwnd, win.SW_SHOW)
	f.winid = uintptr(hwnd)
	f.borderless = true
}
```

**Comment by therecipe** [comment]
Hey, it's already late here so I will try to look into this in more depth tomorrow.

But I think if you want to catch the `WM_CREATE` event, then you will need to subclass `QMainWindow` in a moc struct and override the constructor function.

So maybe test this example here and check if the custom window was able to catch the `WM_CREATE` event.

You will need to use `qtmoc && go run` or `qtdeploy` to compile this.

```go
package main

import (
	"os"
	"unsafe"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

type myWindow struct {
	widgets.QMainWindow

	_ func() `constructor:"init"`
}

func (w *myWindow) init() {
	w.SetWindowTitle("myWindow")
	w.ConnectNativeEvent(func(eventType *core.QByteArray, message unsafe.Pointer, result *int) bool {
		println("myWindow", eventType.ConstData())

		//it might be possible to catch the WM_CREATE event here

		return w.NativeEventDefault(eventType, message, result)
	})
}

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	NewMyWindow(nil, 0).Show()

	w := widgets.NewQMainWindow(nil, 0)
	w.SetWindowTitle("stdWindow")
	w.ConnectNativeEvent(func(eventType *core.QByteArray, message unsafe.Pointer, result *int) bool {
		println("stdWindow", eventType.ConstData())
		return w.NativeEventDefault(eventType, message, result)
	})
	w.Show()

	widgets.QApplication_Exec()
}
```

**Comment by akiyosi** [comment]
I appreciate it for your advice! 😃 
I tested your sample code but unfortunately I could not catch `WM_CREATE`.

**Comment by therecipe** [comment]
Okay, looked into this and according to http://arkenthera.github.io/blog/Detecting-external-applicaiton-launch-on-Windows-with-Qt/, you will need to setup an nativeEventFilter for your QApplication.

I tested this with Wine on macOS and it did seem to work:
```go
package main

import (
	"os"
	"unsafe"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"

	win "github.com/akiyosi/w32"
)

func main() {
	app := widgets.NewQApplication(len(os.Args), os.Args)

	filterObj := core.NewQAbstractNativeEventFilter()
	filterObj.ConnectNativeEventFilter(func(eventType *core.QByteArray, message unsafe.Pointer, result *int) bool {
		//println("filter", eventType.ConstData())

		msg := (*win.MSG)(message)
		if eventType.ConstData() == "windows_generic_MSG" || eventType.ConstData() == "windows_dispatcher_MSG" {
			if msg.Message == win.WM_CREATE {
				println("catched WM_CREATE")
			}
		}

		return false
	})
	app.InstallNativeEventFilter(filterObj)

	w := widgets.NewQMainWindow(nil, 0)
	w.SetWindowTitle("stdWindow")
	w.Show()

	widgets.QApplication_Exec()
}
```

**Comment by akiyosi** [comment]
I already tried using `ConnectNativeEventFilter` and putting a shadow in `WM_CREATE`. But I faced the following problems. 
https://stackoverflow.com/questions/55688899/how-to-keep-shadow-in-borderless-window

I tried various implementations and found that [the above source code](https://github.com/therecipe/qt/issues/800#issuecomment-486909160) would work around the problem, but I found that embedding [goqtframelesswindow](https://github.com/akiyosi/goqtframelesswindow) in another application might not display the shadows well. I thought it was a problem due to the timing at which the shadowing process is performed. I also thought that strange behavior by WinId would be a clue to the solution of the timing problem.

However, probably not a problem with the `therecipe/qt` library, So I will close this issue soon.
Thank you very much for your advice.

**Comment by therecipe** [comment]
Ah, okay no problem :)

But from the stackoverflow it seems like you need to do something like
```go
case win.WM_NCCALCSIZE:
	if msg.WParam == 1 {
		*result = 0
		return true
	}
*result = (int)(win.DefWindowProc(msg.Hwnd, win.WM_NCCALCSIZE, msg.WParam, msg.LParam))
return true
```
(I don't know if this actually works or what it does)

But if I did understood correctly, then the return value (true/false) is only there to let Qt know if it should process the event or not.
If you return `true`, then it won't process the event any further.
And if you return `false`, then it will process the event normally.

The important thing for Windows however seems to be, that you "return" something by setting the `*result` like shown above and also use `return true`.

I don't know what exactly you would need to return through the `*result`, but you probably know better.

**Comment by akiyosi** [comment]
I confirmed that the old moc file caused strange behavior.
I am very grateful for your help.😃

**Comment by therecipe** [comment]
You are welcome :)
