### ISSUE TITLE
cgo problem running qtsetup 

### ISSUE THREAD

**Issue by sshikaree** [therecipe/qt#801]
OS: Ubuntu 18.04.2 LTS
go version: go1.12.1 linux/amd64 installed via godeb
Problem:
```
...
INFO[0127] running: 'qtsetup install linux' [docker=false] [vagrant=false] 
INFO[0127] installing full qt/core                      
go install runtime/cgo: open /usr/local/go/pkg/linux_amd64/runtime/cgo.a: permission denied

INFO[0127] installing full qt/androidextras             
go install runtime/cgo: open /usr/local/go/pkg/linux_amd64/runtime/cgo.a: permission denied

INFO[0127] installing full qt/gui                       
go install runtime/cgo: open /usr/local/go/pkg/linux_amd64/runtime/cgo.a: permission denied
...
WARN[0129] failed to install:                           
WARN[0129] core                                         
WARN[0129] androidextras
...
```
Workaround:
Remove "-i" flag from line ```cmd := exec.Command("go", "install", "-i", "-p", strconv.Itoa(runtime.GOMAXPROCS(0)), "-v")``` at https://github.com/therecipe/qt/blob/master/internal/cmd/setup/install.go#L100

**Comment by therecipe** [comment]
This should be fixed now with: https://github.com/therecipe/qt/commit/0167e2b766145ba989798688f125c76f338244ee
(I simply removed the `-i` flag, since the go build cache makes it somewhat obsolete anyway)
