### ISSUE TITLE
qtdeploy doesn't bundle windows folder

### ISSUE THREAD

**Issue by tapir** [therecipe/qt#807]
This one is strange and definitely somehow my fault I just don't know how.

I have linux and darwin folders with assets and on those platforms assets are bundled correctly with the qtdeploy however in windows eventhough I have the windows folder, I don't see the files in the deployment folder and the app crashes at the start due to that.

Any ideas what I might be doing wrong?

**Comment by tapir** [comment]
I think even the qml files are not copied over.

**Comment by therecipe** [comment]
Hey

Do you use msys2 on windows?
Maybe run `qtdeploy -debug` and lookout for any `xcopy` or `cp` entries.

**Comment by tapir** [comment]
Hi yes I'm on MSYS2.
I've just did a grep on the 600 line qtdeploy -debug output and none of the asset files are in there nor my QML files.

I'm using msys2 qt package does that make any difference?

**Comment by tapir** [comment]
I can manually copy the assets over but where should I put the QML files relative to the exe? I load the qml via this line -> `qrc:/qml/MainWindow.qml` I've tried to copy the qml directory to `deploy/windows` but that one didn't seem to work.

**Comment by therecipe** [comment]
Ah sorry, it seems like the asset deployment was buggy for msys2 and mxe builds.

I looked into this and it should be fixed now with https://github.com/therecipe/qt/commit/e1b1bf0d39e83ff07e1a2e3a628e0bc93cbba359#diff-16e44658fb89a392fbb49ad74fdc4570

And about the qml files

>I load the qml via this line -> qrc:/qml/MainWindow.qml

Usually all the files you put inside the qml folder should be automatically embedded into your application. So there should be no need to copy them over as well, if you only want to access them later through `qrc:/...`

Maybe take a look here, in case you haven't already: https://github.com/therecipe/qt/wiki/Bundling-Assets
