### ISSUE TITLE
A sample project with a mainwindow.ui please

### ISSUE THREAD

**Issue by Keyn1** [therecipe/qt#809]
Qt creator in c++ can make the interface of the main window using a file with the extension ui. Give an example please. In your examples not found such a. How do I download the file "mainwindow.ui " in my main window.

**Comment by therecipe** [comment]
Hey

You can find an example about how to use *.ui files here: https://github.com/therecipe/qt/tree/master/internal/examples/uitools/calculator

If you want to convert these *.ui files to *.go files, then you should take a look here: https://github.com/stephenlyu/goqtuic

**Comment by Keyn1** [comment]
thank. helped
