### ISSUE TITLE
GOPATH x is or contains GOROOT

### ISSUE THREAD

**Issue by raff** [therecipe/qt#81]
The check for this (in internal/utils/gopath.go) is wrong:

```
            if strings.Contains(path, runtime.GOROOT()) {
                    err = fmt.Errorf("GOPATH %q is or contains GOROOT", path)
                    return
            }
```

My GOROOT is (on my Mac) /usr/local/go. My GOPATH is /usr/local/gocode. GOPATH is/nor contains GOROOT.

I suggest you add a trailing "/" to runtime.GOROOT() to avoid this issue. The next check may also fail in some circumstances (maybe if my GOPATH was /usr/local/g ?)

Also, maybe you should be using strings.HasPrefix instead of strings.Contains. You really want to check that one path is the prefix of the other.

**Comment by therecipe** [comment]
Hey

Thanks for the info, I will fix it.

**Comment by therecipe** [comment]
Should be fixed with one of the last commits: https://github.com/therecipe/qt/blob/master/internal/utils/gopath.go#L47-L55

**Comment by larrylau** [comment]
this issue has not been fixed.
my GOROOT is d:\go\go and GOPATH is d:\go\golang
so I got this message.
level=error msg="failed to get GOPATH that holds github.com/therecipe/qt" error="GOPATH \"d:\\\\go\\\\golang\" is or contains GOROOT"

**Comment by therecipe** [comment]
Sorry, should be fixed for real this time https://github.com/therecipe/qt/commit/702c18b3817635c9bf545c32bc3eb50fbce7d7e1
