### ISSUE TITLE
Using latest official Qt versions (current and future ones)

### ISSUE THREAD

**Issue by eliezedeck** [therecipe/qt#811]
At this time, the latest Qt version is 5.12.2. Trying to run with this version will fail with the error below, `prep`, `check`, `generate`, `install` seem to all pass, but obviously with some problems.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x84baf4]

goroutine 1 [running]: 
github.com/therecipe/qt/internal/cmd/minimal.Minimal(0xc000163380, 0x55, 0x93df6c, 0x5, 0x0, 0x0)
	/home/elie/tmp/mmmmm/src/github.com/therecipe/qt/internal/cmd/minimal/minimal.go:247 +0x1314
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x93d518, 0x4, 0x93df6c, 0x5, 0xc000163380, 0x55, 0x0, 0x0, 0x0, 0x0, ...)
	/home/elie/tmp/mmmmm/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:78 +0x1592
github.com/therecipe/qt/internal/cmd/setup.Test(0x93df6c, 0x5, 0x930000, 0x0, 0x0)
	/home/elie/tmp/mmmmm/src/github.com/therecipe/qt/internal/cmd/setup/test.go:146 +0x8f5
main.main()
	/home/elie/tmp/mmmmm/src/github.com/therecipe/qt/cmd/qtsetup/main.go:112 +0x49b
```

I'd like to ask how hard is it to compile against current and future versions? I have noticed that the repo is usually a few versions behind.

Thanks.

**Comment by therecipe** [comment]
Hey

Usually the repo should work with all Qt versions ranging from 5.6 to 5.12 out of the box (5.4 might work as well, but is not really fully tested)

Future (major) versions probably won't work out of the box, but minor versions usually should.
I looked into this and fixed it now with  https://github.com/therecipe/qt/commit/e1b1bf0d39e83ff07e1a2e3a628e0bc93cbba359, which makes the binding also forward compatible to Qt 5.13
(There is some minor issue in the Qt 5.13 speech module, but I will wait for the final 5.13 RC first before I look into this again.)

However, it's rather easy to get this working with future untested Qt versions on your own as well.
All you need to do is to set `QT_VERSION` and run the setup, if you are lucky it works out of the box.
If you are unlucky (like in your case) you will only need to set `QT_API` to one of [these](https://github.com/therecipe/qt/tree/master/internal/binding/files/docs) versions
(such as `QT_VERSION=5.12.0`) as well.
This compatibility modus will then generate Go code for the Qt 5.12.0 api, but it will compile and link against the version specified with `QT_VERSION`.
(This should most of the time make it work, but there are also rare cases in which it might not work)

**Comment by eliezedeck** [comment]
Thank you @therecipe ... 5.12.2 working with no issues. **All tests now pass**.
