### ISSUE TITLE
qtdeploy depletes computer resources

### ISSUE THREAD

**Issue by tapir** [therecipe/qt#817]
So I've been having this issue since I've started to use qtdeploy but can't reproduce it in anyway so  I'm just gonna report it here by the chance that you might know what's causing this.

After I do `qtdeploy build linux`, once in a while (this is the part I can't reproduce) I get 8 processes (each) of `as`, `cc1`, `cc1plus`, `cgo`  hanging in the background even after the application finished building. They just keep going and make my machine unusable. I've tried to wait it out but seems like it's not possible. One time I've at least waited for 30 minutes but they didn't exit.

Any ideas? Thanks

**Comment by therecipe** [comment]
Hey

I will investigate and try to reproduce it, but usually it shouldn't be possible for these processes to keep running after a successful build.

However, it could be possible that they keep running after canceling the build with `^C` or something.

But, if you use go modules by any chance, then maybe it's a side effect of `go list` (take a look here https://github.com/golang/go/issues/29452)
Do you use code completion in your editor or IDE?
If yes, then chances are great that `go list` is called somewhere down the line.

**Comment by tapir** [comment]
Hi `go list` is not used but `^C` is used a lot due to compile time taking long and I'm noticing typos etc..
I think that's it! Is it possible to make qtdeploy respond to os signal like below?
```go
terminate = make(chan os.Signal, 1)
signal.Notify(terminate, os.Interrupt, os.Kill, syscall.SIGTERM)
select {
case <-terminate:
//do something
}
```

**Comment by tapir** [comment]
Strangest thing happened just now. I've opened up Visual Studio Code (my choice of IDE for Go) and lots of compiler processes started right away. I did not do any qtdeploy at all. I might add this doesn't happen in any other Go project. What might cause QT and vscode go extension to not play well together?

**Comment by therecipe** [comment]
I will check if I can make use of Notify like in https://github.com/therecipe/qt/issues/817#issuecomment-480071143, but the spawned processes should usually already stop with qtdeploy. (will try to verify that thought)

About the `go list` issue,  I wrote a bit about it here https://github.com/therecipe/qt/issues/755#issuecomment-455248057

>also, golang/go#29452 which causes go list to compile cgo code
and whose workaround CGO_ENABLED=0 won't work if you also use GOPROXY=disallow

So, maybe try to set `CGO_ENABLED=0` in VSCode somehow to work around this.
