### ISSUE TITLE
failed to update QT_VERSION when running qtsetup

### ISSUE THREAD

**Issue by BH90210** [therecipe/qt#818]
Hello,

I'm under Ubuntu 18.04 and got everything working using the official pre-built version of Qt, then updated using the maintenance tool (from 5.12.0 to 5.12.2 cause of a bug with textField..) and removed 5.12.0 since I wouldn't use it anymore.
Qt -via Qt Creator- works fine. Compiles and runs everything on desktop & mobile.

First I tried running `qtdeploy build desktop github.com/myApplication` as usual and got an error about Qt 5.12.0 directory not found.
Then I decided to re-install. I followed the install instructions (I didn't follow this step on the initial setup) and added

```
export QT_DIR=$HOME/Qt
export QT_VERSION=5.12.2
export QT_API=5.12.2
```

to my `~/.profile.` I tried both source `~/.profile` and reboot.
I re-downloaded everything using `sudo go get -u -v -tags=no_env github.com/therecipe/qt/cmd/...`
When I try to run setup `sudo /home/****/go/bin/qtsetup` I get this log and then a bunch of errors following (files not found)
INFO[0000] running: 'qtsetup prep'
INFO[0000] successfully created qtrcc symlink in your PATH (/usr/local/bin/qtrcc)
INFO[0000] successfully created qtmoc symlink in your PATH (/usr/local/bin/qtmoc)
INFO[0000] successfully created qtminimal symlink in your PATH (/usr/local/bin/qtminimal)
INFO[0000] successfully created qtdeploy symlink in your PATH (/usr/local/bin/qtdeploy)
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false]
INFO[0000] GOOS: 'linux'
INFO[0000] GOARCH: 'amd64'
INFO[0000] GOVERSION: 'go1.12'
INFO[0000] GOROOT: '/usr/local/go'
INFO[0000] GOPATH: '/home//go'
INFO[0000] GOBIN: '/home//go/bin'
INFO[0000] QT_HASH: 'da9f0689a846bd6233b12e4a65a8d443fb35f4b3'
INFO[0000] QT_API: ''
INFO[0000] QT_VERSION: '5.12.0'
INFO[0000] QT_VERSION_MAJOR: '5.12.0'
INFO[0000] QT_DIR: '/home/****/Qt'
INFO[0000] QT_STUB: 'false'
INFO[0000] QT_DEBUG: 'false'
INFO[0000] QT_QMAKE_DIR: ''
INFO[0000] QT_WEBKIT: 'false'
INFO[0000] QT_DISTRO: 'ubuntu'
INFO[0000] QT_PKG_CONFIG: 'false'

tried adding
```
export QT_DIR=$HOME/Qt
export QT_VERSION=5.12.2
export QT_API=5.12.2
```
to my `/root/.profile` as well, nothing.

Am I missing something?
I'm stuck, please help.

EDIT: running the qtsetup command with flags -qt_dir, -qt_version, -qt_api seems to fix the problem
`sudo /home/****/go/bin/qtsetup -qt_dir $HOME/Qt -qt_version 5.12.2 -qt_api 5.12.2` (also tried against 5.11.3)
and now I get this error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x848189]

goroutine 1 [running]:
github.com/therecipe/qt/internal/cmd/minimal.Minimal(0xc00001e640, 0x4c, 0x93a331, 0x5, 0x0, 0x0)
	/home/****/go/src/github.com/therecipe/qt/internal/cmd/minimal/minimal.go:247 +0x1409
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x9398d8, 0x4, 0x93a331, 0x5, 0xc00001e640, 0x4c, 0x0, 0x0, 0x0, 0x0, ...)
	/home/****/go/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:78 +0x158f
github.com/therecipe/qt/internal/cmd/setup.Test(0x93a331, 0x5, 0x930000, 0x0, 0x0)
	/home/****/go/src/github.com/therecipe/qt/internal/cmd/setup/test.go:146 +0x97b
main.main()
	/home/****/go/src/github.com/therecipe/qt/cmd/qtsetup/main.go:112 +0x4c6

EDIT 2: fixed my permissions issues, fixed duplicate qt installation (had installed also via apt-get).
But it turns out there is no support for 5.12.1 & 5.12.2?
`$(go env GOPATH)/bin/qtsetup -qt_dir $HOME/Qt -qt_version 5.11.1 -qt_api 5.11.1`
I rolled-back to Qt 5.11.1 and the above command worked for me.

Just a suggestion, maybe alter the documentation making more clear which versions of Qt are supported? Or is it already somewhere and I missed it?

**Comment by therecipe** [comment]
Hey

Sorry, I think this is the result of few unlucky circumstances.
Theoretically you did everything right and one would expect it to work with
`-qt_version 5.12.2 -qt_api 5.12.2` or both of the QT_* env vars set to 5.12.2,
but practically only the `QT_VERSION` var or `-qt_version` flag is necessary in your case.
And the use of the additional `-qt_api` flag or `QT_API` var with 5.12.2 broke your setup.

The thing is that only these versions [here](https://github.com/therecipe/qt/tree/master/internal/binding/files/docs) are supported for the `qt_api` flag or env var at the moment. (the binding should probably work with most if not all versions between 5.6.x and 5.13.x though)

I will add a little check to let the setup fail more gracefully in the future, as the current error is rather misleading.

So, for this to work with 5.12.2 you will only need to export these two env vars
```bash
export QT_DIR=$HOME/Qt
export QT_VERSION=5.12.2
```
before simply running
```bash
$(go env GOPATH)/bin/qtsetup
```

also btw, the `qt_api` flag or `QT_API` var are meant to be used to work around api compatibility issues.
Such as when you want to generate go code for a different Qt version than the Qt version you want to link against.

For example, you want to compile go code that you wrote against the Qt 5.12 api against the Qt 5.13 libs. Then you can use something like `-qt_version=5.13.0 -qt_api=5.12.0` to let your "old" code work with the new Qt version.
(Most code written against Qt 5.12 should directly work with 5.13, but if there would be breaking changes then this flag can be used to quickly work around them)

**Comment by BH90210** [comment]
Thank you. Removed `QT_API` from `~/.profile` and it works.

**Comment by therecipe** [comment]
You are welcome.
The setup should fail more gracefully now and also provide infos about valid api versions with https://github.com/therecipe/qt/commit/0b4efcc3673376434874226ad9c8715fa3bf84b1
