### ISSUE TITLE
qtdeploy -fast throwing error 'QAbstractAnimation' file not found

### ISSUE THREAD

**Issue by andre-l-mm** [therecipe/qt#819]
Hello, 

I went through the documentation and saw that the build time can be improved with qtdeploy `-fast` flag.

My installation was successful (including qtsetup step) and I am able to build my project without the `-fast` flag but when I add this flag I get the error below:

```
qtdeploy -fast build desktop
ERRO[0020] failed to run command                         _func=RunCmd cmd="go build -p 4 -v -ldflags=all=\"-w\" -o /Users/a530616101/Documents/rbc-value/sandbox/tradeui/deploy/darwin/tradeui.app/Contents/MacOS/tradeui -i -tags=\"\"" dir=/Users/a530616101/Documents/rbc-value/sandbox/tradeui env="GOFLAGS=-mod=vendor SHELL=/bin/bash TERM=xterm-256color Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.e5gG8YIwl3/Render OLDPWD=/Users/a530616101 PATH=/Users/a530616101/Applications/mongodb-4.0.2/bin:/Users/a530616101/Applications/sonar-scanner-3.2.0.1227-macosx/bin:/Users/a530616101/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin GOPATH=/Users/a530616101/go GOROOT=/usr/local/go XPC_FLAGS=0x0 XPC_SERVICE_NAME=0 _=/Users/a530616101/go/bin/qtdeploy CGO_ENABLED=1 TERM_PROGRAM=Apple_Terminal TERM_SESSION_ID=A14A7CF2-6975-49D2-896E-76BB802E6E72 PWD=/Users/a530616101/Documents/rbc-value/sandbox/tradeui LANG=en_CA.UTF-8 SHLVL=1 GOOS=darwin TERM_PROGRAM_VERSION=421.1 SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.eTXrfgcy8M/Listeners HOME=/Users/a530616101 LOGNAME=a530616101 GOARCH=amd64 TMPDIR=/var/folders/dr/4hnvllvn3y765fjqj4zf5hdm0000gn/T/ USER=a530616101" error="exit status 2" name="build for darwin on darwin"
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: 'QAbstractAnimation' file not found
```
I am wondering what could be causing this. 

Command: `qtdeploy -fast build desktop`
Operating System: macOS 10.14.2 (18C54)
QT Version: 5.12

**Comment by therecipe** [comment]
Hey

It looks like you are using `go modules`, could it be that you did install the binding while using the GOPATH mode at some point earlier?
If yes, then you will need to install the binding for your project again.
Maybe take a look here https://github.com/therecipe/qt/issues/755#issuecomment-455248057

(Also if you are lucky, then maybe it's also enough to just run `qtsetup` inside your go moduled project folder, without the need to download the binding again like https://github.com/therecipe/qt/issues/755#issuecomment-455248057 instructs you to do.)

**Comment by andre-l-mm** [comment]
Thanks, following the instructions on [#755 Comment](https://github.com/therecipe/qt/issues/755#issuecomment-455248057) as you suggested, worked just fine.
