### ISSUE TITLE
qt controls 2.0 6 Materials Design supported ?

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#82]
http://blog.qt.io/blog/2016/06/10/qt-quick-controls-2-0-a-new-beginning/

Material Design across all devices is something i personally prefer.

Can this be done currently with the current code base in this repo, or is more work required ?

**Comment by joeblew99** [comment]
any takers on this. 
From the QT quick examples it seems that the Material Namespace must be brought in specifically.

But i am not sure...

**Comment by therecipe** [comment]
Hey

This is an example qml file, which you can use as a replacement for `examples/qml/application/qml/application.qml`

Just compile with `qtdeploy` and then start the binary like this
`./application` for the default style
`./application -style material` for the material style
`./application -style universal` for the universal style

I toke the example from here: http://doc.qt.io/qt-5/qtquickcontrols2-styles.html
There you will also find additional informations (for example: you can let the application use the material style by providing a config file, using the style flag, defining environmental variables or use functions in your code)

I'm not sure if QML currently supports the Google Material design, but IIRC it will supported with Qt 5.8.
Also you should be able to use all features of QML, as if you would directly use C++.

```qml
import QtQuick 2.0
import QtQuick.Controls 2.0
import QtQuick.Controls.Material 2.0
import QtQuick.Controls.Universal 2.0

ApplicationWindow {
    visible: true

    Material.theme: Material.Dark
    Material.accent: Material.Purple

    Column {
        anchors.centerIn: parent

        RadioButton { text: qsTr("Small") }
        RadioButton { text: qsTr("Medium");  checked: true }
        RadioButton { text: qsTr("Large") }
    }
}
```

**Comment by joeblew99** [comment]
@therecipe thankyou. thats an awesome example.
I tried it out and it works. 
i am on OSX; and so its builds a .app, for which command line flags dont work, and i could not work out how to use the conf file thats explained in the web page.

Maybe its best to put the example into the examples folder, with a build.sh or build.bat script so that we can work up the example to do the things i could not get going ? Not sure ....

**Comment by therecipe** [comment]
@joeblew99 
Added a new [qml/material](https://github.com/therecipe/qt/tree/master/internal/examples/qml/material) example and fixed the support for the qtquickcontrols2.conf with qtdeploy.

You just need to rebuild qtdeploy from `internal/deploy`, if you don't want to re-run the full setup.

Hope that's what you needed.
I'm off now, but will be back in a few hours.

**Comment by joeblew99** [comment]
@therecipe 
ok that makes sense. Thanks heaps.

I will try it out tomorrow, and report back

**Comment by joeblew99** [comment]
@therecipe 
works perfectly for me. thanks !
I noticed you changed allot in the tooling area now. Really like the new changes, and it will make it easier for me to make some examples and widgets etc and commit back what i can.

Closing...

**Comment by therecipe** [comment]
@joeblew99

Thank you :)
