### ISSUE TITLE
Custom Application Name

### ISSUE THREAD

**Issue by andre-l-mm** [therecipe/qt#828]
Hello, 

This sounds like a pretty basic question but I was not able to find a solution so far. 

QTDeploy is working, and building the app on MacOS. However, the `.app` file is generated with file name in lower case and the application name that shows on the Mac Application bar is lower case too. 

I would like to change that name but could not find the source of it. Tried renaming project folder, Golang project name, go module name but nothing worked. 

I also tried changing the app name with `app.SetApplicationName()` but that didn't work either. 

I also realize that in QT creator that can be changed in TARGET property of the `.pro` file. Is there anything equivalent in `therecipe` binding? 

Any help would be much appreciated.

**Comment by therecipe** [comment]
Hey

No problem, maybe checkout [this](https://github.com/therecipe/examples/tree/master/deploy/darwin) example. 
Especially [this](https://github.com/therecipe/examples/blob/master/deploy/darwin/darwin/Contents/Info.plist#L14) line, which is responsible for the name in the application and dock bar.

All you need to do is to copy your `Info.plist` file from this folder `your_project/deploy/darwin/your_project.app/Contents/` into this folder `your_project/darwin/Contents/` and then change the `CFBundleName` value.
(you will also need to create the `darwin/Contents/` folders first)

Then just run qtdeploy as usual.

Btw, you can run `qtdeploy test desktop github.com/therecipe/examples/deploy/darwin` to directly download and test the example from above.

**Comment by andre-l-mm** [comment]
That worked. Thanks a lot for the detailed instructions.
