### ISSUE TITLE
Install steps don't produce bin folder

### ISSUE THREAD

**Issue by egee-irl** [therecipe/qt#829]
I've walked through the install steps (for Linux) from the Readme and the Wiki and neither are producing the `bin` folder. I have the `src` folder (`~/go/src/github.com/therecipe/`) but no `bin` folder. Are the steps in the documentation incorrect or am I missing an assumption during the install?

**Comment by therecipe** [comment]
Hey

The documentation should be correct, go getting
`go get -v -tags=no_env github.com/therecipe/qt/cmd/...`
should be enough to get qt* tooling installed in either `$(go env GOPATH)/bin` or `$GOBIN` (if set)

Could you re-run `go install -v -tags=no_env github.com/therecipe/qt/cmd/...` ?

**Comment by egee-irl** [comment]
Seems to be working just fine now, both with the commands you posted and now with the commands in the readme.
