### ISSUE TITLE
QMetaMethod::invoke: Unable to handle unregistered datatype 'QSystemTrayIcon::MessageIcon'

### ISSUE THREAD

**Issue by microo8** [therecipe/qt#83]
when I'm calling [`QSystemTrayIcon::showMessage`](http://doc.qt.io/qt-5/qsystemtrayicon.html#showMessage) from other goroutine than the main, it doesn't show the balloon message and prints this warning:
`QMetaMethod::invoke: Unable to handle unregistered datatype 'QSystemTrayIcon::MessageIcon'`

I'm calling it like this: `systray.ShowMessage("title", "message", widgets.QSystemTrayIcon__Information, 5000)`

where is the problem?

**Comment by therecipe** [comment]
Hey

This is strange, `QSystemTrayIcon::showMessage` is labeled as `slot` and should be able to cross threads without problems. I will look into this.

But the example below should work.
You just need to create a custom slot in as subclass of `widgets.QSystemTrayIcon` to wrap your functions calls, if you want to cross threads. 
Or use the "safe" functions labeled `slot` in the Qt docs (even through `QSystemTrayIcon::showMessage` didn't work in that particular case).

You can also take a look at the `qml/bridge` examples to see how your can use slots and signals with parameters and you may want to read http://doc.qt.io/qt-5/signalsandslots.html.

```go
package main

import (
	"os"

	"github.com/therecipe/qt/widgets"
)

type QSystemTrayIconWithCustomSlot struct {
	widgets.QSystemTrayIcon

	_ func() `slot:triggerSlot`
}

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	var (
		widget       = widgets.NewQWidget(nil, 0)
		widgetLayout = widgets.NewQVBoxLayout()
	)
	widget.SetLayout(widgetLayout)

	var systray = NewQSystemTrayIconWithCustomSlot(nil)
	systray.SetIcon(widget.Style().StandardIcon(widgets.QStyle__SP_MessageBoxCritical, nil, nil))

	var systrayMenu = widgets.NewQMenu(nil)
	systrayMenu.AddAction("first action")
	systrayMenu.AddAction("second action")
	systray.SetContextMenu(systrayMenu)

	systray.Show()

	//works
	var buttonMain = widgets.NewQPushButton2("call from main thread", nil)
	buttonMain.ConnectClicked(func(bool) {
		systray.ShowMessage("title", "main thread message", widgets.QSystemTrayIcon__Information, 5000)
	})
	widgetLayout.AddWidget(buttonMain, 0, 0)

	//fails
	var buttonOther = widgets.NewQPushButton2("call from other thread", nil)
	buttonOther.ConnectClicked(func(bool) {
		go func() {
			systray.ShowMessage("title", "other thread message", widgets.QSystemTrayIcon__Information, 5000)
		}()
	})
	widgetLayout.AddWidget(buttonOther, 0, 0)

	//works
	var buttonSlot = widgets.NewQPushButton2("call from other thread with slot", nil)
	systray.ConnectTriggerSlot(func() {
		systray.ShowMessage("title", "other thread message with slot", widgets.QSystemTrayIcon__Information, 5000)
	})
	buttonSlot.ConnectClicked(func(bool) {
		go func() {
			systray.TriggerSlot()
		}()
	})
	widgetLayout.AddWidget(buttonSlot, 0, 0)

	widget.Show()

	widgets.QApplication_Exec()
}
```
