### ISSUE TITLE
go语言编写的QT5程序无法用fcitx输入中文的问题

### ISSUE THREAD

**Issue by rocket049** [therecipe/qt#833]
我发现用`github.com/therecipe/qt`编写的小程序无法使用`fcitx`输入中文。
网上各种设置XIM变量的fcitx都已经设置了，还是没用。
同时`qt creator`是可以用`fcitx`输入中文的。

然后我用`ldd`查看程序链接的动态库发现编译出来的程序链接了`$GOPATH/src/github.com/therecipe/env_linux_amd64_512/5.12.0/gcc_64/`目录里的动态库，
而没有使用系统目录中的动态库，于是我检查了目录`$GOPATH/src/github.com/therecipe/env_linux_amd64_512/5.12.0/gcc_64/plugins/platforminputcontexts/`，
发现里面缺少动态库`libfcitxplatforminputcontextplugin.so`，我抱着试一试的态度，把
`/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`
复制到该目录下，然后打开我的小程序，发现已经可以用`fcitx`输入中文了。

**Comment by apocelipes** [comment]
默认情况下goqt将会使用`QT_DIR`指定目录下的Qt代码/库，如果需要使用通过包管理器安装在系统中的Qt以便利用系统附带的Qt插件，可以在qtsetup时指定`QT_PKG_CONFIG=true`，更具体的描述可以参考这里：[install Qt bindings with system package managers](https://github.com/therecipe/qt/wiki/Installation-on-Linux#your-system-package-managers-version-without-android-support)

**Comment by therecipe** [comment]
@apocelipes thank you :)

**Comment by rocket049** [comment]
@therecipe  我上面已经给出解决方法，希望作者把 `libfcitxplatforminputcontextplugin.so` 预先打包在 `platforminputcontexts`  目录中

**Comment by therecipe** [comment]
The setup will try to copy `libfcitxplatforminputcontextplugin.so` into the `platforminputcontexts` Qt  dir with https://github.com/therecipe/qt/commit/79b8fae1a72310315e04f924fd6a21d9003e1e49#diff-19d3db68f28ce9b950c312ac5c4260e7 now.

**Comment by rocket049** [comment]
@therecipe You are nice!
