### ISSUE TITLE
not support GO111MODULE=on?

### ISSUE THREAD

**Issue by orange-jacky** [therecipe/qt#838]
when GO111MODULE=on  ,it run "go get -u -v github.com/therecipe/qt/cmd/..."  failed,
is it not support go module?

**Comment by therecipe** [comment]
Hey

Take a look here https://github.com/therecipe/qt/issues/755#issuecomment-455248057, you will need to run 
```
go get -u -v github.com/therecipe/qt/cmd/qtsetup && go get -u -v github.com/therecipe/qt/cmd/...
```
to make it work. (This is a Go issue)

I also updated the wiki with new instructions on how to get it working now
https://github.com/therecipe/qt/wiki/Installation-on-Linux#in-module-mode-more-info-here-such-as-how-to-work-around-the-gfw-1
