### ISSUE TITLE
qtsetup full android  fail

### ISSUE THREAD

**Issue by orange-jacky** [therecipe/qt#839]
macos
go version go1.12 darwin/amd64

clang link error, how to fix it

macbookpro:Downloads fredlee$ export GO111MODULE=off
macbookpro:Downloads fredlee$ qtdeploy test desktop github.com/therecipe/examples/basic/widgets
macbookpro:Downloads fredlee$ qtsetup full android
INFO[0000] running: 'qtsetup prep'                      
INFO[0000] successfully created qtrcc symlink in your PATH (/usr/local/bin/qtrcc) 
INFO[0000] successfully created qtmoc symlink in your PATH (/usr/local/bin/qtmoc) 
INFO[0000] successfully created qtminimal symlink in your PATH (/usr/local/bin/qtminimal) 
INFO[0000] successfully created qtdeploy symlink in your PATH (/usr/local/bin/qtdeploy) 
INFO[0000] running: 'qtsetup check android' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'darwin'        
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.12'        
INFO[0000] GOROOT:                      '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/Users/fredlee/Documents/develop/go/workspace' 
INFO[0000] GOBIN:                    *  '/Users/fredlee/Documents/develop/go/workspace/bin' 
INFO[0000] GOMOD:                       ''              
INFO[0000] QT_HASH:                     '47435cc1dd5b08612085c0c0687134bcc7954a02' 
INFO[0000] QT_API:                   *  '5.12.0'        
INFO[0000] QT_VERSION:               *  '5.12.0'        
INFO[0000] QT_DIR:                   *  '/Users/fredlee/Qt5.12.0' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] JDK_DIR:                     '/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home' 
INFO[0000] ANDROID_SDK_DIR:          *  '/Users/fredlee/Library/Android/sdk' 
INFO[0000] ANDROID_NDK_DIR:          *  '/Users/fredlee/Library/Android/sdk/ndk-bundle' 
INFO[0000] running: 'qtsetup generate android' [docker=false] [vagrant=false] 
INFO[0008] generating cgo qt/core                       
INFO[0009] generating cgo qt/androidextras              
INFO[0009] generating cgo qt/gui                        
INFO[0009] generating cgo qt/network                    
INFO[0010] generating cgo qt/xml                        
INFO[0010] generating cgo qt/nfc                        
INFO[0010] generating cgo qt/script                     
INFO[0010] generating cgo qt/sensors                    
INFO[0011] generating cgo qt/positioning                
INFO[0011] generating cgo qt/widgets                    
INFO[0011] generating cgo qt/sql                        
INFO[0012] generating cgo qt/qml                        
INFO[0012] generating cgo qt/websockets                 
INFO[0012] generating cgo qt/xmlpatterns                
INFO[0012] generating cgo qt/bluetooth                  
INFO[0013] generating cgo qt/webchannel                 
INFO[0013] generating cgo qt/svg                        
INFO[0013] generating cgo qt/multimedia                 
INFO[0013] generating cgo qt/quick                      
INFO[0014] generating cgo qt/help                       
INFO[0014] generating cgo qt/location                   
INFO[0014] generating cgo qt/scripttools                
INFO[0015] generating cgo qt/uitools                    
INFO[0015] generating cgo qt/testlib                    
INFO[0015] generating cgo qt/scxml                      
INFO[0015] generating cgo qt/gamepad                    
INFO[0016] generating cgo qt/purchasing                 
INFO[0016] generating cgo qt/datavisualization    [GPLv3] 
INFO[0016] generating cgo qt/charts               [GPLv3] 
INFO[0017] generating cgo qt/speech                     
INFO[0017] generating cgo qt/quickcontrols2             
INFO[0017] generating cgo qt/sailfish                   
INFO[0017] generating cgo qt/webview                    
INFO[0017] generating cgo qt/remoteobjects              
INFO[0018] running: 'qtsetup install android' [docker=false] [vagrant=false] 
INFO[0018] running: 'qtsetup test android' [docker=false] [vagrant=false] 
INFO[0018] testing quick/calc                           
ERRO[0024] failed to run command                         _func=RunCmd cmd="go build -p 4 -v -ldflags=all=\"-s\" \"-w\" -o /Users/fredlee/Documents/develop/go/workspace/src/github.com/therecipe/qt/internal/examples/quick/calc/deploy/android/libgo_base.so -tags=\"android\" \"minimal\" -pkgdir /Users/fredlee/Documents/develop/go/workspace/pkg/android_android_arm -buildmode c-shared" dir=/Users/fredlee/Documents/develop/go/workspace/src/github.com/therecipe/qt/internal/examples/quick/calc env="GOBIN=/Users/fredlee/Documents/develop/go/workspace/bin MONGODB=/Applications/mongodb SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.qb7rnE6hka/Listeners CGO_ENABLED=1 TERM=xterm-256color TERM_SESSION_ID=02FC4942-D5E3-403E-BD40-CBD9B83B12B5 PWD=/Users/fredlee/Downloads CC=/Users/fredlee/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang CGO_CFLAGS_ALLOW=.* ANDROID_HOME=/Users/fredlee/Library/Android/sdk LANG=zh_CN.UTF-8 QT_API=5.12.0 GOARCH=arm CGO_LDFLAGS_ALLOW=.* QT_VERSION=5.12.0 ADBPATH=/Users/fredlee/Library/Android/sdk/platform-tools XPC_FLAGS=0x0 DISPLAY=/private/tmp/com.apple.launchd.xGMuJvpajd/org.macosforge.xquartz:0 GOPATH=/Users/fredlee/Documents/develop/go/workspace TMPDIR=/var/folders/34/z2z_vp1573g5014m8k7wys100000gn/T/ SHELL=/bin/bash TERM_PROGRAM_VERSION=421.1 GO111MODULE=off PERL_MM_OPT=INSTALL_BASE=/Users/fredlee/perl5 GOARM=7 CGO_CPPFLAGS=-D__ANDROID_API__=16 -target armv7-none-linux-androideabi -gcc-toolchain /Users/fredlee/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/fredlee/Library/Android/sdk/ndk-bundle/sysroot -isystem /Users/fredlee/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi CXX=/Users/fredlee/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ CGO_LDFLAGS=-D__ANDROID_API__=16 -target armv7-none-linux-androideabi -gcc-toolchain /Users/fredlee/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/fredlee/Library/Android/sdk/ndk-bundle/platforms/android-16/arch-arm TERM_PROGRAM=Apple_Terminal SSLKEYLOGFILE=/Users/fredlee/sslkeylog.log ANDROID_SDK_DIR=/Users/fredlee/Library/Android/sdk SHLVL=1 PATH=/Users/fredlee/Library/Android/sdk/platform-tools:/usr/local/opt/coreutils/libexec/gnubin:/Users/fredlee/Documents/develop/go/workspace/bin:/Applications/mongodb/bin:/Users/fredlee/Library/Android/sdk/platform-tools:/usr/local/opt/coreutils/libexec/gnubin:/Users/fredlee/Documents/develop/go/workspace/bin:/Applications/mongodb/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS GOROOT=/usr/local/go _=/Users/fredlee/Documents/develop/go/workspace/bin/qtsetup ANDROID_NDK_DIR=/Users/fredlee/Library/Android/sdk/ndk-bundle SECURITYSESSIONID=186a7 PERL_MB_OPT=--install_base \"/Users/fredlee/perl5\" PKG_ROOT=/usr/local/lib/pkgconfig Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.OoLD5nqoK8/Render OLDPWD=/Users/fredlee USER=fredlee XPC_SERVICE_NAME=0 HOME=/Users/fredlee LOGNAME=fredlee GOOS=android CGO_CXXFLAGS_ALLOW=.* QT_DIR=/Users/fredlee/Qt5.12.0 ANDROID_NDK_HOME=/Users/fredlee/Library/Android/sdk/ndk-bundle" error="exit status 2" name="build for android on darwin"
runtime/cgo
# runtime/cgo
clang: error: /Users/fredlee/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64: 'linker' input unused [-Werror,-Wunused-command-line-argument]

**Comment by therecipe** [comment]
Hey

This should be fixed now with https://github.com/therecipe/qt/commit/79b8fae1a72310315e04f924fd6a21d9003e1e49#diff-1630b82908dbc9a3aae774d5e2f6afa8

To make it work you can either patch the `-Wno-unused-command-line-argument` changes manually, or update the binding.

**Comment by orange-jacky** [comment]
it works, thank you , you could close this issue

**Comment by therecipe** [comment]
Okay, will close this now :)
