### ISSUE TITLE
Linux: qtdeploy not in PATH, fails with "import cycle not allowed"

### ISSUE THREAD

**Issue by d10r** [therecipe/qt#84]
I followed the installation instructions for Linux on Ubuntu 14.04.
g++ was 4.8.4 (distro default), older then requested by the doc (>5), however the issue reported here doesn't seem to be related.

After installing, I tried to build the example app as described in https://github.com/therecipe/qt#example.
First I failed with `qtdeploy not found`. Turned out it's not symlinked into a directory in PATH if not run as root, see https://github.com/therecipe/qt/blob/master/internal/setup/test.go#L48.
After linking it manually, `qtdeploy build desktop` fails with

```
build_1
output:import cycle not allowed
package github.com/therecipe/qt/internal/examples/uitools/calculator
        imports github.com/therecipe/qt/core
        imports github.com/therecipe/qt/core

error:exit status 1
```

Running it for an existing example (e.g. calculator) fails with the same message.
Which is weird because the setup script did successfully build and run the examples.

**Comment by therecipe** [comment]
Hey

You probably got some wrong files in you `qt/*` subfolders.
The simplest solution would be to remove the whole `therecipe/qt` dir from your $GOPATH and just clone the repo and re-run the setup again.
