### ISSUE TITLE
clean msys2 windows setup: missing dll files on deploy folder

### ISSUE THREAD

**Issue by tapir** [therecipe/qt#847]
Looks like 

```
libicudt64.dll
libicuin64.dll
libicuuc64.dll
```

files are missing after a successful `qtdeploy build windows`

**Comment by therecipe** [comment]
Hey

Thanks for the info, it should be fixed now with https://github.com/therecipe/qt/commit/c8497dbdcf68bd7ac2733a2d854ffda7f4fc7696#diff-16e44658fb89a392fbb49ad74fdc4570
