### ISSUE TITLE
Error running qtdeploy build desktop

### ISSUE THREAD

**Issue by andre-l-mm** [therecipe/qt#849]
Hello, 

I recently updated go to `1.12.4` and ran therecipe qt binding setup again for a project that was previously working fine. 

The initial therecipe setup works ok. However, now I am not able to run a full build anymore. Details below:

```
qtdeploy build desktop

error="exit status 1" name="get import path"
build rbcgithub.fg.rbc.com/UZ40/tradeui: cannot load github.com/therecipe/qt/core: no Go source files
```
I am using go modules and I am not sure why it is not able to find the qt core files.  All dependencies seem to be in vendor folder as expected. Am I missing anything?

**Comment by therecipe** [comment]
Hey

Could you post the output of `qtdeploy -debug build desktop`, so I can look into this?
Also maybe the output of`$GOPATH/bin/qtsetup check`?

**Comment by andre-l-mm** [comment]
The output of `qtdeploy -debug build desktop` is attached. 

Here is the output of `$GOPATH/bin/qtsetup check`:
```
INFO[0000] running: 'qtsetup check darwin' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'darwin'        
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.12.4'      
INFO[0000] GOROOT:                      '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/Users/a530616101/go' 
INFO[0000] GOBIN:                       '/Users/a530616101/go/bin' 
INFO[0000] GOMOD:                       '/Users/a530616101/Documents/rbc-value/sandbox/tradeui/go.mod' 
INFO[0000] QT_HASH:                     '2a7512c9676520e7daad930ace42689367f41138' 
INFO[0000] QT_API:                      ''              
INFO[0000] QT_VERSION:                  '5.12.0'        
INFO[0000] QT_DIR:                      '/Users/a530616101/Qt' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_HOMEBREW:                 'false'         
INFO[0000] QT_MACPORTS:                 'false'         
INFO[0000] QT_NIX:                      'false'         
INFO[0000] QT_FELGO:                    'false'         
INFO[0000] XCODE_DIR:                   '/Applications/Xcode.app'
```
[qtdeploy_debug.log](https://github.com/therecipe/qt/files/3121454/qtdeploy_debug.log)

**Comment by therecipe** [comment]
Thanks, I looked into this and it might be that these two changes https://github.com/therecipe/qt/commit/120a741ef613ab95a16508cd2c4681ebd0545f49#diff-0b920e11d23aaee04d124651588f95e0 https://github.com/therecipe/qt/commit/120a741ef613ab95a16508cd2c4681ebd0545f49#diff-8f782e894fa2d2161e1d9ecb7397197f
fix it.

Can you update qtdeploy and then try to build you application again?

Also if this won't work, could you enable cgo in this line https://github.com/therecipe/qt/blob/master/internal/utils/env.go#L350 with `CGO_ENABLED=1` and test it as well?

**Comment by andre-l-mm** [comment]
Hello, 

It worked with the fix. I updated therecipe/qt with the [Fast Track Installation Command - In Module Mode](https://github.com/therecipe/qt/wiki/Installation-on-macOS#in-module-mode-more-info-here-such-as-how-to-work-around-the-gfw). 

After that `qtdeploy build desktop` started working again. 

Thanks for your help on this.

**Comment by therecipe** [comment]
No problem, you are welcome
