### ISSUE TITLE
MSpanList_Insert error MacOS 

### ISSUE THREAD

**Issue by danzar** [therecipe/qt#85]
I received an error when running the 
cd $GOPATH/src/github.com/therecipe/qt && ./setup.sh item

batman in ~/GoWorkSpace/src/github.com/therecipe/qt/internal/setup on master ● λ cd $GOPATH/src/github.com/therecipe/qt && ./setup.sh

go get golang.org/x/crypto/ssh
go get github.com/emirpasic/gods/lists/arraylist
go run $GOPATH/src/github.com/therecipe/qt/internal/setup/check.go "$@"
go run $GOPATH/src/github.com/therecipe/qt/internal/setup/generate.go "$@"
.# command-line-arguments
failed MSpanList_Insert 0x47dcc0 0x8d60f8f43b8f 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x2a3340, 0x10)
	/usr/local/go/src/runtime/panic.go:530 +0x90
runtime.(*mSpanList).insert(0x3a58a8, 0x47dcc0)

**Comment by therecipe** [comment]
Hey

Are you on macOS Sierra?
Which go version are your using?

I have no idea how to solve this, but I found a few related issues:
https://github.com/golang/go/issues/16352
https://github.com/golang/go/issues/17335
https://github.com/golang/go/issues/17570

It seems to be a problem from Go itself.

**Comment by danzar** [comment]
Hi Sorry for not supplying that info to begin with.

Go: 1.7.3
MacOS: Sierra

Yes, it does seem to appear it from them links to be out of your hands :)
I think I might create a VM from an earier release. 
I believe you can prob close this issue then as has nothing to do with your code directly.
