### ISSUE TITLE
debugging possible memory allocation issues (using qt static version)

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#851]
For qt static is there a way to debug memory? 
My application crashes consistently when **quickly** loading and unloading a large chunk of data to a QTextEdit using:
to save - ```node.Output = edittree.OutputEditor.ToPlainText()```
to get - ```edittree.OutputEditor.SetText(node.Output)```

When I've seen/tested this type of behavior before I would get a crash because it seemed the application would allocate too much memory. But that is not the case here -- memory allocation is small increments. And it seems to depend on the speed I'm switching nodes - each node has a separate Output text. In this case (of crash) the length of the Output string is 175391 (characters). In datasets where node Output text is in the 5 digit range, the application is stable.

Thanks

**Comment by 5k3105** [comment]
Verified that when commenting out ```ToPlainText()``` call on output textedit box, application is stable again:
```go
func (edittree *EditTree) Set(previous *core.QModelIndex) {
	id := previous.Data(0x0100).ToLongLong(nil)

	node, ok := node_map[id]
	if ok {
		node.Name = previous.Data(0).ToString()
		node.Notes = edittree.NotesEditor.ToPlainText() 
		node.Input = edittree.InputEditor.ToPlainText() 
		// node.Output = edittree.OutputEditor.ToPlainText() 
	}
}
```

Seems the fix is:
```go
func (edittree *EditTree) Set(previous *core.QModelIndex) {
	id := previous.Data(0x0100).ToLongLong(nil)

	node, ok := node_map[id]
	if ok {
		node.Name = previous.Data(0).ToString()

		if edittree.NotesEditor.Document().IsModified() {
			node.Notes = edittree.NotesEditor.ToPlainText() 
		}
		if edittree.InputEditor.Document().IsModified() {
			node.Input = edittree.InputEditor.ToPlainText() 
		}
		if edittree.OutputEditor.Document().IsModified() {
			node.Output = edittree.OutputEditor.ToPlainText()
		}
	}
}
```

So I guess the time it takes for ```ToPlainText()``` call on a large text field then called again when moving to a new field before it has finished the first call is crashing the program?
Can this be fixed any other way?

Thanks

**Comment by 5k3105** [comment]
Even with that modification I get crash only on large text fields. I thought it was working but I had to make the addition of ```.SetModified(true)``` because edits to the text document through function calls do not set Modified, you must use ```.SetModified(true)```...

So this comes back to probably a memory issue where calling ```ToPlainText()``` of ```ToRawText()``` crash on ~6 digit length text strings.

**Comment by therecipe** [comment]
Hey

I will try to reproduce it tomorrow, but you could try to export these env variables here
`QT_DEBUG=true` `QT_DEBUG_CONSOLE=true` `QT_DEBUG_CPP=true`
if you want to have every qt function call printed to the console
you will then need to either run `qtminimal && qtmoc && go run/build` or `qtdeploy`

Directly debugging the memory would be possible with Valgrind, but its not working with go programs iirc. And the usual way to debug go programs (pprof) is not really great to use for cgo stuff.

Did you test if you can crash it with an QPlainTextEdit as well? It's a bit more performant iirc.
And could you maybe test if using SetPlainText makes a difference?

**Comment by 5k3105** [comment]
Excellent - thanks!
I get the same behavior using QPlainTextEdit. I also cannot reproduce the crash in debug mode - I will assume because debug has slowed the program down so much, it has a chance to run ```ToPlainText()``` fully before moving to the next call.

There is a way I can work around using the ```ToPlainText()``` call. Since the output field is the result of a database query, I can save the table string directly to the string map - only using ```SetPlainText()```. _This is what I've done and it works._

Other than that I'd need to develop some type of paging system for the result - either through code or modifying the sql.

**Comment by therecipe** [comment]
Okay, looked into this again and you might be right with 
>it has a chance to run ToPlainText() fully before moving to the next call.

It might be a problem, that queued slot calls (e.g. calls to `SetPlainText` from some other go routines) are not blocking and that even though they are almost immediately executed, it could probably cause problems calling them several times in short interval with that much data.

It for example did work for me without any problems, when I was calling `SetPlainText` and directly `ToPlainText` afterwards in a tight loop on the main thread. But once they were called from a go routine things started to act weird after some time.

So you are probably better of working around this, like you said.

About the paging, I'm not sure I fully understood.
But if you for example have a list/table/treeview and you don't want to trigger the onSelectionChanged function on every selection. Then you can use something like this to defer the execution of the function for a few milliseconds, as long as you quickly change the selections.

```diff
diff --git a/advanced/widgets/listview/main.go b/advanced/widgets/listview/main.go
index 152dadf..c1df104 100644
--- a/advanced/widgets/listview/main.go
+++ b/advanced/widgets/listview/main.go
@@ -3,6 +3,7 @@ package main
 import (
        "fmt"
        "os"
+       "time"
 
        "github.com/therecipe/qt/core"
        "github.com/therecipe/qt/widgets"
@@ -103,6 +104,25 @@ func main() {
        })
        widget.Layout().AddWidget(edit)
 
+       var timer *time.Timer
+       deferredUpdate := func(selected *core.QItemSelection) {
+               index := core.NewQPersistentModelIndex(selected.Indexes()[0])
+               if timer == nil {
+                       timer = time.AfterFunc(250*time.Millisecond, func() {
+                               timer = nil
+                               if index.IsValid() {
+                                       println("SELECTED", index.Data(0).ToString())
+                               }
+                       })
+               } else {
+                       timer.Reset(250 * time.Millisecond)
+               }
+       }
+
+       listview.ConnectSelectionChanged(func(selected *core.QItemSelection, deselected *core.QItemSelection) {
+               deferredUpdate(selected)
+       })
+
        window.Show()
 
        app.Exec()
``` 

I made the changes to [this](https://github.com/therecipe/examples/blob/master/advanced/widgets/listview/main.go) example, to test it.

**Comment by 5k3105** [comment]
> About the paging, I'm not sure I fully understood.
I was talking about paging in data from database (using limit and offset).

Thanks for the example and your time :)
