### ISSUE TITLE
docker qt:windows_32_shared is not correct

### ISSUE THREAD

**Issue by rocket049** [therecipe/qt#856]
I build my qt program with the docker qt:windows_32_shared, and it lost some dlls.

my build command on ubuntu 18.04.2 :
`qtdeploy -docker build windows_32_shared`

generate executable:  "tray-controller-qt.exe"

then i go into `deploy/windows`, then run:
`wine tray-controller-qt.exe`

### result errors:
```
0009:err:module:import_dll Library libcrypto-1_1.dll (which is needed by L"Z:\\home\\fuhz\\go\\src\\tray-controller-qt\\deploy\\windows\\Qt5Network.dll") not found
0009:err:module:import_dll Library libssl-1_1.dll (which is needed by L"Z:\\home\\fuhz\\go\\src\\tray-controller-qt\\deploy\\windows\\Qt5Network.dll") not found
0009:err:module:import_dll Library Qt5Network.dll (which is needed by L"Z:\\home\\fuhz\\go\\src\\tray-controller-qt\\deploy\\windows\\Qt5Qml.dll") not found
0009:err:module:import_dll Library Qt5Qml.dll (which is needed by L"Z:\\home\\fuhz\\go\\src\\tray-controller-qt\\deploy\\windows\\tray-controller-qt.exe") not found
0009:err:module:attach_dlls Importing dlls for L"Z:\\home\\fuhz\\go\\src\\tray-controller-qt\\deploy\\windows\\tray-controller-qt.exe" failed, status c0000135
```

It seems lost `libcrypto-1_1.dll` and `libssl-1_1.dll`

otherwise: windows_32_static is good.

**Comment by therecipe** [comment]
Hey

Thanks for the info, this should be fixed now with https://github.com/therecipe/qt/commit/120a741ef613ab95a16508cd2c4681ebd0545f49

**Comment by rocket049** [comment]
It is OK now.
