### ISSUE TITLE
make it easier to edit and deploy ?...

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#86]
in /internal/setup/test/ there is the code to install qtdeploy and qtmoc.

I am still getting used to this, but does it make sense for this to be runnable more easily than calling setup.sh ?

**Comment by therecipe** [comment]
Hey

Yes, the scripts bother me as well :)

I'm planning to get rid of the `setup.sh` and `setup.bat` and instead create a new application `qtsetup` in `qt/cmd/qtsetup`, which then will be installed into $GOPATH/bin with `go get`.

This application would then be used like `qtsetup XYZ` and should behave like the current setup.
And you will also be able to run `qtsetup check/generate/install/test XYZ` to run the stages separately.

Also I will move `qtdeploy` and `qtmoc` into the `qt/cmd/` folder as well.
And seperate some parts of `qtdeploy` into independent applications: `qtrcc` and `qtminimal`

`qtrcc` can then be used to create the `qrc*`files and `qtminimal` to create a minimal version of the binding (which then can be used to be build applications with the plain `go build/run -tags=minimal` command more easily). 

What do you think?

**Comment by joeblew99** [comment]
thanks for responding.

My comments, although some of the terms are QT specific and i am a QT newbie.

1. good old cmd based pattern is good. makes it easier for all to know where to fix stuff.

2. qtsetup with flags for each op type is great, so we have more control.

3. The changes to qtdeploy i cant comment about as i dont know what qtrcc and qtminimal really do. But the ability to us "go build ./..." etc is more golangy (make up word :)) so all good

---

The thing was that i needed to run setup.sh just because i took the latest pull from your repo, and it takes 20 minutes to run on my mac. This is why i raised this. It is a long time.
It might be that i did not have to do a full setup build, in order to try the new code changes. I think i tried and it complained so i decided to run a full setup.sh.

**Comment by joeblew99** [comment]
I am really interested in trying the new docker stuff you committed to try and build for windows, android and ios.
i think thats my next experiment to see what i can do with this...

**Comment by therecipe** [comment]
Yes, the setup takes really long.
I should probably add a flag to omit building/testing of the examples, which would save 10min.

**Comment by fcying** [comment]
@therecipe  I try use `go run -tags=minimal` for example dropsite, it make some error:

```go
qtmoc.exe
qtrcc.exe
qtminimal.exe
go run -tags=minimal dropsite.go
# command-line-arguments
.\dropsite.go:24: undefined: NewDropSiteWindow
.\dropsite.go:31: dropArea.ConnectChanged undefined (type *DropArea has no field or method ConnectChanged)
.\dropsite.go:125: undefined: NewDropArea
```

`go build -tags=minimal` work ok.

**Comment by therecipe** [comment]
@fcying 

You need to move the "moc" structs (`DropSiteWindow` and `DropArea`) into a sub-package.
So that all the moc* files with `qtmoc` are created in that sub-package.
This is necessary IIRC, because `go run` can't handle *.h, *.cpp, ... files in the main package.

(The same needs to be done with the rcc* files, if you got any of those)

Then you should be able to use `go run -tags=minimal ...`

**Comment by fcying** [comment]
@therecipe  it can work, but a little cumbersome.
in last version, I use `ctrl-c` after `qtdeploy` create qrc and moc files,  then i can use `go run ...`
