### ISSUE TITLE
qtsetup fails with missing QAbstractAnimation include

### ISSUE THREAD

**Issue by muesli** [therecipe/qt#860]
Using it just fine on Arch, but trying to run it on Ubuntu 19.04 I run into issues using qtsetup. This is using Ubuntu's Qt5 packages.

INFO[0000] running: 'qtsetup prep'                      
WARN[0000] failed to create qtrcc symlink in your PATH (/sbin/qtrcc); please use /home/muesli/go/bin/qtrcc instead 
WARN[0000] failed to create qtmoc symlink in your PATH (/sbin/qtmoc); please use /home/muesli/go/bin/qtmoc instead 
WARN[0000] failed to create qtminimal symlink in your PATH (/sbin/qtminimal); please use /home/muesli/go/bin/qtminimal instead 
WARN[0000] failed to create qtdeploy symlink in your PATH (/sbin/qtdeploy); please use /home/muesli/go/bin/qtdeploy instead 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.10.4'      
INFO[0000] GOROOT:                      '/usr/lib/go-1.10' 
INFO[0000] GOPATH:                      '/home/muesli/go' 
INFO[0000] GOBIN:                       '/home/muesli/go/bin' 
INFO[0000] GOMOD:                       ''              
INFO[0000] QT_HASH:                     'cf6956137ad2a2b502ae3cf8b4f8026bec87364d' 
INFO[0000] QT_API:                      ''              
INFO[0000] QT_VERSION:                  '5.12.2'        
INFO[0000] QT_DIR:                   *  '/home/muesli/Qt'          
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'ubuntu'        
INFO[0000] QT_PKG_CONFIG:            *  'true'          
INFO[0000] QT_DOC_DIR:                  '/usr/share/qt5/doc' 
INFO[0000] QT_MISC_DIR:                 '/usr/lib/x86_64-linux-gnu/qt5' 
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
WARN[0000] parser.LoadModule                             error=EOF module=RemoteObjects
WARN[0000] parser.LoadModule                             error=EOF module=AndroidExtras
WARN[0000] parser.LoadModule                             error=EOF module=Scxml
WARN[0000] parser.LoadModule                             error=EOF module=Gamepad
INFO[0008] generating full qt/core                      
INFO[0021] generating full qt/androidextras             
INFO[0021] generating full qt/gui                       
INFO[0039] generating full qt/network                   
INFO[0044] generating full qt/xml                       
INFO[0045] generating full qt/dbus                      
INFO[0046] generating full qt/nfc                       
INFO[0047] generating full qt/script                    
INFO[0048] generating full qt/sensors                   
INFO[0052] generating full qt/positioning               
INFO[0053] generating full qt/widgets                   
INFO[0092] generating full qt/sql                       
INFO[0094] generating full qt/qml                       
INFO[0096] generating full qt/websockets                
INFO[0097] generating full qt/xmlpatterns               
INFO[0097] generating full qt/bluetooth                 
INFO[0099] generating full qt/webchannel                
INFO[0100] generating full qt/svg                       
INFO[0101] generating full qt/multimedia                
INFO[0113] generating full qt/quick                     
INFO[0116] generating full qt/help                      
INFO[0120] generating full qt/location                  
INFO[0121] generating full qt/scripttools               
INFO[0122] generating full qt/uitools                   
INFO[0122] generating full qt/webengine                 
INFO[0124] generating full qt/testlib                   
INFO[0124] generating full qt/serialport                
INFO[0125] generating full qt/serialbus                 
INFO[0126] generating full qt/printsupport              
INFO[0129] generating full qt/designer                  
INFO[0132] generating full qt/scxml                     
INFO[0132] generating full qt/gamepad                   
INFO[0132] generating full qt/datavisualization    [GPLv3] 
INFO[0136] generating full qt/charts               [GPLv3] 
INFO[0144] generating full qt/virtualkeyboard      [GPLv3] 
INFO[0146] generating full qt/speech                    
INFO[0146] generating full qt/quickcontrols2            
INFO[0146] generating full qt/sailfish                  
INFO[0146] generating full qt/webview                   
INFO[0146] generating full qt/remoteobjects             
INFO[0146] running: 'qtsetup install linux' [docker=false] [vagrant=false] 
INFO[0146] installing full qt/core                      
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: QAbstractAnimation: No such file or directory
 #include <QAbstractAnimation>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

ERRO[0246] failed to install 'core'; aborting setup

**Comment by muesli** [comment]
Note, that the include does exist in the filesystem at:

`/usr/include/x86_64-linux-gnu/qt5/QtCore/QAbstractAnimation[.h]`

**Comment by therecipe** [comment]
Hey

Maybe try to run `qtsetup -debug generate` and check the log, but I guess you will probably need to either unset `QT_DIR` or install `qtbase5-dev`

I just tested it on 19.04 using this docker file:
```Dockerfile
FROM ubuntu:19.04 as base

ENV USER user
ENV HOME /home/$USER
ENV GOPATH $HOME/work

RUN apt-get -qq update && apt-get --no-install-recommends -qq -y install ca-certificates curl git
RUN GO=go1.12.4.linux-amd64.tar.gz && curl -sL --retry 10 --retry-delay 60 -O https://dl.google.com/go/$GO && tar -xzf $GO -C /usr/local
RUN /usr/local/go/bin/go get -tags=no_env github.com/therecipe/qt/cmd/...

FROM ubuntu:19.04
LABEL maintainer therecipe

ENV USER user
ENV HOME /home/$USER
ENV GOPATH $HOME/work
ENV PATH /usr/local/go/bin:$PATH
ENV QT_DOCKER true
ENV QT_PKG_CONFIG true

COPY --from=base /usr/local/go /usr/local/go
COPY --from=base $GOPATH/bin $GOPATH/bin
COPY --from=base $GOPATH/src/github.com/therecipe/qt $GOPATH/src/github.com/therecipe/qt

RUN apt-get -qq update && apt-get --no-install-recommends -qq -y install build-essential libglib2.0-dev libglu1-mesa-dev libpulse-dev && apt-get -qq clean
RUN apt-get -qq update && apt-get --no-install-recommends -qq -y install libqt*5-dev qt*5-dev qt*5-doc-html && apt-get -qq clean

RUN $GOPATH/bin/qtsetup prep
RUN $GOPATH/bin/qtsetup check
RUN $GOPATH/bin/qtsetup generate
RUN cd $GOPATH/src/github.com/therecipe/qt/internal/examples/widgets/line_edits && $GOPATH/bin/qtdeploy build linux && rm -rf ./deploy
```
(based https://github.com/therecipe/qt/blob/master/internal/docker/linux/Dockerfile.ubuntu_18_04)
and it seems to work

**Comment by muesli** [comment]
Ok, it looks like the second apt install command in the Dockerfile installed a bunch of missing packages. Need to compare that with the wiki entry once more.

The demo apps also build and run fine during the qtsetup stage (besides the widget error you probably referred to yourself:

```
widgets.cpp:323:10: fatal error: metrics: No such file or directory
```

However when I try to launch my binary now, I get the following errors:

```
QQMlApplicationEngine failed to load component
module "QtQuick.Controls.Material" is not installed
module "QtQuick" is not installed
module "QtQuick.Layouts" is not installed
...
```

**Comment by muesli** [comment]
Ok, that was just missing two packages: `qml-module-qtquick-controls` and `qml-module-qtquick-controls2`. They are probably not build time dependencies though. Closing as such.

**Comment by therecipe** [comment]
The `widgets.cpp:323:10: fatal error: metrics: No such file or directory` issue should be fixed now with https://github.com/therecipe/qt/commit/89b7941f483a7a450aa72057326d3401aca58cfe

And about the missing packages, yeah these are runtime dependencies, but I will update the wiki to include them as well. Thanks for the heads up :)
