### ISSUE TITLE
WebView.Page().RunJavaScript4 can't call react component function

### ISSUE THREAD

**Issue by sunwenli** [therecipe/qt#861]
Hi , dear dev.
  I got a problem 
  The `RunJavaScript4` api can't call function , when i click a button bind a js function in a page render by react . The console log: function `goOnPkg` is not defined 

![image](https://user-images.githubusercontent.com/14137823/57673037-25306a00-764d-11e9-82f0-ca83891305e1.png)

code in go file is :
![image](https://user-images.githubusercontent.com/14137823/57673115-6fb1e680-764d-11e9-9f11-0aa38a2089d5.png)

code in react component is ：
![image](https://user-images.githubusercontent.com/14137823/57673414-69703a00-764e-11e9-8ac1-111079f62e37.png)
may help me ,thx

**Comment by therecipe** [comment]
Hey

What Qt version do you use?
Also did you test `RunJavaScript` and `RunJavaScript2` as well?

And do other function calls work?
Does something like `RunJavaScript4("alert(\"hello\")")` work for example?

**Comment by sunwenli** [comment]
OK，I will try it.

**Comment by sunwenli** [comment]
my Qt version is 5.10

**Comment by sunwenli** [comment]
@therecipe ,Hi , I tried those method that you provided .  But it seems that `RunJavaScript` , `RunJavaScript2 ` and `RunJavaScript4`  only access  functions that wrappered by `<script type=“text/javascript”> </script>` .
```
  <script type="text/javascript">
    function a (){} // can call this func
  </script>
```

since react js function can only  support wrappered by `<script type=“text/babel”>` or `<script type=“text/jsx”>`.

```
<script type="text/babel">
    function b (){} // can't call this func
  </script>
  <script type="text/jsx">
    c (){} // can't call this func
  </script>
```

I tried so many ways , i also tried to modify [config file](https://umijs.org/guide/html-template.html#specify-templates-for-specific-pages) (generate by [umi](https://umijs.org/guide/) )  of [Ant Design (react framework)](https://ant.design/docs/react/introduce) to change content of index.html, it didn’t  work . And i have no idea to solve this problem now.

**Comment by sunwenli** [comment]
aha, i solved this problem .

1. in js file, we should export React Class instance to window.

```
import xxx;

//...

window.updateValue = function(url) {
    alert("call ok !");
    // if(window.callback != undefined) {
    //    window.callback.updateValue(url);
    // }
};
 
window.setCallback = function(callback) {
    window.callback = callback;
}

//...

export default class MyFeedback extends React.Component {

   //...
   // key step
   //  in react life cycle `componentWillMount` set `this` :
   componentWillMount() {
         window.setCallback(this);
   }

  //...

}

```

2. in go file, we call function like this :

```
ap.WebView.Page().RunJavaScript4("window.updateValue('hello')")
```

after run project .  i see  alert `call ok!` . 👍

**Comment by sunwenli** [comment]
[Refer to the link : https://blog.csdn.net/ZHOUYONGXYZ/article/details/82760929](https://blog.csdn.net/ZHOUYONGXYZ/article/details/82760929)

**Comment by therecipe** [comment]
Perfect, thanks for the update :)
