### ISSUE TITLE
Can you add libfcitxplatforminputcontextplugin into the linux_static docker image?

### ISSUE THREAD

**Issue by rocket049** [therecipe/qt#863]
Shared mode for linux is to big.
I try the linux_static docker.
The program generated is so little, about 1/4 of shared mode, but the program can't use fcitx inputmethod.
My project: 
https://github.com/rocket049/secret-diary

**Comment by rocket049** [comment]
@therecipe the source of libfcitxplatforminputcontextplugin:
https://github.com/fcitx/fcitx-qt5

**Comment by therecipe** [comment]
Hey

Thanks, I will add it to the `linux_static` image.

**Comment by rocket049** [comment]
@therecipe Your work is very execllent!

**Comment by rocket049** [comment]
@therecipe 
The program seems can't compile.
always report : Parse error "IID".
You'd better contact the author. http://code.google.com/p/fcitx

**Comment by therecipe** [comment]
>always report : Parse error "IID".

I looked into this real quick today, and it seems to somewhat work if you put `QPlatformInputContextFactoryInterface_iid` into quotes, like this:
`Q_PLUGIN_METADATA(IID "QPlatformInputContextFactoryInterface_iid" FILE`

But I did run into another issue, because it tries to build a shared `*.so` lib instead of a static `*.a` lib for some reason. I will look into this again tomorrow.

Also btw, the `linux`, `linux_59` and `linux_56` images should deploy the `libfcitxplatforminputcontextplugin.so` plugin now.

**Comment by rocket049** [comment]
@therecipe  Thanks.

**Comment by rocket049** [comment]
> > always report : Parse error "IID".
> 
> I looked into this real quick today, and it seems to somewhat work if you put `QPlatformInputContextFactoryInterface_iid` into quotes, like this:
> `Q_PLUGIN_METADATA(IID "QPlatformInputContextFactoryInterface_iid" FILE`
> 

I found your method is wrong, it compiled successful, but won't work.
The right way is  insert  `QFcitxPlatformInputContextPlugin() {};` before that line. like follow:

```
class QFcitxPlatformInputContextPlugin : public QPlatformInputContextPlugin {
    Q_OBJECT
public:
    QFcitxPlatformInputContextPlugin() {};
    Q_PLUGIN_METADATA(IID QPlatformInputContextFactoryInterface_iid FILE "fcitx.json")
    QStringList keys() const;
    QFcitxPlatformInputContext *create(const QString &system,
                                       const QStringList &paramList);
};
```

**Comment by rocket049** [comment]
@therecipe  Teach me how to use Q_IMPORT_PLUGIN in static mode.

**Comment by therecipe** [comment]
Ah, thanks you are right :)

If you did compile the fcitx plugin, then all you need to do is to add `Q_IMPORT_PLUGIN(QFcitxPlatformInputContextPlugin)` to one the `github.com/therecipe/qt/*/*_plugin_import.cpp` files and to also add
`#cgo LDFLAGS: path/to/libfcitxplatforminputcontextplugin.a` to the `*cgo_*` file(s) in the same dir.

But I added the fcitx plugin to the `linux_static` image now as well, so it should work out of the box with https://github.com/therecipe/qt/commit/8161b74c70d08536471962c2cbd2b3b24005b222#diff-76b12f273547795e182aa407544c7ecd now.

Please let me know if the image works for you.

**Comment by rocket049** [comment]
@therecipe I will try later, thanks.

**Comment by rocket049** [comment]
@therecipe I tried it. your new image linux_static work well with fcitx now!

**Comment by rocket049** [comment]
@therecipe I found you also didn't load ibusinputcontextplugin, I add it myself, otherwise, I suggest add it default.

**Comment by therecipe** [comment]
sorry for the delay, and thanks for testing the linux_static image
I added the ibusinputcontextplugin with https://github.com/therecipe/qt/commit/543fb14d45ea3efd34b2962d71a64a9137c06949 now

**Comment by rocket049** [comment]
@therecipe It's almost perfect now!
