### ISSUE TITLE
How do I pass a void pointer to core.QModelIndex.CreateIndex()?

### ISSUE THREAD

**Issue by MakotoE** [therecipe/qt#864]
I am having trouble with subclassing `QAbstractItemModel`. I want to implement [`QAbstractItemModel.index()`](https://doc.qt.io/qt-5/qabstractitemmodel.html#index), and to do this, I must call [`QAbstractItemModel.createIndex()`](https://doc.qt.io/qt-5/qabstractitemmodel.html#createIndex), which takes a void pointer for a custom tree type. I am currently getting a runtime error with my code. Sorry this is a long example, but I couldn't write a shorter reproducible code which printed the same error.

``` go
import (
	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
	"unsafe"
)

func main() {
	app := widgets.NewQApplication(0, nil)
	window := widgets.NewQMainWindow(nil, core.Qt__Window)
	window.SetFixedSize2(500, 500)

	treeModel := NewTreeModel(window)
	treeModel.Root = &TreeItem{Data: "Root item"}
	treeModel.Root.Children = &TreeItem{Data: "Child item", Parent: treeModel.Root}

	treeView := widgets.NewQTreeView(window)
	treeView.SetModel(treeModel)

	window.SetCentralWidget(treeView)
	window.Show()
	app.Exec()
}

type TreeModel struct {
	core.QAbstractItemModel
	_ func() `constructor:"init"`

	Root *TreeItem
}

func (this *TreeModel) init() {
	this.ConnectRowCount(func(parent *core.QModelIndex) int {
		if !parent.IsValid() {
			return 1
		}

		if (*TreeItem)(parent.InternalPointer()).Children == nil {
			return 0
		}
		return 1
	})

	this.ConnectColumnCount(func(_ *core.QModelIndex) int {
		return 1
	})

	this.ConnectIndex(func(row int, column int, parent *core.QModelIndex) *core.QModelIndex {
		if !parent.IsValid() {
			// This line below is where I am getting the cgo runtime error
			return this.CreateIndex(row, column, unsafe.Pointer(this.Root.Children))
		}

		treeItem := (*TreeItem)(parent.InternalPointer())
		return this.CreateIndex(row, column, unsafe.Pointer(treeItem.Children))
	})

	this.ConnectParent(func(index *core.QModelIndex) *core.QModelIndex {
		if !index.IsValid() {
			return core.NewQModelIndex()
		}

		treeItem := (*TreeItem)(index.InternalPointer())
		if treeItem.Parent == nil {
			return core.NewQModelIndex()
		}

		return this.CreateIndex(treeItem.Parent.Row, 0, unsafe.Pointer(treeItem.Parent))
	})

	this.ConnectData(func(index *core.QModelIndex, role int) *core.QVariant {
		if !index.IsValid() {
			return core.NewQVariant()
		}

		treeItem := (*TreeItem)(index.InternalPointer())
		return core.NewQVariant14(treeItem.Data)
	})
}

type TreeItem struct {
	Children *TreeItem // (I will change this to a slice later)
	Parent *TreeItem
	Row int
	Data string
}
```
The error:

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
github.com/therecipe/qt/core.(*QAbstractItemModel).CreateIndex.func1(0xc00000e060, 0x0, 0x0, 0xc00008e300, 0x0)
	/home/makoto/go/src/github.com/therecipe/qt/core/core.go:3349 +0xbe
github.com/therecipe/qt/core.(*QAbstractItemModel).CreateIndex(0xc00000e060, 0x0, 0x0, 0xc00008e300, 0x0)
	/home/makoto/go/src/github.com/therecipe/qt/core/core.go:3349 +0x78
main.(*TreeModel).init.func3(0x0, 0x0, 0xc0000106a0, 0x0)
	/home/makoto/go/src/go-test/main.go:73 +0x137
main.callbackTreeModel90ede3_Index(0x29e22b0, 0x0, 0x7ffcc375c840, 0x0)
	/home/makoto/go/src/go-test/moc.go:1191 +0xd5
...
```

I am sort of following [this tutorial for a C++ implementation](https://doc.qt.io/qt-5/qtwidgets-itemviews-simpletreemodel-example.html#treemodel-class-implementation).

One way to make this run without errors is by changing the marked line to:

``` go
return this.CreateIndex(row, column, unsafe.Pointer(&TreeItem{}))
```

This isn't the correct implementation, but I can kind of understand the error from this - there is a go pointer inside the passed struct, which cgo doesn't like. I don't understand the reasoning for this. I have tried the overloaded `CreateIndex2`, and I tried copying the referenced `TreeItem` to a new struct then taking the pointer of that.

Is there a way to make this work, so that I can pass the pointer `TreeItem` like in the C++ implementation? Thanks!

**Comment by therecipe** [comment]
Hey

Yeah, this due the cgo limitation that forbids you to store go pointers in c-land for longer than a single function call. Take a look here https://golang.org/cmd/cgo/#hdr-Passing_pointers for more info.

But, you can work around this by creating an TreeItem struct that subclasses QObject and than take the c pointer and pass it to the `CreateIndex` function. You can then later use `NewTreeItemFromPointer` to get access to your original Go object from the c pointer.

Take a look here for an working example: https://github.com/therecipe/examples/blob/master/advanced/widgets/treeview/main.go

Btw, you can now also use `NewQVariant1` to create an QVariant from all kind of types.

**Comment by MakotoE** [comment]
Awesome. Thank you!
