### ISSUE TITLE
crash build window in macos

### ISSUE THREAD

**Issue by zsdevX** [therecipe/qt#870]
qt 5.12.0
go 1.12.5
qtdeploy latest

${GOPATH}/bin/qtdeploy -docker build windows_32_static

```
DEBU[0000] running Deploy                                comply=false docker=true fast=false ldFlags= mode=build path=/Volumes/dev/gosrc/src/github.com/xxx quickcompiler=false target=windows_32_static useuic=true
DEBU[0000] Execute                                       _func=RunCmd cmd="go env GOMOD" dir=/Volumes/dev/gosrc/src/github.com/xxx env= name=GOMOD
DEBU[0000] Execute                                       _func=RunCmd cmd="docker run --rm -v /Volumes/dev/gosrc:/media/sf_GOPATH0 -e GOPATH=/home/user/work:/media/sf_GOPATH0 -i therecipe/qt:windows_32_static qtdeploy -debug -ldflags= -tags= build windows /media/sf_GOPATH0/src/github.com/xxx" dir= env= name="deploy binary for windows_32_static on darwin with docker"

```

> time="2019-05-28T08:40:33Z" level=debug msg="analyse for minimal" path=/media/sf_GOPATH0/src/github.com/StackExchange/wmi/wmi.go
> time="2019-05-28T08:40:33Z" level=debug msg="analyse for minimal" path=/media/sf_GOPATH0/src/github.com/StackExchange/wmi/swbemservices_test.go
> time="2019-05-28T08:40:33Z" level=debug msg="found 109 files to analyze"
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a1bb7]
> 
> goroutine 1 [running]:
> github.com/therecipe/qt/internal/cmd/minimal.exportClass(0x0, 0xc00038a000, 0x6d, 0x80)
>         /home/user/work/src/github.com/therecipe/qt/internal/cmd/minimal/minimal.go:306 +0x37
> github.com/therecipe/qt/internal/cmd/minimal.Minimal(0x7fff23717e99, 0x29, 0x7fff23717e91, 0x7, 0x7fff23717e85, 0x0)
>         /home/user/work/src/github.com/therecipe/qt/internal/cmd/minimal/minimal.go:253 +0xad6
> github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x7fff23717e8b, 0x5, 0x7fff23717e91, 0x7, 0x7fff23717e99, 0x29, 0xc000074800, 0x7fff23717e7b, 0x0, 0x7fff23717e85, ...)
>         /home/user/work/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:93 +0x198f
> main.main()
>         /home/user/work/src/github.com/therecipe/qt/cmd/qtdeploy/main.go:138 +0x7a4
>

**Comment by therecipe** [comment]
Hey

I looked into this, and it should be fixed now with https://github.com/therecipe/qt/commit/543fb14d45ea3efd34b2962d71a64a9137c06949
