### ISSUE TITLE
How to use signal\slot?

### ISSUE THREAD

**Issue by rhaidiz** [therecipe/qt#872]
I have a question about how signal\slot are supported by this framework (awesome work btw).
I'm relatively new to Qt signal\slot so I might have gotten this wrong, anyway here it is:

A signal is basically used to trigger a slot and a slot is a function that can be either called directly or triggered by a signal, and a signal has to be connected to a slot in order to trigger it.
While checking for examples on how to use signal\slot with this library, it seemed to me that signal\slot are implemented slightly differently. It seems that the following line is actually creating a signal (and not a slot) called "inSlot".

    type hStruct struct {
       core.QObject
        _ func() `slot:"inSlot"`
    }

In fact, I would then write something like this:

	h := NewHStruct(nil)
	h.ConnectInSlot(func(){// do something here})

Which I read as "connect the signal 'inSlot' to the slot func(){// do something here}".
Am I correct in this? Or did I get it totally wrong?

**Comment by therecipe** [comment]
Hey

No, you are right the binding somewhat blurs the lines between signals/slots so that they are practically indistinguishable from one another. In c++ "connecting" a slot is basically overriding a virtual function, while connecting a signal is like you said connecting a signal to some slot.

But this is all abstracted away for you when you make use of `ConnectXYZ`, so you can just use `ConnectXYZ` regardless if you want to override a slot or connect a signal to some slot.

The differentiation between signals/slots is now only important if you work with qml and you want to listen on a signal in qml (to receive go function calls) or if you want to call a go function (slot) from qml.
Maybe take a look [here](https://github.com/therecipe/qt/blob/master/internal/examples/quick/bridge2/bridge2.go#L18-L19) for some qml example which shows you how to communicate with qml

And another thing to remember is that slots can have return values, while signals can't.
But that's about it, you simply "connect" the signals/slots and then invoke/emit them by using the uppercase version of you function (`InSlot()` in this case)

**Comment by rhaidiz** [comment]
Awesome, thank you very much for your answer. Indeed I had checked the QML example where I could see the difference between signals\slots in a qml-to-go scenario which lead me to ask the question for go-to-go.

Finally, I would like to ask about best practices on using the signals\slots approach with the framework. Let me borrow two sentences from the Qt documentation [here](https://doc.qt.io/qt-5/signalsandslots.html):

1. "[...] we recommend to only emit them [signals] from the class that defines the signal and its subclasses."
2. "[...] a slot does not know if it has any signals connected to it."

So the idea should be that a slot does not know if there's a signal attached to it, so one shouldn't connect a signal to a slot in the same class that defines the slot, and a signal should be sent from the class that defines it.

Following the best practices above (which are of course are not mandatory), I would implement signals\slots in a go-to-go scenario like shown in the following snippet, where `hStruct` and `hStruct2` might be in two different packages for some reason and main is glueing everything together.

What do you think? Does it make sense?

```go
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/core"
)

type hStruct struct {
	core.QObject
	_ func() `signal:"mySignal"`
}

type hStruct2 struct {
        // This isn't strictly necessary, but is convenient to have NewHStruct2
	core.QObject
}

func(h *hStruct2) mySlot(){
	fmt.Println("current thread (mySlot):", core.QThread_CurrentThread().Pointer())
}

func main() {
	core.NewQCoreApplication(len(os.Args), os.Args)

	fmt.Println("current thread (main):", core.QThread_CurrentThread().Pointer())

	h := NewHStruct(nil)
	h2 := NewHStruct2(nil)

	h.ConnectMySignal(h2.mySlot)

	go h.MySignal()

	core.QCoreApplication_Exec()
}
```

**Comment by therecipe** [comment]
No problem :)

Yeah, you can do it that way but there is really no restriction about how to use this, so what I usually do is something like this:

```go
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/core"
)

type hStruct struct {
	core.QObject

	_ func() `constructor:"init"`

	_ func() `signal:"mySignal"`
}

func (h *hStruct) init() {
	h.ConnectMySignal(h.mySignal)
}

func (h *hStruct) mySignal() {
	fmt.Println("current thread (mySignal):", core.QThread_CurrentThread().Pointer())
}

func main() {
	core.NewQCoreApplication(len(os.Args), os.Args)

	fmt.Println("current thread (main):", core.QThread_CurrentThread().Pointer())

	h := NewHStruct(nil)

	go h.MySignal()

	core.QCoreApplication_Exec()
}
```

or  use the `,auto` tag to automatically connect the signal/slot

```go
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/core"
)

type hStruct struct {
	core.QObject

	_ func() `signal:"mySignal,auto"`
}

func (h *hStruct) mySignal() {
	fmt.Println("current thread (mySignal):", core.QThread_CurrentThread().Pointer())
}

func main() {
	core.NewQCoreApplication(len(os.Args), os.Args)

	fmt.Println("current thread (main):", core.QThread_CurrentThread().Pointer())

	h := NewHStruct(nil)

	go h.MySignal()

	core.QCoreApplication_Exec()
}
```

But again, your example is perfectly fine as well and there are scenarios where you want to connect a signal from one object to a slot from another object, but in most cases you can also just connect the signal/slot to itself and then just see it as a function which can be safely called from another thread than the main thread.

**Comment by rhaidiz** [comment]
Awesome, thank you very much for your time :-) I can now close this.

**Comment by danielhongwoo** [comment]
I've been trying to use signal/slot to disable widgets during some background process.
I tried the code snippet above, but it occurs run time error. Any idea or comment will be helpful. 

* main.go
``` go
package main

import (
	"fmt"
	"github.com/therecipe/qt/core"
	"os"
)

type hStruct struct {
	core.QObject
	_ func() `signal:"mySignal,auto"`
}

func (h *hStruct) mySignal() {
	fmt.Println("current thread (mySignal):", core.QThread_CurrentThread().Pointer())
}

func main() {
	core.NewQCoreApplication(len(os.Args), os.Args)
	fmt.Println("current thread (main):", core.QThread_CurrentThread().Pointer())
	h := NewHStruct(nil)
	go h.MySignal()
	core.QCoreApplication_Exec()
}
```

* go.mod
```
module therecipe-qt-sample

go 1.13

require (
	github.com/therecipe/qt v0.0.0-20200904063919-c0c124a5770d
	github.com/therecipe/qt/internal/binding/files/docs/5.13.0 v0.0.0-20200904063919-c0c124a5770d // indirect
)
```

``` go
$ go run therecipe-qt-sample
looking for qtbox in: /work/therecipe-qt-sample/qtbox
final qtbox location: /work/therecipe-qt-sample/qtbox
current thread (main): 0x9c595f0
panic: reflect: New(nil)

goroutine 1 [running, locked to thread]:
reflect.New(0x0, 0x0, 0x0, 0x0, 0x0)
	reflect/value.go:2351 +0xc1
github.com/therecipe/qt/interop.Z_wrapperFunction(0xc000320350, 0xc00028d9a8)
	github.com/therecipe/qt/interop/interop.go:165 +0x1189
github.com/therecipe/qt/interop._syncCallIntoLocal.func3()
	github.com/therecipe/qt/interop/interop_api.go:64 +0x3c
github.com/therecipe/qt/interop.(*mainThreadHelper).runOnMainThread(...)
	github.com/therecipe/qt/interop/interop_api.go:36
github.com/therecipe/qt/interop.callbackmainThreadHelperc43c44_RunOnMainThread(0x9c595d0, 0x165db9de507baab7)
	github.com/therecipe/qt/interop/moc.go:106 +0x96
github.com/therecipe/qt/interop._cgoexpwrap_7bfbe95d990e_callbackmainThreadHelperc43c44_RunOnMainThread(0x9c595d0, 0x165db9de507baab7)
	_cgo_gotypes.go:660 +0x35
github.com/therecipe/qt/interop._Cfunc_mainThreadHelperc43c44_EventDefault(0x9c595d0, 0x7f39240011c0, 0x0)
	_cgo_gotypes.go:339 +0x4a
github.com/therecipe/qt/interop.(*mainThreadHelper).EventDefault.func1(0xc0000a0bb0, 0x4298060, 0xc000011940, 0xc000011940)
	github.com/therecipe/qt/interop/moc.go:478 +0xb6
github.com/therecipe/qt/interop.(*mainThreadHelper).EventDefault(0xc0000a0bb0, 0x4298060, 0xc000011940, 0x5)
	github.com/therecipe/qt/interop/moc.go:478 +0x4d
github.com/therecipe/qt/interop.callbackmainThreadHelperc43c44_Event(0x9c595d0, 0x7f39240011c0, 0x3e71c88)
	github.com/therecipe/qt/interop/moc.go:473 +0x11e
github.com/therecipe/qt/interop._cgoexpwrap_7bfbe95d990e_callbackmainThreadHelperc43c44_Event(0x9c595d0, 0x7f39240011c0, 0x1)
	_cgo_gotypes.go:764 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0x0)
	_cgo_gotypes.go:9044 +0x49
github.com/therecipe/qt/widgets.QApplication_Exec(...)
	github.com/therecipe/qt/widgets/widgets.go:9694
main.main()
	github.com/therecipe/box/full/full_box.go:25 +0x69
httpRequest error: ["",31669904,"","ConnectDestroyed","___REMOTE_CALLBACK___"] -> Post http://127.0.0.1:8000/syncCallIntoLocal: EOF
```

**Comment by hiteshhedwig** [comment]
Hi, @danielhongwoo. I am facing the same issue. Did you figure out the way to solve it?

**Comment by hiteshhedwig** [comment]
Anyone stumbles upon the same thing, i was able to test by just using `qtdeploy`. It compiled without error. No idea why didn't work with simple `go run ...`
