### ISSUE TITLE
Webengine  Cannot display

### ISSUE THREAD

**Issue by wang5561207** [therecipe/qt#876]
`package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/webengine"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	window := widgets.NewQMainWindow(nil, 0)
	window.SetMinimumSize2(500, 500)
	view := webengine.NewQWebEngineView(nil)
	page := webengine.NewQWebEnginePage(nil)
	page.ConnectCertificateError(func(certificateError *webengine.QWebEngineCertificateError) bool {
		println(certificateError.Error(), certificateError.ErrorDescription(), certificateError.IsOverridable(), certificateError.Url().ToString(0))
		return true
	})
	page.SetUrl(core.NewQUrl3("https://www.baidu.com", 0))
	view.SetPage(page)

	window.SetCentralWidget(view)
	window.Show()

	widgets.QApplication_Exec()
}`

Qt WebEngine ICU data not found at /home/wang/go/src/hello/deploy/linux/resources. Trying parent directory...
Installed Qt WebEngine locales directory not found at location /home/wang/go/src/hello/deploy/linux/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine resources not found at /home/wang/go/src/hello/deploy/linux/resources. Trying parent directory...
/home/wang/go/src/hello/deploy/linux/QtWebEngineProcess: error while loading shared libraries: libQt5WebEngineCore.so.5: cannot open shared object file: No such file or directory
[22511:22511:0604/011126.048901:FATAL:zygote_host_impl_linux.cc(187)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid). 
#0 0x7fc3c9c0f25f <unknown>
#1 0x7fc3c9b877ec <unknown>
#2 0x7fc3cacd546a <unknown>
#3 0x7fc3c9b416be <unknown>
#4 0x7fc3cacd44bd <unknown>
#5 0x7fc3cacd6c21 <unknown>
#6 0x7fc3c9b42244 <unknown>
#7 0x7fc3c815208e <unknown>
#8 0x7fc3c815344c <unknown>
#9 0x7fc3ced93d4e <unknown>
#10 0x7fc3ced94a44 QWebEnginePage::QWebEnginePage()
#11 0x0000004ca5f8 QWebEnginePage_NewQWebEnginePage
#12 0x0000004c9627 _cgo_05e92bbf946c_Cfunc_QWebEnginePage_NewQWebEnginePage
#13 0x000000486860 <unknown>

Received signal 6
#0 0x7fc3c9c0f25f <unknown>
#1 0x7fc3c9c0f65b <unknown>
#2 0x7fc3c9c0fcde <unknown>
#3 0x7fc3cf2280c0 <unknown>
#4 0x7fc3c54e6fff gsignal
#5 0x7fc3c54e842a abort
#6 0x7fc3c9c0f225 <unknown>
#7 0x7fc3c9b8793f <unknown>
#8 0x7fc3cacd546a <unknown>
#9 0x7fc3c9b416be <unknown>
#10 0x7fc3cacd44bd <unknown>
#11 0x7fc3cacd6c21 <unknown>
#12 0x7fc3c9b42244 <unknown>
#13 0x7fc3c815208e <unknown>
#14 0x7fc3c815344c <unknown>
#15 0x7fc3ced93d4e <unknown>
#16 0x7fc3ced94a44 QWebEnginePage::QWebEnginePage()
#17 0x0000004ca5f8 QWebEnginePage_NewQWebEnginePage
#18 0x0000004c9627 _cgo_05e92bbf946c_Cfunc_QWebEnginePage_NewQWebEnginePage
#19 0x000000486860 <unknown>
  r8: 0000000000000000  r9: 00007ffe7fffbb00 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fc3c60eefa0 r13: 00007ffe7fffbf80 r14: 00000000000000ac r15: 00007ffe7fffbd80
  di: 0000000000000002  si: 00007ffe7fffbb00  bp: 00007ffe7fffbd40  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fc3c54e6fff  sp: 00007ffe7fffbb78
  ip: 00007fc3c54e6fff efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by therecipe** [comment]
Hey

This should be fixed now with https://github.com/therecipe/qt/commit/0c188103d806ae75ce42dd90bec90dd16d85b8e7
