### ISSUE TITLE
Android Virtual keyboard causes black screen

### ISSUE THREAD

**Issue by YUSHEN2015** [therecipe/qt#878]
`package main

import (
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(0, nil)

	window := widgets.NewQMainWindow(nil, 0)
	window.SetMinimumSize2(250, 200)

	widget := widgets.NewQWidget(nil, 0)
	widget.SetLayout(widgets.NewQVBoxLayout())
	window.SetCentralWidget(widget)

	input := widgets.NewQLineEdit(nil)
	input.SetPlaceholderText("Write something ...")
	widget.Layout().AddWidget(input)

	window.Show()

	widgets.QApplication_Exec()
}`

1. build code as above for android (qtdeploy -docker build android)
2. install the apk on android mobile
3. launch the app and click edit box
4. lock the mobile screen when the virtual keyboard displays
5. unlock the mobile screen
6. the app displays a black screen

i test the code as above with c++, this issue cannot be reproduced.
and i run the example code of QLineEdit in qtcreator, this issue cannot be reproduced.

**Comment by therecipe** [comment]
Hey

Thanks for the report, this seems to have been a Qt issue.
I bumped the Qt version of the android docker image to 5.12.3 with https://github.com/therecipe/qt/commit/601259d3f181104f59c0c6f8999e0605ecdbe2e7 now, which should solve this issue.

**Comment by YUSHEN2015** [comment]
It is OK now, thanks.
