### ISSUE TITLE
too many errors with qtsetup test 

### ISSUE THREAD

**Issue by YUSHEN2015** [therecipe/qt#879]

**Comment by YUSHEN2015** [comment]
# github.com/therecipe/qt/widgets
widgets-minimal.cpp:346:7: warning: 'MyQAbstractItemView::edit' hides overloaded virtual function [-Woverloaded-virtual]
/Users/youchain-y/Qt/5.12.0/ios/include/QtWidgets/qabstractitemview.h:295:18: note: hidden overloaded virtual function 'QAbstractItemView::edit' declared here: different number of parameters (3 vs 1)
widgets-minimal.cpp:7991:7: warning: 'MyQListView::edit' hides overloaded virtual function [-Woverloaded-virtual]
/Users/youchain-y/Qt/5.12.0/ios/include/QtWidgets/qabstractitemview.h:295:18: note: hidden overloaded virtual function 'QAbstractItemView::edit' declared here: different number of parameters (3 vs 1)
widgets-minimal.cpp:8323:7: warning: 'MyQListWidget::edit' hides overloaded virtual function [-Woverloaded-virtual]
/Users/youchain-y/Qt/5.12.0/ios/include/QtWidgets/qabstractitemview.h:295:18: note: hidden overloaded virtual function 'QAbstractItemView::edit' declared here: different number of parameters (3 vs 1)

**Comment by ne-ray** [comment]
Hi. How you installed/updated package?
Did you use [this Instruction](https://github.com/therecipe/qt#installation)?

**Comment by YUSHEN2015** [comment]
Yes, but this error occurs after I execute the command (qtsetup full ios && qtsetup full ios-simulator)

**Comment by YUSHEN2015** [comment]
I updated my go version to 1.12.5.

**Comment by YUSHEN2015** [comment]
It works well after I run the command qtsetup update
