### ISSUE TITLE
Can't run even example exe

### ISSUE THREAD

**Issue by marinat** [therecipe/qt#880]
Qtsetup succeeds. I see launched exe examples like calc, wallet, etc.
But when I try to run wallet.exe manually from C:\Users\1\go\src\github.com\therecipe\qt\internal\examples\showcases\wallet\deploy\windows
i get "System not detected libgcc_s_seh1.dll" Why?
I found libgcc_s_seh_64-1.dll in this example folder, why it don't depends on it?

**Comment by ZoneTong** [comment]
add qt libraries (qt5widgets.dll Qt5Gui.dll ...) path to your PATH like me:   "D:\gopath\src\github.com\therecipe\env_windows_amd64_512\5.12.0\mingw73_64\bin"

**Comment by therecipe** [comment]
Hey

I will look into this, do you use the msys2 or the official Qt version?
Also does renaming `libgcc_s_seh_64-1.dll` to `libgcc_s_seh-1.dll` make it work?

**Comment by marinat** [comment]
I switched to mac and all works fine :)
