### ISSUE TITLE
How to add ios framwork

### ISSUE THREAD

**Issue by YUSHEN2015** [therecipe/qt#881]
I had a problem when I run the command  `qtdeploy build ios`, as below
youchain-ydeMBP:agent-client youchain-y$ qtdeploy build ios
ERRO[0048] failed to run command                         _func=RunCmd cmd="go build -p 4 -v -ldflags=all=\"-w\" -o /Users/youchain-y/go/src/agent-client/deploy/ios/libgo.a -tags=\"ios\" \"minimal\" -pkgdir /Users/youchain-y/go/pkg/ios_darwin_arm64 -buildmode c-archive" dir=/Users/youchain-y/go/src/agent-client env="CGO_LDFLAGS_ALLOW=.* SHLVL=1 ANDROID_NDK=/Users/youchain-y/Documents/android-ndk-r10e GOOS=darwin GOARCH=arm64 TERM=xterm-256color _INTELLIJ_FORCE_SET_GOPATH=/Users/youchain-y/go _=/usr/local/bin/qtdeploy GOPATH=/Users/youchain-y/go GOROOT=/usr/local/Cellar/go/1.12.6/libexec HOME=/Users/youchain-y LOGNAME=youchain-y CGO_LDFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -miphoneos-version-min=11.0 -arch arm64 SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ed6iUipEst/Listeners XPC_FLAGS=0x0 CGO_CXXFLAGS_ALLOW=.* ANDROID_HOME=/Users/youchain-y/Library/Android/sdk SHELL=/bin/bash _INTELLIJ_FORCE_SET_PATH=/Users/youchain-y/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/youchain-y/Library/Android/sdk/tools:/Users/youchain-y/Library/Android/sdk/platform-tools:/Users/youchain-y/Documents/android-ndk-r10e:/Users/youchain-y/go/bin:/usr/local/Cellar/go/1.12.6/libexec/bin:/Users/youchain-y/go/bin CGO_CFLAGS_ALLOW=.* PWD=/Users/youchain-y/go/src/agent-client LC_CTYPE=zh_CN.UTF-8 CGO_ENABLED=1 PATH=/Users/youchain-y/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/youchain-y/.fastlane/bin:/Users/youchain-y/Library/Android/sdk/tools:/Users/youchain-y/Library/Android/sdk/platform-tools:/Users/youchain-y/Documents/android-ndk-r10e:/Users/youchain-y/go/bin:/usr/local/Cellar/go/1.12.6/libexec/bin:/Users/youchain-y/Library/Android/sdk/tools:/Users/youchain-y/Library/Android/sdk/platform-tools:/Users/youchain-y/Documents/android-ndk-r10e:/Users/youchain-y/go/bin:/usr/local/Cellar/go/1.12.6/libexec/bin TMPDIR=/var/folders/y5/zq0rjb2s7ggc_y4qk8k45k440000gn/T/ Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.xplLAf4xMx/Render CGO_CPPFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -miphoneos-version-min=11.0 -arch arm64 USER=youchain-y __CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34 XPC_SERVICE_NAME=0" error="exit status 2" name="build for ios on darwin"
runtime/cgo
github.com/shirou/gopsutil/disk
github.com/shirou/gopsutil/mem
github.com/therecipe/qt/core
net
github.com/therecipe/qt/gui
github.com/therecipe/qt/widgets
os/user
# github.com/shirou/gopsutil/disk
In file included from ../github.com/shirou/gopsutil/disk/disk_darwin_cgo.go:24:
./disk_darwin.h:2:10: fatal error: 'IOKit/IOKitLib.h' file not found
#include <IOKit/IOKitLib.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
# agent-client/model/data
moc.cpp:118:7: warning: 'RewardListModel3cf468::setData' hides overloaded virtual function [-Woverloaded-virtual]
/Users/youchain-y/Qt/5.12.0/ios/include/QtCore/qabstractitemmodel.h:192:30: note: hidden overloaded virtual function 'QAbstractItemModel::setData' declared here: different number of parameters (3 vs 1)
agent-client/model/data

**Comment by therecipe** [comment]
Hey

It looks like `github.com/shirou/gopsutil` is not supporting iOS.
I looked into this and there seems to be no `IOKitLib.h` in `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/IOKit.framework`

You will probably need to open an issue on `github.com/shirou/gopsutil` to get this solved.
