### ISSUE TITLE
How to call the method of oc(ios)

### ISSUE THREAD

**Issue by YUSHEN2015** [therecipe/qt#884]
1. How to call the method of oc
2. How to add ios framework

**Comment by YUSHEN2015** [comment]
and, how to ios mix programming like QtCreator with cpp

**Comment by therecipe** [comment]
Hey

Here is an example that shows you how to mix go and c++ code: https://github.com/therecipe/qt/tree/master/internal/examples/3rdparty/qzxing

To build it, you will need to run the `init.go` file once.
Then you can build the `demo/QZXingLive` example with qtdeploy for the desktop or for iOS with
`qtdeploy build ios`

If you want to know how to mix objective-c and go, then maybe take a look here: https://github.com/therecipe/qt/tree/master/internal/examples/3rdparty/sparkle

**Comment by YUSHEN2015** [comment]
Thank you for taking the time.

**Comment by notatestuser** [comment]
Hey @therecipe, thanks for the pointers in this issue. We are trying to do a similar thing.

A basic requirement for our app is to store some data in the iOS Keychain, but this appears to only be possible from Objective-C/Swift.

My (naive) interpretation of this example is that anything in `darwin` is copied into the Xcode project. If that is true, we should be able to reference Security.framework from Objective-C via a symlink or by copying over the framework.

And I've noticed that, in this example, the Framework is placed into `darwin/Contents` by the init script, but that path does not appear to be the same for iOS. I am hoping that it's just a different directory name :P

Do you think this approach could work?
