### ISSUE TITLE
howto add application icon  for mac app.

### ISSUE THREAD

**Issue by zsdevX** [therecipe/qt#886]
Here's my problem:

```
in my logo.rc:
 rsrc -ico qml/logo.ico -o logo.syso
and
${GOPATH}/bin/qtdeploy build desktop
```
but, in deploy/darwin, the application has no icon.

**Comment by amlwwalker** [comment]
What you have is for a Windows icon

See here for mac https://github.com/therecipe/qt/wiki/Setting-the-Application-Icon#macos
