### ISSUE TITLE
Final app size is quite large

### ISSUE THREAD

**Issue by avinassh** [therecipe/qt#887]
Details:

- Host OS - Mac OS X Mojave (10.14.2 (18C54))
- Target OS - Mac 
- qt version - current master brach (be44906910f46e7d43b928c84a099ad433d103c7)

I installed using [Fast Track Method](https://github.com/therecipe/qt/wiki/Installation-on-macOS#fast-track-version) (In GOPATH mode)

Then I built the example lineedit app from the repo (internal/examples/widgets/line_edits/) by running:

    qtdeploy build desktop

The final app size is 24.8MB! 

What I am doing wrong? Anyway to reduce the binary size?

**Comment by bh90210** [comment]
There is nothing you do wrong. This is expected. I guess others will point out a couple of things you can do to reduce the size, but in using a binding such "behavior" is expected I am afraid.

**Comment by therecipe** [comment]
Hey

Yeah, like bh90210 said this size is expected, but what you could do would be to remove unneeded plugins or frameworks from the `*.app`, since the program used to bundle these (`macdeployqt`) is far from perfect and attempts to bundle more than is necessary in most cases.
But you probably won't save that much that way (around 4mb or so I think).

What you could however do to reduce the size drastically, would be to build a static version of Qt and use that instead, that way you might halve the final `*.app` size.

On the other side, one thing to keep in mind is that these 25mb are already containing every function of the `core, gui and widgets` packages and that if you don't start to import other Qt packages, then your application size should only grow slowly from this point.

**Comment by avinassh** [comment]
> What you could however do to reduce the size drastically, would be to build a static version of Qt and use that instead, that way you might halve the final *.app size.

can you tell me how?

**Comment by therecipe** [comment]
Something like this should work:
```bash
#compile Qt
git clone -q --depth 1 -b 5.12.4 --recursive https://code.qt.io/qt/qt5.git
cd qt5
./configure -prefix $(go env GOPATH)/src/github.com/therecipe/qt_static -opensource -confirm-license -release -nomake tests -nomake examples -qt-zlib -qt-libjpeg -qt-libpng -platform macx-clang -sysconfdir /Library/Preferences/Qt -dbus-runtime -static -optimize-size -skip qtwebengine -skip qtfeedback
make -j 8 && make install -j 8

#setup the binding
export QT_QMAKE_DIR=$(go env GOPATH)/src/github.com/therecipe/qt_static/bin
export QT_STATIC=true
export QT_API=5.12.0
$(go env GOPATH)/bin/qtsetup
```

I just tested it and the final *.app size for the line edits example was about 16mb.
With [lto](https://blog.qt.io/blog/2019/01/02/qt-applications-lto/) enabled (by simply adding the `-ltcg` flag during the configuration step) you can get it down to 14mb, but the compilation of the example will take way longer.

Also for this to properly work you will need to update to https://github.com/therecipe/qt/commit/83311ce9ed9240af9538ee40a05707e135b326bc

**Comment by avinassh** [comment]
Thank you!

**Comment by yuche** [comment]
> Something like this should work:
> 
> ```shell
> #compile Qt
> git clone -q --depth 1 -b 5.12.4 --recursive https://code.qt.io/qt/qt5.git
> cd qt5
> ./configure -prefix $(go env GOPATH)/src/github.com/therecipe/qt_static -opensource -confirm-license -release -nomake tests -nomake examples -qt-zlib -qt-libjpeg -qt-libpng -platform macx-clang -sysconfdir /Library/Preferences/Qt -dbus-runtime -static -optimize-size -skip qtwebengine -skip qtfeedback
> make -j 8 && make install -j 8
> 
> #setup the binding
> export QT_QMAKE_DIR=$(go env GOPATH)/src/github.com/therecipe/qt_static/bin
> export QT_STATIC=true
> export QT_API=5.12.0
> $(go env GOPATH)/bin/qtsetup
> ```
> 
> I just tested it and the final *.app size for the line edits example was about 16mb.
> With [lto](https://blog.qt.io/blog/2019/01/02/qt-applications-lto/) enabled (by simply adding the `-ltcg` flag during the configuration step) you can get it down to 14mb, but the compilation of the example will take way longer.
> 
> Also for this to properly work you will need to update to [83311ce](https://github.com/therecipe/qt/commit/83311ce9ed9240af9538ee40a05707e135b326bc)

@therecipe 

Follow this instruction, `internal/examples/widgets/textedit` can not be executed in macOS, and `qtdeploy` command no error shows up.

Also, `qtwebengine`can't be installed during the `qtsetup` process, since [webengine can't be built statically](https://stackoverflow.com/questions/37093711/static-build-of-qtwebengine-dependent-application). Can we dynamic link `qtwebengine` module while all other modules static linked.

**Comment by jxltom** [comment]
> Something like this should work:
> 
> ```shell
> #compile Qt
> git clone -q --depth 1 -b 5.12.4 --recursive https://code.qt.io/qt/qt5.git
> cd qt5
> ./configure -prefix $(go env GOPATH)/src/github.com/therecipe/qt_static -opensource -confirm-license -release -nomake tests -nomake examples -qt-zlib -qt-libjpeg -qt-libpng -platform macx-clang -sysconfdir /Library/Preferences/Qt -dbus-runtime -static -optimize-size -skip qtwebengine -skip qtfeedback
> make -j 8 && make install -j 8
> 
> #setup the binding
> export QT_QMAKE_DIR=$(go env GOPATH)/src/github.com/therecipe/qt_static/bin
> export QT_STATIC=true
> export QT_API=5.12.0
> $(go env GOPATH)/bin/qtsetup
> ```
> 
> I just tested it and the final *.app size for the line edits example was about 16mb.
> With [lto](https://blog.qt.io/blog/2019/01/02/qt-applications-lto/) enabled (by simply adding the `-ltcg` flag during the configuration step) you can get it down to 14mb, but the compilation of the example will take way longer.
> 
> Also for this to properly work you will need to update to [83311ce](https://github.com/therecipe/qt/commit/83311ce9ed9240af9538ee40a05707e135b326bc)

Hi @therecipe , I'm curious could this method (ltcg) also be applied to windows static docker image to make the final deployed app smaller?

**Comment by therecipe** [comment]
Hey @jxltom 
I tried to get something working real quick:
```diff
diff --git a/internal/docker/windows_64_static/Dockerfile.base b/internal/docker/windows_64_static/Dockerfile.base
index 144649f7..f2b82ebf 100644
--- a/internal/docker/windows_64_static/Dockerfile.base
+++ b/internal/docker/windows_64_static/Dockerfile.base
@@ -1,7 +1,7 @@
 FROM ubuntu:16.04 as base
 
 RUN apt-get -qq update && apt-get --no-install-recommends -qq -y install ca-certificates git
-RUN git clone -q --depth 1 https://github.com/mxe/mxe.git /usr/lib/mxe
+RUN git clone -q --depth 1 https://github.com/mxe/mxe.git /usr/lib/mxe && sed -i -e 's/-opensource/-opensource -ltcg/g' /usr/lib/mxe/src/qtbase.mk
 RUN apt-get -qq update && apt-get --no-install-recommends -qq -y install autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool libc6-dev-i386 libgdk-pixbuf2.0-dev libltdl-dev libssl-dev libtool-bin libxml-parser-perl make openssl p7zip-full patch perl pkg-config python ruby scons sed unzip wget xz-utils lzip
 
 RUN cd /usr/lib/mxe && make -j $(grep -c ^processor /proc/cpuinfo) MXE_TARGETS='x86_64-w64-mingw32.static' qt5 && rm -rf /usr/lib/mxe/log && rm -rf /usr/lib/mxe/pkg
```

But the compilation did fail for some reason

```
...
[build]       freetype               x86_64-w64-mingw32.static
[done]        freetype               x86_64-w64-mingw32.static                              26944 KiB      0m38.808s
[done]        postgresql             x86_64-w64-mingw32.static                              233368 KiB     6m43.157s
[build]       qtbase                 x86_64-w64-mingw32.static

Failed to build package qtbase for target x86_64-w64-mingw32.static!
------------------------------------------------------------
Makefile:38: recipe for target 'release' failed
make[2]: *** [release] Error 2
make[2]: Leaving directory '/usr/lib/mxe/tmp-qtbase-x86_64-w64-mingw32.static/qtbase-everywhere-src-5.13.1/test-qt'
Makefile:813: recipe for target 'build-only-qtbase_x86_64-w64-mingw32.static' failed
make[1]: *** [build-only-qtbase_x86_64-w64-mingw32.static] Error 2
make[1]: Leaving directory '/usr/lib/mxe'
real	24m58.470s
user	57m40.210s
sys	10m26.130s
------------------------------------------------------------
[log]      /usr/lib/mxe/log/qtbase_x86_64-w64-mingw32.static

Makefile:813: recipe for target '/usr/lib/mxe/usr/x86_64-w64-mingw32.static/installed/qtbase' failed
make: *** [/usr/lib/mxe/usr/x86_64-w64-mingw32.static/installed/qtbase] Error 1
```

**Comment by jxltom** [comment]
@therecipe Thanks!
