### ISSUE TITLE
howto setup autorun  in window

### ISSUE THREAD

**Issue by zsdevX** [therecipe/qt#888]
Howto  make a autoRun program in windows? where should I find api for write the entry:

```
HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run
```

**Comment by zsdevX** [comment]
I solved by using:

```
"github.com/golang/sys/windows/registry"
```

**Comment by therecipe** [comment]
Thanks for update! :)
And for the reference, it seems like one can use QSettings to access the windows registry as well: https://doc.qt.io/qt-5/qsettings.html#accessing-the-windows-registry-directly
