### ISSUE TITLE
How to use QTextLayout::draw

### ISSUE THREAD

**Issue by akiyosi** [therecipe/qt#891]
Hi,
I'm looking for a way to draw lots of text faster, and I'll try the implementation introduced in the following stackOverflow entry.

 https://stackoverflow.com/a/40476430/9572800

This implementation uses QMap, but I do not know how to translate it to Go with `therecipe/qt` lib.
I would be glad to get some advice.

Also, I looks like this implementation generates `QPainter` through `QImage` pointer `&glyph`.
Does this generating is the same apploach as using `NewQPainterFromPointer`?

**Comment by akiyosi** [comment]
> Also, I looks like this implementation generates QPainter through QImage pointer &glyph.
> Does this generating is the same apploach as using NewQPainterFromPointer?

Oh, `QImage` is a type that is inherited from `QPaintDevice`, so I realized now that it can be generated with `NewQPainter2`.

**Comment by therecipe** [comment]
Yeah it would translate to `p = gui.NewQPainter2(glyph)`, I think

**Comment by akiyosi** [comment]
thank you!
I also realizeed that the `QMap` is not need it. I use `map` in Go.

By the way, I also wanted to try implementation with `QTextLayout::draw` in drawing a lots of text. But `QTextLayout::draw` does not appear to generate in this binding. 
Is it a problem specific to my environment?

**Comment by therecipe** [comment]
This seems to be related to https://github.com/therecipe/qt/issues/416 and will probably take a while to figure out.
I'm afraid that I can't look into this as I'm on vacation for at least the next 2-3 weeks, but I will try to look into this once I'm back.

In the meantime maybe something like this works for you.
(I haven't really tested it though)

`main.go`
```go
package main

//#include <stdint.h>
//#include "draw.h"
import "C"
import (
	"os"
	"unsafe"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
)

//this is needed to compile custom c++ code at the moment
type stub struct{ core.QObject }

//go:linkname QTextLayout__formats_newList github.com/therecipe/qt/gui.(*QTextLayout).__formats_newList
func QTextLayout__formats_newList(*gui.QTextLayout) unsafe.Pointer

func QTextLayout__formats_setList(l unsafe.Pointer, v *gui.QTextCharFormat, length int, start int) {
	C.QTextLayout__formats_setList(l, v.Pointer(), C.int(length), C.int(start))
}

func QTextLayout_draw(ptr *gui.QTextLayout, painter *gui.QPainter, pos *core.QPointF, l unsafe.Pointer, clip *core.QRectF) {
	C.QTextLayout_draw(ptr.Pointer(), painter.Pointer(), pos.Pointer(), l, clip.Pointer())
}

func main() {
	gui.NewQGuiApplication(len(os.Args), os.Args)

	l := QTextLayout__formats_newList(new(gui.QTextLayout))
	QTextLayout__formats_setList(l, gui.NewQTextCharFormat(), 1, 0)

	layout := gui.NewQTextLayout()
	QTextLayout_draw(layout, gui.NewQPainter(), core.NewQPointF(), l, core.NewQRectF())
}
```

`draw.h`
```go


#pragma once

#ifndef GO_DRAW_H
#define GO_DRAW_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void QTextLayout__formats_setList(void* l, void* v, int length, int start);
void QTextLayout_draw(void* ptr, void *p, void* pos, void* selections, void* clip);

#ifdef __cplusplus
}
#endif

#endif
```

`draw.cpp`
```go

#include "draw.h"

#include <QVector>
#include <QTextLayout>
#include <QTextCharFormat>
#include <QPainter>
#include <QPointF>
#include <QRectF>


void QTextLayout__formats_setList(void* l, void* v, int length, int start)
{
	static_cast<QVector<QTextLayout::FormatRange>*>(l)->append({ start, length, *static_cast<QTextCharFormat*>(v) });
}

void QTextLayout_draw(void* ptr, void *p, void* pos, void* selections, void* clip)
{
	static_cast<QTextLayout*>(ptr)->draw(static_cast<QPainter*>(p), *static_cast<QPointF*>(pos), *static_cast<QVector<QTextLayout::FormatRange>*>(selections), *static_cast<QRectF*>(clip));
}
```

**Comment by akiyosi** [comment]
Thanks for the code example. I am very grateful.
I will try.

Please enjoy your vacation :)

**Comment by akiyosi** [comment]
The code sample works and the issue closes.
Thank you.
