### ISSUE TITLE
Do you change the APIs?

### ISSUE THREAD

**Issue by rocket049** [therecipe/qt#894]
I got some error report about `QGridLayout.AddWidget` when I compile my old program with new docker `windows_32_static`.

errors:
```
./editor.go:241:16: too many arguments in call to grid.QLayout.AddWidget
	have (*widgets.QLabel, number, number, number)
	want (widgets.QWidget_ITF)
./editor.go:257:16: too many arguments in call to grid.QLayout.AddWidget
	have (*widgets.QLineEdit, number, number, number)
	want (widgets.QWidget_ITF)
```

**Comment by amlwwalker** [comment]
If you see commit 9e0d30121645ef928ee504958d1548996c30396d it does suggest there have beeb breaking changes with previous versions so some apps do need updates if you want to recompile them.

**Comment by rocket049** [comment]
@amlwwalker thanks.
