### ISSUE TITLE
QWidget CustomContextMenuRequested signal

### ISSUE THREAD

**Issue by jonywtf** [therecipe/qt#9]
Hi, help me please!
How can i use custom context menu with QTreeWidget?
I can't find ConnectCustomContextMenuRequested method.
Thanks!

**Comment by jonywtf** [comment]
And i can't find http://doc.qt.io/qt-5/qtreewidget.html#selectedItems method

**Comment by jonywtf** [comment]
and http://doc.qt.io/qt-4.8/qwidget.html#dropEvent
How can i use events?

**Comment by therecipe** [comment]
Hey

I added the ability to override impure virtual functions that return void, so you should be able to override functions similar to this one http://doc.qt.io/qt-5/qwidget.html#dropEvent.
And http://doc.qt.io/qt-5/qwidget.html#customContextMenuRequested should be available now also.

But http://doc.qt.io/qt-5/qtreewidget.html#selectedItems and all other functions that return `QList<T>` are currently not available.

I will keep this open until I added the `QList<T>` functions, full (pure and impure) virtual function support + abstract class constructors + functions for the default impure implementations and the ability to override virtual functions in subclasses.

**Comment by therecipe** [comment]
Everything but generic list is implemented.
