### ISSUE TITLE
Usage with systray?

### ISSUE THREAD

**Issue by MostHated** [therecipe/qt#901]
Hey there,
    I the majority of my application is meant to run as a background app and I was hoping to use this package to create the configuration windows and different things. I had been using http://github.com/getlantern/systray to handle the running of the application on the system tray, but seem to be having issue where when I actually bring up a window, it displays just fine but I can't interact with it, and then after a few seconds it hangs up and wants to force close. 

Am I going to have issues trying to use this package as a tray application? I have tried one or two other gui's and one of them was unable to work as a tray app (wails), so I just wanted to make sure this is capable of doing this in the first place before I go much further into figuring out what the issue is.

Thanks!
-MH

**Comment by therecipe** [comment]
Hey

Yes, you can use this package for systray applications.
One example can be found here https://github.com/therecipe/qt/blob/master/internal/examples/widgets/systray/systray.go and another one here https://github.com/therecipe/qt/issues/774#issuecomment-456490977
