### ISSUE TITLE
Some of the methods of QWebEnginePage has disappeared

### ISSUE THREAD

**Issue by akiyosi** [therecipe/qt#912]
Hi,
I installed Qt 5.13.0 and updated the binding, some methods of QWebEnginePage disappeared.
e.g.
```
webengine.go:

func NewQWebEngineView
func NewQWebEnginePage
func NewQWebChannel

func (ptr *QWebEnginePage) SetHtml
func (ptr *QWebEnginePage) SetWebChannel
func (ptr *QWebEnginePage) RunJavaScript
```

The latest change is a breaking change, but is the intention of losing the above method?
Also, I would be glad to get advice on alternatives to these methods.

**Comment by therecipe** [comment]
Hey

Sorry, these methods were somehow falsely labeled as private in the new index files.
I manually made them public again, and they should be available now with https://github.com/therecipe/qt/commit/37b08fcec7033f4e3ba23a8ed5e1320e277d094d#diff-ed48c47c1c28a43f8dc117828d9af84f

Please let me know, if there are any other functions suddenly missing as well.

**Comment by akiyosi** [comment]
Thank you😀

I then tried the latest bindings and get the following error:
```
../../editor/markdown.go:41:20: undefined: webengine.NewQWebEngineView
../../editor/markdown.go:42:20: undefined: webengine.NewQWebEnginePage
../../editor/markdown.go:89:11: m.webview.SetPage undefined (type *webengine.QWebEngineView has no field or method SetPage)
../../editor/markdown.go:91:13: undefined: webchannel.NewQWebChannel
```

**Comment by akiyosi** [comment]
I tried the latest bindings and It's works!
Thank you.

**Comment by therecipe** [comment]
You are welcome, thanks for letting me know it works :)
Also sorry that I forgot to let you know, when I pushed the changes.
