### ISSUE TITLE
dwapi

### ISSUE THREAD

**Issue by zsdevX** [therecipe/qt#925]
missing dwapi.dll in XP.

is there a good way to solve this?

thx.

**Comment by therecipe** [comment]
Hey

For WinXP deployments you can use the `windows_32_shared_xp` image, which contains Go 1.10.8 and Qt 5.6.3, newer versions of Go and Qt are sadly no longer supporting XP.

**Comment by zsdevX** [comment]
> Hey
> 
> For WinXP deployments you can use the `windows_32_shared_xp` image, which contains Go 1.10.8 and Qt 5.6.3, newer versions of Go and Qt are sadly no longer supporting XP.

Thank for you reply, really.
