### ISSUE TITLE
windows msys2 qtsetup fatal error

### ISSUE THREAD

**Issue by kaiping-liu** [therecipe/qt#929]
hello I get this error when running qtsetup.exe in msys2, how can I fix it?
go1.12.7
qt5.13.0

> time="2019-08-12T16:15:25+08:00" level=info msg="running: 'qtsetup install windows' [docker=false] [vagrant=false]"
time="2019-08-12T16:15:25+08:00" level=info msg="installing full qt/core"
github.com/therecipe/qt/core
core.cpp:39:10: fatal error: QConcatenateTablesProxyModel: No such file or directory
   39 | #include <QConcatenateTablesProxyModel>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
time="2019-08-12T16:17:43+08:00" level=error msg="failed to install 'core'; aborting setup"

**Comment by therecipe** [comment]
Hey

This should be fixed now with: https://github.com/therecipe/qt/commit/0b997e8d18a6f416bf646ee24338413c33ba4237
