### ISSUE TITLE
Can constructor have some parameters?

### ISSUE THREAD

**Issue by liugangnhm** [therecipe/qt#936]
Sometimes we need some parameters in our initial function, how could we do this? Expect your response, thanks!

**Comment by therecipe** [comment]
Hey

Custom constructors are planned, but I haven't had time to work on them yet.
But in the meantime you could use something like this:

```go
package main

import "github.com/therecipe/qt/core"

type MocStruct struct {
	core.QObject

	_ func() `constructor:"init"`

	someString string
}

func (mc *MocStruct) init() {
	//some general constructor stuff
}

func (mc *MocStruct) withString(s string) *MocStruct {
	mc.someString = s
	return mc
}

func main() {
	NewMocStruct(nil).withString("someString")
}
```

**Comment by liugangnhm** [comment]
Thanks for your reply. I will leave this issue be open until the feature is done.Thanks
