### ISSUE TITLE
Android build 64 bit

### ISSUE THREAD

**Issue by chuckwagoncomputing** [therecipe/qt#942]
Android builds seem to be 32 bit only, and Google now only allows apps that have 64 bit bundled. Is there a way to do this?

**Comment by therecipe** [comment]
Hey

Yes, you just need to export `GOARCH=arm64` before running
`qtdeploy build android` or `qtdeploy -docker build android`

Also https://github.com/therecipe/qt/commit/dd09a2c3864777d9fab24db10f236e14c9057d20 should make `qtdeploy -docker build android_arm64` work as well.

The 64bit android-emulator builds on the other side aren't supported yet, but I will look into it.
