### ISSUE TITLE
Attempting to implement a (newer) more beautiful treeview - "Unable to handle unregistered datatype"

### ISSUE THREAD

**Issue by amlwwalker** [therecipe/qt#943]
Based on this [article](https://stackoverflow.com/questions/47993755/qml-treeview-display-nodes-by-levels-or-custom-delegate) 
I am trying to implement this

![gif](https://i.stack.imgur.com/pxDT5.gif)

as Qt Controls 2 doesn't have a treeview (I have a normal Qt Controls 1 treeview working fine)  I tried to follow the response's approach. In short, I get this error 
`QMetaProperty::read: Unable to handle unregistered datatype 'QAbstractItemModel*' for property 'treeController6a2f9a::treeModel'`

My structure is:
```
└── tree
    ├── qml
    │   └── Tree
    │       ├── Tree.qml
    │       ├── TreeSlide.qml
    │       └── qmldir
    └── tree.go
└── main.go
```

**main()**
```
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
	app := qml.NewQQmlApplicationEngine(nil)
	app.AddImportPath("./tree/qml")
	app.Load(core.NewQUrl3("./main.qml", 0))
	widgets.QApplication_Exec()
```

**tree.go**
```
func init() {
	treeController_QmlRegisterType2("Tree", 1, 0, "TreeController")
	fmt.Println("general intialisation")
}

type treeController struct {
	quick.QQuickItem
	_ func() `constructor:"init"`

	_ *core.QAbstractItemModel `property:"treeModel"`
}

func (t *treeController) init() {
	t.SetTreeModel(NewTreeModel())

	fmt.Println("treeController initialised")

	t.TreeModel().ConnectRowsInserted(func(*core.QModelIndex, int, int) {
		model := t.TreeModel()
		t.SetTreeModel(nil)
		t.SetTreeModel(model)
	})
}

var TreeModel *treeModel

type treeModel struct {
	*gui.QStandardItemModel
	// _       func() `signal:"Update,auto"`
}

func NewTreeModel() *core.QAbstractItemModel {
	TreeModel = &treeModel{gui.NewQStandardItemModel(nil)}
	TreeModel.ConnectRowCount(TreeModel.rowCount)
	TreeModel.ConnectData(TreeModel.data)

	rootNode := TreeModel.InvisibleRootItem()

	americaItem := gui.NewQStandardItem2("America")
	mexicoItem := gui.NewQStandardItem2("Canada")
	usaItem := gui.NewQStandardItem2("USA")
	bostonItem := gui.NewQStandardItem2("Boston")
	europeItem := gui.NewQStandardItem2("Europe")
	italyItem := gui.NewQStandardItem2("Italy")
	romeItem := gui.NewQStandardItem2("Rome")
	veronaItem := gui.NewQStandardItem2("Verona")

	rootNode.AppendRow2(americaItem)
	rootNode.AppendRow2(europeItem)
	americaItem.AppendRow2(mexicoItem)
	americaItem.AppendRow2(usaItem)
	usaItem.AppendRow2(bostonItem)
	europeItem.AppendRow2(italyItem)
	italyItem.AppendRow2(romeItem)
	italyItem.AppendRow2(veronaItem)

	fmt.Println("TreeModel ", TreeModel)
	return TreeModel.QAbstractItemModel_PTR()
}

func (t *treeModel) rowCount(parent *core.QModelIndex) int {
	return 2
}
func (t *treeModel) data(index *core.QModelIndex, role int) *core.QVariant {
	if role != int(core.Qt__DisplayRole) {
		return core.NewQVariant()
	}
	return core.NewQVariant1(index.Row())
}

```
**Tree.qml**
```
import QtQuick 2.6
import QtQuick.Controls 2.4
import QtQuick.Layouts 1.3

import Tree 1.0
import "."
TreeController {
  ListView {
    Layout.fillHeight: true
    Layout.fillWidth: true
    model: treeModel
    clip: true
    snapMode: ListView.SnapToItem

    property var rootIndex

    delegate: ItemDelegate {
        property var modelIndex: treeModel.index(index,0, rootIndex)
        property bool hasChildren: treeModel.hasChildren(modelIndex)
        width: parent.width
        text: treeModel.data(modelIndex)
        onClicked: {
            if(hasChildren)
            {
                // Recursively add another TreeSlide, with a new rootIndex
                stackView.push("TreeSlide.qml", {rootIndex: modelIndex})
            }
        }
    }
  }
}
```

**TreeSlide.qml**
```
import QtQuick.Controls 2.4 //Menu
import QtQuick.Dialogs 1.2  //MessageDialog
import QtQuick.Layouts 1.3  //GridLayout
import QtQuick 2.2

ListView {
    Layout.fillHeight: true
    Layout.fillWidth: true
    model: treeModel.rowCount(rootIndex)
    clip: true
    snapMode: ListView.SnapToItem

    property var rootIndex

    onRootIndexChanged: {
        if(treeModel.canFetchMore(rootIndex))
            treeModel.fetchMore(rootIndex)
    }
    Connections {
        target: treeModel
        onRowsInserted: {
            rootIndexChanged()
        }
    }

    delegate: ItemDelegate {
        property var modelIndex: treeModel.index(index,0, rootIndex)
        property bool hasChildren: treeModel.hasChildren(modelIndex)
        width: parent.width
        text: treeModel.data(modelIndex)
        onClicked: {
            if(hasChildren)
            {
                // Recursively add another TreeSlide, with a new rootIndex
                stackView.push("TreeSlide.qml", {rootIndex: modelIndex})
            }
        }
    }
}
```

I can't figure out why, as I understand it, Qml cant see the treeModel. 
This would be quite a lovely way to view trees :)

It seems there must be a better way than loading the stack child from a qml file for something like this where the child comes from a model and is merely a case of specifying the fields from the child on a delegate?

**Comment by therecipe** [comment]
Hey

I looked into this, but couldn't get the `TreeSlide.qml` to properly load here:
```go
stackView.push("TreeSlide.qml", {rootIndex: modelIndex})
```

I was however able to use the `treeModel` property without any issues. 

When does the `QMetaProperty::read: Unable to handle unregistered datatype ...` error come up for you?
Do you maybe use the property from another go routine or something?

Also maybe try to use 
```go
_ *gui.QStandardItemModel `property:"treeModel"`
```
or
```go
_ *core.QObject `property:"treeModel"`
```
or maybe make the treeModel a moc struct.

Also do you passively include the `tree` package with something like:
`import _ "github.com/therecipe/tree_example/tree"`
from your main.go?

>It seems there must be a better way than loading the stack child from a qml file for something like this where the child comes from a model and is merely a case of specifying the fields from the child on a delegate?

I'm not sure I fully understand, but you can probably also change the `rootIndex` instead of pushing a new view on the stackview. If everything is setup up correctly then the `ItemDelegate` might re-evaluate itself and display the content of the child.
And then to move "up" again, you could set the `rootIndex` to the parent of the current `rootIndex`. But I'm not sure how well this would work out in practice.

**Comment by amlwwalker** [comment]
Hmm, thanks for taking a look. I have pushed the example to git (should have done that originally)
https://github.com/amlwwalker/qml-tree-stack

I just ran that three or four times:

![image](https://user-images.githubusercontent.com/2920180/63983090-187d3800-cabd-11e9-9b6a-8bbfedff090f.png)

It seems to waver between two errors as you can see, sounds like whichever gets there first basically. Is that the same thing you got (due to the `stackView.push` not working?)
I haven't tried changing the model type yet - did you have to do that to not get the error I was getting?

**Comment by therecipe** [comment]
I looked into your example, and these changes here:

```diff
diff --git a/main.go b/main.go
index 989643e..844dc87 100644
--- a/main.go
+++ b/main.go
@@ -3,7 +3,7 @@ package main
 import (
 	"os"
 
-	_ "github.com/amlwwalker/example-qml/NewTreeView/tree"
+	_ "github.com/amlwwalker/qml-tree-stack/tree"
 	"github.com/therecipe/qt/core"
 	"github.com/therecipe/qt/qml"
 	"github.com/therecipe/qt/widgets"
diff --git a/tree/qml/Tree/Tree.qml b/tree/qml/Tree/Tree.qml
index 97671fa..38dd616 100644
--- a/tree/qml/Tree/Tree.qml
+++ b/tree/qml/Tree/Tree.qml
@@ -9,15 +9,15 @@ TreeController {
     // Layout.fillHeight: true
     // Layout.fillWidth: true
     model: treeModel
-    clip: true
+    //clip: true
     snapMode: ListView.SnapToItem
 
     property var rootIndex
 
     delegate: ItemDelegate {
-        property var modelIndex: treeModel.index(index,0, rootIndex)
+        property var modelIndex: treeModel.index(index,0)
         property bool hasChildren: treeModel.hasChildren(modelIndex)
-        width: parent.width
+        //width: parent.width
         text: treeModel.data(modelIndex)
         onClicked: {
             if(hasChildren)
```
should work on this commit https://github.com/amlwwalker/qml-tree-stack/commit/089d30adb483bf1a9fd261ed04781ab600280978


I think the main issue is probably caused by using
` property var modelIndex: treeModel.index(index,0, rootIndex)`
because all the warnings I get disappear once I change it to
` property var modelIndex: treeModel.index(index,0)`

The warnings I would get otherwise are these here:
```
"Could not convert argument 0 at"
	 "expression for hasChildren@file:///Users/user/go/src/github.com/amlwwalker/qml-tree-stack/tree/qml/Tree/Tree.qml:19"
"Passing incompatible arguments to C++ functions from JavaScript is dangerous and deprecated."
"This will throw a JavaScript TypeError in future releases of Qt!"
"Could not convert argument 0 at"
	 "expression for text@file:///Users/user/go/src/github.com/amlwwalker/qml-tree-stack/tree/qml/Tree/Tree.qml:21"
"Passing incompatible arguments to C++ functions from JavaScript is dangerous and deprecated."
"This will throw a JavaScript TypeError in future releases of Qt!"
file:///Users/user/go/src/github.com/amlwwalker/qml-tree-stack/tree/qml/Tree/Tree.qml:18: ReferenceError: rootIndex is not defined
```

**Comment by amlwwalker** [comment]
Hmmm, 
Checked out that commit, and made those changes (only to qml for me obviously) and I still get the issue. Could I be out of date of something in /therecipe/qt ? Latest commit I have is `9e361992b5ed846ce9d71389aa59de522b39c48d` (22nd August)

**Comment by therecipe** [comment]
Strange, 9e361992b5ed846ce9d71389aa59de522b39c48d should work just fine.
Which Qt version do you use?
I'm testing it on macOS with Qt 5.13

**Comment by amlwwalker** [comment]
So I think I got this right....
When I compile, I first have to `export QT_DIR=/usr/local/opt/qt`.
Then if I do

`/usr/local/opt/qt/bin/qmake --version`
I get
```
QMake version 3.1
Using Qt version 5.12.0 in /usr/local/Cellar/qt/5.12.0/lib
```
Hmmm, I did think I was using 5.13, is the above a good test?

**Comment by therecipe** [comment]
Yes, that's a good test and yes this is what I'm seeing as well.
Strange that it didn't work with 5.12 though.

**Comment by amlwwalker** [comment]
ok cool. Updates are always worth doing!

I'm wondering why we are only seeing the first row of the list (there should be two elements there). I looked into the TreeSlide, the problem is it can't also see the model. I was trying to google how to pass a parameter into another page in a stackview

**Comment by therecipe** [comment]
Sorry, I'm off now.

But I figured that we currently only see the first row/item, because the ListView has no proper height set.
I think you will need to either anchor it, or explicitly bind the height to the height of some parent.
(`Layout.fillHeight: true` might work as well if you give the TreeController a proper height, but I'm 
not sure)

For testing something like this works though.
```
TreeController {
  ListView {
    height: 100
    ...
   }
}
```

And about passing parameters, this is simply done by passing something like this
`{rootIndex: modelIndex}` to the [push](https://doc.qt.io/qt-5/qml-qtquick-controls2-stackview.html#push-method) function.

**Comment by amlwwalker** [comment]
Yes, I had to check out aswell....

I have gone back to just trying to style a normal treeview. It's a slight shame as treeviews aren't supported in Qt Controls 2, so was hoping to find a newer and nicer looking alternative, but I can still get a treeview looking _quite_ good.

For some reason however that warning has come back

I can get the treeview working as expected from a UI perspective
![image](https://user-images.githubusercontent.com/2920180/64022024-29fe2880-cb2d-11e9-91a0-32208216daf0.png)

however that results in it firing loads and loads of 

```
	 "onCompleted@file:///Users/alex/go/src/github.com/amlwwalker/example-qml/TreeView/deploy/darwin/TreeView.app/Contents/Resources/qml/QtQuick/Controls/Private/BasicTableView.qml:545"
"Passing incompatible arguments to C++ functions from JavaScript is dangerous and deprecated."
"This will throw a JavaScript TypeError in future releases of Qt!"
```

I have no idea what I have changed to cause this. I've pushed it to the same repo - its the latest on master. The only thing I tried to change was to try and sort out roles so I could display more than just a single word (I wanted to add columns of data also):

```
	type City struct {
		*gui.QStandardItem
		Name       string `property:"name"`
		Population int64
	}
	toronto := &City{gui.NewQStandardItem(), "Toronto", 1200}
	//canadian cities
	toronto := gui.NewQStandardItem(toronto)
```
After that, the warning started appearing. I commented the above out and went back to the single word but the warning stayed... Seems like I'm definately missing something but the warning talks about code inside of Qt itself rather than mine, so hard to pin down.

To make the old TreeView a bit nicer, I was hoping to change the delegate for  row if it had no children (i.e its a leaf). In that case I would open it up more like an expanded card on other platforms to display information about it but I haven't found a way to change delegate based on a condition (except using loaders but everything I read says that is almost never the best way to go)

**Comment by amlwwalker** [comment]
I'm working on something to replace tree views using this library. I'll post somewhere when done

**Comment by therecipe** [comment]
Sorry for the delay.
If you want to get a second column working for the TreeView while using the QStandardItemModel, then you will need to create custom "roleNames" first. And then use them for the "roles" inside the TableViewColumn.

These changes should make the example work:
```diff
diff --git a/main.go b/main.go
index 01a5e0f..2fa918c 100644
--- a/main.go
+++ b/main.go
@@ -4,7 +4,7 @@ import (
 	"os"
 	"sync"
 
-	_ "github.com/amlwwalker/example-qml/TreeView/tree"
+	_ "github.com/amlwwalker/qml-tree-stack/tree"
 	"github.com/therecipe/qt/core"
 	"github.com/therecipe/qt/qml"
 	"github.com/therecipe/qt/widgets"
diff --git a/tree/qml/Tree/Tree.qml b/tree/qml/Tree/Tree.qml
index ad7c0ca..e712203 100644
--- a/tree/qml/Tree/Tree.qml
+++ b/tree/qml/Tree/Tree.qml
@@ -21,8 +21,9 @@ height: 400
                 anchors.verticalCenter: parent.verticalCenter
                 anchors.left: parent.left
                 color: "hotpink"
-                text: styleData.value 
+                text: styleData.value ? styleData.value : ""
             }
+            /*
             MouseArea {
                 anchors.fill: parent
                 onClicked: {
@@ -31,6 +32,7 @@ height: 400
                     }
                 }
             }
+            */
         }
         style: TreeViewStyle {
             branchDelegate: Rectangle {
@@ -55,8 +57,10 @@ height: 400
         TableViewColumn {
             role: "display"
         }
-        // TableViewColumn {
-        //     role: "name"
-        // }
+        TableViewColumn {
+            role: "population"
+        }
+
+        onClicked: isExpanded(index) ? collapse(index) : expand(index)
     }
 }
diff --git a/tree/tree.go b/tree/tree.go
index dac8e32..44d7e3a 100644
--- a/tree/tree.go
+++ b/tree/tree.go
@@ -23,6 +23,10 @@ type treeController struct {
 func (f *treeController) init() {
 	treeModel := gui.NewQStandardItemModel(nil)
 
+	roleNames := treeModel.RoleNames()
+	roleNames[int(core.Qt__UserRole+1)] = core.NewQByteArray2("population", -1)
+	treeModel.SetItemRoleNames(roleNames)
+
 	rootNode := treeModel.InvisibleRootItem()
 
 	americaItem := gui.NewQStandardItem2("America")
@@ -43,7 +47,9 @@ func (f *treeController) init() {
 	// toronto := &City{gui.NewQStandardItem(), "Toronto", 1200}
 	//canadian cities
 	toronto := gui.NewQStandardItem2("Toronto")
+	toronto.SetData(core.NewQVariant1(1200), int(core.Qt__UserRole+1))
 	montreal := gui.NewQStandardItem2("Montreal")
+	montreal.SetData(core.NewQVariant1(2222), int(core.Qt__UserRole+1))
 	quebeck := gui.NewQStandardItem2("Quebeck")
 
 	canadaItem.AppendRow2(montreal)
```
