### ISSUE TITLE
Android docker build is out of sync

### ISSUE THREAD

**Issue by muesli** [therecipe/qt#946]
For regular builds in master, `core.NewQVariant15` expects a `string` as a parameter. For the Android docker builds, it's `core.NewQVariant14` instead.

**Comment by therecipe** [comment]
Hey

Did you try to pull the latest android docker image with `docker pull therecipe/qt:android`?
It could be that you still use an old one with Qt 5.12

Also btw, I recently added a universal `NewQVariant1` function which accepts an interface{}, and which was created to work around this api issue.

**Comment by muesli** [comment]
Oh my, I do feel awfully stupid now. Indeed, I had an older docker image lingering around on this system and should have noticed something's wrong when it wasn't pulling any images over the network.

Sorry for the noise.

**Comment by therecipe** [comment]
No worries, my favorite issues are those that resolve themselves quickly :)
