### ISSUE TITLE
Incorrect package name, main, generated by qtmoc

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#95]
It appears that if a package name starts with `main`, then `qtmoc` generates a `moc.go` file with the package name `main`. This of course fails to build.

`mainwindow/window.go`
```go
package mainwindow

import (
  ...
```

`mainwindow/moc.go`
```go
package main

//#include <stdint.h>
...
```

**Comment by pekim** [comment]
I wonder if it's https://github.com/therecipe/qt/blob/master/cmd/qtmoc/moc.go#L103 that's responsible?

```go
			if !strings.Contains(string(src), "package main") {
```

**Comment by therecipe** [comment]
Hey

I just came back online :)

Yes, that was the problem.
It's fixed with https://github.com/therecipe/qt/commit/de96785a7480ceb2475d9a5b213198d96dc59b3b

**Comment by pekim** [comment]
Yes, that's fixed it.

Thank you very much for fixing it so quickly.

**Comment by therecipe** [comment]
You are welcome :)
