### ISSUE TITLE
Crashing when adding row to model

### ISSUE THREAD

**Issue by amlwwalker** [therecipe/qt#951]
Sorry to bring this up again, I don't think i could have tested this completely but have since closed the issue and thought it was perhaps an issue for others in its own right.

In https://github.com/therecipe/qt/issues/926 we discussed how to update the frontend model based on a backend DB.

My model

```
type sortFilterModel struct {
	*core.QSortFilterProxyModel
	viewModel *core.QAbstractItemModel
	_         func() `signal:"Update,auto"`
}
func (m *sortFilterModel) Update() {
	m.viewModel.BeginResetModel()
	m.viewModel.EndResetModel()
}
type ViewModel struct {
	*core.QAbstractTableModel
	manager *logic.Manager
}
```

Then in my controller

```
func (c *Controller) addNewFile(filepath string) {
	model.ListModel.BeginInsertRows(core.NewQModelIndex(), model.ListModel.RowCount(core.NewQModelIndex())+1, model.ListModel.RowCount(core.NewQModelIndex())+1)
	if path, err := c.manager.AddFileToMonitor(filepath, true); err != nil {
		fmt.Println("adding file "+path+" to watch errored ", err)
	}
	model.ListModel.EndInsertRows()
}
```
where `AddFileToMonitor` just adds a file to a database (and some other stuff).

The issue that occurs is (linking back to the other issue where I have a routine that informs the model that the db has changed and so calls the Update() function) is that with the above insert occuring I get a runtime error:

```
detected row inserted
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x627a057]

runtime stack:
runtime.throw(0x4599d6e, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 19 [syscall]:
runtime.cgocall(0x43f5fe0, 0xc000139e38, 0xc0fc6f00e1)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000139e08 sp=0xc000139dd0 pc=0x40090be
github.com/therecipe/qt/core._Cfunc_QAbstractItemModel_EndResetModel(0x6e48290)
	_cgo_gotypes.go:291 +0x41 fp=0xc000139e38 sp=0xc000139e08 pc=0x40d71a1
github.com/therecipe/qt/core.(*QAbstractItemModel).EndResetModel.func1(0x6e48290)
	/Users/alex/go/src/github.com/therecipe/qt/core/core-minimal.go:270 +0x56 fp=0xc000139e70 sp=0xc000139e38 pc=0x4130846
github.com/therecipe/qt/core.(*QAbstractItemModel).EndResetModel(0xc00009e180)
	/Users/alex/go/src/github.com/therecipe/qt/core/core-minimal.go:270 +0x44 fp=0xc000139e88 sp=0xc000139e70 pc=0x40f8044
github.com/amlwwalker/pickleit/gui/model.(*listModel).Update(0xc0000a4540)
	/Users/alex/go/src/github.com/amlwwalker/pickleit/gui/model/listmodel.go:28 +0x45 fp=0xc000139ea0 sp=0xc000139e88 pc=0x430c0d5
github.com/amlwwalker/pickleit/gui/controller.(*Controller).processInformationChannel(0xc0000e6000)
	/Users/alex/go/src/github.com/amlwwalker/pickleit/gui/controller/controller.go:119 +0x84 fp=0xc000139fd8 sp=0xc000139ea0 pc=0x4329a14
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000139fe0 sp=0xc000139fd8 pc=0x405d161
created by github.com/amlwwalker/pickleit/gui/controller.(*Controller).InitWith
	/Users/alex/go/src/github.com/amlwwalker/pickleit/gui/controller/controller.go:153 +0x311
```

If I remove the `Begin/End`InsertRows I don't get the crash however I get the issue that the update is not happening on the main thread:

```
QObject::connect: Cannot queue arguments of type 'QQmlChangeSet'
(Make sure 'QQmlChangeSet' is registered using qRegisterMetaType().)
```

I think the above is enough information (??)

* Adding a file to a db, prefixed by a BeginInsert, suffixed by a EndInsert
* When the file is added, a channel passes the information to the model and calls Update()
* In doing so I get the run time error....
* Without the begin/End I dont get the run time error but I get the registration error.

_Hmm on writing that, I am thinking that its possible that the Update is occuring before the EndInsert fires_ - could that cause this issue? That sounds a little painful to work around?

**Comment by therecipe** [comment]
I think you properly just forgot to subclass the QSortFilterProxyModel and so the `Update` function is never executed in the main thread. (or maybe it's the `addNewFile` function?)

The easiest way to go about this is to implement both functions with lower case names, and then only call them by their upper case names.

**Comment by amlwwalker** [comment]
👍
