### ISSUE TITLE
Setting QSG_RENDER_LOOP to basic with os.Setenv not working

### ISSUE THREAD

**Issue by l0hn** [therecipe/qt#965]
I'm trying to force QSG_RENDER_LOOP=basic at runtime by using Setenv as below:

```go
func main() {
	_ = os.Setenv("QSG_RENDER_LOOP", "basic")

	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
	gui.NewQGuiApplication(len(os.Args), os.Args)

	var app = qml.NewQQmlApplicationEngine(nil)

	app.Load(core.NewQUrl3("./main.qml", 0))
	gui.QGuiApplication_Exec()
}
```

However when the QGuiApplication runs it doesn't seem to have this environment variable.

If I restart the process after calling Setenv as follows the env var is available to the QGuiApplication, however this is not an ideal technique for obvious reasons:

```go
func main() {
	if os.Getenv("QSG_RENDER_LOOP") != "basic" {
		_ = os.Setenv("QSG_RENDER_LOOP", "basic")
		restart()
		return
	}

	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
	gui.NewQGuiApplication(len(os.Args), os.Args)

	var app = qml.NewQQmlApplicationEngine(nil)

	app.Load(core.NewQUrl3("./main.qml", 0))
	gui.QGuiApplication_Exec()
}

func restart() {
	procAttr := new(os.ProcAttr)
	procAttr.Files = []*os.File{os.Stdin, os.Stdout, os.Stderr}
	p, _ := os.StartProcess(os.Args[0], os.Args, procAttr)
	_ = p.Release()
}
```

Is there a way around this?

**Comment by l0hn** [comment]
For anyone else coming up against this I was able to solve the issues by calling _putenv_s() directly (Windows specific) using cgo instead of using os.Setenv as follows (no error handling in example):

```go
/*
#include <stdlib.h>
int setenv(const char *key, const char *val) {
	_putenv_s(key, val);
}
 */
import "C"

func main() {
	setEnv("QSG_RENDER_LOOP", "basic")

	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
	gui.NewQGuiApplication(len(os.Args), os.Args)

	var app = qml.NewQQmlApplicationEngine(nil)

	app.Load(core.NewQUrl3("./main.qml", 0))
	gui.QGuiApplication_Exec()
}

func setEnv(key string, val string) {
	ckey := C.CString(key)
	defer C.free(unsafe.Pointer(ckey))
	cval := C.CString(val)
	defer C.free(unsafe.Pointer(cval))

	C.setenv(ckey, cval)
}
```

**Comment by therecipe** [comment]
Hey

Strange that `os.Setenv` isn't properly working on windows.
I just tested it on macOS and it seems to work there just fine.

However, I added support for some of the env related QtGlobal functions (`qputenv`, `qgetenv`, ...) with https://github.com/therecipe/qt/commit/cd53818b8ffcb925d8256eb532061a6ffbdf2f4b now.

So something like this should work now as well:
`core.QtGlobal_qputenv("QSG_RENDER_LOOP", core.NewQByteArray2("basic", -1))`

**Comment by l0hn** [comment]
Yes it's also fine for me on MacOS, in-fact the reason I was trying to set this variable on Windows is because the test app I created had animations that were running much faster on Windows than MacOS.

Many thanks for adding qputenv / qgetenv I previously searched for these but couldn't see them.
