### ISSUE TITLE
Horizontal Expanding of QTextEdit

### ISSUE THREAD

**Issue by Matt-Texier** [therecipe/qt#97]
Hi Guys,

I am trying to build a basic window with HLayout made of two frames each having VLayout with couples of widgets. I would like to have an horizontal / vertical expanding text widget in my fist frame. Vertical expanding works fine but horizontal refuse to expand.

It works fine using CPP ... but I am probably missing something with he go version.

If you could have a look ... It is probably a problem in my code or this is default behavior that is different from CPP to your libraries ?

Thanks for your help,
Matt.

Here is my code:

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	var consoleWindow = widgets.NewQMainWindow(nil, 0)
	consoleWindow.Layout().DestroyQObject()
	consoleWindow.SetGeometry(core.NewQRect4(100, 100, 1000, 600))
	consoleWindow.SetWindowTitle("GoBGP Console")
	var mainLayout = widgets.NewQHBoxLayout()
    mainLayout.SetSpacing(6)
    mainLayout.SetContentsMargins(11, 11, 11, 11)
	consoleWindow.SetLayout(mainLayout)
	
	// console window widgets
	// log Frame
	var logFrame = widgets.NewQFrame(consoleWindow, 0)
	logFrame.SetFrameShape(widgets.QFrame__Panel)
    logFrame.SetFrameShadow(widgets.QFrame__Raised)
    var frameSizePolicy = widgets.NewQSizePolicy()
    frameSizePolicy.SetHorizontalPolicy(widgets.QSizePolicy__Preferred)
	frameSizePolicy.SetVerticalPolicy(widgets.QSizePolicy__Preferred)
	frameSizePolicy.SetHorizontalStretch(0)
	frameSizePolicy.SetVerticalStretch(0)
	logFrame.SetSizePolicy(frameSizePolicy)
	
	// layout for log
	var logLayout = widgets.NewQVBoxLayout()
	logLayout.SetSpacing(6);

	// Console text edit / display
	var logLabel = widgets.NewQLabel2("Console output", logFrame, 0)
	var logLabelSizePolicy = widgets.NewQSizePolicy()
	logLabelSizePolicy.SetHorizontalPolicy(widgets.QSizePolicy__Preferred)
	logLabelSizePolicy.SetVerticalPolicy(widgets.QSizePolicy__Preferred)
	logLabelSizePolicy.SetHorizontalStretch(0)
	logLabelSizePolicy.SetVerticalStretch(0)
	logLabelSizePolicy.SetHeightForWidth(logLabel.HasHeightForWidth())
	logLabel.SetSizePolicy(logLabelSizePolicy)
	logLabel.SetAlignment(core.Qt__AlignLeading|core.Qt__AlignLeft|core.Qt__AlignVCenter)
	logLayout.AddWidget(logLabel, 0, core.Qt__AlignLeft)

	var logText = widgets.NewQTextEdit(logFrame)
	var logTextSizePolicy = widgets.NewQSizePolicy()
	logTextSizePolicy.SetHorizontalPolicy(widgets.QSizePolicy__Expanding)
	logTextSizePolicy.SetVerticalPolicy(widgets.QSizePolicy__Expanding)
	logTextSizePolicy.SetHorizontalStretch(0)
	logTextSizePolicy.SetVerticalStretch(0)
	logTextSizePolicy.SetHeightForWidth(logText.HasHeightForWidth())
	logText.SetSizePolicy(logTextSizePolicy)
	logLayout.AddWidget(logText, 0, core.Qt__AlignLeft)

	logFrame.SetLayout(logLayout)
	mainLayout.AddWidget(logFrame, 0, core.Qt__AlignLeft)

	// command Frame
	var cmdFrame = widgets.NewQFrame(consoleWindow, 0)
	cmdFrame.SetFrameShape(widgets.QFrame__Panel)
    cmdFrame.SetFrameShadow(widgets.QFrame__Raised)
    cmdFrame.SetSizePolicy(frameSizePolicy)

	// push buttons
	var cmdButtonSizePolicy = widgets.NewQSizePolicy()
	cmdButtonSizePolicy.SetHorizontalPolicy(widgets.QSizePolicy__Minimum)
	cmdButtonSizePolicy.SetVerticalPolicy(widgets.QSizePolicy__Fixed)
	cmdButtonSizePolicy.SetHorizontalStretch(0)
	cmdButtonSizePolicy.SetVerticalStretch(0)
	
	var cmdLabel = widgets.NewQLabel2("Basic Commands", cmdFrame, 0)
	cmdButtonSizePolicy.SetHeightForWidth(cmdLabel.HasHeightForWidth())
	cmdLabel.SetSizePolicy(cmdButtonSizePolicy)

	var	cmdNeighButton = widgets.NewQPushButton2("Neighbors", cmdFrame)
	cmdButtonSizePolicy.SetHeightForWidth(cmdNeighButton.HasHeightForWidth())
	cmdNeighButton.SetSizePolicy(cmdButtonSizePolicy)

    var cmdFsrib4Button = widgets.NewQPushButton2("IPv4 FlowSpec RIB", cmdFrame)
    cmdButtonSizePolicy.SetHeightForWidth(cmdFsrib4Button.HasHeightForWidth())
	cmdFsrib4Button.SetSizePolicy(cmdButtonSizePolicy)

    var cmdFsrib6Button = widgets.NewQPushButton2("IPv6 FlowSpec RIB", cmdFrame)
    cmdButtonSizePolicy.SetHeightForWidth(cmdFsrib6Button.HasHeightForWidth())
	cmdFsrib6Button.SetSizePolicy(cmdButtonSizePolicy)

	// layout for buttons
	var cmdLayout = widgets.NewQVBoxLayout()
	cmdLayout.AddWidget(cmdLabel, 0, core.Qt__AlignCenter)
	cmdLayout.AddWidget(cmdNeighButton, 0, core.Qt__AlignCenter)
	cmdLayout.AddWidget(cmdFsrib4Button, 0, core.Qt__AlignCenter)
	cmdLayout.AddWidget(cmdFsrib6Button, 0, core.Qt__AlignCenter)
	var cmdVerticalSpacer = widgets.NewQSpacerItem(20, 40, widgets.QSizePolicy__Fixed, widgets.QSizePolicy__Expanding)
	cmdLayout.AddItem(cmdVerticalSpacer)
	cmdFrame.SetLayout(cmdLayout)
	mainLayout.AddWidget(cmdFrame, 0, core.Qt__AlignRight)

	consoleWindow.Show()

	widgets.QApplication_Exec()
}

**Comment by therecipe** [comment]
Hey

I haven't had time to port and test it in C++ yet, but it seems to work if you replace 

`logLayout.AddWidget(logText, 0, core.Qt__AlignLeft)`
with
`logLayout.AddWidget(logText, 0, 0)`

and

`mainLayout.AddWidget(logFrame, 0, core.Qt__AlignLeft)`
with
`mainLayout.AddWidget(logFrame, 0, 0)`

Generally the binding should behave exactly as the C++ version, so I will port this to C++ line for line to check if there is a bug that needs to be fixed.

**Comment by Matt-Texier** [comment]
Thanks :) Works.
Unless I am missing something, the C++ version doesn't ask for more parameters than the widget itself (see here under).
I tested many (if not all) existing / constant defined but none of them was working fine. I didn't imagine I should use 0 which is, as far as I can see, not a defined constant... 

Not a big deal but would be convenient to clarify how this 0 value behave.

verticalLayout->addWidget(textEdit);
horizontalLayout->addWidget(frame);

Thanks again for your help,
Matt.

**Comment by therecipe** [comment]
You are welcome :)

QtCreator will show you the function with the shortest/simplest signature first. (http://doc.qt.io/qt-5/qlayout.html#addWidget)
So you will get `(*QLayout).AddWidget(w)` suggested for (QVBoxLayout / QHBoxLayout)

With Go and code-completion you will get always the latest overriden function shown. (http://doc.qt.io/qt-5/qboxlayout.html#addWidget)
So you will get `(*QBoxLayout).AddWidget(widget, stretch, alignment)` suggested for (QVBoxLayout / QHBoxLayout)

But you can still access the overriden function from a QVBoxLayout, if you write `(*VBoxLayout).QLayout.AddWidget(w)`


About the 0, yes it's strange that it's not defined here: http://doc.qt.io/qt-5/qt.html#AlignmentFlag-enum
But it's mentioned here: http://doc.qt.io/qt-5/qboxlayout.html#addWidget

>The alignment is specified by alignment. The default alignment is 0, which means that the widget fills the entire cell.

And thats also the general rule, most times you can omit a parameter with `0` or `nil` to get the default value (if it's not specified different in the function docs).

Also I did test it with `(*VBoxLayout).QLayout.AddWidget(w)` and it works too, so I don't have to port this over :)

**Comment by Matt-Texier** [comment]
I see … thanks again for this detailed answer and advices :).

btw, thanks also for the nice framework for Qt/golang programming. 

Cheers,
Matthieu.
