### ISSUE TITLE
qtsetup failed

### ISSUE THREAD

**Issue by yunyanU** [therecipe/qt#971]
yandeMacBook-Pro:downloader yan$ qtsetup
INFO[0000] running: 'qtsetup prep'                      
INFO[0000] successfully created qtrcc symlink in your PATH (/usr/local/bin/qtrcc) 
INFO[0000] successfully created qtmoc symlink in your PATH (/usr/local/bin/qtmoc) 
INFO[0000] successfully created qtminimal symlink in your PATH (/usr/local/bin/qtminimal) 
INFO[0000] successfully created qtdeploy symlink in your PATH (/usr/local/bin/qtdeploy) 
INFO[0000] running: 'qtsetup check darwin' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                     *  'darwin'        
INFO[0000] GOARCH:                   *  'amd64'         
INFO[0000] GOVERSION:                   'go1.13'        
INFO[0000] GOROOT:                   *  '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/Users/yan/GolandProjects/downloader/vendor/github.com/therecipe/qt' 
INFO[0000] GOBIN:                    *  '/Users/yan/go/bin' 
INFO[0000] GOMOD:                       '/Users/yan/GolandProjects/downloader/go.mod' 
INFO[0000] QT_HASH:                     'a14b2a9ec416173e61e471b879e31aed03a18e5e' 
INFO[0000] QT_API:                      ''              
INFO[0000] QT_VERSION:                  '5.13.0'        
INFO[0000] QT_DIR:                      '/Users/yan/Qt' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_HOMEBREW:                 'false'         
INFO[0000] QT_MACPORTS:                 'false'         
INFO[0000] QT_NIX:                      'false'         
INFO[0000] QT_FELGO:                    'false'         
INFO[0000] XCODE_DIR:                   '/Applications/Xcode.app' 
INFO[0000] QT_PKG_CONFIG:               'false'         
INFO[0000] running: 'qtsetup generate darwin' [docker=false] [vagrant=false] 
INFO[0005] generating full qt/core                      
INFO[0018] generating full qt/androidextras             
INFO[0018] generating full qt/gui                       
INFO[0034] generating full qt/network                   
INFO[0039] generating full qt/xml                       
INFO[0040] generating full qt/dbus                      
INFO[0042] generating full qt/nfc                       
INFO[0043] generating full qt/script                    
INFO[0044] generating full qt/sensors                   
INFO[0048] generating full qt/positioning               
INFO[0049] generating full qt/widgets                   
INFO[0086] generating full qt/sql                       
INFO[0088] generating full qt/macextras                 
INFO[0089] generating full qt/qml                       
INFO[0092] generating full qt/websockets                
INFO[0093] generating full qt/xmlpatterns               
INFO[0094] generating full qt/bluetooth                 
INFO[0097] generating full qt/webchannel                
INFO[0097] generating full qt/svg                       
INFO[0098] generating full qt/multimedia                
INFO[0114] generating full qt/quick                     
INFO[0119] generating full qt/help                      
INFO[0123] generating full qt/location                  
INFO[0124] generating full qt/scripttools               
INFO[0125] generating full qt/uitools                   
INFO[0126] generating full qt/webengine                 
INFO[0128] generating full qt/testlib                   
INFO[0129] generating full qt/serialport                
INFO[0130] generating full qt/serialbus                 
INFO[0131] generating full qt/printsupport              
INFO[0134] generating full qt/designer                  
INFO[0138] generating full qt/scxml                     
INFO[0139] generating full qt/gamepad                   
INFO[0140] generating full qt/purchasing                
INFO[0141] generating full qt/datavisualization    [GPLv3] 
INFO[0145] generating full qt/charts               [GPLv3] 
INFO[0155] generating full qt/virtualkeyboard      [GPLv3] 
INFO[0156] generating full qt/speech                    
INFO[0157] generating full qt/quickcontrols2            
INFO[0157] generating full qt/sailfish                  
INFO[0157] generating full qt/webview                   
INFO[0158] generating full qt/remoteobjects             
INFO[0159] running: 'qtsetup install darwin' [docker=false] [vagrant=false] 
INFO[0159] installing full qt/core                      
INFO[0192] installing full qt/androidextras             
INFO[0192] installing full qt/gui                       
INFO[0226] installing full qt/network                   
INFO[0238] installing full qt/xml                       
INFO[0243] installing full qt/dbus                      
INFO[0248] installing full qt/nfc                       
INFO[0251] installing full qt/script                    
INFO[0255] installing full qt/sensors                   
INFO[0264] installing full qt/positioning               
INFO[0269] installing full qt/widgets                   
INFO[0331] installing full qt/sql                       
INFO[0339] installing full qt/macextras                 
INFO[0341] installing full qt/qml                       
INFO[0347] installing full qt/websockets                
INFO[0351] installing full qt/xmlpatterns               
INFO[0354] installing full qt/bluetooth                 
INFO[0361] installing full qt/webchannel                
INFO[0363] installing full qt/svg                       
INFO[0367] installing full qt/multimedia                
INFO[0395] installing full qt/quick                     
INFO[0404] installing full qt/help                      
INFO[0413] installing full qt/location                  
INFO[0418] installing full qt/scripttools               
INFO[0420] installing full qt/uitools                   
INFO[0422] installing full qt/webengine                 
INFO[0435] installing full qt/testlib                   
INFO[0438] installing full qt/serialport                
INFO[0440] installing full qt/serialbus                 
INFO[0445] installing full qt/printsupport              
INFO[0445] installing full qt/designer                  
INFO[0454] installing full qt/scxml                     
INFO[0459] installing full qt/gamepad                   
INFO[0462] installing full qt/purchasing                
INFO[0465] installing full qt/datavisualization    [GPLv3] 
INFO[0479] installing full qt/charts               [GPLv3] 
INFO[0497] installing full qt/virtualkeyboard      [GPLv3] 
INFO[0502] installing full qt/speech                    
INFO[0505] installing full qt/quickcontrols2            
INFO[0506] installing full qt/sailfish                  
INFO[0506] installing full qt/webview                   
INFO[0508] installing full qt/remoteobjects             
INFO[0513] running: 'qtsetup test darwin' [docker=false] [vagrant=false] 
INFO[0513] testing widgets/textedit                     
ERRO[0513] failed to run command                         _func=RunCmd cmd="go list -mod=vendor -tags= -e -f {{join .TestImports \"|\"}}|{{join .XTestImports \"|\"}}|{{join .Deps \"|\"}}" dir=widgets/textedit env="TERM=xterm-256color SHELL=/bin/bash _INTELLIJ_FORCE_SET_GO111MODULE=on TMPDIR=/var/folders/yc/b2wsz3j9093dtgl5vhl4m2bm0000gn/T/ GOBIN=/Users/yan/go/bin Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.EfDWT0rrEy/Render USER=yan SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.dl2eCaLSW2/Listeners __CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34 GO111MODULE=on PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin TERMINAL_EMULATOR=JetBrains-JediTerm GOPROXY=goproxy.cn,direct _INTELLIJ_FORCE_SET_GOROOT=/usr/local/go PWD=/Users/yan/GolandProjects/downloader GOARCH=amd64 _INTELLIJ_FORCE_SET_PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin _INTELLIJ_FORCE_SET_GOPATH=/Users/yan/go XPC_FLAGS=0x0 _INTELLIJ_FORCE_SET_GOPROXY=goproxy.cn,direct XPC_SERVICE_NAME=0 SHLVL=1 HOME=/Users/yan GOROOT=/usr/local/go GOOS=darwin LOGNAME=yan LC_CTYPE=zh_CN.UTF-8 GOPATH=/Users/yan/go _=/Users/yan/go/bin/qtsetup CGO_ENABLED=0 PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin GOBIN=/Users/yan/go/bin TERMINAL_EMULATOR=JetBrains-JediTerm GOPATH=/Users/yan/go TMPDIR=/var/folders/yc/b2wsz3j9093dtgl5vhl4m2bm0000gn/T/ _INTELLIJ_FORCE_SET_GOPROXY=goproxy.cn,direct Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.EfDWT0rrEy/Render _INTELLIJ_FORCE_SET_GOROOT=/usr/local/go _=/Users/yan/go/bin/qtsetup XPC_FLAGS=0x0 LOGNAME=yan GOROOT=/usr/local/go __CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34 GOPROXY=goproxy.cn,direct _INTELLIJ_FORCE_SET_PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin TERM=xterm-256color USER=yan PWD=/Users/yan/GolandProjects/downloader SHLVL=1 GO111MODULE=on LC_CTYPE=zh_CN.UTF-8 GOOS=darwin CGO_ENABLED=1 _INTELLIJ_FORCE_SET_GO111MODULE=on SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.dl2eCaLSW2/Listeners GOARCH=amd64 GOFLAGS=-mod=vendor SHELL=/bin/bash _INTELLIJ_FORCE_SET_GOPATH=/Users/yan/go XPC_SERVICE_NAME=0 HOME=/Users/yan" error="chdir widgets/textedit: no such file or directory" name="go list deps"

**Comment by yunyanU** [comment]
when I use qtsetup test then
`yandeMacBook-Pro:downloader yan$ qtsetup test
INFO[0000] running: 'qtsetup test darwin' [docker=false] [vagrant=false] 
INFO[0000] testing showcases/wallet                     
ERRO[0000] failed to run command                         _func=RunCmd cmd="go list -mod=vendor -tags= -e -f {{join .TestImports \"|\"}}|{{join .XTestImports \"|\"}}|{{join .Deps \"|\"}}" dir=showcases/wallet env="TERM=xterm-256color SHELL=/bin/bash _INTELLIJ_FORCE_SET_GO111MODULE=on TMPDIR=/var/folders/yc/b2wsz3j9093dtgl5vhl4m2bm0000gn/T/ GOBIN=/Users/yan/go/bin Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.EfDWT0rrEy/Render USER=yan SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.dl2eCaLSW2/Listeners __CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34 GO111MODULE=on PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin TERMINAL_EMULATOR=JetBrains-JediTerm GOPROXY=goproxy.cn,direct _INTELLIJ_FORCE_SET_GOROOT=/usr/local/go PWD=/Users/yan/GolandProjects/downloader GOARCH=amd64 _INTELLIJ_FORCE_SET_PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin _INTELLIJ_FORCE_SET_GOPATH=/Users/yan/go XPC_FLAGS=0x0 _INTELLIJ_FORCE_SET_GOPROXY=goproxy.cn,direct XPC_SERVICE_NAME=0 SHLVL=1 HOME=/Users/yan GOROOT=/usr/local/go GOOS=darwin LOGNAME=yan LC_CTYPE=zh_CN.UTF-8 GOPATH=/Users/yan/go _=/Users/yan/go/bin/qtsetup CGO_ENABLED=0 Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.EfDWT0rrEy/Render GOPROXY=goproxy.cn,direct XPC_FLAGS=0x0 GOARCH=amd64 TMPDIR=/var/folders/yc/b2wsz3j9093dtgl5vhl4m2bm0000gn/T/ _INTELLIJ_FORCE_SET_GOROOT=/usr/local/go _INTELLIJ_FORCE_SET_GOPROXY=goproxy.cn,direct SHELL=/bin/bash SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.dl2eCaLSW2/Listeners LOGNAME=yan GOPATH=/Users/yan/go _INTELLIJ_FORCE_SET_GO111MODULE=on GOBIN=/Users/yan/go/bin PWD=/Users/yan/GolandProjects/downloader _INTELLIJ_FORCE_SET_GOPATH=/Users/yan/go PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin GOROOT=/usr/local/go GOFLAGS=-mod=vendor GO111MODULE=on LC_CTYPE=zh_CN.UTF-8 GOOS=darwin CGO_ENABLED=1 TERMINAL_EMULATOR=JetBrains-JediTerm XPC_SERVICE_NAME=0 _=/Users/yan/go/bin/qtsetup TERM=xterm-256color __CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34 SHLVL=1 HOME=/Users/yan USER=yan _INTELLIJ_FORCE_SET_PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin" error="chdir showcases/wallet: no such file or directory" name="go list deps"`

**Comment by therecipe** [comment]
Hey

Yeah, this can happen if you run the setup in module mode without the `-test=false` flag.
But I made some changes now with https://github.com/therecipe/qt/commit/e9f3046c7665eeb4e1578498c08a65dc615e5407 to always automatically set the flag when the setup is ran in module mode.

The setup however seems to have been successful otherwise and you should be able to use `qtdeploy` nevertheless.
