### ISSUE TITLE
How to use queued connections (core.Qt__QueuedConnection)

### ISSUE THREAD

**Issue by stdevCrow** [therecipe/qt#972]
# How to use queued connections (`core.Qt__QueuedConnection`)

This is really important to handle errors and warnings in the QML engine:

The current C++ code template that Qt Creator creates for Qt Quick (2) projects is:
```c++
#include <QGuiApplication>
#include <QQmlApplicationEngine>

int main(int argc, char *argv[])
{
    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);

    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    const QUrl url(QStringLiteral("qrc:/main.qml"));
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject *obj, const QUrl &objUrl) {
        if (!obj && url == objUrl)
            QCoreApplication::exit(-1);
    }, Qt::QueuedConnection);
    engine.load(url);

    return app.exec();
}
```
Observe that the slot is using a queued connection. As Qt docs indicates [here](https://doc.qt.io/qt-5/qcoreapplication.html#exit), a queued connection is needed in order to make `QCoreApplication::exit()` work.

**Comment by therecipe** [comment]
Hey

I haven't had this on the radar tbh, but I made some changes with https://github.com/therecipe/qt/commit/e9f3046c7665eeb4e1578498c08a65dc615e5407 and now you should be able to use the `(*QObject).ConnectSignal` function to connect the `objectCreated` signal like this:
```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/qml"
)

func main() {
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)

	app := gui.NewQGuiApplication(len(os.Args), os.Args)

	engine := qml.NewQQmlApplicationEngine(nil)

	url := core.NewQUrl3("qrc:/qml/main.qml", 0)
	engine.ConnectSignal(engine.ConnectObjectCreated, func(obj *core.QObject, objUrl *core.QUrl) {
		if obj.Pointer() == nil && url.ToString(0) == objUrl.ToString(0) {
			app.Exit(-1)
		}
	}, core.Qt__QueuedConnection)
	engine.Load(url)

	app.Exec()
}
```

I will also try to make
`engine.ConnectSignal(engine.ObjectCreated, ... ) `
and
`engine.ConnectSignal("objectCreated", ... ) `
work in the future as well.

**Comment by stdevCrow** [comment]
Hi.
Thank you for fixing it. This repository is awesome!!!

**Comment by stdevCrow** [comment]
Sorry for closing this issue prematurely. Your example code does not work. The output is:
```
engine.ConnectSignal undefined (type *qml.QQmlApplicationEngine has no field or method ConnectSignal)
```

**Comment by therecipe** [comment]
It should work with https://github.com/therecipe/qt/commit/e9f3046c7665eeb4e1578498c08a65dc615e5407 though.
Did you update the binding and re-ran the setup?
Or at least ran `$(go env GOPATH)/bin/qtsetup prep`?

**Comment by stdevCrow** [comment]
U're right. Sorry. I pull the changes but not update the wrapper correctly. Sorry. However there is another related problem. I will raise another issue.

**Comment by stdevCrow** [comment]
Well I change my mind since it is so related to this issue. It's about the non-related members of `QMetaType`: `Q_DECLARE_METATYPE` and `qRegisterMetatype<>()`. The main purpose of using queued signals is to handle errors and warninga in the `QQmlEngine` by listening to `warnings()` signal. The connection can be done now and it compiles well, but unfortunelly it raises a runtime warning `Cannot queue arguments of type QQmlError. Make sure it is registered with qRegisterMetatype()` and the slot is never executed. Also to handle custom types it is neccessary the macro `Q_DECLARE_METATYPE`. I dived into the Go wrapper and didn't found any of those. Queued connections with custom types will not work without those features.

**Comment by therecipe** [comment]
Ah, yeah you are right it seems like I forgot to properly declare various meta types.
(I only properly declared QObject derived types previously)
But I declared many more now with https://github.com/therecipe/qt/commit/6c3ac91945e60f398c591c11f6acb78ae8fc54e8, which should also make a queued `warnings()` signal work.

**Comment by stdevCrow** [comment]
Thank u very much. BTW it is possible to declare custom Meta types right now?

**Comment by therecipe** [comment]
Sadly there is no way to manually declare custom meta types due to Go's lack of generics.
I could probably find a way to make `qRegisterMetatype<T>()` work, but the solution would be pretty ugly.
However, if you just want to declare custom meta types to get them working in "custom" `signals/slots/properties` then this should work automatically already when using `qtmoc`.

**Comment by stdevCrow** [comment]
Ok. Thank u again. Closing the issue...

**Comment by therecipe** [comment]
@stdevCrow Sorry, I just remembered that you can already call `qRegisterMetatype` on your custom moc structs. To do so just call `STRUCTNAME_QRegisterMetaType()`.
It's done here for example: https://github.com/therecipe/qt/blob/master/internal/examples/quick/listview/personmodel.go#L31

If you need to have `qRegisterMetaType` work for some of the other Qt classes, then just let me know and I will look into it.
