### ISSUE TITLE
Showing/Raising a NewQQmlApplicationEngine or NewQApplication object

### ISSUE THREAD

**Issue by amlwwalker** [therecipe/qt#974]
In previous projects, I have used `var view = quick.NewQQuickView(nil)` and then been able to do `view.Show()` etc, however recently I have been using 

`qApp := widgets.NewQApplication(len(os.Args), os.Args)`
and 
`app := qml.NewQQmlApplicationEngine(nil)`
which has generally been much nicer, however these two don't seem to have a `.Show()` function available. I want to be able to click on the dock item and raise/show the window, which should be possible if I had the above `view` object available with:

```
qApp.ConnectEvent(func(e *core.QEvent) bool {
	if e.Type() == core.QEvent__ApplicationActivate {
		view.Show()
	}
	return qApp.EventDefault(e)
})
```

What is the best approach to get a handle on a window so that I can do this when I don't have a  `NewQQuickView` available?

Thanks

**Comment by therecipe** [comment]
You could either use something like this to catch the window object:
```go
var window *gui.QWindow
engine.ConnectObjectCreated(func(object *core.QObject, objUrl *core.QUrl) {
	if object.MetaObject().ClassName() == "QQuickApplicationWindow" {
		window = gui.NewQWindowFromPointer(object.Pointer())
	}
})
```
and then later use `window.Show()`

Or use something like this:
`gui.NewQWindowFromPointer(engine.RootObjects()[0].Pointer()).Show()`

**Comment by amlwwalker** [comment]
Perfect thanks.
While I'm here, before I close this question. Is there a flag, or could there be a flag to name the directory/app once its built? I'm building sometimes with virtualisation in mind and sometimes for desktop (which results in different flags) - and sometimes production/dev and it would be nice to have the binaries next to each other, rather than overwriting one and other. Also the directory I am compiling from is not necessarily the project directory and therefore the name of the compiled app is like "gui" or "interface" rather than my apps name....
