### ISSUE TITLE
qtdeploy fails with go v1.13 (go mod/vendor)

### ISSUE THREAD

**Issue by tomasger** [therecipe/qt#981]
I have a medium-sized project with quite a few dependencies involved. The project is utilizing go modules. With very minor tweaks to my code I was able to build it with `qtdeploy` on docker's `therecipe/qt:linux` (it worked with both qtdeploy's `-docker` flag on my machine and by using `qtdeploy` inside the container environment).

However, I am not content with Go inside the container as it is 1.12.9 and I'd like to be using the latest one (1.13.1). So I tried updating the Go version to the latest one inside the container. Simple projects like the examples build well with go 1.13, but my project fails to build with this error:
```
$ qtdeploy build desktop {...}
ERRO[0002] failed to run command                         _func=RunCmd cmd="go list -mod=vendor -tags= -e -f {{join .TestImports \"|\"}}|{{join .XTestImports \"|\"}}|{{join .Imports \"|\"}}" dir=/home/user/linux-app/src/vendor/google.golang.org/grpc/internal/syscall env="HOSTNAME=4ba243a09d82 TERM=xterm OLDPWD=/home/user/linux-app USER=user QT_VERSION=5.13.0 PATH=/usr/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin QT_DOCKER=true PWD=/home/user/linux-app/src SHLVL=1 HOME=/home/user GOROOT=/usr/lib/go QT_DIR=/opt/Qt GOPATH=/home/user/work _=/usr/local/bin/qtdeploy CGO_ENABLED=0 PATH=/usr/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin GOPATH=/home/user/work CGO_LDFLAGS=-Wl,-rpath,$ORIGIN/lib -Wl,--disable-new-dtags QT_DOCKER=true HOME=/home/user SHLVL=1 CGO_ENABLED=1 GOFLAGS=-mod=vendor HOSTNAME=4ba243a09d82 TERM=xterm USER=user QT_VERSION=5.13.0 GOOS=linux GOROOT=/usr/lib/go QT_DIR=/opt/Qt _=/usr/local/bin/qtdeploy GOARCH=amd64 OLDPWD=/home/user/linux-app PWD=/home/user/linux-app/src" error="exit status 1" name="go list deps"
build golang.org/x/sys/unix: cannot load golang.org/x/sys/unix: open /home/user/linux-app/src/vendor/google.golang.org/grpc/vendor/golang.org/x/sys/unix: no such file or directory
```
As you can see, qtdeploy fails on `go list deps` as it tries to find a package `golang.org/x/sys/unix`, which exists in the vendor folder. However, it is attempting to locate it inside `vendor/google.golang.org/grpc/vendor` folder (which does not exist). I found a crude way to circumvent the issue - simply copying the vendor folder to `vendor/google.golang.org/grpc/` is enough:
```
cd /home/user/linux-app/src
cp -r vendor vendor_cp
mv vendor_cp vendor/google.golang.org/grpc/vendor
```
I've tested it on several machines and it is a recurring pattern - qtdeploy works with go 1.12 and fails with the same exact error on 1.13. If any extra information is needed, I'll be happy to provide it.

**Comment by therecipe** [comment]
Hey

I looked into this, and it seems to be a Go bug.

Take a look here, it works with 1.12.9:
```dockerfile
FROM golang:1.12.9

RUN mkdir $HOME/mtest \
	&& echo "package main\nimport _ \"google.golang.org/grpc\"\nfunc main() {}" > $HOME/mtest/main.go \
	&& cd $HOME/mtest && go mod init module && go mod vendor \
	&& cd ./vendor/google.golang.org/grpc/internal/syscall \
	&& go list -mod=vendor
```

But fails with 1.13.0 and 1.13.1:
```dockerfile
FROM golang:1.13.1

RUN mkdir $HOME/mtest \
	&& echo "package main\nimport _ \"google.golang.org/grpc\"\nfunc main() {}" > $HOME/mtest/main.go \
	&& cd $HOME/mtest && go mod init module && go mod vendor \
	&& cd ./vendor/google.golang.org/grpc/internal/syscall \
	&& go list -mod=vendor
```

However, I'm probably able to work around this by passing the pkg directly to "go list" like this:
```dockerfile
FROM golang:1.13.1

RUN mkdir $HOME/mtest \
	&& echo "package main\nimport _ \"google.golang.org/grpc\"\nfunc main() {}" > $HOME/mtest/main.go \
	&& cd $HOME/mtest && go mod init module && go mod vendor \
	&& go list -mod=vendor google.golang.org/grpc/internal/syscall
```

I will look into this.

**Comment by therecipe** [comment]
https://github.com/therecipe/qt/commit/46410576ccb67679e0844dbe30e9d6cc0766ad0b should work around this now by directly passing the pkg name to "go list".

**Comment by tomasger** [comment]
Confirmed that the build no longer fails with go 1.13.1 compiler. Thank you for looking into this!
