### ISSUE TITLE
qtdeploy failed

### ISSUE THREAD

**Issue by yunyanU** [therecipe/qt#984]
when I use qtdeploy test desktop after qtsetup
` qtdeploy test desktop ./
ERRO[0001] failed to run command                         _func=RunCmd cmd="go list -mod=vendor -tags= -e -f {{join .TestImports \"|\"}}|{{join .XTestImports \"|\"}}|{{join .Imports \"|\"}}" dir=/Users/yan/GolandProjects/downloader/vendor/github.com/guonaihong/gout env="TERM=xterm-256color SHELL=/bin/bash _INTELLIJ_FORCE_SET_GO111MODULE=on TMPDIR=/var/folders/yc/b2wsz3j9093dtgl5vhl4m2bm0000gn/T/ GOBIN=/Users/yan/go/bin Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.WnwEnpZeAH/Render USER=yan SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.J7pye8MODs/Listeners __CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34 GO111MODULE=on PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin TERMINAL_EMULATOR=JetBrains-JediTerm GOPROXY=goproxy.cn,direct _INTELLIJ_FORCE_SET_GOROOT=/usr/local/go PWD=/Users/yan/GolandProjects/downloader GOARCH=amd64 _INTELLIJ_FORCE_SET_PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin _INTELLIJ_FORCE_SET_GOPATH=/Users/yan/go XPC_FLAGS=0x0 _INTELLIJ_FORCE_SET_GOPROXY=goproxy.cn,direct XPC_SERVICE_NAME=0 SHLVL=1 HOME=/Users/yan GOROOT=/usr/local/go GOOS=darwin LOGNAME=yan LC_CTYPE=zh_CN.UTF-8 GOPATH=/Users/yan/go _=/usr/local/bin/qtdeploy CGO_ENABLED=0 PWD=/Users/yan/GolandProjects/downloader XPC_FLAGS=0x0 GOFLAGS=-mod=vendor LC_CTYPE=zh_CN.UTF-8 GOARCH=amd64 GOBIN=/Users/yan/go/bin __CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34 GO111MODULE=on _INTELLIJ_FORCE_SET_GOPATH=/Users/yan/go GOOS=darwin CGO_ENABLED=1 PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin TERM=xterm-256color USER=yan _INTELLIJ_FORCE_SET_GOPROXY=goproxy.cn,direct XPC_SERVICE_NAME=0 HOME=/Users/yan _=/usr/local/bin/qtdeploy _INTELLIJ_FORCE_SET_GO111MODULE=on Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.WnwEnpZeAH/Render TERMINAL_EMULATOR=JetBrains-JediTerm _INTELLIJ_FORCE_SET_GOROOT=/usr/local/go LOGNAME=yan GOPATH=/Users/yan/go TMPDIR=/var/folders/yc/b2wsz3j9093dtgl5vhl4m2bm0000gn/T/ SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.J7pye8MODs/Listeners GOROOT=/usr/local/go GOPROXY=goproxy.cn,direct _INTELLIJ_FORCE_SET_PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/yan/go/bin:/Users/yan/go/bin SHLVL=1 SHELL=/bin/bash" error="exit status 1" name="go list deps"
build gopkg.in/yaml.v2: cannot load gopkg.in/yaml.v2: open /Users/yan/GolandProjects/downloader/vendor/github.com/guonaihong/gout/vendor/gopkg.in/yaml.v2: no such file or directory
`

but I find the directory in my vendor, not gout vendor

**Comment by therecipe** [comment]
Hey

This is probably the same Go bug, I wrote about here: https://github.com/therecipe/qt/issues/981#issuecomment-540719601
https://github.com/therecipe/qt/commit/46410576ccb67679e0844dbe30e9d6cc0766ad0b should work around this now though.

**Comment by yunyanU** [comment]
Thanks! Now qtsetup is all right in my mac, but when I use win10, always failed with
`github.com/therecipe/qt/core
# github.com/therecipe/qt/core
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in`

I know it due to gcc not right, but I use the qt provider mingw730_64, now I don't know what I can do...

**Comment by yunyanU** [comment]
Now I use msys2 gcc replace mingw,it's ok.
