### ISSUE TITLE
unknown method return type

### ISSUE THREAD

**Issue by ziflex** [therecipe/qt#989]
Hey,

Tried to find similar issue but could not.

I have a bridge and a type that the bridge returns:

```go
type Execution struct {
	core.QObject

	_ func(query string) *Result `slot:"execute"`
}

type Result struct {
	core.QObject

	_ string `property:"data"`
	_ string `property:"error"`
}

```

Whenever I execute the method, I get the following exception: ``Error: Unknown method return type: Result70e666*``.
What am I doing wrong?

**Comment by therecipe** [comment]
This should work, can you maybe try to run `go fmt && qtmoc`?
Also maybe try to remove the moc* files and re-run `qtmoc` or `qtdeploy` again.

**Comment by ziflex** [comment]
O! ``func init() { Result_QRegisterMetaType() }`` helped!
Thank you!

**Comment by therecipe** [comment]
No problem.
I should probably make `NewXYZ` call `XYZ_QRegisterMetaType()` automatically, to prevent these issues in the future.
