### ISSUE TITLE
QML TableView: Binding loop detected for property "__scrollBarTopMargin"

### ISSUE THREAD

**Issue by gravetii** [therecipe/qt#993]
I'm not sure if it's directly related to this library, but I don't want to rule it out.

I'm simply trying to create a `TableView` in my QML file, like so - 
```
TableView {
        id: resultListTableView
        anchors.fill: parent
        rowDelegate: Rectangle {
            color: "#D3D3D3"
            height: 30
        }

        itemDelegate: Rectangle {
            width: 100
            height: 50
            border.color: "#000000"
            border.width: 1
            Text {
                id: textItem
                text: styleData.value
                anchors.fill: parent
                verticalAlignment: Text.AlignVCenter
                horizontalAlignment: Text.AlignHCenter
                elide: Text.ElideRight
            }
        }

        headerDelegate: Rectangle {
            height: textItem.implicitHeight * 1.2
            width: textItem.implicitWidth
            color: "lightsteelblue"
            Text {
                id: textItem
                anchors.centerIn: parent
                text: styleData.value
                elide: Text.ElideRight
            }
        }
        
        TableViewColumn {
            role: "file"
            title: "File"
            width: resultListTableView.viewport.width * 0.3
            movable: false
            resizable: false
        }
        TableViewColumn {
            role: "type"
            title: "Type"
            width: resultListTableView.viewport.width * 0.2
            movable: false
            resizable: false
        }
        TableViewColumn {
            role: "size"
            title: "Size"
            width: resultListTableView.viewport.width * 0.2
            movable: false
            resizable: false
        }
        TableViewColumn {
            role: "path"
            title: "Path"
            width: resultListTableView.viewport.width * 0.3
            movable: false
            resizable: false
        }

        model: ResultListDataModel {}
        onDoubleClicked: {
            const element = model.get(row)
            console.log("Downloading file ", element.file, "of size", element.size)
        }
    }
```

This component is part of a `TabView` and shows up when the corresponding tab is clicked. When the tab is clicked though, I randomly get a binding loop warning:
```
QML TableView: Binding loop detected for property "__scrollBarTopMargin"
```

I'm not doing anything that might result in this binding loop, so I'm wondering where the issue is. Anybody knows what's going on here?

**Comment by gravetii** [comment]
Thanks @therecipe . Using 5.13.1 did resolve the issue.

**Comment by gravetii** [comment]
I'm sorry @therecipe . I somehow made a mistake in testing it. I get this error after performing the steps you suggested and running `qtdeploy build desktop` - 

```
ERRO[0000] failed to run command                         _func=RunCmd cmd="/Users/s0d01bw/go/src/github.com/therecipe/env_darwin_amd64_513/5.13.1/clang_64/bin/rcc -project -o /Users/s0d01bw/go/src/github.com/gravetii/qttest/rcc.qrc" dir=/Users/s0d01bw/go/src/github.com/gravetii/qttest/qml env= error="fork/exec /Users/s0d01bw/go/src/github.com/therecipe/env_darwin_amd64_513/5.13.1/clang_64/bin/rcc: no such file or directory" name="execute rcc *.qrc on darwin for darwin"
```

Any clue?

**Comment by therecipe** [comment]
Did you install Qt in a custom location? (i.e. not in `$HOME/Qt`?)
If yes, then you will need to export `QT_DIR=path/to/Qt` as well.
So in the end you will need to export both `QT_DIR=path/to/Qt` and `QT_VERSION=5.13.1`
You can then check the env variables by running `$(go env GOPATH)/bin/qtsetup check`

Also btw, moving Qt after installing it won't work.

**Comment by gravetii** [comment]
Ah, this is funny.
So, I did have 5.13.0 installed in `$HOME/Qt5.13.0`. However, when I try to upgrade it to 5.13.1 using `brew upgrade qt`, it does install, but there's nothing I can find apart from Qt5.13.0 in my home dir. Did you happen to come across something like this?

**Comment by gravetii** [comment]
I think installing Qt via Homebrew is the culprit here. I'm trying out an offline installer, will let you know if it works.

**Comment by gravetii** [comment]
Ok, so I upgraded to Qt 5.13.1 but the issue still persists. I understand that this may not be an issue with the library so I think it's wise to close the ticket and look elsewhere for the fix. But, before closing, I'd love to see if you could suspect any other issue?

**Comment by therecipe** [comment]
If you use the HomeBrew version of Qt, then you will just need to export `QT_HOMEBREW=true` and you can unset `QT_DIR` and `QT_VERSION`.
Then maybe try to re-run the setup.

**Comment by gravetii** [comment]
I discarded homebrew's installation and ran the offline installer. It now uses 5.13.1 and confirmed it using `qtsetup check` as well. Now, `qtdeploy build desktop` of my project succeeds too but the warning still persists.

**Comment by therecipe** [comment]
Sorry, I tried to reproduce it but couldn't get the warning to show up.
If it's not a Qt bug then maybe, it's either `anchors.fill: parent` in the `itemDelegate` or
`height: textItem.implicitHeight * 1.2`, `width: textItem.implicitWidth` or
`anchors.centerIn: parent` in the `headerDelegate`.

Also it seems like you used the `textItem` id twice, I doubt that's the cause but I can't tell for sure.

Could you maybe create a small example so I can reproduce it?

**Comment by gravetii** [comment]
Wow, you know what, using the `textItem` twice was the issue. Sorry for wasting so much of your time on this, it's resolved now.

Thank you for this great project, cheers!

**Comment by therecipe** [comment]
No worries, you are welcome :)
