### ISSUE TITLE
install error on macox

### ISSUE THREAD

**Issue by yifanes** [therecipe/qt#996]
## go env
go version: go1.13.1  
go mod: on
## install qt
brew install qt
## global env
export PATH="/usr/local/opt/qt/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/qt/lib"
export CPPFLAGS="-I/usr/local/opt/qt/include"
export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

export QT_HOMEBREW=true
export QT_DIR=/usr/local/Cellar/qt/5.13.1
export QT_VERSION=5.13.1
export QT_API=5.13.1
export QT_DEBUG=false                # 是否启用debug
export QT_STUB=false                 # 内存低于2Gb或32位系统才需要设置true
export QT_QMAKE_DIR=/usr/local/Cellar/qt/5.13.1/bin/qmake

## qt version
➜  mygo /usr/local/Cellar/qt/5.13.1/bin/qmake -v
QMake version 3.1
Using Qt version 5.13.1 in /usr/local/Cellar/qt/5.13.1/lib

## next
go get -v -tags=no_env github.com/therecipe/qt/cmd/...
➜  bin $GOPATH
➜  mygo $GOPATH/bin/qtsetup
ERRO[0000] invalid api version provided: '5.13.1'
valid api versions are:
➜  mygo

Can you look at it for me?  How to config The QT_API?

**Comment by therecipe** [comment]
Hey

Maybe try to export `QT_API=5.13.0` and then run
`go get -v -d github.com/therecipe/qt/internal/binding/files/docs/5.13.0` (inside your project dir with `GO111MODULE=on`) before re-running the setup.

Also, since I recently updated the wiki, the new and also way faster way to install the binding (with go modules enabled) is to run:
`go get -v github.com/therecipe/qt && go install -v -tags=no_env github.com/therecipe/qt/cmd/...`

**Comment by yifanes** [comment]
sry, The problem is still unresolved.
when `GO111MODULE=on` `QT_API=5.13.0`,
```
cd ~/
go get -v -d github.com/therecipe/qt/internal/binding/files/docs/5.13.0
go install -v -tags=no_env github.com/therecipe/qt/cmd/...
```
get:

> go: warning: "github.com/therecipe/qt/cmd/..." matched no packages

but when I :
```
export GO111MODULE=on; xcode-select --install; git clone https://github.com/therecipe/examples.git && cd ./examples && go install -v -tags=no_env github.com/therecipe/qt/cmd/... && go mod vendor && git clone https://github.com/therecipe/env_darwin_amd64_513.git vendor/github.com/therecipe/env_darwin_amd64_513 && $(go env GOPATH)/bin/qtdeploy test desktop ./basic/widgets
```
I made it, and the window came out!

**Comment by therecipe** [comment]
You will probably need to run `go get -v github.com/therecipe/qt` before `go install ...` if your `go.mod` doesn't already contain `therecipe/qt`.

So in the end you will probably need to run this:
```
go get -v github.com/therecipe/qt && go install -v -tags=no_env github.com/therecipe/qt/cmd/...
go get -v -d github.com/therecipe/qt/internal/binding/files/docs/5.13.0
```
inside your project dir containing a `go.mod` file.
(`go get -v -d ... docs/5.13.0` is probably not needed, but running it shouldn't cause trouble anyway)

**Comment by yifanes** [comment]
Wow, thanks. You solved my stupid problem.
